### ISSUE TITLE
Critical Issue

### ISSUE THREAD

**Issue by zet4** [Kwoth/NadekoBot#1]
Please fix by burning in fire.

**Comment by Kwoth** [comment]
XD

**Comment by zet4** [comment]
Please fix by drowning it in acid.

**Comment by Kwoth** [comment]
XD

**Comment by bubbie** [comment]
Please fix by deleting root directory.

**Comment by AlexFlipnote** [comment]
Please fix by giving KawaiiBot the 4th place
