### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by Smokit** [Kwoth/NadekoBot#100]
Hello,

Can you make the bot to not type communication in the main text channel and respond in different text channel that i create?. And what command do i use to make this happend, what should i type? :)

Best Regards Philip

**Comment by LawlyPopz** [comment]
btw this is for issues not help please visit https://discord.gg/0ehQwTK2RBj4mEDG for help!

**Comment by Kwoth** [comment]
No, you cannot redirect bot's messages. Just run commands in that other channel, there is no other way.

**Comment by Smokit** [comment]
i will join the server, and type in their next time i need help. Thx for the help!
