### ISSUE TITLE
Ready Check (Request)

### ISSUE THREAD

**Issue by TeRRa4** [Kwoth/NadekoBot#1000]
A feature requested by one of my clan members - a ready check system.

Simply put, someone uses a command to start a ready check and everyone else has to respond either in the affirmative or negative. I've attached a screenshot (set up using .acr's) to better demonstrate what I mean. 

If this could be limited to only the people in the voice channel of the person who started the check and with an optional variable for a timer, that would be awesome. 

Not sure how doable this is, or how sought after it is, but it would be nice. :)

![readycheck](https://cloud.githubusercontent.com/assets/25179530/22269817/e09a1174-e284-11e6-8522-acea1dd1138e.JPG)

**Comment by Kwoth** [comment]
Too specific, i don't see a wide use for it.
