### ISSUE TITLE
NSFW commands not working,

### ISSUE THREAD

**Issue by MarkisJr** [Kwoth/NadekoBot#1002]
Hi, I imported the bot via your hosting, mainly for the use of NSFW as a joke for my mates. I enabled the NSFW module but it still doesn't work? Help would be amazing!

**Comment by Kwoth** [comment]
Only ~boobs and ~butts work atm due to spam. I have to limit the usage somehow in the near future and then i'll reenable them.

**Comment by MarkisJr** [comment]
Oh ok
