### ISSUE TITLE
Bring back ~i and ~ir

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#1003]
Please bring back the `~i` and `~ir` aliases for `~img` and `~rimg`.

Thanks! 👍 

Also, thank you for sorting out #970 and #1001. 😄

**Comment by Zylon** [comment]
I believe `~img` and `~rimg` are just for Imgur, whereas `~i` and `~ir` were for google searches.
(I'd still like to see them back, but not as aliases 👌 )

**Comment by shikhir-arora** [comment]
It seems to be working fine with the latest dev branch. Remember you only get 100 Google image lookups with the standard API before it falls back, between all servers your bot is hosted on.

[~img and ~rimg working fine for Google search](http://i.imgur.com/DM7smNy.png)

**Comment by Kwoth** [comment]
no

**Comment by xnaas** [comment]
@Kwoth any particular reason *not* to have those as aliases, even though they were in the past?

**Comment by Kwoth** [comment]
because they don't fit. I and IR could be used for something else. We will have command aliases at one point, so feel free to change them to whatever you like then.

**Comment by xnaas** [comment]
>because they don't fit.

Can't say I agree. Seems like perfect shorthand for "image" and "random image" to me. 😛 

But oh well. ¯\\\_(ツ)_/¯
