### ISSUE TITLE
.prune # .clr # behaviour inconsistent

### ISSUE THREAD

**Issue by Viscerous** [Kwoth/NadekoBot#1004]
Not sure what's going on here, I suspect it has to do with the command acknowledge message, but sometimes it removes one message too many, sometimes it doesn't.

E.g. clr 1 removes either the last two messages or the last one.

**Comment by xnaas** [comment]
I would assume it's still a problem with #834. But not 100% sure on that one.

**Comment by Kwoth** [comment]
tested, can't reproduce. It removes the command + the number of messages you specified. tried with 1 and 2.

**Comment by Viscerous** [comment]
Reproducible for me: http://streamable.com/cedyf

Actually I tested it, and it has to do with .delmsgoncmd, I use this since I like to keep the chat tidy. But obviously if the bot happens to delete it before the clr/prune command is run, you'll be deleting one too many messages. If it lags a bit and clr/prune runs first, it will delete the proper amount of messages.

**Comment by Kwoth** [comment]
Ah that makes sense. Yes it would indeed conflict with delmsgoncmd.

**Comment by Kwoth** [comment]
I have and idea of a very crude way of fixing that.

**Comment by Kwoth** [comment]
Just fixed.
