### ISSUE TITLE
Acrophobia Voting Hit or Miss

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#1008]
Screenshot:
![img](http://i.imgur.com/hNI3xTZ.png)

I have up to [this commit](https://github.com/Kwoth/NadekoBot/commit/14b7aae0b026d3e1ad3d21dd5123b8a419d6391f) installed.

Did a little more testing and one of the users was able to get a vote to actually be registered if they flipped back and forth between 1 and 2 several times.

**Comment by Kwoth** [comment]
Are users invisible maybe?

**Comment by xnaas** [comment]
invisible? We're all either in DnD or Online.

**Comment by xnaas** [comment]
Just did more testing, this time it took both of our votes the first time, but we each voted for something different and there was one point in each submission but it gave someone winner randomly. 😛

**Comment by Kwoth** [comment]
Don't try to makeup some weird rules. And yes, I believe winner is chosen at random when it's a draw, that's not important.

**Comment by Kwoth** [comment]
omg. You guys are trying to vote for your own submissions aren't you. ffs.

**Comment by xnaas** [comment]
Top fucking kek, that was it. ¯\\\_(ツ)_/¯

Might add a note or something: `You can't vote for your own submission, jackass!` or whatever. 😛

**Comment by Kwoth** [comment]
I think a lot of people would agree that's common sense :D
