### ISSUE TITLE
.rrc command 

### ISSUE THREAD

**Issue by Kawaiikat14** [Kwoth/NadekoBot#1009]
Is there any way to set the minimum amount of rotating role colors from 60 to a lower number?

**Comment by xnaas** [comment]
No. The minimum is currently set to 60.

You could beg @Kwoth to change it, maybe, I guess. 😛

**Comment by Kawaiikat14** [comment]
@xnaas Maybe @Kwoth could make a config or something to change such a thing

**Comment by theoddball** [comment]
It's not a minimum it's a maximum

**Comment by Kawaiikat14** [comment]
@theoddball the command only works when set to 60 though.

**Comment by theoddball** [comment]
@kawaiikat14 
You mean the timer between changes.
That's set at 60 to prevent spamming of discord API, which would get you banned

**Comment by Kawaiikat14** [comment]
I see

**Comment by shikhir-arora** [comment]
I think he meant the minimum time for rotating roles, which is 60 seconds. It's easy to change in the code, so I suspect @Kwoth has his reasons for not making this shorter.
