### ISSUE TITLE
Enhancement: Can we get a radom fact command?

### ISSUE THREAD

**Issue by Mersenne-Prime** [Kwoth/NadekoBot#101]
That would enhance my experience ten-fold. Great bot by the way!

**Comment by Kwoth** [comment]
Don't close it, I'm planning to add it in the coming days. 

I dont care if you don't care anymore :)

**Comment by tg44** [comment]
http://numbersapi.com/

**Comment by Kwoth** [comment]
https://market.mashape.com/mishrapk12/wtf-facts# this looks good
