### ISSUE TITLE
.setname .newnm not working

### ISSUE THREAD

**Issue by plexuh** [Kwoth/NadekoBot#1016]
![fd59c7d5c8d49c5e9cfce42a3bba8198](https://cloud.githubusercontent.com/assets/25381539/22362840/ad3519e0-e41a-11e6-88e8-9c3244059089.png)

**Comment by Kwoth** [comment]
It works just tested. Make sure you've updated to the latest version 1.1.4 or 1.1.5. Also, you can change the name only twice in an hour I believe.
