### ISSUE TITLE
">cleverbot" command not working correctly.

### ISSUE THREAD

**Issue by StormSurge95** [Kwoth/NadekoBot#1017]
I'm sorry if this isn't in the correct spot...but whenever I try to use the `>cleverbot` command, it turns the cleverbot feature on and off just fine, but anytime I try to talk to the bot, it says `CommandHandler | Error in cleverbot` on the bots program window. It has the "Manage Messages" permission that it needs for the cleverbot feature, but it's still not working and I don't know why, because the guides for the bot don't have any special tutorial part for cleverbot. I just thought I might put it here in case it had something to do with the code. In any case, thank you for any help.

**Comment by Kwoth** [comment]
Update to latest version.

**Comment by StormSurge95** [comment]
Oh I see. I was using the stable version. x.x Thank you though.
