### ISSUE TITLE
NSFW commands don't work

### ISSUE THREAD

**Issue by Kawaiikat14** [Kwoth/NadekoBot#1018]
I tried VALID and actual tags in several nsfw commands but they end up "No results found"

**Comment by reddeadrex** [comment]
NSFW is broken, all the commands are broken except ~boobs and ~ass

**Comment by mikenzb** [comment]
Please see issue #1021, should be back soon.

**Comment by Kwoth** [comment]
They are not broken, they are disabled by me. refer to the issue above.
