### ISSUE TITLE
Music will not start playing

### ISSUE THREAD

**Issue by hanyuislife** [Kwoth/NadekoBot#1019]
Hello, I followed the guide step by step and everything seems to work fine until I tried to let my bot play a song from Youtube. When I type: "!!q faded" the bot will respond: "Playing song - Alan Walker - Faded", but I heard nothing. 
Then if I type: "!!nowplaying", the bot will say: "Now playing: Alan Walker - Faded Vol100% 00:00/03:33". I think that means the music did not start playing for some reason...? 
Before I had some problem with FFMPEG but I think I already fixed those problems. I restarted my computer many times, too.
I looked through the closed issues, searched on Google, and checked the FAQs but I did not found solutions to this problem.
Thank you!

**Comment by samdivaio** [comment]
Screenshot your console/ terminal with the error.

**Comment by hanyuislife** [comment]
@samdivaio Like this?
![1485702635668](https://cloud.githubusercontent.com/assets/25407207/22405105/3eb9264a-e678-11e6-8e37-49402e65369f.jpg)

**Comment by Kwoth** [comment]
You are on a 32bit system? It's not supported.

**Comment by hanyuislife** [comment]
@Kwoth Oops. So I can not use Nadekobot on a 32bit system?

**Comment by Kwoth** [comment]
Not music unless you get 32bit .dlls for libopus and libsodium and replace the current ones in NadekoBot/src/NadekoBot 🤔 I think this could be done automatically in the installers. Will ask samvaio to look into it.

**Comment by hanyuislife** [comment]
@Kwoth O..okay..?? Thank you:))!

**Comment by Kwoth** [comment]
You can try extracting this zip, and copying these files to NadekoBot/src/NadekoBot (replacing current ones)

[32bitdlls.zip](https://github.com/Kwoth/NadekoBot/files/737789/32bitdlls.zip)

**Comment by samdivaio** [comment]
Hi, can you please test this new installer on a new folder, let me know if you see 
`Your System Architecture is 32bit...`
and `Dependencies Downloaded...` I added 10secs timer to it so it should be easy to notice.
Thanks 😄 
[nadeko-with-systemarch.zip](https://github.com/Kwoth/NadekoBot/files/737831/nadeko-with-systemarch.zip)

**Comment by hanyuislife** [comment]
@Kwoth I tried and still it will not start playing... 😭 
@samdivaio I opened it and it just said: "git not found, make sure it's been installed as per the guides instructions!
Press any key to exit." (I have git installed already though..)

(Thank you guys for helping me! Usually if I ask something like this on a forum or something no one will reply or help. I'm really happy😆!)

**Comment by samdivaio** [comment]
Weird if you already have git but can you check running this command `git --version` in cmd?
It should show you not found if its environment variable path is somehow removed or charged.
If so, try reinstalling git with selecting option to use it with command prompt.
[NadekoInstaller.zip](https://github.com/Kwoth/NadekoBot/files/738633/NadekoInstaller.zip)
I have updated the installer for you, you can use two files in the zip, `NadekoInstaller.bat` to run or install ffmpeg for 32bit and same as before `Latest.bat` to install latest build of Nadeko.
