### ISSUE TITLE
Hosting on a different platform.

### ISSUE THREAD

**Issue by MarkisJr** [Kwoth/NadekoBot#1020]
Hi, I was wondering is it possible to host Nadeko bot on Raspbian? If so could I please have a few pointers on how to do so. I am new to the whole raspberry pi thing and I'm not exactly sure what I'm doing. BTW I have a Pi 3 so 4 cores, 1.2gh, 64-bit, 1gb ram. Help would be awesome!

**Comment by Kwoth** [comment]
http://nadekobot.readthedocs.io/en/latest/guides/Docker%20Guide/

Try this 👍

**Comment by MarkisJr** [comment]
Thanks! I'll try it and see if it works.

**Comment by MarkisJr** [comment]
Writing back again. I have been following all the steps to install docker on my pi but I have ran into an issue. I have updated my apt repository and now I'm onto Installing docker. The first step (updating the apt package index) worked fine but when I go to install docker I get errors like this - docker.service failed... See "bla bla bla" for details...
Error processing package docker-engine and so on. Please do not redirect me to the docker forums as they are no help because 1. When you search up the exact term it comes up with nothing. 2. I can't really wait a week for a reply and I know you guys are nice and fast when it comes to that cause you're all awesome. BTW as you can see a normal linux user could figure this out but I'm new.

**Comment by samdivaio** [comment]
Is you hardware supported? https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/

**Comment by Kwoth** [comment]
https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md you can use this to figure out how to setup dotnet and then just follow the linux guide afterwards. 

Officially you can't run nadeko on rpi, but you can try

**Comment by MarkisJr** [comment]
oh ok, thanks.
