### ISSUE TITLE
Some of the NSFW commands not working

### ISSUE THREAD

**Issue by snigelhasten** [Kwoth/NadekoBot#1021]
I've used Nadekobot for sometime now but recently all the "~hentai" commands have stopped working, but the other nsfw commands still work like "~boobs". I have tried a couple of things like reseting perms and kicking and reinviting the bot but nothing seems to work. I have no idea of what might be causing the problem so any help is much appreciated :)

**Comment by R4SH1D** [comment]
Hentai commands are stopped because they are lagging bot. Host the bot if you want to use all nsfw commands

**Comment by snigelhasten** [comment]
Hmm okay, is it temporary or permanent? the stop i mean

**Comment by R4SH1D** [comment]
Probably permanent, but im not 100% sure

**Comment by snigelhasten** [comment]
Ah okay thats sad, thanks though

**Comment by Kwoth** [comment]
It's temporary, should come back within 3 days.
