### ISSUE TITLE
Twitch Notification

### ISSUE THREAD

**Issue by ericadrayton** [Kwoth/NadekoBot#1022]
Can there be a change to the Twitch/Hitbox/Beam notifications where we can decide how much or how little information is announced? For instance showing the URL of the streamer, showing the Stream Description, also the Game being played. A command to toggle those on/off would be helpful.

**Comment by Kwoth** [comment]
There is a problem with this because all 3 apis show different info, and i just make the feature show the same amount of info the worst api gives you in order to reuse the same code.

This is already in suggestions, and will be improved in the future.
