### ISSUE TITLE
Can the web panel be managed to manage the bot?

### ISSUE THREAD

**Issue by DaYWhiTe** [Kwoth/NadekoBot#1023]
Because it's in other bots, why not?

**Comment by Kwoth** [comment]
Soon:tm: 

It's on my 400$/m goal on patreon, which should happen very soon hopefully. When it does i will devote myself fulltime to continuing the work on it, it's chugging slowly atm.

**Comment by DaYWhiTe** [comment]
I want to support you but unfortunately PayPal is not in Turkey and my card does not work in patreon
