### ISSUE TITLE
change $$$ currency name, icon

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#103]

**Comment by appelemac** [comment]
A command to do this, like $changecurrency Gems :gem: ?

**Comment by Kwoth** [comment]
nope, no command. This would be in the serverspecificconfig.

**Comment by Kwoth** [comment]
d72c809ae499a50ab4d9850cdcface8e4d91f64e

**Comment by andruxo** [comment]
how can i change currency pic? there is no file with this name

**Comment by Kwoth** [comment]
ask in #help on https://discord.gg/nadekobot server
