### ISSUE TITLE
!!maxradiobuffer Command

### ISSUE THREAD

**Issue by Kexerval** [Kwoth/NadekoBot#1030]
The concept is simple. !!maxradiobuffer will clamp the max amount that FFMPEG will buffer before stopping the current radio stream. This command would be useful for when a user leaves a voice channel for an extended amount of time. Right now, Nadeko will pause the stream, but continue to buffer until resumed. This costs disk space and CPU time for no captive audience, so this command can help optimize Nadeko as well.

Proposed Syntax: !!maxradiobuffer <int buffer_size_in_MB> or !!mrb <int>

**Comment by Kwoth** [comment]
no, it will bo done differently

**Comment by Kexerval** [comment]
For reference, Kwoth is referencing native OPUS talked about in #943
