### ISSUE TITLE
!!rcs bug

### ISSUE THREAD

**Issue by Kexerval** [Kwoth/NadekoBot#1032]
After leaving !!rcs on overnight, I noticed a bug where playback will cease and will not work without using !!destroy.
Nadeko does the following when this bug occurs:
- Nadeko will successfully buffer
- Nadeko will successfully prebuffer
- **Nadeko will read 0 bytes and restart the audio stream**
The result is no playable audio is heard and text chat is spammed with Playing Song notifications at the Guild rate limit. No exceptions are thrown. This is using a YouTube link on 1.1.5a
![image](https://cloud.githubusercontent.com/assets/12567900/22510378/be2d3446-e85f-11e6-898b-759c3ea9d40c.png)

**Comment by Kexerval** [comment]
This may take up to 8 hours to produce with a 1 minute clip but I think I may have seen spam starting as early as 2-3 hours in.

**Comment by ManuelFte** [comment]
What's that song/playlist you're trying to reproduce?

**Comment by Kexerval** [comment]
This was the exact "song" I was playing when this bug happened. Try not to think about it much: https://www.youtube.com/watch?v=BqkwLqh3Sa0

**Comment by samdivaio** [comment]
Yeah thats an issue with `!!rcs` and `!!rpl` it seems could be a memory or ffmpeg issue or both. Need investigation 
I tested discord voice lockdown thing, by making the bot leave the voice channel and rejoin every time a song starts to play (even when on loop)... that wasn't enough to fix it, only `.die` fixes it so far...

**Comment by Kexerval** [comment]
@samdivaio I just looked at my VPS graph and I noticed high outbound traffic and high CPU usage when this problem was occurring. Note the middle of the graphs is when `!!rcs` started to fail. The server is 4 vCores and I realize the CPU graph doesn't read well. The important part is that you can see when the buffer problem started and ended since no one else was playing music at the time. 
![image](https://cloud.githubusercontent.com/assets/12567900/22530210/800a5c4a-e8a8-11e6-9bb7-145c9da7bd7e.png)

**Comment by Kwoth** [comment]
#1053 for tracking music issues, most of them are the same issue
