### ISSUE TITLE
Youtube song is not found

### ISSUE THREAD

**Issue by namhohe** [Kwoth/NadekoBot#1033]
So I'm hosting a NadekoBot locally for my server, it works fine but sometime I queue a song or youtube link and nothing happen, in the cmd it says "Song is not found" without any other error. I enabled all the required API and have ffmpeg installed correctly, being able to stream song from my hdd also.

**Comment by ManuelFte** [comment]
Update your bot. That bug was solved yesterday in latest dev build (1.1.5a).

**Comment by namhohe** [comment]
Oh I just installed the bot yesterday so not realize that it's not the latest one. Will try.

**Comment by ManuelFte** [comment]
Then please close this bug report. :P
