### ISSUE TITLE
Music doesn't play despite buffering 

### ISSUE THREAD

**Issue by RubiksGamer** [Kwoth/NadekoBot#1034]
Hello, bot doesn't give any errors, I've installed ffmpeg correctly, pasted google API key correctly.
It just queues the song and plays it without sound.

**Comment by ManuelFte** [comment]
Any errors in the terminal?

**Comment by RubiksGamer** [comment]
Nothing.

**Comment by ManuelFte** [comment]
Are you using the app or the browser?

**Comment by RubiksGamer** [comment]
App.

**Comment by samdivaio** [comment]
- Check Nadeko's perms.
- Check if her volume is down manually.
- Check her volume with `!!vol` command.
- Leave the voice channel and rejoin.
- Ask your friends if they can hear Nadeko.
- Close the Discord app completely and relaunch.
- Use `.die` command.

**Comment by RubiksGamer** [comment]
Bot Has administrator privleges on server. Manual volume is up, command volume is up, rejoining the channel does nothing, my friends cant hear it, .die Has no effect either.

**Comment by samdivaio** [comment]
Change your Discord server region
Or invite to your bot to a new server ans try her music commands there
Screen shot console when you do that

**Comment by Kwoth** [comment]
#1053 for tracking music issues, most of them are the same issue
