### ISSUE TITLE
Edit trivia database

### ISSUE THREAD

**Issue by namhohe** [Kwoth/NadekoBot#1036]
I would like to edit the entire trivia database for myself, I tried to edit the data\trivia_question file but when I try to run the trivia command the trivia end right after with an error in the console saying The type initializer  for 'NadekoBot.Modules.Games.Trivia. TriviaQuestionPool' threw an exception. I don't have experience in programming so I don't really understand. Can't we manually edit the trivia question and how?

Btw all of my new question (and it's the entirely list) have one same category.

**Comment by Kwoth** [comment]
Yes. You messed up your formatting. Read up on json formatting, or make a better attempt of copying the format in which current questions are.
