### ISSUE TITLE
Autoplay (music) seems to be non-functioning

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#1039]
Screenshot:
![img](http://i.imgur.com/Qk5f72M.png)

Basically, the first song played without any hiccups and then just...nothing after it ended.

I recall seeing an issue for this on here, maybe, but I couldn't find it.

And you know me, the Discord server (US South) and bot server (in southern US) are as close to each other as possible. Also tried with two other US server locations.

**Comment by Kwoth** [comment]
reported on discord long time ago, no time yet to look into it. working on other stuff
