### ISSUE TITLE
Cannot earn nedako flowers through flower reaction as server owner

### ISSUE THREAD

**Issue by AlyssHashizawa** [Kwoth/NadekoBot#1040]
Noticed about after i updated either discord or nadeko that i wasn't able to receive nadeko flowers from the reaction event anymore. @_@

![screenshot_2](https://cloud.githubusercontent.com/assets/25089674/22569019/a508d86a-e95b-11e6-96cb-aef404334308.png)

**Comment by Kwoth** [comment]
I'm guessing you're on mobile device or web discord. You can't see the reactions. Use the app you can see reactions in. Windows desktop app works. If normal doesn't work, try beta one.
