### ISSUE TITLE
(Feature Request) Datadog Support

### ISSUE THREAD

**Issue by Kexerval** [Kwoth/NadekoBot#1041]
Datadog would help NadekoBot administrators monitor their instance with statistics such as uptime, connected servers, unique users, and more. In addition, functions and commands can be timed by Datadog and could be reported to the monitor and used by developers or bot owners for debugging. Datadog already has an official .NET C# library that can be easily added to Nadeko's code.

**Comment by Kexerval** [comment]
I would love to help add this to Nadeko, but I have limited knowledge of Nadeko's code. I would have free time to sit down with anybody willing to talk about where I should add my code.

**Comment by Kwoth** [comment]
it's not free, so no. useless 1 day retention.

**Comment by Kexerval** [comment]
@Kwoth I've been using DataDog for my RedBot fork for over a month and I've retained all of my data and can continue to record data even though my free trial expired.
