### ISSUE TITLE
Song is not found error

### ISSUE THREAD

**Issue by bogusstarwars** [Kwoth/NadekoBot#1042]
Finding songs on youtube used to work but recently I have been getting the Song is not found error. Whenever I queue a song this error shows up. I have checked that FFMPEG is installed correcty and I created a new Google API Key which did not work. Any help is appreciated.
![songisnotfound](https://cloud.githubusercontent.com/assets/24450555/22616848/1b7d95b6-ea6b-11e6-9ab2-9a844a8434e5.png)

**Comment by shikhir-arora** [comment]
You need to update your bot. 1.0-rc2 is outdated now, latest version will fix this.

**Comment by Kwoth** [comment]
You just need to replace your installer with the new one from the guide and then update. Old installer doesn't work anymore.
