### ISSUE TITLE
Overwatch search needs to be case-sensitive

### ISSUE THREAD

**Issue by taweko** [Kwoth/NadekoBot#1044]
In using the regex to substitute "#" for "-", the case of the battletag is being dropped and breaking the search for some usernames.

**Comment by Kwoth** [comment]
Can you tell me if it works now? Sorry you waited a month for such a simple issue.

**Comment by EthanChrisp** [comment]
To add on to this, it'd be awesome if we could get multi-platform support for the Overwatch commands, as Overwatch is on PlayStation 4 and Xbox One as well. 

```
.WithUrl("https://www.overbuff.com/players/pc/" + battletag + "")
```

In this line you can see `pc` for the platform, so I'd assume that overbuff.com supports `ps4` and `xb1` or something of the sort as well.
