### ISSUE TITLE
CentOS Docker The build failed. Please fix the build errors and run again.

### ISSUE THREAD

**Issue by jikson26** [Kwoth/NadekoBot#1047]
Pulling the latest docker container updates broke the bot's startup. Running docker on CentOS 7.3

docker logs nadeko -f
Dotnet installed.
Running NadekoBot with auto restart Please wait.
/opt/NadekoBot/src/NadekoBot/NadekoBot.xproj(7,3): error MSB4019: The imported project "/usr/share/dotnet/sdk/1.0.0-rc4-004771/Microsoft/VisualStudio/v14.0/DotNet/Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

The build failed. Please fix the build errors and run again.

**Comment by Kwoth** [comment]
Yeah, microsoft updated their docker to the newest sdk which moves back to .csproj from project.json. I will see what I can do today. Hopefully we won't have to upgrade to .csproj so suddenly.

**Comment by Kwoth** [comment]
Try again, we've just changed the image to `1.1-sdk-projectjson`. Close the issue if it works.

**Comment by jikson26** [comment]
Perfect! Thanks Kwoth
