### ISSUE TITLE
Could not load any video elements based on the query.

### ISSUE THREAD

**Issue by jikson26** [Kwoth/NadekoBot#1048]
CentOS 7.3 Docker

Any Idea on why this is happening? I have working API credentials in credentials.json

Failed resolving the link.Could not load any video elements based on the query.
22:14:30 CommandHandler | Command Errored after 0.008/0.008/0.008/1.468s
	User: [redacted]
	Server: [redacted]
	Channel: [redacted]
	Message: !!q test
	Error: Song is not found.

**Comment by Kwoth** [comment]
Too vague query? No idea.
try
`!!q oracion ending full`

**Comment by jikson26** [comment]
Getting the same error. Happens even with shortlinks

**Comment by Kwoth** [comment]
#1053 for tracking music issues, most of them are the same issue. In your case though it seems to be incorrect api key.
