### ISSUE TITLE
(Feature Request) Membership Application via DMs

### ISSUE THREAD

**Issue by paetrox** [Kwoth/NadekoBot#1049]
(I sent this to #help in the support discord, and they told me to post it here. It's copy/pasted. A couple people said it's not currently possible with Nadeko, so I figured it might be something cool to add)

Hey guys. I've a thing I'm trying to do with my self-hosted NadekoBot. I don't know if it's entirely possible or not. So I'm just gonna kind of put it out there and see if anyone knows if it's possible, and what I might have to do to get it running (or where I can look to read about it, or even where I can go to add/make a custom module that will do it)..

I run a small but growing gaming community, and our discord has become a pretty cool hangout, but as it gets bigger, it's becoming harder to manually keep track and sort out who's part of the community, who wants to be a part of the community, and who's just some random that never left the server. We offer contests, giveaways, extra channels, extra privledges, and other various things to actual members of the community. We don't really want randies that don't give a hoot involved in those, but we want to maintain our "everyone is welcome here!" attitude. 

My solution is simple. A quick "Fill in the blanks" membership application. I'll have Nadeko give everyone that comes in a "base" level role that has restricted permissions and access. From there, they fill out the application, an admin approves it, and they're then granted the next "level" role.
So here's what I want (Sorry it took so long to get here). As new people land in our server, I'll have Nadeko send them a .greetdm welcome message. At the end of the welcome message, I would include instructions to reply to the Bot's DM with a "command," to which the bot would respond with a blank membership application. Then from there, I'd like them to be able to fill it out and send it as a DM reply to the bot with another "command" (which would be included in the copy/paste application template). Then I would like Nadeko to send them a confirmation message saying their application has been received, blah blah blah, AND at the same time, have Nadeko forward thier completed application to an admin only channel on our server, where someone can do a quick review and accept/deny it. 

EXTRA POINTS if the admins could then just type in another command like...
!Accept/Deny (USERNAME)
or
!application (username) yes/no

Which from there, Nadeko could then DM the user that they've been accepted/denied and automatically grant them their Member role. 

I'm really sorry that this is so long, but I've been trying to get it to work for a while, and I haven't been able to get it to work, so I just wanted to be real thorough in explaining what I'm trying to do. 

If anyone has any knowledge on this, or ideas for things that might work... Please let me know. That would just be fantastic. And please feel free to DM me, so I don't have to blow up chat with my bullroar anymore :3 

Thanks so much!

**Comment by Kwoth** [comment]
Everything is possible.

You'll have to know C# to do it.

Good luck.

**Comment by paetrox** [comment]
So now to learn C+ and figure out how to do it. Swag
