### ISSUE TITLE
FFMPEG Error on Linux

### ISSUE THREAD

**Issue by ttshivers** [Kwoth/NadekoBot#1051]
I have NadekoBov v1.1.6 running on Ubuntu Server 16.04. The bot has been working fine with music for many months, but just today, I have been getting this error anytime I queue up music:

```
You have not properly installed or configured FFMPEG.
Please install and configure FFMPEG to play music.
Check the guides for your platform on how to setup ffmpeg correctly:
    Windows Guide: https://goo.gl/SCv72y
    Linux Guide:  https://goo.gl/rRhjCp
Buffering done.
05:00:33 Song | Slow connection buffering more to ensure no disruption, consider hosting in cloud
```

Also, the Linux Guide link is broken.

Maybe this has something to do with a newer version of Nadeko. I also installed FFMPEG from the regular Ubuntu repositories like normal as described in the install guide.

**Comment by samdivaio** [comment]
How are you installing the prerequisites, there is auto prerequisites installer with `linuxAIO.sh ` before going with that, check your ffmpeg by just typing `ffmpeg ` in you terminal.

**Comment by Kwoth** [comment]
#1053 for tracking music issues, most of them are the same issue
