### ISSUE TITLE
Warnings appeared after updating

### ISSUE THREAD

**Issue by boredgamerz** [Kwoth/NadekoBot#1052]
F:\Nadeko\NadekoBot\src\NadekoBot\DataStructures\CREmbed.cs(73,30): warning CS0168: The variable 'ex' is declared but never used
F:\Nadeko\NadekoBot\src\NadekoBot\Modules\Games\Commands\TicTacToe.cs(82,55): warning CS0169: The field 'Games.TicTacToe._playMove' is never used

Bot still working . I might just comment the non-used things myself to remove the warnings

**Comment by boredgamerz** [comment]
Version I updated to: Stable

**Comment by Kwoth** [comment]
'fixed'

however, you updated to latest. And warnings mean nothing, no need to create issues for them.
