### ISSUE TITLE
CommandHandler | Error in cleverbot - Updated to latest version

### ISSUE THREAD

**Issue by roflsausage** [Kwoth/NadekoBot#1055]
Hello, I am having an issue with the bot where attempting to use cleverbot returns the error "CommandHandler | Error in cleverbot". I have updated to the latest version as described in the other issues, but this does not seem to help.

**Comment by roflsausage** [comment]
I would like to add that we were using it VERY heavily last night. Could the clever bot website have blacklisted my bot somehow because it thought we were spamming it?

**Comment by StewieFellows** [comment]
I'm getting the same error as of recently. I've tried both a Linux and Windows copy with the same credentials, and neither are working.

**Comment by roflsausage** [comment]
I have done a bit more troubleshooting here. I have tried accessing the cleverbot site through an internet browser and when I query it, it returns no results. I am unsure if this is a result of my IP being blacklisted or their site is experiencing issues. @StewieFellows can you attempt to use the bot at www.cleverbot.com and see if you get the same results?

**Comment by moofishies** [comment]
I'm having this error as well. I run the linux version of Nadeko on my linode VPS. I can ping the cleverbot website but don't have a good way to test actually using the bot on my machine.

**Comment by Gremagol** [comment]
Nadeko\NadekoBot\src\NadekoBot\Services\CleverBotApi
Open ChatterBotFactory.cs
Go to line 35
You will see something like:
http://www.cleverbot.com/webservicemin?uc=3210&botapi=chatterbotapi
Edit the 3210 to 777
Restart your bot
And it should work again. :D

**Comment by moofishies** [comment]
@Gremagol That worked for me :) Thank you! No clue how you figured that out. 

Hopefully I won't have to edit that every time I update.

**Comment by roflsausage** [comment]
@Gremagol You bloody genius. <3

**Comment by StewieFellows** [comment]
Agreed, all set with the change to ChatterBotFactory.cs! :)

**Comment by StewieFellows** [comment]
As of today, the fix from @Gremagol is no longer working for me (same error as before). Anyone else notice this?

**Comment by Gremagol** [comment]
Change the 777 to UseOfficialAPI

**Comment by Gremagol** [comment]
Should work then :D

**Comment by Kwoth** [comment]
Update to latest again.

**Comment by roflsausage** [comment]
I would like to say that this issue is occurring again on the latest version. The UseOfficialAPI fixed described by @Gremagol no longer works either.

**Comment by StewieFellows** [comment]
@roflsausage The devs are aware, but this is because the unoffical API no longer works at all. There is an official one, but it would probably require reworking some code to get it swapped in, and the free version won't support the bandwidth of requests the public bot was getting before. I'm not sure if the devs are even planning to swap it over to the official API or not, so hopefully they can give an answer as to whether or not that will be done. I would gladly get my own API key if I had to supply one for my copy.

**Comment by HailfireCCS** [comment]
can someone describe how i would insert my own API key into ChatterBotFactory.cs? I don't seem to get the hang of the url formatting in the python code.

**Comment by Kwoth** [comment]
#1076

**Comment by StewieFellows** [comment]
@HailfireCCS Even if you have an official API key, the URL in ChatterBotFactory is not for the official API, and the code utilizing that URL is intended for the unofficial API that no longer works.

**Comment by RBGaming** [comment]
what now? UseOfficialAPI no longer works

**Comment by Gremagol** [comment]
Latest version of nadeko used another API, it's called Program-O.

**Comment by RBGaming** [comment]
guess i need to update then
