### ISSUE TITLE
Songs will be skipped (Windows and Linux)

### ISSUE THREAD

**Issue by DerSani1988** [Kwoth/NadekoBot#1056]
Hi,

i've 2 Servers (1 Windows Server 2012 and 2. Linux Debian) and run on booth a Nadeko bot. The following issue happens on both Servers.

The Issue is, the if i add some songs via !!q some songs never will played 
(eg. http://www.youtube.com/watch?v=I4ArKr6W8YM) or the Playlist 
(https://www.youtube.com/playlist?list=PLQa8bbvHpX3qkhCFZxz5mfew4pSJHItsl) will added and confirdmed by the bot with: Playlist queue complete. The first song starts to play if i skip this song via !!n or the song is over. The bot spams "Playling Song" for 4-5 times (everytime another song) and only 2-3 Songs the bot can play from this list the other songs will be skipped. Yesterday the whole list worked. See attached the Shell of the bot. It looks similar on windows and linux. 
(https://cloud.githubusercontent.com/assets/25698122/22849067/e0a8c430-eff9-11e6-9971-4aeef39178f9.png)

Any ideas? 
I tried to update the bot, nothing solved it

Thanks

Kind Regards
Sani

**Comment by samdivaio** [comment]
Issue seems to be happening with few users, looks like api cant grab the uri needed to stream the song.
You can check your [Google "API" Console](https://console.developers.google.com/) to refresh or generate a new API to see it helps, personally it has not effected me yet, bots being at east U.S locations. 

[More infos here about API setup](http://nadekobot.readthedocs.io/en/latest/guides/Windows%20Guide/#setting-up-nadekobot-for-music)

**Comment by Kwoth** [comment]
#1053 for music issues.

**Comment by DerSani1988** [comment]
@Kwoth i checked out #1053 before i posted my main post. so there is no solution for this problem

**Comment by DerSani1988** [comment]
@samdivaio  i tried a new api key problem not solved

**Comment by samdivaio** [comment]
Looks like issue with EU region.

**Comment by TheRealhanBrolo** [comment]
![image](https://user-images.githubusercontent.com/28786216/37188196-7ee99bae-2313-11e8-900f-ab171dc1d100.png)

![image](https://user-images.githubusercontent.com/28786216/37188262-d38e1bc6-2313-11e8-80ac-8a1bc287b1f0.png)

Everything is installed as is presented from the updater

Have 100% reinstalled the bot, Redis, YoutubeDL. and ffmpeg.  and downloaded the .net SDK linked by sam. Bot location is US East. Have refreshed google api. 
The output to chat is always https://youtube.com/watch?v= with no URI

**Comment by hemipatu** [comment]
I too can confirm that it has something relating to the EU region.
