### ISSUE TITLE
.mentionrole permissions

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [Kwoth/NadekoBot#1057]
.mentionrole does not require any special permissions to use.
If everyone on a server has a role, say as a way to accept terms and conditions, You can mention said role. 

Was pretty funny though, figured it out on the /b/ discord, crashed the bot.
Perhaps a way to cancel the mention, and a "Anti-Spam" method if there's x users in a role, like how you can't list users in a role over a certain amount.

**Comment by samdivaio** [comment]
Probably need the mention role to mention a max of 200~500 users.
