### ISSUE TITLE
[Feature Request] .unban Command

### ISSUE THREAD

**Issue by EthanChrisp** [Kwoth/NadekoBot#1059]
Simple and to-the-point. Say you have Moderators (not Admins) on the Server who need to unban a user who was wrongfully banned, this is impossible for them to do without the Ban Members(?) Permission. This is important because you cannot use Nadeko's Logs to see who unbanned what user, as it is all done through Discord and not Nadeko. 

Command: `.unban @user#1234 "reason"`

Command would be `.unban`, Argument would be `user and discrim`, another optional Argument would be `"reason"`

**Comment by Kwoth** [comment]
No idea why I still didn't do this. Soon:tm:

**Comment by Kwoth** [comment]
Finished, will be pushed when some other things are tested tomorrow.
