### ISSUE TITLE
Not responding to "@Nadeko <message>" using Cleverbot

### ISSUE THREAD

**Issue by RevvyTt** [Kwoth/NadekoBot#1060]
I've toggled Cleverbot on, but when I type a message I can see Nadeko typing, but the message never appears when it's done typing. Any help would be greatly appreciated. Thanks!

**Comment by samdivaio** [comment]
https://github.com/Kwoth/NadekoBot/issues/1055 change in api

**Comment by RevvyTt** [comment]
Ah, could you help me navigate there?

**Comment by deivedux** [comment]
Gremagol said:
```Nadeko\NadekoBot\src\NadekoBot\Services\CleverBotApi
Open ChatterBotFactory.cs
Go to line 35
You will see something like:
http://www.cleverbot.com/webservicemin?uc=3210&botapi=chatterbotapi
Edit the 3210 to 777
Restart your bot
And it should work again. :D```

**Comment by RevvyTt** [comment]
Oh, it must be bc I used an installer. Didn't do it manually... I can reinstall it if it helps

**Comment by Kwoth** [comment]
Gremagol was right. It was fixed in an update few minutes ago.
