### ISSUE TITLE
CommandHandler | Error in cleverbot in latest build

### ISSUE THREAD

**Issue by CyborgNinjaPaz** [Kwoth/NadekoBot#1062]
Every time @<BOT> is used, this error occurs. I have also changed the URL in ChatterFactory.cs to 777, which solved the issue temporarily, but the issue is occurring again today.

**Comment by Gremagol** [comment]
Change the 777 to UseOfficialAPI
And restart.

**Comment by CyborgNinjaPaz** [comment]
Unfortunately, the issue is persisting.

**Comment by Gremagol** [comment]
Its works for me. Check the link again.

**Comment by CyborgNinjaPaz** [comment]
Well, it's working now. Thank you.
