### ISSUE TITLE
Mirai only responding with <html>

### ISSUE THREAD

**Issue by BrooklynAQ** [Kwoth/NadekoBot#1063]
Mirai has only been responding to messages with "<html>" and I can't figure out why

**Comment by Kwoth** [comment]
?

**Comment by BrooklynAQ** [comment]
Mirai is only responding with <html> whenever I try to ask her something

**Comment by Jukuu** [comment]
This is not Mirai :)

**Comment by BrooklynAQ** [comment]
how so?

**Comment by BrooklynAQ** [comment]
Mirai is only responding with "html" but with <> like a script does

**Comment by Kwoth** [comment]
She's responding only with html not <>

**Comment by kongslien** [comment]
Mirai is responding only with html

**Comment by samdivaio** [comment]
Did you ask her to be your web browser?

**Comment by miraai** [comment]
html

**Comment by ManuelFte** [comment]
^

**Comment by gh0s7w4r10rd** [comment]
@BrooklynAQ Same with me dude! I don't understand how is this even possible!

**Comment by ShotzPotz** [comment]
I think she might be responding with <html> can anyone confirm?

**Comment by ManuelFte** [comment]
Yes

**Comment by infy147** [comment]
Me too thanks

**Comment by OrigamiSS** [comment]
im sure thats how she usually respond

**Comment by BrooklynAQ** [comment]
No she NEVER responded like that before

**Comment by ManuelFte** [comment]
She hadn't responded like that previously.

**Comment by Jukuu** [comment]
html
