### ISSUE TITLE
Hangman bug on mobile Discord caused by style processing inside <code>

### ISSUE THREAD

**Issue by Snor** [Kwoth/NadekoBot#1065]
This is actually a Discord bug (I have submitted it to them too) but I'm also submitting this in case you'd like to make your hangman game work on Discord on mobile in the mean time, too (which would be great!)

The issue is that the _ _ _ _ _ characters used for hangman are being processed as markdown code and turned into italicized text. Nadeko outputs these inside a \<code\> tag to stop this happening, which works as expected on desktop.

However on mobile (Android), Discord still processes the _ into style inside the \<code\> tag.

Unless there's some way to force the _ to show correctly then a fix for this game to work correctly as a Discord bot would be to replace the _ with another similar character.

**Comment by Kwoth** [comment]
it's using circles now instead of _, should be working fine.
