### ISSUE TITLE
(Feature Request) Music keyword search brings up multiple choices

### ISSUE THREAD

**Issue by wamuzu** [Kwoth/NadekoBot#1066]
This would be a way to have the bot show a list of selections for the search query instead of auto-selecting the first result, which is often not what the user wanted played in the first place.
I've seen this on another bot before and would be a good addition to this one.

An example would be: "!!play nujabes"

![](http://i.imgur.com/AD5KQ0e.png)

**Comment by shikhir-arora** [comment]
Yeah it's possible and not terribly hard to do, but with youtube API it's just a bit annoying and inherits some issues from that. Plus I'm not sure how much faster that is over searching again.

Anyways, I know that feature and I think that it would come after a bigger re haul of the music module first

**Comment by Kwoth** [comment]
Yea this is a nice suggestions

**Comment by Kwoth** [comment]
Not a priority. After 1.3

**Comment by Kwoth** [comment]
I won't do this for 1.42, I'll go through the whole music module soon:tm: to stabilize it and add this too.

**Comment by Kwoth** [comment]
Scrap that, seems fun, I'll do it tomorrow as the last thing for 1.42

**Comment by Kwoth** [comment]
Was fun to make
![qs demo](https://user-images.githubusercontent.com/2537696/27086168-9f30eda8-5051-11e7-8297-98d03f9054cb.gif)
