### ISSUE TITLE
Tried running Nadeko on Mac OS and failed

### ISSUE THREAD

**Issue by T0ugA** [Kwoth/NadekoBot#1067]
I was on the "running Nadeko" step and did what it told, the terminal said:

bash: linuxAIO.sh: No such file or directory

Even when I tried "cd ~ && wget -N https://github.com/Kwoth/NadekoBot-BashScript/raw/master/linuxAIO.sh && bash linuxAIO.sh" at the first place, it said "command not found".

Please help!

**Comment by samdivaio** [comment]
The command not found is the only issue you couldn't get the `linuxAIO.sh` to fix it install the command first.
From `cd ~ && wget -N https://github.com/Kwoth/NadekoBot-BashScript/raw/master/linuxAIO.sh && bash linuxAIO.sh` I believe it means your `wget` command isn't found, to fix that use command `brew install wget` to get the wget installed first later get the `linuxAIO.sh` and run it.
Good Luck!
