### ISSUE TITLE
.serverinfo does not work on all servers

### ISSUE THREAD

**Issue by Kakkela** [Kwoth/NadekoBot#1072]
.sinfo/.serverinfo doesn't work on all of the servers bot is in and gives error 0
> 22:55:58 CommandHandler | Command Errored after 0.124s
>        User: Kakkela#6315 [134298438559858688]
>        Server: ***** [*****************]
>        Channel: botland-and-trivia [*****************]
>        Message: .serverinfo
>        Error: The server responded with error 0: BadRequest

All the servers bot is in do have icons, custom emotes and very varying amount of users.
Bot is running version 1.1.5a

**Comment by Kwoth** [comment]
update to latest (1.1.8-alpha)
It was fixed partially or completely, but i can't remember when.

**Comment by Kakkela** [comment]
Okay I updated, one of the servers it didnt work on stable is now OK.
There's still other servers it doesnt work though.

**Comment by Kwoth** [comment]
It's caused by a big number of long server emojis.

I'll make .sinfo show another 5 less soon:tm: to make it more reliable.

**Comment by Kwoth** [comment]
Updated this last night, should be working better, unless you guys have some crazy long server emojis

**Comment by Kakkela** [comment]
Thanks, all the servers I have it on are now fine.
