### ISSUE TITLE
cant update nadeko to new version 

### ISSUE THREAD

**Issue by singragum** [Kwoth/NadekoBot#1073]
i installed  nadeko bye  load at https://github.com/Kwoth/NadekoBot/releases   and i can use it to play music

but  some music in youtube it cant play. have code 

" Failed resolving the ling.an invalid request URI was provided . the request URI  must either be an absolute URI  or BaseAddress  must be set "

 and i saw post https://github.com/Kwoth/NadekoBot/issues/1027   same issue   admin said update to latest (1.1.5a)  
i need to update  i saw my version of nadeko bot is  0.9.6111.2080     i follow guides to update   1.installed  .netcore sdk  2.installed GIT   use NadekoInstaller.bat  to update but it wont work   have code
"dotnet not found, make sure it 's been installed as per the guides instruction !."  
i really sure  i installed it  or i wrong with someting.    How can i update to new version  please help or someone have  link to download new version  like  https://github.com/Kwoth/NadekoBot/releases

Thank verymuch  and sorry about my english  am newbie

**Comment by hakufu** [comment]
Use the guides on the left at the link below corresponding to your system to install Nadeko. Make sure to not skip any steps.

http://nadekobot.readthedocs.io/en/latest/

**Comment by shikhir-arora** [comment]
^ what @hakufu said is correct. That issue was fixed a few releases ago. Current release is 1.1.8.

**Comment by singragum** [comment]
i stuck at i cant download with NadekoInstaller.bat  but i sure i installed a .netcore sdk and GIT

**Comment by hakufu** [comment]
Run as admin and make sure your anti-virus isn't blocking it. It helps if you include more info other than not being able to download like an error or screenshot,etc.

**Comment by theoddball** [comment]
Restart your PC, fixes dotnet not found.
This isn't an issue, use the help channel ID the discord please

**Comment by singragum** [comment]
i run as admin and my pc no have ativirus  T_T

**Comment by samdivaio** [comment]
`dotnet not found, make sure it 's been installed as per the guides instruction !.` means you either have incorrect version of dotnet core sdk or you have installed the version that only supports visual studio.

**Comment by singragum** [comment]
i installed last version of it
