### ISSUE TITLE
dotnet has stopped working

### ISSUE THREAD

**Issue by onceepic** [Kwoth/NadekoBot#1074]
The bottom is the error message,

I have tried redoing this multiple times.
It comes up with another error box saying.

"dotnet has stopped working"

First time trying to setup the bot

Unhandled Exception: System.PlatformNotSupportedException: The WebSocket protoco
l is not supported on this platform.
   at System.Net.WebSockets.WebSocketValidate.ThrowPlatformNotSupportedException
()
   at System.Net.WebSockets.WebSocketHandle.CheckPlatformSupport()
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at Discord.Net.WebSockets.DefaultWebSocketClient.<ConnectInternalAsync>d__25.
MoveNext() in A:\bots\nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\Net
\DefaultWebSocketClient.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.Net.WebSockets.DefaultWebSocketClient.<ConnectAsync>d__24.MoveNext
() in A:\bots\nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\Net\Default
WebSocketClient.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.API.DiscordSocketApiClient.<ConnectInternalAsync>d__24.MoveNext()
in A:\bots\nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\DiscordSocketA
piClient.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.API.DiscordSocketApiClient.<ConnectInternalAsync>d__24.MoveNext()
in A:\bots\nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\DiscordSocketA
piClient.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.API.DiscordSocketApiClient.<ConnectAsync>d__23.MoveNext() in A:\bo
ts\nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\DiscordSocketApiClient
.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<ConnectInternalAsync>d__96.MoveNext
() in A:\bots\nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\DiscordSock
etClient.cs:line 212
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.WebSocket.DiscordSocketClient.<ConnectInternalAsync>d__96.MoveNext
() in A:\bots\nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\DiscordSock
etClient.cs:line 241
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<ConnectAsync>d__95.MoveNext() in A:
\bots\nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\DiscordSocketClient
.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.WebSocket.DiscordShardedClient.<ConnectInternalAsync>d__35.MoveNex
t() in A:\bots\nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\DiscordSha
rdedClient.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.WebSocket.DiscordShardedClient.<ConnectAsync>d__34.MoveNext() in A
:\bots\nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\DiscordShardedClie
nt.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.WebSocket.DiscordShardedClient.<ConnectAsync>d__34.MoveNext() in A
:\bots\nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\DiscordShardedClie
nt.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.NadekoBot.<RunAsync>d__56.MoveNext() in A:\bots\nadeko\NadekoBot
\src\NadekoBot\NadekoBot.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__58.MoveNext() in A:\bots\nadeko\N
adekoBot\src\NadekoBot\NadekoBot.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.Program.Main(String[] args) in A:\bots\nadeko\NadekoBot\src\Nade
koBot\Program.cs:line 6

**Comment by onceepic** [comment]
also as a sidenote when i first install NadekoBot.

It asks to "Insert the diskette that contains the batch file"
How do i add commands to it when only option is to "press any key when ready"

**Comment by samdivaio** [comment]
`Unhandled Exception: System.PlatformNotSupportedException: The WebSocket protoco
l is not supported on this platform.` 

You are probably using Windows 7 or early version, you have to use Virtual box to host it on those Windows, dotnet core don't support Websocket protocol on those meaning you can just install them but it won't be able to connect.

**Comment by onceepic** [comment]
Was wondering if that was the case if it was o/s?  Is there instructions on virtual hosting? So I have to use VMware or cloud?

**Comment by samdivaio** [comment]
You can use virtualbox there are lots of guide online already, you can use one ubuntu os image from http://www.osboxes.org/virtualbox-images/ and follow the linux http://nadekobot.readthedocs.io/en/latest/guides/Linux%20Guide/
