### ISSUE TITLE
Cleverbot not working

### ISSUE THREAD

**Issue by wavejump** [Kwoth/NadekoBot#1076]
I'm _not sure_ exactly when this issue arose, or if anybody else has reported it, but Nadeko's cleverbot function has been broken the past few days... When cleverbot is enabled and Nadeko is mentioned with a message, Nadeko doesn't respond and instead shows 'Nadeko is typing..." at the bottom of the screen for a couple of seconds before it disappears. I should mention that I'm not hosting Nadeko off of my own computer and that it is occuring on multiple servers that I use (only one of which is owned by me). Sorry again if this was already reported or talked about. I can provide a video if needed.
**~Wave**

**Comment by Kwoth** [comment]
Cleverbot won't work until further notice. It's a paid service now and we'd have to spend a big chunk of money from donations in order to keep it working for a full month with the usage it was getting.
