### ISSUE TITLE
Cleverbot Issue

### ISSUE THREAD

**Issue by Konkz** [Kwoth/NadekoBot#1081]
After enabling >cleverbot and mentioning him and adding a message, for example "@bot hello" he will type but not send the actual message.

Here is the console view, not sure how to get the actual error log:
https://i.gyazo.com/65b60945e36510cd1fd08ae8345f1fb5.png

**Comment by Kwoth** [comment]
#1076

**Comment by Deivedux** [comment]
Closed how?
