### ISSUE TITLE
.v+t command - anyway to reverse this command?

### ISSUE THREAD

**Issue by Kyzrael** [Kwoth/NadekoBot#1086]
I have tried to reset perms and reinvite the bot. Seems like the command is stuck for the server I owned. Would like to know if there's a way to undo it as the chat channels are under utilised.

**Comment by DogeOps97** [comment]
Just type `.v+t`

**Comment by Kwoth** [comment]
and .cv+t

**Comment by Kyzrael** [comment]
Thank you :D
