### ISSUE TITLE
If a user has Link Preview disabled in their settings, bot does not function

### ISSUE THREAD

**Issue by Draco18s** [Kwoth/NadekoBot#1087]
Due to the way that Nadeko embeds its links through markup wizardry, if a user has Link Previews turned off in their client-side settings, then nothing shows up when the bot posts:
![link](https://cloud.githubusercontent.com/assets/1750680/23324845/a2441940-fabe-11e6-9183-74d64d2df187.png)
![capture](https://cloud.githubusercontent.com/assets/1750680/23324817/5d5dd294-fabe-11e6-8158-789d7706bbbb.PNG)

There is *no fallback text link!*

**Comment by ManuelFte** [comment]
That's not a bug. Nadeko posts using Discord embeds, so if users don't have Link Previews enabled they obviously won't see anything. That's how it is and there's nothing that can be done about it.

**Comment by Draco18s** [comment]
No, it's a bug.  Turning link preview off is a legitimate Discord setting that users can--and will--utilize. If the bot doesn't support it, then your bot is broken.  You might think it's awesome and clever to embed images that way, but as someone who doesn't want link previews cluttering the chat interface after I've viewed it (or mobile users who don't want it eating their mobile data), it makes your bot not function.

As a result, our server owner is already looking for alternative solutions.

**Comment by ManuelFte** [comment]
Good luck finding a bot that doesn't use embeds.

**Comment by Kwoth** [comment]
Bot is using embeds. If you don't want to see embeds, you can't see bot's responses. Logic - not a bug.

**Comment by samdivaio** [comment]
I think its already reported several times in Discord Devs Server, Discord shouldn't block the embed posts when only embeded link previews are disabled.
