### ISSUE TITLE
MSB4019 (Microsoft.DotNet.Props not found) on ArchLinux

### ISSUE THREAD

**Issue by marwanpro** [Kwoth/NadekoBot#1088]
I've installed .NET from AUR (It's working) but Nadeko gave me this error:

`/srv/nadeko/NadekoBot/src/NadekoBot/NadekoBot.xproj(7,3): error MSB4019: The imported project "/opt/dotnet/sdk/1.0.0-rc4-004771/Microsoft/VisualStudio/v14.0/DotNet/Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

## Environment data
`dotnet --info` output:

`.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     arch
 OS Version:
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /opt/dotnet/sdk/1.0.0-rc4-004771`

I've included the tree of /opt/dotnet:

[tree-dotnet.txt](https://github.com/dotnet/cli/files/800769/tree-dotnet.txt)

**Comment by samdivaio** [comment]
Probably the Docker thing happening to you, go back to .NET `1.0.0-preview2-1-003177`

**Comment by Kwoth** [comment]
yup, you must be on `1.0.0-preview2-1-003177`. The one you have is a .csproj one, we're still using project.json
