### ISSUE TITLE
auto assign role on user join

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#109]

**Comment by appelemac** [comment]
I've taken it like this:

- Added new variable to the AnnouncementModel: `public ulong defaultRoleId { get; set; } = 0;`
- Added new command to the ServerGreetCommand.cs to set a defaultRole
- Changed the UserJoined command in ServerGreetCommand.cs to implement the giving of roles

Unfortunately, the change to the AnnouncementModel freaked it out, and now I get a `System.TypeInitializationException` when initializing the datamodel, so I can't test whether it works

**Comment by Kwoth** [comment]
uhh, do not do that. Thats wrong way to go about it. It all needs to be in 1 class, do not put in other classes event handler's, and announcement model has nothing to do with this.

**Comment by appelemac** [comment]
Sure

**Comment by Kwoth** [comment]
this is done in 0.98 or 0.97 idr
