### ISSUE TITLE
Make >poll a bit easier to understand

### ISSUE THREAD

**Issue by Deivedux** [Kwoth/NadekoBot#1091]
Idk if people have been affected by this or not, but whenever I do `>poll` in my server, I get it, the bot says `Private Message me with the corresponding number of the answer.`, so that must have mean to DM the bot, but it also says `Deivedux has created a poll which requires your attention:`. It's pretty nice that it tells who hosts the poll, altho, because of that, when they see the `Private Message me`, they take it as me (literaly) and I have a flood of over 20 DMs at once. I hope there will be a fix like, make people understand it better on who to actually DM their answer.

**Comment by Kwoth** [comment]
no
