### ISSUE TITLE
Nadeko crashes on startup (String was not recognized as a valid DateTime)

### ISSUE THREAD

**Issue by Puncia** [Kwoth/NadekoBot#1094]
I'm hosting Nadeko on my computer.
My internet went down for a while today, and both my Discord account and Nadeko disconnected. Once it came back, I closed Nadeko and opened it up like I usually do. Since then, it keeps crashing. [Here is the stack trace](http://pastebin.com/0QWETSA4).

I went ahead and started to understand what was causing the issue. I tried to comment the 24th line on RateLimitInfo.cs, and adding a value to Lag:

`Lag = TimeSpan.Zero;
            Console.WriteLine("HEADERS VALUE: " + headers["Date"]);
            //Lag = headers.TryGetValue("Date", out temp) ? 
            //    DateTimeOffset.UtcNow - DateTimeOffset.Parse(temp) : (TimeSpan?)null;`

I also added a line to output the headers["Date"] value (since apparently that's the problem here, I think?).

Anyway this is the output: `HEADERS VALUE: Wed, 01 Mar 2017 19:44:04 GMT`

Assigning TimeSpan.Zero to Lag lets the bot online and so far it has worked without problems, but I don't really know what Lag does and such workaround is ugly anyway 😄.

I already asked for help to the Nadeko server, tried few things like redownloading both Stable and Latest, connect using a VPN, restart my computer, change my date-time format to 12h.
I am running Nadeko as Administrator. I am on Windows 10.

**Comment by Kwoth** [comment]
This is fixed in 1.4 I believe, just wait for it
