### ISSUE TITLE
Custom Reactions Failing (Says "NadekoBot is typing", but won't post)

### ISSUE THREAD

**Issue by MoonBootsForHire** [Kwoth/NadekoBot#1096]
I'm trying to add some custom reactions to NadekoBot, and I am it's owner, It says that the reactions have been added Globally and I've tried Local server based too, but whenever I test them and say "@nadekobot hello" All I get is Discord saying NadekoBot is Typing... and eventually it stops with the bot not replying.

Everything else works great, Music and Local Music from my Folders, it's perfect.

I've copied and pasted the command prompt exactly from the guide too, just to test it.

The Bot has all permissions. Am I doing or missing something incredibly stupid?

Thanks in advance!

![image](https://cloud.githubusercontent.com/assets/26130937/23493161/a2afb35c-ff01-11e6-9922-617f6de14e25.png)

**Comment by shikhir-arora** [comment]
How are you adding your reactions? If you gave/set Nadeko with a nickname (not username), then `%mention%` won't work.

**Comment by MoonBootsForHire** [comment]
I'm adding reactions in Direct chat with the .acr command like this.

![image](https://cloud.githubusercontent.com/assets/26130937/23493494/194bd61a-ff04-11e6-9264-a37661936b64.png)

I have changed the name of the bot yes, I used the .Setname command to change it from the other name I gave it when I first set it up.

**Comment by MoonBootsForHire** [comment]
I must be misunderstanding command, Do I have to put %mention% in the quatation marks?

**Comment by shikhir-arora** [comment]
That triggers when you just say `hello` - not `@bot hello` - just type `hello` and it will say `Hi there, Tomato-Chan!` if you type it.

`.setname` is fine, that changes the username/nickname.

**Comment by MoonBootsForHire** [comment]
I've sussed it, thank you. It was something stupid, I feel so dumb! I'm going to test real custom mentions, then report back to you.

**Comment by samdivaio** [comment]
Also you probably have cleverbot enabled thats why you are seeing Nadeko typing, disable them if you ever use CRs with mentions

**Comment by MoonBootsForHire** [comment]
Ah yes, I have it working now.

It's a shame you have to be specific, for instance if you say "@NadekoBot hello," Or "@NadekoBot hello?" it doesn't work because of the comma or question mark, but I suppose you can add the variations yourself.

Thank you very much for a fast reply, you helped me wrap my head around such a simple problem.

**Comment by shikhir-arora** [comment]
Regex support for reactions will probably be added in the future to allow for all types of cases.

**Comment by MoonBootsForHire** [comment]
That sounds fantastic, it'll be a fun day if that gets added. Thank you again, I'll close my issue.
