### ISSUE TITLE
eval maths

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#110]

**Comment by appelemac** [comment]
How would you want the maths to be evaluated? Would it be
- `!eval 1+1` returning `2`
- `!eval 1+1=2` returning `true`
Maybe integrate Wolfram Alpha?

**Comment by Kwoth** [comment]
wolfram has very limited api request count, it would be >eval ....

**Comment by MM4005** [comment]
Its a third party library so I don't know how you feel about it but check this out https://ncalc.codeplex.com/

**Comment by Kwoth** [comment]
Thats what applemac used, im just very unsure of security implications.

**Comment by appelemac** [comment]
I didn't use that one for the current version, I used https://mathosparser.codeplex.com/
Which shouldn't do anything weird, but you never know

**Comment by tg44** [comment]
https://ncalc.codeplex.com/
This project lost me in Evaluant.Calculator/NCalcParser.cs ~line 175;
	`public override string GrammarFileName { get { return "C:\\Users\\sebros\\My Projects\\NCalc\\Grammar\\NCalc.g"; } }`
No way you need to burn in a file path...

https://mathosparser.codeplex.com/
This seems OK. Well documented, good to read code, and tests.

**Comment by appelemac** [comment]
You can read my code with it in one of the commits of #126, it's reverted tn though

**Comment by tg44** [comment]
That commit is not bad, I commented in it.

**Comment by Kwoth** [comment]
this is done by dragon
