### ISSUE TITLE
Language Settings Error

### ISSUE THREAD

**Issue by Azratosh** [Kwoth/NadekoBot#1107]
Whenever I try to change the language using **.languageset** or **.langset** the command isn't being recognized, as in, it's not being shown in the console nor is it being executed. **.langset** alone without any arguments however is being recognized, and it also tells me that the current set language is en-US (English), even though all text is in de-DE (German).

![](http://puu.sh/uv3h9/7c992a62e6.png)

**Comment by zigrin** [comment]
I have the same problem with Polish language. It seems that the bot uses default system locale instead of English. I can set other languages without problems, only English doesn't work. I'm using latest dev build on Windows 10.

**Comment by Kwoth** [comment]
I think I understand the issue. Will be pushing a fix right away to see if it helps. Very odd.

**Comment by Kwoth** [comment]
Update to LATEST then tell me if it works.

**Comment by zigrin** [comment]
it worked for me. Thanks :)
