### ISSUE TITLE
Max amount of permissions

### ISSUE THREAD

**Issue by dapal-003** [Kwoth/NadekoBot#1110]
I'm running Nadeko bot on my own pc, and well I got a lot of permissions I want to set up. but after a while they just seem to delete themselves. after adding 61 permissions the last permission (which should be 62) deletes itself. This comes because there are a lot of channels on my server and I like to customize a lot. Is there a workaround I could implement ? or is it hardcoded and do I just have to deal with it?
Thanks

**Comment by Kwoth** [comment]
There's no workaround, permission storing should be reworked in a few days at most to allow for more than 62 permissions.
