### ISSUE TITLE
I'm having problems running NadekoBot on my RPi2

### ISSUE THREAD

**Issue by SibaNL** [Kwoth/NadekoBot#1111]
Hello, I'm trying to set-up NadekoBot on my Raspberry Pi 2.
But I'm running into a few error when trying to launch it.
It comes up with the following:

> sudo mono NadekoBot.exe
> ▒▒▒▒Google API key provided.
> No trello appkey found. You will not be able to use trello commands.
> Forwarding private messages to owner.
> No soundcloud Client ID found. Soundcloud streaming is disabled.
> No osu! api key found. Song & top score lookups will not work. User lookups still available.
> Specific config started initializing.
> Specific config done initializing.
> Reading from the permission files.
> Permission initialization complete.
> Token is wrong. Don't set a token if you don't have an official BOT account.
> System.Exception: You must send data by websocket after websocket is opened!
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f712f98eb8e445c8918edaf595bbe465>:0
>   at Discord.TaskManager.ThrowException () [0x0001e] in <9529832d40a3420689999daa52622c45>:0
>   at Discord.Net.WebSockets.WebSocket.WaitForConnection (System.Threading.CancellationToken cancelToken) [0x0002b] in <9529832d40a3420689999daa52622c45>:0
>   at Discord.Net.WebSockets.GatewaySocket.WaitForConnection (System.Threading.CancellationToken cancelToken) [0x00012] in <9529832d40a3420689999daa52622c45>:0
>   at Discord.DiscordClient+<BeginConnect>d__78.MoveNext () [0x0044c] in <9529832d40a3420689999daa52622c45>:0
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f712f98eb8e445c8918edaf595bbe465>:0
>   at Discord.DiscordClient+<BeginConnect>d__78.MoveNext () [0x005a6] in <9529832d40a3420689999daa52622c45>:0
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f712f98eb8e445c8918edaf595bbe465>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <f712f98eb8e445c8918edaf595bbe465>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <f712f98eb8e445c8918edaf595bbe465>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <f712f98eb8e445c8918edaf595bbe465>:0
>   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <f712f98eb8e445c8918edaf595bbe465>:0
>   at Discord.DiscordClient+<Connect>d__77.MoveNext () [0x0008b] in <9529832d40a3420689999daa52622c45>:0
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f712f98eb8e445c8918edaf595bbe465>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <f712f98eb8e445c8918edaf595bbe465>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <f712f98eb8e445c8918edaf595bbe465>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <f712f98eb8e445c8918edaf595bbe465>:0
>   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <f712f98eb8e445c8918edaf595bbe465>:0
>   at NadekoBot.NadekoBot+<>c+<<Main>b__32_3>d.MoveNext () [0x00179] in <0c3b1ee187ad4dbc8d304a35d06d044e>:0
> Severity: ErrorExceptionMessage: You must send data by websocket after websocket is opened!Message: Disconnected

Does anyone know what the problem is?
Thank you.

**Comment by samdivaio** [comment]
[!img](https://cdn.discordapp.com/attachments/251504306010849280/276455844223123457/Capture.PNG)
its either your bot token you just need to downgrade mono <http://nadekobot.readthedocs.io/en/0.9/guides/Linux%20Guide/#mono-fix-socket-error>

**Comment by SibaNL** [comment]
Got Mono working using ZirconiumHacker's post on https://github.com/Kwoth/NadekoBot/issues/731

Thanks for helping.

**Comment by xnaas** [comment]
@SibaNL if it's working you should close this issue. 😉 Or @Kwoth should. Either way. ¯\\\_(ツ)_/¯

**Comment by Jimmy062006** [comment]
It wont work as its only 32bit
