### ISSUE TITLE
CleverBot fails

### ISSUE THREAD

**Issue by AGuyNotNamedJon** [Kwoth/NadekoBot#1112]
When typing the command as an example "@NadekoBot Hello, how are you?" causes it to fail.
Giving the error "14:55:49 CommandHandler | Error in cleverbot"

After having a quick look through the bot, it appears that the bot is still using the old cleverbot APIs. As these APIs are now paid for, it might be worth changing over to https://cleverbot.io/ or getting users to pay ;)

**Comment by Kwoth** [comment]
#1076

**Comment by samdivaio** [comment]
also no to cleverbot.io ![img](https://cdn.discordapp.com/attachments/144065504871579648/285038598196035584/unknown.png)

**Comment by AGuyNotNamedJon** [comment]
Is there a way that we can have our own api keys used?
Added the same way that say the google api is done

**Comment by samdivaio** [comment]
yes and read the kwoths comment
