### ISSUE TITLE
I get an error from AnimeSearchCommands.cs every time I start NadekoBot.

### ISSUE THREAD

**Issue by bogusstarwars** [Kwoth/NadekoBot#1114]
Every time I start NadekoBot, I am greeted with this error in the Command Prompt.
![animesearchnotworkin](https://cloud.githubusercontent.com/assets/24450555/23687363/f5c5e04c-0362-11e7-8ebf-872647aa5eb3.PNG)
How do I fix this? I have tried looking at the code at that specific line, but the fact is that I do not know anything about C# so can someone please help me.

By the way this is the code
![animesearchnotworkin2](https://cloud.githubusercontent.com/assets/24450555/23687431/46d3dc5a-0363-11e7-911d-c0797818fbab.PNG)

Thank you for your time.

**Comment by Kwoth** [comment]
Don't mess with the code, just update to latest.
