### ISSUE TITLE
MSB4019

### ISSUE THREAD

**Issue by TechnoDaft** [Kwoth/NadekoBot#1117]
I'm getting the "MSB4019" error it used to work without any issues until i installed Visual Studio 2017.
I only have 2 folders in the sdk folder {1.0.0-preview2-1-003177, and 1.0.0} any help would be appreciated.

"C:\Users\Techn\OneDrive\Documents\Nadeko\NadekoBot\src\NadekoBot\NadekoBot.xproj(7,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.0\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

The build failed. Please fix the build errors and run again."

![image](https://cloud.githubusercontent.com/assets/20615768/23702968/8b72fac2-03cb-11e7-8971-046500f349a7.png)

**Comment by Cry0tic** [comment]
Same for me except mine says "C:\Program Files\dotnet\sdk\1.0.1\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props". I looked for the folders and got to 1.0.1 but there is no "Microsoft" folder within it.

![capture](https://cloud.githubusercontent.com/assets/26279190/23708916/a97a28dc-03e5-11e7-8223-331bca29bdc5.PNG)
.

**Comment by Kwoth** [comment]
Visual studio 2017 comes with msbuild version of 1.0. We're using project.json version of 1.1. Remove it from control panel and it will work. Didn't look into how to switch version but that's possible too, probably.
