### ISSUE TITLE
when someone queues spotify song/playlist, search youtube for songs and play those

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#112]

**Comment by Kwoth** [comment]
nah

**Comment by JhOnNeY** [comment]
https://www.statista.com/statistics/367739/spotify-global-mau/

Hey I wouldn't write spotify off so quickly...

100 million users a month... that's 100,000,000

a good number of my server members use spotify and won't even join the music channel because the bot doesn't queue spotify playlists.

**Comment by shikhir-arora** [comment]
It's not that simple to integrate Spotify. If you just mean getting playlists and the tracks -> then finding the tracks on YouTube to actually play - as you *can't* queue from Spotify directly. Some players are able to get specific track previews by 'scraping' the open.spotify URLs, but this doesn't work for most tracks and isn't consistent. tl;dr nobody is writing off Spotify, but it doesn't make much sense considering the limitations. Not to mention they can change their API functions at any time.
