### ISSUE TITLE
Dotnet not found, Make sure it's been installed as per the guides instructions!

### ISSUE THREAD

**Issue by Montrigo** [Kwoth/NadekoBot#1120]
![help](https://cloud.githubusercontent.com/assets/26307561/23769605/40821f20-0510-11e7-84be-132ff29d2998.png)

I've reinstalled Dotnet but still does not work.

**Comment by Kwoth** [comment]
restart your pc

**Comment by Montrigo** [comment]
I did that aswell but that did not work

**Comment by ScarletKuro** [comment]
Guess you need to add dotnet directory to PATH Environment Variable in Windows. ("My Computer" > "Properties" > "Advanced" > "Environment Variables" > "Path")
