### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by ModdyLP** [Kwoth/NadekoBot#1128]
Hello,

 i have added the bot completly new to my server and get 400 Bad Request by the .clr command.
`20:18:54 CommandHandler | Command Errored after 0,004/0,02/0,028/0,872s
        User: ModdyLP#9519 [##]
        Server: ModdyLP - Developing - Gaming [##]
        Channel: onlyforbot [##]
        Message: .clr 100
        Error: The server responded with error 400: BadRequest
`

**Comment by Kwoth** [comment]
You are trying to remove messages which are older than 2 weeks, right? You can't do that.

**Comment by ModdyLP** [comment]
Why ? That was possible i think

**Comment by Kwoth** [comment]
It was possible before, discord disabled it because it's causing some database issues on their end. There will be a different way to do it in the future

**Comment by ModdyLP** [comment]
I have an idea how to fix that issue, you can get the messages from the channel and delete all message seperated and not as bulk. The two weeks rule is only for bulk messages not for deleting messages seperated. I know it will take longer to delete all messages, but i think it would be helpfull. Also please add a message for the user, which say the cause of the problem.
