### ISSUE TITLE
No lock file exists and restore doesnt work linux

### ISSUE THREAD

**Issue by Algraud** [Kwoth/NadekoBot#1129]
Hello, I am getting this error when I try to run normaly. I tried both stable and dev instals, i tried deleting and redoing. Checked the name and tried the Some info Section. I am using a droplet.

The current project is not valid because of the following errors:
/root/NadekoBot/src/NadekoBot/project.lock.json(1,0): error NU1009: The expected lock file doesn't exist. Please run "dotnet restore" to generate a new lock file.

This is the problem i think. It happens when i try the dot restore commands in the last section of the guide.

log  : Restoring packages for /root/NadekoBot/src/NadekoBot/project.json...
Killed

Thank you in advance :)

**Comment by samdivaio** [comment]
check .net version with `dotnet --version` and post here along with you OS details.

**Comment by Algraud** [comment]
1.0.0-preview2-1-003177
 and the droplet is Ubuntu 16.04.2 x64

**Comment by samdivaio** [comment]
try just restarting your droplet or try on a different droplet with different region and without ipv6 option

**Comment by Algraud** [comment]
I tried restarting and a complete reinstall, it didnt help. I dont have ipv6 and i don't have any more droplets :(

**Comment by Algraud** [comment]
I actually fixed it with a dotnet restore on NadekoBot folder. I guess the restart helped with this, because i tried before and it didnt help.
