### ISSUE TITLE
unblacklist (to revert ;ubl, ;sbl, ;cbl)

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#113]

**Comment by haloes123** [comment]
how i whitelist someone?

**Comment by Kwoth** [comment]
remove them from data/permissions/[serverid].json file

**Comment by haloes123** [comment]
i added it from one server how can i delete someone if i hasnt have the code downloaded?

**Comment by Kwoth** [comment]
@haloes123 i just fixed it, it was a bug, no one except me should be able to blacklist users or servers. Sorry for that.

**Comment by haloes123** [comment]
now im whitelisted?

**Comment by haloes123** [comment]
can i do to make Nadeko obey a role in specific?

**Comment by appelemac** [comment]
@haloes123 You can do that using the permission commands

**Comment by appelemac** [comment]
@Kwoth Shouldn't this issue be resolved now?

**Comment by Kwoth** [comment]
@appelemac we need unblacklist for server and channel too
