### ISSUE TITLE
(Feature request) Separated BotConfig for each server

### ISSUE THREAD

**Issue by ScarletKuro** [Kwoth/NadekoBot#1130]
An optional thing for selfhosted bots, so that every server where the bot is invited had their own settings in botconfig, that u could setup different CurrencyGenerationChance, CurrencySign and etc for each server separately. Well and it would be also great if you could do the same with waifu and currency, so that the data wasn't shared between servers.

**Comment by Kwoth** [comment]
Can't do, that would mean rewriting huge parts of everything.
