### ISSUE TITLE
Ubuntu 16.04 with dotnet-dev1.0.1 cant compile nadekobot

### ISSUE THREAD

**Issue by TheRadziu** [Kwoth/NadekoBot#1132]
Sup. I got vps on which I intend to set up latest nadekobot (until now nadeko 0.99 was running flawlessly on my raspberry pi, but I want to move on to mentioned vps) but new 'install method' fails on compiling the bot.
`/root/NadekoBot/src/NadekoBot/NadekoBot.xproj(7,3): error MSB4019: The imported project "/usr/share/dotnet/sdk/1.0.1/Microsoft/VisualStudio/v14.0/DotNet/Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

The build failed. Please fix the build errors and run again.
`
when I checked the mentioned dir there is no Microsoft folder at all:
[Screen](http://i.imgur.com/C8iQtme.png)

I installed .Net via official guide [https://www.microsoft.com/net/core#linuxubuntu](https://www.microsoft.com/net/core#linuxubuntu)

**Comment by samdivaio** [comment]
Read the official guide carefully and install the right version of dotnet core again.

**Comment by TheRadziu** [comment]
The real issue was nadekobot build code does not support latest **dotnet-dev-1.0.1** build (as recommended in dotnet core install guide and i had to force install outdated **1.0.0-preview2** dotnet version. 
Its a shame, I like keeping my software up to date.

**Comment by Still34** [comment]
Seems that 1.0.1 migration is not the top priority at the moment. It's a huge problem for those who run bots based on the newer MSBuild based projects. This issue needs to be addressed imo.
