### ISSUE TITLE
Missing feature from 0.99 in 1.x

### ISSUE THREAD

**Issue by TheRadziu** [Kwoth/NadekoBot#1133]
Hi, I recently updated nadekobot to recent version but to my surprise (and yes, i checked command list in docs before I asked this question), it misses feature it had in version 0.99. 
There is no more Voice channel join/leave notification [like this](http://i.imgur.com/s3ggeg5.png). The closest command I found is **.log** but it works way different then mentioned missing feature used to, it notifies about every action of a selected kind (all across server) into single chat room. 

old commands bound single voice channel notifications (about someone joining or leaving) to selected chat only, so it could be used in multiple voice/chat rooms without messing and mixing them up. 

is this command coming back or maybe updated docs are simply missing these commands (I configured 0.99 long time ago, so now i simply dont remember the command's name)?

**Comment by xnaas** [comment]
If you type `.log voicepresence` (or whatever it is exactly) into a channel, that's the channel that will log voice presence.

**Comment by TheRadziu** [comment]
No. As I stated in this issue, this will log ALL events (in this case voice presence) that happened in ALL voice channels to the single channel where command was issued. Whats more it can only be enabled in ONE text channel. Complete opposite of an old feature.

Again: old command only logged join/leave from single voice channel where you were in while issuing the command into the chat where command was sent. 
So, someone joins VoiceChannel1 -> bots sends notification in VoiceChannel1-chat, but when someone joins VoiceChannel2 -> bots sends notification in VoiceChannel2-chat.

**Comment by TheRadziu** [comment]
More info for Dev or people related in case my description was chaotic and confusing. Old command was **.voicepresence**
> Toggles logging to this channel whenever someone joins or leaves a voice channel you are in right now. 

it could be enabled for multiple different voice channels and chat channels.
[source](http://nadekobot.readthedocs.io/en/0.9/Commands%20List/)

now after 1.x rework it does not work like this anymore and command is pretty much unusable with exception of single log channel.

**Comment by Kwoth** [comment]
Yeah that command isn't comming back (logging only single voice channel voice presences)
