### ISSUE TITLE
Can't install mono 4.4.2 op RPi2

### ISSUE THREAD

**Issue by SibaNL** [Kwoth/NadekoBot#1134]
So I'm trying to install mono on my pi using the following lines provided in the guide

> sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
> echo "deb http://download.mono-project.com/repo/debian/dists/wheezy/snapshots/4.4.2/main/" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
> sudo apt-get update
> sudo apt-get install mono-runtime

When running "sudo apt-get update" it comes up with:

> E: Malformed line 1 in source list /etc/apt/sources.list.d/mono-xamarin.list (dist)
> E: The list of sources could not be read.

But the mono-xamarin.list looks fine to me.
sudo nano /etc/apt/sources.list.d/mono-xamarin.list

> deb http://download.mono-project.com/repo/debian/dists/wheezy/snapshots/4.4.2/main/

So, what am I doing wrong?
Or what's going wrong?

Thank you.

**Comment by Kwoth** [comment]
We don't support mono anymore. See if you can .net core running on your pi and install latest nadekobot if you can.
