### ISSUE TITLE
dotnet restore

### ISSUE THREAD

**Issue by MrJunkman137** [Kwoth/NadekoBot#1135]
How do i start the command dotnet restore, ive tried from the cmd but it wont work.

plz help 
![image](https://cloud.githubusercontent.com/assets/26476436/24030140/24bf9d10-0b2f-11e7-9517-028cb797bd51.png)

**Comment by samdivaio** [comment]
Just install the bot again, it will auto restore it for you. 
`1. for Dev Build.`
`2. for Stable Build.`
