### ISSUE TITLE
Cant use >pick command

### ISSUE THREAD

**Issue by VenomTheFox** [Kwoth/NadekoBot#1138]
I have >gc enabled, Im pretty sure, when I last typed that command in it said I enabled it, but unfortunately after at least an hour I try to do >pick but it just removes in the next half a second, this is a problem that is really bugging me!

**Comment by Kwoth** [comment]
>gc doesn't work on the public bot. On self hosted ones, each message sent in the channel where >gc is enabled has a chance to spawn a nadeko flower.
