### ISSUE TITLE
Start Using Version Tags Again

### ISSUE THREAD

**Issue by ttshivers** [Kwoth/NadekoBot#1146]
I noticed that you have not been using version tags since NadekoBot v0.99.10. I am not sure why you stopped doing them. Not having version tags makes trying to figure out what changes were made between versions of Nadeko much more time consuming and annoying than it should be. It also makes very annoying to try and downgrade to an older version, which now involves scrolling through the entire commit list and trying to find a commit where you changed a version number in a file. Having version tags makes it simple to also browse through the repository and see exactly what changes were made between versions, providing a way to see what changes were made. It also provides a great place to put changelogs, and makes historical exploring very easy.

I see that you do keep track of versions however, and make changes like these: [`Ex1`](https://github.com/Kwoth/NadekoBot/commit/59f0fb56e2727194d6d77e6b9f26a754c698940c), [`Ex2`](https://github.com/Kwoth/NadekoBot/commit/dde37f4be816633e23d03dd179d00a98440dd16a). So, you are keeping track of versions, but you have recently stopped telling git about them. It would be wonderful if right after you made those version changes in that file, you could also just run this one command to tag the new version on the repository: `git tag -a v1.XX -m 'Version 1.XX'`

**Comment by shikhir-arora** [comment]
There are a lot of commits from potentially many authors before Kwoth makes a release. Kwoth also is the person who looks at all final pull requests. And in the end the releases are always documented in the same file.

Once enough justifies a new version all the commits that were pushed are collected and usually posted in the Discord server with a nice changelog **which contains the info from the commits** that seem to be important.

Commits are so variable and different in nature that with a project like this you cannot reasonably expect one to follow every single commit made by different authors. The changelogs and versions are good overviews.

If you wish to really look through all things, then just fork the dev branch and add any system you wish. You can merge daily or whatever and you will have full control. Plus they would be your style and reference tags..and archives the same goal.

**Comment by Kwoth** [comment]
Github was doing it for me before when I made releases. Alright. I'll try doing it myself from now on. I'll leave this open to remind me.

**Comment by ttshivers** [comment]
Let me clarify what I am suggesting. I am not suggesting to do a tag after every commit. This would of course be pointless. I just suggest adding a version tag when you decide to increment the version number of the bot.

**Comment by Kwoth** [comment]
I probably won't do it whenever I increment the version number, just when I PR to stable most likely.

**Comment by Kwoth** [comment]
Ok, I've added 1.26 and 1.25a tags, will continue doing so in the future.
