### ISSUE TITLE
Time based repeaters (request)

### ISSUE THREAD

**Issue by forcemaster89** [Kwoth/NadekoBot#1147]
I love your .remind feature, but I find that the countdown isn't very useful in my case. Would it be difficult to create a command that reminds at a certain time (such as 4:00PM) every day, instead reminding after a countdown? (or is this already implemented? I couldn't find it in the documentation.)
An example would be (probably using the 24hr time format):

.repeat hh:mm %message%

Thanks again for the wonderful bot!

**Comment by shikhir-arora** [comment]
It's actually a cool feature I agree, personally will start looking into it as it's been up there. Not *exactly* timed reminders, moreso regex support for reactions and triggers like that, which would allow tons of use cases.

**Comment by Kwoth** [comment]
Will take a look near the 1.3 end, most likely will be moved to future.

**Comment by spark942** [comment]
Improvements from #suggestions 
![image](https://cloud.githubusercontent.com/assets/5710200/25365373/874acf66-2968-11e7-8595-8ebb58d9c156.png)

**Comment by Kwoth** [comment]
Added basic version in 1.42
