### ISSUE TITLE
.setav not working?

### ISSUE THREAD

**Issue by MemeGodiolli** [Kwoth/NadekoBot#1149]
Whenever I use .setav , .setavatar, with an image URL Nadeko does not respond alongside the bots profile image not updating. I have used an imgur link, a .jpg, and even a .gift.

**Comment by shikhir-arora** [comment]
What, if anything do you see in the console? And you are the botowner, correct?

**Comment by Kwoth** [comment]
It does work, you must be bot owner though. It won't work on the public bot. 

SERVER OWNERS ARE NOT BOT OWNERS. All owner-only commands require you host the bot. Hosting means you are running a nadekobot on your own computer. If you want to learn how to host the bot yourself, type `-guide`
