### ISSUE TITLE
"Make sure you are running NadekoInstaller.bat as Administrator" [W10]

### ISSUE THREAD

**Issue by LynnSG** [Kwoth/NadekoBot#1150]
runing as admin "normal" bat https://gyazo.com/5acf0d8117ce34002fafb71ee5f64d98

i need more to fix t ;w;

**Comment by shikhir-arora** [comment]
I can only see it for a second, but it looks like you're getting a compatibility error. Did you:

- Make sure to download the right versions of everything?

- What version of Windows are you running?

**Comment by LynnSG** [comment]
.NET Core SDK 64-bit, Git 2.11.1 (all working) & W10 (Pro)
