### ISSUE TITLE
Possible Spotify API Compatibility? 

### ISSUE THREAD

**Issue by MoonBootsForHire** [Kwoth/NadekoBot#1151]
Would it be possible to use the Spotify Web API with Nadeko Bot to fetch Music and Saved Playlists from Spotify's Music catalogue?

How hard would it be to add more commands such as !!spq !!sppl (Spotify Que and Playlist) and then have it play through the Discord Voice Chat?

It seems similar to the other APIs but I'd like to know how hard (If possible) such a thing would be to set up.

Thanks for any Answers/help.
![spotify api](https://cloud.githubusercontent.com/assets/26130937/24294289/c6e2dfa4-108d-11e7-834c-fd672d3dbc11.png)
![untitled](https://cloud.githubusercontent.com/assets/26130937/24294296/cadac6da-108d-11e7-9939-5cb81e966b12.png)

**Comment by shikhir-arora** [comment]
This was requested several times, right now there's no plans for it due to several complexities and other things right now.

**Comment by MoonBootsForHire** [comment]
Would it be possible for someone to do personally on their own?

**Comment by shikhir-arora** [comment]
> Would it be possible for someone to do personally on their own?

Anything is possible like that, sure, if *you* want to implement it I'm sure it would be looked at. Or am I reading this wrong?

**Comment by MoonBootsForHire** [comment]
No, no. I was just wondering if it was possible. I'm in no rush to attempt a project this big anyway. Thank you very much for the fast reply.
