### ISSUE TITLE
Public typing articles are all about psychology and have untypable characters

### ISSUE THREAD

**Issue by Hubcapp** [Kwoth/NadekoBot#1153]
In this file https://github.com/Kwoth/NadekoBot/blob/dev/src/NadekoBot/data/typing_articles.json almost every article is about pyschology. This is a problem because it is boring and the word psychology is hard to spell.

Could you come up with some better public server typing articles?

Also, there are several articles with the character "â" which guarantees me an error because I can't type that character.

**Comment by shikhir-arora** [comment]
That is up to @Kwoth at the end of the day, if you are talking about public Nadeko. But he is busy so this is low priority. If you come up with a decent amount of good articles / content and put them in the JSON format preferably, like:

```{
		"Title":"The Psychology of Risk Taking Behavior",
		"Text":"This book aims to help the reader to understand what motivates people to engage in risk taking behavior, such as participating in traffic, sports, financial investments, or courtship."
	},

```

I am sure he would consider.

**Comment by Hubcapp** [comment]
I could see about making a pull request, but I don't want to go through the work if Kwoth likes them the way they are.

**Comment by Hubcapp** [comment]
y'all could do this as a "contest" on discord, actually. It may be fun for the community to suggest typing articles.

**Comment by shikhir-arora** [comment]
Remember it's also just JSON so you don't have to delete these ones to add more to them. People who are botowners that self-host can `>typeadd` to add to the options from Discord directly (or edit the JSON themselves), so it's pretty flexible.

**Comment by Hubcapp** [comment]
Yup. I like that feature, and I'm glad that it's stored in JSON. Of course >typeadd and >typedel are not available to those who don't self-host, and it would be nice to provide a better default list of articles for those who do.

**Comment by Kwoth** [comment]
You can fix all accented letters if you want, and add fine new text. Yes these ones are annoying. I don't care that psychology is the tough to type though, that's fine. I couldn't find a proper source to pull the data from, so I scraped google search for psychology book descriptions.

**Comment by Hubcapp** [comment]
addressed by https://github.com/Kwoth/NadekoBot/pull/1155 (but could use more articles)

**Comment by Hubcapp** [comment]
Cool, thanks for merging it. I'll add some more articles later.
