### ISSUE TITLE
(Feature Request) Auto Mute as well as .mute length

### ISSUE THREAD

**Issue by WarmasterCain55** [Kwoth/NadekoBot#1156]
I would like to suggest the feature of including an option length in mute like .mute name m. Having that would push her abilities for auto mod.

**Comment by shikhir-arora** [comment]
Something like this? https://github.com/Kwoth/NadekoBot/commit/93c28918d0e3d40919ddf4790e70f4684614e1c9

**Comment by WarmasterCain55** [comment]
if I understood that right then yes

**Comment by Kwoth** [comment]
it exists. `.mute 5 @someone`
