### ISSUE TITLE
Permissions interference

### ISSUE THREAD

**Issue by Jonz00r** [Kwoth/NadekoBot#1160]
Currently the Nadeko Permission system and Discord permission system interfere with one another. If I give someone the kick command in Nadeko and they don't have the discord kick command they won't be able to kick. Since the person would need both permissions then this makes the Nadeko Permission redundant. If I could make the Nadeko perms take precedence over Discord ones then I could force my moderators to use the Nadeko Command rather than discord functionality. This would help with keeping rogue moderators accountable since they would need to use commands to add roles, kick, ban, mute, anything. I've been in a few communities where we get rogue moderators and spend weeks trying to weed them out. This would help us greatly.

**Comment by Kwoth** [comment]
Not a bad idea but not possible really. Would be very messy too. Maybe something that can be done in the future.

**Comment by Jonz00r** [comment]
I hope you consider it. Currently it seems pointless to have commands if people are just going to use discord functionality anyway. Forcing them to use commands would be more auditable.
