### ISSUE TITLE
Suggestion : Voice Channel User Limit Adjustment

### ISSUE THREAD

**Issue by TheEffects** [Kwoth/NadekoBot#1166]
How hard would it be to implement the ability to adjust the user limit on  pre-existing voice channels?

**Comment by shikhir-arora** [comment]
That doesn't have anything to do with Nadeko. You mean the user limit you set in Discord that is optional to set, I assume?

**Comment by TheEffects** [comment]
Indeed, I was wondering whether it's possible to implement a command to adjust that for So that i don't have to give people the ability to fully change channels

**Comment by shikhir-arora** [comment]
Sadly no, that isn't anything Nadeko controls. Discord controls that, it has nothing to with NadekoBot.

**Comment by shikhir-arora** [comment]
What are you trying to accomplish at the end? Elaborate a bit :-)

**Comment by Kwoth** [comment]
Nah I won't be adding a command to control that
