### ISSUE TITLE
Error: Song not found. 

### ISSUE THREAD

**Issue by RiK2021** [Kwoth/NadekoBot#1167]
I keep getting an error with some youtube videos that says:

**20:35:21 CommandHandler | Command Errored after 1.1533381s
        User: RiK#1456 [112967817321533440]
        Server: Flame [240263294105944067]
        Channel: general [240263294105944067]
        Message: !!queue https://www.youtube.com/watch?v=gglhMDQdFms
        Error: Song is not found.**

Some videos do work, and the bot works with other commands and joins the channel I am in, but it doesn't queue the song. I'm currently on the most recent build of nadeko, tried to update, redo ffmpeg, run as admin, etc, but none of them have changed anything. Any ideas as to why?

**Comment by shikhir-arora** [comment]
Google API will reject certain songs due to region, copyright, etc. There isn't anything that can be done right now with that. 

Alternatives:

- Use `!!sq` (soundcloud link or search)

- Try a different video or `!!q` with keywords

**Comment by RiK2021** [comment]
I understand that may happen, but i've been able to queue these songs in the past, but they aren't queueing anymore. Was Youtube API changed in a way that disallowed these types of songs due to region, copyright, and others? If so, I'm probably just going to switch to Soundcloud for main music playlists, etc.

**Comment by shikhir-arora** [comment]
Yes, Google can do the following:

- Uploader requests change (restrict region, etc.)
- Monetization, etc. options from the uploader change the way the API works 
- Copyright claims against the video
- Internal update with certain endpoints 

and can go on and on, but it is very easy for certain things to change. Remember this is the official API. :-)

**Comment by RiK2021** [comment]
Ok, thank you. Switching to soundcloud.

Google and their API changes... tsk tsk ### (sarcasm).
