### ISSUE TITLE
Polls eventually stop with no result

### ISSUE THREAD

**Issue by senpaizuri3** [Kwoth/NadekoBot#1169]
I hope this is the right place to give an issue on Nadeko's standard bot issues. I started a poll, then gave myself a reminder for 5 days to close it. I went to close the poll and it didn't close. I messed with the permissions and eventually just went "fk it" and tried to make a test poll. The test poll succeeded. I made sure no results were shown and there were none. Some time in those 5 days, the poll ended without my recollection and I don't know why.

**Comment by rjt-rockx** [comment]
There was a bot restart in between, that probably would've messed with the poll.

**Comment by Kwoth** [comment]
Poll doesn't persist through restarts. There is no way for it to disappear like that otherwise.
