### ISSUE TITLE
Music still not working?

### ISSUE THREAD

**Issue by samiesaurus** [Kwoth/NadekoBot#117]
I noticed a few days ago that Nadeko's status mentioned music was down or not working, but we've still had issues trying to get her music side to work in our group chat. Constantly readded and installed her in there but with no luck. We trigger the command but she's unresponsive to anything music related.

**Comment by Kwoth** [comment]
use HaNadeko for music. Not NadekoBot, i had to split them. I will remerge them sometime soon
