### ISSUE TITLE
Game SneakyGame event

### ISSUE THREAD

**Issue by justinkruit** [Kwoth/NadekoBot#1170]
Hey,

How exactly does the SneakyGame event work? I've tried to find it out, but I simply couldn't understand the code behind it. For example, how exactly does it determine the word that is used?

**Comment by Kwoth** [comment]
![image](https://cloud.githubusercontent.com/assets/2537696/24800723/968c2198-1ba1-11e7-8c29-bfec6f7c1719.png)
![image](https://cloud.githubusercontent.com/assets/2537696/24800766/c4c57618-1ba1-11e7-8184-c958102119b5.png)
![image](https://cloud.githubusercontent.com/assets/2537696/24800774/cda4b992-1ba1-11e7-80dc-d114d95ea7a8.png)
