### ISSUE TITLE
Can't run with linuxAIO.sh

### ISSUE THREAD

**Issue by etshy** [Kwoth/NadekoBot#1171]
Hi

After installed all the pre-requisites I have this message in when I try to launch via linux AIO.sh (Part V of the tutorial)

```
Running NadekoBot. Please wait.
/root/NadekoBot/src/NadekoBot/NadekoBot.xproj(7,3): error MSB4019: The imported project "/opt/dotnet/sdk/1.0.1/Microsoft/VisualStudio/v14.0/DotNet/Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

The build failed. Please fix the build errors and run again.
Done
```

I launched on a dedicated server debian 8 x64

Thanks in advance for the help.

**Comment by samdivaio** [comment]
Looks like you manually installed .net core sdk, try removing it and installing with auto prerequisite installer or check out the manual section of the guide.

**Comment by etshy** [comment]
I tried first with prerequisite installer but I had a message "dotnet not installed. Please install it first." or something like that.

So I installed via the link given in the guide : https://www.microsoft.com/net/core#linuxdebian
And after that, the command netcode worked fine.

How can I delete all the netcode "framework" ?

**Comment by etshy** [comment]
After removing dotnet I launched the install for prerequisite and got this:
```
Running NadekoBot Auto-Installer
Your OS Debian 8 x64 probably can run Microsoft .NET Core.
Contact NadekoBot's support on Discord with screenshot.

Welcome back...

Welcome to NadekoBot.
1. Download Dev Build (Latest)
2. Download Stable Build
3. Run Nadeko (Normally)
4. Run Nadeko with Auto Restart (Run Nadeko normally before using this.)
5. Auto-Install Prerequisites (For Ubuntu, Debian and CentOS)
6. Set up credentials.json (If you have downloaded NadekoBot already.)
7. To Exit
Choose [1 or 2] to Download, [3 or 4] to Run, or [7] to Exit
```
Your OS Debian 8 x64 probably can run Microsoft .NET Core.
but I can't launch "dotnet" command now.

**Comment by etshy** [comment]
MAnaged to install it.

Seems thers is a problem in https://raw.githubusercontent.com/Kwoth/NadekoBot-BashScript/master/nadekoautoinstaller.sh to enter in 'Debian 8' elif.
I did the command in this elif manualy and it works well.

**Comment by samdivaio** [comment]
Probably some os related issue, I tested the installer just now on Debian 8.7 and it works fine for me.
Glad you made it work 👍🏻

**Comment by etshy** [comment]
Oh OK.
Well My Verison number and OS is well detected but the elif didn't work.
Well I don't know much about C# so can't say for sure there is something wrong.

Thanks o/
