### ISSUE TITLE
Unable to have @Nadeko replies

### ISSUE THREAD

**Issue by Fleshcrawler** [Kwoth/NadekoBot#1173]
I have gone through all the set up and set all permissions on a self hosted Nadeko. It replies back on everything but anything that is @Botname (example "@Botname die" does not work but .die does) is there any solution to this?

**Comment by xnaas** [comment]
IIRC nicknames break this. Does your bot have a nickname applied to it?

**Comment by Fleshcrawler** [comment]
Yes although I am replacing the @Botname with the @Nickname of the bot

**Comment by Kwoth** [comment]
Not sure what you're trying to acheive. 

If you have a custom reaction `.acr "%mention% die" rip` it will only work if the bot doesn't have a nickname.

**Comment by Fleshcrawler** [comment]
So none of the @mention commands under the conversation commands (like "@mention die" or "@mention do you like me") would work if there is a nickname to the bot?

**Comment by Kwoth** [comment]
there is no conversation module, and yes, they won't work. Update the bot.
