### ISSUE TITLE
Custom reaction placeholders do not work

### ISSUE THREAD

**Issue by Tremmert9** [Kwoth/NadekoBot#1177]
The placeholders for custom reactions do not seem to work, or I'm doing it wrong (I have tried every possible way, and none work).

Essentially, if you do:
`.acr "pat %target%" %user% pats %target%`
And then do `pat @someone` it will not output anything.

Tried to put %mention% instead of %target%, same result. Any solutions to this?

Cheers.

**Comment by Kwoth** [comment]
`.acr pat %user% pats %target%`

If `%target` is present in the response, custom reaction will take anything after the keyword and replace that with %target%
