### ISSUE TITLE
If I wanted to go about changing the command for >8ball to >conch, how would I go about that?

### ISSUE THREAD

**Issue by SourRocketJump** [Kwoth/NadekoBot#1179]
I checked in src\NadekoBot\Modules\Games\Commands, but I could not find the file that controls the >8ball command.

**Comment by Deivedux** [comment]
Just use the `.alias` command. Easy.

**Comment by SourRocketJump** [comment]
I'll try that. Thanks for the fast response :)

**Comment by DogeOps97** [comment]
Well, lol. It's not going to work tho. Putting anything after `>conch` renders it useless 🤔 woof

**Comment by SourRocketJump** [comment]
I tried it. It worked no problem.

**Comment by DogeOps97** [comment]
Oh woah. Ok lol, I typed the wrong thing. And yeah it worked
