### ISSUE TITLE
Korean Translator doesnt work

### ISSUE THREAD

**Issue by ThatzGaming** [Kwoth/NadekoBot#1180]
The bot cant translate english into korean it just keeps giving. 

~trans en>kr Hello
Bad input format, or something went wrong.

**Comment by infy147** [comment]
`KR` is not recognized as a language, as it isn't a language in `~translangs`. However, `KO` and `Korean` are, so use `~trans en>ko Hello` or `~trans en>korean hello`

**Comment by ThatzGaming** [comment]
thanks
