### ISSUE TITLE
(Feature Request) Error messages

### ISSUE THREAD

**Issue by rreminy** [Kwoth/NadekoBot#1182]
I would like for the bot to show some descriptive error messages on the discord channel and not just on the console like for example:

When you type
`!!q`

It doesn't give any feedback at all for the user, unless you're active looking at the console which its where it gives out the errors currently.

Would be nice if it says at least the error message, like for example:
`The input text has too few parameters.`
`Type "-h !!q" for help`

That would help us in figuring out what happened, what we need to do or similar. (The help part is a suggestion)

(Or alternatively, act as if `-h !!q` was typed instead)

If there's a way to turn them on as well like permissions have then my apologies. (Note: I haven't messed with permissions yet other than disabling the NSFW module)

**Comment by Kwoth** [comment]
Printing errors is out of the question, but actually a general error message with that command's help is useful. Good idea.

**Comment by Kwoth** [comment]
![image](https://user-images.githubusercontent.com/2537696/27033568-3cc27e52-4f7a-11e7-9b30-4bf3f6d2ac46.png)
