### ISSUE TITLE
(Feature Request) Automated creation of custom color roles

### ISSUE THREAD

**Issue by luizsan** [Kwoth/NadekoBot#1183]
**.usercolor** or **.uc** _#RRGGBB_
Creates a role tied to the user's name and/or ID and applies it to the command user. If the color parameter isn't specified, reset the role color to default. If the color parameter is specified, set the role color to the color parameter. If the role already exists, it only changes the color.

**Comment by Kwoth** [comment]
Just use 

.cr RoleName
.rc RoleName #colorhexhere
.sr RoleName @[User]

I'm not sure if i wrote the arguments in the right order, but something like that will work. The command you're requesting seems arbitrary and too specific.

**Comment by luizsan** [comment]
This goal of this suggestion is to let users have custom colors without being able to edit other users roles, which currently can't be accomplished using these commands as they require special permissions.
