### ISSUE TITLE
Repeater is not closing

### ISSUE THREAD

**Issue by DaYWhiTe** [Kwoth/NadekoBot#1190]
![adsiz](https://cloud.githubusercontent.com/assets/21060067/25279010/c5dc008c-26ad-11e7-9fa1-ab92f7ba9aea.png)

**Comment by Kwoth** [comment]
O.o 

type `.stats` and screenshot the response

**Comment by Kwoth** [comment]
Stop the bot, open your .db file, and execute `DELETE FROM REPEATERS` save changes and start the bot back up. However something is really weird with what you're showing me. If that doesn't fix it - you're running 2 bots at the same time.

**Comment by DaYWhiTe** [comment]
not fixed

**Comment by Kwoth** [comment]
? Repeaters are not showing up when you add them again?

**Comment by Kwoth** [comment]
You must've edited the source then.

**Comment by DaYWhiTe** [comment]
I certainly did not play with the codes.

**Comment by DaYWhiTe** [comment]
When you enter the patron code, the bot broken. He repeats it for him.

**Comment by DaYWhiTe** [comment]
fixed

**Comment by DaYWhiTe** [comment]
it repeat again. not fixed :(

**Comment by Kwoth** [comment]
No idea what you're referring to
