### ISSUE TITLE
:arrows_counterclockwise: stops the command

### ISSUE THREAD

**Issue by ImSnowy1** [Kwoth/NadekoBot#1192]
Hey! I have a issue , i tried to make an autobumper for my discord but the (:arrows_counterclockwise:) blocks it (Screen Shot Below)
[https://gyazo.com/19c9c96603e7c2f2b5820529ad62dc93](url)

What can i do?

**Comment by Deivedux** [comment]
That's not an issue, it's meant to do that.

**Comment by DogeOps97** [comment]
Nadeko can't take commands from itself either way o.o
