### ISSUE TITLE
Stop repeat

### ISSUE THREAD

**Issue by Pastakilla911** [Kwoth/NadekoBot#1193]
Hello,
I would like to know how to disable the command. .repeat of bot Nadeko ... Is it possible? If so how do I disable the command please?
Thank you for your attention.

**Comment by snipplets** [comment]
Have a look here
http://nadekobot.readthedocs.io/en/latest/Commands%20List/#permissions
Specifically something like`;rolecmd`, `;usrcmd` or `;srvrcmd` should serve

**Comment by Kwoth** [comment]
What snipplets said, however you maybe meant stopping a running repeater? use `-h .replst` and `-h .reprm`
