### ISSUE TITLE
[Feature Request] Trigger Global Custom Reactions by DMing the bot

### ISSUE THREAD

**Issue by IsogiEU** [Kwoth/NadekoBot#1196]
Not sure if possible, however in my use case I'd find it pretty helpful from a user point of view if global custom reactions could be triggered not only in the server, but also by DMing the bot.

**Comment by Kwoth** [comment]
Custom reactions aren't meant to be used in DMs. If you have rules or something similar as a custom reaction, you can use `.crad` and `.crdm` to make the triggering message be deleted, and response sent to DM.
