### ISSUE TITLE
User Account?

### ISSUE THREAD

**Issue by ImRyanFeng** [Kwoth/NadekoBot#1197]
How to use an User Account instead of a Bot User? (or is it possible / allowed)

**Comment by DogeOps97** [comment]
I don't see why it's not possible, but, from here https://github.com/hammerandchisel/discord-api-docs/issues/69#issuecomment-223898291

> self bots should not act like actual bots, i.e. they shouldn't respond to other people's commands, join servers on your behalf, etc... 

Just saying

**Comment by Kwoth** [comment]
You shouldn't do it. It can crash in some instances too since there are some checks which don't take into consideration the bot being a self-bot.
