### ISSUE TITLE
Failed to parse Int32 during waifu claim

### ISSUE THREAD

**Issue by Rishea** [Kwoth/NadekoBot#1199]
So the waifus on my server are really inflated, and we seem to be getting this error message

![image](https://cloud.githubusercontent.com/assets/28070655/25459041/0faa108a-2aa2-11e7-87b3-33948d278fd7.png)

If this is a known issue, is there a fix? Or is there any way to make it auto reset at a certain threshold? Do I have to go in and manually reset people in the DB file?

**Comment by DogeOps97** [comment]
![image](https://cloud.githubusercontent.com/assets/18622245/25463927/7433ecae-2aae-11e7-964d-48e4c21d843e.png)

Yep, it's way pass the limit o.o
