### ISSUE TITLE
[Help] Adding Commands

### ISSUE THREAD

**Issue by ethanjansen** [Kwoth/NadekoBot#1200]
I wanted to make a other auto commands like ~autohentai, and I believe all my code is correct, but the bot doesn't recognize them as commands.

**Comment by Kwoth** [comment]
Then it's not. You must Add the command in the appropriate namespace, and add it to CommandStrings.resx

I don't have time to support people who are editing the source, however you're free to make specific questions about how something works, but it's all pretty simple really.

**Comment by ethanjansen** [comment]
Thank-you. I forgot to add the commadn to CommandString.resx
