### ISSUE TITLE
Error: failed to start containers: nadeko

### ISSUE THREAD

**Issue by Mychy1** [Kwoth/NadekoBot#1201]
Hey, i have problem with bot, when i try to start it it give me this error 
`Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/nadeko/credentials.json\\\" to rootfs \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged\\\" at \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged/opt/NadekoBot/src/NadekoBot/credentials.json\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Error: failed to start containers: nadeko`

**Comment by Kwoth** [comment]
@Poag  needs to take a look at this

**Comment by Poag** [comment]
Please make your /nadeko/credentials.json file before starting the container up.

It can be blank but the file needs to exist before startup, else it tried to turn it into a folder.

**Comment by Mychy1** [comment]
@Poag so i made empty file like you said but it still not working 
`container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/nadeko/credentials.json\\\" to rootfs \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged\\\" at \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged/opt/NadekoBot/src/NadekoBot/credentials.json\\\" caused \\\"not a directory\\\"\""
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/nadeko/credentials.json\\\" to rootfs \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged\\\" at \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged/opt/NadekoBot/src/NadekoBot/credentials.json\\\" caused \\\"not a directory\\\"\""
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/nadeko/credentials.json\\\" to rootfs \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged\\\" at \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged/opt/NadekoBot/src/NadekoBot/credentials.json\\\" caused \\\"not a directory\\\"\""
standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/nadeko/credentials.json\\\" to rootfs \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged\\\" at \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged/opt/NadekoBot/src/NadekoBot/credentials.json\\\" caused \\\"not a directory\\\"\""
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/nadeko/credentials.json\\\" to rootfs \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged\\\" at \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged/opt/NadekoBot/src/NadekoBot/credentials.json\\\" caused \\\"not a directory\\\"\""
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/nadeko/credentials.json\\\" to rootfs \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged\\\" at \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged/opt/NadekoBot/src/NadekoBot/credentials.json\\\" caused \\\"not a directory\\\"\""
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/nadeko/credentials.json\\\" to rootfs \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged\\\" at \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged/opt/NadekoBot/src/NadekoBot/credentials.json\\\" caused \\\"not a directory\\\"\""
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/nadeko/credentials.json\\\" to rootfs \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged\\\" at \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged/opt/NadekoBot/src/NadekoBot/credentials.json\\\" caused \\\"not a directory\\\"\""
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/nadeko/credentials.json\\\" to rootfs \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged\\\" at \\\"/var/lib/docker/overlay2/b923388b5e2a792d01cf69f793a6d287a0c8efa2aaa49f372c1a448695ccbb45/merged/opt/NadekoBot/src/NadekoBot/credentials.json\\\" caused \\\"not a directory\\\"\""
standard_init_linux.go:178: exec user process caused "exec format error"
`

**Comment by Kwoth** [comment]
Was this resolved?
Poag seems very busy lately and I don't know enough about docker nor the time to go through it to troubleshoot it.

**Comment by Mychy1** [comment]
No, and i forget about it since its longe time so i dont even need it resolved now so u can close it. Thx for help.
