### ISSUE TITLE
Raspberry Pi support?

### ISSUE THREAD

**Issue by ethanjansen** [Kwoth/NadekoBot#1203]
I know this has been asked before, but is it possible to run nadeko bot with this on RPI 3b?https://dotnetcorechris.github.io/dotnetcoreonraspberrypi.html

If not, is it possible with exagear desktop and wine?

**Comment by Jonz00r** [comment]
I don't see why it wouldn't be if you're using Ubuntu. There's no harm in
trying it out.

**Comment by ethanjansen** [comment]
I believe I found a way to do it with an x86 dotnet core, but in the docs it says there isnt any x86 support. Why isnt there support?

**Comment by ColinCee** [comment]
Would be nice if we got some raspberry pi support

**Comment by Kwoth** [comment]
This is pretty much up to you guys, my rpi died, so I can't do it myself.

**Comment by samdivaio** [comment]
https://github.com/dotnet/core-setup

The guide https://dotnetcorechris.github.io/dotnetcoreonraspberrypi.html is for .NET Core Runtime.
.NET Core SDK still doesn't support 32bit linux https://github.com/dotnet/cli

**Comment by binnysenpai** [comment]
Someone buy Kwoth another rpi uwu

**Comment by Macley-Kun** [comment]
*throws link* 
http://www.dx.com/c/electrical-tools-499/arduino-scm-supplies-436/raspberry-pi-471

**Comment by hemipatu** [comment]
If someone was to buy you a Raspberry pi, how long roughly would it take to add support Kwoth?

**Comment by Kwoth** [comment]
no

**Comment by Taknok** [comment]
I manage to run the bot on Raspberry Pi 3. Is the dev team interested by it ? If yes, I will prepare a proper PR, because for the moment it was done to work, not for coding style. If not, I will keep my crappy stuff for me :)

The people of my server tried to make it crash during 1 hours without success for the moment. There will probably find something, but it's quite stable for the moment.

Info :
- Dotnet-2.0.2-preview2
- use of another package under apache 2 for easy build : this package have some lib needed, instead of building them myself, I used this package without calling it.

If you have any question feel free to ask :)

**Comment by Macley-Kun** [comment]
Wow this is amazing!! I rlly hope Kwoth will implement this. Tho he has no Raspberry to test/work on for himself. So only you would be able to 'fix' bugs or improve it.

**Comment by Taknok** [comment]
That's not a problem for me to 'fix' it. Plus it will be more and more easier to keep it updated with the evolution of .net core (roadmap have in cross compiling for arm and arm support). So at the end, Kwoth will be able to compile it from the same source code, just by changing the runtime target.

I detected one 'bug' for the moment : when I kill the program in a hard way (`ctrl + c`) it has around 50% chances to crash at reboot when the program try to load guildconf : missing key in dataset. I will investigate on this latter in the day. But if you don't cut the power or `ctrl + c` still no trouble.

**Comment by Taknok** [comment]
[Here](https://goo.gl/YnKdfQ) is own to run NadekoBot on raspberry.

**Comment by Macley-Kun** [comment]
@Taknok thx dude, I just thoughed about the Nadeko raspberry thing. It’s indeed handier to just fork from Kwoth and become a contributor.

Even tho I don’t have one, I’m surely happy to have this option now for in the future and all the people who own this little thing. Thanks for sharing dude!

**Comment by Macley-Kun** [comment]
@Kwoth is the discussion still relevant? Because the solution is now provided. Think you can close it if your ok with it.

**Comment by Kwoth** [comment]
I'll leave it open because it will be easier for people to find.

**Comment by ZMOT7S** [comment]
@Taknok @Kwoth I'm having an issue with trying to play music. The bot seems to be working correctly but when I search or link any song it says No Song Found in Discord and the following in SSH after using the ".q" command to queue a song. 

"12:31:41 E:\Documents\GitHub\NadekoBot\src\NadekoBot\Modules\Music\Common\SongResolver\Strategies\YoutubeResolveStrategy | System.ComponentModel.Win32Exception (0x80004005): No such file or directory"

Any idea what's going on?

**Comment by Taknok** [comment]
The issue is on raspberry ?

**Comment by ZMOT7S** [comment]
It's on the pi, yes. I assumed it had to do with the publish folder copying from windows to the pi. The directory is there on windows though, so it should have been transferred.

**Comment by Taknok** [comment]
On pi with raspbian or windows IoT ? Because for the moment the music module isn't working raspbian I had issues with the ffmpeg lib and now I have issues with my sd card :/ So I'm trying to fix it before starting again debugging.
Maybe we can move it to my repo, to avoid to bother Kwoth.

**Comment by Jimmy062006** [comment]
The channel ID's are UInt64 so can and does cause issues.

**Comment by cris11368** [comment]
Does anyone have any ideas what the publish string would be for Debian? I'm running this version that supports 64bit on an rpi3:
 https://github.com/bamarni/pi64 

I tried running the Ubuntu version on another distro using the publish from this string:
dotnet publish -r ubuntu.16.04-arm -c Release
creates but it gets stuck here:

ubuntu@ubuntu:~/publish$ ./NadekoBot
-1 10:05:54 ShardsCoordinator | Starting NadekoBot v2.13.3

And never progresses.

**Comment by Jimmy062006** [comment]
The issue for that is that the dependencies wont be available for arm. That is why its sat there doing nothing.

**Comment by Taknok** [comment]
If dependencies aren't available then the compilation should not display error ?

**Comment by Kwoth** [comment]
WIth the release of .net core 2.1, some newer versions of rpi will be supported

**Comment by nex86** [comment]
any news about this?
theres an RC of 2.1 but the guides how to install it on a pi are all for 2.0 or under.

**Comment by sleepymanakete** [comment]
all i found was info that 2.1 works on the pi. i coudn't find a guide for it, sadly.

**Comment by Taknok** [comment]
Indeed dotnet 2.1 works on raspberry : you can publish code for armhf (rasp's arch). But the version of Nadeko with shardmanager is very CPU consuming, so you can adapt the guidelines in my repo to the latest nadeko version, but you will only see "starting shard manager..." That's why I do not publish a new version of nadeko on rasp, until I find time to solve this issue. I prefer publish a old working solution instead of a non working brand new :) but if anyone find a way, I'm open to be helped !

**Comment by sleepymanakete** [comment]
if the shardmanager wasn't there, then nadeko could work on the pi?

**Comment by Taknok** [comment]
Maybe, we can try to remove it. There maybe be other bugs, but we have to try to know :)

**Comment by sleepymanakete** [comment]
ah, ok!

**Comment by nex86** [comment]
That's how far I got. 
the process always hung afterwards at 0% CPU and 5MB used RAM.
I couldn't manage to bring the bot online.

**Comment by Viscerous** [comment]
Has anyone made any strides towards this? I tried publishing this for ARM and I got as far as:
```
-1 16:20:16 ShardsCoordinator | Starting NadekoBot v2.24.3
-1 16:20:18 ShardsCoordinator | Images are already present in redis. Use .imagesreload to force update if needed.
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
-1 16:21:40 ShardsCoordinator | Shard 0 is scheduled for a restart because it's unresponsive.
-1 16:21:43 ShardsCoordinator | Auto-restarting shard 0
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

**Comment by Univa** [comment]
I was able to get Nadeko running on a Raspberry Pi Model 2B running Raspbian 9 (stretch) using the [.NET Core SDK 2.1 for ARM32](https://www.microsoft.com/net/download/dotnet-core/2.1).

More specifically, I downloaded [these binaries](https://download.microsoft.com/download/4/0/9/40920432-3302-47a8-b13c-bbc4848ad114/dotnet-sdk-2.1.302-linux-arm.tar.gz), extracted them into it's own folder, and added the folder to my $PATH.

Since the [auto installer](https://github.com/Kwoth/NadekoBot-BashScript/blob/1.9/nadekoautoinstaller.sh) wouldn't get past the architecture requirements, I had to install the dependencies manually.

I came across these errors when running the bot using `dotnet run -c Release` in `~/NadekoBot/src/NadekoBot`:
```
/home/pi/dotnet/sdk/2.1.302/Microsoft.Common.CurrentVersion.targets(4237,5): warning MSB3026: Could not copy "obj/Release/netcoreapp2.0/NadekoBot.pdb" to "bin/Release/netcoreapp2.0/NadekoBot.pdb". Beginning retry 1 in 1000ms. The process cannot access the file '/home/pi/NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/NadekoBot.pdb' because it is being used by another process.  [/home/pi/NadekoBot/src/NadekoBot/NadekoBot.csproj]
/home/pi/dotnet/sdk/2.1.302/Microsoft.Common.CurrentVersion.targets(4237,5): warning MSB3026: Could not copy "obj/Release/netcoreapp2.0/NadekoBot.pdb" to "bin/Release/netcoreapp2.0/NadekoBot.pdb". Beginning retry 2 in 1000ms. The process cannot access the file '/home/pi/NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/NadekoBot.pdb' because it is being used by another process.  [/home/pi/NadekoBot/src/NadekoBot/NadekoBot.csproj]
/home/pi/dotnet/sdk/2.1.302/Microsoft.Common.CurrentVersion.targets(4237,5): warning MSB3026: Could not copy "obj/Release/netcoreapp2.0/NadekoBot.pdb" to "bin/Release/netcoreapp2.0/NadekoBot.pdb". Beginning retry 3 in 1000ms. The process cannot access the file '/home/pi/NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/NadekoBot.pdb' because it is being used by another process.  [/home/pi/NadekoBot/src/NadekoBot/NadekoBot.csproj]
/home/pi/dotnet/sdk/2.1.302/Microsoft.Common.CurrentVersion.targets(4237,5): warning MSB3026: Could not copy "obj/Release/netcoreapp2.0/NadekoBot.pdb" to "bin/Release/netcoreapp2.0/NadekoBot.pdb". Beginning retry 4 in 1000ms. The process cannot access the file '/home/pi/NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/NadekoBot.pdb' because it is being used by another process.  [/home/pi/NadekoBot/src/NadekoBot/NadekoBot.csproj]
/home/pi/dotnet/sdk/2.1.302/Microsoft.Common.CurrentVersion.targets(4237,5): warning MSB3026: Could not copy "obj/Release/netcoreapp2.0/NadekoBot.pdb" to "bin/Release/netcoreapp2.0/NadekoBot.pdb". Beginning retry 5 in 1000ms. The process cannot access the file '/home/pi/NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/NadekoBot.pdb' because it is being used by another process.  [/home/pi/NadekoBot/src/NadekoBot/NadekoBot.csproj]
/home/pi/dotnet/sdk/2.1.302/Microsoft.Common.CurrentVersion.targets(4237,5): warning MSB3026: Could not copy "obj/Release/netcoreapp2.0/NadekoBot.pdb" to "bin/Release/netcoreapp2.0/NadekoBot.pdb". Beginning retry 6 in 1000ms. The process cannot access the file '/home/pi/NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/NadekoBot.pdb' because it is being used by another process.  [/home/pi/NadekoBot/src/NadekoBot/NadekoBot.csproj]
/home/pi/dotnet/sdk/2.1.302/Microsoft.Common.CurrentVersion.targets(4237,5): warning MSB3026: Could not copy "obj/Release/netcoreapp2.0/NadekoBot.pdb" to "bin/Release/netcoreapp2.0/NadekoBot.pdb". Beginning retry 7 in 1000ms. The process cannot access the file '/home/pi/NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/NadekoBot.pdb' because it is being used by another process.  [/home/pi/NadekoBot/src/NadekoBot/NadekoBot.csproj]
/home/pi/dotnet/sdk/2.1.302/Microsoft.Common.CurrentVersion.targets(4237,5): warning MSB3026: Could not copy "obj/Release/netcoreapp2.0/NadekoBot.pdb" to "bin/Release/netcoreapp2.0/NadekoBot.pdb". Beginning retry 8 in 1000ms. The process cannot access the file '/home/pi/NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/NadekoBot.pdb' because it is being used by another process.  [/home/pi/NadekoBot/src/NadekoBot/NadekoBot.csproj]
/home/pi/dotnet/sdk/2.1.302/Microsoft.Common.CurrentVersion.targets(4237,5): warning MSB3026: Could not copy "obj/Release/netcoreapp2.0/NadekoBot.pdb" to "bin/Release/netcoreapp2.0/NadekoBot.pdb". Beginning retry 9 in 1000ms. The process cannot access the file '/home/pi/NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/NadekoBot.pdb' because it is being used by another process.  [/home/pi/NadekoBot/src/NadekoBot/NadekoBot.csproj]
/home/pi/dotnet/sdk/2.1.302/Microsoft.Common.CurrentVersion.targets(4237,5): warning MSB3026: Could not copy "obj/Release/netcoreapp2.0/NadekoBot.pdb" to "bin/Release/netcoreapp2.0/NadekoBot.pdb". Beginning retry 10 in 1000ms. The process cannot access the file '/home/pi/NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/NadekoBot.pdb' because it is being used by another process.  [/home/pi/NadekoBot/src/NadekoBot/NadekoBot.csproj]
/home/pi/dotnet/sdk/2.1.302/Microsoft.Common.CurrentVersion.targets(4237,5): error MSB3027: Could not copy "obj/Release/netcoreapp2.0/NadekoBot.pdb" to "bin/Release/netcoreapp2.0/NadekoBot.pdb". Exceeded retry count of 10. Failed.  [/home/pi/NadekoBot/src/NadekoBot/NadekoBot.csproj]
/home/pi/dotnet/sdk/2.1.302/Microsoft.Common.CurrentVersion.targets(4237,5): error MSB3021: Unable to copy file "obj/Release/netcoreapp2.0/NadekoBot.pdb" to "bin/Release/netcoreapp2.0/NadekoBot.pdb". The process cannot access the file '/home/pi/NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/NadekoBot.pdb' because it is being used by another process. [/home/pi/NadekoBot/src/NadekoBot/NadekoBot.csproj]

The build failed. Please fix the build errors and run again.
```

To avoid this, I had to run it using `dotnet run -c Debug` instead.

**Comment by Viscerous** [comment]
@Univa Wow, that's pretty stupid of me. I could've sworn .NET Core SDK wasn't on ARM32 yet. I've tried it and the latest build runs for me as well, I haven't run into any issues yet either. Worth noting is that `dotnet run -c Release` worked fine for me.

**Comment by Kwoth** [comment]
@Univa means something else is using the bot, just reboot your server and run it again with -c Release (btw you might want to move your database file from the debug to the release folder, otherwise you'll start from 0 again)

**Comment by Viscerous** [comment]
Ah, this doesn't seem like a problem on this side but running it overnight resulted in a `Error in `dotnet': double free or corruption (fasttop)` which seems to be this issue: https://github.com/dotnet/coreclr/issues/18486

I figured I'd put a warning here in case anyone wanted to switch over.

**Comment by Univa** [comment]
Just to follow up, I was able to get rid of the build issues, but I still couldn't start the bot.
The bot takes a while to start up (over a minute and a half on my RPi 2B) and as a result, the Shard Coordinator thinks that its unresponsive, and restarts it automatically, making it fall into a reset loop. I had to manually adjust the delays in `ShardCoordinator.cs` to fix the issue.

**Comment by Viscerous** [comment]
@Univa Interesting, I've relaunched the bot a number of times on my RPi 3B+ but haven't had this issue until it crashed due to my last post here. Then it told me it was in use but perhaps it was just a coincidence. I'm not sure exactly how long it takes to boot but it's quite slow as well.

**Comment by Univa** [comment]
@Viscerous I also saw that dotnet error when I ran it overnight, but I didn't really think much of it. My bot also would fall into the reset loop when it crashed, but once again, changing the delays in `ShardCoordinator.cs` solved that.

I'm not sure if this is the best solution, but I manually increased the delays on line 121 and 305 to ensure that it doesn't think it's unresponsive:
```
//this is to avoid the shard coordinator thinking that
//the shard is unresponsive while starting up
var delay = 180;
```
```
//to prevent shards which are already scheduled for restart to be scheduled again
s.Time = DateTime.UtcNow + TimeSpan.FromSeconds(180 * _shardStartQueue.Count);
```

**Comment by sleepymanakete** [comment]
Did you guys follow one of the nadeko guides to run the bot and if so, which one? I tried "from source" and it doesn't work for me.

**Comment by Univa** [comment]
@sleepymanakete I just followed the [scripts](https://github.com/Kwoth/NadekoBot-BashScript/tree/1.9), and figured stuff out on my own.

Assuming you have the dependencies, you can try `dotnet restore; dotnet build -c Release` in ~/NadekoBot before running it. IIRC dotnet installs some other things when you run from source for the first time.

**Comment by sleepymanakete** [comment]
@Univa  Tried what you said and this is the error I keep getting. 
![image](https://user-images.githubusercontent.com/30272172/43611062-3d34ea54-9665-11e8-8b19-f22d38be4670.png)

**Comment by Viscerous** [comment]
@sleepymanakete I personally just installed all the dependencies `sudo apt install libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev unzip youtube-dl libopus0 opus-tools libopus-dev libsodium-dev ffmpeg tmux python python3-pip redis-server` and the newest .NET Core SDK and it ran.

@Univa Not sure how it goes for you but it seems like the dotnet issue can either crash a shard or the bot entirely. This time it only crashed a shard which it was able to restart since it became unresponsive, however it did leave a dotnet process with 100% CPU usage, so you might want to be careful.

**Comment by JiMMYBOOi** [comment]
I'm stuck here after installing.
```[root@alarmpi NadekoBot]# dotnet run -c Release
/home/alarm/NadekoBot/src/NadekoBot/NadekoBot.csproj : warning NU1603: NadekoBot.Core depends on Discord.Net (>= 2.0.0-beta2-00937) but Discord.Net 2.0.0-beta2-00937 was not found. An approximate best match of Discord.Net 2.0.0-beta2-00940 was resolved.
/home/alarm/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj : warning NU1603: NadekoBot.Core depends on Discord.Net (>= 2.0.0-beta2-00937) but Discord.Net 2.0.0-beta2-00937 was not found. An approximate best match of Discord.Net 2.0.0-beta2-00940 was resolved. [/home/alarm/NadekoBot/src/NadekoBot/NadekoBot.csproj]
/home/alarm/NadekoBot/src/NadekoBot/NadekoBot.csproj : warning NU1603: NadekoBot.Core depends on Discord.Net (>= 2.0.0-beta2-00937) but Discord.Net 2.0.0-beta2-00937 was not found. An approximate best match of Discord.Net 2.0.0-beta2-00940 was resolved.
/home/alarm/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj : warning NU1603: NadekoBot.Core depends on Discord.Net (>= 2.0.0-beta2-00937) but Discord.Net 2.0.0-beta2-00937 was not found. An approximate best match of Discord.Net 2.0.0-beta2-00940 was resolved.
Using launch settings from /home/alarm/NadekoBot/src/NadekoBot/Properties/launchSettings.json...
-1 16:50:56 ShardsCoordinator | Starting NadekoBot v2.28.4

Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 876
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 849
   at NadekoBot.Core.Services.ShardsCoordinator..ctor() in /home/alarm/NadekoBot/NadekoBot.Core/Services/ShardsCoordinator.cs:line 82
   at NadekoBot.Program.Main(String[] args) in /home/alarm/NadekoBot/src/NadekoBot/Program.cs:line 20
   at NadekoBot.Program.<Main>(String[] args)```
