### ISSUE TITLE
ParserError upon installing

### ISSUE THREAD

**Issue by otakueadwine** [Kwoth/NadekoBot#1204]
Im trying to install Nadeko so I can host it myself, but i keep getting this error when using the NadekoInstaller.bat:

![image](https://cloud.githubusercontent.com/assets/8110976/25568230/87984c2e-2dfe-11e7-8acf-a08d4dfa4876.png)

**Comment by Kwoth** [comment]
Try using both cmd and powershell to run the .bat

Make sure you're executing it properly. Also, redownload the .bat file.
