### ISSUE TITLE
[Feature Request] Ideas for the pokemon module

### ISSUE THREAD

**Issue by RinagiMai592** [Kwoth/NadekoBot#1205]
_I was told to post this here because it was too large for the discord channel._

Add stats to people like in the real pokemon games (hp,attack, defense, sp. atk, sp. def, speed). Make people have random stats rolled the first time they use the module. The databse can be based off real pokemon stats, so you'd be technically rolling for a specific pokemon but the name wouldn't be disclosed, unless you feel that would be something people would like. Additionally, since THERE ARE SO MANY POKEMON, use for the database only fully evolved pokemon. 

Instead of having 1 type, let people have 2 types (according to the pokemon they rolled). Instead of using >settype for 1 flower, remove that command altogether and change it for >rolltype, you'd be rolling your stats and type again (trying to get a better pokemon) and the initial cost would be 1 flower, but each time to roll it would cost double (so people with lots of flower don't keep rolling until they get a legendary pokemon stats). Each time you roll you keep your old moves. Add a moveshop where you can buy moves for flowers. Powerful moves would cost more flowers. Ignore Status inflicting moves and stat modifier moves if it's too much work.

Once stats are added to use the speed stat you'd need a >duel @ someone command and nadeko woud referee the match, saying the turn number and who's turn it is after each attack. To avoid a heavy server load you could restrict the number of duels you can have at the same time going per server. 

Adding a leveling system would be difficult because higher level people would stomp over new ones. So it'd be better to normalize all stats for a level 100 pokemon. 

As a last suggestion (as if all I'm saying is not enough work already), instead of being a pokemon ourselves, let people have up to 6 pokemon. You would get your first pokemon for free and then you could buy a "random pokeball" from the shop for 10 flowers. The >rolltype command could then have a numeric parameter to tell nadeko which pokemon you want to roll, each pokemon slot would have its own price counter (for the doubling price mechanic). 

People would love this.

**Comment by Kwoth** [comment]
I've moved it to suggestions channel
