### ISSUE TITLE
Plant sends error message but generally works (on pl-PL locale)

### ISSUE THREAD

**Issue by Pawiczekk** [Kwoth/NadekoBot#1206]
(I am hosting the bot on my PC)
When I use >plant command the bot says:
"I can't tell you if the command is executed, because there was an error printing out the response. Key 'games_planted' is not properly formatted. Please report this."
But after this it says that I can pick it up with >pick
Console doesn't show any errors (everything is white)
I checked and it's present on locale pl-PL but on en-US it doesn't send this

**Comment by Wizkiller96** [comment]
It means the response string is missing. So games_planted string isn't in the language response string. You can add the missing string or wait until it fixed.

**Comment by Kwoth** [comment]
It means it's there but has messed up placeholders. I will take a look.

**Comment by Kwoth** [comment]
Ok, fix is applied, but it will be available in 1.4
