### ISSUE TITLE
NadekoBot isn't reponding to any commands.

### ISSUE THREAD

**Issue by NoPrimesButWe** [Kwoth/NadekoBot#1209]
Hello,

I have 2 servers on Discord where we have Nadeko bot looking over everything, she's also a bot in a friends server. Today, however, in one of my servers and my friends, Nadeko has broken, she is completely unresponsive to all commands, we've tried booting her and re-inviting, attempting to reset her perms, but nothing is getting her to work.

**Comment by DogeOps97** [comment]
Nadeko is currently down on approximately 33150 servers atm welp
![image](https://cloud.githubusercontent.com/assets/18622245/25687914/12e9474c-302f-11e7-87ce-6fe9a85a9838.png) 

>.> It's been in disconnecting state for 2 hours, so I guess you'll have to wait until Kwoth restart the bot

**Comment by NoPrimesButWe** [comment]
Ah, gotcha, thanks for notifying me.

**Comment by Kwoth** [comment]
Restarting. Should be up in a few minutes.

**Comment by snipeknife** [comment]
not working for my server too. it is online and works on other servers. i even put the bot in my server again.

**Comment by Kwoth** [comment]
3 shards were dead, its' restarting now

**Comment by snipeknife** [comment]
thanks

**Comment by ThetaZom** [comment]
my server's nadeko bot is also down
