### ISSUE TITLE
Issue with new version?

### ISSUE THREAD

**Issue by FierceFrankie** [Kwoth/NadekoBot#121]
When I try to run the new version of the bot I get an error and it crashes. 

Failed loading configuration.
Google API key provided.
No trello appkey found. You will not be able to use trello commands.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at NadekoBot.NadekoBot.Main() in C:\Users\Master\Documents\Visual Studio 2015\Projects\NadekoBot\NadekoBot\NadekoBot.cs:line 79

**Comment by samdivaio** [comment]
You need to make the config example json file in \data to config.json

**Comment by omegavesko** [comment]
The [guide](https://github.com/Kwoth/NadekoBot/blob/master/ComprehensiveGuide.md) linked in README.md doesn't mention touching config.json. I'm assuming that's why OP was confused. Should it be updated?

**Comment by Kwoth** [comment]
89507a7d51abf2e1a9e7d335aef2a7b96fb268c8 @omegavesko 

updated, thanks
