### ISSUE TITLE
.asar not adding roles 

### ISSUE THREAD

**Issue by Rinokii** [Kwoth/NadekoBot#1213]
i added the bot new to a testserver to try and set her up once befor going in for real but i keep having the problem that she doenst react if i try to add a role with .asar as she doenst respond to it
![nadekoissue](https://cloud.githubusercontent.com/assets/28492611/25775751/ea680ca6-32ac-11e7-8fa2-1586e20b3e27.png)

i keep having the feeling that i have missed something, but the roles got full rights in all so i dont know what im missing

**Comment by Deivedux** [comment]
```Make sure that Nadeko's highest role is higher than any role you want Nadeko to interact with as well as Nadeko's role itself has enough permissions to do it so. Just give it admin since it always works out.```
A quote from discord server.

**Comment by DogeOps97** [comment]
The role need to exist first before making it self-assignable
