### ISSUE TITLE
[Feature Request] Custom Reactions - Imgur Album

### ISSUE THREAD

**Issue by ibigfire** [Kwoth/NadekoBot#1214]
It would be pretty awesome if it were possible to use random pictures from specified imgur albums as custom reaction responses.

So you could make Nadeko respond to someone saying "~panda" and it would pull a random image from http://imgur.com/gallery/CVJw1 and respond with it.

Not necessarily the greatest example, but I'm sure there are many uses for people to set up their own imgur albums custom to their channels that it would be useful for.

I feel like this particular endpoint should be handy for getting it done, but I'm not good enough to fully know how to implement it:

https://api.imgur.com/endpoints/gallery#gallery-random

**Comment by Kwoth** [comment]
Interesting idea.

**Comment by Kwoth** [comment]
I added just querying using tags, I don't want to use imgur api at this point. You're free to suggest it here http://feathub.com/Kwoth/NadekoBot but I doubt it will be implemented anytime soon.

You can use `%img:cat% placeholder for example, to get a cat image`. I'll push it in a few minutes
