### ISSUE TITLE
NadekoBot being unresponsive.

### ISSUE THREAD

**Issue by MovingBlast** [Kwoth/NadekoBot#1220]
It seems my life hates me today with the amount of issues I'm having with NadekoBot...

Basically, after I finally got it online I thought I had it working, after half an hour I decided to talk to it like for example "@Nadeko Hello!" and after a minute, still nothing.

I decided to venture out onto other servers that had Nadeko running and had noticed that it would respond back to me when I asked the exact same thing. I googled the internet and I've found nothing, so either I'm an idiot, Or this world hates me...

Help would be nice! :3

**Comment by ScarletKuro** [comment]
If u want it to response, you have to use this command first >cleverbot

**Comment by MovingBlast** [comment]
Hello there and thanks for replying.

Since I am quite new to programming(but would be willing to learn), I have no idea on how to enter the command. A reply would be nice, thank you.

**Comment by shikhir-arora** [comment]
Type `>cleverbot` in the channel where your bot is and it should say "Enabled CleverBot..." 

Then, proceed and it should work.

**Comment by MovingBlast** [comment]
Hello!

I tried typing in "@Nadeko >clever bot" & ">cleverbot" by itself as well but I haven't gotten the message.

**Comment by DogeOps97** [comment]
Enable cleverbot in the server using `>cleverbot`, then chat with Nadeko by mentioning the bot in front `@Nadeko hi` 

![image](https://cloud.githubusercontent.com/assets/18622245/25973566/8221741a-3659-11e7-8f6e-6fdd9ce07630.png)

**Comment by MovingBlast** [comment]
nvm, It responded to me now, Thanks!
