### ISSUE TITLE
No flowers

### ISSUE THREAD

**Issue by wyattFegert** [Kwoth/NadekoBot#1221]
Nadeko Flowers don't work on my server, no matter what I do, everyone has 0.
I tried awarding, I tried winning trivia, and I've looked for ways to set it up, but no results. Pls halp.

**Comment by Deivedux** [comment]
You can get free 100 flowers from flower events in the Nadeko support server if you are not there already. At the moment this is the only way to get free flowers. Type `-h` in server where you have Nadeko or in Nadeko bot DM to get the invite link to there.
