### ISSUE TITLE
[Feature Request] Titles of musics in a playlist

### ISSUE THREAD

**Issue by Dragonink** [Kwoth/NadekoBot#1223]
I tried to __change the title of a music in a playlist using the database__, but the name of the file (like *rand0mNam.mp4*) appeared.

**Is it possible to change this and allow to edit track names in the playlist database ?**

**Comment by Deivedux** [comment]
If you are talking about the local files, you have to edit the name of the file itself.
Don't know if that is what you are asking tho 👀

**Comment by Kwoth** [comment]
Its not possible, and it won't be possible. Names are taken from the service/place the music is queued from, not from the database.

**Comment by Jonz00r** [comment]
You'll have to edit the metadata I believe. I think you can do this in
foobar or songbird.
