### ISSUE TITLE
"git not found" even though I installed Git?

### ISSUE THREAD

**Issue by Poccket** [Kwoth/NadekoBot#1225]
I installed Git and .NET for my system, but whenever I run the NadekoInstaller and it gives me this error
![image](https://cloud.githubusercontent.com/assets/25379215/26262656/211a211a-3c9b-11e7-95d4-2a551d11d143.png)
Not sure what I'm doing wrong, because I can run Git Bash

**Comment by Deivedux** [comment]
Make sure you used this option while installing git:
![4w5ec4m](https://cloud.githubusercontent.com/assets/25952144/26262890/15131d60-3cdf-11e7-9a0c-8ddbf44c8154.png)

**Comment by Poccket** [comment]
@Deivedux This worked! Thank you.
