### ISSUE TITLE
Generate Currency issue

### ISSUE THREAD

**Issue by Aip0** [Kwoth/NadekoBot#1228]
everytime i try to use >gc <any value>, an error message is shown and it says:

CommandHandler | Command Errored after 0/0/0/0s
User: <my user> [My user ID]
Server: <my server> [My server id]
Channel: <channel name> [server id]
Message: >gc
Error: The input text has too many parameters.

**Comment by Deivedux** [comment]
You don't need to specify any parameters, simply type `>gc`. If you want to change something how currency generation behaves you can edit it in the database.

**Comment by Jonz00r** [comment]
Not a terrible Idea to have that functionality though.
