### ISSUE TITLE
[Feature Suggestion] NSFW Image Filter/Scanner (Clarifai)

### ISSUE THREAD

**Issue by roxaskeyheart** [Kwoth/NadekoBot#1229]
Hi there,

I recently implemented a NSFW filter for images into our forked NadekoBot and I thought I would share that implementation in-case you wished to add it to the main program. The code is still a bit messy, but does seem to work well.

This filter works by using the Clarifai NSFW API (https://www.clarifai.com) and as such needs an API token, which can be obtained for free at the above link. My code steps through three different types of Discord messages: Image Embeds, Attachments and raw image URLs and attempts to get a response from Clarifai from each (in that order) before attempting the next.

When a valid URL is received from Clarifai, the API responds with a JSON string (parsed into an object model) with a double (between 0.0 and 1.0) to determine the probability of a NSFW image.
_**Reference:** https://developer.clarifai.com/models/nsfw-image-recognition-model/e9576d86d2004ed1a38ba0cf39ecb4b1_

I receive that returned double and checks if the value is >0.85 (high probability of NSFW) and if so, removes the posted message. The code is pretty basic and relies on no Nadeko commands, however I could see the following commands being nice to have:

**.nsfwimagefilter 85** - Toggles NSFW image filter on this server with a tolerance of 85%.
**.nsfwimagefilterignore** - Tells NSFW image filter to ignore this channel.

**Models**

        public class Status
        {
            public int code { get; set; }
            public string description { get; set; }
        }

        public class Status2
        {
            public int code { get; set; }
            public string description { get; set; }
        }

        public class OutputInfo
        {
            public string message { get; set; }
            public string type { get; set; }
        }

        public class Status3
        {
            public int code { get; set; }
            public string description { get; set; }
        }

        public class ModelVersion
        {
            public string id { get; set; }
            public string created_at { get; set; }
            public Status3 status { get; set; }
        }

        public class Model
        {
            public string name { get; set; }
            public string id { get; set; }
            public string created_at { get; set; }
            public object app_id { get; set; }
            public OutputInfo output_info { get; set; }
            public ModelVersion model_version { get; set; }
        }

        public class Image
        {
            public string url { get; set; }
        }

        public class Data
        {
            public Image image { get; set; }
        }

        public class Input
        {
            public string id { get; set; }
            public Data data { get; set; }
        }

        public class Concept
        {
            public string id { get; set; }
            public string name { get; set; }
            public object app_id { get; set; }
            public double value { get; set; }
        }

        public class Data2
        {
            public List<Concept> concepts { get; set; }
        }

        public class Output
        {
            public string id { get; set; }
            public Status2 status { get; set; }
            public string created_at { get; set; }
            public Model model { get; set; }
            public Input input { get; set; }
            public Data2 data { get; set; }
        }

        public class NSFWModel
        {
            public Status status { get; set; }
            public List<Output> outputs { get; set; }
        }

**Implementation (CommandHandler.cs)**

        private async Task<bool> IsImageUrlAsync(string URL)
        {
            //This function is used to determine if a posted URL is an image. This does not work with HTTPS errors however.

            Uri targetUriA;
            Uri targetUriB;
            try
            {
                if (Uri.TryCreate(URL, UriKind.RelativeOrAbsolute, out targetUriA))
                {
                    var req = (HttpWebRequest)WebRequest.Create(URL);
                    req.Method = "HEAD";
                    var resp = await req.GetResponseAsync();
                    return resp.ContentType.ToLowerInvariant().StartsWith("image/");
                }
            }
            catch
            {
                try
                {
                    if (Uri.TryCreate(@"http://" + URL, UriKind.RelativeOrAbsolute, out targetUriB))
                    {
                        var req = (HttpWebRequest)WebRequest.Create(@"http://" + URL);
                        req.Method = "HEAD";
                        var resp = await req.GetResponseAsync();
                        return resp.ContentType.ToLowerInvariant().StartsWith("image/");
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Error: " + ex.Message);
                }
            }

            return false;
        }

       public string ClarifaiTagging(string url)
        {
            //Implementation of Clarifai API. Sends URL as a JSON POST request and fetches response.

            const string ACCESS_TOKEN = "ACCESS_TOKEN_HERE";
            const string CLARIFAI_API_URL = "https://api.clarifai.com/v2/models/e9576d86d2004ed1a38ba0cf39ecb4b1/outputs";

            using (HttpClient client = new HttpClient())
            {
                // Set the authorization header
                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + ACCESS_TOKEN);
                
                HttpContent json = new StringContent(
                    "{" +
                        "\"inputs\": [" +
                            "{" +
                                "\"data\": {" +
                                    "\"image\": {" +
                                        "\"url\": \"" + url + "\"" +
                                    "}" +
                               "}" +
                            "}" +
                        "]" +
                    "}", Encoding.UTF8, "application/json");

                // Send the request to Clarifai and get a response
                var response = client.PostAsync(CLARIFAI_API_URL, json).Result;

                // Check the status code on the response
                if (!response.IsSuccessStatusCode)
                {
                    // End here if there was an error
                    return null;
                }

                // Get response body
                string jsonX = response.Content.ReadAsStringAsync().Result.ToString();
                NSFWModel model = JsonConvert.DeserializeObject<NSFWModel>(jsonX);
                
                //Get value of NSFW probability (makes sure it is the NSFW probability and NOT the SFW probability)
                var nsfwval = model.outputs.FirstOrDefault().data.concepts.Find(t => t.name == "nsfw").value;
                if (nsfwval > 0.85)
                {
                    return "nsfw";
                }

                return "sfw";
            }
        }`

        private async Task<bool> NSFWFiltered(IGuild guild, IUserMessage usrMsg)
        {
            //Main Function to implement NSFW Image Filtering

            //Check against NSFW channels - hardcoded for now.
            if (usrMsg.Channel.Name == "nsfw-thewilderness" || usrMsg.Channel.Name == "nsfw") return false;

            var message = usrMsg.Content;
            var embeds = usrMsg.Embeds;
            var attatchs = usrMsg.Attachments;
            
            //Check image embed types
            if (embeds != null)
            {
                foreach (var embed in embeds)
                {
                    if (embed.Type == "image")
                    {
                        var tag = ClarifaiTagging(embed.Url);

                        if (tag != null)
                        {
                            if (tag == "nsfw")
                            {
                                try
                                {
                                    //Delete Message
                                    await usrMsg.DeleteAsync().ConfigureAwait(false);
                                }
                                catch
                                {
                                    _log.Warn("I do not have permission to filter words in channel with id " + usrMsg.Channel.Id);
                                }

                                //Implements a log to the logging channel
                                //await LogToLoggerAsync(usrMsg.Author.Username, usrMsg.Channel.Name, message, guild);
                                return true;
                            }
                        }
                        else
                        {
                            Console.WriteLine("null error A"); //Clarifai couldn't parse request
                        }
                    }
                }
            }

            //Check attachement types
            if (attatchs != null)
            {
                foreach (var attatch in attatchs)
                {
                    var tag = ClarifaiTagging(attatch.Url);

                    if (tag != null)
                    {
                        if (tag == "nsfw")
                        {
                            try
                            {
                                //Delete Message
                                await usrMsg.DeleteAsync().ConfigureAwait(false);
                            }
                            catch
                            {
                                _log.Warn("I do not have permission to filter words in channel with id " + usrMsg.Channel.Id);
                            }

                            //Implements a log to the logging channel
                            //await LogToLoggerAsync(usrMsg.Author.Username, usrMsg.Channel.Name, message, guild);
                            return true;
                        }
                    }
                    else
                    {
                        Console.WriteLine("null error B");
                    }
                }
            }

            //Finally check raw post URLs (does not support HTTPS)
            var linkParser = new Regex(@"\b(?:https?://|www\.)\S+\b", RegexOptions.Compiled | RegexOptions.IgnoreCase);
            foreach (Match m in linkParser.Matches(message))
            {
                bool ret = await IsImageUrlAsync(m.Value);
                if (ret)
                {
                    var tag = ClarifaiTagging(m.Value);

                    if (tag != null)
                    {
                        if (tag == "nsfw")
                        {
                            try
                            {
                                //Delete Message
                                await usrMsg.DeleteAsync().ConfigureAwait(false);
                            }
                            catch
                            {
                                _log.Warn("I do not have permission to filter words in channel with id " + usrMsg.Channel.Id);
                            }

                            //Implements a log to the logging channel
                            //await LogToLoggerAsync(usrMsg.Author.Username, usrMsg.Channel.Name, message, guild);
                            return true;
                        }
                    }
                    else
                    {
                        Console.WriteLine("null error C");
                    }
                }
            }

            return false;
        }

Above code is called in the **TryRunCommand** method within CommandHandler.cs.

            if (guild != null && guild.OwnerId != usrMsg.Author.Id)
            {
                if (await InviteFiltered(guild, usrMsg).ConfigureAwait(false))
                    return;

                if (await WordFiltered(guild, usrMsg).ConfigureAwait(false))
                    return;

                if (await NSFWFiltered(guild, usrMsg).ConfigureAwait(false))
                    return;
            }

**Comment by Kwoth** [comment]
Thanks a lot for sharing, that's very kind of you. However, how does this improve upon discord's own NSFW detection feature?

**Comment by roxaskeyheart** [comment]
Well I haven't seen Discord's NSFW detection kick in at all so far, in fact when i posted some very nsfw pictures to test the above code nothing happened on Discord's part - wheras Clarifai hits it straight away and allows you to set up a tolerance given the way it works.

So I don't know i guess, the reason I implemented the above is because people kept posting stuff which Discord didn't pick up which i should have, despite having all the moderation settings active and all that.

**Comment by Kwoth** [comment]
Alright, when I'm done with 1.41, I'll take a closer look at this.

**Comment by Kwoth** [comment]
Sorry but no, there isn't enough time, and it requires an api key. You could repost it on feathub once it's back online, and let the people decide :)

**Comment by happyhourarcade** [comment]
Will this work with 1.3b? Would like to test
