### ISSUE TITLE
~IMDB Returns 401

### ISSUE THREAD

**Issue by TwinDragon** [Kwoth/NadekoBot#1230]
So as I found out today out of randomness, the ~imdb command in the console is returning a 401 (Unauthorized) message. Not sure if the API has been closed, or something changed with IMDB, but figured I'd open this ticket to let people know.

**Comment by rjt-rockx** [comment]
API has changed, it'll be updated in the code soon.

**Comment by Kwoth** [comment]
This will be a top priority starting tomorrow.

**Comment by TwinDragon** [comment]
Awesome. This isn't a big issue for me, just something I was pointing out.

**Comment by Kwoth** [comment]
Fixed in 1.4
