### ISSUE TITLE
[Feature Request] allow commands in custom reactions

### ISSUE THREAD

**Issue by JSalazarII** [Kwoth/NadekoBot#1233]
Allowing the bot to run commands through custom reactions would be useful for some servers. servers with an RP/RPG channel, or themed servers, could use it to overload a command in a user-friendly way, and it lets admins be creative with the bot's functionality, which is never a bad thing.

Ex: .acr "greatword attack %target%" %user% attacks the %target% with their greatsword! They get a <.roll 1d20>, doing <.roll 1d10> damage if they hit!

**Comment by Kwoth** [comment]
Just use %rng% placeholder `They get a %rng1-20%, doing %rng1-10% damage if they hit!`

http://nadekobot.readthedocs.io/en/latest/Custom%20Reactions/

**Comment by JSalazarII** [comment]
I read the documentation, that was just one example Kwoth. As I said, this would allow servers to overload commands in a user-friendly way and be creative with anything from permissions to the games system, and add flavor to their servers. 

I'm not familiar with the discord bot API, but it seems like even just allowing the bot to recognize commands in its own comments would work, perhaps with a depth counter to prevent infinite loops. Unless discord API filters the bots comments on its own, that shouldn't be too hard.

**Comment by Kwoth** [comment]
Nah, it's not something I'm interested in doing. And it's very complex
