### ISSUE TITLE
[Feature Request] Youtube Stream Notification

### ISSUE THREAD

**Issue by Crazierinzane** [Kwoth/NadekoBot#1236]
I don't think this is in, and I'm not sure what happened to the idea in 2016. If it wasn't possible then, I'm guessing something may have changed because I've seen another bot do it recently. Hopefully, that is the case.

Feature request. Please add Youtube stream notification option for channels.

**Comment by Kwoth** [comment]
There are no plans to add it as of right now, you can add that suggestion to the #suggestions channel on the #NadekoLog server when it reopens.

**Comment by Crazierinzane** [comment]
Whatever, I'll just do it myself.
