### ISSUE TITLE
[Feature Request] Direct Image Custom Reactions

### ISSUE THREAD

**Issue by TheoLeeTho** [Kwoth/NadekoBot#1237]
Hello! I wanted to request a feature that would be in a lot of use in my personal (and probably many other) servers.
I'd like to request of the bot to be able to upload images directly as custom reactions.
That would be very useful as most of my server relies/has funny jokes revolving around custom reaction images.

As of today I simply add a direct link to the image as a custom reaction.
So for example, if you write "wat" a gif of the blinking white guy meme will appear as a direct link.

However, that also shows the link in the chat which is quite unpleasing to me.

It would be wonderful if the bot could upload/store images somewhere in the folder or database that we can use to attach to custom reactions! 

Thank you in advance.

**Comment by Deivedux** [comment]
The thing is, if that would be possible it would be a thing already for a while now. Bots simply can't read images from other users, just like you would do `.acr "trigger"` and the image, the bot won't be able to register it and there is nothing you can really do unless you build it that yourself by source editing.

**Comment by TheoLeeTho** [comment]
Isn't it possible the bot to read the direct link we send to the image and send it in the chat as an attachment instead of pasting its link?

**Comment by Kwoth** [comment]
Yes, use embed builder.

http://www.nadekobot.me/embedbuilder/

for example `.acr "image test" {"image":"http://i.imgur.com/mna03Ke.jpg","color":7458112}`
