### ISSUE TITLE
Alias Bug

### ISSUE THREAD

**Issue by Elohmro** [Kwoth/NadekoBot#1238]
I created an alias for `.prune` like so:
```.alias ".p" .prune```
When I type `.p 1`, it types in chat two messages; one message for me, and one from the bot that shows what the alias path is. It then deletes 1 message, however I have .delmsgoncmd toggled on, so it deletes the second. When I type `.p 2`, it types in chat the two messages, then deletes them both. When I type `.p 3`, it types in chat two messages, then it deletes both AND one above. The alias should just be that when I type `.p 1` it deletes the messages that it creates AND 1 message. I think this is a bug?

Console log:

```Markdown
00:53:22 CommandHandler | --Mapping Command--
    GuildId: 229710716100149249
    Trigger: .p 1
    Mapping: .prune 1
00:53:23 NadekoModule | Culture info is en-US
00:53:23 CommandHandler | Command Executed after 0/0/0/0.41s
        User: ElohmroW#0881 [229673776638328832]
        Server: CRTRTS [229710716100149249]
        Channel: testing [316746331286798356]
        Message: .p 1
00:53:24 CommandHandler | --Mapping Command--
    GuildId: 229710716100149249
    Trigger: .p 2
    Mapping: .prune 2
00:53:24 NadekoModule | Culture info is en-US
00:53:24 CommandHandler | Command Executed after 0/0/0/0.387s
        User: ElohmroW#0881 [229673776638328832]
        Server: CRTRTS [229710716100149249]
        Channel: testing [316746331286798356]
        Message: .p 2
00:53:25 CommandHandler | --Mapping Command--
    GuildId: 229710716100149249
    Trigger: .p 3
    Mapping: .prune 3
00:53:25 NadekoModule | Culture info is en-US
00:53:26 CommandHandler | Command Executed after 0/0/0/1.323s
        User: ElohmroW#0881 [229673776638328832]
        Server: CRTRTS [229710716100149249]
        Channel: testing [316746331286798356]
        Message: .p 3
```

https://gyazo.com/54426ebf5f2cd48cadfad55f992273f3

**Comment by Kwoth** [comment]
Prune is a special case for delmsgoncmd, so aliasing it breaks that special case check, and starts behaving the way you don't want it again. I'd advise not putting alias on .prune
