### ISSUE TITLE
[Feature Request] Custom Commands Module

### ISSUE THREAD

**Issue by Elohmro** [Kwoth/NadekoBot#1239]
***Custom Commands Module***

*The main part of it:*

$[Character] = variable

***Alias -> One Output:***

*Kind of like Custom Reactions, but with multiple variables*
*You could do this just by adding multiple variables to Custom Reactions*

`.acc` - add custom command
.acc "command" "variable" "output"

**Example:**

`.acc "/test" "$1 $2 $3" "Hello, $1, welcome to $2, where you can $3."`

*If you run that alias:*

`/test user github code`

*Output:*

Hello, user, welcome to github, where you can code.

***Alias -> Multiple Outputs:***

.acc "command" "variable" "output 1" "output 2" etc.

**Example:**

`.acc "/test" "$1 $2 $3 $4" ".sr $1 $2" ".sr $1 $3" ".sr $1 $4"` (I'm using the .setrole command as an example, set multiple roles for one person at once is one function of this)

*If you run that alias:*

`/test @User#1234 Role1 Role2 Role3`

*Output:*

`.sr @User#1234 Role1`
`.sr @User#1234 Role2`
`.sr @User#1234 Role3`

***Custom Command Deletion:***

*All custom commands are written into a database*

`.dcc [Id]` - deletes custom command based on Id

***Permissions Module Integration:***

*Same Syntax as `.sc` `.uc` `.rc` `.cc`*

`.scc` - server based for custom command
`.ucc` - user based for custom command
`.rcc` - role based for custom command
`.ccc` - channel based for custom command

**Comment by Kwoth** [comment]
You can move this to #suggestions channel when it opens. I considered some options but no, this would take too much work and won't happen anytime soon.
