### ISSUE TITLE
NSFW commands should be disabled by default when joining new servers

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#124]
People who run NSFW commands should get a helpful message saying how to enable it.

**Comment by appelemac** [comment]
Is this only for joining new servers through an invite, so it should be enabled in servers that the bot already has when it is first set up?

**Comment by Kwoth** [comment]
@appelemac should be simple to add, just need to edit permissions constructor and add nsfw module automaticaly there
