### ISSUE TITLE
[Feature Request] Official Cleverbot

### ISSUE THREAD

**Issue by Gremagol** [Kwoth/NadekoBot#1240]
Dear Botmaster, 
it would be nice for Selfhosters to add support for the Official Cleverbot by using this wrapper:

[https://github.com/velddev/Cleverbot.Net](url)

And for people, who do not want it, you could make a command which toggles them.
For example: .togglecleverbot .tclvbt

I wanted to create this suggestion, because the actual cleverbot-api is sometimes very, very slow and only in english. 
Teaching new answers doesn't work so the answers will be the same everytime. I think there are many people out there who think the same. 
Please, take at least a look at it when you have time.

Greetings.

**Comment by xnaas** [comment]
The problem, @Gremagol, is that Cleverbot is no longer free. That's why Nadeko dropped it.

Source: http://www.cleverbot.com/api/

**Comment by Gremagol** [comment]
Nadeko doesnt even have to use it, I was talking about the Selfhosters.
Because selfhosters can "buy" the free api which provides 5000 calls.

**Comment by Kwoth** [comment]
Please move this to http://feathub.com/Kwoth/NadekoBot
