### ISSUE TITLE
[Question] Random Currency Amounts?

### ISSUE THREAD

**Issue by Alison-Sera** [Kwoth/NadekoBot#1241]
Finally found the BotConfig table in NadekoBot.db , and pinned down (I think) that CurrencyDropAmount is how much currency can be picked up when it spawns. My question is how can I make it a random number within a set of numbers, like say, one to one hundred?

**Comment by Kwoth** [comment]
You can't atm.

**Comment by Kwoth** [comment]
Added `CurrencyDropAmountMax` field to 1.42 which, if set, makes your currency generation drop random amount of flowers between `DropAmount` and `DropAmountMax`, inclusive.
