### ISSUE TITLE
[Enhancement Request] Custom Reactions

### ISSUE THREAD

**Issue by Elohmro** [Kwoth/NadekoBot#1243]
It would be really cool if you can have those fancy embedded messages have placeholders such as %user% and %target% for custom reactions. Then it would be easy to make "more professional" looking reactions for people whenever someone triggers a reaction.

It would also be nice if you could set permissions on certain custom reactions, and not just the whole module, so not all users can some of the reactions them while some can't. That way you can have permissions for literally everything! All of the permissions...

**Comment by Kwoth** [comment]
It's already in the #suggestions channel. I need to rewrite the crappy Custom reaction logic to make this happen. Probably in 1.43 or later version.
