### ISSUE TITLE
NadekoBot updater for Linux doesn't work

### ISSUE THREAD

**Issue by FlashingYoshi** [Kwoth/NadekoBot#125]
```
Failed to load /home/john/Downloads/ubuntu.14.04-x64/publish/libcoreclr.so, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to coreclr
```
^ This happens when I try to run nadekoupdater.

Is there a dependency I am missing?

**Comment by Kwoth** [comment]
Can you verify that file actually exists (/home/john/Downloads/ubuntu.14.04-x64/publish/libcoreclr.so)

if it does not, you didn't extract properly, because i can clearly see it in the zip

**Comment by FlashingYoshi** [comment]
libcoreclr.so exists.

**Comment by Kwoth** [comment]
Try installing dotnet cli from https://dotnet.github.io/getting-started/ and try again.

Also, do you have 32bit linux? If so, it wont work.

If it still won't work, you can pull the repo, type 
`dotnet restore`
`dotnet publish`
 and run the produced build.

Nothing else can be done to help you
