### ISSUE TITLE
Shards Thing

### ISSUE THREAD

**Issue by YamiyoYamxiy** [Kwoth/NadekoBot#1252]
Isn't possible do a script to check shards and restart the bot if the counts isn't appropriated?
Like auto do the .shards thing if the result is less than a defined percentage it restart the bot? Maybe something to force a defined `uptime` ?!

Actually can go deeper and make check's to guilds, voice connects (when using the music module - *it actually exist I think?!*).

**Comment by Kwoth** [comment]
No, it's normal for shards to reset connection,, if the check triggers when they're down, it will needlessly restart.  Anyway shards issue will be hopefully gone when i upgrade public bot to 1.4x
