### ISSUE TITLE
Don't re-join voice channels the bot is already in

### ISSUE THREAD

**Issue by Pluckerpluck** [Kwoth/NadekoBot#1258]
So something that can be quite annoying is that at at the start of every song the bot tries to join the voice channel.

However, even if it's already in the channel this triggers the "User Joined" notification, which means every song starts with a "bong" for people who have this enabled.

So it would be pretty good that if it were already in the channel it wouldn't try to re-join.

**Comment by Kwoth** [comment]
it's already removed in latest version. update.

**Comment by Pluckerpluck** [comment]
I use docker. Should I be pulling "1.4" as "latest" seems to be the oldest of all of them and points to version 1.3b.

I'd literally just pulled it before posting the issue so I had thought I was up to date.

**Comment by Kwoth** [comment]
yup http://nadekobot.readthedocs.io/en/latest/guides/Docker%20Guide/
