### ISSUE TITLE
DigitalOcean and AWS issues

### ISSUE THREAD

**Issue by beatchef** [Kwoth/NadekoBot#1262]
Hi, I installed Nadeko on a DigitalOcean droplet [as suggested here](http://nadekobot.readthedocs.io/en/latest/guides/Linux%20Guide/) in your guide and followed the exact steps in the guide too. I opted for a 1gb ram server. Whenever I run a radio stream with Nadeko, the sound keeps cutting out every 10 seconds or so. I check the resources being used and it's never taking more than 10% of the CPU and hardly any ram. I also tried installing on Amazon Web Services and it's the same. Is there any way to make it take more resources to stop the audio cutting out? Has anything changed with the way the bot works since that guide was created?

Thanks

**Comment by Kwoth** [comment]
We use #1053 to track music issues. Discord.net's music code changed, and I haven't refactored the music module yet to fix old issues and match new changes. Some people have more, some less luck in running music on 1.4+ 

Just wait for the refactor I guess, sorry for the inconvenience.
