### ISSUE TITLE
The error in the new script

### ISSUE THREAD

**Issue by DaYWhiTe** [Kwoth/NadekoBot#1264]
![image](https://user-images.githubusercontent.com/21060067/27241067-e42916a2-52df-11e7-944a-65ba526297c1.png)

I enter the install command as you see it, and then I try to open it

**Comment by xnaas** [comment]
Hey, go down a little further, then try `dotnet restore`.

Should be like `NadekoBot\src\NadekoBot` or similar?

**Comment by DaYWhiTe** [comment]
I do try, says "project.json" was not found

**Comment by DaYWhiTe** [comment]
It was okay Problem is that the old version of .net is in the new version.
