### ISSUE TITLE
(Request/question) Rainbow rank

### ISSUE THREAD

**Issue by MoonKidd** [Kwoth/NadekoBot#1265]
I recently seen something about a rainbow rank, is that option still available? Could a rainbow status also be added along with it?

**Comment by Kwoth** [comment]
command is `.rrc`
![image](https://user-images.githubusercontent.com/2537696/27252466-b04956a0-535f-11e7-9eeb-e03f50723fd3.png)

Feature requests go here http://feathub.com/Kwoth/NadekoBot

**Comment by MoonKidd** [comment]
I tried this, but it doesn't seem to be working

**Comment by Deivedux** [comment]
The command description literally says that 60 is a minimum amount, and make sure that Nadeko's highest role with highest permissions is higher by role hierarchy.

**Comment by MoonKidd** [comment]
I moved the bot farther in the highest roles, and the command is set to 60 but still won't work for me..

**Comment by Deivedux** [comment]
Are you even using public Nadeko or actually hosting it yourself?
