### ISSUE TITLE
Bot awards itself currency from reaction event

### ISSUE THREAD

**Issue by sunshoes** [Kwoth/NadekoBot#1266]
Not sure if it's intended but since updating from 1.3b to 1.43 the bot now awards itself currency from all flowerreaction events.

**Comment by xnaas** [comment]
Can't offer a fix, but that definitely shouldn't be happening (at least, it's not for me). 🤔

**Comment by beminee** [comment]
It probably is intended since bot reacts to event message as it makes easier for other people to react.

**Comment by sunshoes** [comment]
@beminee it has always done that, but before 1.4 it did not award itself currency in doing so. Considering currency awards are handled with a different script since 1.4 I'm assuming it's just a minor oversight.
