### ISSUE TITLE
Wait for shard connect problem

### ISSUE THREAD

**Issue by tayson2525** [Kwoth/NadekoBot#1267]
i just can't connect the nadeko bot, in the "waiting for all shards to connect..." the program just prints "Nadekobot : Connecting... 0/1" someone can help me? I'm trying to host the bot in my computer.
ps: i don't really understand about bots so if i'm doing something wrong sorry! xD

**Comment by xnaas** [comment]
>21:04:55 NadekoBot | Starting NadekoBot v1.43
21:04:55 NadekoBot | Logging in...
21:04:56 NadekoBot | Waiting for all shards to connect...
21:04:56 NadekoBot | Connecting... 0/1
21:04:57 NadekoBot | Connecting... 0/1
21:04:58 NadekoBot | Connecting... 0/1
21:04:59 NadekoBot | Connecting... 0/1
21:05:00 NadekoBot | Connecting... 0/1
21:05:01 NadekoBot | Connecting... 0/1
21:05:02 NadekoBot | Loading services...

How long does is it do it for? Mine does it a few times (seen above) then connects and proceeds as normal.

**Comment by tayson2525** [comment]
"21:04:58 NadekoBot | Connecting... 0/1" Remains in this same warning indefinitely (I left it for about 10 minutes and nothing happened), reappearing every 1 second

**Comment by tayson2525** [comment]
OMG, i noticed that in the documentation it speaks that works only on windows 8 or higher, my windows is windows 7, really sorry Xnaas probably have been this

**Comment by xnaas** [comment]
You can close out your own request here, by the way.

And yes, you'll have to upgrade Windows if you want to use Nadeko (or use a Linux VM or something). 👍
