### ISSUE TITLE
Bot Time is Wrong, Hard-coded?

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#1268]
So earlier, I found that the bot seems to have a hard-coded timezone or something?

![img1](https://i.imgur.com/C9Zv8Nu.png)

![img2](https://i.imgur.com/yywGnnf.png)

The time on the server the bot is hosted on *is* set correctly and the terminal even has the correct time listed as well.

![img3](https://i.imgur.com/OGdM8Mb.png)

I'm on [1.43](https://github.com/Kwoth/NadekoBot/releases/tag/1.43). Windows 10 Pro.

**Comment by xnaas** [comment]
Scratch that. I see the change in the commands list.

**Comment by Kwoth** [comment]
it's using utc time, will use .timezone time in the future, but not atm

**Comment by xnaas** [comment]
Ah, I see. Yeah, just tried `.timezone` with no luck. That's a shame...makes reminders a bit tedious... 😅
