### ISSUE TITLE
Commands not working 

### ISSUE THREAD

**Issue by Starxyy** [Kwoth/NadekoBot#1271]
After updating my bot none of the commands seems to work now. I have tried to start clean but still no luck.

**Comment by xnaas** [comment]
What version did you upgrade from? Have you verified what prefix is set in the database?

**Comment by Starxyy** [comment]
I upgraded from version 1.3.

**Comment by Starxyy** [comment]
I found out that the new commands have a prefix of . not !! anymore, thank you for the help.

**Comment by xnaas** [comment]
@Starxyy no problem. Yeah, it's worth it to review http://nadekobot.readthedocs.io/en/latest/Commands%20List/ every now and then. 😄
