### ISSUE TITLE
I accidentally deleted the NadekoBot/system folder

### ISSUE THREAD

**Issue by pakrtee** [Kwoth/NadekoBot#1272]
I've tried to reinstall the Nadekobot updater but the current version is the latest one, and it kept saying Please install or reinstall Nadekobot, or run manually via dekstop, and i want to know how to run it manually and how to solve this ?
Thank you

**Comment by Kwoth** [comment]
Remove it from the control panel and install it again. You can run the bot 'manually' by double clickign the desktop shortcut. You should have 2 of them when you install. One for the bot and one for updater.
