### ISSUE TITLE
Some commands ignored.

### ISSUE THREAD

**Issue by mightbemaybeme** [Kwoth/NadekoBot#1281]
Hello. I have setup my custom nadeko using the Windows installer (NadekoInstaller.bat), and some commands like any commands in the music group (http://nadekobot.readthedocs.io/en/latest/Commands%20List/#music), don't respond.
Better yet the commands are not even reported in the log (onscreen). So, with that I tried upgrading the bot and it did not work, I restarted it, and it's still not working.
The bot has all the necessary permissions to use voice, and it's not even being ran at all.

How can this happen?

**Comment by samdivaio** [comment]
You are on 1.3 with NadekoInstaller.bat and your commands lists are [here](http://nadekobot.readthedocs.io/en/1.3x/Commands%20List/)

[Upgrade](http://nadekobot.readthedocs.io/en/latest/guides/Upgrading%20Guide/) to use the commands listed [here](http://nadekobot.readthedocs.io/en/latest/Commands%20List/)

**Comment by mightbemaybeme** [comment]
well i did upgrade as mentioned and the command list you posted is the same as the one i posted.

**Comment by samdivaio** [comment]
try `.stats` is it showing 1.4x or 1.3x

**Comment by mightbemaybeme** [comment]
yep it is 1.3x

**Comment by mightbemaybeme** [comment]
time to upgrade again

**Comment by mightbemaybeme** [comment]
latest or stable build?

**Comment by mightbemaybeme** [comment]
cool a new installer
