### ISSUE TITLE
Music isn't working

### ISSUE THREAD

**Issue by lauryn4445** [Kwoth/NadekoBot#129]
I tried using the bot for music commands, and it is not joining the voice channels. 
Is there anything I should do?

**Comment by Kwoth** [comment]
Use HaNadeko for music, not NadekoBot.

If you are hosting your own bot, get googleapi key and install ffmpeg and add it to path. Its all explained inthe comprehensive guide.

If hanadeko stops working, just wait for the restart. You can also try running
`!m s`
`!m d`
[change server location to some other europe location]
and then queue your song.
