### ISSUE TITLE
Default volume not being applied?

### ISSUE THREAD

**Issue by whizvox** [Kwoth/NadekoBot#130]
I'm trying to set the default volume for playing music, as new users complain it's initially too loud. However, `!m dv #` doesn't seem to work.

![pic](http://puu.sh/nPv5V/4205cd578a.jpg)

The next song always plays at 100% volume.

**Comment by Kwoth** [comment]
yes, because default volume applies only if the bot's music is destroyed (new instance of music player, after `!m d`) I should really make it persist restarts though, now that I've made ServerSpecificConfig.json
