### ISSUE TITLE
Funny behavior on global custom reactions

### ISSUE THREAD

**Issue by Deivedux** [Kwoth/NadekoBot#1305]
If you get a list of global custom reactions (by DMing the bot with `.lcr`) the list of global custom reactions is paginated, but it's behavior is really weird...
![3qqjvse](https://user-images.githubusercontent.com/25952144/27410452-542ca248-56f0-11e7-9aea-ad788b64182f.gif)

**Comment by Kwoth** [comment]
I tested it now and it seems to work properly after that sharding change
