### ISSUE TITLE
[Feature Request] Have nadeko remove ALL links

### ISSUE THREAD

**Issue by Zequew1** [Kwoth/NadekoBot#1309]
With Nadeko, you can only have her remove invite links, so I was thinking that having Nadeko remove all links would help a lot! Thanks for reading.

**Comment by Deivedux** [comment]
This is not a place for suggestions, please go here instead: http://feathub.com/Kwoth/NadekoBot

**Comment by Zequew1** [comment]
My bad, thx for letting me know.
