### ISSUE TITLE
[Feature Request] Duplicate strings at .shoplistadd

### ISSUE THREAD

**Issue by Inzow** [Kwoth/NadekoBot#1310]
I use the currency system so much and I thank you greatly for such bot.
Is it possible to add an option to allow duplicate text records at .shoplistadd?

I made a shop item that's basically Scratch & Win, not being able to add multiple records of "Better luck next time" makes it hard to make such activity.

Thanks again!

**Comment by Deivedux** [comment]
Suggestions goes here: http://feathub.com/Kwoth/NadekoBot

**Comment by Inzow** [comment]
Sorry, thanks.
