### ISSUE TITLE
[Suggestion] Ability to filter certain tags from being searched in NSFW function

### ISSUE THREAD

**Issue by DaekTwentri** [Kwoth/NadekoBot#1312]
Any chance of adding a setting to block certain tags? Like we currently host a nsfw channel that aims to be more vanilla instead of the more different parts of hentai. But more often than not we get content like futa, traps, and furries to show up. Would it be possible to add a command that would allow the user to block the tags to cater more towards the channels preference?

**Comment by Kwoth** [comment]
http://feathub.com/Kwoth/NadekoBot
