### ISSUE TITLE
Nadeko Installation Not Working

### ISSUE THREAD

**Issue by lordfundarbyrd** [Kwoth/NadekoBot#1315]
I uninstalled Nadeko and deleted all the files as it was acting weird before, and now I'm trying to reinstall it. I reinstalled the Updater, and now it won't update. When I click "Start Bot" it tells me to launch it from the desktop, even though I am. I also can't find the NadekoBot folder or the credential.json file. It seems like the Updater installed but isn't able to do anything. How do I fix this?
I have also tried numerous times to uninstall and reinstall it again (as I saw someone else suggest on another post) but I'm still having the same issue.

**Comment by Kwoth** [comment]
Delete everything, when you install updater, see where is the install location, that's where your nadekobot folder is. Try not installing it on your main drive, but on the secondary one, maybe that helps. Also you need to show us some screenshot of the errors.
