### ISSUE TITLE
Strings error when starting

### ISSUE THREAD

**Issue by MajorJones** [Kwoth/NadekoBot#1317]
My bot was working fine until i had to restart him because i changed somo of the visuals for the slots, then it wouldnt start at all because of the strings being in a incorrect format. i reinstalled the bot and i keep getting the same error. Here's a screenshot of the terminal 
![screenshot_42](https://user-images.githubusercontent.com/29762279/27659478-fbe69a1e-5c29-11e7-8324-322be05778c0.png)
 . Any help?

**Comment by Kwoth** [comment]
You must have the same name of the files when replacing them. They have to be numbers
