### ISSUE TITLE
Lower case custom reactions

### ISSUE THREAD

**Issue by Deporee** [Kwoth/NadekoBot#1318]
All custom reactions for nadeko seem to now post entirely in lower case, which creates problems for image links that are case sensitive.

**Comment by xnaas** [comment]
Why close this, @Deporee? This is still a problem in 1.51 unless @Kwoth pushed a fix I didn't notice. 😛

**Comment by Deporee** [comment]
Kwoth fixed the problem, my custom reactions are all back to normal.

**Comment by xnaas** [comment]
@Deporee care to share the fix? Was a commit pushed that fixed it? Where's there something you had to fix in the database. I'm sure myself and others would like to be enlightened on cause and solution. 👍

**Comment by Kwoth** [comment]
@xnaas it's fixed after 1.51, wait for 1.52 on releases if you're on windows, or just update if you're on linux

**Comment by xnaas** [comment]
Confirmed fixed. 👍
