### ISSUE TITLE
NadekoBot.exe Won't Even Open

### ISSUE THREAD

**Issue by REDHE** [Kwoth/NadekoBot#132]
I'm not sure if it's just me being a complete idiot, or a problem with the build, but after I did pretty much all of the API setup and creation of the discord account, and etc, I tried opening up the NadekoBot.exe from the file I put it in my desktop. The entire file explorer tab just froze, and the loading cursor appeared, and just sat there, and it's been over 30 minutes.

**Comment by REDHE** [comment]
Process:
 - Downloaded the release,
 - Extracted to Desktop folder.
 - Went to the Credentials_example.json.
 - Added info as in the Username Email, Password for the Discord account.
 - Added Google API server key.
 - Saved as 'Credentials.json'
 - Attempted to run 'Nadekobot.exe'
 - File Explorer freezes.
 - Continues to freeze, doing nothing.

**Comment by samdivaio** [comment]
Do you have an config.json file in \data. If not make config examples.json to config.json and try again

**Comment by LawlyPopz** [comment]
Sam no need to do that in the new release

**Comment by samdivaio** [comment]
It's probably not the beta4

**Comment by REDHE** [comment]
Due to the EXE not opening, I ended up manually changing the config_example.json to Config.json

**Comment by REDHE** [comment]
Still, nothing works.

**Comment by samdivaio** [comment]
File explorer is freezing? Have you tried restarting your PC? Could be some services like Windows Update or some creppy registery mess with you.

**Comment by REDHE** [comment]
Everythings fine except the explorer when I attempt to open the bot.exe

**Comment by samdivaio** [comment]
Can you check in task manager, which process is hogging file explorer

**Comment by REDHE** [comment]
I don't think it's anything on the task manager. 

If the 0.8 version still works, I'd be happy to try working that,

**Comment by Kwoth** [comment]
@REDHE can you use the updater and download latest stable like that, watch the video tutorial linked in here after you download it <https://github.com/Kwoth/NadekoUpdater/releases/tag/v1.0>

**Comment by Kwoth** [comment]
Ok, we are solving it in our discord server.
