### ISSUE TITLE
Bot does not remember timezone in Custom Reaction

### ISSUE THREAD

**Issue by ItsFriday** [Kwoth/NadekoBot#1322]
Bot does not sync to the new set timezone, not to sure about the playing with, but here.
(https://itsfriday.s-ul.eu/xn956NHd)
https://itsfriday.s-ul.eu/9d4FxVV3

**Comment by xnaas** [comment]
Rehosts and showing images properly to save lazies time:

![img1](https://i.imgur.com/umPafXx.png)
![img2](https://i.imgur.com/nWrGf0z.png)

👍

**Comment by Kwoth** [comment]
http://nadekobot.readthedocs.io/en/latest/Placeholders/
