### ISSUE TITLE
The enabling and disabling of "Rotate Playing" is the same message.

### ISSUE THREAD

**Issue by ItsFriday** [Kwoth/NadekoBot#1323]
https://itsfriday.s-ul.eu/XdpRgOkx

I have a playing status enabled too.

https://itsfriday.s-ul.eu/pVgol9uk

**Comment by Kwoth** [comment]
I just pushed a fix to the response, it's working correctly, but always saying disabled. Either update if you're on linux, or wait for 1.53 on windows

**Comment by Kwoth** [comment]
I'll just close this now, 1.53 will be released for windows later tonight
