### ISSUE TITLE
Capitalization not working in custom reactions

### ISSUE THREAD

**Issue by Mexiguy** [Kwoth/NadekoBot#1324]
When making a new custom reaction the bot always replies in lowercase regardless of what the response was typed as, this is a problem if the response includes any sort of shortened url that uses both lowercase and upper case, for obvious reasons.

http://puu.sh/wxB4k/b076bfb9e9.png
http://puu.sh/wxBDX/3b09a2838e.jpg

**Comment by xnaas** [comment]
#1318

**Comment by Kwoth** [comment]
Fixed in 1.52, update
