### ISSUE TITLE
Startup commands ignoring "

### ISSUE THREAD

**Issue by ItsKanin** [Kwoth/NadekoBot#1326]
So all of my startup commands are working other than one which is my .rrc because the role is 2 words I need to put Quotation marks around it, however the startup command seems to ignore them which makes the command not work.

**Comment by Kwoth** [comment]
Hm, haven't tried it, but maybe try escaping quotation marks with 

For example `\"My Role\"`

**Comment by Kwoth** [comment]
I tested it, it works.
