### ISSUE TITLE
Patreon hardcoding

### ISSUE THREAD

**Issue by TheDeadCode** [Kwoth/NadekoBot#1327]
Add an option in the credentials to supply our own campaign

https://github.com/Kwoth/NadekoBot/blob/1.4/src/NadekoBot/Services/Utility/PatreonRewardsService.cs#L67

**Comment by Kwoth** [comment]
Wow, What. There were people 'using' patreon features and nobody reported this? I'll do it later today or tomorrow, thanks.

**Comment by TheDeadCode** [comment]
Do you want me to make a pull request? (If I have time?).

I love supporting creators in ways that I can; Cheers!

**Comment by Kwoth** [comment]
Thanks, but i'm doing it right now

**Comment by Kwoth** [comment]
Added 👍 try it out

**Comment by TheDeadCode** [comment]
Awesome sauce!

**Comment by Kwoth** [comment]
I thought I added it?

**Comment by TheDeadCode** [comment]
```08:51:38 MusicService | System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NadekoBot.Services.Impl.YtdlOperation.<GetDataAsync>d__2.MoveNext() in /root/discord/nadeko/NadekoBot/src/NadekoBot/Services/Impl/Ytdl.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.Music.MusicService.<GetYoutubeVideo>d__26.MoveNext() in /root/discord/nadeko/NadekoBot/src/NadekoBot/Services/Music/MusicService.cs:line 336```

I'm investigating

**Comment by Kwoth** [comment]
@TheDeadCode did you start using patroen feature? Is it working? midorina is having issues with it

**Comment by TheDeadCode** [comment]
We haven't setup our patreon page yet. ETA is 1w

**Comment by Midoriin** [comment]
Hey. I'm still having issues with that. @TheDeadCode where are you going to get your campaign ID from?

**Comment by julian100004** [comment]
@Midoriin did you find it yet? Searching for it too.

**Comment by TheDeadCode** [comment]
We started our campaign, but didn't setup the perks yet :P

**Comment by julian100004** [comment]
@TheDeadCode could you ping me, when you find the id pls :3

**Comment by Kwoth** [comment]
I don't remember how I got mine, but you can go to 

https://hurl.it

and make this request
![image](https://user-images.githubusercontent.com/2537696/28395765-ac9d3ec6-6cf6-11e7-8e74-4141be676c93.png)

and copy the id from the "id" field.

**Comment by julian100004** [comment]
I'm too stupid for this world. Getting an error with this. 
![image](https://user-images.githubusercontent.com/21989955/28396295-b61e0594-6cfa-11e7-9840-ec37be925e0c.png)
