### ISSUE TITLE
Timezone doesn't effect most commands

### ISSUE THREAD

**Issue by TheOddball** [Kwoth/NadekoBot#1328]
Set a timezone
Use remind
The time is not formatted into your timezone

**Comment by Kwoth** [comment]
print screen

**Comment by TheOddball** [comment]
http://i.oddball.tf/Bem9w.png
Current time:
http://i.oddball.tf/DCd15.png

**Comment by Kwoth** [comment]
It's just because it's not added there yet.

Only place it's added at is when you use .repeat <time> (daily repeaters)
It still needs to be added to a few places, like

[ ] Text placeholders
[ ] Reminders
[ ] Logs
