### ISSUE TITLE
FFmpeg Issue on 1.53

### ISSUE THREAD

**Issue by Gremagol** [Kwoth/NadekoBot#1331]
This happens when I try to play a song:
![ffmpeg2](https://user-images.githubusercontent.com/24619854/27844158-2d44f45e-611e-11e7-8c89-c37a91378690.PNG)
And i got this ffmpeg version:
![ffmpeg1](https://user-images.githubusercontent.com/24619854/27844181-4e779186-611e-11e7-8e3b-f9959b52bb67.PNG)

As you said we should use 3.3+
I'm on Ubuntu 16.04 LTS tho.
Oh and when I downgrade to 1.51/1.52, it works fine.

Any Suggestions how to fix this?

**Comment by Kwoth** [comment]
I'm on ubuntu 16.04, same version of fmpeg as you. Try removing ffmpeg completely and installing again, try restarting your server.

**Comment by Gremagol** [comment]
Works fine after restart now, BUT:
![1 53](https://user-images.githubusercontent.com/24619854/27861755-7003f1fa-6182-11e7-8d2a-1f9061e62f99.PNG)
%queued% placeholder doesnt work anymore for playing status.

**Comment by Gremagol** [comment]
Also:
What's this?
![ffmpeg3](https://user-images.githubusercontent.com/24619854/27861891-060c9378-6183-11e7-8080-5b4e8930f2cd.PNG)

**Comment by Kwoth** [comment]
%queued% and %playing% fixed
