### ISSUE TITLE
`.shardstats` doesn't display properly

### ISSUE THREAD

**Issue by DogeOps97** [Kwoth/NadekoBot#1333]
Sometimes, Nadeko is down in some servers, but `.shardstats` still display as all shards connected

**Comment by Midoriin** [comment]
I have this issue on my clone aswell. It says all shards are connected even though a shard goes down.

**Comment by Kwoth** [comment]
Fixed. 

this happened because it simply showed the last state. I've made it so it goes unresponsive if status is not updated within 20 seconds (each status update happens every 5 seconds), so if it fails to send status four times in a row, it will show as unresponsive in shardstats.
