### ISSUE TITLE
Uses 99% usage after executing music commands

### ISSUE THREAD

**Issue by NeonSpectrum** [Kwoth/NadekoBot#1335]
After executing any music commands, dotnet uses and stay in 99% cpu for almost 30secs and then it will play the song. It only occurs when I start the bot.
![image](https://user-images.githubusercontent.com/29432829/27865885-d827275e-61c6-11e7-9f45-0db2bc7f2734.png)

**Comment by Kwoth** [comment]
Your internet connection/pc specs?

**Comment by NeonSpectrum** [comment]
using aws free tier windows server 2016 1gb ram 1 core

**Comment by Kwoth** [comment]
Which version?

**Comment by NeonSpectrum** [comment]
1.53

**Comment by Kwoth** [comment]
So, you're running it from source on windows? You made some changes to the source?

**Comment by NeonSpectrum** [comment]
didnt change any

**Comment by Kwoth** [comment]
try updating again, i made some fixes recently

**Comment by NeonSpectrum** [comment]
same result after updating to the latest
![image](https://user-images.githubusercontent.com/29432829/27872290-dd5feefe-61da-11e7-9f77-fc8c49217766.png)

**Comment by Kwoth** [comment]
Other commands work fine? Try restarting the bot and using the `.stats` first, see if it lags that much

**Comment by NeonSpectrum** [comment]
all commands work fine the only thing is when the music player starts it will load 30 seconds before executing commands

**Comment by Kwoth** [comment]
Pretty sure this is fixed. The cause of this was the cpu hungry youtube song resolver, I'll do some more testing today because there seems to be another thing which eats cpu.
