### ISSUE TITLE
Currency Conversion Broken - v1.52

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#1336]
Currency conversion appears to be broken at the moment.

![img](https://i.imgur.com/haVx9ZA.png)

Looks like it's missing whatever the "ConverterService" dependency is?

**Comment by Kwoth** [comment]
try now?

**Comment by Kwoth** [comment]
works, tested it

**Comment by xnaas** [comment]
Mostly fixed. Think you might add back a missing `D` though. 😛 

![missing D](https://i.imgur.com/r5nLHli.png)
