### ISSUE TITLE
.help isn't working since update.

### ISSUE THREAD

**Issue by BourKeeg815** [Kwoth/NadekoBot#1338]
![image](https://user-images.githubusercontent.com/27071605/27888876-8a5588c8-61b6-11e7-8ee6-9ce51434f18f.png)

My .h and .help command arent working, I updated the bot and go the error above

**Comment by Kwoth** [comment]
Can you check which version are you on?

**Comment by Kwoth** [comment]
I'll close this as it's not happening to me or anyone else that I know of.
