### ISSUE TITLE
How to disable .img and only allow it in certain channels.

### ISSUE THREAD

**Issue by JoshB84** [Kwoth/NadekoBot#1339]
Hello I am trying to disable the command .img. People keep spamming images in the lounge area and we have specific areas for images.

I have created the Nadeko role and added it to myself.

**Comment by JoshB84** [comment]
I figured it out....
.sm Searches disable
.cm Searches enable #ExampleChannel

**Comment by eric123911** [comment]
@JoshB84  Please mark this issue as closed :-)
