### ISSUE TITLE
Nadeko not launching

### ISSUE THREAD

**Issue by petery07** [Kwoth/NadekoBot#1341]
![capture](https://user-images.githubusercontent.com/29939729/27896951-51d776d0-6271-11e7-999e-c7b8a8210737.JPG)
![capture 2](https://user-images.githubusercontent.com/29939729/27896973-6f791e1e-6271-11e7-93da-557f255051be.JPG)

I've double checked the json file, I've copied the OwnerId and double checked it. But it still says that "_No owner channels created! Make sure you've specified correct OwnerId in the credentials.json file._"

I've kicked and invited Nadeko back to the server as I've followed the last issue that someone posted with the same problem.

Help!

**Comment by samdivaio** [comment]
Try command `.stats` and send us your bot's response.
I believe either your Owner ID is incorrect or you invited the bot after running NadekoBot program.

**Comment by petery07** [comment]
Ohh yes I did invited the bot after running the NadekoBot program. Here is the snapshot after putting the command .stats
![capture 3](https://user-images.githubusercontent.com/29939729/27907487-f4fa4ca0-629b-11e7-8515-ca2ec17fb9a6.JPG)

**Comment by petery07** [comment]
Strange, the things on my json files are not the same as the stats. But all I had done was just following the instruction http://nadekobot.readthedocs.io/en/latest/guides/Windows%20Guide/

**Comment by Kwoth** [comment]
You should kick out public nadeko, also, you probably didn't invite YOUR bot to your server, because looking at the console, it seems to run fine.
