### ISSUE TITLE
Missing key on strings de-DE.

### ISSUE THREAD

**Issue by YamiyoYamxiy** [Kwoth/NadekoBot#1345]
**tl;dr** Missing the ` key on the string.

On `"games_pick_sn"` where we have: ```"games_pick_sn": "Sammel sie durch das Schreiben von `{0}pick"``` should be ```"games_pick_sn": "Sammel sie durch das Schreiben von `{0}pick`".```

The ⎛⎝ julian ⎠⎞#5732 report this.

![](https://cdn.discordapp.com/attachments/117523346618318850/332591087577333760/unknown.png)

**Comment by Kwoth** [comment]
just updated it, thanks. It will be fixed when i push string updates
