### ISSUE TITLE
.translangs output format

### ISSUE THREAD

**Issue by SillyBirds** [Kwoth/NadekoBot#1347]
A minor thing, but when using `.translangs`, you get a list that's not so clear... (latest 1.54)

![pic](http://i.imgur.com/2s6qBYg.jpg)

**Comment by Kwoth** [comment]
What's not clear? It lists all available codes/languages

**Comment by SillyBirds** [comment]
Up to **catalan** you have on one side the language code and on the right side the corresponding language description. And then, there's those **simplified chinese** and **traidtinal chinese** that mess up the order.

![so messy](http://i.imgur.com/0sLXP0G.jpg)

If it's not possible to have two proper columns, how about separating the language and the code by simple comma?

**Comment by Kwoth** [comment]
no, it orders languages and language codes in alphabetic order. It's going from left to right, top to bottom

**Comment by SillyBirds** [comment]
If both the languages and the codes are listed separately and alphabetically in 3 different columns, that's why. Your list has a lot of languages that don't have a similarly named code, ie:
albanian ->  sq
armenian ->  hy
chinese-traditional ->  zh-TW
croatian  -> hr
dutch -> nl
filipino -> tl

**Comment by Kwoth** [comment]
I don't see that as a problem, it's using 3 columns to save vertical space. Anyone looking for a country code, knows the starting letter and will find it, same with country name. They don't have to be next to each other.

**Comment by SillyBirds** [comment]
My point was, if I was trying to translate something from like, english to albanian, that list doesn't show you. You have albanian at the top and the albenian code "sq" near the bottom.

If you're not an albenian person yourself, you can't be expected to know that the code is so different from the name. The purpose of the list is to help you on that.

I had to look at your ` NadekoBot/src/NadekoBot/Services/Impl/GoogleApiService.cs` file to understand what language goes with what code. Couldn't it be listed like in there?

Again, it's a minor thing, but only till you need to actually use that list.

**Comment by Kwoth** [comment]
you can use either a language name or the country code.

**Comment by SillyBirds** [comment]
Ohhh, that changes everything!

You don't get that idea from looking at the `.trans` description, since the example uses only the codes.

Anyway, thanks, now I'll know for the next time.
