### ISSUE TITLE
" REPORT THIS " 

### ISSUE THREAD

**Issue by StormAE** [Kwoth/NadekoBot#1348]
Command:  " repeat 15:10 dd " 

-"  Repeating dd every 1 day(s), 0 hour(s) and 0 minute(s). Error: dkey utility_repeater_initial not found!

CMD : " utility_repeater_initial key is missing from en-US response strings. PLEASE REPORT THIS "

**Comment by Kwoth** [comment]
Update your bot, i tested it and it works.
