### ISSUE TITLE
Embeds not working

### ISSUE THREAD

**Issue by NaokoKyouseiNingyou** [Kwoth/NadekoBot#1350]
In version 1.54, embeds aren't working.
This is the output I get in the console:
![image](https://user-images.githubusercontent.com/29898563/27957392-97e171c8-631e-11e7-8ca0-40dff33e38f5.png)

**Comment by Gremagol** [comment]
I can confirm that.
![rip19](https://user-images.githubusercontent.com/24619854/27957421-bb0fb934-631e-11e7-8168-413eaa44ac7b.PNG)

**Comment by Gremagol** [comment]
Same with .greet and .bye
![rip20](https://user-images.githubusercontent.com/24619854/27957702-e2bc3c5e-631f-11e7-9a24-79cc6b795f84.PNG)

**Comment by Kwoth** [comment]
What, I fixed this last night?! Someone, dm me your greet/bye message

**Comment by Gremagol** [comment]
Works fine now, except footers. As I saw in your commit, you fixed it for Images and Thumbnails, what about the IconURLs?
![iconurl](https://user-images.githubusercontent.com/24619854/27978487-f733b388-636f-11e7-94c0-5310e402dde0.PNG)

**Comment by Kwoth** [comment]
Fixed both in 1.54b
