### ISSUE TITLE
youtube-dl error

### ISSUE THREAD

**Issue by SociusPugnae** [Kwoth/NadekoBot#1351]
When I first downloaded youtube-dl via the updater it gave an error about a missing "Msvcr100.dll" file. I downloaded the dll file manually and now I have an error saying that "the program could not be launched correctly" with (0xc000007b) attached to it.

I attached a picture of the error. Unfortunately it is in German but I hope this is okay for you guys ;)
![omjku2arqu6ohcsplt1yqw](https://user-images.githubusercontent.com/26843910/27957800-4ff11a74-6320-11e7-8735-a5012eefe152.png)

After this error "YouTube video" stops working

**Comment by xnaas** [comment]
Can confirm the same. Any time I launch the NadekoUpdater, that error will popup twice now before being able to start the bot.

![img](https://i.imgur.com/VMKbf9e.png)

**Comment by Kwoth** [comment]
https://www.microsoft.com/en-US/download/details.aspx?id=5555 download this

**Comment by Kwoth** [comment]
maybe i should try to install that too when installing youtube-dl 🤔

**Comment by SociusPugnae** [comment]
I installed the programm you linked to but the error still exists. Still the same.

**Comment by Kwoth** [comment]
try restarting your pc?

**Comment by SociusPugnae** [comment]
Restarted it but it is still showing the error :/

**Comment by xnaas** [comment]
Installing it fixed the error for me, just as an FYI.

I guess @SociusPugnae has something else going on. ☹️

**Comment by Kwoth** [comment]
He's just doing something wrong.
