### ISSUE TITLE
Phone users can't hear any songs after the first one until they rejoin

### ISSUE THREAD

**Issue by DaYWhiTe** [Kwoth/NadekoBot#1352]
FFmpeg Version: 3.3.2-1~14.04.york1
Ubuntu Version: 14.04
Bot Version: 1.52

This happened after version 1.4
When I first open the bot, I play music and listen without distress. the next music is broken for phone users.
I want to show you what's on the phone and computer. (Same song at the same time)

Computer:
https://quikegaming.com/wp-content/uploads/2017/07/2017-07-07_16-57-42.mp4

Phone:
https://youtu.be/XRn-czcHP6A

**Comment by Kwoth** [comment]
I think this is related to the discord error. They will patch it soon

**Comment by DaYWhiTe** [comment]
i will be waiting

**Comment by samdivaio** [comment]
It only happens with Android Discord app and any web browser.

**Comment by DaYWhiTe** [comment]
There is no problem installing and using other types of bots, but there is such a problem with the only Nadekobot 1.4+ version

**Comment by DaYWhiTe** [comment]
Problem is in phone and web browsers

**Comment by samdivaio** [comment]
Temp fix until discord resolves this issue: https://github.com/samdivaio/NadekoBot-Extensions

**Comment by DaYWhiTe** [comment]
now it is OK. I understand why I got the bot again, the channel plays the song properly

**Comment by DaYWhiTe** [comment]
Why are the songs still in the player?
