### ISSUE TITLE
Issues with embeds and Discord.Net's character limits

### ISSUE THREAD

**Issue by ManuelFte** [Kwoth/NadekoBot#1355]
Discord.Net's character limit for embeds is 256 for field names and 1024 for field values. This causes a couple of issues with Nadeko:

- If the user adds a custom reaction longer than 1024 characters, neither `.acr`, `.dcr` or `.scr` will show anything; although the first two will add/delete the custom reaction correctly.

- Similar issue if the user adds a custom reaction, quote or greet/bye message using the embed builder with field names and/or values superior to these limits. In this case, the bot will return no error when adding them but they won't be displayed (the embed builder should not allow to add content exceeding the character limit to prevent this).

**Comment by Gremagol** [comment]
There should be a message like: "I created your custom reaction, but one value was too big for preview. Please test your reaction." :D
