### ISSUE TITLE
Updating to 1.55 on Windows 10

### ISSUE THREAD

**Issue by LillySatou** [Kwoth/NadekoBot#1357]
Hey,

I just tried to update to 1.55.1 or whatever using the updater. But I couldn't without turning of some file protection. I know that Nadeko isn't a problem but i thought I'd just give a heads up. Also my sample size is pretty small since I only have Windows 10. But i managed to turn off the file protection to install it and Nadeko runs fine with it back on.

Not sure how to solve it other than to turn it off each time maybe but at least i still have Nadeko. Keep up the great work ^_^

**Comment by Kwoth** [comment]
Try installing her to a drive that's not system drive? But yea, it's generally a problem because i don't have the time to tinker with app signing.

**Comment by LillySatou** [comment]
I'm not sure what is classified as a system drive. But its not on my C drive where my OS is. Its on an M.2 drive so it might have some special properties or something. Still nothing major or breaking just thought I'd give the heads up :)
