### ISSUE TITLE
Overwatch Search not working

### ISSUE THREAD

**Issue by DaYWhiTe** [Kwoth/NadekoBot#1359]
Bot version: 1.55
No code changes

![noknown3](https://user-images.githubusercontent.com/21060067/27986533-b728e9e0-6408-11e7-8563-ce4be460b7ea.png)

![noknown2](https://user-images.githubusercontent.com/21060067/27986447-fc8badf2-6407-11e7-8212-ae0f068fab18.png)

![noknown](https://user-images.githubusercontent.com/21060067/27986445-f91c5950-6407-11e7-9090-e0b53aba5a9b.png)

**Comment by Kwoth** [comment]
Was a server issue, try it again and it should work (no restart or update required)
