### ISSUE TITLE
Prune +1

### ISSUE THREAD

**Issue by Glaived** [Kwoth/NadekoBot#136]
Currently
```
GlaiveÐ - Today 04:36: one
GlaiveÐ - Today 04:36: two
GlaiveÐ - Today 04:36: tree !!!
GlaiveÐ - Today 04:36: .prune 3
```
After:
```
GlaiveÐ - Today 04:36: one
```

Can you add one more to Nadeko for it removes all the desired elements ? :#

**Comment by Kwoth** [comment]
no sorry, its not backwards compatible, people will screw up :) always add 1 to the number you want to delete
