### ISSUE TITLE
Nadekobot sometimes says things 3 times

### ISSUE THREAD

**Issue by eruzang** [Kwoth/NadekoBot#1360]
Whenever I do a command, it will repeat itself 2 more times. This doesn't happen to all commands, but it does happen with most. It doesn't seem to follow any rule as to which commands it repeats answers to.

Eg.
<img width="238" alt="screen shot 2017-07-08 at 1 59 06 pm" src="https://user-images.githubusercontent.com/30007491/27988376-f372fa9e-63e5-11e7-87cf-78b6794a7603.png">

**Comment by Kwoth** [comment]
That doesn't seem right. Maybe it happened when discord stuttered a bit today, or you somehow 3 instances of your bot running?

**Comment by eruzang** [comment]
Very likely that there are three instances. I just set it up today, and when I was doing it I restarted twice after realizing I hadn't set up credentials.json correctly. I closed the terminal (on mac) and redid the process starting from `screen -S nadeko` each time. However, this doesn't explain how some commands only get executed once...

How can I check the number of instances of the bot? Again, I am on mac. 

Thanks

**Comment by eruzang** [comment]
nope, doesn't seem to be instances. I did .die and restarted everything, and it still gives me three responses for some commands.

**Comment by eruzang** [comment]
O.K. never mind. I did .die and left it there. It gives me two responses now, and .die no longer works. Weird. Will a computer restart fix this?

**Comment by Kwoth** [comment]
Yea, restart your pc, and run your bot *once*

**Comment by eruzang** [comment]
worked, thanks
