### ISSUE TITLE
Music can't download API Page [CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by Popupkiller** [Kwoth/NadekoBot#1362]
Whenever I try to load a song, or playlist I get an error.
Example:

I write 
.qs walk off the earth taekwondo

I get the response:
NadekoBOTBOT - Today at 11:45 PM
1.
    Walk off the Earth - TAEKWONDO
    http://www.youtube.com/watch?v=RJCvwslfIYI
2.
    TAEKWONDO - Official Trailer (Walk off the Earth)
    http://www.youtube.com/watch?v=F-DqDesJg9E
3.
    Walk Off The Earth | Taekwondo | CBC Music Fest...
    http://www.youtube.com/watch?v=nJfm-WUSasI
4.
    Walk off the Earth-TAEKWONDO Lyrics
    http://www.youtube.com/watch?v=8jYIww-dbgM
5.
    Taekwondo - Walk Off The Earth (11/06/17)
    http://www.youtube.com/watch?v=83Mab27PmBI

If I type and send 1, I get the reply:
 No song found.

and the following error in the server window:
23:45:48 Ytdl | ERROR: Unable to download API page: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))

I have made sure that Ffmpeg is installer.
I downloaded Youtube-dl for good measure.
Rebooted both times.
Checked for updates
I have checked that my Token is correct, and updated it.
I have run Nadekobot.exe with administrator rights.
I have checked that I have the correct GoogleApiKey.

I run Windows 10 Pro
and I'm running version 1.55.1 of Nadeko.
I live in Norway, if that has anything to do with it.
My Discord server is set to Server region Central Europe.

**Comment by Devaliah** [comment]
Same issue, been happening since 1.5+

**Comment by Kwoth** [comment]
are you both on linux?

**Comment by Kwoth** [comment]
seems like the last comment in this issue has the solution https://github.com/rg3/youtube-dl/issues/11573

**Comment by Kwoth** [comment]
I just pushed 1.55.2 to fix this, try updating and trying again

**Comment by samdivaio** [comment]
Fixed ✅
