### ISSUE TITLE
.queue <song> loops added songs

### ISSUE THREAD

**Issue by lukezord** [Kwoth/NadekoBot#1364]
when you add song to queue it goes to the bottom of the playlist after its played, if you queue just one - repeats in infinite loop, after update music module is bugged so hard i guess

**Comment by Kwoth** [comment]
No, it just has .rpl enabled by default. Read the patch notes or announcements before making issues please.

**Comment by lukezord** [comment]
already tried it, doesnt solve the issue

**Comment by Kwoth** [comment]
You want to say that after you disabled `.rpl` while you had 1 song in the queue, it continued to play indefinitely?

**Comment by lukezord** [comment]
yeah thats the issue when i queue one song its added twice and just loops

**Comment by Kwoth** [comment]
"when i queue one song its added twice" what?

**Comment by lukezord** [comment]
killing tmux session fixed it, somehow bot had 2 instances lol.
