### ISSUE TITLE
Bot Hangs after first song. v1.55-v1.55.3

### ISSUE THREAD

**Issue by Devaliah** [Kwoth/NadekoBot#1365]
Bot Still crashes and burns after the first song. Whether AP or multiple songs are queued or not. The bots voice activity starts flickering rapidly without sound in the chat.

(edit) Seems to hang on browsers specifically. Using firefox.

**Comment by samdivaio** [comment]
Discord issue

**Comment by Kwoth** [comment]
we'll track it in that issue
