### ISSUE TITLE
Can't play music - Can't join

### ISSUE THREAD

**Issue by RustyJuice** [Kwoth/NadekoBot#1367]
So i've got everything setup as per the guide, hosting on a linux box, bot invited to the server with full permissions, however whenever i try and play a song i get the following:

![screenshot 133](https://user-images.githubusercontent.com/7268811/27990713-31353286-6457-11e7-86f8-5a5035b5bd91.png)

At a complete loss with what to do now so any advice appreciated. 

Cheers

**Comment by samdivaio** [comment]
Get me these info:
OS
OS version 
ffmpeg version
youtube-dl version 
Screenshot of your google console with all enable api

**Comment by RustyJuice** [comment]
@samdivaio 

- Ubuntu 14.04.5
- ffmpeg version 3.3.2-1~14.04.york1
- youtube-dl --version = 2017.07.02

![screenshot 135](https://user-images.githubusercontent.com/7268811/27990762-7e4c4418-6459-11e7-9280-68f2ed39b2c3.png)

**Comment by samdivaio** [comment]
Can you check your bot perms again, or test the bot's music in a new server?

**Comment by DaYWhiTe** [comment]
Enable the api and restart the bot and try again

**Comment by Kwoth** [comment]
"Can't join" definitely means bot can't join the voice channel for whatever reason. Make sure she has admin perms.

**Comment by RustyJuice** [comment]
@samdivaio - Have freshly installed the bot, still got the same issue. Will try on another server.

@DaYWhiTe - Those are enabled APIs...

@Kwoth - I've dropped the bot into the same group as me and everything, given it explicit permissions on the voice channel, still no joy. I don't understand, not even got a better error i can show or whatever :/

**Comment by RustyJuice** [comment]
Created a brand new server and have the exact same issues, so i don't think it's permissions based, not that i did given that i gave it the full set of perms for everything...

**Comment by DaYWhiTe** [comment]
Does the console give an error?

**Comment by RustyJuice** [comment]
@DaYWhiTe yeah i'm actually getting something new in the console i wasn't getting last night:

![screenshot 137](https://user-images.githubusercontent.com/7268811/27993596-433f11ec-64a5-11e7-8c8f-8a35b2c31f2d.png)

**Comment by DaYWhiTe** [comment]
I think there is not enough authority but it may be related to the server zone. Can you change the server zone and reboot the bot? And try again

**Comment by RustyJuice** [comment]
@DaYWhiTe Nope, changed from Central EU to Western EU and still the exact same issues, also completely removed all pre-reqs and re-installed the bot however have the same issue, the bot has full permissions on my server and a completely brand new server, this makes absolutely no sense.

**Comment by Sevenn83** [comment]
I've the same issue, bot join and leave immediately, and i get the same error (broken pipe)

**Comment by mantaikas9** [comment]
Same problem. Installed ffmpeg by myself and youtube-dl, still not working and console giving same error.

**Comment by DaYWhiTe** [comment]
@RustyJuice  Will you give me the link to the bot?

**Comment by DaYWhiTe** [comment]
@mantaikas9 I used the bot. The channel goes in but does not open the song. Are you new to the google api key?

**Comment by Kwoth** [comment]
Did you try restarting your pc?

**Comment by DaYWhiTe** [comment]
My bot is working but its bot is not working.Maybe the server is slow for him to react late and does not work properly

**Comment by mantaikas9** [comment]
@DaYWhiTe yes I'm new. About server speed, I think it depends on where you live, because the VPS is in my country thus I didn't experience any lag.

**Comment by Sevenn83** [comment]
To help for debug, the Dockerfile I using https://past.sevenn.fr/?0ef7efd00d1009ee#lpImlgOe0gIIJquuHIyoHk2LdG25U3Yhf1LbDINPisA=
And the file for installing ffmpeg https://past.sevenn.fr/?b28caaadbb0f49b1#n7eN3SgxhsvxI/bKSYSwU50P6EGwrLEJWOn7Lu+wk0g=

**Comment by DaYWhiTe** [comment]
link expired

**Comment by DaYWhiTe** [comment]
@mantaikas9 where are you from ?

**Comment by Sevenn83** [comment]
Weird, link work i send it to one of my friend and he can read it, but i repost it to pastbin
https://pastebin.com/mDSp3TRu  
https://pastebin.com/bvTXGCGv

**Comment by RustyJuice** [comment]
Just deployed a fresh box with Ubuntu 16.04 and the bot works fine, same location and all. Strange.

**Comment by mantaikas9** [comment]
@DaYWhiTe I'm in central Europe, Lithuania to be exact.

**Comment by Kwoth** [comment]
I guess it's solved then. You must've messed something up before.
