### ISSUE TITLE
Certain Youtube URLs cause a random video to play

### ISSUE THREAD

**Issue by 8BitSloth** [Kwoth/NadekoBot#1368]
When I try to play certain Youtube videos with either .play or .q I get an totally different video. A good example is https://www.youtube.com/watch?v=G7uph8H4V8s or https://www.youtube.com/watch?v=aoLxeSTJ4Ao, it redirects to https://www.youtube.com/watch?v=GvtNyOzGogc.

For the love of all, please fix this so Nadeko will stop playing this pretentious prick's videos.

**Comment by Devaliah** [comment]
LMFAO the bots being redirected by an ad.  we've been experimenting with it. seems to be only on monetized youtube vids, however "searching" for the song instead of a direct .q link overrides it.

**Comment by samdivaio** [comment]
I bet it overrides to similar song? last time I tested, I found the said song queued up even with the `.qs` not just with `.q`.
