### ISSUE TITLE
%playing% %queued% not working

### ISSUE THREAD

**Issue by NeonSpectrum** [Kwoth/NadekoBot#1369]
![image](https://user-images.githubusercontent.com/29432829/27993078-c2dce616-64d4-11e7-876a-05efabe0dbad.png)
forgot to remove // in playingrotateservice 
![image](https://user-images.githubusercontent.com/29432829/27993088-d98344d2-64d4-11e7-9280-6b8f0d92106c.png)

**Comment by Kwoth** [comment]
woopsie daisy

**Comment by Kwoth** [comment]
fixed?

**Comment by NeonSpectrum** [comment]
yes :3

**Comment by DaYWhiTe** [comment]
OS: Ubuntu 14.04
Bot Version: 1.55.3

yeah not working

![](https://user-images.githubusercontent.com/21060067/27993206-d6549d3c-64ad-11e7-8d9c-b53825e63e7c.png)
