### ISSUE TITLE
~i/ir command broken?

### ISSUE THREAD

**Issue by YamaJuugo** [Kwoth/NadekoBot#137]
So it was working fine, but then a few of us kinda started spamming it a lot. And it would occasionally give us a 400 error. Then it started giving a 403 no matter what. Not sure if its because we spammed or something just broke. So basically I'm asking how to fix it if possible.

http://puu.sh/nQGUM/05147e3a1f.png

**Comment by Kwoth** [comment]
there is limited number of queries you can do per day using google image api sadly. I can't do anything about that

**Comment by YamaJuugo** [comment]
ok thanks for the fast reply!
