### ISSUE TITLE
Play List Repeat not turned off

### ISSUE THREAD

**Issue by DaYWhiTe** [Kwoth/NadekoBot#1370]
OS: Ubuntu 14.04
Bot Version: 1.55.3
FFmpeg version: 3.3.2-1~14.04.york1
Youtube-dl version: 2017.07.02

The playlist does not turn off the repeater and always turns on the same song

![image](https://user-images.githubusercontent.com/21060067/27993206-d6549d3c-64ad-11e7-8d9c-b53825e63e7c.png)

**Comment by Kwoth** [comment]
you're playing a radio, it will play indefinitely....

**Comment by DaYWhiTe** [comment]
![image](https://user-images.githubusercontent.com/21060067/27994075-cab87398-64be-11e7-9031-244588bc3746.png)

It's not just radio

**Comment by DaYWhiTe** [comment]
#1053
