### ISSUE TITLE
.greet and .bye not working

### ISSUE THREAD

**Issue by JoshB84** [Kwoth/NadekoBot#1371]
I enabled them both on my channel in my server. They do not seem to show anything when people come and leave. I have also set the greet and bye messages. Dyno bot does show when people join. I am trying to get everything working with Nadeko so I can remove Dyno bot.

**Comment by DaYWhiTe** [comment]
Do you open it with .bye and .greet

**Comment by Kwoth** [comment]
Make sure nadeko has permissions to write in that channel, check your greet/bye messages with `.greetmsg` and `.byemsg`

**Comment by JoshB84** [comment]
I have it working correctly now.
