### ISSUE TITLE
.next crashes music

### ISSUE THREAD

**Issue by ManuelFte** [Kwoth/NadekoBot#1372]
Using `.next` twice in a row makes the music module crash, with the playback stopping and commands like `.stop` and `.play` returning no response; although in the console they appear as being executed correctly and show no errors. Other commands apparently work but the bot remains silent until using `.destroy`.

**Comment by DaYWhiTe** [comment]
yeah same problem 1.55.3 version

**Comment by Kwoth** [comment]
screenshot

**Comment by ManuelFte** [comment]
![screenshot from 2017-07-09 09-43-53](https://user-images.githubusercontent.com/896973/27995118-955c3796-648e-11e7-8f81-cf84d05498bb.png)

**Comment by DaYWhiTe** [comment]
This problem is present in version 1.55-1.55.3 of the bot
