### ISSUE TITLE
.srm always removes first song in the queue and messes with the index

### ISSUE THREAD

**Issue by ManuelFte** [Kwoth/NadekoBot#1373]
`.srm` always removes the song with index `#1` in the queue no matter what number is specified (except `.srm all` which works correctly). Eg. typing `.srm 12` will make the bot reply `Removed song #12`, but the song removed will actually be the one with index `#1`.

Additionally, using it makes both `.listqueue` and `.nowplaying` jump a number in the index. For example, if I'm listening a playlist and use the command, then I type `.lq` or `.np`, both of them will show that I'm listening the next song in the queue when in actuality I'm still listening the same. Typing the command again will repeat the error.

![screenshot from 2017-07-09 08-49-22](https://user-images.githubusercontent.com/896973/27995253-9acbf3a4-6490-11e7-8079-162b66b420c9.png)

**Comment by Gremagol** [comment]
Confirmed.
![srm](https://user-images.githubusercontent.com/24619854/27994396-6cdfc4d4-64bd-11e7-8f2d-f429894f2222.PNG)
