### ISSUE TITLE
NadekoRandom is not effectively random

### ISSUE THREAD

**Issue by butnotexactly** [Kwoth/NadekoBot#1378]
https://raw.githubusercontent.com/Kwoth/NadekoBot/0a36ecf06691495ea0ccb5dfc0393d4977e14c86/src/NadekoBot/DataStructures/NadekoRandom.cs

`return Math.Abs(BitConverter.ToInt32(bytes, 0)) % maxValue;` isnt an even distribution, affects hangman selection (frequent duplicates) and gambling games

Try
`((int64) Math.Abs(BitConverter.ToInt32(bytes, 0)) * (int64) maxValue) / int.MaxValue` instead?

**Comment by Kwoth** [comment]
Generated 100 milion numbers, these are the results, ignore the `%` sign at the end.
![image](https://user-images.githubusercontent.com/2537696/28037315-373f979c-65bb-11e7-9c70-e90298ab4341.png)
