### ISSUE TITLE
Using filtered words are caps-sensitive while adding them aren't

### ISSUE THREAD

**Issue by Lemonical** [Kwoth/NadekoBot#138]
I added two words for it to filter, but without any caps, it got added to the list of filtered words no problem. However, it will only work if banned words are said without caps. Banned words said with caps will not be filtered. I tried adding the same banned words in caps and gave me this error: "💢 Error: That word is already banned."

**Comment by Kwoth** [comment]
Thanks for the report, it was already fixed this morning, and it will be fixed in the next release
