### ISSUE TITLE
Sound Cloud Songs Don't Register Their Queue Time 

### ISSUE THREAD

**Issue by Devaliah** [Kwoth/NadekoBot#1380]
It's easier to show this in a screen shot then try to explain it. 

![image](https://user-images.githubusercontent.com/26513239/28042178-12039a62-6581-11e7-9eaa-8722a146d2f8.png)

**Comment by Kwoth** [comment]
Can you show me your console output when you queue a song/songs? Can you try queuing `.q oracion ending full`

**Comment by Devaliah** [comment]
Queued the same song on YouTube, then on SC:

![image](https://user-images.githubusercontent.com/26513239/28042898-3748b660-6584-11e7-830b-e1371fab06f2.png)

then here is the console:
![image](https://user-images.githubusercontent.com/26513239/28042953-7966ad22-6584-11e7-85fb-c44e9cfc616d.png)

**Comment by Kwoth** [comment]
Oh, those are soundcloud songs. I see, i must've messed up. Thanks
