### ISSUE TITLE
Installer GUI

### ISSUE THREAD

**Issue by Jukuu** [Kwoth/NadekoBot#1385]
When running installer, anywhere the installer shows "not installed" runs off of the screen. 
![image](https://user-images.githubusercontent.com/7268396/28096610-0a62542c-665f-11e7-98c5-7741b8346e75.png)

**Comment by Kwoth** [comment]
I'll just make it say 'none' tomorrow 😂

**Comment by Kwoth** [comment]
Should be fixed now
