### ISSUE TITLE
"mute" is unresponsive

### ISSUE THREAD

**Issue by bakabakasama** [Kwoth/NadekoBot#1386]
Mute no longer works in any way. using .mute doesn't return anything in console.
Examples: http://i.imgur.com/9QjKiXq.png and http://i.imgur.com/XNz5JOu.png

**Comment by samdivaio** [comment]
its `mute @user` try `.h .mute` and currently discord messed up the role hierarchy and users can send messages if they have perms to send message in any channel even if that said role is below the mute role.

**Comment by Kwoth** [comment]
I don't know why it's not showing up in the console, i checked the code. Must be because it has 2 overloads. Reopen if there is an actual bug with the command itself.
