### ISSUE TITLE
New Nadeko Updater won't start.

### ISSUE THREAD

**Issue by Aerysch** [Kwoth/NadekoBot#1388]
Hi there,

after restarting the updater the new version were downloaded and installed and thats it. Every time I try to start the updater it will check for newer versions and then nothing will happen.

I'm not sure if there are any requirements for the updater itself but since the older versions worked just fine and out of the box I'm a bit confused.

What I've tried so far: repairing the updater, reinstalling the updater, rebooting the hole server.

Maybe I'm missing a simple point, thanks for your time and help.

Further information:

Windows Server 2016 (1607)

**Comment by Kwoth** [comment]
no there are no new requirements, it's just an UI overhaul. Try removing the Updater and installing it again

**Comment by Aerysch** [comment]
I did that already. Even deleting it from \AppData\Local\Apps\2.0 manually did not worked out. I've redownloaded the installer as well but that did not changed something either. Is there something similar I can test on a Windows Server machine to exclude a general problem with apps like that?

Thanks a lot.

**Comment by Kwoth** [comment]
It might have something to do with your server permissions. Try restarting your server? Try disabling internet explorer advanced security thing

**Comment by Aerysch** [comment]
Yes, restarted the machine. I guess you misunderstood me there, the webinstaller seems to be successfully check for a new version and the latest version were updated trough that webinstaller so I guess this part works fine. I think just the app itself is somehow not starting. Is there a general name for applications like the nadeko updater so I can do some research for common problems on windows server machines? Am I right that this one is based on dotnetframework?

**Comment by Kwoth** [comment]
it's a WPF application

**Comment by Aerysch** [comment]
Okay, finally I got it running again.

I just went to the Eventlog (not sure why I did not go there earlier) and noticed the following error:

![image](https://user-images.githubusercontent.com/21172960/28125452-ed9062bc-6726-11e7-89af-a9f12cec3c00.png)

I did some research and found multiple topics about that error and the following policy was preventing the UAC Popup to confirm that you let an unknown application to make changes to your harddrive so I changed it as shown. **!!! The following step brought up some new errors on other application so be aware of that !!!**

![image](https://user-images.githubusercontent.com/21172960/28125305-84356380-6726-11e7-869e-08230c4a5e69.png)

After changing that, the application is running fine again.

My advise at this point is to disable the policy again after you successfully registrated the application to avoid permission errors on other points.

In addition to that you have to install 

> 32Bit: Microsoft Visual C++ 2010 SP1 Redistributable Package (x86) 

or you will get an MSVCR100.dll missing Message but this has nothing to do with the problem mentioned here.

I'm not sure if you could do some changes to the application for more user-friendly experience but at least, it is fixable. 👍
