### ISSUE TITLE
clean code

### ISSUE THREAD

**Issue by tg44** [Kwoth/NadekoBot#139]
Hy there!

I have no idea when this project started, but when I started to explore its functionality my cleancode eyes started bleeding and my do it hackily mind started to boot up :)

So we have commands which are under the commands package, but we have modules where you can either add a command or write it in place? Why? Why not separate commands from modules? Or give modules a bit deeper hierarchy? Sth like modules/gambling/{GamblingModule, DrawCommand, FlipCoinCommand, etc.}

I think the command itself (Do) must contains as few commands as possible sth like parse input, call the main logic function, write the output to the channel, OR should be separated like in the FlipCoinCommand.Init do. I think its really messy now whats need to be in the MessageRecieved handler function and what is not.

The Classes are more like Helpers, the classes is simply a bad nameing, I think the things inside this namespace are OK. Some border fixing may need (which function is a helper and which is a command executer), but it's mostly OK.

I do the refactoring stuff if you give it a green light, it's an intresting project with intresting features, but the code starting to be a swamp or jungle if sb doesn't fix it.

**Comment by Kwoth** [comment]
Hello there, and thanks for checking out the project :D

The reason modules both have separate commands, and commands in Do is that i tend to keep simple functions in there to prevent a new file for each new small command.

I did think about splitting modules into smaller ones, but I like having a separate prefix for each module, which wouldn't be possible if I've put a couple of commands in each module.

So, complex commands (generally) get their own files, and simpler ones are written in place.

If you do want to refactor it, you can do something smaller as an example and PR it, so i can tell you would i accept something like that.

**Comment by Kwoth** [comment]
Is there any work being/will be done on this?

**Comment by tg44** [comment]
I will make a PR today.

**Comment by Kwoth** [comment]
I think this is nearly done. We can just maybe see what to do with all those statics/singletons once.70791ebe7f9dcedfb4a77d765709ee006b354cd9
