### ISSUE TITLE
administration_presence_updates key is missing from eng response strings

### ISSUE THREAD

**Issue by AJdisco** [Kwoth/NadekoBot#1390]
🤔  I've got no clue what i did to cause this.
![image](https://user-images.githubusercontent.com/26025947/28118927-fd9b1024-670a-11e7-921f-6a221e46a855.png)

I'm completely stumped on this. 🤷‍♂️  It's currently flooding my nadeko console.

**Comment by Kwoth** [comment]
`.langset en-US`
