### ISSUE TITLE
Music missing

### ISSUE THREAD

**Issue by mamounir** [Kwoth/NadekoBot#1391]
the command work , the crendencials is all set 
![capture d ecran 646](https://user-images.githubusercontent.com/22207787/28137507-877801e8-671b-11e7-8ef0-4e0c83b12103.png)

But there no music playing in the vocal room

**Comment by samdivaio** [comment]
where is the bot hosted?
OS ver, ffmpeg ver, youtube-dl version

**Comment by mamounir** [comment]
ffmpeg ver and youtube-dl version

**Comment by mamounir** [comment]
but before youtube-dl it wasnt more working

**Comment by samdivaio** [comment]
What do you mean?

**Comment by mamounir** [comment]
i install everything and set up all correctly , the command work , the bot came in the voice channel and he doing nothing more, not even a single sound

**Comment by samdivaio** [comment]
Where is the bot hosted?
