### ISSUE TITLE
Music ytdl issue

### ISSUE THREAD

**Issue by amants** [Kwoth/NadekoBot#1392]
Hey guys!
I just now updated the bot and had issues with the music commands, couldn't get a song to play. constantly said "No song found" after checking the terminal I noticed it said ytdl was missing so I reran the install prerequisites and it installed it for me. After running the bot again with auto update the songs will get retrieved it will pop up a message saying it started playing the song but the bot just joins and leaves the voicechat instantly. After checking the terminal again the following message popped up:
`16:12:22 Ytdl | WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.`

I know it's related to the ytdl package but I searched all through google and couldn't find anything. Is this a programming error on your side of things or is it a missconfiguration on my end?

I'm running Ubuntu 14.04.5 LTS

**Comment by samdivaio** [comment]
_"bot just joins and leaves the voicechat instantly"_ 
Are you using webbrowser to access Discord?

To, fix `Ytdl | WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.`
Use the following commands:

```
locale-gen en_GB.UTF-8
update-locale LC_ALL=en_GB.UTF-8
```
reboot the vps with `reboot` command.

**Comment by amants** [comment]
> "bot just joins and leaves the voicechat instantly"
> Are you using webbrowser to access Discord?
> 
> To, fix Ytdl | WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
> Use the following commands:
> 
> locale-gen en_GB.UTF-8
> update-locale LC_ALL=en_GB.UTF-8
> reboot the vps with reboot command.

I'm using the Desktop application on Windows 10 and Mac OSX Sierra
