### ISSUE TITLE
Nadeko Bot Cannot Find The Queued Song?? HELP PLEASE!

### ISSUE THREAD

**Issue by sofakingg** [Kwoth/NadekoBot#1393]
So i will type .q <song name> or .q <youtube link>, I installed everything and did all the proper API's and it is all up to date but Nadeko bot responds with this:  
![screenshot 16](https://user-images.githubusercontent.com/30138428/28151857-4c86c98e-676b-11e7-8a84-1f3b3a76c251.png)
![screenshot 15](https://user-images.githubusercontent.com/30138428/28151866-52b6f518-676b-11e7-9ffd-4a14ae4efded.png)

**Comment by samdivaio** [comment]
restart pc, if you have installed `youtube-dl` from Nadeko Updater.

**Comment by Kwoth** [comment]
Yup, it means you didn't install, or didn't restart your pc after installing youtube-dl
