### ISSUE TITLE
ffmpeg: error while loading shared libraries: libx265.so.95: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by coromd** [Kwoth/NadekoBot#1394]
Trying to play music but every time I try it spews this

ffmpeg: error while loading shared libraries: libx265.so.95: cannot open shared object file: No such file or directory

Tried purging ffmpeg and reinstalling and it didn't help. Tried googling it and there's really not much to go off of.

**Comment by samdivaio** [comment]
OS?

**Comment by coromd** [comment]
Sorry, didn't get a notification. Ubuntu Server 16.10

**Comment by samdivaio** [comment]
Gotcha, thats an issue with some vps. 
Try using command `sudo ldconfig` then test ffmpeg by typing `ffmpeg` if its shows the same error again,
build static version of ffmpeg with options `--pkg-config-flags="--static"` and `--with-openssl` make sure `build-essential`, `openssl`, `libssl-dev` are already installed.
If it's a new vps you can try reinstalling os to save time.

**Comment by shikhir-arora** [comment]
Type `ffmpeg` and see if `-enable-libx265` is in the flags. You may need to rebuild it with that if it's missing.

**Comment by darkterrorooo** [comment]
i just solve it.

first , you should install x265,  it may install to   /usr/local/lib
second , configue, make your ffmpeg again.

lld ./ffmpeg
it will show how ffmpeg load .so faild,  you will see the systme .so dir.
on my linxu ,this dir is  /lib64/
so   
cp libx265.so.151 /lib64/  

./ffmpeg 
is work
