### ISSUE TITLE
Slot machine message with custom currency

### ISSUE THREAD

**Issue by dnaf** [Kwoth/NadekoBot#1395]
The slot machine messages use the currency symbol you set in the database, which doesn't make sense.

![slot machine](http://i.imgur.com/qYTz1Sy.png)

with the custom currency, it tells me the slot machine had a single :dollar:. it should just say :cherry_blossom: regardless of my custom currency symbol.

**Comment by samdivaio** [comment]
They are completely different things.
I believe you just edited your `NadekoBot.db` for emoji and forgot to change the image files.
Try checking and replacing images in your `src/NadekoBot/data/images` folder if you are hosting on Linux or `system\data\images` for Windows.

**Comment by dnaf** [comment]
@samdivaio I know I can change the emoji image, but I'd personally rather just have the emoji in the message changed. I suppose it may make more sense to change the slot image, now that I'm thinking about it...

**Comment by Kwoth** [comment]
data/images
