### ISSUE TITLE
Warning for filtered words

### ISSUE THREAD

**Issue by dnaf** [Kwoth/NadekoBot#1398]
It'd be nice if Nadeko could warn users when they say a filtered word instead of just deleting the message.

**Comment by Jonz00r** [comment]
Use custom reactions. Or do you mean like .warn ?

**Comment by Deivedux** [comment]
This is not actually the place for suggestions, altho I do remember something already suggested...
Anyway, for suggestions you need to post it here: http://feathub.com/Kwoth/NadekoBot but the site is down for quite a while and we don't know when it will get back up.

**Comment by Jonz00r** [comment]
Nevermind. I'm dumb. That wouldn't. work

**Comment by Kwoth** [comment]
Post features on feathub, when it's back.
