### ISSUE TITLE
Feature Request - Record Sound to File

### ISSUE THREAD

**Issue by myoblastic** [Kwoth/NadekoBot#140]
Occasionally my friends and I have some hilarious moments over discord voice that would be great to record, as having a built in functionality is better than opening audacity/wasting precious time before the moment disappears

Maybe have a command (!rec to start/stop or something) that takes the incoming voice data (no idea if discord.net supports it) and uses ffmpeg to put it in a file? Alternatively, if I use Virtual Audio Cable to output discord to a certain output, have a command that uses ffmpeg to take that output into a file.

A more advanced thing would be like an oddshot system for audio - constantly record the past x amount of minutes, and on a command cut that time into an audio file.

**Comment by Kwoth** [comment]
yeah good idea, sadly discord.net does not support audio receiving atm.

I will implement this after discord.net 1.0 is done

**Comment by Kwoth** [comment]
Maybe one day. Not planned.
