### ISSUE TITLE
Time counting in singing

### ISSUE THREAD

**Issue by DaYWhiTe** [Kwoth/NadekoBot#1400]
![noknown](https://user-images.githubusercontent.com/21060067/28167666-07b25394-67e5-11e7-8475-773868d8b672.png)

As you can see, this is added to the channel description and it shows how long the song has play

**Comment by ItsFriday** [comment]
? Suggestion/Request go here: http://feathub.com/Kwoth/NadekoBot

**Comment by DaYWhiTe** [comment]
I am sorry. i forgot

**Comment by DaYWhiTe** [comment]
Stay open until feathub opens. Then i forget

**Comment by Kwoth** [comment]
Just post on feathub when it's up again (should be this week i believe)
