### ISSUE TITLE
Word filtering doesn't seem to filter edited messages

### ISSUE THREAD

**Issue by dnaf** [Kwoth/NadekoBot#1401]
if a user sends a message then edits it to contain a filtered word, nadeko doesn't delete it.

**Comment by ItsFriday** [comment]
I don't think its possible at the moment for a bot to monitor an edited message.

**Comment by dnaf** [comment]
@ItsFriday [it is.](https://discordapp.com/developers/docs/topics/gateway#message-update) it's even possible to have nadeko log message edits already with `.log MessageUpdated`.

**Comment by Kwoth** [comment]
Just fixed
