### ISSUE TITLE
trying to change .antispam's options disables it

### ISSUE THREAD

**Issue by SillyBirds** [Kwoth/NadekoBot#1402]
It's not possible to change the options after `.antispam` has been enabled.

Trying to switch options when it's already on, ie doing `.antispam 10 ban` or something else, will disable it instead. The disable command should be the `.antispam` command alone, without the options.

This is kinda annoying if there are ignored channels, since those have to be reapplied when turning it back on.

On 1.55.7.

**Comment by Kwoth** [comment]
fixed

**Comment by Kwoth** [comment]
woops. I referenced wrong issue.

**Comment by Kwoth** [comment]
Should be working now. Please test it and report back.

**Comment by SillyBirds** [comment]
Changing the options only works if there are no ignored channels.

I disabled it, re-enabled it and was able to change the options. But once I re-added an ignored channel, it stopped responding to option changes.

![pic](http://i.imgur.com/CSGAlNl.jpg)

**Comment by Kwoth** [comment]
Please tell me if it works now.

**Comment by SillyBirds** [comment]
@Kwoth It's working now, but the bot now doesn't post a message saying the options have changed (you have to use `.antilist` to check), but that's minor compared to the earlier issue.

![pic](https://i.imgur.com/hapu7iF.jpg[/img)

Thanks for your hard work 👍

**Comment by Macley-Kun** [comment]
@SillyBirds then you can close the issue :')
