### ISSUE TITLE
Console is going into sleep when not in running foreground or scrolling up?

### ISSUE THREAD

**Issue by Aerysch** [Kwoth/NadekoBot#1404]
Hi,

just mentioned (like another one earlier that day on W10) that the console will going into sleep in some cases.
In my case this happens, wenn you are scrolling up the recent tasks.
The console will not stop imidietly but the next action won't be executed until you are going back to the bottom and hit enter.
I know that sounds wired but since I'm not alone with this I thought that would be something to have a look at?

Greetings

**Comment by Kwoth** [comment]
you can scroll up but not click on it. If you do you will block the program. If you wanna see what happened before, right click, select all, right click again to copy , and paste it into text editor.

**Comment by Aerysch** [comment]
Okay, thanks.
