### ISSUE TITLE
.prefix does not prevent the prefix from having a space in it

### ISSUE THREAD

**Issue by PapaMichael** [Kwoth/NadekoBot#1405]
.prefix allows you to change a server prefix to something with a space in it, however this new prefix will never be recognized by the bot (due to the space), forcing manually db editing to get the bot to ever respond to commands again.

**Comment by Kwoth** [comment]
not true. Just tested it.

`.prefix one two`
`one twostats`

Correctly works.

**Comment by PapaMichael** [comment]
Whoops! I never thought to try just the first word. ^.^

**Comment by Kwoth** [comment]
just the first word? Both words.
