### ISSUE TITLE
Music does not pause when every user leaves the voice channel.

### ISSUE THREAD

**Issue by redsauce117** [Kwoth/NadekoBot#1407]
In my server, when everyone has disconnected from the Voice server, except for the bot itself, it continues to play the music, wasting bandwidth on my end. In previous updates the bot would pause music playback when no users were left in the voice channel with it. Please fix this? I don't have unlimited bandwidth.

**Comment by Kwoth** [comment]
Library we're using is very buggy when it comes to that. I can't do it.

**Comment by redsauce117** [comment]
But it was working before?

**Comment by ItsFriday** [comment]
Due to the new way nadeko is built, it isnt currently possible.
