### ISSUE TITLE
Translation mistake - german

### ISSUE THREAD

**Issue by julian100004** [Kwoth/NadekoBot#1408]
If you use **.crad** it always says that it has been toggled of, no matter if you toggled it on or not. 
Reaktionsnachricht für die benutzerdefinierte Reaktion mit der ID 123 wird _nicht_ als DN gesendet.
it should be
Reaktionsnachricht für die benutzerdefinierte Reaktion mit der ID 123 wird als DM gesendet.

**Comment by Kwoth** [comment]
It's been changed, will be live next time I push string updates.
