### ISSUE TITLE
Role Colour Changing

### ISSUE THREAD

**Issue by MxTrex** [Kwoth/NadekoBot#1410]
When I type .rrc nothing happens, other commands work though.
I am hosting the bot manually.

**Comment by ManuelFte** [comment]
Hosting means that you have Nadeko installed on your PC following this guide: http://nadekobot.readthedocs.io/en/latest/guides/Windows%20Guide/

Also make sure that Nadeko's highest role is higher in the list than the role you want to rotate.

And please stop opening bug reports to ask questions, we have a support server for that: https://discord.gg/0ehQwTK2RBjAxzEY
