### ISSUE TITLE
Can't play my computer playlist anymore :(

### ISSUE THREAD

**Issue by avidyano** [Kwoth/NadekoBot#1411]
Hello, so I've been able to play my music playlist through Nadeko without any problem. But then now it suddenly stopped working or has shown an error. Here's the picture below:

![image](https://user-images.githubusercontent.com/30206835/28244733-def4f4ba-69c0-11e7-873a-83f1af77410d.png)

It said that there's an error. Is there anything that I can do to fix it? Thanks! I appreciate for taking your time to read this.

**Comment by Kwoth** [comment]
that second error has nothing to do with the music. Your bot is getting disconnected. Restart it.

You're using the command incorrectly.

`.lopl C:\music` for playlist
`.lo C:\music\mysong.mp3` for the song

Please read help using `.h .commandname` in the future

**Comment by samdivaio** [comment]
Also update your bot, 0.9x is not supported by library or us.
