### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by Nihilou** [Kwoth/NadekoBot#1413]
Greetings,
I got a long error string when searching for a song.
Ending in Song not found, Anyone who can help me out here?

![19b1af53b47f69258264a2f0ed1332aa](https://user-images.githubusercontent.com/30213284/28248022-98cc5d8a-6a3c-11e7-9ee1-2528aab7f2eb.png)

**Comment by xnaas** [comment]
Bot version?

**Comment by Nihilou** [comment]
1.55.7

**Comment by samdivaio** [comment]
install youtube-dl, if its windows then restart your pc after installing

**Comment by Nihilou** [comment]
fixed, youtube dl bugged so I reinstalled it and it works
