### ISSUE TITLE
Music issue maybe?

### ISSUE THREAD

**Issue by Pizzahaet** [Kwoth/NadekoBot#1414]
I am new to the self hosting bot stuff, but when I setup my bot to work with music it just doesn't work, it will que the song but it will finish the song before it even plays it I know that makes no sense but I look at the console and it says this...

Unreconized option "reconnect"
Error splitting argument list :option not found

Is there like a specific amount of CPU or ram I need to use music well? I have ffmpeg and the correct googleapis enabled and added to the credentials.json file and still no success

**Comment by Kwoth** [comment]
You need ffmpeg 3.3+

**Comment by Pizzahaet** [comment]
How can I update it?

**Comment by Kwoth** [comment]
delete it and redownload again

**Comment by Pizzahaet** [comment]
It is still only giving me version 2.6

**Comment by Pizzahaet** [comment]
I am on Centos7

**Comment by Kwoth** [comment]
I'm not sure music even works on centos, see #1053   @samdivaio help

**Comment by Pizzahaet** [comment]
Maybe you can make a branch that fixes it because I found there is no such argument called reconnect which is used in songbuffer.cs, maybe there is another argument that can be used that supports ffmpeg 2.6?

**Comment by samdivaio** [comment]
@Pizzahaet there is some issue with centOS https://github.com/Kwoth/NadekoBot/issues/1308  but you can try using [docker](https://docs.docker.com/engine/installation/linux/docker-ce/centos/). Checkout the [Guide here](https://nadekobot.readthedocs.io/en/latest/guides/Docker%20Guide/)
