### ISSUE TITLE
uninstall issue

### ISSUE THREAD

**Issue by roxtarr** [Kwoth/NadekoBot#1416]
I manually deleted Nadeko folder and unistalled updater, then reinstall Nadeko updater. After all, i can't install Nadeko bot becouse updater thinks it already installed, and i can't launch bot ("please install or reinstall NadekoBot, or run it manually via its desktop shortcut")
![explorer_2017-07-17_02-25-06](https://user-images.githubusercontent.com/28262454/28252208-4cd3ae1e-6a97-11e7-8693-7fafb08e23cc.png)

**Comment by Kwoth** [comment]
uninstall the bot from the Control Panel -> Add or remove programs.

**Comment by Kwoth** [comment]
If that doesn't work, go to https://github.com/Kwoth/NadekoBot/releases and manually download the .exe installer and run it
