### ISSUE TITLE
Location of config files after the new installer.

### ISSUE THREAD

**Issue by FLeWz** [Kwoth/NadekoBot#1417]
Before the launch of the new installer configs were stored in Modules folder. Now when I updated the bot with new installer I cant find Modules folder neither the config files.

**Comment by samdivaio** [comment]
What was your previous Nadeko's version?

**Comment by FLeWz** [comment]
My previous version was 1.3a now I updated to 1.5x.x

**Comment by shikhir-arora** [comment]
What OS are you running? Have you done a search for it `find / -name *modules` or something similar if you are on a Linux system.

**Comment by FLeWz** [comment]
I am running windows... I did search all the drives on root. Nothing came up.

**Comment by shivaco** [comment]
Looks like every user doesn't have the `Modules` folder on 1.4+ versions

**Comment by FLeWz** [comment]
You dont tell...thats the reason why i posted this.

**Comment by willysunny** [comment]
Wait ... what config for what modules?

Afaik, the only config you would ever need to touch is the crediential.json

And maybe sometimes the nadekobot.db for the database, and that's about it.

What modules are you talking about?

**Comment by FLeWz** [comment]
All of them, the whole Modules folder. I have a bit different setup on commands and responses and generaly how the bot works. I need access to all config files in the new version.

**Comment by Kwoth** [comment]
there's only credentials.json which is next to the .exe on windows, and in src/NadekoBot on linux/mac/source
