### ISSUE TITLE
Everything works but only as long as the NadekoBot.exe is running

### ISSUE THREAD

**Issue by Rogue-99** [Kwoth/NadekoBot#1418]
Hi,

I set up everything and managed to get the bot working on my server but only as long as I keep the command window open on my PC after running NadekoBot.exe.

As soon as I close the window or shut down the PC, the bot will no longer accept commands in Discord.

Surely this cannot be normal. It would be great if you could let me know what I'm doing wrong!

Many Thanks!

**Comment by Jonz00r** [comment]
The bot runs on your computer. If you close the bot how can it possibly
work?

**Comment by Rogue-99** [comment]
I don't know... So everyone who is running the Nadeko bot has their PC running 24/7 to keep it active?

**Comment by Jonz00r** [comment]
Yes. Or they run it on a server.

**Comment by Rogue-99** [comment]
Oh, OK. I did not realise that. Many thanks for the clarification!
