### ISSUE TITLE
Using .iam with .tesar enabled doesn't remove all other roles but only 1

### ISSUE THREAD

**Issue by spark942** [Kwoth/NadekoBot#1419]
All self-assignable roles aren't removed when using `.iam` but only one.

**Comment by willysunny** [comment]
mind elaborate on it? like a sample case?

**Comment by spark942** [comment]
List of self-assignable roles:
`Role1`, `Role2`, `Role3`, `Role4`, `Role5`

My roles : `Role1`, `Role2`, `Role3`, `Role6`
Roles after using `.iam Role 5` : `Role1`, `Role3`, `Role5`, `Role6` (replaced 2 by 5)
Roles I should have after using `.iam Role 5` :  `Role5`, `Role6` (remove 1,2,3)

**Comment by Kwoth** [comment]
fixed in https://github.com/Kwoth/NadekoBot/commit/0bf6459e6ad53364ed45e3d8fe4dd4b1ef7177cd
