### ISSUE TITLE
Shuffle output string broken

### ISSUE THREAD

**Issue by willysunny** [Kwoth/NadekoBot#1421]
Even it's translated, but it does not appear in the output when using .shuffle

**Comment by Kwoth** [comment]
print screen?

**Comment by willysunny** [comment]
![image](https://user-images.githubusercontent.com/5907852/28453595-8b5282b4-6e2a-11e7-9112-0091acfdcfee.png)
![image](https://user-images.githubusercontent.com/5907852/28453614-a2d090f2-6e2a-11e7-9741-d0defefa6057.png)

**Comment by Kwoth** [comment]
Strings just aren't updated probably. When they are, it will be ok.
