### ISSUE TITLE
Stole my flowers

### ISSUE THREAD

**Issue by chipmunck12sold** [Kwoth/NadekoBot#1422]
So I was gambling my flowers on a server. I have 61k or 64k flowers. Then my phone froze for a second so I had to reset my discored. As soon as I came back I lost 10k, then it kept happening... Now I'm at 0. Can I get my flowers back

**Comment by willysunny** [comment]
more like, what command were you executing on the server that you are gambling?

**Comment by shivaco** [comment]
I once had 100k, but accidentally restarded my phone and now I have 0. Nadeko likes trolling me.

**Comment by ItsFriday** [comment]
If you want a REAL response.
Show some proof of this "glitch" happening, tell us the command you were using.

if you want a TROLL response.
Wow nadeko is a real meanie

**Comment by chipmunck12sold** [comment]
I used .bf what ever number h or t

**Comment by Kwoth** [comment]
No lol

**Comment by chipmunck12sold** [comment]
Wow thx nadeko for glitching my flowers
