### ISSUE TITLE
dotnet stop working?

### ISSUE THREAD

**Issue by EverBlueFly** [Kwoth/NadekoBot#1424]
How should I fix it....?
I've installed .Net Framework 4.6.2,however NadekoBot still not work.
screenshot: http://imgur.com/a/1gBhv

**Comment by Kwoth** [comment]
Nadeko doesn't use .net framework.

You didn't setup your credentials.json correctly. Read the guide 

http://nadekobot.readthedocs.io/en/latest/guides/Windows%20Guide/

JSON Explanations on the left also provide instructions of what to put in each of the fields.

**Comment by samdivaio** [comment]
Windows 7 is not supported by .net core sdk, you can only use virtual box to host it on windows 7.
**Guide:
Prerequisites
Windows 8 or later**

**Comment by EverBlueFly** [comment]
@samdivaio 
I followed the guide again with my notebook (windows10) 
it still doesn't work....
http://imgur.com/a/tljZW
is NadekoBot only for Windows 8 !?

**Comment by samdivaio** [comment]
> Kwoth commented 2 hours ago
> You didn't setup your credentials.json correctly. Read the guide
> http://nadekobot.readthedocs.io/en/latest/guides/Windows%20Guide/
> JSON Explanations on the left also provide instructions of what to put in each of the fields.

Your token is incorrect.

**Comment by EverBlueFly** [comment]
@samdivaio  
I know what's wrong~
I copied wrong the token~~
Thank you :)
