### ISSUE TITLE
Patreon commands, selfhost

### ISSUE THREAD

**Issue by julian100004** [Kwoth/NadekoBot#1425]
**.clparew** not working for my patreons 🤔 i think i should've done everything right. They already got they're roles but they can't get the flowers. We even waited a few hours but still just getting the "error" message that they can't claim the flowers right now.

**Comment by Deivedux** [comment]
On public Nadeko you now have to DM the bot to claim flowers, check if it's the same for self-hosters.

**Comment by Kwoth** [comment]
`.clparew` has nothing do with their roles. You have to self host, and setup your patreon access token, and campaign id in credentials.json in order to have patreon flower claiming feature enabled on the bot. You can see exact key names in JSON explanations in the guide.

**Comment by julian100004** [comment]
Still getting this error
![image](https://user-images.githubusercontent.com/21989955/28394063-c6e179ac-6cea-11e7-817b-e5020732e047.png)

**Comment by Kwoth** [comment]
That means you campaign id is incorrect.

**Comment by julian100004** [comment]
Then i'm too incompetent to find it. I don't know where it is 🤔

**Comment by Trielice** [comment]
also having this problem with improper campaign id..     my patreon has a client ID  .. is that it?  doesn't seem to work though
