### ISSUE TITLE
.streamrole takes an unusually long time to execute.

### ISSUE THREAD

**Issue by QuantumToasted** [Kwoth/NadekoBot#1426]
![image](https://user-images.githubusercontent.com/30324210/28430130-f3e95d02-6d44-11e7-9761-6e46f0a4dde9.png)
`.streamrole` seems to take an unusually long time to execute (regularly 15+ seconds). I'm not sure if this is expected for the commands functionality or if it is a bug. Someone else was having this issue yesterday and they claimed it would take *minutes* to execute.

**Comment by Kwoth** [comment]
It is not a bug. Recent patch to streamrole forces the bot to check everyone from the first role to be checked right away if they're streaming, and if they are, give them the role right away (assuming they fulfill the preconditions).

**Comment by Kwoth** [comment]
I sped it up 5x now, but it may error out if there are too many users. I'm not sure about role add ratelimiting.
