### ISSUE TITLE
The bot says its playing music, but i cant hear anything

### ISSUE THREAD

**Issue by Folke137** [Kwoth/NadekoBot#1427]
Music is silent
I installed the FFMPEG and YOUTUBE-DL correctly
The google api is also done exactly as the guide said.

The bot is working fine with everything else

**Comment by Folke137** [comment]
i hosted it on windows on a secondary computer that is always on

**Comment by Folke137** [comment]
21:07:37 NadekoBot | Starting NadekoBot v1.55.7
21:07:37 NadekoBot | Shard 0 logging in ...
21:07:39 NadekoBot | Shard 0 logged in.
21:07:39 NadekoBot | Shard 0 loading services...
21:07:39 NadekoStrings | Loaded 23 languages (ja-jp,ar,nb-no,cs-cz,he-il,it-it,ru-ru,da-dk,en-us,de-de,ko-kr,es-es,pt-br,nl-nl,sr-cyrl-rs,zh-tw,sv-se,fr-fr,id-id,tr-tr,pl-pl,ro-ro,zh-cn) in 0,04s
21:07:39 PermissionsService | Permission version is 1, upgrading to 2.
21:07:40 PermissionsService | Loaded in 0,30s
21:07:40 NadekoBot | Shard 0 connected in 2,55s
21:07:40 NadekoBot | Shard 0 ready.
21:07:46 SelfService | Created 1 out of 1 owner message channels.
21:07:51 MusicService | Checks
21:07:51 MusicService | Get or add
21:07:51 MusicService | Getting default volume
21:07:51 MusicService | Creating musicplayer instance
21:07:51 MusicPlayer | Initialized
21:07:51 MusicPlayer | Loop started
21:07:51 MusicService | Subscribing
21:07:51 MusicService | Done creating
21:07:51 NadekoModule | Getting player
21:07:51 MusicService | Checks
21:07:51 MusicService | Get or add
21:07:51 NadekoModule | Resolving song
21:07:51 YoutubeResolveStrategy | Getting link
21:07:55 Ytdl | WARNING: unable to extract uploader nickname

21:07:55 NadekoModule | Queueing song
21:07:55 NadekoModule | Added
21:07:55 MusicPlayer | Starting
21:07:55 NadekoModule | --------------
21:07:55 CommandHandler | Command Executed after 0/0,016/4,438s
        User: Folke#5013 [84054119190368256]
        Server: PoonBot [84054377559527424]
        Channel: general [84054377559527424]
        Message: .play alaska accuse
21:07:59 MusicPlayer | Get current user
21:07:59 MusicPlayer | Connecting
21:08:00 MusicPlayer | Connected, stopping
21:08:00 MusicPlayer | Disconnected
21:08:01 MusicPlayer | Connecting
21:08:01 MusicPlayer | Got Audio client
21:08:01 MusicPlayer | Created pcm stream

**Comment by Folke137** [comment]
this fixed it!

"That error only appears when user have 32bit .net core sdk installed instead of 64bit on a 64bit system.
I am not sure how that could affect macOS as there is no 32bit version of .net core.
I suggest @zentek12 to install the .net core "sdk installer" from here: https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1-preview2.1-download.md"

**Comment by samdivaio** [comment]
That could happen with windows OS if it doesn't have some dotnet prerequisites, installing .net core sdk appears to fix it for good.
