### ISSUE TITLE
"Too few parameters" only works on one server

### ISSUE THREAD

**Issue by shikhir-arora** [Kwoth/NadekoBot#1428]
I've received this from a few people. For some reason, the automatic help menu with Nadeko that says "Too few parameters" when one does something like `.mute` without arguments only works on one server (the first server our selfhosted bot is on). Verified permissions and confirmed it only works on one server. On the others, you need to do `.h .mute` to get the menu. Doing `.mute` for example doesn't output anything.

Is that a bug or am I missing something? Sorry, been swamped lately and haven't had time to look closer! 

Thanks 👍

**Comment by shikhir-arora** [comment]
```0|Nadeko   | 18:09:59 CommandHandler | Command Errored after 0/0/0s
0|Nadeko   | 	User: .vlexɹɐ.#5320 [243902693666455553]
0|Nadeko   | 	Server: JustTest [317157817045745664]
0|Nadeko   | 	Channel: general [317157817045745664]
0|Nadeko   | 	Message: .mute
0|Nadeko   | 	Error: The input text has too few parameters.
0|Nadeko   | 18:10:17 CommandHandler | Command Errored after 0/0/0.004s
0|Nadeko   | 	User: .vlexɹɐ.#5320 [243902693666455553]
0|Nadeko   | 	Server: SeriousShit [284962667922194432]
0|Nadeko   | 	Channel: main-mail [284962667922194432]
0|Nadeko   | 	Message: .mute
0|Nadeko   | 	Error: The input text has too few parameters.
0|Nadeko   | 18:10:26 CommandHandler | Command Errored after 0/0/0s
0|Nadeko   | 	User: .vlexɹɐ.#5320 [243902693666455553]
0|Nadeko   | 	Server: EC || Bot & Dev || General [249664293656592384]
0|Nadeko   | 	Channel: musicbots [277603445794668555]
0|Nadeko   | 	Message: .mute
0|Nadeko   | 	Error: The input text has too few parameters.
``` 

It does output the proper console error on all the servers, but only one of them "responds" when doing something like `.mute` with the help.

**Comment by Kwoth** [comment]
maybe `.ve` is not enabled on other servers? I'm not sure what your'e asking

**Comment by shikhir-arora** [comment]
Yeah, *facepalm* 
Forgot to do that. 

/closed
