### ISSUE TITLE
Dicerolling

### ISSUE THREAD

**Issue by Sairys** [Kwoth/NadekoBot#143]
Just a suggestion/request, the dice roller stuff is nice but the users on my server are wondering if we could confirm the d10 for $roll without arguments (should it have 11 possible outcomes or just 10, we expected 10)

Also it'd be really great if the $nroll could accept an argument to allow you to roll x number of die with variable amounts.

We're kinda working on a few things ourselves but might be useful for others too.

**Comment by Kwoth** [comment]
Sorry but i don't understand what you mean. Could you provide examples?

**Comment by Sairys** [comment]
Sorry

At the moment the $roll function says that it rolls between 0-10 but it actually rolls 0-9, so looks like the help text is a typo

For the $nroll I guess we were wondering if this could happen

User - Today at 10:42 PM
$nroll 100 5
Nadeko - Today at 10:42 PM
@User rolled 47, 37, 74, 2, and 13.
