### ISSUE TITLE
Cannot .award @everyone or @here

### ISSUE THREAD

**Issue by willysunny** [Kwoth/NadekoBot#1430]
Was thinking of giving the whole server a bonus, but it never worked.

**Comment by shivaco** [comment]
.award works only on self-hosted version of Nadeko. Alao, you cannot use it on `@everyone` or `@here`

**Comment by willysunny** [comment]
Yes, I'm aware it only works on self hosted (I'm self hosting as well).

I can easily to .award @role, but not .award @everyone

**Comment by samdivaio** [comment]
Probably because everyone and here don't have ids of thier own? 🤔

**Comment by shikhir-arora** [comment]
It works fine here on the latest version.

`.award 5 @everyone` or `.award 5 roleid` also works -- you can use the role ID for `@everyone` and try, but they both should work. Any console errors?

```
0|Nadeko   | 12:12:20 CommandHandler | Command Executed after 0/0/0.144s
0|Nadeko   | 	User: .vlexɹɐ.#5320 [243902693666455553]
0|Nadeko   | 	Server: JustTest [317157817045745664]
0|Nadeko   | 	Channel: general [317157817045745664]
0|Nadeko   | 	Message: .award 5 @everyone
0|Nadeko   | 12:12:26 CommandHandler | Command Executed after 0/0/0.144s
0|Nadeko   | 	User: .vlexɹɐ.#5320 [243902693666455553]
0|Nadeko   | 	Server: JustTest [317157817045745664]
0|Nadeko   | 	Channel: general [317157817045745664]
0|Nadeko   | 	Message: .award 5 317157817045745664

```

**Comment by ItsFriday** [comment]
![Works](https://itsfriday.s-ul.eu/EhPjcm7T.png)
Works fine

**Comment by ItsFriday** [comment]
+ 338402173459103745 is the id for @everyone

**Comment by shikhir-arora** [comment]
That's the ID on your server. The ID for @everyone is the same as the original `#general` channel. There is one channel on every Discord server that cannot be deleted, whatever it is called/renamed on your server - that channel's ID is the one you want to copy for `@everyone`

**Comment by willysunny** [comment]
Nevermind, guess it works now for some odd reason.
