### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by SillyBirds** [Kwoth/NadekoBot#1431]
I've had this error quite frequently when updating, since I think when youtube-dl got added (no idea if related). Only way to get past it, is to restart the server and try again, otherwise it loops with that error.

Running 16.04 with two different nadekos.

Building NadekoBot
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/1.0.4/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB6006: "/usr/share/dotnet/sdk/1.0.4/Roslyn/RunCsc.sh" exited with code 137. [/home/bakatsuki/NadekoInstall_Temp/NadekoBot/src/NadekoBot/NadekoBot.csproj]

Build FAILED.

/usr/share/dotnet/sdk/1.0.4/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB6006: "/usr/share/dotnet/sdk/1.0.4/Roslyn/RunCsc.sh" exited with code 137. [/home/bakatsuki/NadekoInstall_Temp/NadekoBot/src/NadekoBot/NadekoBot.csproj]
    0 Warning(s)
    1 Error(s)

**Comment by samdivaio** [comment]
Probably some issue with you vps, try checkin https://github.com/dotnet/cli/issues/6175
