### ISSUE TITLE
Unable to get the proper server member count

### ISSUE THREAD

**Issue by Centerten** [Kwoth/NadekoBot#1433]
I am trying to publically display the member count of our server by using the ".addplaying with %users% members" command, but the Bot is not displaying the correct member count, it is off by over 300 members (around 670 instead of around 1010). What could cause the issue? Is there any way to have the Bot properly count all the members?

**Comment by shikhir-arora** [comment]
Not 100% certain, but perhaps that's the online/idle/dnd users?

**Comment by Centerten** [comment]
The Bot is displaying the wrong member count with that command as well, it is the same one as displayed with the %users% command though. Discord still lists a lot more members than the Bot.

**Comment by shikhir-arora** [comment]
Must be the cache then. Have you done a hard restart of the bot, then started it back up? Like almost all libraries (if not all), Discord.NET caches, so perhaps that is it.

**Comment by Centerten** [comment]
I have restarted the Bot, yes. What exactly do you mean by "hard restart"? What do I need to do?

**Comment by ItsFriday** [comment]
I can confirm this happening with large servers.

**Comment by shikhir-arora** [comment]
Editing this line - https://github.com/Kwoth/NadekoBot/blob/1.4/src/NadekoBot/NadekoBot.cs#L75 to `                AlwaysDownloadUsers = true` instead of `false` **_could_** fix it. I don't have the issue of member count, but if you want to try you can do that - however generally not suggested to edit source unless you know what you're doing/comfortable with it.

**Comment by ItsFriday** [comment]
@shikhir-arora pretty sure its turned off so the bot isnt constantly downloading new users for large servers.
If its a small self-host it should be fine.

**Comment by shikhir-arora** [comment]
Yes, you don't generally want to keep that as true, but it may fix his issue. You can always revert it back after as well.

**Comment by Centerten** [comment]
Hm, it looks different for me than in that file, and the only "AlwaysDownloadUsers" I could find was already set to true instead of false, I have attached a screenshot of what I mean.
![code](https://user-images.githubusercontent.com/30350960/28503200-3af5b21c-7002-11e7-9bd0-73aeaaaee22f.PNG)

**Comment by Centerten** [comment]
Nevermind I figured out why it looked so weird for me, I didn't update yet. I updated and tried to change the "AlwaysDownloadUsers" to true, but it didn't fix my issue, the count is still wrong.

**Comment by TUSK3N** [comment]
I also have this problem that it's showing the wrong member count. It was fine just like 5 days ago but now when I start the bot it starts to count like 800 members then 5000 members then 10890 members and stays there when my server in total has 14000 members which Dyno bot is showing correct.
