### ISSUE TITLE
Can't play Youtube songs

### ISSUE THREAD

**Issue by Tschoeppeli** [Kwoth/NadekoBot#1435]
When I write the command ".play https://www.youtube.com/watch?v=aCH1eyWq9B0" (can be any video) the bot replies with "@Tschöppeli No song found."

Here is a picture of the console:

![nadekobot problem](https://user-images.githubusercontent.com/30378867/28495211-c9add0fa-6f46-11e7-965d-23ad0ce83412.PNG)

Thanks for helping!
Cheers, Tschöppeli

**Comment by Deivedux** [comment]
Make sure you have latest versions of your ffmpeg and youtube-dl, there were some new requirements after the 1.53 update:
```
Music requirements for Nadeko v1.53+
Nadeko v1.53+ now requires FFMPEG v3.3+ and youtube-dl to play music.

● On Windows, use the Nadeko Updater to install them, then reboot your PC.
● On Linux/Mac, use option 4 of the Nadeko script to auto-install prerequisites (even if you already did it when installing the bot, do it again to update the packages).

Open a command prompt and type ffmpeg and youtube-dl --version to verify that they're correctly installed. If not, install them manually.
```

**Comment by Tschoeppeli** [comment]
Thanks for the fast reply and the solution! 
I somehow forgot to install youtube-dl. After pressing the button "install youtube-dl" I immediatly pressed "install FFMPEG" and I think because of that he canceld the youtube-dl installation. xD

Now it works, thanks a lot!
