### ISSUE TITLE
YoutubeResolveStrategy | Getting link

### ISSUE THREAD

**Issue by trolhamonas** [Kwoth/NadekoBot#1436]
It's getting stuck in YoutubeResolveStrategy | Getting link for 5 minutes then it adds the song to the playlist and 1 more minute for the bot to join the channel and start playing song

I have FFmpeg and youtube-dl installed (and yes i tried reinstalling both and restarting my computer nothing worked)

**Comment by Kwoth** [comment]
Are you on 1.6

**Comment by trolhamonas** [comment]
Yes

**Comment by Kwoth** [comment]
I'd just say you're box is too slow. Making nadeko work properly seems imposible on free aws tier.
