### ISSUE TITLE
.award command not working properly on self host

### ISSUE THREAD

**Issue by spudts** [Kwoth/NadekoBot#1439]
the .award command works fine on one of my servers but doesnt work on the other. bot the same version of Nadeko. 
![image](https://user-images.githubusercontent.com/30395020/28503861-d32ed5ce-7005-11e7-9b76-2ca83f0dcb84.png) here's a screenshot of the console error

**Comment by spudts** [comment]
update: .give and .take also dont work

**Comment by Kwoth** [comment]
Try restarting the bot. Not a bot issue, your bot's cached data is probably corrupt for some reason.

**Comment by eruzang** [comment]
This is still an issue. I have added my instance, my instance doesn't work on that server, either. Same error. Move to another server, error gone, working well.

**Comment by willysunny** [comment]
@spudts @MaybeGoogle mind add me on Discord and I'll take a look at what's happening?

My Discord ID is Willy_Sunny#1736 (Case Sensitive)

**Comment by Kwoth** [comment]
Seems like a lib issue. Try doing this:

![image](https://user-images.githubusercontent.com/2537696/29649949-e783fe32-8897-11e7-94af-102cd6399825.png)

**Comment by Kwoth** [comment]
tracking in #1535
