### ISSUE TITLE
Music buffering despite having enough resources

### ISSUE THREAD

**Issue by Brramble** [Kwoth/NadekoBot#1443]
OS: Linux Ubuntu 16.04
Speed: 1gbps up and down
Single threaded system which only runs the bot
Nadeko 1.6

I have not been able to get a full answer on this and I am not sure if it is me or NadekoBot. Audio seems to buffer/stutter at random parts of the song on multiple VPSes. I have tried Digital Ocean, Vultr, Linode and OVH. Does the bot suffer due to the system being single thread or is this a problem with dotnet on linux.

I have gone further to make the bot on my own system with 4 threads in a VM and it works perfectly and also I made a single thread windows VM and it started to buffer here and there.

**Comment by Brramble** [comment]
Edit: NeonSpectrum has found a potential fix for this issue on single threaded systems. Testing it now and he will re-post the outcome

**Comment by NeonSpectrum** [comment]
it seems that changing line 71 from the NadekoBot/src/NadekoBot/Modules/Music/Common/SongBuffer.cs to `RedirectStandardError = false,` fixed the music issue for single threaded systems

**Comment by theo546** [comment]
Hi, i still have a big problem even with using this, ffmpeg is using 90% of the cpu, and the music cannot be ear

**Comment by NeonSpectrum** [comment]
@theo546 what's your bot's version?

**Comment by Kwoth** [comment]
#1053
