### ISSUE TITLE
.sfi works until the owner pins it or edits, it deletes -Self Host

### ISSUE THREAD

**Issue by worldofmadness** [Kwoth/NadekoBot#1444]
.sfi works until the owner pins it, it deletes

https://puu.sh/wUI7V/b3a91c9916.png

it deletes the owners message with invite when pined to the channel

same happens if you edit it

**Comment by xnaas** [comment]
![img](https://puu.sh/wUI7V/b3a91c9916.png)

Embedded your image because leaving GitHub is so overrated. 😛
