### ISSUE TITLE
.streamrole doesn't seem to work -  self host

### ISSUE THREAD

**Issue by worldofmadness** [Kwoth/NadekoBot#1446]
have tried using the .streamrole the bot doesn't know what to do with it its not showing in the bot command prompt screen so wondering what happened to it.

**Comment by Kwoth** [comment]
Streamrole definitely works perfectly. 

What's your bot's version? Do you have sufficient permissions?

**Comment by worldofmadness** [comment]
Im now using 1.6 and it works it wouldnt respond to that command in 1.55.7 that i was on.
