### ISSUE TITLE
Change .beam command to .mixer with updated URL to Mixer.com 

### ISSUE THREAD

**Issue by CameronBunch** [Kwoth/NadekoBot#1448]
Beam.pro is no longer correct for the website.  The websites new name is now Mixer.com

The current beam.pro URL works but you will be redirected to https://mixer.com/STREAMER?origin=beam it will lead to the new site but it will have a pop up that tells the origin story of Mixer.com.

To by pass this, if the user types https://mixer.com/STREAMER the origin story pop-up will not happen.

**Comment by Kwoth** [comment]
thanks

**Comment by DeltaC99** [comment]
This would be really good, along with an option to disable notifications for when they go offline.

**Comment by Kwoth** [comment]
Ok fixed.
