### ISSUE TITLE
[Feature Request] Hide old messages from new users in voice+text channels

### ISSUE THREAD

**Issue by T1MOXA** [Kwoth/NadekoBot#1449]
It would be nice if new users didn't see old messages.
.voice+text

Probably just need to add the rule
Read Message History = false

**Comment by Kyousei** [comment]
Or you could edit channel permissions yourself. 🤔

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Kwoth** [comment]
http://feathub.com/Kwoth/NadekoBot
