### ISSUE TITLE
Autoassignrole Problem

### ISSUE THREAD

**Issue by traxim** [Kwoth/NadekoBot#1450]
i activated autoassignrole but it seems it doenst work. Everytime a new user join, he or she is still in the @everyone group. Bot is self host.

**Comment by Kyousei** [comment]
Make sure Nadeko'd role is higher than the role you want her to interact with.

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by traxim** [comment]
How can i do it? in the server settings?

**Comment by Kyousei** [comment]
Ask in Nadeko Log before you post it as an issue.
 


_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shivaco** [comment]
Server Settings -> Roles
![image](https://user-images.githubusercontent.com/22858781/28754987-f6681c36-7572-11e7-8f6c-7c1659e573e2.png)

**Comment by traxim** [comment]
Ok thank you
