### ISSUE TITLE
Jumping ping

### ISSUE THREAD

**Issue by T1MOXA** [Kwoth/NadekoBot#1451]
For some reason, the bot on Linux has strange ping.
If you check through the bot (command .ping) the ping 180 - 5000
But if on a straight line through the machine (ping "my discord server ip") then ~ 1

**Comment by Kwoth** [comment]
if you spam ping, bot will get ratelimited. Your bot doesn't get directly messages from your client, it goes through discord servers. So ping will always be >40

**Comment by T1MOXA** [comment]
The fact is that because of the high ping lag the music

But the ping is high only from the bot, and if you check on the line then everything is OK.
EX -
```
PING russia226.discord.gg (213.196.55.116) 56(84) bytes of data.
64 bytes from 213.196.55.116: icmp_seq=1 ttl=58 time=1.11 ms
64 bytes from 213.196.55.116: icmp_seq=2 ttl=58 time=1.16 ms
64 bytes from 213.196.55.116: icmp_seq=3 ttl=58 time=1.09 ms
64 bytes from 213.196.55.116: icmp_seq=4 ttl=58 time=1.21 ms
64 bytes from 213.196.55.116: icmp_seq=5 ttl=58 time=1.10 ms
64 bytes from 213.196.55.116: icmp_seq=6 ttl=58 time=1.12 ms
64 bytes from 213.196.55.116: icmp_seq=7 ttl=58 time=1.07 ms
64 bytes from 213.196.55.116: icmp_seq=8 ttl=58 time=1.06 ms
64 bytes from 213.196.55.116: icmp_seq=9 ttl=58 time=1.17 ms
64 bytes from 213.196.55.116: icmp_seq=10 ttl=58 time=1.07 ms

```

**Comment by Kwoth** [comment]
select the discord server location closes to your server's location

**Comment by T1MOXA** [comment]
My server in Moscow, and the Discord server has region, Russia
