### ISSUE TITLE
Remove song from queue after playing it

### ISSUE THREAD

**Issue by GMR516** [Kwoth/NadekoBot#1452]
Nadeko should auto-clean that stuff up. Any way to add this? Thanks.

**Comment by Gremagol** [comment]
You could upvote this on FeatHub: http://feathub.com/Kwoth/NadekoBot/+101

**Comment by willysunny** [comment]
![image](https://user-images.githubusercontent.com/5907852/28816403-51266fc8-76d7-11e7-89a7-ecedb3da1534.png)

His words, not mine, now sprinkle him with cash now XDDDD

**Comment by Kwoth** [comment]
That's an option :D 

I said this a few times. I will add most things in time when they're at the top of my priority list. If you want them NOW, or something specific to your bot that you want me to do, you can DM me on discord and we can make a deal.

If not, you can put it on feathub, and if people upvote it, i will add it soon for sure.
