### ISSUE TITLE
.Mute and .chatmute is not working

### ISSUE THREAD

**Issue by MaXKillS** [Kwoth/NadekoBot#1453]
As th title say, these two commands are not working. .Mute is stoping just voice not text and .chatmute does not work at all. Also if i'm not wrong the timer is also not working, for ex .mute 30 x, after 30 min it does not unmute person X. 
Me and another guy(thx for help) from Nadeko help server tried everything but nothing.

**Comment by xnaas** [comment]
Both are working fine for me.

What version of the bot are you running, @MaXKillS?

**Comment by MaXKillS** [comment]
@xnaas i don't know, it does not runs from my computer it is from some online site. That thing with join...

**Comment by xnaas** [comment]
@MaXKillS GitHub is for reporting issues with the self-hosted bot. If you are not hosting the bot and are using the free hosted version, please report the issue in the Discord help server. Most likely @Kwoth was tinkering with something or there's some disconnected shards or something. Anything is possible, but this isn't the place for that. :D

**Comment by MaXKillS** [comment]
@xnaas well a guy from nadeko help server told me to report it here

**Comment by Kyousei** [comment]
I told you it was a Discord issue. Not to come here.

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Kwoth** [comment]
drag nadeko mute role right under nadeko role in your role settings.
