### ISSUE TITLE
Error In Line #

### ISSUE THREAD

**Issue by SecondHoresman** [Kwoth/NadekoBot#1454]
So I Was Setting Up The Credentials And It Kept Crashing And Needing To Close So I Looked At The Log aNd It SAid Error In Line 3 With "ClientId", Please Help, Just Ask What I Need To Send A Screenshot Of And I Can

**Comment by shivaco** [comment]
![image](https://user-images.githubusercontent.com/22858781/28812774-265e2444-76b8-11e7-83c2-662d16f0f7c0.png)
Check your ClientID in credentials.json

**Comment by SecondHoresman** [comment]
i already checked my client id, i'm sure i have the right one, heres a screenshot of the error in the logs ![help](https://user-images.githubusercontent.com/30616879/28813124-c43e240a-764c-11e7-846a-3c292d6c1e40.PNG) i messed with it a bit so i'm pretty sure i fucked it all up, just try to point out what i need to fix and i can do it, please

**Comment by Kwoth** [comment]
Add a comma after the number in credentials.json please refer to the credentials_example.json
