### ISSUE TITLE
.crca Malfunctioning ... in some cases

### ISSUE THREAD

**Issue by willysunny** [Kwoth/NadekoBot#1455]
Since you know a little bit chinese, which makes explaining the following situation much easier.

Custom reaction command
.acr 問題 你查過Google了嗎?

and someone asks in chat
我有問題~ <- will not trigger.

**Comment by Kwoth** [comment]
It simply can't work for chinese. I checked the code.

**Comment by Kwoth** [comment]
Actually i'll leave this open as an enhancement in case someone has an idea of how to do it.

**Comment by Macley-Kun** [comment]
@willysunny is your issued fixed after updating to the above commit's? :-)

**Comment by Macley-Kun** [comment]
@willysunny so i tried you command and indeed it doesn't respond as you written it down here.
But is the .acr correctly formatted? I would say you need an acr that looks like:
`.acr 我有問題 你查過Google了嗎?`

I rougly used translate and i would say this is kinda bit what you look for?

**Comment by Macley-Kun** [comment]
@willysunny Is your issue still present?

**Comment by Kwoth** [comment]
no, as .crca now works anywhere even if it's not a word.
