### ISSUE TITLE
Service hangs every 24hr

### ISSUE THREAD

**Issue by IchBinAsuka** [Kwoth/NadekoBot#1456]
Ubuntu Server 16.04.2LTS
Starting shell script that starts Nadeko with auto restart works upon initial startup, but seems to hang and not restore itself once a day, so I need to screen -wipe and reinitiate the service. Running latest development build, this has been going on for about 2 weeks (and patches to latest every startup because of the script)

Let me know if you need further information, I've been using this box to run Nadeko fine for a while

**Comment by willysunny** [comment]
I'd highly suggest you host it under docker and maintain it that way, as docker is less OS dependent and much easier to deploy.

**Comment by Kwoth** [comment]
I'm hosting around 10 nadekos on ubuntu 16.04 and i haven't seen this issue.

**Comment by IchBinAsuka** [comment]
Ended up finding what was up, my linuxAIO.sh was the old one which didn't manage dependencies (which look like they've since changed.) New launcher looks like it fixes this
