### ISSUE TITLE
Shop functionality not working 

### ISSUE THREAD

**Issue by PhoenixSanctorum** [Kwoth/NadekoBot#1458]
The shop command doesn't update as the page numbers are changed.

**Comment by willysunny** [comment]
What version are you using? and what commands were you using?

I've tried using .shop with the paginated option as well as .shop with page number, both works fine.

**Comment by Kwoth** [comment]
🤦‍♂️ 

All profits from the shop, go to the admin who made it. IF you purchased your own item, you will get 90% back, because nadeko takes 10% (or similar) cut.

**Comment by NeKyou** [comment]
I think shop pages is actually broken. Page 2+ of the shop only displays the contents of page 1 on 1.55. On 1.6 it appears the shop displays nothing if it has over 25 items (uncomfirmed)

**Comment by willysunny** [comment]
Oh, I see what they mean.
![image](https://user-images.githubusercontent.com/5907852/28967074-125d59c4-794c-11e7-963a-f0f0b8e3e104.png) note the underscores
