### ISSUE TITLE
Heroku Support

### ISSUE THREAD

**Issue by SecondHoresman** [Kwoth/NadekoBot#1459]
Does Anyone Know A Way To Run Your Bot API on Heroku?

**Comment by Macley-Kun** [comment]
https://github.com/ScarletKuro/NadekoBot @SecondHoresman here ya go dude. Keep in mind that this Nadeko is on version 1.3 and updates can't come as fast as your used to.

**Comment by Kwoth** [comment]
Please Stop Talking Like This
