### ISSUE TITLE
Weather Bug

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#1460]
Weather is currently not actually reporting the min/max and is instead just saying "0C" for min and max in all locations.

![screenshot](https://i.imgur.com/qFjYy03.png)

And while we're here...put fucking Fahrenheit back in, @Kwoth! 😛

**Comment by DoNotSpamPls** [comment]
The issue seems to be fixed

**Comment by xnaas** [comment]
Rebooted the bot, still an issue for me:

![img](https://i.imgur.com/6wEm5zG.png)

**Comment by SillyBirds** [comment]
I also have this issue. And as he saya, having it display both Celsius and Fahrenheit would be nice too...

**Comment by Kwoth** [comment]
fixed

**Comment by xnaas** [comment]
RIP Fahrenheit, but it's a start. 😜 Can confirm min/max is fixed. 👌
