### ISSUE TITLE
Nadeko is offline

### ISSUE THREAD

**Issue by Leop0ldhub** [Kwoth/NadekoBot#1461]
I was using the bot and it was fine but suddenly it went offline, what happened?

**Comment by shivaco** [comment]
Maybe you closed the command prompt?

**Comment by Leop0ldhub** [comment]
command prompt? I didn't download it from github, i just added the bot from Nadeko's main website

**Comment by LordeJerry** [comment]
It will come back soon.

**Comment by Kyousei** [comment]
Some shards are down iirc 🤔

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by GenesisAria** [comment]
I'm so confused, because mine is offline, but it's not, but it's ignoring commands etc.

**Comment by Kyousei** [comment]
Nadeko was recently restarted.

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
