### ISSUE TITLE
Music not working.

### ISSUE THREAD

**Issue by LordeJerry** [Kwoth/NadekoBot#1462]
The music feature wont work on the bot..

I have had the support team looking at it and its not just me who is having this problem

Please fix this ASAP!

Thank you.

**Comment by xnaas** [comment]
@LordeJerry are you hosting the bot? If you are using the free, public NadekoBot, it does not support playing music.

**Comment by LordeJerry** [comment]
I am hosting the bot, yes.

**Comment by xnaas** [comment]
Bot version? Platform (Windows, docker, etc.)?

**Comment by LordeJerry** [comment]
Look, a staff member has made sure everything is correct its an issue. I'm the 3rd person now.

**Comment by xnaas** [comment]
I mean, music works fine for me with no issues, so... ¯\\\_(ツ)_/¯

**Comment by LordeJerry** [comment]
It could be an issue with the download.

**Comment by xnaas** [comment]
The reason I was asking for details was to see how your setup (not working) differed from mine (working). Whether it's a Discord server location issue, an actual bug on a specific OS, etc. 😛 

Without any details, this issue can't really be solved and might as well be closed. ¯\\\_(ツ)_/¯

**Comment by LordeJerry** [comment]
Would you mind me asking what server your Discord is on?

**Comment by xnaas** [comment]
@LordeJerry, my bot is on two Discord servers (music works on both): **US East** and **US South**. The bot is hosted on a Windows 10 box in Texas.

**Comment by LordeJerry** [comment]
Ok, I changed my location and nothing is still not working. My bot is hosted on Windows 10 in US West

**Comment by xnaas** [comment]
Is the bot seeing the music commands (you can see in the terminal window)? If it is seeing the commands, what happens? Does it error? Does it join voice with no audio?

**Comment by LordeJerry** [comment]
The bot sees the music commands it joins, says its playing then there is no audio.

**Comment by xnaas** [comment]
Hey @LordeJerry, sorry, been an incredibly long day.

Anyway, sounds like you might be missing the [.net core SDK](https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.4-download.md)? I believe I and others have run into a similar issue on WIndows.

If it's not that, I might be thinking of something else.

**Comment by LordeJerry** [comment]
Will have a look. Thanks

**Comment by LordeJerry** [comment]
That fixed it, thanks.
