### ISSUE TITLE
Unstall then Install

### ISSUE THREAD

**Issue by moo1210** [Kwoth/NadekoBot#1464]
When you unstall it then open up the updater to install the update button is black and it says its installed. I click run bot and it says to install it. This is getting really annoying. Can someone help? [This is self-hosting]

**Comment by samdivaio** [comment]
You can fix that by either removing the registry `HKEY_LOCAL_MACHINE\SOFTWARE\NadekoBot`
or
Just download the latest version from [releases](https://github.com/Kwoth/NadekoBot/releases) you can use the updater to update it later.
