### ISSUE TITLE
[Request] Add %username% placeholder

### ISSUE THREAD

**Issue by DeltaC99** [Kwoth/NadekoBot#1465]
As name says. Similar to the %user%, returns the user/nickname without a mention.

**Comment by Kyousei** [comment]
Suggest that at feathub

https://feathub.com/Kwoth/NadekoBot

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Deivedux** [comment]
Feature requests/suggestions go here: http://feathub.com/Kwoth/NadekoBot

**Comment by DeltaC99** [comment]
Thanks :)
