### ISSUE TITLE
Repeat command adds extra emoji at start of message

### ISSUE THREAD

**Issue by InjuredWolf** [Kwoth/NadekoBot#1466]
I have another bot that responds to commands (/purge, etc.), and I was wanting to use Nadeko to run these commands. However, whenever Nadeko posts the commands, they are prefixed by an emote: 
![image](https://user-images.githubusercontent.com/10350531/28953905-c52ac916-791e-11e7-9c03-8ecb84521ce8.png)

Is there a way to disable this? the bot that reads the commands doesn't recognise it when the emote is in the message before the command

**Comment by InjuredWolf** [comment]
Just moving the emoji to the end could work?

**Comment by samdivaio** [comment]
> Is there a way to disable this?
No, but you can edit source if you want to.

> the bot that reads the commands doesn't recognise it when the emote is in the message before the command

Discord ToS bots shouldn't respond to other bots.

**Comment by InjuredWolf** [comment]
Well I can't even test if it will. If I myself type the command as Nadeko does, the other bot doesn't respond. Putting the emoji after the command works fine as my own message

**Comment by InjuredWolf** [comment]
Should be noted that I am not hosting my own version of the bot, but using the publicly hosted one on my server.

**Comment by DogeOps97** [comment]
What samdivaio said. If you still insist on using public Nadeko, you're out of luck then.
