### ISSUE TITLE
hangman game missing feedback

### ISSUE THREAD

**Issue by MisterBored** [Kwoth/NadekoBot#1467]
Solving a hangman game by guessing the whole word ends the game but gives no feedback.
![image](https://user-images.githubusercontent.com/28933326/28990404-21ba641c-794b-11e7-96b3-ea6519edc9ed.png)

**Comment by Kwoth** [comment]
Does it happen every time?

**Comment by MisterBored** [comment]
Yes I can reproduce it 100% of the time

**Comment by MisterBored** [comment]
Also idk if you want a second report for this, but the hangman game does not end unless the term is typed. If you solve the puzzle by guessing all the letters, it will say you win, but won't let another game start. You can just keep guessing letters for the already completed puzzle
![image](https://user-images.githubusercontent.com/28933326/28994915-2d726ba8-79a8-11e7-88cd-6e29851d2eb7.png)

**Comment by Kwoth** [comment]
Fixed in 1.6.3

Publishing the release soon

**Comment by MisterBored** [comment]
This happens if you lose too. The game will not give a Game Ended message unless the term is typed
![image](https://user-images.githubusercontent.com/28933326/28994940-2ed6b3fe-79a9-11e7-9ae9-26eb62e5a787.png)
