### ISSUE TITLE
Nunchi does not work?

### ISSUE THREAD

**Issue by evacfk** [Kwoth/NadekoBot#1468]
Whenever a player says the number, it just kicks them out.
http://evac.gg/i/fcr2r.png

i also tried picking the same number as nadeko because I thought I was misunderstanding the game and same error.

http://evac.gg/i/jzidn.png

**Comment by NeKyou** [comment]
It's bugged rn and known

**Comment by evacfk** [comment]
oh my fault, i didn't realize it was known. I thought the update earlier took care of it.

Thanks kyou <3
