### ISSUE TITLE
@NadekoBot slm needs to PM 5 messages before and 2-3 messages after the actual mention

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#147]
For context, and won't write to chat like she does now

**Comment by xnaas** [comment]
Also: An option to have **all** pings PM'd to you. Some people are never **offline** on Discord and only **online** or **away**. See: Nearly everyone on my server... 😛

**Comment by Kwoth** [comment]
For the original idea: Not possible with the current way of handling it at all. Would need a complete rewrite, and actually nobody asked for it except me.
@xnaas if we didn't implement your suggestion before, make a new ticket and i'll add it
