### ISSUE TITLE
.hangman bug?

### ISSUE THREAD

**Issue by xMochix** [Kwoth/NadekoBot#1471]
Although it seems to be just a minor glitch that doesn't necessarily hinder gameplay, I thought it would be better to point it out.

The hangman game starts out just fine, but even after I have already guessed the word correctly, it still does not end the game or let me start a new game until the man is hung: [https://media.discordapp.net/attachments/315487335557103617/343372276533821450/Screenshot_2017-08-05-08-38-39.png](url)

Also, even if I get the phrase wrong and the man has been hung, it will not state "game over": [https://media.discordapp.net/attachments/315487335557103617/343371565670334474/Screenshot_2017-08-05-08-35-42.png](url)

**Comment by Kwoth** [comment]
this should be fixed in the latest update. Public bot is not updated.
