### ISSUE TITLE
just installed nadeko files and haven't touched them but getting errors 

### ISSUE THREAD

**Issue by Asiphyx** [Kwoth/NadekoBot#1472]
![image](https://user-images.githubusercontent.com/30754207/28996876-f2c6c4e4-79bc-11e7-8c4f-7caeb8f10e1e.png)
not entirely sure how to fix this

**Comment by samdivaio** [comment]
Update your bot, you're on 1.3x

**Comment by samdivaio** [comment]
Update your bot, you're on 1.3x
