### ISSUE TITLE
.crca cropping wrong text

### ISSUE THREAD

**Issue by willysunny** [Kwoth/NadekoBot#1473]
Commands as follows:

```
.acr ++ %target% inv me!
.crca 1
```

when triggered with 

> @Kwoth ++

It'd return:

> !105635576866156544> ++ inv me!

**Comment by Kwoth** [comment]
fixed

**Comment by willysunny** [comment]
problem with the new behavior is that ... it now just removes %target% completely.

With the above example

> @Kwoth ++

Should behave exactly like 

> ++ @Kwoth

But it actually just returns

> ++ inv me!

**Comment by Kwoth** [comment]
no it shouldn't

**Comment by willysunny** [comment]
![image](https://user-images.githubusercontent.com/5907852/29198313-612a9afc-7e75-11e7-8d9f-487d0451f88f.png)
![image](https://user-images.githubusercontent.com/5907852/29198321-797033ec-7e75-11e7-838b-775ca1b8703e.png)
But it is.

**Comment by willysunny** [comment]
And then there's this too
![image](https://user-images.githubusercontent.com/5907852/29198330-9807b3ac-7e75-11e7-8799-8bb337556b0b.png)
