### ISSUE TITLE
Connect4 games often result in wins with boards that should not have been wins.

### ISSUE THREAD

**Issue by QuantumToasted** [Kwoth/NadekoBot#1476]
Often when playing Connect4 (last played on 1.6.1 so not sure if this was fixed already), someone will win when there are no results on the board which could've resulted in a win. We are sure none of these were timeouts (which do display the same message, that *someone* won), as we were going back and forth quickly, normally ~5-10 seconds or so. Here are some examples of games that resulted in a win which shouldn't have been:
![image](https://user-images.githubusercontent.com/30324210/29005025-3aabf1f4-7a98-11e7-8ad6-e7f0a1c184ca.png)
![image](https://user-images.githubusercontent.com/30324210/29005029-46368f52-7a98-11e7-8f71-202015d2972c.png)
![image](https://user-images.githubusercontent.com/30324210/29005042-9f0ccbe6-7a98-11e7-80ed-cbc659f0fb68.png)

**Comment by Kwoth** [comment]
Yes it was fixed. Due to a bug ✔️ -like shapes of 4 also resulted in a win.

**Comment by Kwoth** [comment]
(it's not updated on public nadeko, it will be fixed tonight after she gets patched)
