### ISSUE TITLE
QUESTION: Host Nadeko on Ubuntu Server 16.04?

### ISSUE THREAD

**Issue by GMR516** [Kwoth/NadekoBot#1477]
How do I install the dependencies that it needs? After trying both mono and dotnet core I cannot get it to work. I published it first with all .dlls, but it doesn't run. I'm attempting to use a Raspberry Pi 3

**Comment by Kyousei** [comment]
Why didn't you ask in __#NadekoLog__?
GitHub is to report issues with Nadeko, not for questions like this 😄

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by GMR516** [comment]
I tried a few times,, but couldn't get an answer. I'll try again! :)

**Comment by samdivaio** [comment]
you need 64bit linux os for latest .net core sdk

**Comment by GMR516** [comment]
Can I install ubuntu 16.04 64 bit on a Pi 3? Everyone online was saying you couldn't/not to, since they built a ubuntu version specifically for the Pi. However, that version was 32bit.

**Comment by samdivaio** [comment]
> Can I install ubuntu 16.04 64 bit on a Pi 3? Everyone online was saying you couldn't/not to, since they built a ubuntu version specifically for the Pi. However, that version was 32bit.

Not currently, but soon after arm support added and officially released for .net core sdk.

**Comment by Macley-Kun** [comment]
@GMR516 perhapes your answer is in here: https://github.com/Kwoth/NadekoBot/issues/1203
You can then just run Nadeko fine on your Pi 3. Think we can close this~

**Comment by Macley-Kun** [comment]
@GMR516 you tried following that link? Otherwise we can close this issue. It's already solved in my eyes.
