### ISSUE TITLE
Bot is only saying messages in the main server and in other servers not saying anything at all. Why it is doing that?

### ISSUE THREAD

**Issue by moo1210** [Kwoth/NadekoBot#1478]
Bot is only saying messages in the main server and in other servers not saying anything at all. Why it is doing that?

**Comment by shivaco** [comment]
Check the prefix (`.prefix`), maybe it was changed. Or server admins used `.asm disable` to disable a commands for everyone

**Comment by moo1210** [comment]
I owned both of the servers. But I did not change the prefix. As this is self-hosting is there any fixes for that?

**Comment by moo1210** [comment]
Not a thing was posted in NadekoBot.exe

**Comment by samdivaio** [comment]
Check Nadekobot.db > "guild config" table with those servers ids. Look for prefix there.

**Comment by Kwoth** [comment]
@samdivaio `.prefix` is now made to work even if you changed your prefix to something else.

**Comment by moo1210** [comment]
Said .prefix did not work. My guild was not in guild config. Added it to that. Just made the bot crash on startup. Removed it. Started up fine. :|

**Comment by willysunny** [comment]
@moo1210 Your question seems more like a support question on #help, I'd highly recommend you ask there first, before posting here.

**Comment by moo1210** [comment]
Yea no one replys it gets too spamed up.

**Comment by Macley-Kun** [comment]
@moo1210 try giving the bot full permission (checking everything is enabeld). Also have a bit patience with the #help. The people their do it already for free and in their free time. If they don't have time better try it later.

Or pay Kwoth on patreon so he can give you support instantly when needed (ofc within reason).

**Comment by Macley-Kun** [comment]
@moo1210 can you close the ticket please?

**Comment by Kwoth** [comment]
closing as there have been no updates on this for weeks
