### ISSUE TITLE
Warframe integration

### ISSUE THREAD

**Issue by hemipatu** [Kwoth/NadekoBot#1479]
Is it possible to have Warframe integration into the bot, providing us with pretty embeds when world events happen, things like; Sorties, Server resets, Alerts and the rewards that come with it etc.

It would also be awesome if there was the possibility of having a per-person thing where people can use a command to track certain things of value to them and if said item comes up they will receive a PM.

Thanks, kind regards.

**Comment by Kyousei** [comment]
For future reference, suggest new features at __https://feathub.com/Kwoth/NadekoBot__

This __isn't__ an issue so 😄

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
