### ISSUE TITLE
Adding new api to the bot from mashape?

### ISSUE THREAD

**Issue by Wingzzzzy** [Kwoth/NadekoBot#1480]
Hello i have bean trying to find a way that i can put new api's in to the bot but i cant find it i want to know if it is possible to add a new api from mashape that make everything to sound like yoda is typing https://market.mashape.com/ismaelc/yoda-speak if there's any way i would be happy to hear.

**Comment by Kwoth** [comment]
there already exists .yodify command. 

If you want to add your own apis, you have to learn to program in C#
