### ISSUE TITLE
I changed the prefix to "-h" and i can't use any commands or return for "."

### ISSUE THREAD

**Issue by zerinho6** [Kwoth/NadekoBot#1481]
I just used the ".setprefix -h" and then any command works, no mather if i'm using "." or "-h" and if i try change for "." she says the prefix have changed to "." (".setprefix ." don't work)

**Comment by Kyousei** [comment]
You don't set prefix with `.setprefix` tho.
You'd have to do `.prefix -`.

For future reference, ask in __#NadekoLog__ before posting it in GitHub. 😄

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
