### ISSUE TITLE
%target% usage within a url

### ISSUE THREAD

**Issue by DDDDDDanny** [Kwoth/NadekoBot#1483]
Hello,

If I use %target% within a url it is inserting a space before it, resulting in an invalid url. I know the bot used to do this and it was fixed. I'm just wondering if this is now intentional or if it'll be fixed again?

Here is what I'm using

.acr !stats http://www.statswebsite.com/%target%

!stats username

Result: http://www.statswebsite.com/ %target% 

Thanks
Danny

**Comment by willysunny** [comment]
I guess a workaround for now is just remove the http:// and parse the link and ask the user to copy-paste it to their browser
