### ISSUE TITLE
Misspell in .ud #1

### ISSUE THREAD

**Issue by KittenKatja** [Kwoth/NadekoBot#1485]
In '.ud trawling' is the word "availible".
-I still don't know what trawl means-

**Comment by Kyousei** [comment]
`.ud` is using an Mashape API. So the person who wrote about the word misspelled it, not Kwoth.

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by KittenKatja** [comment]
so i made a github acc for nothing?

**Comment by Kyousei** [comment]
Pretty much. 

__Close__ the issue please 😄

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by KittenKatja** [comment]
Good that i looked into this before posting my second thing...
