### ISSUE TITLE
High cpu/ram usage when loading up playlist

### ISSUE THREAD

**Issue by willysunny** [Kwoth/NadekoBot#1486]
Whenever trying to .load a play list, the CPU usage and ram would increase dramatically, and will not drop until it has fully resolved all the links.

**Comment by willysunny** [comment]
just for a reference, when I was trying to load a playlist of 177 songs, the ram spiked up to over 2g, and dropped back down to 300 mb once the links has been resolved.

**Comment by Kwoth** [comment]
If true, that would be very interesting, I'll take a look a bit later

**Comment by Kwoth** [comment]
Can't reproduce. Created a playlist of 50 songs, saved, restarted, loaded, memory usage stayed consistent. 

Cpu spike is normal because it's resolving all those songs.

**Comment by Macley-Kun** [comment]
I do noticed this as well with Nadeko on ubuntu 16.04. But that's like a month or 2-3 ago. Can you still reproduce it @willysunny? Maybe you can record it so Kwoth can have a better look at it.

**Comment by shikhir-arora** [comment]
2GB is a lot to spike, but it is normal. Loading large playlists is usually pretty computationally intense compared to any other part of the player with Google/ or youtube-dl.
