### ISSUE TITLE
customreactions_redacted_too_long key is missing from zh-TW response strings.

### ISSUE THREAD

**Issue by willysunny** [Kwoth/NadekoBot#1487]
As title said ;)

Happened when I tried to remove a custom reaction with a very long response.

**Comment by shivaco** [comment]
Looks like this isn't translated yet

**Comment by willysunny** [comment]
or he forgot to put that in the translation table :p

**Comment by Kwoth** [comment]
No need to add missing keys in languages other than english. Missing Keys just mean it either is not translated, or not added to the translations yet. If english key is missing, or if foreign key is not formatted properly, then you should report it.

**Comment by willysunny** [comment]
But ... your console log said to report it anyways XDDD
