### ISSUE TITLE
vcrole stops removing the role

### ISSUE THREAD

**Issue by anigatari** [Kwoth/NadekoBot#1489]
This happens after a certain amount of time after .vcrole is enabled. The vcrole will still grant the set role whenever a user joins a voice channel, but it'll stop removing the set role when the user leaves.

It will work for the first few minutes (or hours) after enabling it. Unfortunately, I can't seem to find a way to trigger the bug immediately - it just happens.

I am running a source-edited, self-hosted 1.4. I also tried this with the latest version and the issue persists.

EDIT: it also refuses to remove the role when the user is placed in an afk channel.

**Comment by coggy9** [comment]
I can also confirm this on a self hosted build on Ubuntu 16.04.2 x64. Time seems to vary, anywhere from 4 hours to days. The only fix is to restart NadekoBot. Nothing appears in the console about it or any other errors.

**Comment by Kwoth** [comment]
This may happen when your bot disconnects for a minute, fails to add role and assumes it doesn't have sufficient permissions, then disables the feature. I will take a look

**Comment by Macley-Kun** [comment]
So hows this issue doing? Is it already fixed?

**Comment by Macley-Kun** [comment]
@anigatari @coggy9 you guys still having this issue? Or has this been fixed?

**Comment by ToshiroTofuKing** [comment]
Still having the issue on both 1.4 and 1.8.4, only option is to restart the bot

**Comment by Myned** [comment]
I run a self-hosted, non-source-edited 1.8.4 on Windows 10 (but this has been a problem in past revisions).
I want to use the vcroles as a cleaner v+t function, with the same permissions as v+t, but am using v+t until this issue is fixed.
---
The vcrole function seems to add the role, but not remove it from the user when joining/leaving a voice channel (needs more testing).

The v+t function (with automatic channel and role generation) works as expected. Only the vcrole function stops working after a while. I cannot seem to locate the exact trigger for it to stop working.

**Comment by Kwoth** [comment]
Extremely weird. Just happened to me too, and simply using `.vcrole` then `.vcrole rolename` again fixes it. I will investigate it tomorrow

**Comment by Kwoth** [comment]
This is possibly fixed. Please update your bots and tell me if it's stil happening.

**Comment by anigatari** [comment]
Still working after 24 hours!

**Comment by Kwoth** [comment]
Wait for 2 more days then close the issue if it works :^)

**Comment by anigatari** [comment]
Still working after around 3 days. Closing this now.

**Comment by anigatari** [comment]
I have to reopen because I found a new problem.

If there are two voice channels that are configured to give the same role, switching from one channel to the other fails to retain the existing vcrole.

**Take this for example:**

Chatroom 1
Chatroom 2

- Both are configured to have a vcrole of `chatroom`. 
- Joining either channel will give you the `chatroom` role. 
- Switching to the other channel _removes_ the `chatroom` role from you.
- Switching back to the initial channel will give you back the `chatroom` role.

This is tested from the public bot.

**Comment by Macley-Kun** [comment]
Tested this out on NadekoBot v2.10.1. Still present.

**Comment by Kwoth** [comment]
Make a new issue,
