### ISSUE TITLE
First Song Plays fine next queued songs sounds robotic or trying to buffer.

### ISSUE THREAD

**Issue by njinco** [Kwoth/NadekoBot#1490]
whether its after the first song or a playlist. as long as the bot finishes the 1st song second songs have problems. which i have to do is join and unjoin the bot from the voice channel. ubuntu 17.04

**Comment by samdivaio** [comment]
Only happens with Discord web and Discord android app. Issue is related to Discord. There is an unofficial patch to counter that but I am unsure if it's updated.

**Comment by willysunny** [comment]
@samdivaio Would love to know what's the workaround patch to fix that issue XD

**Comment by samdivaio** [comment]
> @samdivaio Would love to know what's the workaround patch to fix that issue XD

[NadekoBot-Extensions](https://github.com/samdivaio/NadekoBot-Extensions/)

**Comment by willysunny** [comment]
hm, I recall 1.3 the bot will auto-rejoin upon every play back, not sure why it was removed =\

**Comment by xnaas** [comment]
@willysunny because that shit was obnoxious. 😉

**Comment by Macley-Kun** [comment]
Still relevant? or closing this?

**Comment by Macley-Kun** [comment]
@njinco assuming this is a month old. You updated nadeko and tried again with a song? You can use this one for example: https://www.youtube.com/watch?v=dQw4w9WgXcQ

You can close this ticket if you aren't experiencing it anymore.

**Comment by njinco** [comment]
its still the same. i think i just updated last week. unless there is a new update now i'll do it but basically first one plays fine. the next one queued would always sound robotic or static unless i disconnect the bot from voice and rejoin and play a new one. and if i dont and let the robotic music finish. third input of the command on  queue would always give this message.
https://ibb.co/n9pkJa

**Comment by samdivaio** [comment]
@njinco are you using a web browser?

**Comment by njinco** [comment]
@samdivaio either web or mobile still the same

**Comment by samdivaio** [comment]
Use the Nadeko Extension link from my previous comments and patch it, its related to discord and only happens with web and android discord app.

**Comment by njinco** [comment]
just seeing the description and behavior of the bot . i know this would fix it. cause thats what im doing manually XD . Thanks @samdivaio . closing my issue.
