### ISSUE TITLE
Can't Run on Debian 9

### ISSUE THREAD

**Issue by TheBeverage** [Kwoth/NadekoBot#1491]
Hi, since updating to Debian Stretch from Jessie, I have been unable to get Nadeko to run. Initially it seemed to be related to a dotnet issue, but restoring the libcurl3 version from Jessie's repository seemed to fix that. Unfortunately I'm now absolutely stumped on this error. I have no idea how to alter ImageSharp, or even what it is. Unfortunately the window has taken to crashing whenever I highlight the text, so this screenshot will have to suffice.
![screenshot_from_2017-08-11_02-21-47](https://user-images.githubusercontent.com/13399680/29203559-caf7f35c-7e3f-11e7-8f78-c5c5e5da0d5f.png)

Any help is greatly appreciated.

**Comment by ScarletKuro** [comment]
Is that 1.3 version Nadeko?

**Comment by Kwoth** [comment]
Yea, you just have to update.

**Comment by TheBeverage** [comment]
Does the launcher not update it to the latest version anymore? I had it download the latest stable version multiple times. And if not, how can I transfer to this newer version without losing my settings, custom commands, etc.? Thanks in advance.

**Comment by TheBeverage** [comment]
Okay I can confirm that re-downloading it works fine. I'll just have to re-create all my custom reactions and what not. Thanks!

**Comment by Kwoth** [comment]
just copy the data/NadekoBot.db over

**Comment by TheBeverage** [comment]
Great, thanks!
