### ISSUE TITLE
Mute length option from Antispam

### ISSUE THREAD

**Issue by WattieX** [Kwoth/NadekoBot#1493]
Hello I was wondering if there was , or if you could add an option to choose the length of someone that gets muted by the antispam. Currently someone was to get muted from
Antispam, we will have to manually unmute them. 

Also the antispam currently will still punish those who have sent the same msg even if it was spaced out for 10 min . Is there a way to change this where they would only punished when they send the same msg in a certain time frame to have a punishment ? 

Thanks for your time .

**Comment by Kyousei** [comment]
This Isn't an issue tho 🤔

Why don't you ask in __#NadekoLog__ first before posting it as an issue?

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Kwoth** [comment]
It's not possible, but it's one of the top suggestions on feathub. It will get added sometime soon.
