### ISSUE TITLE
Nadeko Bot will not reinstall.

### ISSUE THREAD

**Issue by SoMatah** [Kwoth/NadekoBot#1494]
I recently uninstalled Nadeko bot and wanted to create a new one for a fresh new start for my server. I uninstalled the bot from both my control panel and removed the folder it was contained in then restarted my PC. But now when I reinstalled the setup.exe and ran the Nadeko updater/installer, it says I have the latest version of the bot but its not installed anywhere. I clicked the launch button hoping it would do something but it tells me to install Nadeko. PLEASE HELP MEH. It also told me to chill out, how long will that be?

**Comment by samdivaio** [comment]
Install from [releases](https://github.com/Kwoth/NadekoBot/releases)

**Comment by SoMatah** [comment]
Thanks it worked!

**Comment by xnaas** [comment]
@SoMatah you should close this if it's sorted out. 😉
