### ISSUE TITLE
games_picked error

### ISSUE THREAD

**Issue by Deksastara** [Kwoth/NadekoBot#1495]
when I pick I get this error
"I can't tell you if the command is executed, because there was an error printing out the response. Key 'games_picked' is not properly formatted. Please report this."

**Comment by Kwoth** [comment]
What language are you using?

**Comment by Deksastara** [comment]
english lol

**Comment by Deksastara** [comment]
ResponseStrings-es-ES.json looks like it's supposed to look

**Comment by Kwoth** [comment]
print screen the error please

**Comment by Deksastara** [comment]
My friend removed the bot from the server and I tried it in a different one. It's working perfectly fine so I don't care anymore. Thanks anyway.
