### ISSUE TITLE
creating a custom currency ^^;

### ISSUE THREAD

**Issue by ChiiTachii** [Kwoth/NadekoBot#1496]
I'm pretty new to this and I want to know how to change the currency to my own ^^;
Just started hosting the bot on my own computer today ;')

**Comment by Kyousei** [comment]
This Isn't an issue.
For future reference, Ask in __#NadekoLog__ before posting it on GitHub.


_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shivaco** [comment]
https://gfycat.com/CommonAssuredCarp

**Comment by Kwoth** [comment]
Just use `.bce` to edit bot config instead of going into the database.

**Comment by andruxo** [comment]
is there is any way to change crown picture? (comand,code or anything else)? i try to ask on support and they say they cant help me :(
