### ISSUE TITLE
Pokemon moves with spaces in their names aren't working.

### ISSUE THREAD

**Issue by ShanaGartrex** [Kwoth/NadekoBot#1497]
The moves for pokemon battles that have spaces wont register as a move for Nadeko, therefore wont use the attack. Is this a bug or problem with the naming?

**Comment by samdivaio** [comment]
try `.h .attack`

**Comment by shivaco** [comment]
Use quotation marks for moves

**Comment by ShanaGartrex** [comment]
The quotation marks work. Thank you!
