### ISSUE TITLE
Multipliers..?

### ISSUE THREAD

**Issue by ChiiTachii** [Kwoth/NadekoBot#1498]
Is there any way to change the multipliers in the .br or bet roll as I think the current multipliers are *2 *4 and *10...

(hopefully this is suitable for github don't kill me kyousei ^^;)

**Comment by xnaas** [comment]
@ChiiTachii, if you're hosting the bot, you can edit the database to adjust those multipliers.

![example](https://i.imgur.com/veRsRvb.png)

**Comment by xnaas** [comment]
On that note, @Kwoth, should those values be added to being able to be modified by `.bce`?

![missing](http://i.imgur.com/L3CreOs.png)
