### ISSUE TITLE
Bot can't give roles.

### ISSUE THREAD

**Issue by Deksastara** [Kwoth/NadekoBot#1499]
![error](https://user-images.githubusercontent.com/30935997/29244833-cec64864-7f91-11e7-9e06-5447efe3dd06.png)
It won't give the role.

**Comment by Kyousei** [comment]
Does Nadeko have __Manage Roles__ permission? 🤔

(Also for future reference, please ask in ___#NadekoLog___)

**Comment by Deksastara** [comment]
Yes.

**Comment by Kyousei** [comment]
Is Nadeko's role higher than the role you want her to give?

**Comment by Deksastara** [comment]
No, I'll see if that fixes it.

**Comment by Deivedux** [comment]
The only valid options are:
* Nadeko needs either `Admin` or `Manage Roles` permission.
* Nadeko has to be higher than that role in a role hierarchy.

**Comment by Deksastara** [comment]
Moving the nadeko role to the top fixed the issue, thanks.
