### ISSUE TITLE
.ve shows errors even when modules are disabled globally.

### ISSUE THREAD

**Issue by Gremagol** [Kwoth/NadekoBot#1501]
Some people using my bot on their server were confused when this happened.
I disabled the music module to prevent the ram leaking (and nobody used her music module anyways lol)
I recorded this to show what I mean:

https://gfycat.com/CandidFarEasteuropeanshepherd

I dont know if it's supposed to be like this, but its pretty confusing.

**Comment by willysunny** [comment]
Can verify,

Once you enter the command in correct form, THEN a message will pop up telling you that it's being disabled.

I think the more logical way is to check if the module is disabled first, before checking if the commands are formatted correctly or not.

**Comment by Macley-Kun** [comment]
Maybe as a temporarly solution. You could use .ve, you don't see the errors then.

**Comment by Gremagol** [comment]
I know that. But when my bot is on 26 servers, its a bit difficult for me when they enabled it. I dont really want to change it in the database file.

**Comment by Macley-Kun** [comment]
Mhm, well i don't rlly have anything else to help you with. Kwoth marked it as bug and it will take some time to find that bug. For now i guess the only thing you can do is ignore it. Sorry ;(

**Comment by Kwoth** [comment]
There is no way to really fix this cleanly, i'll just leave it as it is.
