### ISSUE TITLE
.sad notification mispell

### ISSUE THREAD

**Issue by willysunny** [Kwoth/NadekoBot#1505]
Please refer to comments in https://github.com/Kwoth/NadekoBot/commit/fe3770270e96015ff47595034c4ba1d5bd692cfb

**Comment by Brramble** [comment]
Yeah I wondered these are the wrong way around.
+  "music_sad_disabled": "Songs will be deleted from the music queue when they finish playing.",
+  "music_sad_enabled": "Songs will no longer be deleted from the music queue when they finish playing.",

**Comment by Kwoth** [comment]
i fixed this
