### ISSUE TITLE
Can't figure out .gencurrency

### ISSUE THREAD

**Issue by Nidoking48** [Kwoth/NadekoBot#1506]
A friend and myself can't figure out how to start the .gencurrency command for NadekoBot. Could we have some assistance with this?

**Comment by Nidoking48** [comment]
Is it just a command that doesn't have an activation message or are we doing something wrong :/

**Comment by Kyousei** [comment]
`.gc` is disabled on Public Nadeko.
You need to self host to generate currency.

**Comment by Nidoking48** [comment]
Ok thanks
