### ISSUE TITLE
%user% doesn't work without a `.` after it.

### ISSUE THREAD

**Issue by hiff** [Kwoth/NadekoBot#1508]
For the .acr command, when you type %user% the bot responds with %user$ instead:

<img width="406" alt="screen shot 2017-08-17 at 4 17 09 pm" src="https://user-images.githubusercontent.com/30630506/29402486-ac17d0b0-8367-11e7-98ee-68de3b0c8dd1.png">

Once you type %user%. then it works as intended:

<img width="407" alt="screen shot 2017-08-17 at 4 17 19 pm" src="https://user-images.githubusercontent.com/30630506/29402495-b97a403a-8367-11e7-9fa9-90d65ad6e9b7.png">

**Comment by willysunny** [comment]
![image](https://user-images.githubusercontent.com/5907852/29402806-e56ce6b0-8368-11e7-9f0e-eda0f85c64f6.png)
Cannot reproduce on 1.7

**Comment by Kwoth** [comment]
Delete your old custom reaction before creating a new one with the same trigger.
