### ISSUE TITLE
.lcr pagination starts scrambling up after loading a few pages

### ISSUE THREAD

**Issue by willysunny** [Kwoth/NadekoBot#1509]
![test](https://user-images.githubusercontent.com/5907852/29404214-0d3ddfa6-836d-11e7-8aa5-e99e70f8c870.gif)

Since you refuse to take a look on the DM and recognize it as a bug, then I'll have to officially open it as a bug for you to see it then :p

Reproducing steps:
1. enter .lcr
2. keep going next page
3. ???
4. profit.

**Comment by Kwoth** [comment]
Did you try it yourself on your own server?

**Comment by willysunny** [comment]
My server does not have as much custom reaction as your public one does XD

**Comment by willysunny** [comment]
somewhat, as I only got 3 pages of custom reaction.

The more custom reaction the more obvious this would occur.

**Comment by Kwoth** [comment]
Try creating many pages of custom reactions on your server and test it. Pretty sure they just created those weird custom reactions themselves.
