### ISSUE TITLE
Trivia game continues forever

### ISSUE THREAD

**Issue by ryry013** [Kwoth/NadekoBot#1510]
If left unattended, a trivia game started by Nadeko will continue for at least 70 minutes with no players, which is how long ours continued until a user asked for help, and we used .tq

Not a big deal, but it takes up a tiny bit of processing power on the server side unnecessarily.  You could impose a limit, if no one offers any answers for five questions consecutively, quit the trivia game.

**Comment by willysunny** [comment]
feat hub?

**Comment by ryry013** [comment]
Something is submitted to feat hub now.  It seemed like a bug because I remember this autostopping before, but I could be mistaken.

**Comment by Kwoth** [comment]
it's not a bug, add the suggestion to feathub.
