### ISSUE TITLE
[Feature Request] .autoboobs

### ISSUE THREAD

**Issue by halitalf** [Kwoth/NadekoBot#1511]
I would like to see a .autoboobs command, like the .autohentai command.

**Comment by halitalf** [comment]
Why the close without comment?

**Comment by halitalf** [comment]
Love the thumbs down... Just wanted to know why it got closed without a reason. I mean, I understand that auto-closing means it's not happening, but it would be nice if I could get a _why_.

**Comment by xnaas** [comment]
Since you really don't seem to get it @halitalf, all feature requests go here (and have for some time): http://feathub.com/Kwoth/NadekoBot

@Kwoth should probably add that to the main readme file so it's a nice, giant link when people open the repo.

**Comment by halitalf** [comment]
Ah, OK. I was not aware of that. Thank you. I just did what the FAQ said to do:
![FAQ Question #5](https://image.prntscr.com/image/AT0zjpd7TiWSH3RDblEXVg.png)
