### ISSUE TITLE
Number 3 and 7 are larger than they're supposed to be on slots

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#1514]
As title says
![Image of Yaktocat](https://cdn.discordapp.com/attachments/272616211010027521/347904428336087040/result.png)

**Comment by Tremmert9** [comment]
You can edit the number images yourself in any photo-editing software, if those numbers bother you that much - going by the assumption that you host the bot.

**Comment by Midoriin** [comment]
With that perspective, you can also go ahead and fix the bugs yourself. It's for Kwoth and everyone's sake.

**Comment by Macley-Kun** [comment]
Who made the slot art? Maybe we can ping that guy?

**Comment by Kwoth** [comment]
just fixed
