### ISSUE TITLE
I cannot get flowers.

### ISSUE THREAD

**Issue by TheDarkestHour1504** [Kwoth/NadekoBot#1516]
I tried several times, but it doesn't work. Nothing happens,

**Comment by Deivedux** [comment]
`.gc`, `.award` and `.startevent` are bot owner-only commands, so they don't work on public Nadeko.

Bot owner is NOT the same as server owner. Bot owner is a user who is running a NadekoInstaller on their own PC.

● To learn how to host the bot and use bot owner-only commands, read hosting guides by typing `.guide`

**Comment by TheDarkestHour1504** [comment]
ok. Thank you.
