### ISSUE TITLE
rategirl command has a typo in no-go zone message

### ISSUE THREAD

**Issue by numbermaniac** [Kwoth/NadekoBot#1517]
![screen shot 2017-08-20 at 22 36 12](https://user-images.githubusercontent.com/5206120/29494941-296fc436-85f8-11e7-9c29-c15877fea9ea.png)

"at least" is supposed to be two words, not one, as it is in that message. :)

**Comment by alistairmackenzie** [comment]
@numbermaniac @Kwoth Perhaps we can close this now?
