### ISSUE TITLE
Can`t host the Bot because of the OwnerID

### ISSUE THREAD

**Issue by leuchthelp** [Kwoth/NadekoBot#1518]
I tried to host the bot but everytime i run the bot i get this message (SelfService | No owner channels created! Make sure you've specified correct OwnerId in the credentials.json file.) and I don`t know why.
I filled everthing in correctly in the credientials.json file.
Could you pls help me ?

**Comment by shivaco** [comment]
Have you invited your bot to a server with you in it?

**Comment by leuchthelp** [comment]
everything is set up correctly

**Comment by leuchthelp** [comment]
and i was on when i launched it

**Comment by Deivedux** [comment]
Being online isn't the case, you literally have to invite the bot to the discord server where you are currently in, and then run the bot.

**Comment by Macley-Kun** [comment]
@leuchthelp can you show us your credentials.json. But do blur out your bot token and api keys.
Also could you directly copy paste your userid? Example: 238870889084884885 (about 18 numbers longer). Otherwise we'll close this issue. :)

**Comment by Macley-Kun** [comment]
@leuchthelp update or can we close this?

**Comment by leuchthelp** [comment]
You can close it.

**Comment by Kyousei** [comment]
You can close it yourself
