### ISSUE TITLE
1.7 - Can't host two bots simultaneously on one machine

### ISSUE THREAD

**Issue by Tremmert9** [Kwoth/NadekoBot#1519]
As the title says, I cannot get two bots on one machine to work at the same time.
I'll use a picture to describe it better:
![Nadekobot problem](http://i.imgur.com/8UFWgjg.jpg)

The bot on the left works as it's supposed to - 3 bot owners, reads the correct database.
However, the bot on the left is reading credentials from the .json file of the left bot, and I assume does the same with the database, despite being set otherwise. It's supposed to have 2 bot owners, but has 3 instead. When doing syntax commands in the first server, it outputs the responses twice - meaning I am running two same bots, despite having 2 different sets of credentials and databases set up. How do I fix this issue?

I ran 1.3b without an issue: two Nadekobots on one machine, haven't had an issue. I decided to update to 1.7 today and ran into these problems.

As added troubleshooting - I used the setup installer to install the first bot, however I couldn't use the same installer to install the second bot, due to the registry files being written (I assume), so the installer didn't ask for a setup location. That's why I copy-pasted the first bot into a new directory and edited the proper credentials, even shortcut locations, but the problem still persists. I am 100% sure that's why the problem happens, I am just unsure what else to edit to fix the problem.

**Comment by willysunny** [comment]
First step debug check - did you run nadekobot.exe in the respective folders? or are you running via the links in the nadekobot folder?

**Comment by Tremmert9** [comment]
@willysunny I was about to screenshot the shortcuts, then I noticed that I missed one line in the shortcuts - "Start In". I haven't changed that path before. I did now and it seems to be working as it should now. Can't believe I've missed that one.
Thanks!
