### ISSUE TITLE
Request: Bring back Pokemon Trivia game

### ISSUE THREAD

**Issue by shadowfox87** [Kwoth/NadekoBot#1520]
Hi,

I've been using Nadeko for a long time, more than a year. It once had a Pokemon trivia game where it shows a shadow of a Pokemon and you have to guess the name. Similar to hangman and you'd get 30 secs to name the Pokemon. This game was extremely fun. Please bring it back. I'm not sure why it was removed.

**Comment by Kwoth** [comment]
`.t pokemon`
