### ISSUE TITLE
Strange behaviour in trivia with long answers

### ISSUE THREAD

**Issue by numbermaniac** [Kwoth/NadekoBot#1522]
When the answer to certain questions is fairly long, the bot cuts off the answer:

![screen shot 2017-08-20 at 16 53 49](https://user-images.githubusercontent.com/5206120/29500301-e10e179a-8662-11e7-9a1f-171fc11bbb7b.png)

And for whatever reason, it sometimes leads to incredibly weird capitalisation situations like this:

![screen shot 2017-08-20 at 22 42 08](https://user-images.githubusercontent.com/5206120/29501836-d4d343cc-866e-11e7-9f4d-0c949752dc5a.png)

**Comment by Kwoth** [comment]
Please try it again and it should work properly, if it does, close the issue.

**Comment by Macley-Kun** [comment]
@numbermaniac yo dude you still having the issue after updating NadekoBot? Otherwise you can close the issue 0/

**Comment by numbermaniac** [comment]
Well, it looks like it's working :) If anything does still go wrong I'll open an issue here, but it looks good so far. Thanks!
