### ISSUE TITLE
NSFW images with blacklisted tags still appear in searches.

### ISSUE THREAD

**Issue by coggy9** [Kwoth/NadekoBot#1523]
When server members use the e621 command, it will ignore the blacklist when picking an image. The blacklist is only enforced when a user includes a blacklisted tag.

For example, when someone does `.e621 cheese_grater` and the "gore" tag is in the` .nsfwtbl` blacklist, images with the "gore" tag still occasionally show up. If the user does `.e621 cheese_grater gore`, Nadeko will [tell the user a tag is blacklisted](http://i.imgur.com/Qu5luiG.png). This happens on Windows 10 Pro x64 and Ubuntu 16.04.2 x64.

I do not recommend looking up that tag except for debugging purposes. It's a small set of images where the issue can be easily reproduced.

**Comment by Kwoth** [comment]
Can you test it and tell me if it works?

**Comment by coggy9** [comment]
It appears to be fixed. Thanks!
