### ISSUE TITLE
.prefix is broken

### ISSUE THREAD

**Issue by froidlesprit** [Kwoth/NadekoBot#1524]
![image](https://user-images.githubusercontent.com/18752458/29547589-d4a25636-86af-11e7-9cd9-0c0c640647bc.png)
I am having a difficult time setting the server prefix to "r!", to be consistent with our other bots, which use "t!", "d!", and "p!". I'm self-hosting, and this happens whenever I do something other than the plain ".prefix" command:
![image](https://user-images.githubusercontent.com/18752458/29547664-4a52c7f8-86b0-11e7-86a0-0753e3ffcac5.png)
Any tweaks I could use? Is there an update planned to fix this?

**Comment by Kwoth** [comment]
What version are you on? Windows or linux?

**Comment by froidlesprit** [comment]
Windows 10.

**Comment by Kwoth** [comment]
There was a different kind of issue with prefix. Fixed it. Can't reproduce this. Works perfectly for me.
