### ISSUE TITLE
Unable to select a directory on the installers

### ISSUE THREAD

**Issue by ElectricLovelyland** [Kwoth/NadekoBot#1525]
Is this intentional?
For some reason there's no ability to do so and it will just automatically install to a directory even if it's not the one pointed at in the registry or if it's deleted in the registry.

Can we get the option to select a directory in these installers released here?
It'd be a massive help.

**Comment by Kwoth** [comment]
You can't when you update. Remove nadeko compltely by uinstalling from the control panel, then you should be able to when you install a fresh one.

**Comment by ElectricLovelyland** [comment]
Tried that and it didn't work.
Also could it be added in the future to be possible when it comes to updating?
It'd be a massive help for those of us who host the bot twice locally for more than one server.

**Comment by Jonz00r** [comment]
Sorry to interject, but why have two copies of Nadeko instead of just
adding the bot to both servers? (serious question)

**Comment by willysunny** [comment]
@Jonz00r To answer your question, in my case, I have two different bot, running at different languages.

But before you jumped the gun and said "Well, there's .langset for that", I'm talking about TOTALLY DIFFERENT LANGUAGES. That includes the trivia, and other configs that were not translated in the first place.

Another common reason I heard from other hosters is that they wanted to limit some of the stats limited to single server only. (EG: Flowers, waifu info, leaderboards, etc)

After all, it'd be weird to find a private bot containing user information of another server, right? :p

**Comment by ElectricLovelyland** [comment]
Hopefully this is addressed and added to the installer/updater as an advanced option at the very least for us.

**Comment by Macley-Kun** [comment]
@ElectricLovelyland @willysunny i suggest closing this issue and make a suggestion on feature hub.

**Comment by Kwoth** [comment]
true
