### ISSUE TITLE
won't even bother to launch

### ISSUE THREAD

**Issue by lock1982** [Kwoth/NadekoBot#1526]
As I tried to launch nadeko bot (yes, I followed the installation guide to the word), I get this error:

![image](https://user-images.githubusercontent.com/31259720/29589901-8d561bc6-8797-11e7-8a42-97b43f333a93.png)

So I would appreciate some help. Thanks in advance.

**Comment by shivaco** [comment]
Try installing this version of dotnet: https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.1-preview2-download.md

**Comment by lock1982** [comment]
As unfortunate as it may sound, it gave me the exact same output. Thanks anyways

**Comment by GMR516** [comment]
Looks like for some reason you're missing something to do with ImageSharp. Not sure how you would go about fixing this since there doesn't seem to be any other complaints relating to this issue. Can you try compiling it yourself?

**Comment by lock1982** [comment]
How can I do that?

**Comment by Kwoth** [comment]
I thought i replied to this issue. You're using old version of the bot most likely.

first back up your current folder if you have any settings just incase.

`cd ~ && wget -N https://github.com/Kwoth/NadekoBot-BashScript/raw/1.4/linuxAIO.sh && bash linuxAIO.sh`

run that, select an option to download nadeko

run nadeko again.

**Comment by Macley-Kun** [comment]
@lock1982 still having the issue still?

**Comment by lock1982** [comment]
Yep, sorry I wasn't able to respond earlier.

**Comment by Macley-Kun** [comment]
U tried what kwoth showed?

**Comment by Macley-Kun** [comment]
@lock1982 update? Did you update your nadekobot?

**Comment by Macley-Kun** [comment]
@lock1982 you can close this ticket and follow the refenced one. I suggest just re-installing nadeko.

I just noticed your using and outdated version (1.3). Suggest updating your Nadeko.

**Comment by Kwoth** [comment]
New installations of 1.3 won't work on linux/mac because referenced packages for image sharp no longer exist on their myget feed. Just update your bot using the new installer (check the linux guide for the new script link)
