### ISSUE TITLE
.shopadd help

### ISSUE THREAD

**Issue by OliverGoesLive** [Kwoth/NadekoBot#1528]
Hello,
I'm a little confused on the shopadd command. I know how to make it assign roles but can I make it do other things like send a steam key or give them real money. 

Thanks

**Comment by xnaas** [comment]
Nadeko has a help server for this. GitHub is for reporting bugs with the bot, not help.

**Comment by Kwoth** [comment]
discord.gg/nadekobot please go there and ask your question in the #help channel

If you don't want to here's a tip 

![image](https://user-images.githubusercontent.com/2537696/29647608-44932e76-888a-11e7-992b-295fb450d6bc.png)
