### ISSUE TITLE
Local Host Shop Bug

### ISSUE THREAD

**Issue by Olathurl** [Kwoth/NadekoBot#1529]
https://gyazo.com/0d161a8be3c28d7245ec0fd287b5b27f

As you can see, I set 3 items into our shop so far, costin 1 million, 500k, and 200k respectively. (placeholders). I then gave myself 1m currency. Then, i bought slot 1, for 1m.. However only 100k was taken from my total currency. 

upon testing, it would seem i only required 1m to have access to buying it, however the actual purchase price is only 10% of the listed value.. Any way to make it 100%?

~Edit~ Testing on the Public (Nadeko Server) Bot, shows it to be working just fine, It seems to possibly be just a Local issue. That, or I did the command wrong? (Typed exactly as the commands list shows) .shopadd role price rolename

**Comment by Kwoth** [comment]
The person who created the shop entry receives 90% of the profits.
