### ISSUE TITLE
Console is flooded with error. Idek

### ISSUE THREAD

**Issue by AJdisco** [Kwoth/NadekoBot#1530]
Bot still responds to commands however. this message cycles through every 10 or so minute's.
https://pastebin.com/KwLrhtqM

**Comment by Kwoth** [comment]
possibly your internet connection.

Just in case try disabling logs on your server and see if problem persists

**Comment by AJdisco** [comment]
I believe it is internet related, I left my computer for an hour to go idle. Probably disabled any unneeded outbound connections.

**Comment by Macley-Kun** [comment]
@AJdisco you still having this issue or can we close this?

**Comment by Macley-Kun** [comment]
@AJdisco can you close this ticket?
