### ISSUE TITLE
.rrc can potentially get you banned under stricter API regulations

### ISSUE THREAD

**Issue by butnotexactly** [Kwoth/NadekoBot#1531]
Discord staff has stated this is not a supported use case and has (after weeks without issue) suddenly banned a nadeko intance of mine for using it, even with a 60 second interval.

**Comment by Macley-Kun** [comment]
@Kwoth sorry for this ping Kwoth but due to some users that selfhost and not get the news, i suggest removing this feature ASAP before anything bad happens to them withoud them knowing.

**Comment by shikhir-arora** [comment]
There was already an announcement made in the server and https://github.com/Kwoth/NadekoBot/commit/20fb253eb31604967bc39ab0e5ca2a377dfb4bc5

**Comment by Kwoth** [comment]
^ already removed but i didn't make a windows release because i'm waiting to finish other stuff.

**Comment by Kwoth** [comment]
If anyone who has had their bot banned is reading this - Stop using the command, update the bot and contact discord support to get your bot unbanned.

**Comment by Macley-Kun** [comment]
@shikhir-arora ik. But not everyone watches the news about their selfbots 👀
