### ISSUE TITLE
CommandHandler Errorr

### ISSUE THREAD

**Issue by Nao-Tomori** [Kwoth/NadekoBot#1532]
I'm getting this error every time I try to use a command where I @ someone. Say I use .waifuinfo it works, but if I mention someone .waifu @someone it errors out with these errors:
https://puu.sh/xjqtn/7249394d1f.txt

This happens with any command that has an @ with it, but without it works. But for some reason it works in a new server.

**Comment by Nao-Tomori** [comment]
After doing some testing this happens on my server with public Nadeko too..

**Comment by agangofkittens** [comment]
This bug also happens on the public Nadeko instance.
![2017-08-25-222739_1024x600_scrot](https://user-images.githubusercontent.com/13337073/29731410-ab251d10-89e4-11e7-957d-9ed2b33c0f44.png)

**Comment by agangofkittens** [comment]
This bug also appears on the public Nadeko instance.
![2017-08-25-222739_1024x600_scrot](https://user-images.githubusercontent.com/13337073/29731475-e1388cde-89e4-11e7-9cc7-47151fe73125.png)

**Comment by Nao-Tomori** [comment]
It finally just started working again idk why. 10 hours after the initial issue
