### ISSUE TITLE
Nadeko.db file not found

### ISSUE THREAD

**Issue by ChiefKeef97** [Kwoth/NadekoBot#1533]
I have downloaded the latest version of the bot and ran the bot successfully and only ran into a few issues. the first being the bot randomly crashes, it works fine and then i cant use a command for some reason and find out that the command prompt for the bot has closed itself. the second issue i have is that the nadeko.db file used to edit parts of the bot isnt in the data file where it should be. the file never created itself like it is claimed

Thanks in advance for any help on my issue

**Comment by samdivaio** [comment]
Get me these info:
- OS
- version of bot
- error log when it crashes

> the file never created itself like it is claimed

Most likely it never ran so I am guessing your bot's token is incorrect or you're using outdated version of Nadeko.

**Comment by ChiefKeef97** [comment]
The bot ran fine before, I just couldn’t find the .db file to edit the bot. What happened was I downloaded the .zip from here and ran the updated app so I had 2 desperate file locations. The .zip was not being used therefore the .db file was never created in that location.

For the “crash” I’m not sure what happened but I will have to check the error log at a later time
