### ISSUE TITLE
Fair play

### ISSUE THREAD

**Issue by KuraiChanZ** [Kwoth/NadekoBot#1534]
So at first it was fine, but now suddenly when I load a saved playlist the only name that shows up is me the 'bot owner'. The songs that my friend added have my name now and I clearly remember not adding it. 

So there's technically zero songs added by anyone else and it renders the fair play command completely useless.

 In the first place fair play sometimes played my songs back to back, but that's a separate issue.

**Comment by Kwoth** [comment]
yea it can't work like that.

The person who loads the playlist is the new 'owner' of all songs
