### ISSUE TITLE
Commands that require pinging users not working.

### ISSUE THREAD

**Issue by Jamaaaa** [Kwoth/NadekoBot#1535]
Recently we've been having issues with Nadeko, both the public version and a self hosted version, on our server. https://discord.gg/pXPJApK
Any command that pings a user to do something (such as check waifu info or give flowers) does not work. In addition .pick and .prune do not work. All attempts to get the public and self hosted bot versions to work have failed, even after getting someone from the Nadeko support discord to come check it out. They referred me to here. The following are screenshots of the issue, as well as the errors I was getting from the self hosted bot.

![screenshot 598](https://user-images.githubusercontent.com/31378529/29746494-29fb3f32-8aaa-11e7-8796-90fc2f1d386f.png)
![screenshot 599](https://user-images.githubusercontent.com/31378529/29746495-2c2f6864-8aaa-11e7-9866-4e9452ee0be4.png)
![screenshot 600](https://user-images.githubusercontent.com/31378529/29746496-3e128f0c-8aaa-11e7-86be-06e4a272b2e9.png)
![screenshot 601](https://user-images.githubusercontent.com/31378529/29746530-1bb84194-8aab-11e7-938f-7a05c6feac28.png)

Her prefixes were not changed on either version, she had admin permissions the entire time, and she could still perform actions like the gambling games, manage roles, search porn, and do repeat messages. I've been trying to fix this for the better part of 5 hours and I'm out of ideas.

**Comment by willysunny** [comment]
Just asking for a supplementary info, is your self bot running in more than one server?

Because this happened to me as well, when I had multiple server setup.

**Comment by Jamaaaa** [comment]
No, it was not. I kept it only to our server.

**Comment by Jamaaaa** [comment]
I've since removed the self hosted bot and returned to the public version,
still having the same problem.

**Comment by willysunny** [comment]
double check with .listservers, someone might secretly invite your bot in case if you set your bot to public by accident.

**Comment by Jamaaaa** [comment]
There is only one server listed, our own.

**Comment by agangofkittens** [comment]
Relevant issue https://github.com/Kwoth/NadekoBot/issues/1532

**Comment by Kwoth** [comment]
Is this still happening? If yes, i'll open an issue on the discord.net repo

**Comment by Jamaaaa** [comment]
Yes, it is.

**Comment by Macley-Kun** [comment]
Any update on it? Can we get a link to the issue you made on Discord.net repo?

**Comment by DreamerNetwork** [comment]
Any updates? 

Still happening on 1.9.1

https://hastebin.com/eceruyekeq.md

**Comment by Kwoth** [comment]
I've created an issue on discord.net repo https://github.com/RogueException/Discord.Net/issues/824 

lets wait and see

**Comment by Midoriin** [comment]
I've tried to use `.shopadd` command in a server which has this issue and I got this error:
![1](http://midorina.ga/u/14a9f7.png)
