### ISSUE TITLE
Edit Command names?

### ISSUE THREAD

**Issue by ChiefKeef97** [Kwoth/NadekoBot#1536]
Is there a way to edit the command names through the .db file or another file such as .plant to .drop but it doing the same event (placing a currency in the channel for someone to pick up)

**Comment by GMR516** [comment]
You can compile the bot yourself if that's what you're asking. If that's the case, navigate to Resources>CommandStrings.resx or something similar (off the top of my head), and go to the plant command. Under the plant_cmd or whatever, add an alias by adding a space and typing a word.

**Comment by Kwoth** [comment]
you cant unless you compile yourself.

**Comment by ChiefKeef97** [comment]
Is there a tutorial on how to compile the bot with self hosting? Or only using the updator app
