### ISSUE TITLE
Can't start the Bot 

### ISSUE THREAD

**Issue by foxilich** [Kwoth/NadekoBot#1538]
Hi ,
When i try to start the bot with the updater or laucher, it just stops working and the window closed. Sure i used your guide on the webpage... but still not. Maybe the version isn't ok for my pc, but i couldn't find any answer.

**Comment by Kyousei** [comment]
Windows? If so, which Windows? 🤔

**Comment by foxilich** [comment]
Yes, i'm on windows 8

**Comment by Kyousei** [comment]
If you're getting dotnet error, double check your `credentials.json`

**Comment by foxilich** [comment]
it seems to be ok... i just can run the app, it's strange

**Comment by Macley-Kun** [comment]
Running it with admin? Compatible mode on Windows 8 to be sure? Re-install the bot perhapes? (Would save the credentials.json however).

**Comment by foxilich** [comment]
I tried but nothing worked :/ Windows just can't run the app, but i can't find the reason

**Comment by Macley-Kun** [comment]
Strange. Well the only other option would be re-installing windows. But that’s a bit to hardcore I would say. @kyousei you have any ideas?

**Comment by Kyousei** [comment]
You could try to reinstal Nadeko, @foxilich.

**Comment by willysunny** [comment]
@foxilich or try to contact me on nadeko help server@Willy_Sunny#1736 And I'll see if there's anything I can help you as well

**Comment by foxilich** [comment]
Thanks you! My problem is still here, even with the re-installing nadeko

**Comment by Macley-Kun** [comment]
I assume it has to do with dot,net or smth.. you could try to run it in a virtualbox or reinstall dot.net???

**Comment by Macley-Kun** [comment]
Update anyone?

**Comment by Macley-Kun** [comment]
@foxilich can you close the ticket?
