### ISSUE TITLE
Issues with linux (Debian) and dotnet

### ISSUE THREAD

**Issue by SpeedBird95** [Kwoth/NadekoBot#1539]
I installed everything and got the latest version of dotnet (which is 2.0.0) sdk.

However when I run Nadeko i get the following

Running Nadeko Normally, if you are running this to check Nadeko, use .die command on discord to stop Nadeko.
--2017-08-27 16:05:21--  https://github.com/Kwoth/NadekoBot-BashScript/raw/1.4/nadeko_run.sh
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Kwoth/NadekoBot-BashScript/1.4/nadeko_run.sh [following]
--2017-08-27 16:05:22--  https://raw.githubusercontent.com/Kwoth/NadekoBot-BashScript/1.4/nadeko_run.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 458 [text/plain]
Saving to: ‘nadeko_run.sh’

nadeko_run.sh                                   100%[====================================================================================================>]     458  --.-KB/s    in 0.001s

Last-modified header missing -- time-stamps turned off.
2017-08-27 16:05:22 (413 KB/s) - ‘nadeko_run.sh’ saved [458/458]

NadekoBot 1.5+
Mirai was here.
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
Dotnet installed.
The specified SDK version [1.0.1] from global.json [/root/NadekoBot/global.json] not found; install specified SDK version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
The specified SDK version [1.0.1] from global.json [/root/NadekoBot/global.json] not found; install specified SDK version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
Running NadekoBot. Please wait.
The specified SDK version [1.0.1] from global.json [/root/NadekoBot/global.json] not found; install specified SDK version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
Done

Welcome back to NadekoBot.
Welcome to NadekoBot.

Here is my dotnet --info:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     kali
 OS Version:  2017.1
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /root/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

I tried installed dotnet 1.0.1 but it gave me major issues.

**Comment by Macley-Kun** [comment]
U ran the pre-installer? I use debian 8 all the time, never had a problem?

**Comment by SpeedBird95** [comment]
Yes , ran everything. I fixed the issue. I had to downgrade dotnet to 1.0.1 , and that was giving me segmentation faults on my machine which is based on debian 9 , so i have to dpkg and force downgrade a few SSL libraries and finally got it working.

**Comment by Macley-Kun** [comment]
Intresting seems like you know way more about this problem. I geuss u can close this now? Btw does this happen to a Debian 9 that you have locally installed/running in a virtual box?

**Comment by SpeedBird95** [comment]
No , its not virtual. This issue happens on Kali Linux which is a Debian 9 based system which is heavily modified. If anyone else wants to get the bot running on Kali or Debian 9 or has seg faults and crypto dependency errors do the following:

Make sure you are using dotnet 1.0.1 and not 2.0.0 (Can wget it here https://www.microsoft.com/net/core#linuxdebian)

Downgrade  libicu57 to libicu52 
Downgrade  libssl1.0.2 to libssl1.0.0
Downgrade libcurl3 7.52 to libcurl3 7.38

You can find all of them at packages.debian.org

use dpkg --force-downgrade -i libname.deb   to force the downgrade and it should work.

Warning: You might break other apps that depend on those libs being up to date.
