### ISSUE TITLE
sinfo does not show the right amount of server members

### ISSUE THREAD

**Issue by pedall** [Kwoth/NadekoBot#1540]
![image](https://user-images.githubusercontent.com/20089354/29753935-c7200a14-8b7b-11e7-8f07-9d032083cf90.png)

![image](https://user-images.githubusercontent.com/20089354/29753938-d11fb640-8b7b-11e7-9ca7-5a2733abd66a.png)

**Comment by Macley-Kun** [comment]
@pedall you can close this issue. It's being picked up already here: #1433
