### ISSUE TITLE
Music doesn't play properly

### ISSUE THREAD

**Issue by Deady99** [Kwoth/NadekoBot#1542]
Hi,
i just setting up a new NakedoBot on my Linux Debian Server.
I followed the steps in the guide (http://nadekobot.readthedocs.io/en/latest/guides/Linux%20Guide/).
Everything worked fine but the music doesn't play properly. There are incredible laggs in the songs, you can't understand them. It seems like the songs aren't buffered or something.
Starting the song with ".play SONGTITLE"

Console: 
 MusicPlayer | Starting
 MusicPlayer | Got Audio client
 MusicPlayer | Created pcm stream

Now the music sounds like that: https://www.dropbox.com/s/uu4dd7lkuh9fp12/Discord%20Nadeko.m4a?dl=0

ffmpeg version 3.2.5-1~bpo8+1 Copyright (c) 2000-2017 the FFmpeg developers
What can i do now...?

Thanks
Deady

**Comment by samdivaio** [comment]
We are aware of that, its due to latest .net sdk. Try using docker on your debian or switch os to ubuntu.

**Comment by Deady99** [comment]
Thanks man, with docker it works fine 👍
