### ISSUE TITLE
Wrong translation German

### ISSUE THREAD

**Issue by Timguin** [Kwoth/NadekoBot#1543]
If you get a warn and it gets deleted, there is written "Bereinigt bei ...".
The correct translation would be "Breinigt von..."
But "Bereinigt von..." is seriously a bizarre translation, it would be better if it was "Gelöscht von..." or "Entfernt von..."
mfg timguin

**Comment by AuroraKy** [comment]
changed to geloescht von.

**Comment by Kwoth** [comment]
thanks @AuroraKy ^^
