### ISSUE TITLE
NSFW commands can be used in non-nsfw channels

### ISSUE THREAD

**Issue by jonasbpa** [Kwoth/NadekoBot#1544]
The title is self-explicative. Some members were spamming gay hentai in general channel in my server, which didn't have any NSFW tag/option active.

**Comment by shikhir-arora** [comment]
Type `.cm NSFW enable #yournsfwchannel` (replace the channel with the one you want). Then it will only work in that channel. You can also type `.listperms` to see the hierarchy. [All explained here](https://nadekobot.readthedocs.io/en/latest/Permissions%20System/) 👍

**Comment by Jonz00r** [comment]
Was there an update to the bot that made it so the commands were only
usable in NSFW flagged channels? If not you;ll have to set the permissions
up yourself. It doesn't do it on it's own and is clearly pointed out in the
permissions portion of the bot documentation.

**Comment by Deivedux** [comment]
It doesn't matter which channels are marked as NSFW or not, you have to manually manage the commands using permissions module. Keep that in mind.

**Comment by Kyousei** [comment]
Someone must've enabled NSFW in that channel.
Take away their perms.
Next time, please ask in **#NadekoLog** before posting it as an issue.

**Comment by Kwoth** [comment]
Permission system allows you to disable nsfw on certain channels. It's independent of discord nsfw channel option.
