### ISSUE TITLE
Bot won't start.

### ISSUE THREAD

**Issue by applebee53642** [Kwoth/NadekoBot#1546]
I've been trying to get the bot to work for me for a while but I keep getting the same errors / warnings when trying to run it.

https://gyazo.com/6e5500d9d655dc4a98605fbb89ba9ee5

-If the Link doesn't work here's the errors written out.

**C:\Users\brand\Nadeko\NadekoBot\src\NadekoBot\project.json(26,38): warning NU1007: Dependency specified was ImageSharp >= 1.0.0-alpha4-00031 but ended up with ImageSharp 1.0.0-alpha9-00138.
C:\Users\brand\Nadeko\NadekoBot\src\NadekoBot\project.json(27,46): warning NU1007: Dependency specified was ImageSharp.Drawing >= 1.0.0-alpha4-00031 but ended up with ImageSharp.Drawing 1.0.0-alpha9-00133.
C:\Users\brand\Nadeko\NadekoBot\src\NadekoBot\_Extensions\Extensions.cs(434,30): error CS0721: 'Image': static types cannot be used as parameters
C:\Users\brand\Nadeko\NadekoBot\src\NadekoBot\_Extensions\Extensions.cs(418,40): error CS0722: 'Image': static types cannot be used as return types
C:\Users\brand\Nadeko\NadekoBot\src\NadekoBot\_Extensions\Extensions.cs(418,81): error CS0718: 'Image': static types cannot be used as type arguments
C:\Users\brand\Nadeko\NadekoBot\src\NadekoBot\Modules\Gambling\Commands\DiceRollCommand.cs(208,27): error CS0722: 'Image': static types cannot be used as return types**

I've tried using both the stable build and the latest build to fix it and neither of them have worked. I've also tried restarting my computer in order to see if that was the problem, and I tried deleting all the files and reinstalling them to make it work but nothing has fixed this.

It didn't have any problems while installing Nadeko or while updating any of the times either.

**Comment by willysunny** [comment]
Because we don't compile bot anymore :p

Use the new Nadeko Updater.

**Comment by applebee53642** [comment]
Where's the new Updater at?
