### ISSUE TITLE
crca

### ISSUE THREAD

**Issue by MoonKidd** [Kwoth/NadekoBot#1549]
The command crca isn't working. The words in a sentence still don't trigger a response.

**Comment by shivaco** [comment]
Make sure you put custom reaction's ID after `.crca`, not the trigger
For example: `.crca 6381`

**Comment by MoonKidd** [comment]
Actually, I know and did that. The bot says it will respond to the keywords from now on, but it doesn't, which is why I opened the problem.

**Comment by MoonKidd** [comment]
Not sure why it was closed after only one response, but alright

**Comment by MoonKidd** [comment]
Guess I'm not getting help on this then

**Comment by Kwoth** [comment]
O.o 

Can you type exactly which custom reaction you added and how (the command)
And then how did you use crca
and then what are you typing, what are you expecting to happen, and what is actually happening

**Comment by MoonKidd** [comment]
Okay so, I added a custom command if anyone says "Where is pewdiepie" because I own a fan server and that gets asked a lot. The command was acr and it says it was added as #53. I then did crca for 53. I tested typing where is pewdiepie along with other words in the sentence, and for some reason the not won't reply to it. It will only reply to the actual trigger added.

**Comment by Kwoth** [comment]
no, show me the exact command of how you created a custom reaction. and you actually typing stuff. Provide screenshots.

**Comment by MoonKidd** [comment]
http://imgur.com/a/TJbtv

**Comment by MoonKidd** [comment]
http://imgur.com/a/p9Ojw

**Comment by MoonKidd** [comment]
http://imgur.com/a/FWupi any other words in the message and it doesn't trigger, which I expected

**Comment by MoonKidd** [comment]
Also hopefully it still counts for a self-hosted nadeko http://imgur.com/a/AQ1kZ

**Comment by Kwoth** [comment]
make sure you don't have multiple custom reactions with the same tag. I can't reproduce this. Works fine for me 
![image](https://user-images.githubusercontent.com/2537696/30253774-045a27be-968c-11e7-8f3a-7781ec908a5c.png)

**Comment by MoonKidd** [comment]
Still won't work for me for some reason, but seeing how it works for you I'll deal with it

**Comment by Kwoth** [comment]
@MoonKidd this was actually the issue. I just fixed it. It only happened with global custom reactions though. You didn't bring up that detail.
