### ISSUE TITLE
 I can not become the creator of Nadeko

### ISSUE THREAD

**Issue by Pomfych** [Kwoth/NadekoBot#1553]
Followed the instructions. It was not possible to become the creator of Nadeko. The bot does not execute commands on the server, available only to the creator. Attached credentials. What did I do wrong? >.<

**Comment by shivaco** [comment]
You better to re-create bot account ASAP. Leaking token will not lead to anything good. Also try adding a space after first square bracket in `OwnerIds` field

**Comment by Deivedux** [comment]
Firlsty, do not show your bots token unless someone else might be able to control it for their own purpose.
Secondly, you can't run Nadeko on Windows 7 (required Windows 8 or later and 64 bit system).

**Comment by Pomfych** [comment]
Thanks!
