### ISSUE TITLE
Logs are restricted to having to be both bot owner AND administrator

### ISSUE THREAD

**Issue by Blacnova** [Kwoth/NadekoBot#1554]
My friend invited my selfhosted nadekobot on his server, and wanted to enable .antispam and found that it doesn't tell you when you get muted. So I told him he could enable logging, but when he went to enter .logevents he was told that he had to be bot owner. Same thing happened with .log.

**Comment by Kwoth** [comment]
This is more of a feature request. Please post it on feathub. Logging was disabled because of public nadeko.
