### ISSUE TITLE
Issues with Server Mute

### ISSUE THREAD

**Issue by Shukashuu** [Kwoth/NadekoBot#1556]
**.mute**
- will apply _server mute_ even when it said itself that it doesn't have the necessary permission to execute the command. the user has to be in a voice channel for this to happen. i tested this with the bot only possessing the default Nadeko role.

**.voicemute**
- only works if the user is inside a voice channel despite saying that the user has been voice muted.

**.unmute** and **.voiceunmute**
- fails to remove _server mute_  if the user is outside of a voice channel. note that the user has to be server muted first.

_Tested this with the public bot_

**Comment by Kwoth** [comment]
You can't voice unmute the user if he's not in the voice channel, nothing I can do about this.
