### ISSUE TITLE
Nadeko Comands help

### ISSUE THREAD

**Issue by AGNextGen** [Kwoth/NadekoBot#1558]
How do you keep Nadeko online and u can use the commands for Nadeko without always opening the Nadeko Command Launch Application?

**Comment by AnimosusTheWolf** [comment]
How do you expect the bot to run without the program open?

**Comment by sleepymanakete** [comment]
Host on vps

**Comment by Deivedux** [comment]
Let's make it easier to understand this: if you want to play a game on your pc you would expect that you will need to open the game first, and keep it opened to continue playing it; same for Nadeko, you open the console and keep it running to respond to commands. You have multiple choices how to keep Nadeko running, one of them is to host on your own computer, other ways include payed hosting services that will host the bot for you. Most common ones I know are [DigitalOcean](https://www.digitalocean.com), [OVH](https://www.ovh.co.uk), [Heroku](https://www.heroku.com/), and many more.
