### ISSUE TITLE
Music not working from youtube

### ISSUE THREAD

**Issue by borgqueenx** [Kwoth/NadekoBot#1559]
I am running centos 7 with latest youtube-dl and ffmpeg 3.3.2.
I am getting the following error when wanting to play a song:
https://puu.sh/xs3Ax/f94c495b8a.png

Doesn't matter what youtube song. The bot joins, does nothing and disconnects from the voice channel.

Help would be appriciated!

**Comment by Kwoth** [comment]
duplicate of #1308
