### ISSUE TITLE
Globally disallow young images as it is a violation of Discord's ToS

### ISSUE THREAD

**Issue by Swiftfeather** [Kwoth/NadekoBot#1560]
A server I regular recently got hit by Discord admins for having loli/shota/cub/young/etc images posted, many of them by the Nadeko bot. Since these images are in explicit violation of discord ToS, is there any chance of having the .e621 and other commands automatically filter out Loli/shota/young/cub/etc images? We'd love to continue to use the bot*'s NSFW features* but as of now it still pulls up images that Discord disallows.

**Comment by Kwoth** [comment]
No, I'm not responsible for what's hosted on those websites. Anyone using those tags is violating discord ToS, not the bot. 

I believe there is a way to explicitly exclude a tag on those websites but I'm not sure of the way to do that.
