### ISSUE TITLE
Can't start the bot

### ISSUE THREAD

**Issue by hvrdtimes** [Kwoth/NadekoBot#1561]
I'm attempting to run Nadeko on my server, and when I go to turn it on I get 4 different errors:

Nadeko\NadekoBot\src\NadekoBot\_Extensions\Extensions.cs(434,30): error CS0721: 'Image': static types cannot be used as parameters
Nadeko\NadekoBot\src\NadekoBot\_Extensions\Extensions.cs(418,40): error CS0722: 'Image': static types cannot be used as return types
Nadeko\NadekoBot\src\NadekoBot\_Extensions\Extensions.cs(418,81): error CS0718: 'Image': static types cannot be used as type arguments
Nadeko\NadekoBot\src\NadekoBot\Modules\Gambling\Commands\DiceRollCommand.cs(208,27): error CS0722: 'Image': static types cannot be used as return types

How do I go about fixing this?

**Comment by GMR516** [comment]
https://github.com/Kwoth/NadekoBot/issues/1526  ?

**Comment by Macley-Kun** [comment]
@hvrdtimes @GMR516 I noticed from the refence provided that the user had version 1.3. I assume for now that you also use an outdated Nadeko. Re-install nadeko and tell us if you still have the issue.

**Comment by Kwoth** [comment]
Yea, just update. Make sure to use the new installer.
