### ISSUE TITLE
Nadeko Notification Tray

### ISSUE THREAD

**Issue by PhoenixMusic** [Kwoth/NadekoBot#1562]
Hi!
I host Nadeko on my pc. I want to know if I can put the application is system notification tray on windows, I don't want to be in taskbar.
Anybody knows how to do this?

**Comment by antonmassoud** [comment]
There is a program called OuttaSight which can do this

**Comment by willysunny** [comment]
hasn't heard the name OuttaSight for a really long time. Are you like, 3x~4x? XD

Anyways, back to the subject, no. Nadeko does not provide built-in function to hide into the notification tray without third party support.

**Comment by Macley-Kun** [comment]
@PhoenixMusic if i were you go to feature hub of NadekoBot and suggest it there! Ask your friends to upvote it. Meanwhile, use this OuttaSight program. You can close the issue ^.^
