### ISSUE TITLE
SongBuffer issues, lagging music.

### ISSUE THREAD

**Issue by StargazingNeko** [Kwoth/NadekoBot#1563]
Any song played seems to start lagging half way through, the console outputs "Unable to read from socket" and "Failed to send close message".

I have two Nadeko installations, one is version 1.3b the other is 1.7.1, the 1.3b plays just fine while the 1.7.1 lags. I don't know if this is just me or not.

1.3b log output-
![image](https://user-images.githubusercontent.com/4255010/30235663-e8c90042-94bf-11e7-9dfb-22f359988a5d.png)

1.7.1 log output-
![image](https://user-images.githubusercontent.com/4255010/30235668-fc8d0894-94bf-11e7-8e96-4bee73a2f3d8.png)

**Comment by WasabiIceCream** [comment]
Same issue here. The lagging/buffering is actually really bad.

**Comment by Macley-Kun** [comment]
Are you running these both at the same time?
Perhapes re-doing the installation could help?
I do noticed there is a pull request open #1527 but idk if that would have anything to do with your issue.

**Comment by StargazingNeko** [comment]
No, I make absolutely sure there is only one bot running at a time.
The 1.7.1 is a fresh install, I didn't even know 1.7.1 as well as the executable updater existed until the day I opened this issue because I thought the batch file was keeping everything up-to-date.
I'm not so sure the issue is the same, I run Nadeko off of my gaming/streaming PC so it's multi-threaded but never know it could be the same.

**Comment by Macley-Kun** [comment]
@StargazingNeko and you also are sure your using a windows 8.1 up to date version?

**Comment by StargazingNeko** [comment]
Windows 10, fully up to date.

**Comment by Macley-Kun** [comment]
@Kyousei you have a clue how this can be fixed?

**Comment by Macley-Kun** [comment]
@StargazingNeko ok so idk how to fix it for now but. I would assume you do the following.
Disable alle modules on NadekoBot v1.3b expect music.
Disable Music module on the newest NadekoBot.

I geuss that's the only solution i can give you now. I don't use Windows sow...

**Comment by Kwoth** [comment]
please post music issues here, don't open new issues, #1053
