### ISSUE TITLE
Self-hosted nadeko not responding

### ISSUE THREAD

**Issue by WalkingDude02** [Kwoth/NadekoBot#1564]
Ever since Discord released channel categories Nadeko hasn't been responding to commands. The version of Nadeko that I am running is 1.3b and I was told that 4 other people have reported this bug

**Comment by Kwoth** [comment]
Please update your bot. You can do so by simply getting the new installer link from the linux guide.
1. Run it and install prerequisites
2. Download the bot (option 1)
3. Run the bot

All of your old data and setting should be preserved. Make sure to backup first just incase.

**Comment by seshormerow** [comment]
I updated to the latest Nadekobot and my self hosted from source bot is also not responding in a server that tested categories in disord canary but decided not to use them until stable discord had them. It works on the another server just fine that hasn't tested categories.

**Comment by Kwoth** [comment]
I just created categories on my server. Works fine.

**Comment by Kyousei** [comment]
One user reported that it didn't work since they restarted the bot

**Comment by seshormerow** [comment]
My bot had been offline through the duration and was started after testing categories, The bot hasn't responded to anything since.

**Comment by Kwoth** [comment]
Ah, there's the issue
https://github.com/RogueException/Discord.Net/issues/810

I'll try to push the update tonight
