### ISSUE TITLE
.xpex User isn't working (doesn't exist)

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#1569]
doing `.xpex User @google` gives an error, saying my ID is not a server...

`.xpex` command description and command examples suggest that you can exclude Users and Servers

`Xp.cs` and `.xpexl` reveals that you can exclude Server, Role, Channel, but not User.

🤔 

Also, small thing: `.xpex channel` isn't very flexible as it always requires 2 arguments. Please make `.xpex channel` exclude the channel that the command is run in, if no other argument is provided.

**Comment by Kwoth** [comment]
Ah, my bad. You can't exclude users. Just create an 'xp-excluded' role, exclude it, and add users to that role.

`.xpex channel` will now default to current channel. Just pushed those fixes.
