### ISSUE TITLE
.xpex does not take into account the current state [?]

### ISSUE THREAD

**Issue by YamiyoYamxiy** [Kwoth/NadekoBot#1571]
If you attempt to toggle the permissions after restarting the bot, a new addition will occur.

E.g. 1. Add a channel to the deleted xp list.
2. Restart the bot.
3. Try to toggle the permission. Instead of removing the channel from the list, it will add again but a duplicate in .xpexl will not be listed - it may appear in db.
4. After placing the duplicate and trying to toggle again, the channel is removed from the list.

**Comment by Kwoth** [comment]
fixed :^)
