### ISSUE TITLE
If there any blacklisted tags, Nadeko will not post any images from any command under the NSFW module.

### ISSUE THREAD

**Issue by hedgeh0gpie** [Kwoth/NadekoBot#1572]
Just as the title says, if there is a single tag that is blacklisted, and it can be anything, Nadeko will not reply with an image at all when a NSFW command is used.

**Comment by Kwoth** [comment]
No, can't reproduce. It's working fine.

**Comment by zergling-man** [comment]
Reproduced on public Nadeko version 1.8.4, NSFW commands won't work with the tags "loli", "shota" and "underage" blacklisted, or with just "loli" blacklisted (I haven't tested any other combinations), *if I don't search for a tag*. If I search for a tag they work normally. If I search for a blacklisted tag, it works as it should.
