### ISSUE TITLE
NadekoBot.db not updating when making changes

### ISSUE THREAD

**Issue by sleepymanakete** [Kwoth/NadekoBot#1573]
Asked in help a few times on channel and no one didn't really help, my bot doesn't seem to be updating the db anymore. if i do .$ it says i have 35188 but if i shutdown the bot and go to the db it still says i have 35678. Any changes I do to the bot doesn't show up in the db. I was told that "channel categories" might be my problem and i have no idea what this.

**Comment by Kwoth** [comment]
Make sure to close your SqliteBrowser. Any pending changes in the sqlitebrowser with prevent database from being updated by the bot.

**Comment by sleepymanakete** [comment]
Yeah its closed, I'm not so sure what's wrong. I'm hosting on Windows from the source, could that be it?

**Comment by Kwoth** [comment]
Sure, if you messed with the source, it might be the issue. Data definitely persists through restarts :D

**Comment by sleepymanakete** [comment]
I figured it out, the db is saved somewhere else when hosting from the source :D
