### ISSUE TITLE
NadekoStrings | music_sad_enabled key is missing from ru-RU response strings. PLEASE REPORT THIS.

### ISSUE THREAD

**Issue by RedWolf8** [Kwoth/NadekoBot#1574]
Reported.
"Songs will be deleted from the music queue when they finish playing." should be "Песни будут удаляться из очереди по завершению воспроизведения.".
"Songs will no longer be deleted from the music queue when they finish playing." should be "Песни больше не будут удаляться из очереди по завершению воспроизведения.".

**Comment by Kwoth** [comment]
Strings are being translated atm.
