### ISSUE TITLE
Unicode in .xp

### ISSUE THREAD

**Issue by willysunny** [Kwoth/NadekoBot#1577]
![image](https://user-images.githubusercontent.com/5907852/30255563-32a9767e-96d7-11e7-82d3-b4e4dc52a95d.png)

Would become blank, most likely due to the font used not able to support the Unicode.

PS: is it possible for us to change the font?

**Comment by Kwoth** [comment]
No plans to support that atm. Not sure about font changing. 

Fonts are indeed in data folder, but i'm not sure would it work if you added another font but renamed it to match the current one.

**Comment by willysunny** [comment]
Reason being when font file can not parse the character glyph, it'll just return empty, or squares like this

![image](https://user-images.githubusercontent.com/5907852/30257468-f2a2bb7c-96e4-11e7-8639-b7aaa87f944a.png)

PS: This is using Google Noto font https://www.google.com/get/noto/

From the above screen shot, it's now more of a fact on how the string was parsed. (or else it should appear with the proper text already.)
