### ISSUE TITLE
Converter module

### ISSUE THREAD

**Issue by tg44** [Kwoth/NadekoBot#158]
For converting stuffs.

Like:
~convert m>inch 10
~convert eur>usd 100
~convert faren>celsi 76

Libs:
```
+ http://www.codeproject.com/Articles/23087/Measurement-Unit-Conversion-Library
? http://www.codeproject.com/Articles/787029/UnitConversionLib-Smart-Unit-Conversion-Library-in
- https://github.com/objorke/QuantityTypes <-  ? and a list in it
- https://physicalmeasure.codeplex.com/ (it's intresting but not in our case)
? http://nugetmusthaves.com/Tag/measurement (huge list, need a deeper look)

+ where I read the api and it's seems good
? where I didn't read the api
- where I read the api but its not fit in our cases
```

**Comment by Kwoth** [comment]
Pffff, looks epic

**Comment by tg44** [comment]
PR added closeable.

**Comment by Kwoth** [comment]
Phyxsius - Yesterday at 12:59 PM
It would be nice that ~convert could convert timezones to, that would be very helpful.

**Comment by tg44** [comment]
This is much harder than I thought. If sb want to implement this some resource:
http://stackoverflow.com/a/15171527/2118749 <- this code is a good starting point, but instead of the json deserialization you can use [this][1]
The next problem will be this: http://stackoverflow.com/questions/5996320/net-timezoneinfo-from-olson-time-zone

And if you want to write it you will need to cache the city/country - timezone information.

Because this is more work then the whole converter functionality was I pass it :)

[1]: http://stackoverflow.com/a/17617710/2118749

**Comment by Kwoth** [comment]
Since i saw how much complexity there is for time zone conversion, and having in mind almost nobody will use it, i have no interest in nadeko having this feature anymore.
