### ISSUE TITLE
NadekoBot for 32 bit/ x84

### ISSUE THREAD

**Issue by DELIRIOUSDONUT** [Kwoth/NadekoBot#1580]
am i able to run nadekobot on a 32 bit computer?

**Comment by samdivaio** [comment]
That is correct if you use the regular Windows self hosting method. But it should be possible if use the traditional method of running the bot from its source code as long as [.net core sdk installer](https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.4-download.md) is available for 32bit windows 8+ or similar

**Comment by Macley-Kun** [comment]
Really? A windows 8+ 32bit can be used for hosting Nadeko? And you can still transfer the db file withoud any issues?

**Comment by samdivaio** [comment]
Yes but you gonna have to use [scripts for that](https://github.com/Kwoth/NadekoBotInstallerWin/raw/1.4/windowsAIO.bat) and manually install other prerequisites like git and dotnet core sdk also db is universal you can use it with any platform as long as bot isnt outdated.

**Comment by DELIRIOUSDONUT** [comment]
Thanks a lot!
