### ISSUE TITLE
.xp command shows people's server rankings as #1 if they don't have any XP. and a club bug

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#1581]
As title says. There are some screenshots:
![1](https://cdn.discordapp.com/attachments/244404504366284800/356798985396027392/266636899790094347_xp.png)

When they gain some xp, their real ranking appears:

![2](https://cdn.discordapp.com/attachments/244404504366284800/356799082087579649/266636899790094347_xp.png)

**Comment by Midoriin** [comment]
Also, even though that club has only 12 xp, leaderboard shows it as #1. This is probably because that club is newer, but leaderboard is not supposed to work like that, I assume.
![image](https://user-images.githubusercontent.com/22325138/30279042-bf78f402-9714-11e7-8448-aed3a0fb4863.png)

**Comment by Kwoth** [comment]
Can't reproduce first issue, second issue just fixed

**Comment by Kwoth** [comment]
Actually that issue is indeed present on the public bot, but not on beta bot 🤔

**Comment by PhoenixMusic** [comment]
I didn't wanted to create another issue. I want to know how level up system is working.
You get xp when you talk? and how much in time?

**Comment by Midoriin** [comment]
You get 3 xp per 5 minutes. Please use the Nadeko support server to get help next time. discord.gg/nadekobot

**Comment by PhoenixMusic** [comment]
Okay, thank you very much. I'll join to server

**Comment by Kwoth** [comment]
I believe this is fixed?

**Comment by MatiasMovie** [comment]
how change color and image on xp image? only admin can do?
