### ISSUE TITLE
Public Nadeko dead in servers that uses categories

### ISSUE THREAD

**Issue by kongslien** [Kwoth/NadekoBot#1582]
Please fix. We cannot softban or warn people. Regular bans will have to suffice until you've updated.

**Comment by Macley-Kun** [comment]
Linux Self Hosters ONLY

I've just pushed :tada:  1.8 :tada:  update. If you had issues with unresponsive bot because of categories feature, it should work now.

Update to v1.8, and magic will happen 👀

**Comment by kongslien** [comment]
WTF. This was just to grab Kwoth's attention. You posted for no reason.

**Comment by Macley-Kun** [comment]
In your title you said: Public Nadeko dead in servers that uses categories #1582

I assumed that Public Nadeko means the bot you invited from a link, one that you don't host yourself.

If you ment a selfhosted Nadeko, i suggest updating, it's bin fixed in the previous post.

**Comment by kongslien** [comment]
If i meant selfhosted, i would've written that.

**Comment by willysunny** [comment]
@kongslien Just in case if you didn't know, 司义徒弟 is kwoth, well, his current tag that is.

**Comment by Macley-Kun** [comment]
Lmao this issue was already known, I just copied pasted the announcements 😂

**Comment by Kyousei** [comment]
@willysunny, kongslien is Kong, the Cute Girl in **#NadekoLog**, and he knows 😂

**Comment by kongslien** [comment]
:thinkderp:

**Comment by Macley-Kun** [comment]
Wtf? What’s this bullshit =3=
