### ISSUE TITLE
Nadeko Bot offline

### ISSUE THREAD

**Issue by Cassiebas** [Kwoth/NadekoBot#1583]
I added the bot via the website. It worked fully this afternoon. I recently logged back in again but it seems it is offline. What's happening?

**Comment by Kyousei** [comment]
Nadeko's temporarily offline.
Look at the image below

![image](https://user-images.githubusercontent.com/29898563/30287770-9638770e-9726-11e7-930e-bcf79d9d5693.png)

**Comment by shivaco** [comment]
Nadeko is offline for a while. Just wait.

**Comment by Cassiebas** [comment]
Thank you!

**Comment by Kyousei** [comment]
Please close the issue.
