### ISSUE TITLE
.autohentai won't work after self-hosting

### ISSUE THREAD

**Issue by tmcdiscord** [Kwoth/NadekoBot#1585]
So I typed the following command : 
`.autohentai 30 futa` 
and it showed this message : 
![d](https://user-images.githubusercontent.com/31867334/30298170-097cc748-9753-11e7-935f-eaa9b86a059f.PNG)

however, there're no images being posted in the channel. I allowed for nsfw and manage messages. 
the prompt would show this : 
![858](https://user-images.githubusercontent.com/31867334/30298231-45716c18-9753-11e7-8884-656511d51d59.PNG)
but nothing happens in the channel.

**Comment by QuantumToasted** [comment]
Just so you know, @Kwoth , this person already figured out their issue - Where they live, this sites were blocked. Using a VPN solved their issue.
