### ISSUE TITLE
.clubcreate not working for self-hosters

### ISSUE THREAD

**Issue by Bread2k** [Kwoth/NadekoBot#1587]
I am level 13, I am the server owner, the bot owner, basically I have full authority over the bot. When I do .clubcreate <name> the message gets deleted signaling that the bot recognizes it as a command, I look at the console and the command has been registered..... but nothing happens. There's no confirmation message, and when I go to check the club's info, it doesn't exist

**Comment by Macley-Kun** [comment]
Wanna add smth on this too. I try to create a club for example, but i have to be level 5. I award myself the xp and i still couldn't make a club?

Though this was relevant to the topic.

**Comment by Kwoth** [comment]
You need global level 5, also i tried this and it works. Can't reproduce.
