### ISSUE TITLE
Race issue

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#1589]
When people send a lot of messages after a race starts, Nadeko was sending the race message again in order to keep it at bottom. But in 1.8.4, it does not bring the race to the bottom in any way.

**Comment by Macley-Kun** [comment]
@Midoriin can you provide a screenshot? I think you can also ping master kwoth then ^~^

**Comment by Midoriin** [comment]
Well, I dont think it needs a proof. You can just simply start a race with your friend and spam as much as you can.

**Comment by Macley-Kun** [comment]
Yeh i just tested it, was buzzy. But indeed it doesn't work.. @Kwoth can you label this issue as bug?

**Comment by Macley-Kun** [comment]
@Kwoth tested out the .race, it indeed doesn’t send it again anymore. You can put a label Bug on it :)

**Comment by Macley-Kun** [comment]
@Kwoth is this a bug or intended?

**Comment by Kwoth** [comment]
chilllll :emiwot: i'll get to it eventually
