### ISSUE TITLE
ASCII art

### ISSUE THREAD

**Issue by tg44** [Kwoth/NadekoBot#159]
@BotName ascii url
@BotName ascii img

http://www.codeproject.com/Articles/9153/ASCII-art-with-C

If sb want to go deeper it is possible to convert a text to img and convert that to ascii.

@BotName ascii text

like: http://www.text2image.com/pit_t2i/saver but sth cooler would be better :)

**Comment by Kwoth** [comment]
I'll get started on this now, lets see how far i go

**Comment by Kwoth** [comment]
Well, its kinda impossible due to the fact that discord limits messages to 2000 characters. That's around 45x45 image.

**Comment by tg44** [comment]
you can sand it with multiple messages quickly after each other
The bigger problem is the window resize I think...

**Comment by ZetaHunter** [comment]
Bot's have a rate limit of 10 messages per 10 seconds, multiple messages for a single command is sure way to kill the bot.

**Comment by tg44** [comment]
then drop the idea :) We tried it at least.

**Comment by Kwoth** [comment]
Yeah ill close it for now, i don't see a way for it to work properly, except generating an image of the ascii representation, which is lame.

**Comment by ZetaHunter** [comment]
The only other way I could see this also working is generate the ASCII and
send it as attachment, but this requires attachment perms and would be
kinda useless as output would be in a separate text file user has to
download to view.

2016-03-30 11:27 GMT+03:00 Master Kwoth <notifications@github.com>:
