### ISSUE TITLE
Antispamignore for roles?

### ISSUE THREAD

**Issue by MoonKidd** [Kwoth/NadekoBot#1594]
Sorry to bother with this, but my admins and mods keep getting banned for spamming bot commands and ignoring a whole channel wouldn't work because the actual raiders wouldn't be banned.

**Comment by QuantumToasted** [comment]
@MoonKidd I haven't tested this myself, but I believe bots must still respect the role hiearchy. Try placing all of Nadeko's roles lower than the highest role you want to be able to be banned, like so:
```
Owner
Admins
Moderators
Nadeko <----
VIP
Regular users
@everyone
```

**Comment by MoonKidd** [comment]
Thanks! I was dumb to not think of that. We tested it out and it seems to be working so far.
