### ISSUE TITLE
Music not working on 1.8.4

### ISSUE THREAD

**Issue by Mexiguy** [Kwoth/NadekoBot#1596]
Whenever trying to play either a song either from youtube or soundcloud it shows the song info but never plays, when checking the console I get the following

![screenshot 2](https://user-images.githubusercontent.com/7787321/30447849-cb03b3f8-9952-11e7-8dcd-20f6fe8890f0.jpg)

18:16:25 CommandHandler | Command Executed after 0.004/0.004/4.084s
        User: Mexiguy#8874 [289299050795106306]
        Server: Slice of Life Club [288366371736125450]
        Channel: music [288367328369049601]
        Message: .q https://www.youtube.com/watch?v=ryUGkBFUX2o
18:16:25 MusicPlayer | Starting
18:16:27 Ytdl | WARNING: unable to extract uploader nickname

18:16:27 MusicPlayer | Get current user
18:16:27 MusicPlayer | Connecting
18:16:27 VplusTService | Adding role nvoice-288366371736125452 to user Koume-cha
n
18:16:28 SongBuffer | >>> Unrecognized option 'reconnect_streamed'.
18:16:28 SongBuffer | >>> Error splitting the argument list: Option not found
18:16:28 MusicPlayer | Got Audio client
18:16:28 MusicPlayer | Created pcm stream
18:16:28 MusicPlayer | Song removed because it can't play
18:16:28 MusicPlayer | Next song
18:23:42 MusicService | Checks
18:23:42 MusicService | Get or add
18:23:42 YoutubeResolveStrategy | Getting link
18:23:46 Ytdl | WARNING: unable to extract uploader nickname

18:23:47 MusicPlayer | Starting
18:23:47 CommandHandler | Command Executed after 0/0.004/4.297s
        User: Mexiguy#8874 [289299050795106306]
        Server: Slice of Life Club [288366371736125450]
        Channel: music [288367328369049601]
        Message: .q sakuea quext op
18:23:50 Ytdl | WARNING: unable to extract uploader nickname

18:23:50 MusicPlayer | Got Audio client
18:23:50 MusicPlayer | Created pcm stream
18:23:50 SongBuffer | >>> Unrecognized option 'reconnect_streamed'.
18:23:50 SongBuffer | >>> Error splitting the argument list: Option not found
18:23:50 MusicPlayer | Song removed because it can't play
18:23:50 MusicPlayer | Next song
18:27:42 MusicService | Checks
18:27:42 MusicService | Get or add
18:27:42 CommandHandler | Command Executed after 0/0/0.648s
        User: Mexiguy#8874 [289299050795106306]
        Server: Slice of Life Club [288366371736125450]
        Channel: music [288367328369049601]
        Message: .q https://soundcloud.com/alakram27/hatsune-miku-megurine-luka-
samune-zimi-reboot-vocaloid-anime
18:27:43 MusicPlayer | Starting
18:27:43 MusicPlayer | Got Audio client
18:27:43 MusicPlayer | Created pcm stream
18:27:43 SongBuffer | >>> Unrecognized option 'reconnect_streamed'.
18:27:43 SongBuffer | >>> Error splitting the argument list: Option not found
18:27:43 MusicPlayer | Song removed because it can't play
18:27:43 MusicPlayer | Next song

**Comment by xnaas** [comment]
#1053

**Comment by Kwoth** [comment]
You need to update your ffmpeg to 3.x+

**Comment by Happiys** [comment]
Hmmm this is broken as it doesn't seem play any music just give me this:
15:39:08 SongBuffer | >>> av_interleaved_write_frame(): Broken pipe
15:39:08 SongBuffer | >>> Error writing trailer of pipe:1: Broken pipe
15:39:08 MusicPlayer | Next song
15:39:08 MusicPlayer | Starting
15:39:28 MusicService | Checks
15:39:32 MusicService | Get or add
15:39:32 MusicService | Checks
15:39:32 MusicService | Get or add
15:39:32 CommandHandler | Command Executed after 0/0/3.859s
        User: Iris BloodRaven#6571 [233055065588367370]
        Server: Testing [264177412797890563]
        Channel: general [264177412797890563]
        Message: vanilla.start
15:39:38 Ytdl | WARNING: unable to extract uploader nickname

15:39:38 MusicPlayer | Got Audio client
15:39:38 MusicPlayer | Created pcm stream
15:39:39 MusicPlayer | Song Canceled
15:39:39 SongBuffer | >>> av_interleaved_write_frame(): Broken pipe
15:39:39 MusicPlayer | Next song
15:39:39 MusicPlayer | Starting
15:39:46 Ytdl | WARNING: unable to extract uploader nickname

15:39:46 MusicPlayer | Got Audio client
15:39:46 MusicPlayer | Created pcm stream

I even tried manually updating ffmpeg to stable and latest version of 3.3.3  seem do nothing.
Bot stays in there until you force close not even .die kills it

**Comment by Happiys** [comment]
I just done a youtube-dl update it seems it fix the errors but it doesn't play music still

**Comment by Macley-Kun** [comment]
You also updated FFMPEG?

**Comment by Macley-Kun** [comment]
So because version 1.9 is out. Can you try to update to that? Your then still having the issues?
