### ISSUE TITLE
.iam doesnt work for some people until you .rsar .asar

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#1597]
I saw this a few days ago, joined a server where there were many self-assignable roles, but they weren't working for everyone. I eventually told the person to remove the role from the list, and then add them back, and it worked 🤔 Public Nadeko iirc.

Probably not a big problem, maybe just a hiccup?

**Comment by Macley-Kun** [comment]
Probably. You can try to recreate the situation and see if it works straight away. It's up to you 👍

**Comment by MaybeGoogle** [comment]
Have only seen it once... can't recreate it, maybe I should close.

**Comment by Macley-Kun** [comment]
👍

**Comment by MaybeGoogle** [comment]
Closing because it doesn't seem to be an actual problem, just a weird case. 🤔
