### ISSUE TITLE
Music isn't working

### ISSUE THREAD

**Issue by PhoenixMusic** [Kwoth/NadekoBot#1599]
I'm using Nadeko 1.8.4. I host her on Digital Ocean VPS. I installed correctly, youtube-dl and ffmpeg are up to date.
I cannot play music. When I use the command .play songname it said "No song found".
I changed the droplet on vps and reinstaled Nadeko, but same thing.
On PC music is working perfectly. I use Google API Key.
![capture](https://user-images.githubusercontent.com/31708040/30505586-39327e32-9a7e-11e7-835f-64d452ec1b52.PNG)

**Comment by PhoenixMusic** [comment]
I want to now why it doesn't work? I did something wrong?

**Comment by Macley-Kun** [comment]
Did you also enabled the correct services in the google api console?
Also idk what kind of video your playing there. But it says Payment Required ???

**Comment by PhoenixMusic** [comment]
I enabled all the required services in the Google api console. The APIs work good. But Nadeko can't play any song. Seems like the problem is with youtube-dl or ffpeg, but Idk why. I installed and reinstalled the bot and I followed any instruction to host on vps. Also Idk why it work on pc with same creditentials.

**Comment by PhoenixMusic** [comment]
And Idk what is with that video or payment

**Comment by Macley-Kun** [comment]
Can you maybe show the version of both Youtube and FFMPEG? Maybe that helps a bit. @kyousei ya got a clue 🤔 ?

**Comment by PhoenixMusic** [comment]
Here are the version of youtube-dl and ffpeg
![screenshot_2017-09-16-12-22-35](https://user-images.githubusercontent.com/31708040/30511077-0e224608-9ada-11e7-80f7-5f5f3d5c29d2.png)

**Comment by Macley-Kun** [comment]
Hope someone else can help with this issue, everything seems fine in my eyes. Personally i don't use the music module so i can't test it out for ya.

**Comment by PhoenixMusic** [comment]
Thank you. I hope someone will help me. This is what I get:
![img_20170916_123520](https://user-images.githubusercontent.com/31708040/30511153-9e4a4e3c-9adb-11e7-9ce2-2faaa925a8d5.png)

**Comment by samdivaio** [comment]
You either need to solve the captcha or your ip/api has used all free youtube quota . (i doubt that)

**Comment by samdivaio** [comment]
https://github.com/rg3/youtube-dl/blob/master/README.md#faq Check the error 402 here

**Comment by PhoenixMusic** [comment]
how I solve the captcha for my ip? please steps

**Comment by Macley-Kun** [comment]
https://github.com/rg3/youtube-dl/blob/master/README.md#i-get-http-error-402-when-trying-to-download-a-video-whats-this
He refers to this part @PhoenixMusic

**Comment by PhoenixMusic** [comment]
I give up. I don't know what to do. I tried everything. youtube-dl doesn't want to access my vps IP and can't download the video to extract the music and then to play it.

**Comment by PhoenixMusic** [comment]
Not a problem now. I don't know what happened but now the music works. I deleted the droplet on vps and I created another one, I reinstalled the bot again and setted up. The only change that I made is to not enabling the ipv6 on the droplet.

**Comment by Macley-Kun** [comment]
Mhm intresting. Thanks for sharing that tho. Perhapes we can support ipv6?

**Comment by PhoenixMusic** [comment]
Idk, pc has ipv4 and ipv6, but now works and I will not do any changes to the droplet, maybe youtube-dl doesn't support ipv6 on Digital Ocean (my vps) or in any vps. The problem was with the IP.

**Comment by samdivaio** [comment]
ipv6 used to cause some youtube issues with us digitalocean vps before 🤔 Interesting

**Comment by Macley-Kun** [comment]
Can this be fixed on nadeko? Or is this a yt side issue?

**Comment by samdivaio** [comment]
YouTube
