### ISSUE TITLE
RedisConnection: not possible to connect to redis server

### ISSUE THREAD

**Issue by NeonSpectrum** [Kwoth/NadekoBot#1600]
it only occurs after updating to 1.9
AWS Server Ubuntu 16.04
![image](https://user-images.githubusercontent.com/29432829/30509194-1a04ba3e-9add-11e7-8951-b91701b9fcb3.png)

**Comment by NeonSpectrum** [comment]
installing `sudo apt-get install redis-server` fix the problem

**Comment by Kwoth** [comment]
why are you upgrading to 1.9? Who said it was ready?

**Comment by Kwoth** [comment]
dont blame me later
