### ISSUE TITLE
.prune isn't showing the right error

### ISSUE THREAD

**Issue by anonymasen** [Kwoth/NadekoBot#1604]
Actual: ```Error: The input text has too many parameters.```
Expected: some error saying insufficient permission like this
https://gyazo.com/f929ab3456e58647737523689f4d5073

Reproducing steps:
- give permission for non-owner to run this command on nadeko
- disable `manage message` permission on discord on that person's role
- type `prune 3`
wohala!

**Comment by Macley-Kun** [comment]
Label as Bug?

**Comment by Kwoth** [comment]
I woudln't call this a bug. I can't fix this actually. That's simply how the parsing system works
