### ISSUE TITLE
.clubbans errors are a bit weird

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#1605]
Scenario: I am not in a club, and I do `.clubbans`. Nadeko tells me "%user% that club doesn't exist." It should say "%user% you are not in a club."

If you meant for only the clubowner to be able to check bans, maybe "%user% you are not a club owner."

**Comment by Macley-Kun** [comment]
@shivaco hey dude i noticed recently you found fixed some 'typo's' in Nadeko. Can you maybe fix the above issue?
