### ISSUE TITLE
Unable to disable XP module

### ISSUE THREAD

**Issue by anthonyrgib** [Kwoth/NadekoBot#1606]
Hello,

I'm trying to disable the XP module as it is something I do not wish to use on my server. I've tried typing ".sm xp disable" and even tried things like ".sm exp disable" and other ways of typing XP such as; xp, XP and Xp to no avail. 

I'm assuming that either i'm not typing it correctly or the module doesn't seem to be able to be disabled, which i'm assuming shouldn't be the case?

Thanks in advance! 👍

**Comment by Kyousei** [comment]
`XP` module contains commands such as `.xp`, `.clubinfo`, etc.
if you wish to disable XP gain, exclude the server by typing `.xpex Server`.

But if You're trying to disable commands from `XP` module, make sure You have **Nadeko** role. (Make a new role, call it Nadeko and give it to yourself)

**Comment by Kwoth** [comment]
What kyousei said.  And btw it works for me.
![image](https://user-images.githubusercontent.com/2537696/30588171-038465d8-9d36-11e7-8a2e-0f551803c482.png)

**Comment by Zrad72** [comment]
Do I have to give the Nakedo role any permissions after creating it? And can I disable all modules? Because I dont want to have NSWF module on my server

**Comment by Kwoth** [comment]
NSFW commands can't be used outside NSFW channels. so if you don't want NSFW commands, you don't need to do anything.
