### ISSUE TITLE
[feature request] Automated club voice channels

### ISSUE THREAD

**Issue by theENiGMAman** [Kwoth/NadekoBot#1607]
Sorry if this is the wrong place to post, I couldn't find a suggestions page anywhere so I hope it's ok to post it here ^_^

Anyway, would love to see a feature in a future release so on .clubcreate Nadeko automatically creates a role and a voice channel with perms only that role (+admins & Nadeko) can see so clubs can have private rooms only their club can see and use. Would be great for multigaming communities - atm we have to do this manually. Not sure if it's even possible to automate.

Keep up the good work!

**Comment by Kyousei** [comment]
Post your suggestions [here](https://feathub.com/Kwoth/NadekoBot). 😄
