### ISSUE TITLE
No response for .xprr on public bot

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#1608]
I was told you already know this, but I didn't see an issue for it.

Title says it all, no response and no action after `.xprr` (at least according to `.xprrs`)

**Comment by shivaco** [comment]
What parameters are you using? I just tried using  `.xprr 10 Verified` and it workes only when I used `.xprr 8 Verified`.

**Comment by MaybeGoogle** [comment]
I used a bunch of stuff, meow tested it, I tested it, someone asked about
it on nadeko help... I thought it was a well-known problem. Is there a
minimum value for xp required in .xprr?

**Comment by shivaco** [comment]
As I can see, 10 is the maximum.

**Comment by Kwoth** [comment]
Fixed in 1.9, there is no maximum btw.
