### ISSUE TITLE
No owner Channels Created?

### ISSUE THREAD

**Issue by Mauroooo** [Kwoth/NadekoBot#1615]
Today I got this error message and I cant fix it.

![ss 2017-09-22 at 02 35 54](https://user-images.githubusercontent.com/25819357/30744675-76d4d15c-9fa3-11e7-97ea-17808c5ab088.png)
I havent changed anything on the credentials.json file
![unbenannt](https://user-images.githubusercontent.com/25819357/30744722-b567e4fe-9fa3-11e7-9e6d-4fe09cf1fafa.PNG)

**Comment by Kwoth** [comment]
Is the ID correct?
Did you invite the bot to the server you're at?
Can people who are not in your friends list DM you?

**Comment by Mauroooo** [comment]
Yes its the correct Client/Owner/Bot/Token ID.
Yes I invited the Bot to the server
And people that are not in my FL can DM me

**Comment by Mauroooo** [comment]
I created a new Server and the bot works there.
Could it be that the problem has to do with the Category system, because I added Categorys and since that it wont work.

**Comment by Kwoth** [comment]
Slight chance. Make sure to update your bot. You didn't tell me your bot doens't work at all.

**Comment by Mauroooo** [comment]
It works fine but not on that server and I dont know why
It's also up to date.

**Comment by Kwoth** [comment]
try reinviting it?

**Comment by Mauroooo** [comment]
Tried it several times

**Comment by Kwoth** [comment]
What version are you on?

**Comment by GMR516** [comment]
According to that screenshot: 1.3b.

**Comment by Kwoth** [comment]
Oh mesage was edited. You're not on latest version. You need to update to 1.4+  You can do that by checking the installation guide

**Comment by Mauroooo** [comment]
Sorry for not answering wasnt home it works again, ty.
