### ISSUE TITLE
Bug with multiple Bots on 1.9

### ISSUE THREAD

**Issue by Gremagol** [Kwoth/NadekoBot#1616]
As Kwoth said, I should create an Issue.
As the title says, theres a huge mess when you run more than one bot on your PC/VPS/Whatever.
How to recreate:
Run more than one bot on 1.9
type `.setgame Test` ONLY FOR ONE BOT
All bots you're running on 1.9 will sync their playing status to `Test`

Check these Images:

![1 9bug1](https://user-images.githubusercontent.com/24619854/30747582-0357b388-9fae-11e7-953f-d05c2027ed42.PNG)
![1 9bug2](https://user-images.githubusercontent.com/24619854/30747614-164bb462-9fae-11e7-9f44-5b2343decd25.PNG)

**Comment by Kwoth** [comment]
Should be fixed
