### ISSUE TITLE
Bot Doesn't work with categories.

### ISSUE THREAD

**Issue by DulceArma** [Kwoth/NadekoBot#1617]
NadekoBot is immediately not reading and voice or chat channel within a discord that has a category in it. Categories were recently added in a new discord update so I didn't think it would work with anything with thin that category but the bot is just not reading ANY channel in that discord even channels that aren't in a category.

Tested:
I deleted all added Categories in my discord. then the bot was able to read all Voice and chat channels.

I then added a single Category and added a couple of channels into it. The bot was not able to read any of the Voice or chat channels.

**Comment by shikhir-arora** [comment]
Are you running the latest version? Make sure to update Nadeko. It was fixed in 1.8 I believe.

**Comment by DulceArma** [comment]
I updated it a couple of times including the stable and the latest builds neither of them worked

**Comment by DulceArma** [comment]
I haven't tried reinstalling it completely I only updated but I can try that

**Comment by Kwoth** [comment]
Update your bot to 1.8+

If you're on linux you need to use this link

first, backup your current installation just in case

`cd ~ && wget -N https://github.com/Kwoth/NadekoBot-BashScript/raw/1.4/linuxAIO.sh && bash linuxAIO.sh`


1. Reinstall prerequisites
2. Download nadeko (first option)
3. Run nadeko
