### ISSUE TITLE
CurrencyGenerationChance Not working properly

### ISSUE THREAD

**Issue by Jengas** [Kwoth/NadekoBot#1619]
Default chance is **0.02**. But when i try to put any number from 0.01 to 0.99 - nothing works. Only 1 or 0
https://prnt.sc/gonl5n
http://prntscr.com/gonm95

**Comment by Kwoth** [comment]
Make sure your bot is up to date. Works fine for me. Possibly a bug in some of the ancient versions?

**Comment by Jengas** [comment]
I have 1.8.4 version http://prntscr.com/gooewt
