### ISSUE TITLE
Twitch notification, flood (don't panic, DON'T PANIC!)

### ISSUE THREAD

**Issue by Glaived** [Kwoth/NadekoBot#162]
![sans titre 2](https://cloud.githubusercontent.com/assets/1835170/14092341/77b89c1a-f546-11e5-86ca-1b5485763106.png)

the alert is repeated 5-10 times
offline, online, offline, online.. while I had no problem side Twitch

**Comment by Kwoth** [comment]
does it spam instantly, or once every 15 seconds?

**Comment by Glaived** [comment]
Hm, i don't know because i don't watch (I was on stream)

**Comment by Kwoth** [comment]
One thing i guess could be happening is that Nadeko is following too much twitch streams and she gets blocked every so often from making api calls which results in her treating it as offline. I will look into this.

**Comment by Glaived** [comment]
you can use a buffer depending on _id, if if does not change is that it does not send a message via Nadeko

https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#if-online

**Comment by Glaived** [comment]
![capture](https://cloud.githubusercontent.com/assets/1835170/14230895/94735eba-f96c-11e5-9a6c-e4d043aec5f6.PNG)

The correction is incomplete, but Nadeko did not say more than what you see in the image

**Comment by Glaived** [comment]
up? @Kwoth

**Comment by Kwoth** [comment]
Nobody else reported this afaik since the update. I don't know what could cause the issue.

**Comment by Glaived** [comment]
The problem would not come uppercase? or made to do this:
```
~twitch Glaived_Tv
~rms Glaived_Tv
~twitch Glaived_Tv
```

**Comment by Luxadin** [comment]
I'm not sure if it's helpful for me to say but I have the same problem with the bot as well. Just thought to say because you've said that nobody else reported about it besides the OP. NadekoBot still spams a lot of stream announcements during twitch streams even though they're still running and never down once. Not sure how would it be fixed however.

**Comment by xnaas** [comment]
I've never encountered this issue. But I've only been using the bot since https://github.com/Kwoth/NadekoBot/releases/tag/v0.94. I'm gonna guess this can be re-closed unless @Glaived is still having trouble?

**Comment by blownco** [comment]
im having the same issue with the latest release.

**Comment by Kwoth** [comment]
@blownco on self hosted bot, or Nadeko?
