### ISSUE TITLE
"Issue" on -h command.

### ISSUE THREAD

**Issue by YamiyoYamxiy** [Kwoth/NadekoBot#1620]
The DM help string still sending the old prefix in the message bellow:
Type `-h` for help.

That's in BotConfig table and I think that should be changed to automatic detection since we have the `.prefix` now.

Also, this message is not in `ResponseStrings.json`, would not this be a problem because the translations?

**Comment by Kwoth** [comment]
that's your own setting. DmHelpString. you have to modify it yourself in bot config.
