### ISSUE TITLE
Version 1.9 does not open.

### ISSUE THREAD

**Issue by DaYWhiTe** [Kwoth/NadekoBot#1621]
I made an update as you said, but it is not opening now.

![adsiz](https://user-images.githubusercontent.com/21060067/30773832-94b2b980-a081-11e7-8529-be437891bf38.png)

**Comment by Gremagol** [comment]
Have you installed Redis properly?

**Comment by DaYWhiTe** [comment]
I reinstalled the prerequisite

**Comment by DaYWhiTe** [comment]
I have installed redis manually and it is working now.
