### ISSUE TITLE
Bot cant join channel

### ISSUE THREAD

**Issue by Regnator** [Kwoth/NadekoBot#1622]
16:57:07 MusicService | Checks
16:57:07 MusicService | Get or add
16:57:07 YoutubeResolveStrategy | Getting link
16:57:10 CommandHandler | Command Executed after 0/0/3,31s
        User: Solus Regnator#4036 [165086845573529612]
        Server: United Gaming DE [165087484722675712]
        Channel: botbefehle [263016329844359169]
        Message: .q dubstep
16:57:10 MusicPlayer | Starting
16:57:14 MusicPlayer | Get current user
16:57:14 MusicPlayer | Connecting
16:57:14 MusicPlayer | Got Audio client
16:57:14 MusicPlayer | Can't join
16:57:15 MusicPlayer | Song removed because it can't play

Bot has adminrights, joins for half a second and leaves, saying he cant join.
All dependencies have been downloaded and installed.

Bot version 1.8.4 on Ubuntu 14.04

**Comment by Macley-Kun** [comment]
I would suggest trying to update, maybe it's because of channel categories?
Backup your db file and credentials.json before updating!

**Comment by Regnator** [comment]
It got fixed! It works now with bot version 1.9.1
Discord probably broke something but now its working again. :D
