### ISSUE TITLE
`.xp` command shows your global ranking +1

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#1624]
![1](http://midorina.ga/u/7eb42b.png)
I've tested it for others. The issue occurs with them as well. I'm on 1.9.0

**Comment by Gremagol** [comment]
I'm Rank 1 on my bot when using .xpglb, but when I use .xp, my bot shows me im #0. Nadeko seems to have problems with the ranking system :/

**Comment by DaYWhiTe** [comment]
Same issue. I'm #1 on my bot but it shows in the image #2

**Comment by QuantumToasted** [comment]
![image](https://user-images.githubusercontent.com/30324210/30777276-ba6a732a-a07c-11e7-810e-2ecc9b3ce478.png)
Same here, running 1.9.0, just updated a few hours ago.

**Comment by raser129** [comment]
Hey I have a question how do you level up your Global level?

**Comment by Kwoth** [comment]
Should be fixed.
