### ISSUE TITLE
Bot deletes reaction message on 1.9

### ISSUE THREAD

**Issue by sleepymanakete** [Kwoth/NadekoBot#1626]
All i did was type `.startevent reaction` and then my bot deletes it. It worked fine in 1.8.4
![image](https://user-images.githubusercontent.com/30272172/30775457-076d0f56-a051-11e7-99d5-ac4b3b5d6b83.png)

**Comment by Midoriin** [comment]
Yep. It occurs for me as well. 
![1](http://midorina.ga/u/a6bec5.png)

**Comment by Kwoth** [comment]
Because your currency sign can't be used as a reaction. Change your currrency sign to be something that bot can react with, and it will work.

**Comment by Kwoth** [comment]
I'll leave this open for a while, so that other people can see it.
