### ISSUE TITLE
Custom hangman text doesn't work (self-host, 1.10.1)

### ISSUE THREAD

**Issue by Foxwells** [Kwoth/NadekoBot#1627]
Whether using `.hangman` or `.hangman categoryname`, you just get the following error:

```
21:13:09 CommandHandler | NadekoBot.Modules.Games.Common.Hangman.Exceptions.TermNotFoundException: Term of that type couldn't be found
   at NadekoBot.Modules.Games.Common.Hangman.TermPool.GetTerm(TermType type)
   at NadekoBot.Modules.Games.Common.Hangman.Hangman..ctor(TermType type)
   at NadekoBot.Modules.Games.Games.HangmanCommands.<Hangman>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_1.<<BuildCommand>g__ExecuteCallback1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsync>d__40.MoveNext()
```

I've checked a number of times to ensure that there were no issues with brackets or anything, so I'm out of ideas. I've attached my custom text, as well as the error text log.

My computer OS is Windows 10, latest version.

Note: This bug report was filed on ver 1.8.4, but I upgraded to 1.10.1 and it's still broken.

[hangman3.txt](https://github.com/Kwoth/NadekoBot/files/1326999/hangman3.txt)

[command_errors_2017-09-23.txt](https://github.com/Kwoth/NadekoBot/files/1326998/command_errors_2017-09-23.txt)

**Comment by Kwoth** [comment]
it needs to be called hangman3.json, not txt

**Comment by Foxwells** [comment]
@Kwoth It **is** a json file. I turned it into a .txt so you can see its contents, as github doesn't take .json uploads.

**Comment by Kwoth** [comment]
Delete the file and update your bot.

**Comment by Foxwells** [comment]
He is up to date already. This problem wasn't around when it was 1.5(ish-- it's been a while since then). It only occurred after I updated. And it's been broken since.

![hdfa9evjqfevf7vulyvhaq](https://user-images.githubusercontent.com/15647033/30785929-d1ca292c-a133-11e7-8440-3b264d097e10.png)

**Comment by Kwoth** [comment]
Ah hm. Since you're using the installer, you'll have to go to your installation folder and change data/hangman3.json with the contents from this link https://raw.githubusercontent.com/Kwoth/NadekoBot/1.4/src/NadekoBot/data/hangman3.json

**Comment by Foxwells** [comment]
@Kwoth that's exactly against the point of this bug report... I _want_ custom hangman, because I run an SFW Pokemon-themed server, and the hangman has inappropriate references. Custom hangman used to work, and now it doesn't. So I'm submitting a bug report so it can be fixed, because just telling me to "put the old text back" doesn't fix the problem that custom hangman stuff is broken.

**Comment by Kwoth** [comment]
Oh. then your text isn't a valid json. There's no bug that prevents you from putting your own hangman references. Just check your json. use some of the json validators on the internet.

**Comment by Foxwells** [comment]
No, it's valid.

![screenshot_420](https://user-images.githubusercontent.com/15647033/30787256-205b0e92-a14a-11e7-8c70-27f3a55e38b4.png)
![screenshot_421](https://user-images.githubusercontent.com/15647033/30787255-20571f6c-a14a-11e7-909b-552a927ca295.png)
![screenshot_422](https://user-images.githubusercontent.com/15647033/30787254-2056eeac-a14a-11e7-9e16-a38972bfc405.png)

**Comment by Kwoth** [comment]
try it with a one word category, idk. Try gradually changing the data, and you'll find where the error is.

**Comment by Foxwells** [comment]
Have tried one word categories already. Did not change anything.

The custom hangman _used_ to work. I haven't changed the data at all since it last did (save for my tests, but it was reverted back to what it was before after). The only thing that changed was that I updated my bot from 1.5-- after that, it just stopped working. I really don't think this is an issue on my end.

**Comment by Foxwells** [comment]
@Kwoth Updated to 1.10.1, still doesn't work. I ran tests, removing each of my custom categories one by one. All produced errors. I tried renaming them to the ones you have (animals, etc). All produced errors. Can this _please_ be re-opened and marked as a bug, if anything?

**Comment by Kwoth** [comment]
It's definitely not a bug. You're doing something wrong. You can't tell me my json works but yours doesn't. There's nothing special about the json I wrote. Try making small changes incrementally.

**Comment by Foxwells** [comment]
It _is_ a bug. I did poking around files. I can't claim to know all of what everything says, but the terms list clearly isn't zero, so it's throwing the error due to this: `!Data.TryGetValue(type.ToString(), out var termTypes)`

I had to rename my categories to, and in the order of, [termType.cs](https://github.com/Kwoth/NadekoBot/blob/e76f3216deac8d4e7942888640edb23e8ef51548/src/NadekoBot/Modules/Games/Common/Hangman/TermType.cs) before it finally worked.

![screenshot_431](https://user-images.githubusercontent.com/15647033/31016552-cf963bfe-a4ea-11e7-904e-f0ddab94e9ab.png)

But that is not a fix. That is a workaround. And it doesn't allow for more categories to be added, and throws errors at categories not in that rigid name call.

**Comment by Kwoth** [comment]
`I tried renaming them to the ones you have (animals, etc). All produced errors.` This is what you said, but yes, that indeed is an issue.

**Comment by Foxwells** [comment]
The difference with that, I think, is that they weren't in the specific order of termType.cs -- I had one category in the file, and I named it "Animals", "Movies", etc. Was tossed the error. In this case, I had "Countries" and then "Movies". Tried specifically `.hangman Movies` and it worked.

**Comment by Kwoth** [comment]
@Foxwells it's working now, right?

**Comment by EthanTheAce** [comment]
@Foxwells I was wondering if you still have the json file? Because I was trying to do the exact same thing, would save a lot of pain and time if you have it :P.
