### ISSUE TITLE
Atom feeds not being accepted

### ISSUE THREAD

**Issue by SillyBirds** [Kwoth/NadekoBot#1628]
I've tried two different ones, but it seems the bot is not accepting atom feeds, though the same ones as rss do work.

One of them: rss, `https://www.animenewsnetwork.com/all/rss.xml`, atom `https://www.animenewsnetwork.com/all/atom.xml`

**Comment by Kwoth** [comment]
I will test it later today. I've tried some atom feeds and they worked. Possibly didn't consider different combination of available fields.

**Comment by Kwoth** [comment]
I'm not sure what's wrong. There are some atom and rss feeds which syndication feed says they're invalid. Other one's work fine. Needs further investigation. I think i'll need to write custom parsers, or use some which are already written for older versions of those standards.

**Comment by nicolastd5** [comment]
Is not working.

https://animesvision.net/beta/rss/lancamentos.rss

**Comment by Fuseteam** [comment]
appearantly it does work for youtube channel feeds like https://www.youtube.com/feeds/videos.xml?channel_id=UCa9qpOXTVcj1iFMlgg0fOxw either

**Comment by narrundo** [comment]
it doesnt work using Twitter RSS fetch https://twitrss.me/ example :  https://twitrss.me/twitter_user_to_rss/?user=eslrainbowsix

**Comment by Kwoth** [comment]
http://store.steampowered.com/feeds/news.xml doesn't work

**Comment by Macley-Kun** [comment]
Hacktoberfest is over :p

**Comment by OrigamiSS** [comment]
any reddit feed will not work. they use ATOM feed.
e.g https://www.reddit.com/r/AskReddit.rss

**Comment by Macley-Kun** [comment]
Even the populair 9gag feeds doesn't work! O_O
http://www.9gag-rss-feed.ovh/rss/9GAG_-_Hot.atom
How do we get the hottest meme's to discord now 🤔

**Comment by thebeastgamer25** [comment]
Any updates on this?

**Comment by Macley-Kun** [comment]
This issue cant be fixed by Kwoth himself (see the help wanted tag). 
A person who know how to program in c# and knows how to code rss/atom/feeds is needed in order to solve this issue.

**Comment by thebeastgamer25** [comment]
@Macley-Kun ah, I see. What feeds are supported? Is there an alternative bot that _does_ work with atom?

**Comment by Macley-Kun** [comment]
Discord.RSS
Written in javascript. Max feeds per server 5. Selfhosting it can increase it too ∞ feeds per server.
Works with every feed you can imagine.

**Comment by thebeastgamer25** [comment]
Thanks!

**Comment by hemipatu** [comment]
I might know someone that can provide a fix for this and will contact them and query if they can help. I'll let you know if I can indeed get their help.

**Comment by xnaas** [comment]
Someday™ 😉
