### ISSUE TITLE
XP Image stretching 1.9.1

### ISSUE THREAD

**Issue by d-floe** [Kwoth/NadekoBot#1631]
Previously on my self hosted bot I personally designed an XP image that looked like this
https://image.prntscr.com/image/UdGs-fl-R2KTiIjsnfyaiw.png

I made it this way because my self hosted bot only belongs on one server so the extra bottom bar was cropped out for design purpose. However, after updating my bot to 1.9.1, it seems that the image is now stretching to compensate for the previous resolution, and it looks really terrible now.
https://image.prntscr.com/image/OvPdFAgCTu64LlDUvYWhZg.png

Please fix this and revert it to the way it was before!

**Comment by GMR516** [comment]
What version were you on before?

**Comment by Kwoth** [comment]
Just means your image is not correct resolution. Match it to the current xp image.
