### ISSUE TITLE
Offline Bot, Nadekobot.exe - Application Error, BlackScreen... My Nadeko not love me T-T

### ISSUE THREAD

**Issue by AsmodayFalkenheyn** [Kwoth/NadekoBot#1634]
I not have a experience with bots or discord, NadekoBot Updater v1.8.4, win 8.1 (64-bits).

https://uploaddeimagens.com.br/imagens/xzczx-png
https://uploaddeimagens.com.br/imagens/02-png--477
https://uploaddeimagens.com.br/imagens/03-png--301
https://uploaddeimagens.com.br/imagens/01-png--777

**Comment by TwinDragon** [comment]
Just guessing, but looking at what you posted for your config, you're missing a "BotID" flag. This is my config when using the Linux script to auto-setup the credentials: https://i.imgur.com/kE5F4gZ.png - You can see the ClientID and BotID are the same.

**Comment by Kwoth** [comment]
I think your best bet is to google your error and try to see what's causing it. It's an issue specific to your PC.

**Comment by MaybeGoogle** [comment]
can you dl and try the new updater? doubt it will help but maybe...
