### ISSUE TITLE
Windows Running 1.4/1.9 from Source - project.json missing

### ISSUE THREAD

**Issue by Mihro** [Kwoth/NadekoBot#1635]
- [x] Fresh install of Git.
- [x] Followed [this docs page](http://nadekobot.readthedocs.io/en/latest/guides/From%20Source/) about installing from source. (Possibly outdated by the way. Clones from the 1.4 repo.)
- [x] Credentials.json edited accordingly.
- [x] cd to NadekoBot/src/NadekoBot

- [ ] Running `dotnet restore` produces this error:
```
D:\PGS\Documents\Discord\Nadeko\NadekoBot Temp\src\NadekoBot>dotnet restore
warn : The folder 'D:\PGS\Documents\Discord\Nadeko\NadekoBot Temp\src\NadekoBot' does not contain a project to restore.
```
- [ ] Then running `dotnet run -c Release` produces this error:
```
D:\PGS\Documents\Discord\Nadeko\NadekoBot Temp\src\NadekoBot>dotnet run -c Release
The current project is not valid because of the following errors:
D:\PGS\Documents\Discord\Nadeko\NadekoBot Temp\src\NadekoBot(1,0): error DOTNET1017: Project file does not exist 'D:\PGS\Documents\Discord\Nadeko\NadekoBot Temp\src\NadekoBot\project.json'.
```

-----

The error clearly points out that it's looking for a 'project.json' file which it can't find.
Previous versions of the NadekoBot source had the 'project.json' file included. ([see this paste](https://pastebin.com/0CtvvFXs))
I've half a mind to just copy the old project.json over to see how well it would fare.

Hope that this issue isn't too hard to address. Wanting to do some deeper customization of your fabulous bot.
Mihro

**Comment by 20100157** [comment]
I solved this error once installing[ .NET Core 1.0.4](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md) and 1.1.x.

**Comment by Kwoth** [comment]
Yes you need a newer version of .net core. Also you want to clone 1.9 branch and install redis and .net core sdk 2.0 in order to be up to date. I'll update the from source guide soon-ish.
