### ISSUE TITLE
No owner channels created!

### ISSUE THREAD

**Issue by Lapotor** [Kwoth/NadekoBot#1636]
Before a few days the Bot stopped working.
Then i restarted it and there i always get this:
![grafik](https://user-images.githubusercontent.com/17144397/30886869-226efcd6-a319-11e7-8ebf-4a92b7eedf69.png)

===

Here is my credentials.json:
```
{
  "ClientId": ******************,
  "BotId": ******************,
  "Token": "***********************************************************",
  "OwnerIds": [140***************],
  "LoLApiKey": "",
  "GoogleApiKey": "***************************************",
  "MashapeKey": "",
  "OsuApiKey": "",
  "PatreonAccessToken": "",
  "Db": null,
  "TotalShards": 1
}
```
I reconfigured the credentials with the installer but nothing helps.

**Comment by Kyousei** [comment]
Update your bot to the latest. Channel Categories broke Nadeko on v1.7.1

**Comment by Kwoth** [comment]
Update your bot to 1.9+

If you're on linux you need to use this link

first, backup your current installation just in case

`cd ~ && wget -N https://github.com/Kwoth/NadekoBot-BashScript/raw/1.9/linuxAIO.sh && bash linuxAIO.sh`


1. Reinstall prerequisites (option 4)
2. Download nadeko (option 1)
3. Run nadeko
