### ISSUE TITLE
.restart starts a new instance with a new database

### ISSUE THREAD

**Issue by ManuelFte** [Kwoth/NadekoBot#1639]
Tested in a Nadeko install without source code modifications on Ubuntu 16.04. After the bot returns from using the `.restart` command, it starts with a fresh database as it can be seen here:

![screenshot from 2017-09-27 07-00-56](https://user-images.githubusercontent.com/896973/30912503-6938caa0-a352-11e7-9d94-fc0ebea691d4.png)

The instruction I added to the credentials.json was the same recommended in the JSON explanations:

```
  "RestartCommand": {
    "Cmd": "dotnet",
    "Args": "run -C Release"
  }
```

That's when using option 2 of the script, "Run Nadeko (Normally)". Using option 3, "Run Nadeko with Auto Restart", will add another weird behavior where the bot will launch an extra instance every time it restarts. For example, after restarting twice I ended up with three instances as seen here (although it's just natural that these two options shouldn't be used in combination, but it probably should be explained somewhere):

![screenshot from 2017-09-27 07-07-36](https://user-images.githubusercontent.com/896973/30912611-e62e9e4a-a352-11e7-9f11-2bb1b52c7324.png)

**Comment by Kwoth** [comment]
If it's a fresh database, it means you didn't run your bot in release, but in debug mode. You can't run restart with auto restart. If you've using auto restart, option, use .die to restart the bot and remove restartcommand from credentials.
