### ISSUE TITLE
Concurrent bot users

### ISSUE THREAD

**Issue by SillyBirds** [Kwoth/NadekoBot#1640]
I was up to date till 2 days ago on I think 1.9.0 and today I updated the bot for two different users on my server (ubuntu 16.04) and now it's impossible to have both of them up at the same time.

If one starts, then other won't and vice versa.

The error I get is:
```
/usr/share/dotnet/sdk/2.0.0/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "/usr/share/dotnet/sdk/2.0.0/Roslyn/RunCsc.sh" exited with code 137. [/home/bakatsuki/NadekoBot/src/NadekoBot/NadekoBot.csproj]
    0 Warning(s)
    1 Error(s)
```

**Comment by samdivaio** [comment]
That error means you have low available memory, try checkin your RAM usage.

**Comment by SillyBirds** [comment]
Really? Weird, I've been running only those two bots on a 512MB digital ocean droplet with no issues for the last 6 months...

Does that mean 1.9 is hungrier on the memory side?

**Comment by xnaas** [comment]
@SillyBirds you closed it, but I'll assume redis is to blame. I imagine it has to use some amount of extra RAM. Don't quote me on that though. :P

**Comment by SillyBirds** [comment]
Well, the 2nd bot had to move to another server, so there was no point keeping this open if the memory usage was normal.
