### ISSUE TITLE
MacOs high sierra dotnet core crashing

### ISSUE THREAD

**Issue by Hibiki-The-Phoenix** [Kwoth/NadekoBot#1641]
`Dotnet installed.   
The specified SDK version [1.0.1] from global.json [/Users/x/NadekoBot/global.json] not found; install specified SDK version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:        
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409`

 macos high sierra, latest dotnet core.

**Comment by Gremagol** [comment]
If you're on Nadeko 1.9.X, you'll have to update your dotnet to 2.0.0.

**Comment by Gremagol** [comment]
I'm not experienced with mac, but are you sure you downloaded Nadeko 1.9? because it says:
`The specified SDK version [1.0.1] from global.json not found` 1.0.1 is for versions below 1.9.X iIrc.

**Comment by samdivaio** [comment]
check the dotnet info with `dotnet --info`

**Comment by SpeedBird95** [comment]
You need dotnet 1.0.1 for it to work with Nadeko. 2.0.0 gives problems in most unix environments.

**Comment by Hibiki-The-Phoenix** [comment]
downgrading back to 1.0.1 worked for me thanks!
