### ISSUE TITLE
Resetting Waifu list

### ISSUE THREAD

**Issue by SpeedBird95** [Kwoth/NadekoBot#1642]
There seems to be no command to purge the .waifus list.

Can it possibly be done through the config files ? I'm using the UNIX version.

**Comment by Kwoth** [comment]
You need to do a SQL query yourself on `src/NadekoBot/bin/release/netcoreapp2.0/data/NadekoBot.db`
```sql
DELETE FROM WaifuItem;
DELETE FROM WaifuUpdate;
DELETE FROM WaifuInfo;
```
