### ISSUE TITLE
Removing all currency from DB

### ISSUE THREAD

**Issue by SpeedBird95** [Kwoth/NadekoBot#1643]
I've recently purged all waifus from the DB with sqlite.
Now i would like to reset everyone's currency (flowers) to zero.

Is it safe to do

 DELETE FROM Currency;

for that to work ?

Would i also have to do the same for CurrencyTransactions?

**Comment by Kwoth** [comment]
I suggest you do it from currencytransactions too yeah. But you don't have to.
