### ISSUE TITLE
Latest 1.9 installation not working on Centos 7. 

### ISSUE THREAD

**Issue by borgqueenx** [Kwoth/NadekoBot#1644]
When starting the bot i get the following errors after installation:
https://puu.sh/xKnsF/f77f9aa279.png

And during installation i get ALOT errors.
https://puu.sh/xKoV2/eae0bf73b5.png

Using the installation from "readthedocs" everything is working fine.

I am running CentOS 7 64bit.

I'd like to add that all requirements (option 4) were installed successfully without error.

**Comment by SpeedBird95** [comment]
Gonna need to see more than that. Specifically the begging of the error

**Comment by borgqueenx** [comment]
I have re-installed all requirements without problems.

**Comment by Kwoth** [comment]
So, is this fixed?

**Comment by borgqueenx** [comment]
No, im afraid not. The dependancies/requirements install without errors(from option 4) but nadekobot installer (option 1) gives errors and with that it also starts with errors afterwards.
Both on a upgrade and a fresh installation.
If it helps i can make a screen capture video about it.

**Comment by samdivaio** [comment]
Check your dotnet version then install the bot on a new folder.

**Comment by samdivaio** [comment]
Check your dotnet version then install the bot on a new folder.

**Comment by samdivaio** [comment]
Check your dotnet version then install the bot on a new folder.

**Comment by borgqueenx** [comment]
@samdivaio Could you suggest how? I installed nadeko to the standard directory, even on a fresh install with no traces of nadeko left behind.

**Comment by borgqueenx** [comment]
The issue is fixed- yet brings up another issue with the installation i suppose. 
Nadeko option 4 installed dotnet 2.0 (or manual worked too) but did not use that version of dotnet. It instead used the old version of dotnet. I guess the installation needs to be updated (or the start script) to grab and use dotnet 2.0 instead of earlier versions.

I manually removed all of dotnet and forced nadeko to use 2.0 manually as well.
The pre-requirements and/or nadeko installation does not do that.

**Comment by samdivaio** [comment]
We have tested the upgrading of dotnet over various destros and it worked as supposed without needing to manually removing them but it could be random to machines as the errors you showed us above.
We'll go ahead and make the script to kill the process and remove the dotnet before upgrading it.
Thanks for your advice! 😄

**Comment by borgqueenx** [comment]
Then i suppose, that that will fix the issue. But i dont know since my issue is solved now and i hope i dont have to go through that again, hehe.
Thanks everyone!

**Comment by xnaas** [comment]
@borgqueenx you should close the issue. 😉

**Comment by SpeedBird95** [comment]
Before you close it , how did you force nedeko to use 2.0 ? I solved the issue by downgrading to 1.0.1.

**Comment by borgqueenx** [comment]
Downgrading nadekobot worked for me as well. Key to forcing nadeko to use 2.0 is completely wiping everything related to dotnet, then installing dotnet 2.0 again from microsoft. Then make sure the command line/executable "dotnet" is available and pointing to that dotnet installation folder.

**Comment by borgqueenx** [comment]
i have no idea how to close a issue xD.

**Comment by captainmedic** [comment]
I actually have the same issue on centos7. Can't seem to figure out why it wont work. It says it installs dotnet and then says it isnt installed

**Comment by SpeedBird95** [comment]
You have to manually install dotnet from the windows website
