### ISSUE TITLE
move youtube-dl

### ISSUE THREAD

**Issue by Tekyera** [Kwoth/NadekoBot#1645]
So, youtube-dl's path is C:\youtube-dl\youtube-dl.exe

How can I force the bot to use it from another place?

Thanks.

P.S. I need that to run 2 copies of bot. Because 1st copy of bot uses music well, but 2nd doesn't play music at all {song not found} even I use direct link. What can it be?

**Comment by GMR516** [comment]
I've never had any problems just putting Youtube-dl in the folder with Nadeko.

**Comment by Kwoth** [comment]
You can, but you have to update your PATH environment variable to point to the new folder, and restart your PC.
