### ISSUE TITLE
Project file does not exist project.json

### ISSUE THREAD

**Issue by okazakikun** [Kwoth/NadekoBot#1646]
So, going from version 1.3 to 1.9 followed the instructions on site, backed up all i need to, downloaded the 1.9 AIO, Auto-installed all prereq's, downloaded nadeko and ran it, got this error.

```
NadekoBot 1.9+
Mirai was here.
youtube-dl is up-to-date (2017.09.24)
Dotnet installed.
warn : The folder '/home/kyle/NadekoBot' does not contain a project to restore.
Couldn't find 'project.json' in current directory
Running NadekoBot. Please wait.
The current project is not valid because of the following errors:
/home/kyle/NadekoBot/src/NadekoBot(1,0): error DOTNET1017: Project file does not exist '/home/kyle/NadekoBot/src/NadekoBot/project.json'.
```

Was advised to update Dotnet-core, so updated to version 2.0, same error.

edit: Using debian 8.

**Comment by xnaas** [comment]
#1641 mentioned using dotnet 1.0.1? idk

**Comment by samdivaio** [comment]
Remove the dotnet preview you have installed, and install just the dotnet 2.0

**Comment by Kwoth** [comment]
What samvaio said.
