### ISSUE TITLE
Is there any way to change the help message?

### ISSUE THREAD

**Issue by Faoulon0224** [Kwoth/NadekoBot#1649]
hey, I host nadekobot off my personal computer, and I don't want my personal bot being invited to other servers. Is there a way to edit the help message so that it doesn't tell people the inv link? 

Thanks a bunch!

**Comment by sleepymanakete** [comment]
You can edit it with `.bce` or open the nadekobot.db. Go to browse data click on botconfig table. click on help string and remove the link. 
![image](https://user-images.githubusercontent.com/30272172/30998091-683b7016-a489-11e7-8116-3daf5b880171.png)

**Comment by Macley-Kun** [comment]
Or you just don’t check Public on the discord bot application page. Then only the owner(s) can add it to a server.
