### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by SmugCardboardBox** [Kwoth/NadekoBot#1651]
First time installing NadekoBot with the installer, I run Setup.exe and follow the guide from ReadtheDocs, but when I "Check for Updates" nothing happens, "Click here to update" is grayed out, won't let me click on it, I click on Run and it says to install/reinstall or run it through the desktop shortcut.

![screenshot_47](https://user-images.githubusercontent.com/32379718/30999089-c73113ac-a487-11e7-879a-8430a165db7a.png)

![screenshot_48](https://user-images.githubusercontent.com/32379718/30999103-dcde1e3e-a487-11e7-8134-e92147b63cd3.png)

I deleted every folder and file associated with NadekoBot and redownloaded the installer and it still does this to me. I've reset my PC several times and it still does this to me.

Any ideas why?

**Comment by Kwoth** [comment]
You need to remove her from programfiles/add or remove programs

**Comment by SmugCardboardBox** [comment]
![screenshot_50](https://user-images.githubusercontent.com/32379718/31008535-5a811e64-a4b9-11e7-8690-4921b4cd86e9.png)

NadekoBot file doesn't exist for me to uninstall... Yet it appears in my list of apps of features.

**Comment by Kwoth** [comment]
Well, yea, you removed uninstaller. Your registry still has Nadeko in there.

Delete `HKLM/SOFTWARE/Nadekobot` in your registry

**Comment by SmugCardboardBox** [comment]
Okay, that worked.

No idea how I managed to get this installation error in the first place, but it's been resolved.

Thank you.
