### ISSUE TITLE
Nadekobot installer (setup.exe) doesn't open. 

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#1652]
A person in #help had this issue

- Windows 10
- "my computer is insanely fast"
- tried downloading multiple times
- tried running as admin
- nothing shows up in task manager
- nothing detected by antivirus, nothing blocked by antivirus.

[Video](https://i.gyazo.com/fc817e479dd498f62c4cb5ec20340425.mp4)
*throws another* [*link*](https://i.gyazo.com/ec9d717d8bc17ffa9be1555e139c54c4.mp4)

**Comment by Jengas** [comment]
Same problem. PS Windows Server 2016

**Comment by xnaas** [comment]
Can't see the taskbar or if there's another monitor, but I wonder if we don't see that SmartScreen or some other dumb Windows thing is being triggered?

**Comment by xnaas** [comment]
@Jengas' issue: #1648

**Comment by Kwoth** [comment]
Tracking this in #1648
