### ISSUE TITLE
Won't start after update to 1.9

### ISSUE THREAD

**Issue by Friend8718** [Kwoth/NadekoBot#1653]
Tried to update to 1.9 after noticing the bot wasn't working with nested channels. Ran prereqs, installed to a new folder, but I keep getting this error when I try to start the bot:
NadekoBot 1.9+
Mirai was here.
youtube-dl is up-to-date (2017.09.24)
Dotnet installed.
warn : The folder '/root/NadekoBot' does not contain a project to restore.
Couldn't find 'project.json' in current directory
Running NadekoBot. Please wait.
The current project is not valid because of the following errors:
/root/NadekoBot/src/NadekoBot(1,0): error DOTNET1017: Project file does not exist '/root/NadekoBot/src/NadekoBot/project.json'.

My installed dotnet packages are:
dotnet-host/jessie,now 2.0.0-1 amd64 [installed,automatic]
dotnet-hostfxr-2.0.0/jessie,now 2.0.0-1 amd64 [installed,automatic]
dotnet-runtime-2.0.0/jessie,now 2.0.0-1 amd64 [installed,automatic]
dotnet-sdk-2.0.0/jessie,now 2.0.0-1 amd64 [installed]

Any help would be greatly appreciated.

**Comment by Kwoth** [comment]
Completely delete all dotnet version of you have installed.

Make sure command doesn't exist when you do `dotnet -v`

Then reinstall it using this link https://www.microsoft.com/net/core#linuxdebian

**Comment by Friend8718** [comment]
Upon further investigation, it does look like the dotnet command still works even after uninstalling the packages. Looks like it says the version is 1.0.0-preview2-1-003177. I can't seem to find where it is. Already went through my full package list. Is there an easy way to locate it?

**Comment by Friend8718** [comment]
Looks like there was a preview version of dotnet hiding on the system. Took me a while to find it, but seems to be working now after deleting that. Thanks
