### ISSUE TITLE
Bot does not see users in server

### ISSUE THREAD

**Issue by IngenicHacks** [Kwoth/NadekoBot#1656]
After a recent discord update, the bot no longer sees users in one of my servers. All the rest of the servers are fine, but no one in the effected server can use any commands. The `.listservers`command shows that the bot is in the server, but sees no members. 
![screenshot from 2017-09-29 10-32-49](https://user-images.githubusercontent.com/27877969/31022001-859ed32e-a505-11e7-801e-97593e4ed7fe.png)

**Comment by Macley-Kun** [comment]
Wich version are you on?

**Comment by IngenicHacks** [comment]
I've tried both the current stable and the dev builds, both have this same issue

**Comment by Kwoth** [comment]
You're using the old installer. Update your bot to 1.9+

If you're on linux you need to use this link

first, backup your current installation just in case

`cd ~ && wget -N https://github.com/Kwoth/NadekoBot-BashScript/raw/1.9/linuxAIO.sh && bash linuxAIO.sh`


1. Reinstall prerequisites (4th option)
2. Download nadeko (first option)
3. Run nadeko
