### ISSUE TITLE
Shop command shows an extra empty page

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#1657]
![1](http://midorina.ga/u/bf1d4b.png)
![2](http://midorina.ga/u/caeab1.png)
Version 1.10.1

**Comment by Macley-Kun** [comment]
Intresting, i have the same with .feedlist!

![schermafbeelding 2017-09-29 om 19 32 00](https://user-images.githubusercontent.com/26381427/31028098-fee34f98-a54c-11e7-8f4d-f179adf73a2d.png)

**Comment by Kwoth** [comment]
:notlikemiyo:

**Comment by Kwoth** [comment]
Fixed in 2.0
