### ISSUE TITLE
xpadd  and  clubaccept  commands don't work if the prefix is changed

### ISSUE THREAD

**Issue by Chachica** [Kwoth/NadekoBot#1658]
As the title says.  The commands  `xpadd`  and `clubaccept`  do not work if you change the prefix of the command from a dot.

**Comment by xnaas** [comment]
Other than `xp` still being the slowest god damn command known to man, `xpadd` works for me with the prefix changed:

![img](https://i.imgur.com/0UluKer.png)

Note: I already had 500 on me.

Didn't feel like testing `clubaccept` but I'm sure it works as well. I'm guessing you have some other issue.
