### ISSUE TITLE
NadekoBot Updater not launching

### ISSUE THREAD

**Issue by Jengas** [Kwoth/NadekoBot#1663]
Finally after few hours of trying to get some logs, i got it by deleting in programs "Nadeko Updater". Developers, please help me out.
P.S Windows Server 2016

Screen Shot - http://prntscr.com/grplec
Logs - https://pastebin.com/sE4aNfnb

P.S.S Even if it will be downloaded, it still not launching

**Comment by Kwoth** [comment]
Try running it as admin. Something is blocking your access to that website.

**Comment by Jengas** [comment]
Same error

**Comment by Kwoth** [comment]
Something is blocking your app, or access to that website. Could be your antivirus, could be your server settings. Could be bitdefender.

Updater is working fine for the most people.

**Comment by Jengas** [comment]
Website works. http://prntscr.com/grud5t
Antivirus off. http://prntscr.com/grudpi
No bitdefender.
Which server settings?

**Comment by Kwoth** [comment]
I would say google the error you've got

`URLDownloadToCacheFile failed with HRESULT '-2146697208'`

**Comment by xnaas** [comment]
Is this a dupe of #1648? 🤔
