### ISSUE TITLE
Redis Server error (latest build, linux)

### ISSUE THREAD

**Issue by BtheDestroyer** [Kwoth/NadekoBot#1664]
![Image](https://puu.sh/xMZAt/cbf0b40092.png)

I can't seem to find a solution. I tried in Windows 10 (got the same issue) and Ubuntu on Windows 10 from the Windows Store (screenshot above). I haven't yet tried in Linux Mint or an external server because I want to make sure it works first.

**Comment by sleepymanakete** [comment]
did you download redis? there's a windows port for it

**Comment by anigatari** [comment]
it doesn't seem like you have redis installed inyour machine.

**Comment by Kwoth** [comment]
`apt-get install redis`

**Comment by samdivaio** [comment]
`systemctl` (re)start `redis-server.service`

**Comment by BtheDestroyer** [comment]
![more errors](https://puu.sh/xO0jw/e91187730e.png)

I ended up using `service redis-server restart` and am testing it right now. Will report back.
