### ISSUE TITLE
Logging Bug

### ISSUE THREAD

**Issue by Devaliah** [Kwoth/NadekoBot#1667]
Logging seems to have broken again with the latest update. Toggling a log event has an improper confirmation. When toggling an event **off**, it still replies with "Logging **Name** event in this channel." even tho you successfully turned the event off.

**Comment by Gremagol** [comment]
Can't Verify, working fine for me
![logs](https://user-images.githubusercontent.com/24619854/31057572-429cfaf6-a6e5-11e7-9baa-61ddfeb5a196.PNG)

**Comment by Kwoth** [comment]
Same here, works for me. Make sure you've updated your bot.

**Comment by anonymasen** [comment]
Happens for me too. Kwoth please reopen this issue!

**Comment by samdivaio** [comment]
Can confirm, happening with 1.10.2

**Comment by Kwoth** [comment]
Fixed in 2.0
