### ISSUE TITLE
Fresh install, build failed.

### ISSUE THREAD

**Issue by Beaupedia** [Kwoth/NadekoBot#1668]
CentOS Linux release 7.4.1708 x64

Modules/Administration/LogCommands.cs(127,118): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(127,118): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(127,119): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(130,130): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(130,130): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(130,131): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(133,130): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(133,130): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(133,131): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(136,122): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(136,122): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(136,123): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(139,118): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(139,118): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(139,119): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(142,122): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(142,122): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(142,123): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(145,126): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(145,126): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(145,127): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(148,124): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(148,124): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(148,125): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(151,120): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(151,120): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(151,121): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(154,130): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(154,130): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(154,131): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(157,134): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(157,134): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(157,135): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(160,130): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(160,130): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(160,131): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(163,132): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(163,132): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(163,133): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(166,134): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(166,134): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(166,135): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(169,140): error CS1003: Syntax error, '(' expected [/home/servic                                                             es/NadekoBot/src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(169,140): error CS1031: Type expected [/home/services/NadekoBot/                                                             src/NadekoBot/NadekoBot.csproj]
Modules/Administration/LogCommands.cs(169,141): error CS1026: ) expected [/home/services/NadekoBot/src                                                             /NadekoBot/NadekoBot.csproj]

The build failed. Please fix the build errors and run again.
Done

Welcome back to NadekoBot.
Welcome to NadekoBot.

**Comment by Kwoth** [comment]
Completely remove `dotnet` from your machine (make sure it's completely removed by typing `dotnet -v`, and then:

`cd ~ && wget -N https://github.com/Kwoth/NadekoBot-BashScript/raw/1.9/linuxAIO.sh && bash linuxAIO.sh`


1. Reinstall prerequisites (fourth option)
2. Download nadeko (first option)
3. Run nadeko

**Comment by Beaupedia** [comment]
Thanks. Going a little bit crazy trying to figure out how to remove dotnet. I'm on CentOS and have googled this and come up without a working option.

**Comment by Beaupedia** [comment]
That resolved it, thanks.
