### ISSUE TITLE
Question: What drives up the value of a "waifu" ?

### ISSUE THREAD

**Issue by SpeedBird95** [Kwoth/NadekoBot#1669]
Had alot of questions on my server that's using Nadeko.
What is it that drives up a particular persons "value" , when trying to .claim them?
Can you disclose the formula ?

Thanks for the ongoing support.

**Comment by Kwoth** [comment]
✔️ smart
✔️ nice personality
✔️ pretty
✔️ loli

Other attributes may differ according to taste, but these ones are objective, and are crucial for a top-quality expensive waifu :^)

**Comment by SpeedBird95** [comment]
:*)
