### ISSUE TITLE
Disabling NSFW/NSFL

### ISSUE THREAD

**Issue by Dog2puppy** [Kwoth/NadekoBot#167]
Hello, I want to disable NSFW/NSFL. The reason is because I find the content disgusting. And it bothers me. I don't think anyone in my server likes NSFW/NSFL but I just want it disabled in-case. 

Thanks
~Dog2puppy

**Comment by appelemac** [comment]
Easily done: `;sm NSFW enable`. NSFW being disabled by default is being worked on

**Comment by Dog2puppy** [comment]
Okay. Do I run that as a command in the chat or put it in a configuration file?

**Comment by appelemac** [comment]
Command in the chat; If you have problems, join the Discord chat in the Readme.

**Comment by Kwoth** [comment]
Just to add: NSFW is disabled by default on new servers nadeko joins for at least 1 or 2 weeks now.
