### ISSUE TITLE
Music not working properly on Debian 8

### ISSUE THREAD

**Issue by Tchy258** [Kwoth/NadekoBot#1670]
I never tried using music before, today I tried and only heard random noises, the song itself didn't matter.
Already tried changing Discord server location, voice channel bitrate to no avail.
Also tried rebooting the VPS my NadekoBot is being hosted on and had no changes.
Redownloaded prerequisites, redownloaded NadekoBot and still only noise.
Console log shows no errors.

**Comment by No-WiFi** [comment]
Second that, it would sound like you're scraping metal against another metal surface, just that annoying squeaking/scraping noise

**Comment by Macley-Kun** [comment]
Can you confirm it's because of Debian 8? Maybe it's because the connection from your VPS to discord isn't stable/sufficient?

**Comment by Kwoth** [comment]
Uh this happened before, are you 100% sure you have the correct version of ffmpeg? (3.3+)

@samdivaio do you maybe know of the issue where we resolved this?

**Comment by samdivaio** [comment]
We used docker to fix music issues on debian. 🤔

**Comment by No-WiFi** [comment]
Unsure on top of my head, I think both of us simply used the Bot installer to download the necessary prereqs like ffmpeg that came with it. So the version should be the one supplied by the installer.

**Comment by Tchy258** [comment]
Seems to be the ffmpeg version, tried removing and reinstalling it with apt-get and I'm getting ffmpeg 3.2...
I'll try installing docker

**Comment by samdivaio** [comment]
Just use docker on it or switch os to Ubuntu

**Comment by Tchy258** [comment]
Switched OS to ubuntu and now it works completely fine

**Comment by Kwoth** [comment]
Could have something to do with opus or sodium... Maybe it's 32bit, i really don't know. If someone else is reading this in the future, try compiling libopus and libsodium yourself, and replacing the existing ones in the output folder after building the bot.
