### ISSUE TITLE
Nadeko Bot crashing on startup after update

### ISSUE THREAD

**Issue by Saven17** [Kwoth/NadekoBot#1674]
There are several others with this problem and a few others where the case is closed but not answered. 
![1222111](https://user-images.githubusercontent.com/14907842/31072280-4822564c-a735-11e7-87c6-6db37404f7f8.png)

Please help.

Thank you for your time.

P.S. Windows 10

**Comment by Kwoth** [comment]
In the updater, click "install redis" (new button all the way at the bottom)
