### ISSUE TITLE
.convertlist is broken

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#1676]
![1](http://midorina.ga/u/4bedd9.png)
![2](http://midorina.ga/u/6cabcd.png)

**Comment by Midoriin** [comment]
I have this issue on both 1.10.1 and 1.10.2 versions, and I host the bot on Linux. But someone claims that his clone on Windows and he does not seem to have this issue. 
![1](https://cdn.discordapp.com/attachments/117523346618318850/364442476959760386/unknown.png)

**Comment by Kwoth** [comment]
Works for me, try restarting your bot. or running `DELETE FROM ConverterUnits` and restarting your bot.

**Comment by samdivaio** [comment]
Open your `NadekoBot.db` with DB Browser, go to the tab **Execute SQL**, paste the command `DELETE FROM ConversionUnits`  on SQL 1 field and press F5 and then write changes. Done.

**Comment by Midoriin** [comment]
That solved my problem. Thanks a lot to both of you ^^
