### ISSUE TITLE
Global custom reaction "%mention% pat" has incomplete json

### ISSUE THREAD

**Issue by Shenkenstein** [Kwoth/NadekoBot#1679]
in particular, this response

```
      {
        "id": 211898,
        "text": "{\"plaintext\":\"%target%\",\"image\":\"https://cdn.discordapp.com/attachments/294812503719018500/350183424381812736/Blonde_Pat.gif%22,%22color%22:7118787%7D"
      }
```
I don't know about the proper formatting myself, but just comparing it to the ones above it, I think it's missing a close bracket before the end quotes.

![image](https://user-images.githubusercontent.com/24500138/31149572-5f6f0906-a85e-11e7-9b48-053a30778c8a.png)

**Comment by Kwoth** [comment]
fixed
