### ISSUE TITLE
Crashing immediately after running it

### ISSUE THREAD

**Issue by Apollo72** [Kwoth/NadekoBot#1689]
![help](https://user-images.githubusercontent.com/32556141/31254810-cd325e4c-a9ef-11e7-8872-0352ded8692b.PNG)

**Comment by GMR516** [comment]
https://github.com/Kwoth/NadekoBot/issues/1677
https://github.com/Kwoth/NadekoBot/issues/1686

**Comment by MaybeGoogle** [comment]
if ur on windows go to [nadekolog support discord](https://discord.gg/0ehQwTK2RBjAxzEY), and the first pin in #help channel is the solution. 

Pretty much, you need to get the new updater and install redis.
