### ISSUE TITLE
Steel/Fairy type

### ISSUE THREAD

**Issue by Sairys** [Kwoth/NadekoBot#169]
Looks like numtype in steeltype.cs is set to -1 and not giving any moves at the moment (should be 16?)

Also Fairy type isn't in at the moment, we've added it in on the version we're running one our server (along with removing nadekoflowers) so I've attached the changes we made if that makes it easier.
[Pokemon.zip](https://github.com/Kwoth/NadekoBot/files/199436/Pokemon.zip)

**Comment by Kwoth** [comment]
Can you make a PR that fixes fairy type?

**Comment by appelemac** [comment]
@Kwoth ain't no fixing; it be ADDING
