### ISSUE TITLE
Having Issues launching...

### ISSUE THREAD

**Issue by Yu-Narukami** [Kwoth/NadekoBot#1691]
![nadeko issue](https://user-images.githubusercontent.com/32586595/31304384-e2fb5d88-aad4-11e7-8c4d-fa742c11917c.png)
I'm no doubt just being stupid but I keep having issues when launching the bot.

**Comment by sleepymanakete** [comment]
Download redis from the updater.

**Comment by Yu-Narukami** [comment]
Yep, definitely, me being stupid. Thank you for the help.
