### ISSUE TITLE
credential.json seems not working, help!

### ISSUE THREAD

**Issue by wonderstruck12** [Kwoth/NadekoBot#1693]
this is what credential.json looks like to me.. Im so new with this, what's wrong?
{
  "ClientId": 123123123,
  "Token": "",
  "OwnerIds": [
    0
  ],
  "LoLApiKey": "",
  "GoogleApiKey": "",
  "MashapeKey": "",
  "OsuApiKey": "",
  "SoundCloudClientId": "",
  "CleverbotApiKey": "",
  "CarbonKey": "",
  "Db": {
    "Type": "sqlite",
    "ConnectionString": "Data Source=data/NadekoBot.db"
  },
  "TotalShards": 1,
  "PatreonAccessToken": "",
  "PatreonCampaignId": "334038",
  "RestartCommand": null,
  "ShardRunCommand": "",
  "ShardRunArguments": "",
  "ShardRunPort": null
}

**Comment by shivaco** [comment]
Follow [this](http://nadekobot.readthedocs.io/en/latest/JSON%20Explanations/) guide

**Comment by wonderstruck12** [comment]
hmmm, but I see the credentials.json I got nothing to rename...

**Comment by wonderstruck12** [comment]
![2](https://user-images.githubusercontent.com/32589222/31305809-b1aed1d8-ab74-11e7-8a70-c64be64f3658.JPG)

**Comment by wonderstruck12** [comment]
oh I get it now
