### ISSUE TITLE
no owner channel created, said in NADEKOBOT.EXE 

### ISSUE THREAD

**Issue by wonderstruck12** [Kwoth/NadekoBot#1694]
![qwdewe](https://user-images.githubusercontent.com/32589222/31306387-a85eed72-ab81-11e7-96c5-8008fd78b970.JPG)

**Comment by shivaco** [comment]
Update your bot.
Make sure your `Ownerid` in credentials.json is right.

**Comment by Kwoth** [comment]
Or unblock your DMs for people who are not in your friends list, and make sure your bot is invited to one of the servers you're on.
