### ISSUE TITLE
Left server unmuted, came back muted.

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#1696]
One case, public nadeko.

The person says he has been muted in that server before. 

But in two tests, he left the server unmuted, joined back, and was muted using nadeko-mute automatically and instantly (shown in audit logs but no message sent in channel)

UserID is 184831853096730634 if you want to check in the db or something

**Comment by MaybeGoogle** [comment]
Btw yay i got my discord discrim for the issue number!

**Comment by MaybeGoogle** [comment]
Also if you want to join the server and take a look, DM Google#1696 for server invite

**Comment by Kwoth** [comment]
Did you try using mute and then unmute command on him again?

**Comment by MaybeGoogle** [comment]
Yea, doing that worked. Is this a common issue? 

Is it because he left as a muted user before, and then manually got mute role removed? 

Answer pls and close.

**Comment by Kwoth** [comment]
Yea he probably left as muted.
