### ISSUE TITLE
Feeds not supporting atom?

### ISSUE THREAD

**Issue by Brramble** [Kwoth/NadekoBot#1697]
When I use the URL: https://github.com/Kwoth/NadekoBot/commits/1.9.atom It says the following in the screenshot. 

![alt text](https://i.imgur.com/rp92jM9.png)

Im not sure if I am doing something wrong but what will Nadeko support on the feeds? Also how will I else be able to make a feed for 1.9 commits. When also using https://www.reddit.com/wiki/rss. Them feeds will not work either.

**Comment by Brramble** [comment]
#1628 Just found this

**Comment by Kwoth** [comment]
yes, we're tracking this there
