### ISSUE TITLE
Dissable features

### ISSUE THREAD

**Issue by MirrorsEgg** [Kwoth/NadekoBot#17]
hei there,

so we have your bot in our community and it has some inapporpriate features such as the hentai search function. I was wondering if its possible to dissable those features somehow as a server admin / owner even if you dont own the bot f.e. through roles f.e. that you create a role f.e. NSFW that signalizes the bot that its allowed to enable those commands or not. 

would love to hear a fast solution / reply 
MirrorsEgg

**Comment by Kwoth** [comment]
Hello,
Glad to hear that you are using the bot!
I appreciate your concerns regarding inappropriate features of the bot. The solution is planned and its basic version **should** be implemented within 36 hours.
That being said, keep in mind that disabling hentai and other "inappropriate" features will not stop users linking similar material manually or through the regular search (~ir, ~i) functions. The bot should not be held responsible or at fault, but the users who are invoking those commands.  

The bot is there only to provide convenience.

**Comment by MirrorsEgg** [comment]
Hei Kwoth,

Thank you for the quick reply! Didnt expect such a fast reply. We just implemented bots into our community and so far things sre going well. The Bots wont be taken as responsible for what users do with them, thats obviously the users mistake for bringing up inappropriate features. Im really happy that this feature will be implemented soon, cant wait for it :P 
Maybe the bot will make it as our "main chat bot" though that depends on the configurability. Is there something like a permission system planned too? F.e. That you give those who should be able to use the bot certain ranks?

Have a nice day
MirrorsEgg

**Comment by cuken** [comment]
MirrorsEgg,

Just submitted the initial pull request to get this feature going, the Permissions system is looking really good already. Worked with Kwoth tonight and things are looking promising!

Cuken

**Comment by MirrorsEgg** [comment]
Awesome guys :) im crazy happy that you guys are so energetic on this :D your bot is amazing and im sure it'll find a great place in our big comunity :D

**Comment by Kwoth** [comment]
New release with permission system is coming in ~8 hours

**Comment by towicode** [comment]
Will you be giving examples of the permissions actions in the readme? I'm assuming that the new permissions will for example give me the ability to limit users ability to change volume and stuff, but I'm confused on how to use it.

**Comment by Kwoth** [comment]
It was out last night, you can type -h to see help. It has some problems atm, I will fix them within an hour, but basicaly atm you must have "Nadeko" role in order to change permissions.

After the fix you will be able to change the required role, and server owner won't need a role to change the permissions.
