### ISSUE TITLE
Pokegame type rolling

### ISSUE THREAD

**Issue by Sairys** [Kwoth/NadekoBot#170]
Having a look at the getpoketype code it looks like some uids are resulting in a negative result from the modulus due to the typing here:

`            int remainder = (int)id % 16;`

changing it to 

```
            ulong remainder = id % 16;
            int result = (int)remainder;
```

seems to have fixed it up.

**Comment by Kwoth** [comment]
I'm sorry, it wasn't me who implemented new pokemon. When i get time ill rewrite it all.

**Comment by Sairys** [comment]
No worries, we were poking around cause a few people didn't get responses and found it. :)
