### ISSUE TITLE
NadekoBot isn't reponding to any commands.

### ISSUE THREAD

**Issue by crimsonanex** [Kwoth/NadekoBot#1700]
Hi guys, Since last Saturday, 10/7, around 4'ish PM EST, the Nadeko bot stopped responding to commands. The permissions are good (even tested with full admin permissions) and the bot appears online. However, none of the server commands or custom reactions are working - nothing happens.

Any thoughts? How can I find out what's blocking/preventing it from working?

**Comment by Macley-Kun** [comment]
Well, have you checked your database file?
Maybe try: `.lcr`
If you don't see anything of custom reactions, i assume it's not present in the bot anymore?

**Comment by shivaco** [comment]
If you are using public Nadeko, you have nothing to do. Some shards are down, and if Nadeko doesn't respond, that means your server is on the shard that is down at the moment.

**Comment by Kwoth** [comment]
Shard 29 is being restarted, try again in 5 minutes.

If that doesn't work, try `.resetperms` and then `.stats`, maybe you just blocked the bot using the permissions system.

**Comment by crimsonanex** [comment]
Resolved. Thanks guys. Really appreciate it. Close away ;)

**Comment by Macley-Kun** [comment]
@crimsonanex why don't you hit close here in the bottom right yourself? :)
