### ISSUE TITLE
Invites still being filtered even though filtering is turned off

### ISSUE THREAD

**Issue by Bread2k** [Kwoth/NadekoBot#1701]
Both server filtering and channel filtering is turned off for specific channels, but invite links still get filtered unless sent by the bot owner.... kind of. There are 3 bot owners in the credentials file, but only one doesn't get invites filtered as well.

**Comment by Macley-Kun** [comment]
Check if you use the correct format/id's for the bot owners. That should normally never happen.
I would turn on the filters that work now, and try to disable them again. I suggest you take screen pictures to show us what's going on.

**Comment by Kwoth** [comment]
Must be some other bot, I will reopen if you provide proof with no other bots in the server. Seems highly unlikely
