### ISSUE TITLE
Nedeko bug

### ISSUE THREAD

**Issue by lagfare** [Kwoth/NadekoBot#1702]
I just donated and claimed my 🌸 After I head over to play coin flip on this discord https://discord.gg/kDKVbJ I .bf 20 t it didn't show anything then I .$ and it showed it took the 20🌸 But then I .flip to see if it was working and it flipped t so then I was like cool with working now so I .bf 50 and nothing showed up again .$ worked and it showed again that I listed the 50🌸 And . Flip works but when I input .bf it just takes my 🌸 Please help
![img_1124](https://user-images.githubusercontent.com/32677750/31392170-91bf2dd0-ada6-11e7-920f-d0150dd56fd5.PNG)
![img_1125](https://user-images.githubusercontent.com/32677750/31392171-91ddcdb2-ada6-11e7-81bb-0d1375725adf.PNG)
![img_1126](https://user-images.githubusercontent.com/32677750/31392172-91f56c74-ada6-11e7-82ef-66cdba51a335.PNG)

**Comment by Kwoth** [comment]
Seems like the message just got 502'd 2 times in a row and you lost both times. Sometimes bot can't send the message, you will notice sometimes you'll get more money even when both doesn't reply anything (but people usually don't complain about that :) )
