### ISSUE TITLE
Failed to initialize

### ISSUE THREAD

**Issue by FrostsFox** [Kwoth/NadekoBot#1703]
Upon starting the bot It showed this message (see picture), and this message only, and then proceded to close tthe launcher. What can I do to fix this?
![screenshot_1](https://user-images.githubusercontent.com/32679664/31395720-59c30cac-add9-11e7-8e07-da28da5414e1.png)

**Comment by Kwoth** [comment]
which os?

**Comment by FrostsFox** [comment]
os?

**Comment by Kwoth** [comment]
What's your operating system. Tell me everything you know about the server/PC you're trying to run your bot at.

**Comment by FrostsFox** [comment]
okay I have windows 10

**Comment by FrostsFox** [comment]
the server is in us central, while I'm situated in eu west

**Comment by Macley-Kun** [comment]
@FrostsFox wich company your hosting it on?

**Comment by Kwoth** [comment]
Remove everything, go through the guide carefully again, if it doesn't work, google the error you're getting because it's something related to dotnet core, not the bot itself.
