### ISSUE TITLE
static types cannot be usd as

### ISSUE THREAD

**Issue by BaronVonAnime** [Kwoth/NadekoBot#1704]
So, just started Nadeko and got an error, reinstal didn't fixed it.
I was able to use Nadeko before without any problems and i didn't changed anything.
os: Win10
![ss 2017-10-10 at 10 51 55](https://user-images.githubusercontent.com/23082662/31410114-3fe8760c-ae0e-11e7-8a14-cf10e0ce6b4e.png)

**Comment by Kwoth** [comment]
Update your bot to 1.9+

If you're on linux you need to use this link

first, backup your current installation just in case

`cd ~ && wget -N https://github.com/Kwoth/NadekoBot-BashScript/raw/1.9/linuxAIO.sh && bash linuxAIO.sh`


1. Reinstall prerequisites
2. Download nadeko (first option)
3. Run nadeko

**Comment by BaronVonAnime** [comment]
( Not sure what i'm supposed to do with an Linux link on a win10 🤔 )
Just noticed that here ( https://nadekobot.readthedocs.io/en/latest/guides/Windows%20Guide/ ) is an Updater wich i just used, now the problem is this https://puu.sh/xV0jM/da58d8f91d.png

So, starting the bot wie shortcut on desktop as Admin, then after the text shows up in the console the "stopped working" window pops out.

**Comment by Kwoth** [comment]
Press Install redis button in the launcher

**Comment by BaronVonAnime** [comment]
Everything working fine now, thanks
