### ISSUE TITLE
Public Nadeko Bot appears to be offline in a few of my servers

### ISSUE THREAD

**Issue by crimsonanex** [Kwoth/NadekoBot#1707]
Noticed the public nadeko bot in 3 of my discord servers stopped working a couple hours ago - a 4th looks fine though. I'm guessing a node is down / needs the handle jiggled?

**Comment by Kwoth** [comment]
yup, 2 shards are dead, everything should work now?

**Comment by crimsonanex** [comment]
Looks good. Thanks for the quick turn around Kwoth!
