### ISSUE TITLE
Nadeko randomly goes offline- shard 0 is in disconnected state

### ISSUE THREAD

**Issue by borgqueenx** [Kwoth/NadekoBot#1708]
Here is a screenshot, i don't know what else to make of this:
https://cdn.discordapp.com/attachments/117523346618318850/367620996250730497/image.png

A restart of nadeko through ssh fixes the problem quite fast, but since i am(and will be) the only administrator accessing the bot, there are sometimes periods of time when i am not there to immediatly restart the bot.

Is there any cause or fix to this? Help would be great!

**Comment by ibigfire** [comment]
I also get this issue, as evidenced here: https://i.imgur.com/QaBDq2y.png

Near I've been able to figure, if there's any sort of connection blip Nadeko just starts spamming that error message, instead of trying to reconnect.  So even once a connection is back and fully available again, the error will continue.

That's the best I can figure anyway.  If I've got it figured right so far, which I may or may not have done, then I think the behavior should be changed so that the bot starts trying to reconnect instead, like, try to reconnect once every minute or something if it loses connection.

**Comment by xnaas** [comment]
I was hosting a bot for someone for awhile and they never used it. That would happen after the bot was idle for days with no interaction. This problem never occurs on my main bot I host myself where it's constantly in use.

**Comment by bizmar** [comment]
Same happens to me, two instances one hosted on a home windows PC and one hosted on EC2 Ubuntu. Both are actively used, both have that error every few hours. Sucks because it disrupts the music, and has to be manually restarted every time.

**Comment by borgqueenx** [comment]
Im glad i’m not the only one. The question is now, is this a bug or feature request since maybe nadeko is not meant to attempt to reconnect?

**Comment by borgqueenx** [comment]
It would be weird though if this is intentional. But i suppose this does not longer fall under the “question” tag.

**Comment by shikhir-arora** [comment]
See my comment here - https://github.com/Kwoth/NadekoBot/issues/1680

The guide I posted is for Linux hosters. 

https://gist.github.com/shikhir-arora/b1ec4820e3299c255e4f97dcfdf99d87

**Comment by borgqueenx** [comment]
That is not an answer to our issue. It is not the VPS going down, its nadeko somehow going down and not reconnecting. I am already running nadekobot using a systemd service file that automaticly starts the bot.

Furthermore to verify that its not my VPS, i can connect fine to my websites running on the VPS or ssh into the vps and reboot the system file that automaticly reboots nadeko. Then nadeko will work fine again. But i rather have nadeko attempt to reconnect itself. I am not sure that, if this error we report is a bug, or rather a feature request that is needed, to make the bot automaticly reconnect in case it returns this message.

**Comment by MaybeGoogle** [comment]
Same error, this person says that Nadeko has been doing the shard disconnect thing for 2 weeks (estimate). Windows 8.0, bot is in 3 servers, NadekoBot v1.10.2.

**Comment by bizmar** [comment]
Two weeks sounds about right. Here's a cpu usage graph slowly rising, it may not be relevant, but looks suspicious to me.
<img width="428" alt="screenshot 2017-10-14 23 53 28" src="https://user-images.githubusercontent.com/4053708/31579719-625eae00-b13c-11e7-9fd9-e02d1b518dfd.png">

**Comment by GMR516** [comment]
Happened to me for the first time the other day. A little more than 2 weeks ish maybe for me? Dunno. Maybe once it detects that error it should try an auto-reconnect or something.

**Comment by Kwoth** [comment]
It usually happens when discord dies for a while, and the shard can't reconnect.

**Comment by GMR516** [comment]
Any way to establish a reconnecting system?

**Comment by borgqueenx** [comment]
Yeah a system that makes nadeko attempt to reconnect would be great!

**Comment by GMR516** [comment]
Once every minute or so would be fine.

**Comment by Macley-Kun** [comment]
So is this solved now 🤔 ? Or do we need to investigate this furthermore?

**Comment by borgqueenx** [comment]
no @Macley-Kun... It is not fixed at all, unless i missed a new version that rolled out. And then it would require 2-4 weeks of testing before we know if its fixed.

**Comment by MaybeGoogle** [comment]
The issue appears to be solved for me... it hasnt happened in a while. Can other people confirm, or is it still a problem? @borgqueenx nadekobot v2.0.2 is latest iirc

**Comment by borgqueenx** [comment]
ah i didn't note the new version of yesterday. time will have to tell if this issue is fixed.

**Comment by Kwoth** [comment]
I'm working on making the shardcoordinator autorestart shards when they go down.

**Comment by borgqueenx** [comment]
Awesome kwoth! :D

**Comment by Kwoth** [comment]
Should be done in the latest 2.1.0 update

**Comment by Demon1986** [comment]
still happens if discord has outages, and manual restart shouldnt be required. perhaps allow one to restart it from the shell/cmd however the user runs it.
