### ISSUE TITLE
Unable to use NadekoBot

### ISSUE THREAD

**Issue by Owie963** [Kwoth/NadekoBot#1713]
Hi, I recently downloaded NadekoBot and I have problems running it. Though I followed the instructions, when running NadekoBot.exe, I get the message
SelfService | No owner channels created! Make sure you've specified correct OwnerId in the credentials.json file
I have my all the IDs entered correctly in the credentials.json file and so I'm not sure how to fix this.

**Comment by Macley-Kun** [comment]
@Owie963 did you first invited the bot into your server?
Example how you should've made the OwnerIds:
```"OwnerIds": [
    177445849952026625
  ],```

Double check that your ID is correctly in the .json :-)

**Comment by Owie963** [comment]
Yep, I invited the bot into my server, using the link in the guide with my client ID. And my OwnerId in the credentials.json are like this:

  "OwnerIds": [
    208923842020769793
  ],

I also double checked that it is correct.

**Comment by Macley-Kun** [comment]
Mhm strange, the fault is really in your .json Everything else is also correctly in your eyes?

**Comment by shivaco** [comment]
Can you type `.stats` and send a screenshot of the response from Nadeko?

**Comment by Owie963** [comment]
Everything should be correct.
![credentials](https://user-images.githubusercontent.com/32614482/31549913-296610aa-b062-11e7-8813-80bd4e58c1c2.png)

I get no response from the bot when I type that or any other commands.

**Comment by shivaco** [comment]
Download the new installer from [here](http://dl.nadekobot.me/), install all prerequisites needed (check the left bottom corner), setup credentials.json file, restart your PC, try running the bot and see if bot responds.

**Comment by Owie963** [comment]
Thanks so much! I think it might have been because I did not install Redis. The bot is working fine now.
