### ISSUE TITLE
.warn can be used by anyone with ban perms to ban anybody from the server, even admins.

### ISSUE THREAD

**Issue by sirneversleep** [Kwoth/NadekoBot#1715]
The way the bot is written allows anybody with ban permission to use .warn to ban anyone from a server, regardless of their position in the role order. This means literallly a low level moderator can ban a high ranking admin, as long as the admin isnt the owner. 

For example, a moderator could wait until the server owner is away and then just warn ban anybody else with power to do anything and then they could do serious damage to a server

**Comment by Kwoth** [comment]
Fixed in 2.0
