### ISSUE TITLE
Music doesn't sound, but it seems to work properly.

### ISSUE THREAD

**Issue by DavidGarciaOriol** [Kwoth/NadekoBot#1717]
Both, shard and discord says that when I execute .yq command with link or .play command, it starts playing without any problems, but music itself actually doesn't sound, isn't a volume problem, I reinstalled ffmpeg, YT-dl and actually I even reinstalled the bot, but still not working properly, it says that music started to play and bot joins the channel, but it doesn't sound anything.

https://media.discordapp.net/attachments/282987865556647936/368924864620396544/unknown.png
https://media.discordapp.net/attachments/282987865556647936/368925411091939348/unknown.png

Any ideas? I'll be thankful for some help.

**Comment by samdivaio** [comment]
Install [.NET Core SDK](https://www.microsoft.com/net/download/core), your OS is missing some preinstalled requirements.

**Comment by DavidGarciaOriol** [comment]
I've already done that, and it didn't work.

**Comment by Kwoth** [comment]
#1053
