### ISSUE TITLE
Nadeko-mute problems

### ISSUE THREAD

**Issue by AnkokuShizora** [Kwoth/NadekoBot#1719]
First off, people that get nadeko-muted sometimes leave and rejoin the server in order to evade mute. i was told by a staff in nadekologs that nadeko-mute is supposed to be assigned again to anyone who was muted before leaving and rejoins, to avoid evasion. That is clearly not the case with me so i thought i'd file an issue here. I'm also not a host of nadeko and i don't know if that is related in any way.

Secondly, i'd like to bring to your attention that nadeko sometimes adds nadeko-mute or a self-assignable role on people that join the server. I'd like to note that those people most of the time have not been on the server before so this problem is unrelated to the previous one. Also none of the roles randomly assigned by nadeko are set as auto-assigned ofcourse. When i asked about this in nadekologs the staff told me it's just a bug and i should try disabling and enabling auto-assigning. This doesn't really occur often but i've noticed many people complaining about the same thing.

I think nadeko is a great bot so i thought i'd share my thoughts with you in hope for improvements.
Thnx for reading.

**Comment by Kwoth** [comment]
Bot just can't automatically add self-assignable role, that's not possible.

Check the auto assignable role. Also, mute and unmute the user who has that thing happening to him. We already have the possible mute issue logged in #1556

**Comment by AnkokuShizora** [comment]
Hmm i will tell you my experience with this in detail. In my understanding i can only have one auto assignable role with nadeko at a time. In my server that role is called "animu member" and it is auto assigned to everyone the moment they join. We have also set 2 self assignable roles with nadeko from which one is called "itsmeagain's close friend". I have personally witnessed new members join the server for the first time and have both "animu member" and "itsmeagain's close friend" roles. No one assigned the role to themselves and one of them was also some troll bot that doesnt even chat on channels and dms our users instead. I even saw one once have only the "itsmeagain's close friend" role for some reason. Taking all that into consideration i think it is worth reconsidering wether it is possible for a bot to automatically add self assignable role.
