### ISSUE TITLE
nadeko just stoped working and has a issue

### ISSUE THREAD

**Issue by wolfkid4** [Kwoth/NadekoBot#1720]
nadeko has been working fine for months then this past friday it stop and iv reset it, updated it, redid the .json and still no luck. this is what it says
![capture25](https://user-images.githubusercontent.com/32859804/31646031-5ccfbef6-b2cd-11e7-8ecf-cad76376aea6.JPG)

**Comment by GMR516** [comment]
1.3b doesn't look updated to me. I recommend updating to the latest.

**Comment by wolfkid4** [comment]
yea just found out its a .exe file now just downloaded new install

**Comment by wolfkid4** [comment]
have a issue with installer tho 
![image](https://user-images.githubusercontent.com/32859804/31647015-6eb23f62-b2d3-11e7-812d-47861e6261ff.png)

**Comment by shivaco** [comment]
Install Redis, check the left bottom corner in NadekoBot Updater, also restart your PC after installing all prerequisites.
