### ISSUE TITLE
Shared 0 Logging in...

### ISSUE THREAD

**Issue by 2UNIEK** [Kwoth/NadekoBot#1722]
Been sitting on this for about half an hour, not sure what the problem is. 
https://i.imgur.com/kgezyOE.png

**Comment by shivaco** [comment]
Your OS is Windows 7? If so, you cannot host Nadeko.

**Comment by Macley-Kun** [comment]
@2UNIEK ya using Windwos 7 dude? You need to use Windows 8.1 or higher.
