### ISSUE TITLE
Channel filter for invites

### ISSUE THREAD

**Issue by MoonKidd** [Kwoth/NadekoBot#1724]
Nadeko is deleting any messages sent in the server for some reason, not just any discord invites.

This just started to happen, before it was working but wasn't following the role order rule, it would delete invites from roles higher than it. https://imgur.com/a/tAO4m

**Comment by Kwoth** [comment]
No, she always deleted all invites?

**Comment by MoonKidd** [comment]
I can understand that, but is there any reason that she deletes normal messages sometimes?

**Comment by Kwoth** [comment]
None i can think of

**Comment by MoonKidd** [comment]
Okay it's cool
