### ISSUE TITLE
NadekoBot.exe Stop responding

### ISSUE THREAD

**Issue by hank0531** [Kwoth/NadekoBot#1725]
![image](https://user-images.githubusercontent.com/24751265/31821198-deecca08-b5d6-11e7-82d5-8cf93cfca8e6.png)

**Comment by Kwoth** [comment]
Press "Install redis" in the bottom left corner of the installer.

**Comment by hank0531** [comment]
How to NadekoBot installer link??

**Comment by MavisTail** [comment]
it's from the installer itself, just find "Redis" and install it

**Comment by Macley-Kun** [comment]
@hank0531 assuming from you latests issue you submitted, i assume this issue is resolved for you?
You can close the issue here on Github then 👍
