### ISSUE TITLE
Different Kind of Raffle or Game

### ISSUE THREAD

**Issue by TwinDragon** [Kwoth/NadekoBot#1729]
More a suggestion than anything.

Friend of mine in a certain discord server mentioned something about a possible raffle function so I dug around the command list to see. _**.raffle**_ wasn't quite what I was looking for so here are my thoughts.

Someone in this server wanted someone to pick a number from 0 to 1,000,000. People would then @ him directly with a number that he already had in mind. Anyone who enters has a chance to win a code or whatever for a game. The user with the number guessed closest to his chosen number basically wins the contest.

This may not be too bad to have perhaps for Nadeko as for something fun that doesn't cost flower points or anything.

**Comment by Kwoth** [comment]
use feathub
