### ISSUE TITLE
userpresence integration in logserver is spamming

### ISSUE THREAD

**Issue by samdivaio** [Kwoth/NadekoBot#173]
Remove the user status (offline and online) notifications form logserver,
Also message typed in text channels,
**ONLY KEEP** Loggin when message is edited/changed or deleted. User name and avatar changes.
**ADD/ FEATURE REQUEST** Loggin changes to _**user roles, text/ voice channel names and text channel topic**_

**Comment by Kwoth** [comment]
can you move this to #111
