### ISSUE TITLE
Error when building NadekoBot 2.0 - 'Image': static types cannot be used

### ISSUE THREAD

**Issue by tukimoop** [Kwoth/NadekoBot#1730]
I got the announcement from Kwoth that 2.0 was out, so I started with getting the new install script and installing the new prerequisites. However, when trying to build NadekoBot, these errors pop up.
![putty_2017-10-21_22-46-33](https://user-images.githubusercontent.com/28344254/31851460-11ce4916-b6b2-11e7-9ee7-2e3d8865ebcb.png)

These errors pop up both on development and stable release. Any idea how I fix it, or when it's going to be fixed if it's a problem with the code?

I've tried reinstalling dotnet and reinstalling prerequisites once again, but that doesn't solve the problem.

**Comment by tukimoop** [comment]
This is an entirely fresh build/folder, as I have deleted the folder in trying to fix another issue.

**Comment by Kwoth** [comment]
Completely remove your previous installation of dotnet, then make sure you're using 1.9 installer link, then reinstall prerequisites and redownload nadeko.

**Comment by tukimoop** [comment]
Shouldn't have jumped the gun and got the new script then, eh? Fixed and got 2.0, thanks Kwoth.
