### ISSUE TITLE
.deletewaifu SQL error

### ISSUE THREAD

**Issue by ronelm2000** [Kwoth/NadekoBot#1731]
![screenshot 2017-10-21 19 54 29](https://user-images.githubusercontent.com/12634987/31851549-90bc398a-b69a-11e7-83b6-82c6fc0285b9.png)

Ofc, using latest 2.0.0 NadekoBot, Linux Ubuntu self-hosted.

**Comment by Kwoth** [comment]
fixed in 2.0.2
