### ISSUE TITLE
How to use the robot in the text channel to enter the text you want?

### ISSUE THREAD

**Issue by hank0531** [Kwoth/NadekoBot#1732]
like this
![image](https://user-images.githubusercontent.com/24751265/31852045-766cb056-b6a3-11e7-8801-708fcdaedad2.png)

**Comment by Macley-Kun** [comment]
Hank we got a channel for these questions....... It's called #help

**Comment by Kwoth** [comment]
You can't (not with the here and everyone mentions at least) . `.say` is closest to that
