### ISSUE TITLE
.xp doesn't load Avatars on 2.0 and gives an error.

### ISSUE THREAD

**Issue by Gremagol** [Kwoth/NadekoBot#1733]
Kwoth told me to create an Issue.

So, here's how to reproduce:
1. update nadeko to 2.0
2. type `.xp`
3. look at the image. (and the console)
![bug6](https://user-images.githubusercontent.com/24619854/31854299-c23970a8-b696-11e7-9540-894dc0d12e34.PNG)
![nadeko](https://user-images.githubusercontent.com/24619854/31854310-01b3aa82-b697-11e7-91a4-367bedc8416a.png)

**Comment by QuantumToasted** [comment]
Seems only avatars are affected, club icons still work properly.
![image](https://user-images.githubusercontent.com/30324210/31854527-6c0e84f6-b660-11e7-9bc3-482d8f753147.png)

**Comment by Kwoth** [comment]
Fixed in 2.0.1, update
