### ISSUE TITLE
Weird issues in 2.0

### ISSUE THREAD

**Issue by Brramble** [Kwoth/NadekoBot#1734]
1) There seems to be avatars missing in `.xp`. I have couple of other friends who are also having this issue,

2) `.clubinfo` as a command alone does not display your active club and prints this in the console: https://i.imgur.com/RJHRh6a.png

3) `.clublb` also dont work and posts this in console: https://i.imgur.com/74R4iVs.png

I have been able to repeat this issues on another VPS running Linux Ubuntu 16.04 on Nadeko v2.0

**Comment by Macley-Kun** [comment]
@Brramble i noticed someone already made that issue: #1733 . You can close this one and follow the events in that issue from now on.

**Comment by Kwoth** [comment]
@Brramble can you show me the full error of the second issue?

**Comment by Brramble** [comment]
is this enough: https://i.imgur.com/PuYBAKE.png

**Comment by Brramble** [comment]
@Kwoth Do you require me to test anything else? I'm looking to see if there is any others but it seems to be the XP module

**Comment by Kwoth** [comment]
i fixed .xp, working on other ones, just wait

**Comment by Brramble** [comment]
#1736 #1735 Two other issues I can reproduce too

**Comment by Kwoth** [comment]
Fixed in 2.0.1, update
