### ISSUE TITLE
Self Assignable Roles

### ISSUE THREAD

**Issue by LunarSera** [Kwoth/NadekoBot#1735]
Nadeko v 2.0.0 - updated today. Linux. mint. 
Lsar does not list all the roles that can be assigned. listed around 22 of 28. cannot lsar 1 to see the second group either. previously a reaction popped up to allow switching between pages.

**Comment by Kwoth** [comment]
Are you sure? try running it again? It might have cleaned up 6 roles

**Comment by LunarSera** [comment]
same issue. second group isn't listed. lsar 0 deletes itself and doesn't do anything. all commands log in the terminal. including lsar 0. {the one that is useless}

**Comment by Kwoth** [comment]
DM me your database on discord.

**Comment by LunarSera** [comment]
Dm'd. rename to nadekobot.db (obviously)

**Comment by LunarSera** [comment]
I will forward this to the ofiicial discord bug squashers. The embed was cut short on android. the whole embed shows on canary for linux.
