### ISSUE TITLE
duo bot

### ISSUE THREAD

**Issue by Kyuoshi** [Kwoth/NadekoBot#174]
This might just be a stupid question that has a simple answer :P 
but how do i only get 1 bot to reply? atm i have 2 nadeko bots for some reason. 
[http://puu.sh/o2uAD/6d41165446.jpg](url)

**Comment by Kwoth** [comment]
NadekoBot is "official" one. Ban one.

**Comment by tg44** [comment]
Or, you can deactivate modules and commands...
