### ISSUE TITLE
.sql command not found

### ISSUE THREAD

**Issue by willysunny** [Kwoth/NadekoBot#1740]
as stated in topic.

.h .sql will return command not found, nor would console trigger it.

BotVersion 2.0.2

**Comment by MavisTail** [comment]
I think the latest is 2.0.3 try to update and see if it works

**Comment by shikhir-arora** [comment]
It’s because the command is called `.execsql`
https://i.imgur.com/vRSisfy_d.jpg?maxwidth=640&shape=thumb&fidelity=medium

**Comment by willysunny** [comment]
I got trolled by kwoth then D:

![image](https://user-images.githubusercontent.com/5907852/31868789-7dc0bb12-b7d5-11e7-8491-2addfbffacab.png)
