### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by LunarSera** [Kwoth/NadekoBot#1741]
I changed Nadeko's name a couple times. I think she's being rate limited but the consol is spewing out errors.
Can this be fixed? So others won't be confused. 
Nadeko V 2.0.3 on Linux. 
CommandHandler | Discord.Net.HttpException: The server responded with error 400: BadRequest
   at Discord.Net.Queue.RequestBucket.<SendAsync>d__18.MoveNext()

**Comment by samdivaio** [comment]
Sounds normal to me. It's a discord limit.

**Comment by LunarSera** [comment]
well yeah. I know it's normal. but Nadeko doesn't say anything. she just spews out garbage in the consol

**Comment by samdivaio** [comment]
Ah you want to get error report if its ratelimited 😄
