### ISSUE TITLE
Nadeko Bot Is Sending Doubles?

### ISSUE THREAD

**Issue by MoonSeok7** [Kwoth/NadekoBot#1748]
![screen shot 2017-10-24 at 3 28 33 am](https://user-images.githubusercontent.com/33051791/31929858-76e1eb72-b86b-11e7-8686-08a7356fee9f.png)

So i'm self hosting Nadeko Bot (renamed to Moon Bot) and after I set him to online, he keeps posting in doubles, even though I type in one command.

Anyone else have this problem? Is there a way to fix it?

**Comment by Gremagol** [comment]
On which version is your bot?

**Comment by Gremagol** [comment]
If your Bot is on 2.1.0 and below, you should update it because it got fixed.
#1743

**Comment by MoonSeok7** [comment]
ok! It is 1.9. I'll see if i can update it later today. Thank you!

**Comment by Kwoth** [comment]
1.9 didn't have this issue. You're probably just running 2 bots somehow.

**Comment by MoonSeok7** [comment]
I don't know how i could be. I'm hosting on a Linux and my Mac doesn't have the coding on it. I'm not sure why it's doing this. It didn't do it before it went offline. After he went online did he start posting doubles

**Comment by borgqueenx** [comment]
nope this is also happening to me, probaly because the shard restart system that is new.
