### ISSUE TITLE
Music feature

### ISSUE THREAD

**Issue by nekuisme** [Kwoth/NadekoBot#175]
im not sure if this is a problem with the bot or is just me not being able to computor, but after i queued up like 3 or so music i can seem to get it to play

**Comment by Kwoth** [comment]
You didn't provide any info whatsoever.

Are you using HaNadeko or hosting yourself?

If you are using hanadeko, she is being hammered with requests pretty hard, its too much for the server. I am working on optimization update. If you are hosting it yourself, then you didn't setup ffmpeg/google api key correctly.
