### ISSUE TITLE
Restarting shard restarts the bot? (startup messages shown again)

### ISSUE THREAD

**Issue by borgqueenx** [Kwoth/NadekoBot#1750]
I am asking because when the shard reconnects, the bot again throws in its set startup messages i have set.
I have set 2 startup commands to initiate a cooldown in a certain channel, and a command that just says "im back online". I dont want to see those messages when the shard simply reconnects, if possible.

**Comment by shikhir-arora** [comment]
I can’t replicate this. Are you running the latest version of the bot? (Type .stats)

**Comment by borgqueenx** [comment]
2.1.0.

**Comment by shikhir-arora** [comment]
It was fixed in 2.1.1 - upgrade to 2.1.2 and it shouldn’t be an issue.

**Comment by borgqueenx** [comment]
damn, versions are being pushed out fast. if youre sure this fixed it, then it can be closed. ^^
