### ISSUE TITLE
Curly quotes not recognised as wrapping

### ISSUE THREAD

**Issue by zergling-man** [Kwoth/NadekoBot#1751]
To wrap multiple words (acr/quote triggers, pokemon moves, etc.), Nadeko only checks for the straight quote:
https://unicode-table.com/en/0022/

However, there are many devices (appears to primarily be iOS devices) that will automatically use curly quotes:
https://unicode-table.com/en/201C/
https://unicode-table.com/en/201D/

I believe such devices have no easy way of disabling this functionality (temporarily or otherwise), so support for those would be appreciated.

**Comment by MaybeGoogle** [comment]
I've had this issue before, but in TextEdit (OSX) when editing the credentials.

In TextEdit, this is called "Smart Quotes" and can be disabled under `Edit>Substitutions`. 

In iOS 11, there is a new feature causing this called "Smart Punctuation". You can disable it in `Settings>General>Keyboards` I think. I don't have an iOS device so I can't personally confirm, but you will trust me bc I'm Google 😄

**Comment by Kwoth** [comment]
You should make this issue on discord.net repo maybe. It has nothing to do with me.

**Comment by Kwoth** [comment]
Yea, can't really do anything about it.
