### ISSUE TITLE
.poll commands not working properly.

### ISSUE THREAD

**Issue by QuantumToasted** [Kwoth/NadekoBot#1752]
Tested on Nadeko v2.1.2, after resetting perms, bot has Admin permissions as well.
`.poll` works correctly, but users cannot vote by typing the number to be voted for.
`.pollstats` does nothing and does not error out in console, simply stating that it executed normally.
`.pollend` does *this* and does not delete the poll. Trying to create a new poll states that one is already running.
![image](https://user-images.githubusercontent.com/30324210/31949122-2347cada-b89e-11e7-952f-3b217dbe71f8.png)

**Comment by Kwoth** [comment]
`.pollend` will indeed throw an exception, but only if there is no poll. Fixed that now.

`.poll` didn't work because of a separate bug, fixed also in 2.1.4
