### ISSUE TITLE
Feature: Using .poll in combination with a counter

### ISSUE THREAD

**Issue by Rushleader** [Kwoth/NadekoBot#1757]
Hey guys,

I'd like to request a small feature, being able to combine a .poll with a group so only people in that group can vote. In combination with that being able to auto stop the poll and post the result when everyone in the group has voted or the bot has met the timelimit.

Something this:
`if (group.memberCount() == poll.votes || timelimit) {
    poll.stop();
}`

This would make it way easier to handle and time when the bot ends without waiting for a timer when everyone has already voted.

Regards,
Rushleader

**Comment by MaybeGoogle** [comment]
This sounds like a really good idea. Nadeko actually has a [page for feature requests](http://feathub.com/Kwoth/NadekoBot), so maybe you should ask for the feature there. Don't worry too much about getting upvotes. Kwoth looks through them when he is bored :^). 

The other option is to make a pull request, but this feature sounds pretty big...

**Comment by Kwoth** [comment]
Thanks for the suggestion, you should create it on feathub (the link maybegoogle posted). 
Call it "Role-specific poll" or something like that.
