### ISSUE TITLE
@Nadeko Cleverbot isn't working

### ISSUE THREAD

**Issue by JackNoahKerr** [Kwoth/NadekoBot#1758]
My server is running its own NadekoBot, Cleverbot used to work but we tried using the @Nadeko Cleverbot command recently and it doesn't work anymore. We see it typing but after a few second there is no reply sent. Is there any way to fix this?

**Comment by shivaco** [comment]
Must be an issue on Program-O's (Cleverbot API) side.
![image](https://user-images.githubusercontent.com/22858781/32015777-e787e9e8-b9e3-11e7-9f74-69410a9e78ca.png)

**Comment by Gremagol** [comment]
If you try to talk to program-o itself, (https://www.program-o.com/) it errors.

**Comment by Midoriin** [comment]
It doesn't work for me neither. The API is probably down. I know, the old cleverbot API costs money now. But we really need to be able to switch between cleverbot APIs. Nadeko Clone owners can probably afford the packages. Even the free package might be enough.
![1](https://midorina.ga/u/eee4fd.png)
Please make this a thing @Kwoth 💯

**Comment by MaybeGoogle** [comment]
@Midoriin it *is* already a thing... kinda hidden but you can put ur api key in there. Copy the format from credentials_example.json and paste it in credentials.json. Then, replace all the values u want to replace 😄 . CleverbotApiKey is one of them.

I know this used to work, and it should still work.

**Comment by Kwoth** [comment]
Yes. Get the free version of the official cleverbot and add it to your credentials.json, and then your cleverbot command will use official one instead of (poopy) program-o

**Comment by Midoriin** [comment]
Wow, I didn't know. That's pretty nice. Thanks!
