### ISSUE TITLE
.streamrole Comand doesnt see mixer people online status

### ISSUE THREAD

**Issue by worldofmadness** [Kwoth/NadekoBot#1759]
The .streamrole Comand doesnt see mixer people online status when streaming

**Comment by Kwoth** [comment]
@worldofmadness do you have a mixer stream? If you do, you could DM me and we could test it together. I don't know anyone who streams over there but I thought it worked from the tests I've done.

**Comment by worldofmadness** [comment]
DM Sent

**Comment by Kwoth** [comment]
`.streamrole` only works on people who have streaming status on discord (purple one with stream name)
