### ISSUE TITLE
Issue and PR Template

### ISSUE THREAD

**Issue by ItsPugle** [Kwoth/NadekoBot#1760]
Do you guys want me to make you an auto-filling Issue & PR template like [HowToDiscord](https://github.com/ItsPugle/DiscordApp)?

**Comment by Kwoth** [comment]
Hey, pretty nice idea but I'd have to refuse.

People just make all kinds of issues, and PRs. I don't want to make people think creating an issue is a hassle and let bugs slide because of it, or other questions which are maybe important but not directly related to the bot.

Thanks again

**Comment by ItsPugle** [comment]
All good! Have a great day 😄
