### ISSUE TITLE
How to run Nadeko v2+ from Source on Windows 10?

### ISSUE THREAD

**Issue by CrYoZs** [Kwoth/NadekoBot#1763]
Hello!

v1.9 running fine, like in [guide](https://nadekobot.readthedocs.io/en/latest/guides/From%20Source/)
`dotnet run -c Release`

But after update to v2, i get error Project Not Found. I also tried on clean git clone.

`PS D:\DiscordBots\NadekoSRC> dotnet run -C Release`
`Не удалось найти выполняемый проект. Убедитесь в том, что проект существует в D:\DiscordBots\NadekoSRC, или передайте путь к проекту с помощью --project.`

Sorry, but i don't know how to run and get this error on english.
And sorry for bad english. (

**Comment by shivaco** [comment]
`Failed to find project. Make sure that the project exists in D:\DiscordBots\NadekoSRC or pass the path to the project with the --project.` is the translation.

**Comment by samdivaio** [comment]
Check your dotnet version.

**Comment by CrYoZs** [comment]
.NET Core 2.0.2 SDK
```
PS D:\DiscordBots\NadekoSRC> dotnet --version
2.0.2
```

I tried another way:
```
dotnet restore
dotnet publish -c Release --runtime win7-x64
```
All is ok, no errors.

Then run from NadekoBot.exe and get this error too, but from Nadeko Console.
```
19:24:25 ShardsCoordinator | Starting NadekoBot v2.1.4
Failed to find project. Make sure that the project exists in D:\DiscordBots\Nadeko or pass the path to the project with the --project.
```

Is this only on my side?
Nothing changes in environment, 1.9 working, 2.0 not :(

**Comment by samdivaio** [comment]
`D:\DiscordBots\NadekoSRC` and `D:\DiscordBots\Nadeko` ?
If you just cloned it and didn't do anything with Nadeko folders then you should have `NadekoBot\src\NadekoBot`.
the `cd NadekoBot/src/NadekoBot` in the guide was meant for Linux; I believe you didn't try `cd src\NadekoBot` before running the bot.

**Comment by Kwoth** [comment]
Sam is right, move into src/NadekoBot and then run the bot.
