### ISSUE TITLE
Int32 overflow on .wheel

### ISSUE THREAD

**Issue by ronelm2000** [Kwoth/NadekoBot#1764]
![screenshot 2017-10-26 23 27 02](https://user-images.githubusercontent.com/12634987/32062701-d7705b70-baa7-11e7-8853-11cbc9dcd991.png)
Either simply disallow bets more than 900 million, or convert the value to Int64 or double before multiplying.

**Comment by Kwoth** [comment]
Nope, i just don't support that usecase.
