### ISSUE TITLE
Patreon problems

### ISSUE THREAD

**Issue by LeaderSoul** [Kwoth/NadekoBot#1767]
Hello
When I try use patreon service then I get this message in console:

15:45:03 PatreonRewardsService | System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (NOT FOUND).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NadekoBot.Modules.Utility.Services.PatreonRewardsService.<RefreshPledges>d__18.MoveNext() in C:\Users\Soomo\De
sktop\NadekoBot-1.10.2\src\NadekoBot\Modules\Utility\Services\PatreonRewardsService.cs:line 72

I don't know if I use badly or the source not ok. 
I created a client here: https://www.patreon.com/portal/registration/register-clients
I put the **Creator's Access Token** in credentials.json file , to **PatreonAccessToken** part.
I didn't find the PatreonCampaignId part so I went to patreon widget page: https://www.patreon.com/dashboard/widgets and put the number from there.

Where can I get patreon campaign id and access token? If I entered everything wrong.

**UPDATE**
I gave bad id. If someone don't know how can add the ID then you can use this: https://github.com/Patreon/patreon-php/blob/master/examples/patron-list.php  and put campaign_id in echo. 

But now, I don't know why I get this:

18:38:21 PatreonRewardsService | System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at NadekoBot.Modules.Utility.Services.PatreonRewardsService.<RefreshPledges>d__18.MoveNext() in C:\Users\Soomo\De
sktop\NadekoBot-1.10.2\src\NadekoBot\Modules\Utility\Services\PatreonRewardsService.cs:line 78

**Comment by Kwoth** [comment]
Try updating your bot and running it again. That line error doesn't match up to mine.

**Comment by LeaderSoul** [comment]
Do you mean update the NadekoBot? Because in updater shows to me the latest version is 1.10.2 and I use 1.10.2. :)

Or the problem is that I don't have patreon donators yet and because of that I get this error?
I checked the api also and when I run in postman program then I get this response:

```
{
    "data": [],
    "links": {
        "first": "https://www.patreon.com/api/oauth2/api/campaigns/xxxxxx/pledges?page%5Bcount%5D=10&sort=created"
    },
    "meta": {
        "count": 0
    }
}
```

**Comment by Kwoth** [comment]
@LeaderSoul update to 2.2.1 now please then try it again.

**Comment by LeaderSoul** [comment]
Same. You can see in attachment.
![screenshot_20171028134617](https://user-images.githubusercontent.com/1939827/32134123-a98c8cfc-bbe6-11e7-8c2c-bc027e0b2769.png)

Credentials.json:
![cred_file](https://user-images.githubusercontent.com/1939827/32134154-2a8ada8e-bbe7-11e7-8798-cf3d4e89188a.png)

Patreon:
![patreon](https://user-images.githubusercontent.com/1939827/32134162-6848d178-bbe7-11e7-8fff-96c60453daa0.png)

Discord:
![discord](https://user-images.githubusercontent.com/1939827/32134173-aca4e8e8-bbe7-11e7-8433-0ca1f26153a5.png)

If I add **PatreonAccessToken** then I get above message but if I put nothing there then I don't get error.

**Comment by Kwoth** [comment]
Seems like this happened because you don't have anyone pledging? I've fixed this possibly in `2.2.3`

Wait for it to release

**Comment by LeaderSoul** [comment]
Yeah, I don't have yet. Thank you in advance. :)

**Comment by d-floe** [comment]
I updated to 2.2.3 and I set up my patreon much like LeaderSoul here but im getting this new issue that pops up every 3 minutes

```
0 07:35:18 PatreonRewardsService | System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (NOT FOUND).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Utility.Services.PatreonRewardsService.<RefreshPledges>d__18.MoveNext() in /root/NadekoBot/NadekoBot.Core/Modules/Utility/Services/PatreonRewardsService.cs:line 90

```

**Comment by LeaderSoul** [comment]
@d-floe you gave bad campaign ID. :P If you don't know how can look into it then come here: https://discord.gg/FTbdFCZ . I will help you.
