### ISSUE TITLE
Hide Disabled modules from .modules

### ISSUE THREAD

**Issue by aikar** [Kwoth/NadekoBot#1768]
Hi, I've disabled NSFW but I still see it on .modules list which my users are able to run.

I don't want this showing at all, can you make it be removed if the module is disabled. 

Using the carbon hosted version.

**Comment by Macley-Kun** [comment]
.verboseerror / .ve
Toggles whether the bot should print command errors when a command is incorrectly used. Requires ManageMessages server permission.
Usage
.ve
Module: Utility

Is this what can fix your issue?

**Comment by aikar** [comment]
No, I want it to not show on .modules, which isn't a command error.

**Comment by Deivedux** [comment]
You can not hide modules from the public list, unless it is globally disabled from everyone's use.

**Comment by BlackMix** [comment]
Just update o commands infos from Nadeko..
InfoCommands.cs and in nsfw command add if for guild id
if guild.id === NSFW  isdisabled : hidden and stop for this guild.

something like this.. a few minutes dev can do this.

**Comment by Kwoth** [comment]
The guy is using public bot, on which that is not possible. If you were selfhosting you could use `.gmod`

Add that feature request to https;//feathub.com/kwoth/nadekobot
