### ISSUE TITLE
Problems with FFMPEG on Windows 8.1

### ISSUE THREAD

**Issue by Dog2puppy** [Kwoth/NadekoBot#177]
I'm running Windows 8.1 and FFMPEG installs fine but, when I do the right-click thing on the This PC and stuff I can't find the PATH.

**Comment by Kwoth** [comment]
video tutorial <https://www.youtube.com/watch?v=x7v02MXNLeI>
textual tutorial <https://github.com/Kwoth/NadekoBot/blob/master/ComprehensiveGuide.md>

its there. advanced setting, envirnoment variables, if path is not listed as in the video, make one with that name and add ffmpeg to it
