### ISSUE TITLE
lsar pagination broken/missing on 2.0+

### ISSUE THREAD

**Issue by zergling-man** [Kwoth/NadekoBot#1770]
Thanks to tesar groups, lsar now shows all roles on a single page, resulting in unwieldy output for servers with large amounts of self-assignable roles.

**Comment by Kwoth** [comment]
more than 2000 characters of self assignable roles, really?

**Comment by zergling-man** [comment]
Not necessarily. In this case I define "unwieldy" as being more than about 20 *lines*. Given an average length of 8 for a role's name, that's only 400 characters needed to be annoying.
