### ISSUE TITLE
Word "test" appearing before 8ball answers (v2.2.1)

### ISSUE THREAD

**Issue by Foxwells** [Kwoth/NadekoBot#1771]
Do .8ball, and the word "test" appears before the "? Question". Was told in the Nadeko server that this is a bug and to report it. Happens on both self-host and public.

Pics:
![screenshot_501](https://user-images.githubusercontent.com/15647033/32137712-f4779096-bbea-11e7-8721-d9fc1b12d51d.png)
![screenshot_502](https://user-images.githubusercontent.com/15647033/32137713-f4a9aeb4-bbea-11e7-9999-2860a2e9cd5d.png)

**Comment by StarlightGalerie** [comment]
I am experiencing a similar issue.

**Comment by Kwoth** [comment]
Fixed in the next update
