### ISSUE TITLE
gambling_reaction_title, gambling_reaction_desc, and gambling_reaction_footer are all ignored in ts-ts despite being specified in the lang file [BUG FOUND; Solution needs to be applied to all lang files]

### ISSUE THREAD

**Issue by StarlightGalerie** [Kwoth/NadekoBot#1773]
I run a self-hosted Nadeko that has both global and server locale set to use Tsundere. However, despite this, whenever .startevent reaction is performed, it fails to use the listed ts-ts key. This is true as well for all lang files after investigating them.

[Current code; unaltered]
![67e5effac252977b7f452eeabcab3e43](https://user-images.githubusercontent.com/33184750/32139529-45276c4a-bc19-11e7-9e93-7237472cb968.png)

[Visible results when ran; unaltered code]
![c19e2996008e0f1ffd9ed6d7e66861e0](https://user-images.githubusercontent.com/33184750/32139605-beb55ec6-bc1b-11e7-9b5a-d1abc9b78cf9.png)

[Terminal; unaltered code]
![image](https://user-images.githubusercontent.com/33184750/32139568-762f1986-bc1a-11e7-87d4-a96bec683ea9.png)

I have found the solution to this bug by closely examining the terminal's request and comparing it to the lang file. The keys between lang files and what the bot is looking for are both different, following the name change of flowerreaction to just reaction. This means that all lang files still refer to the reaction event as "flowerreaction", which now looks for gambling_reaction_title keys. I have applied the change to ts-ts and shown it as a resolved example.

[Solution code]
![image](https://user-images.githubusercontent.com/33184750/32139586-06b1b61c-bc1b-11e7-92d5-9c87b6330650.png)

[Results of solution code]
![image](https://user-images.githubusercontent.com/33184750/32139595-5cc4448e-bc1b-11e7-9c7e-9b80b316e42d.png)

NOTE: This will need to be applied to **each** lang file in order to work correctly for each of their respective locales.

**Comment by Kwoth** [comment]
They're just missing, i'll add them soon

**Comment by StarlightGalerie** [comment]
Well, it is there, but the keys are mislabelled. Timely is still missing however.
