### ISSUE TITLE
Hungarian translation problem

### ISSUE THREAD

**Issue by LeaderSoul** [Kwoth/NadekoBot#1776]
Hello
When I look into translations then I can see that the english version has 904 lines and hungarian version has 871 lines.
If I check what is the difference then there is many: https://www.diffnow.com/?report=nd87x
I will fix this but how can I send to you the fixed version?

UPDATE: Other thing in english version you have: "customreactions_redacted_too_long": "Redecated because it's too long.",

I think this would be Rejected, instead Redecated. :)

**Comment by Kwoth** [comment]
Dw about it, it will get updated.
