### ISSUE TITLE
Error in public nadeko gc (haven't tested on selfhosts yet)

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#1777]
There's a nice new message that comes with the flower spawn, and there's also a nice new error. 

`I can't tell you if the command is executed, because there was an error printing out the response. Key games_curgen_pl is not properly formatted. Please report this."`

and then it says your new what the hell dude message.

gc still works though btw

**Comment by Kwoth** [comment]
Just fixed, translation for tsundere wasn't updated. Baka ser.

**Comment by Kyousei** [comment]
Can confirm, took a screenshot of it too.

![](https://i.imgur.com/KVOjx8X.png)
