### ISSUE TITLE
Poll registered twice (Self-host, v2.2.1)

### ISSUE THREAD

**Issue by Foxwells** [Kwoth/NadekoBot#1779]
I created a poll. It seems to operate fine (outside of the question not appearing on the poll text, but I'm not sure if that's normal), but when I looked at the command prompt, it showed that the poll was registering twice. I did not send 2 messages.

Command prompt:

![screenshot_503](https://user-images.githubusercontent.com/15647033/32178181-1b0a9cba-bd5a-11e7-83e3-98355e82d162.png)
![screenshot_505](https://user-images.githubusercontent.com/15647033/32178182-1b1d018e-bd5a-11e7-8006-007626124df7.png)

Chat:

![screenshot_504](https://user-images.githubusercontent.com/15647033/32178197-2530cb60-bd5a-11e7-905e-3c203ccd56ae.png)

**Comment by Kwoth** [comment]
Restart your bot, there's a known issue with shard coordinator which causes the bot to startup twice if shard goes unresponsive. I'm looking into it.

**Comment by Kwoth** [comment]
#1747
