### ISSUE TITLE
Spelling errors in hangman

### ISSUE THREAD

**Issue by NogiKAZA** [Kwoth/NadekoBot#1781]
I got notified by some on my server members, about spelling errors in the hangman game. 
Showd in the picture down below. There is probably more, but those were the one we managed to find. Thanks.
![image](https://user-images.githubusercontent.com/33229759/32181920-d1cdf614-bd95-11e7-82c9-2eefd1bb7c5a.png)

**Comment by Kwoth** [comment]
xnaas PRed a fix. If you're on windows, wait until next release, if you're on linux, just update right away.
