### ISSUE TITLE
Issues with .timely countdown

### ISSUE THREAD

**Issue by CynicalPopcorn** [Kwoth/NadekoBot#1782]
You can set timely to be x amount of flowers every y hours, however when I've set my timely to be 100 every 48h it restricts access for 48 hours BUT counts down as 24 hours when you do .timely to check your cooldown. Once the first 24 hours hits 0 the 24 hour cooldown will restart when you check again. It will, after 48 hours, work. So the issue is with the countdown.

Here's some screenshots:
![image](https://user-images.githubusercontent.com/11669371/32192916-8846cbf2-bdad-11e7-8e62-80fe7ff3f585.png)
 (Checks at 19:28, sees 19 minutes left implying at 19:47 he'll be able to get his flowers)
![image](https://user-images.githubusercontent.com/11669371/32192909-80dbf81a-bdad-11e7-8d1b-217bd5d41d3d.png) (Checks again at 19:56, should be able to according to countdown but then the countdown shows 23h 51m left, and this is 9 minutes after it hit 0 so it is looping).

**Comment by Kwoth** [comment]
It's not looping, it just didn't show the days value. I guess i have to change that to show d.hours:minutes;seconds instead of just hours:minutes:seconds
