### ISSUE TITLE
Nadeko not responding to commands

### ISSUE THREAD

**Issue by felight88** [Kwoth/NadekoBot#1783]
I have Nadeko running in 3 servers I'm an administrator of, and in one of those servers (the biggest one) it is not responding to any commands. None of the permissions have been changed, and it doesn't appear like anybody's done anything to it in commands, so I don't know why it's not working. Help?

**Comment by xnaas** [comment]
Are you using the public NadekoBot?

**Comment by Kwoth** [comment]
Some shards were down for a few hours, everything should be normal now.

**Comment by Kwoth** [comment]
I've been working on the fix and I think I've found a solution, so public nadeko should be almost perfectly stable from now on.
