### ISSUE TITLE
 Key 'xp_level_up_channel' is not properly formatted

### ISSUE THREAD

**Issue by thiswasmadeonawhim** [Kwoth/NadekoBot#1786]
Was given this error message for a server rank up channel notification, reporting as told

Screenshot:
https://i.imgur.com/zFbxtis.png

**Comment by Kwoth** [comment]
Which language are you using?

**Comment by thiswasmadeonawhim** [comment]
Using tsundere

**Comment by Kwoth** [comment]
Fixed in next update
