### ISSUE TITLE
Send Failure

### ISSUE THREAD

**Issue by rushsteve1** [Kwoth/NadekoBot#179]
I keep getting this error on my Ubuntu server:
```
Probably wrong EMAIL or PASSWORD.
Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
```
Even though I all the dependencies met, and running an identical setup on my Arch desktop or a Windows PC runs just fine.
I have checked and double checked the credentials.json and it's fine.

**Comment by tg44** [comment]
```
mozroots --import --ask-remove --machine
certmgr --ssl https://gateway-1.discord.gg
```
Try these with and without sudo. That error message is refer to some cert errors.

**Comment by rushsteve1** [comment]
I did that.
Was it OK to use the Mono version from the repos? I did that on my desktop where it worked fine, but the guides say go through the whole process of adding it from their website.

**Comment by Kwoth** [comment]
Yes its fine. Was your problem solved @rushsteve1 ?

**Comment by rushsteve1** [comment]
Yep! I needed to run the mozroots and certmgr commands as root. I should really learn to read error messages as they actually said to do that... but its all good now. Thanks @tg44
