### ISSUE TITLE
Uhh... error in tsundere language

### ISSUE THREAD

**Issue by Radioboy126** [Kwoth/NadekoBot#1793]
https://github.com/Kwoth/NadekoBot/blob/9f7604f456ac7b49140977633b9d97a0c5dc3007/src/NadekoBot/_strings/ResponseStrings.ts-TS.json#L830
-applies to channel
-bin > been 
http://prntscr.com/h4olml

**Comment by Kwoth** [comment]
will be fixed when i update the strings again
