### ISSUE TITLE
Rolling 66 with .br returns "You rolled 66.Better luck next time ^_^" yet rolling 100 with .br returns "You rolled 100.Congratulations! You won X for rolling above 100"

### ISSUE THREAD

**Issue by n0n0man** [Kwoth/NadekoBot#1795]

**Comment by Kwoth** [comment]
![working as intended](https://i.imgur.com/c4jt321.png)

**Comment by Kwoth** [comment]
Actually you're right, I thought it's not fixable but after i checked the string again, i just changed 100 to say 99, i thought it's written in the translated string itself.
