### ISSUE TITLE
Muted users can leave, join again and talk

### ISSUE THREAD

**Issue by Altarisa** [Kwoth/NadekoBot#1798]
Title.
A user who has been muted through .mute can leave the server and join again and he or she will not have the nadeko-mute role, thus being free to talk. I've been told to report this here since this is apparently a bug and .mutes should persist.

**Comment by hemipatu** [comment]
I can confirm that this is an issues, seems like it is a persistence issue which might be down to the fact that the _role_ we specify for muting is not held in a database. Or something along those lines?

**Comment by shikhir-arora** [comment]
Don’t think it’s a bug. @hemipatu is right, there’s no role-persistence right now. Would be a good feature indeed, both for muted roles but also any roles (for limited time) - if a user leaves by accident or whatnot, they can regain their roles.

**Comment by Kwoth** [comment]
There is role persistance when it comes to mute role. It should work. I'll test it out in the coming days. There are a lot of things on the todo list atm.

**Comment by shikhir-arora** [comment]
@Kwoth I actually can't replicate this in a clear server; with the default `nadeko-mute` role auto-created.

For everyone else -

The only steps I can think of that are causing this are:
 
- Your Nadeko mute role has modified permissions
- Awarding a role upon server join automatically perhaps that overrides
- Channel-specific overrides

I've muted a user with proper permissions, had them leave, and had them join back instantly, as well as after 15 minutes or so. They are both awarded the `nadeko-mute` role right away as they should be. So this is likely a permission thing on the server(s) in question.

**Comment by Kwoth** [comment]
What shikhir said.
