### ISSUE TITLE
Bot Crashes Daily

### ISSUE THREAD

**Issue by decoratedbug** [Kwoth/NadekoBot#1799]
Ever since I updated from 1.8.4 to 2.3.0 the bot has been crashing at least once a day. The bot goes offline and there are no errors shown in the console. I'm thinking the problem might be ram usage because Digital Ocean only gives 512mb and I am also running a music bot at the same time. I would use 1.8.4 but I read it would stop working because of channel categories.

**Comment by shikhir-arora** [comment]
That could very well be the case. Specifically, 1.9 introduced Redis for the Xp / Clubs features among other things like Shard management. Redis requires pure memory as it’s a key-value memory store. It uses RAM for speed, but that’s likely why you’re experiencing the crashes. 512 is enough for Nadeko easily, but your other music bot is likely taking up a lot of that, especially if it’s a Java powered bot.

**Comment by decoratedbug** [comment]
I think it's working now. I deleted the old droplet and started fresh. There might've been other things running in the background.
