### ISSUE TITLE
.antispam doesn't unmute voice. 

### ISSUE THREAD

**Issue by TUSK3N** [Kwoth/NadekoBot#1800]
So I've been testing the new .antispam where you can set a limit it will unmute the user in. It all works fine when it comes to text but it will mute the user both text and voice and then when the timer is over and it comes to unmute a user it only unmutes text not voice.

So right now people that have been muted once in text for spamming and wants to later go in voice are server muted by Nadeko.

**Comment by MaybeGoogle** [comment]
nadeko's mute is based off of the nadeko-mute role (or whatever you named it). Check to see if that user has any other roles that prevent him/her from talking in vc.

**Comment by Kwoth** [comment]
Yea, in order for the user to be unmuted from voice, they must be in the voice channel at the time of the unmute otherwise it won't work. I don't think I can change this but I can try.

**Comment by Kwoth** [comment]
Not possible
