### ISSUE TITLE
It doesn't show the name of the last person of each XP leaderboard page

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#1802]
![1](https://midorina.ga/u/2f969b02f6.png)
![2](https://midorina.ga/u/15ba2b8fec.png)

**Comment by Kwoth** [comment]
doesn't look right. works fine for me. Can anyone else reproduce?

**Comment by willysunny** [comment]
Server 2.3.2 Linux Docker cannot repoduce

**Comment by shikhir-arora** [comment]
That usually means that person left your server and you have no other servers with that person. Are you sure that user is still in your server?

**Comment by Midoriin** [comment]
The mention below the leaderboard was to test that if that person is still in the server or not. But apperantely, those guys were not in the server. And with coincidence, they were at the bottom of first 2 pages. Thought this is a bug. Sorry for bothering you all. Closing the issue now.
