### ISSUE TITLE
.Google command responding in German

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#1804]
In public Nadeko and in a server where the language is set to english. 

On my selfhost, results come back in English. 

Maybe some glitch, but idk

**Comment by MaybeGoogle** [comment]
I've created a pr for a solution that works with keyword `test`, but it removes one part that I don't know if you want to keep.

**Comment by shikhir-arora** [comment]
Probably due to where the server IP originates from.
The API request is going to come from the server.

**Comment by MaybeGoogle** [comment]
But it randomly changes, which is a problem

**Comment by shikhir-arora** [comment]
Might be because it could use the websocket gateway that Discord assigns as the country for redirect for efficiency.

**Comment by MaybeGoogle** [comment]
and now its Ukrainian :^)

**Comment by Macley-Kun** [comment]
Tested this out on NadekoBot v2.10.1. Still present.

**Comment by Kwoth** [comment]
Should be in english always now.

**Comment by Kwoth** [comment]
nvm it's not fixed for some reason, even after using google.ca

**Comment by FurkanKambay** [comment]
@Kwoth I could swear there was a PR about this and I commented on it, what happened to it?

**Comment by FurkanKambay** [comment]
@Kwoth found what my comment was. It needs `?cr=countryUS`. I tested it on 2 tabs, showed different results.
Source: https://productforums.google.com/forum/#!category-topic/websearch/qBv0VZLSG50

**Comment by Macley-Kun** [comment]
Is this fixed for everyone? I've tested it out, but still got some german results.

**Comment by FurkanKambay** [comment]
@Macley-Kun I have Ukranian results.

**Comment by Macley-Kun** [comment]
I do know a way how to solve this.
https://github.com/appu1232/Discord-Selfbot/wiki/Google-API-Setup-for-Image-Search-Command

Sadly it does require users to add an extra line where the search engine ID is in. But i'm pretty confident that it will fix the issue.

I'm not a programmer so it's really up to Kwoth if he agrees to add code just to fix this issue with the above methode.
