### ISSUE TITLE
Errors on console

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#1810]
Today, while I was monitoring the console, I saw a few errors which told me to report. There were not anything else related to these errors in the console, and I have not encountered any issue while using the bot, yet. Console gives these errors every 20 seconds or so. **v2.4.2**
![1](https://midorina.ga/u/623043dc18.png)
![1](https://midorina.ga/u/e1075f4e08.png)
![1](https://midorina.ga/u/2cdd93d9ac.png)
![1](https://midorina.ga/u/0a6df4ac6e.png)

**Comment by shikhir-arora** [comment]
Thanks for reporting this. It's not a severe issue, it simply means that some of the response keys are missing. Some can be addressed with the next update/commit(s), but a few are language-related so it depends on translators (not everything is translated yet). You shouldn't notice any issue with the bot, but appreciate the notice!

**Comment by Kwoth** [comment]
This should've been fixed few days ago

**Comment by Macley-Kun** [comment]
Update on this one Kwoth 🤔 ? Should we do something with this or just close and call it a day 😴

**Comment by shikhir-arora** [comment]
Yea those keys were fixed so this should be closed ;D
