### ISSUE TITLE
.langset is not working

### ISSUE THREAD

**Issue by Mexiguy** [Kwoth/NadekoBot#1811]
When tyring to change the bot language I get an error on the console saying the command has too many parameters
![studio_20171108_223102](https://user-images.githubusercontent.com/7787321/32588489-a85ed884-c4d4-11e7-80f4-fb25621169e6.png)

**Comment by shikhir-arora** [comment]
What version of the bot are you running? (`.stats`) as I can’t replicate this on 2.4.2.

**Comment by Mexiguy** [comment]
2.4.2 I was having this issue from at least 2.3.6

**Comment by Mexiguy** [comment]
Still having this issue in 2.5.4
