### ISSUE TITLE
auto nsfw

### ISSUE THREAD

**Issue by mctavish23** [Kwoth/NadekoBot#1815]
The auto(hentai,boobs,butts) is acting like its non existent. Nadeko says that the command doesnt exist. Has it been removed or what?

**Comment by Kwoth** [comment]
![image](https://user-images.githubusercontent.com/2537696/32648795-c451b74a-c5f7-11e7-89ed-35a2eded684d.png)

**Comment by mctavish23** [comment]
ok thanks
