### ISSUE TITLE
.crypto errors

### ISSUE THREAD

**Issue by Jengas** [Kwoth/NadekoBot#1816]
Im getting sometimes this error. And to fix it i need to restart whole application (Bot)
![image](https://user-images.githubusercontent.com/14033756/32657665-dd89f596-c616-11e7-8327-ca5fd809da1c.png)

**Comment by Kwoth** [comment]
@Jengas is it really fixed after bot restart? Or does your bot die after that happens? I don't get it.

**Comment by Jengas** [comment]
I mean, sometimes this error happens (But other commands after this error still works). If i will restart and write _.crypto ICO_, this will work again. But in few hours this will happen again (Error). But with error bot works fine (Only that command gives error and not working)
