### ISSUE TITLE
Nadeko changing role perms for custom mute role

### ISSUE THREAD

**Issue by tukimoop** [Kwoth/NadekoBot#1818]
I believe Nadeko wasn't supposed to change channel role perms on mute roles that were set using `.setmuterole`, as mentioned by Zerg and having seen a 1.8 version of the bot before not changing channel roleperms with custom mute roles. However, on 2.3.6 (and presumably a few more versions before this one), the bot would change channel perms whenever `.mute` was passed.

Role perms changing:
![admin](https://user-images.githubusercontent.com/28344254/32689004-75726992-c72f-11e7-9206-d6d22f528421.gif)

Intended vs unintended effect of what most people want:
![user](https://user-images.githubusercontent.com/28344254/32689006-8473f5fa-c72f-11e7-8e26-75019d463307.gif)

**Comment by Kwoth** [comment]
fixed in 2.5.6
