### ISSUE TITLE
.novel returns error

### ISSUE THREAD

**Issue by ForgottenGlory** [Kwoth/NadekoBot#1819]
When running the .novel command, the bot returns 

0 10:39:17 CommandHandler | Command Executed after 0/0/1.063s
        User: ForgottenGlory#8407 [175794596750688257]
        Server: Myth Weavers [313509315627581440]
        Channel: botspam [313546530080423937]
        Message: .novel oathbringer
0 10:39:38 AnimeSearchService | System.NullReferenceException: Object reference not set to an instance of an object.
   at NadekoBot.Modules.Searches.Services.AnimeSearchService.<GetNovelData>d__5.MoveNext()
0 10:39:38 NadekoStrings | searches_failed_finding_novel key is missing from en-US response strings. PLEASE REPORT THIS.

Reporting as requested.

**Comment by Macley-Kun** [comment]
Can confirm, also get some error in Discord.
I assume were missing a string here?
