### ISSUE TITLE
Better !m pl (by niem)

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#182]
**Niem** - Last Wednesday at 5:34 PM
If possible, extended youtube playlist

Example: (If I have a list with 300 songs) I could use different options such as:
!m pl ~ http://www.youtube.com/playlist for either full pl or a one that queues the next 30 after first ones are done.
alternatively:
!m pl X http://www.youtube.com/playslist X indicating any number necessary (can be limited)

Don't know if this is doable, but wanted to point this out.
The current problem with this is that I can only listen to the first 30 songs in the playlist (and yes, I know I can shuffle those but it would be nice to have more queued and then I could for example shuffle)

**Comment by Kwoth** [comment]
i increased playlist load to 50 for now

**Comment by Mikethe3rd** [comment]
It's possible, lots of music bots did it.

**Comment by Kwoth** [comment]
I'll close this for now, see #286 

I rewrote the search and limit has been increased to 500, so i guess there is no need to this?
