### ISSUE TITLE
!overwatch command broken?

### ISSUE THREAD

**Issue by hemipatu** [Kwoth/NadekoBot#1820]
I am having issues using the **!overwatch** command where regardless of what variables I place into the Battletag and Region, the command just outputs the following;

> User not found! Please check the Region and BattleTag before trying again.

**Comment by sleepymanakete** [comment]
It seems to be working fine. Battletags are case-sensitive, are you typing it correctly?

**Comment by Kwoth** [comment]
As sleepymanakete said.
