### ISSUE TITLE
.activity broken on ja-JP langset

### ISSUE THREAD

**Issue by tukimoop** [Kwoth/NadekoBot#1821]
`.activity` is broken on the ja-JP langset for some reason or another. Can be reproduced by setting server language to Japanese (`.langset ja-JP`) then trying to use `.activity`. All other languages seem fine for the most part, though I might've missed some.

Console output:
![](http://puu.sh/ykbSW/612ccd5a81.jpg)

**Comment by MaybeGoogle** [comment]
For me, when I change it to ja-JP, it gives 
```
活動ページ＃1
I can't tell you if the command is executed, because there was an error printing out the response. Key 'utility_activity_line' is not properly formatted. Please report this.
1ユーザーの合計です。
```
And no errors in console.

tried the pull request, nothing changes.
