### ISSUE TITLE
.startevent reaction language problem

### ISSUE THREAD

**Issue by hank0531** [Kwoth/NadekoBot#1822]
![image](https://user-images.githubusercontent.com/24751265/32697362-c8c8978e-c7c9-11e7-8158-9379a1bc39f6.png)
![image](https://user-images.githubusercontent.com/24751265/32697366-d054df44-c7c9-11e7-8a83-cd805459a51c.png)
These two are different
Only **reaction** is valid
**flowerreaction** did not work

**Comment by MaybeGoogle** [comment]
seems like kwoth changed it but didnt change it for other languages...  bc it used to be called reactionevent instead of reaction. Someone not as lazy as me should change all of them :^)
