### ISSUE TITLE
ShardsCoordinator spawns a second instance

### ISSUE THREAD

**Issue by miraris** [Kwoth/NadekoBot#1823]
Apparently a 2nd instance gets spawned because the shard gets marked as unresponsive.
Here are the logs
![screenshot from 2017-11-12 17-48-08](https://user-images.githubusercontent.com/13337073/32701285-fc8f5504-c7d2-11e7-898d-38e182a015ca.png)
And the output of `.shardstats`
![screenshot_20171112-174217](https://user-images.githubusercontent.com/13337073/32701286-05fddaac-c7d3-11e7-9ac7-8cbc0f6072af.png)

**Comment by Macley-Kun** [comment]
Ya got the most recent version of nadeko? We fixed this before. Don't have this issue on linux.

**Comment by miraris** [comment]
Yes, I'm using the master branch the version was `2.4.2` when the issue happened.
Distro is Debian Jessie.

**Comment by MaybeGoogle** [comment]
same issue: #1747

**Comment by Kwoth** [comment]
Yeah, i'll look into this soon-ish, as google said, we'll track this issue in #1747

**Comment by MaybeGoogle** [comment]
@miraris what OS?

**Comment by miraris** [comment]
@MaybeGoogle Proxmox Linux container in a data center - yes it's always connected to the internet.
And the problem is still happening, spawned 3 instances recently.
