### ISSUE TITLE
NadekoBot.exe has stopped working for me

### ISSUE THREAD

**Issue by s7ana** [Kwoth/NadekoBot#1827]
![image](https://user-images.githubusercontent.com/32623755/32746447-428e0bb0-c87b-11e7-831a-8762468d36dc.png)

Anyone know what the problem here is? I most likely did something wrong when editing the bot but don't know where. I did recently update but don't think that's the problem. Any help would be welcome!

**Comment by shivaco** [comment]
Could you send a screenshot of your credentials.json file ~~with all API keys, token, etc. removed~~?

**Comment by s7ana** [comment]
![image](https://user-images.githubusercontent.com/32623755/32761348-7b339f74-c8b8-11e7-80b0-bfa81c114682.png)

**Comment by Kwoth** [comment]
When typing ownerIds, you need to separate them with `,` and don't put `,` after the last ID

**Comment by s7ana** [comment]
This is a late response but I've finally managed to find the problem thanks!

**Comment by Macley-Kun** [comment]
@s7ana glad to hear you were able to solve your problem! You can close this issue then if you have no future questions :-)
