### ISSUE TITLE
Bot won't log in 

### ISSUE THREAD

**Issue by Plushyyy** [Kwoth/NadekoBot#1828]
I'm using Windows 10 
This is what it looks like, it wont change 
![unknown](https://user-images.githubusercontent.com/33649009/32765958-a4b61ff8-c8c1-11e7-8a68-76edb1e64123.png)

**Comment by shikhir-arora** [comment]
Did you check your bot token and make sure it's correct in credentials.json?

**Comment by Kwoth** [comment]
Possibly firewall/proxy?

**Comment by Plushyyy** [comment]
I double checked the credentials and i allowed it on my firewall. 
![unknown](https://user-images.githubusercontent.com/33649009/32800133-65c4e71c-c92e-11e7-80ab-ecc488da0771.png)

**Comment by Macley-Kun** [comment]
@Plushyyy dunno if it might help, but try re-installing the dependencies again. Otherwise try another machine if your able to (to see if it's something on that particulier system your now using).

**Comment by Nekiono** [comment]
Discord had API outages lately. There it looked similar for me. Just try again now?

**Comment by Macley-Kun** [comment]
@Plushyyy still having this issue? Things aren't rlly settelt yet at Discords side. You tried my previous answer?

**Comment by Macley-Kun** [comment]
@Kwoth you can close this. It's bin dead for 10 days.
