### ISSUE TITLE
.warn command with customizable consequences (kick/ban/mute, timed) after flexible number of warnings.

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#183]

**Comment by Doyouwanttomakeacake** [comment]
I really like the idea!

**Comment by cryptochrome** [comment]
Excellent idea.

**Comment by Kexerval** [comment]
Perhaps after adding basic functionality of this feature, the ability to have the Bot Owner .warn by userid/chanid/guildid. This would allow the Bot Owner to warn guilds for misuse with levels such as temp blacklist, bot removal, and a flat-out blacklist.

**Comment by Kwoth** [comment]
`from High Tyhd's suggestion in discord`:

A warning command to warn people of certain offences. E.g
.warn @SomeGuy Mic Spam
Have the command add him to a server database that can be modified by admins.(edited)
---------
For newer people, you should add an auto-set-up config for what roles can do what commands e.g (In this hypothetical example, 30 is the most perms you can have 0 being the lowest);

Owner: 30/30 commands
Co-Owner: 26/30
Senior Admin: 21/30
Admin:  19/30
Junior Admin: 17/30
Moderator:  15/30
Trusetd: 3/30
------------- 
(Each line is a new message)

A set of commands where people can vote to;

- Mute
- Kick
- Ban
- Chat Disable

with admin approval e.g
.votekick (user) (reason)
.votekick @someguy "Mic spam"

(This is just the kick command, the other commands would like this)

.votemute/kick/ban/chat mute (user) (reason) (time) (time would be measured in seconds) 

.votemute/kick/ban/chat mute @someguy Spam 120

**Comment by Kwoth** [comment]
Just plain warnings will be added in 3-5 days. No votekicking and no warning 'weights'.

Pseudo-commands:
.setwarning 4 Ban
.setwarning 3 Kick
.setwarning 2 mute 

.warnclear SomeUser

Warnings would presist until cleared?

`.warn User` would warn the user, if he's at number specified by setwarning, appropriate punishment would be applied.

You can discuss the command names/behaviour here, I'll read it all before working on the command.

**Comment by cryptochrome** [comment]
"Warnings would persist until cleared?" - I would say yes, but add an option to make them time limited. For example: 

.warn @user "reason" (number of days)

If number of days is omitted, warning will be kept until cleared. If number of days is given, warning will be cleared after n days. But I guess that would be way more complicated to implement. Would need a scheduler that prunes warnings...

**Comment by Kwoth** [comment]
No to time limited warnings

**Comment by Kwoth** [comment]
Maybe have a setting on a guild level which tells how much warnings last for 🤔

**Comment by shikhir-arora** [comment]
Personally I think @Kwoth 's above is fine (`.warnclear` or the like) - only suggestion maybe have a lookup `.warnlog @user` which just lists any prior warnings.

**Comment by cryptochrome** [comment]
If time limited warnings are not an option, then no time limit at all and rather make it a manual process.

**Comment by shikhir-arora** [comment]
Time limited softban makes sense, but for warnings it's fine I think to just have it manually. Just having a log of all prior warnings and a warnclear option is how most moderation bots do it, so you can lookup if a user has been warned in the past.

**Comment by Kwoth** [comment]
ohhh warnlog idea is great

**Comment by Kwoth** [comment]
Just needs testing.

**Comment by MeetPing** [comment]
uhmm where is the code?
