### ISSUE TITLE
NadekoBot on a raspberry pi, .NET core SDK

### ISSUE THREAD

**Issue by lxtrem** [Kwoth/NadekoBot#1831]
hello !
I tried to install NadekoBot on my raspberry pi but when i press 4 to "Auto-Install Prerequisites (For Ubuntu, Debian and CentOS)", i got this issue :

`Your system architecture is armv7l which is unsupported to run Microsoft .NET Core SDK.`
Your OS: Debian 
OS Version: 9.1

Can you help me ?
thank you in advance,
lxtrem

**Comment by Deivedux** [comment]
I think you will find your answer here: https://github.com/Kwoth/NadekoBot/issues/1203

**Comment by lxtrem** [comment]
oh, you answer me berore i finished to edit my message

**Comment by lxtrem** [comment]
i didn' test all but my rpi is on debian, i'll finish the topic

**Comment by lxtrem** [comment]
Ok, i red all the topic and i didn't success...
Hope someone will have a solution...

**Comment by Jonz00r** [comment]
It's not officially supported so someone who has done it themselves will
have to help you.

**Comment by Macley-Kun** [comment]
@lxtrem assuming that you find your answer in here: #1203. You can close this issue :-)

**Comment by lxtrem** [comment]
I didn't success, can you say me which is the link follow ?
thanks

**Comment by Macley-Kun** [comment]
@lxtrem https://goo.gl/YnKdfQ
That will bring you to a Nadeko version that works on a raspberry pi.

**Comment by lxtrem** [comment]
Yes, i have already tryed but i don't have anithing in "publish" folder. It's totally empty. i have tryed the Windows Build too but i cannot use any dotnet commands...

**Comment by Macley-Kun** [comment]
I think you can better ask in that Github because not many of us use Nadeko this way. The people on that Github have more experience hosting Nadeko on a Pi.

**Comment by lxtrem** [comment]
yes, you're right... i have created a new topic : https://github.com/Taknok/NadekoBot/issues/6

**Comment by Macley-Kun** [comment]
allright you can close this one then :-)
