### ISSUE TITLE
.xp doesn't show unicode characters on image

### ISSUE THREAD

**Issue by TiBarification** [Kwoth/NadekoBot#1832]
How it works:
![default](https://user-images.githubusercontent.com/6222472/32847744-882de88e-ca33-11e7-9c90-24605205b331.png)

**Comment by Kwoth** [comment]
This is because the drawing library I'm using doesn't support drawing unicode characters :c

**Comment by Macley-Kun** [comment]
Should we make an issue on the library your using instead? Because even with help this is out of your doing :P

**Comment by coconut24** [comment]
the problem is within the font, the drawing library will draw nothing if the font doesnt support the characters

**Comment by Macley-Kun** [comment]
Tested this out on NadekoBot v2.10.1. Still present.

**Comment by Macley-Kun** [comment]
Kwoth, can you make an issue on the drawing library and ask if they wanna add unicode characters?

**Comment by Macley-Kun** [comment]
Update:

Rjt suggested to use Noto Sans. This font supports more characters what should solve this issue.

**Comment by florian-kaiser** [comment]
What about just using the Arial font? I tested it and it draws the unicode character perfectly

**Comment by Kwoth** [comment]
Nice try, but it doesn't work properly, and having the single font be huge % of the size of the whole bot is not viable. It works sometimes but most of the time not. It's better than what we currently have for sure, but definitely not worth it.

![image](https://user-images.githubusercontent.com/2537696/37268142-0f4a6b98-25f7-11e8-9102-0e865f15607f.png)

**Comment by Kwoth** [comment]
Tried it, it's not the font, it's the fact that the library has issues drawing them I believe.

**Comment by kronoize** [comment]
What library is it drawing from? Because you can always just download Microsoft IMEs for the languages most commonly used in the usernames like JP and minimize storage or download all of them with more compatibility with usernames at the cost of more storage.

Though if you're already using it and it's still having problems with drawing from it, just ignore this message I guess.

**Comment by zMatix** [comment]
How to change background like you?
