### ISSUE TITLE
Changes to command_strings.json not reflected at runtime

### ISSUE THREAD

**Issue by Warped2713** [Kwoth/NadekoBot#1833]
## Context

I just upgraded a self-hosted bot (on Windows) from v1.8.4 to v2.4.2

In the 1.8.4 version, the CommandStrings.resx was customized to rename `plant` as `drop` and this was reflected correctly when the bot came online.  Since upgrading to 2.4.2 and modifying the `command_strings.json` in a similar fashion, the `.cmds games` command still uses the original command string, `plant`.

## Reproduction

1. In a branch copy of tag 2.4.2, edit `command_strings.json` to rename `plant` to `drop`
2. Do `dotnet run -c Release`
3. When the bot comes online, type `.cmds games`

**Comment by Kwoth** [comment]
Can you tell me the exact change you're making?

You're supposed to edit the "cmd" part, not the key name part.
"plant":{"cmd":"drop" ... }

**Comment by Warped2713** [comment]
Ah that was it! An oversight on my part.

I had replaced every instance of `plant` instead of just the parts that mattered.

Thanks Kwoth!
