### ISSUE TITLE
.hentai throws HttpException (code 503)

### ISSUE THREAD

**Issue by Kyousei** [Kwoth/NadekoBot#1835]
Doing `.hentaibomb` on self hosted bot (`v2.4.3`) throws this error.
![image](https://user-images.githubusercontent.com/29898563/32866465-4b3ded18-ca68-11e7-9f80-d9a9431b08d2.png)

It worked on the earlier version, it no longer does.
Any fix?

**Comment by MaybeGoogle** [comment]
working for me on 2.5.1

**Comment by coconut24** [comment]
most likely because of the sites getting blocked by your isp, try changing your dns to a public one

**Comment by coconut24** [comment]
most likely because of the sites getting blocked by your isp, try changing your dns to a public one

**Comment by Macley-Kun** [comment]
@Kyousei just tried it too, works just fine. I think your requesting to much hentai :33
Is it still not working for you after +/- 12 hours?

**Comment by shikhir-arora** [comment]
Yes a 503 error is typical when you are temporarily blocked due to excessive use.

**Comment by Kyousei** [comment]
Yeah, really never used it LOL.
I tested it this one time when someone said it wasn't working on public Nadeko.
Also, the bot's hosted on a VPS.

**Comment by Macley-Kun** [comment]
Maybe the hoster disabled reaching hentai sites? Tried to ping to the site maybe?

**Comment by Kyousei** [comment]
I doubt the hoster disabled hentai sites :Think:
Anyways, it's probably one of those "excited" people using my bot in a different server.
Maybe they're spamming it.
I'll take that as the conclusion :^)
