### ISSUE TITLE
.gmod music doesn't disable .cmds music

### ISSUE THREAD

**Issue by Macley-Kun** [Kwoth/NadekoBot#1836]
So i disabled the music module but noticed when i issue .cmds music the list of commands appear.
![schermafbeelding 2017-11-16 om 15 31 10](https://user-images.githubusercontent.com/26381427/32896511-7b0876c8-cae3-11e7-95b4-8ceb5c674130.png)
Kuromu, Kyousei and Deivedux concluded this is a bug :-)

**Comment by Kyousei** [comment]
The fact that the command `.cmds music` gets through and the bot shows all commands for music module, while it doesn't on public Nadeko, is questionable 🤔

**Comment by Kwoth** [comment]
O.o, you can prevent commands with specific arguments from executing. 

If you really want to, just make a global custom reaction with a message that it can't be executed.

**Comment by Kyousei** [comment]
Ah, that explains it
