### ISSUE TITLE
.defprefix doesn't show the def prefix w/o arguments

### ISSUE THREAD

**Issue by Kyousei** [Kwoth/NadekoBot#1837]
Doing `.defprefix` will return this:
![image](https://user-images.githubusercontent.com/29898563/32897510-24570b2a-cae6-11e7-9908-9efd77ede72c.png)

While the command description says it should return the default prefix, just like `.prefix`
![image](https://user-images.githubusercontent.com/29898563/32897143-193b82ee-cae5-11e7-8911-4e5c46237bd4.png)

**Comment by Kuromu** [comment]
Created PR to fix this, see #1839
