### ISSUE TITLE
Gelbooru 404 Not found

### ISSUE THREAD

**Issue by GinzaJ** [Kwoth/NadekoBot#184]
in the newer version of Nadekobot when i use the "~gelbooru" command and i get this error , Anything Lower than NadekoBot v0.8 b14.2 works perfectly
Heres The Screen Capture of the error
http://meowmichi.s-ul.eu/QiHDApxa

**Comment by Kwoth** [comment]
That error has been there always. Its not introduced recently. Most likely removed images from gelbooru getting pulled.
