### ISSUE TITLE
Currency image bug?

### ISSUE THREAD

**Issue by Nihagi** [Kwoth/NadekoBot#1843]
When you have too many files or too large file in currency image folder,
The bot will throw a timeout error and crash before ever starting up.

Not sure on what update this happened since i only just updated from 1.x to 2.x
https://media.discordapp.net/attachments/117523346618318850/381065963434672128/unknown.png
The error I get.

When i delete the larger files and keep below 49 images it works

**Comment by shikhir-arora** [comment]
How much memory does your computer/server have? Images are cached to Redis, which is a fully memory based key-value store. That makes things faster, but there are also inherent limits to a memory based cache.

**Comment by Nihagi** [comment]
16gig ram.
Never had this problem before, on the older version.
It also used Redis at that point.

**Comment by shikhir-arora** [comment]
Yes, but the cache for images (including currency) was not introduced until later -- I believe version 2.2.x or so.

**Comment by Nihagi** [comment]
Any way to increase the ram usage limitation then?
I doubt its bottle-necking 16gig right after a reboot..

**Comment by shikhir-arora** [comment]
Not entirely sure. There may be a way for @Kwoth to add something like `throwOnError="true" retryTimeoutInMilliseconds="500"` to the connection string of the provider to retry on timeout for Redis, but will leave it for him to check.

**Comment by Nihagi** [comment]
Aight. Will wait for a possible future update.
keeping the folder a bit smaller till then.

**Comment by coconut24** [comment]
have you tried to increase your redis memory limit? its 100mb by default

**Comment by Kwoth** [comment]
@Nihagi it's what coconut said, you need to increase your redis memory limit. I can't change that for you.
