### ISSUE TITLE
.Wheel 1 glitch Windows 2.5.2

### ISSUE THREAD

**Issue by Loesna** [Kwoth/NadekoBot#1844]
On a self hosted NadekoBot (Windows 2.5.2), you can do a .wheel 1, thus giving you a pretty big chunk of flowers
![capture](https://user-images.githubusercontent.com/33760121/32960351-dff3a846-cbc4-11e7-9260-47f2e667039f.PNG)
(First Nadekobot is Public, second is my Self Hosted)

**Comment by NeKyou** [comment]
.wheel 1 hardcoded as .wheel allin on 2.5.4

**Comment by Loesna** [comment]
the multiplier seems broken tho, 1 * 0.2 isn't 17

**Comment by NeKyou** [comment]
well you probably have more than 1 flower on your self host
