### ISSUE TITLE
Cant gain XP

### ISSUE THREAD

**Issue by Jengas** [Kwoth/NadekoBot#1845]
Science 2.4.2 update, me and my server noticed that they stopped to gain any XP for chatting. I checked everything but `.bce` command i didnt touch science XP added, There are no channels that Exclude from XP gain.

**Comment by Deivedux** [comment]
I can not reproduce the issue... Both on public Nadeko and self-hosted I can gain xp as intended. 🤔

**Comment by Jengas** [comment]
![image](https://user-images.githubusercontent.com/14033756/32969639-26d48624-cbe6-11e7-8a93-501f6902007d.png)
![image](https://user-images.githubusercontent.com/14033756/32969641-2b5e7132-cbe6-11e7-8032-7c2c8937ef75.png)
After 10 minutes of chatting. I still have same XP

**Comment by Deivedux** [comment]
The only assumption I have, this is because of the discord crash (which is still happening). The API is very slow at the moment, so if you could, please try again in a few moments when discord will be back to normal.

**Comment by Jengas** [comment]
Still cant gain
![image](https://user-images.githubusercontent.com/14033756/32979309-1238ecd8-cc53-11e7-9b27-c0b2b7f361e6.png)
I did almost 600 messages. But still did not get

**Comment by Kwoth** [comment]
1. stop your bot
2. go to `C:\Program Files\redis\` and open `redis-cli.exe`
3. type `FLUSH ALL` press enter, close
4.  start your bot

**Comment by Jengas** [comment]
![image](https://user-images.githubusercontent.com/14033756/32980196-9705a014-cc62-11e7-8ec2-a9fc60fe0c8e.png)
Doest work

**Comment by Jengas** [comment]
Fixed after 2.5.5
