### ISSUE TITLE
Can't use .prune/.clear command

### ISSUE THREAD

**Issue by sinnamonbunnii** [Kwoth/NadekoBot#1846]
![image](https://user-images.githubusercontent.com/33297884/32970020-20ff7014-cb9c-11e7-9105-ed715bed639b.png)

Each time I use it it says this... help?

**Comment by shikhir-arora** [comment]
Strange...it does this in every channel? Also, what version are you running? (type `.stats` to check)

**Comment by Macley-Kun** [comment]
Also your bot has permission to delete/manage messages?

**Comment by Macley-Kun** [comment]
@Kwoth Close? Person hasn't responded in 2 weeks.
