### ISSUE TITLE
Betting a single flower in '.bf' and '.wheel'  would instead bet every flower

### ISSUE THREAD

**Issue by tukimoop** [Kwoth/NadekoBot#1847]
As the title states, betting a single flower (or currency) in either the `betflip` and `wheel` gambling modes would instead invoke `allin` for some reason. Does not happen on `slot` or `br` however.

Setting `MinimumBetAmount` to 0, 1, or any number does not affect the output of the bug. 

![](https://i.imgur.com/dY8WUAi.png)

**Comment by Kwoth** [comment]
Already fixed, wait for next update for windows.
