### ISSUE TITLE
Multiple Messages Sent at Once

### ISSUE THREAD

**Issue by TwinDragon** [Kwoth/NadekoBot#1848]
Not sure how to properly title it, but this is what's going on since Discord has been having issues today and due to that, I think I might partially know where the bug is occurring.

https://cdn.discordapp.com/attachments/317197568926810112/381253457446830080/unknown.png

What's going on I think is that when the bot gets disconnected from the shard via whatever force, either Discord having issues, or maybe my network on occasions... It reconnects, but it leaves behind a "ghost" of sorts and it just builds up until I restart the bot. Normally I just end up terminating the bot and restarting it that way without using a **.restart** command. I do not have a picture of the processes running on my Debian box at the moment, but I have seen instances where I've seen several instances of _/bin/bash/linuxAIO.sh_ or similar running at once. Next time I see it happen, I'll be sure to take a snapshot of it; just slipped my mind for this occasions.

This was done with the latest source I downloaded about 2 hours prior.

**Comment by shikhir-arora** [comment]
Yes, this happened beause Discord went down earlier today and is having some issues. But anyway, to fix this, just go into your console in Debian, type `ps aux | grep linuxAIO` and find the process ID of anything that shows up. Then do: `kill -KILL <id>` where <id> is the process ID (like `kill -KILL 12939`).

Then do `ps aux | grep dotnet` and find any running dotnet processes and kill them the same way.

The bot will be completely offline at this point. Then you can go ahead and start it up normally and it shouldn't do that anymore.

**Comment by Gremagol** [comment]
Yeah thanks for this fix, I hope this gets fixed in nadeko's side.

**Comment by TwinDragon** [comment]
I wouldn't really call it a fix, just a work-around to the issue. Restarting the bot doesn't take me long or anything, but I still think that since the code was added for restart and reconnecting was added probably compounded to the issue; as opposed to the bot silently going dead when Discord servers act up.
