### ISSUE TITLE
.bf 1 goes all in

### ISSUE THREAD

**Issue by d-floe** [Kwoth/NadekoBot#1849]
for the latest update when youre doing betting 1 on betflip it goes all in
![image](https://user-images.githubusercontent.com/31980883/32978396-2d9d05a0-cc07-11e7-8791-9aff3cb71cee.png)
I even set the minimum bet to 2 and it still goes all in

**Comment by shivaco** [comment]
Was already reported, the answer is in [this issue](https://github.com/Kwoth/NadekoBot/issues/1847)
