### ISSUE TITLE
Shard in disconnected state loop.

### ISSUE THREAD

**Issue by Smileynator** [Kwoth/NadekoBot#1852]
Running the bot on linux after a day or 3 it went into a disconnected loop and never recovered. I had to go in an manually reboot the bot.

**Comment by Kwoth** [comment]
Discord had an outage last day. Shouldn't happen usually.

**Comment by Smileynator** [comment]
Well, they had another outage just now. Kind of would be handy if you could make it re-attempt connections at a lower interval if it doesn't get back in immediately? Like once per 5min?

**Comment by Smileynator** [comment]
Well, it seems like the issue is still here. Discord had another outage (3 or 4 over the past month or 2) http://puu.sh/yR2WJ.png This is getting annoying. @Kwoth

**Comment by Demon1986** [comment]
i agree, it's pretty annoying to have to restart it manually because of discords downtime / outage. other bots can easily reconnect themselves, so why can't nadeko figure it out?
