### ISSUE TITLE
Music Silent - Windows 2012 R2 (Windows 8 Server)

### ISSUE THREAD

**Issue by MoriartyFive** [Kwoth/NadekoBot#1855]
I'm trying to have my bot play music in my server, the commands run fine and the console shows that it loaded the song with no errors but when the bot joins the channel it's just silent.

I'm hosting the bot on a Google Cloud Server running Windows 2012 R2 (Windows 8 but as a server), so I'm not sure if that's the issue. I've installed FFMPEG, YouTubeDL, Redis, and the Bot through the installer as well as Microsoft Visual C++ 2010 Redistributable Package (x86) & Microsoft Visual C++ 2010 Redistributable Package (x64)

The songs I'm trying to play are also files downloaded directly to the computer, but the issue persists from music queued from YouTube ETC.

![untitled3](https://user-images.githubusercontent.com/33775358/32985237-04118074-ccae-11e7-838f-d8e72deaff08.jpg)

**Comment by Macley-Kun** [comment]
We got a speciale issue on the bottom of the page here were you post your issues to.
Could you try to re-ask there?

**Comment by MoriartyFive** [comment]
>We got a speciale issue on the bottom of the page here were you post your issues to.
Could you try to re-ask there?

The "post music issues here"? one, cause otherwise I don't see a special issue section.

**Comment by MoriartyFive** [comment]
Closing: Moved to post music issues here.
