### ISSUE TITLE
Quotes Sorted by Number, Heroku support

### ISSUE THREAD

**Issue by microsoft-Word3027** [Kwoth/NadekoBot#1857]
More of a Suggestion or along the lines of a discussion, Is there anyways for the the bot to sort the quotes by number instead of having all of the quotes weirdly sorted, This could help a lot when looking for a certain quote. Also is there anyway That I can self host the bot on heroku because people have told me it’s no longer supported and I just want to run the bot

**Comment by shikhir-arora** [comment]
> More of a Suggestion or along the lines of a discussion, Is there anyways for the the bot to sort the quotes by number instead of having all of the quotes weirdly sorted, This could help a lot when looking for a certain quote. 

I already added this feature a while back but it wasn't wanted at the time. If @Kwoth wants me to re-open and add it, it's already basically done. It will sort them for a specific keyword and those would be in numerical order. Here's the old PR: https://github.com/Kwoth/NadekoBot/pull/1178

Not sure about Heroku, I think someone was working on setting it up.

**Comment by shivaco** [comment]
ScarletKuro has been working on Heroku support, although, not anymore. Not sure about the reason, probably lost motivation

**Comment by Macley-Kun** [comment]
Kuro needs to rewrite alot of code to get from 1.3b to the newer version.
He also stated that the bot works for him as he likes it to be. So he would only update his bot if a feature comes out that he would really want.

He only shares his code and is kind enough to provide the steps how to do it. He has no need/requirement to update to a newer version if his needs are already satisfied.

**Comment by shikhir-arora** [comment]
Fair enough - @Kwoth let me know if you wish and I can get this request squared away, as it’s already mostly done from that old PR #1178 minus updating for the new structure.
