### ISSUE TITLE
Perm hierarchy problems

### ISSUE THREAD

**Issue by SillyBirds** [Kwoth/NadekoBot#1859]
I'm on 2.5.6 and I just noticed that some perms don't take into role hierarchy.

My example is that I'm using `.rc .prune disable Members` to restrict prune usage, but it's affecting staff that share that role but also have higher roles, even one that has `.arm enable Admins` and shouldn't be restricted.

Unless it's intended to work this way? how can I get around to having a staff user that has two roles, a lower one with restrictions and an higher one that overrules those same restrictions?

Thanks in advance for your help.

**Comment by Kwoth** [comment]
.arm enable Admins should be above the `.rc` one, and it will work. Permissions only respect their own hierarchy, not role hierarchy.

**Comment by SillyBirds** [comment]
When you say higher, you mean by display or number? Because `.arm` is 9 and the `.rc` ones are 19-21.

![image](https://user-images.githubusercontent.com/22528910/33007621-dd52cae2-cdcf-11e7-9f1c-4f6d4171dc99.png)

**Comment by shikhir-arora** [comment]
`.arm` is for Modules,  `.rc` is for commands at the role level.

`.rc .prune enable Admins (who admin nothing)` and making sure that's higher up should fix it...

**Comment by Kwoth** [comment]
Higher number, yes. 9 is overridden by the ones with the higher number

**Comment by SillyBirds** [comment]
Great, thanks!
