### ISSUE TITLE
Having spaced prefix 

### ISSUE THREAD

**Issue by arronlim13** [Kwoth/NadekoBot#1860]
I'm not how am I going to explain this but basically I'm trying to set my bot's prefix to "!bot " with a space at the end but I can't get it to work. If I do .prefix "!bot ", it actually set the prefix to "!bot ". Is there any way to add the space at the end of the prefix?

P.S. it is possible to do it on the old version of nadeko by changing the .db file.

**Comment by shikhir-arora** [comment]
You probably have to do it in the database. Did you try that as you said? The prefix change command probably sanitizes it first.

**Comment by arronlim13** [comment]
There's a data(?) in the database called ModulePrefixes on the old version of nadeko (.Net 1.0) but it doesn't existed on the current one (.Net 2.0)

**Comment by shikhir-arora** [comment]
The default prefix is set under `BotConfig --> DefaultPrefix` and the prefix per-guild is set in `GuildConfigs --> Prefix`

**Comment by arronlim13** [comment]
Oh I didn't check the BotConfig data, thanks!
