### ISSUE TITLE
.antispam can't be modified with ignored channels

### ISSUE THREAD

**Issue by zergling-man** [Kwoth/NadekoBot#1864]
Setting up any ignored channels in antispam causes you to be unable to modify the current message count/action. You can disable it still, and then enable anew, which strips all ignored channels.

**Comment by Macley-Kun** [comment]
Shouldn't this one belong in the feathub? http://feathub.com/Kwoth/NadekoBot?

**Comment by zergling-man** [comment]
If you can show me the line in the documentation that says "cannot be modified while channels are ignored".

**Comment by Macley-Kun** [comment]
I assume you ask this to Kwoth..?

**Comment by zergling-man** [comment]
I ask it to anyone who would classify it as a feature request, not a bug report.
