### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by YuriQS** [Kwoth/NadekoBot#1865]
I got an audio issue with the music function. I follow the step to make the bot write here "https://nadekobot.readthedocs.io/en/latest/". I have windows os.

0 16:07:50 MusicService | Done creating
0 16:07:50 <GetResolveStrategy>d__2 | Getting link
0 16:07:55 CommandHandler | Command Executed after 0/0/4,906s
        User: *********** [*******************]
        Server: ****** [******************]
        Channel: ***** [******************]
        Message: .q https://youtu.be/x5XIXl1zfyM
0 16:07:55 MusicPlayer | Starting
0 16:07:59 MusicPlayer | Connecting
0 16:08:00 MusicPlayer | Got Audio client
0 16:08:00 MusicPlayer | Created pcm stream

the bot joins the vocal channel and shows the message "Playing song" but it doesn't play audio. Someone can help me?

**Comment by Macley-Kun** [comment]
Please use the issue made to submit music issue's: #1053. Close this one and re-ask there :-)
