### ISSUE TITLE
Nadeko opens multiple shards when discord has trouble

### ISSUE THREAD

**Issue by borgqueenx** [Kwoth/NadekoBot#1867]
It would be great if nadeko self checks how many shards are running for a single server and kills secondary shards. When discord has trouble, it opens multiple instances without closing others. This makes everything executed multiple times.

For example a .give command executes for how many shards there are. It went so crazy as 7 shards running at the same time with discord's big trouble a couple days ago.

I know that a restart fixes this, but that requires the administrator to be there. It is a bug after all, so im reporting it in the hopes of it getting fixed sometime :)

**Comment by samdivaio** [comment]
It is known and Kwoth is already working on a permanent fix, if you wanna try something you can check out [this comment](https://github.com/Kwoth/NadekoBot/pull/1863#issuecomment-345911683) by @shikhir-arora and use the fix if you are on Linux or running from source codes on Windows.

**Comment by coconut24** [comment]
its caused by dotnet run having a child process to run the executable on. nadeko only kills the parent process, leaving the child process free and running
