### ISSUE TITLE
Music won't queue

### ISSUE THREAD

**Issue by Namaarie** [Kwoth/NadekoBot#187]
When I queue a song, it doesn't queue, it just gives me this error:
https://gyazo.com/56cd2483077dd3feb14e91443d3df074
I've tried redownloading ffmpeg, new versions of Nadeko, and using a different google api key. Nothing seems to work

**Comment by Darklight-03** [comment]
Try a different song, I was getting that error before, but it was only for some certain songs (still possibly a bug, but some songs should work)

**Comment by Kwoth** [comment]
Yep, its the youtube video library throwing that exception, nothing i can do, a lot of people started getting that error since yesterday. Maybe google changed something. If they did, library will get updated and it will work better in the next release. Only thing we can do is wait.
