### ISSUE TITLE
NadekoBot isn't reponding to any commands

### ISSUE THREAD

**Issue by paradoxWanted** [Kwoth/NadekoBot#1871]
Hi NadekoBot not responding to commands

**Comment by Macley-Kun** [comment]
Try turning it off and on again.

**Comment by paradoxWanted** [comment]
Do you work in IT, that is some Rick and Morty level IQ response?

**Comment by shivaco** [comment]
Public Nadeko bot is having issues with shards, which means it is offline on *some* servers

**Comment by Macley-Kun** [comment]
@paradoxWanted we have #support for questions about public/selfhost bot. If you ask a question here we expect you to say more then just:"NadekoBot not responding to commands". Error log, screenshots and most importend wich version of NadekoBot (selfhosted/public & version of the bot you use if it's selfhosted).

**Comment by paradoxWanted** [comment]
Thank you shivaco. Great response. Mackley-Kun I have literally seen a similar question here before and no problem was giving, if I am in the wrong section you could have politely pointed me in the right direction.

**Comment by shivaco** [comment]
@Macley-Kun ~~It is #help, not #support~~ >.>

**Comment by Macley-Kun** [comment]
:feelsgood:
