### ISSUE TITLE
Nadeko seems, unresponsive currently? 

### ISSUE THREAD

**Issue by Chrozzy** [Kwoth/NadekoBot#1872]
Well I wanted to edit something in the options but Nadeko doesn't respond at all, not only on my server.

**Comment by Macley-Kun** [comment]
@Chrozzy don't worry buddy, Kwoth should be working on getting the Public NadekoBot up again. See #1871 :-)

**Comment by Chrozzy** [comment]
Alright, thanks @Macley-Kun !

**Comment by Kwoth** [comment]
shards are being restarted.
