### ISSUE TITLE
Probably a client issue, but...

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#1873]
Just watch the video. https://midorina.ga/u/d2f84183f6.webm
- Volume command is not related to this issue.
- No matter If the bot is playing a song in the other server or not, It just needs to be in a voice channel for this to happen. (.destory has to be executed properly)
- Song does not stop for others. Happens to the person who uses `.d` in the other server.

**Comment by Kwoth** [comment]
Yeah, this happens for a year now, or more. Not sure what to do about it.

**Comment by Macley-Kun** [comment]
Add the tag help wanted :3 ?

**Comment by Macley-Kun** [comment]
Does this have to do with the Discord library? Ccan we make an issue at Discord themself?

**Comment by Kwoth** [comment]
I'll just close this to keep the tickets clean
