### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by TheHoodiniGamer** [Kwoth/NadekoBot#1876]
How do I change the currency name in my server?

**Comment by shivaco** [comment]
`.bce CurrencyName Dollar`
`.bce CurrencyPluralName Dollars`
Change `Dollars` with whatever you need.
If you want to change the emote:
`.bce CurrencySign :EmoteHere:`
Make sure you use self-hosted version/instance of Nadeko, otherwise it won't work :smile:

**Comment by shivaco** [comment]
~~Also, GitHub should be used for issues (bugs, etc.). If you need help with Nadeko, then check out #help in [NadekoBot support server](https://discord.gg/nadekobot).~~
