### ISSUE TITLE
~e621 doesn't return results for some tags

### ISSUE THREAD

**Issue by lunarlabs** [Kwoth/NadekoBot#188]
For the ~e621 command, the bot does not return an image, nor does it return a failure code.

**Comment by Kwoth** [comment]
Its not helpful "for some tags". In any case, it does seem to work for me for the tags i tried.

**Comment by lunarlabs** [comment]
try zach_(gamerfox) or sled_(sledmetodeath)

**Comment by Kwoth** [comment]
this was fixed in #193 , say thanks to @GoBJIuH
