### ISSUE TITLE
Gelbooru API

### ISSUE THREAD

**Issue by TwinDragon** [Kwoth/NadekoBot#1880]
This is something to think about in the future since that stupid owner keeps doing things to piss off some users.

It appears right now the API for Gelbooru is down and there's no real timeframe on when it could reappear. One server I have the bot in, no matter what term I use, will always show with "No results found." - however, the strange part is on my main discord server, it works perfectly fine, even with the same exact tag.

I have looked into the console to see, but there was nothing out of the ordinary. It appears it searched fine in the "broken" server, but of course it really didn't.

**Comment by Kwoth** [comment]
it cached some images, so it will work until it spends them or until you restart the bot. Seems api really is down.

**Comment by TwinDragon** [comment]
This is just an idea of a workaround; dirty, but it works to some extent.

One of my friends wrote it in Python at one point and he's going to re-write it into C# soon when he gets to it. But his method was to scrape the links to a direct image or something which also could be used to bypass Danbooru's paywall to some content.

Whether or not that'll explored is up to you, but figured I'd suggest it because I don't know what that "owner" of Gelbooru will do with the API's if it ever comes back online and is then restricted.

**Comment by miraris** [comment]
The API isn't behind a paywall. He clearly states that the API may have downtimes due to search engine load. Also the API response has a `file_url` property, so there's no need to "scrape the links to a direct image" - `file_url` is a direct URL to the image.
https://gelbooru.com/index.php?page=help&topic=dapi

**Comment by TwinDragon** [comment]
I never said the API was behind a paywall.

If you read, I said to "bypass Danbooru's paywall to some content" and said nothing about the API.

Now, one of my friends already found it will no longer work anyway because Danbooru has changed the way the site operates and you can no longer scrape the images as previously.

**Comment by miraris** [comment]
I just made a few requests and the response seems identical.

Which "content behind a paywall" are you referring to?

**Comment by TwinDragon** [comment]
Two tags on Danbooru are paywalled: loli and shota. The API won't return those. There was a way to bypass it, but that loophole was closed.

**Comment by Macley-Kun** [comment]
@TwinDragon so suggest we warn the user if they use the tags: loli and/or shota?

**Comment by shikhir-arora** [comment]
@Macley-Kun  - I don't think that will be necessary because I'm not able to replicate this just like @miraris is not having any issues.

---

> Now, one of my friends already found it will no longer work anyway because Danbooru has changed the way the site operates and you can no longer scrape the images as previously.

@TwinDragon I don't see the issue either. Both of those work fine.

<img width="1414" alt="screen shot 2017-12-23 at 6 48 43 am" src="https://user-images.githubusercontent.com/8797918/34319332-783bbe64-e7ad-11e7-86fa-429651fb7adf.png">
<img width="1397" alt="screen shot 2017-12-23 at 6 47 34 am" src="https://user-images.githubusercontent.com/8797918/34319333-7845d2fa-e7ad-11e7-9e4d-5a281adaae90.png">


I didn't look into this more than just that; but the data looks completely normal. It's just standard JSON and in no format that seems like it would be off. You can view the images above in full-size to get a closer look.

**Comment by TwinDragon** [comment]
Well I have a gold account so I can see them. But the normal API Nadeko uses is the standard API which will not return any tag paywalled basically. This only applies to Danbooru though.
https://i.imgur.com/wX7o5f9.png

The API response will return something, of course, but if its a tag that is blacklisted in the API, the result will be null basically. I made a suggestion that was already denied about adding in a call to the credentials where one could input their own API key if they wish to call into the URI if one is available. Because it was denied, I'm having to get someone else do that for me at some point in the future.

**Comment by shikhir-arora** [comment]
You’re right that the command in Discord errors. I’ll have to take a look at it. It seems to work fine and I don’t have any gold API or anything. Even an unautjentkcated GET works just fine...I just used [hurl.it](https://hurl.it) to make a basic unauthenticated GET.

![e8e33861-39d5-4fd6-a3d2-2f54c8c15c0f](https://user-images.githubusercontent.com/8797918/34322322-01d37a9c-e7f2-11e7-83c6-b4646e927f0c.jpeg)

**Comment by shikhir-arora** [comment]
Sorry I meant shota there. But same idea. Anyways will try to se why this happens.

**Comment by TwinDragon** [comment]
Yeah, that's why I suggested that in the credentials, add in two parameters: _danbooru\_id_ and _danbooru_api_ - That way in the URI it passes to Danbooru, if it includes the ID and API of a Gold account, it'll recognize it and return as normal. This way, those who do not wish to see it can use the normal API still of the main bot itself.

I'm not in any hurry for the changes, I have another bot in my server coded by someone I know a little and letting him use my API key for it. If I knew anything of C#, I'd do it myself, but there were reasons I got out of programming pretty early when HTML and CSS evolved since 4.1 to be a little too complicated for me to follow.

**Comment by shikhir-arora** [comment]
But I’m not using any gold account here I’m using the same GET request unauthenticated - like you can just visit that link and it’ll surely return tuns of results for loli and shota. So I’ll take a look how it’s done closer on Nadeko. I’m literally sending an open GET - no key at all with testing it on Hurl.it

**Comment by Kwoth** [comment]
Nothing I can do about this. It's disabled.
