### ISSUE TITLE
.race question

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#1884]
Isn't the winner supposed to get all betted flowers? When someone wins a race, they just get their flowers back, or don't get anything If they did not bet, even though there are other players that bets flowers. ??

**Comment by ronelm2000** [comment]
As far as I know that isn't in the use case of .race (if anything, you should use .rafflecur for that.)

This can be a FeatHub ticket too.

**Comment by Jonz00r** [comment]
People can bet different amounts so it wouldn't really be right if someone
bet two on a pot of a couple hundred and got it all.

**Comment by Kwoth** [comment]
.h .jr

**Comment by Midoriin** [comment]
Thanks kwoth 👍
