### ISSUE TITLE
.gc won’t work

### ISSUE THREAD

**Issue by Jackdwarf2002** [Kwoth/NadekoBot#1885]
I made sure to do the .permrole part right, and when I type I the command, nothing happens. It doesn’t say what’s wrong with it either.

**Comment by Kuromaru420** [comment]
.gc, .award and .startevent are bot owner-only commands, so they don't work on public Nadeko.

**Comment by Jackdwarf2002** [comment]
Then how exactly do I get currency?

**Comment by coconut24** [comment]
How to get flowers on public Nadeko?
1.- Flower reaction events: Randomly in #announcements —every 1 or 2 days— there are events where you add a :cherry_blossom: reaction and get flowers.

2.- Picking in #chat-safe channels: Each message sent on this server's #chat-safe channels has a 2% chance of spawning 5 flowers which you pick with .pick

3.- Donating to Nadeko's Patreon: Donations award a ratio of 100 flowers per dollar.

Flower reaction events and spawns is on the [support server](https://discordapp.com/invite/nadekobot)
if youre still having issues with commands, feel free to ask in the support channel

**Comment by coconut24** [comment]
How to get flowers on public Nadeko?
1.- Flower reaction events: Randomly in #announcements —every 1 or 2 days— there are events where you add a :cherry_blossom: reaction and get flowers.

2.- Picking in #chat-safe channels: Each message sent on this server's #chat-safe channels has a 2% chance of spawning 5 flowers which you pick with .pick

3.- Donating to Nadeko's Patreon: Donations award a ratio of 100 flowers per dollar.

Flower reaction events and spawns is on the [support server](https://discordapp.com/invite/nadekobot)
if youre still having issues with Nadeko, feel free to ask in the support channel

**Comment by coconut24** [comment]
How to get flowers on public Nadeko?
1.- Flower reaction events: Randomly in #announcements —every 1 or 2 days— there are events where you add a :cherry_blossom: reaction and get flowers.

2.- Picking in #chat-safe channels: Each message sent on this server's #chat-safe channels has a 2% chance of spawning 5 flowers which you pick with .pick

3.- Donating to Nadeko's Patreon: Donations award a ratio of 100 flowers per dollar.

Flower reaction events and spawns is on the [support server](https://discordapp.com/invite/nadekobot)
if youre still having issues with commands, feel free to ask in the support channel

**Comment by coconut24** [comment]
How to get flowers on public Nadeko?
1.- Flower reaction events: Randomly in #announcements —every 1 or 2 days— there are events where you add a :cherry_blossom: reaction and get flowers.

2.- Picking in #chat-safe channels: Each message sent on this server's #chat-safe channels has a 2% chance of spawning 5 flowers which you pick with .pick

3.- Donating to Nadeko's Patreon: Donations award a ratio of 100 flowers per dollar.

Flower reaction events and spawns is on the [support server](https://discordapp.com/invite/nadekobot)
if you still have questions related to Nadeko, feel free to ask in the support channel
