### ISSUE TITLE
stacking multiple .acr for the same trigger no longer possible.

### ISSUE THREAD

**Issue by sumplkrum** [Kwoth/NadekoBot#1886]
Windows 2.5.2 version

You used to be able to do multiple custom reactions for the same trigger and the bot would give a random response when the trigger was hit.

It still works, but you can't add more than one .acr for a trigger because the trigger activates instead of recognizing the .acr command.

For example:
```
.acr "@Saya" Leave me alone.

Response: 
  New Custom Reaction
  #294
  Trigger
  @Saya
  Response
  Leave me alone.

.acr "@Saya" go away.

Response:
Leave me alone.
```

The bot no longer recognizes the second .acr, but instead activates the trigger

**Comment by coconut24** [comment]
you must have .crca enabled on the first acr, disable it, add the new one and then re-enable it again

**Comment by coconut24** [comment]
you problably has .crca enabled on the first acr, disable it, add the new one and then re-enable it again

**Comment by coconut24** [comment]
you problably have .crca enabled on the first acr, disable it, add the new one and then re-enable it again

**Comment by sumplkrum** [comment]
I do. But why would that cause a problem? It didn't do that in the last version.

**Comment by sumplkrum** [comment]
Can confirm that that works. Disabling .crca on other reaction allows you to add a new reaction.

**Comment by coconut24** [comment]
because acr will try to trigger first and crca now ignores special characters. wouldnt be a bad thing if nadeko were to check the prefix before triggering acr :smiley:

**Comment by sumplkrum** [comment]
cool thanks.

**Comment by Kwoth** [comment]
Working as intended
