### ISSUE TITLE
using .rc with ..

### ISSUE THREAD

**Issue by SillyBirds** [Kwoth/NadekoBot#1889]
While trying to disable for a role to add quotes, I noticed it disabled `.`, used `.rc ".." disable role` with v2.6.0.

![image](https://user-images.githubusercontent.com/22528910/33457632-5e8336aa-d623-11e7-86d9-a0dcf7ade810.png)

![image](https://user-images.githubusercontent.com/22528910/33457619-5371e32e-d623-11e7-84dd-9b1c5afd9ef0.png)

**Comment by Macley-Kun** [comment]
What happens when you use three dots? (Just curious)

**Comment by SillyBirds** [comment]
You disable `..`, but it shows `...` in the perm page,
![image](https://user-images.githubusercontent.com/22528910/33457888-4f597e54-d624-11e7-8ace-2033935a75b8.png)

**Comment by Kwoth** [comment]
Yup. Works fine. Command name is actually `.`, if you add it the `.` prefix, it becomes `..`.
