### ISSUE TITLE
Queuing certain YouTube videos throws exception.

### ISSUE THREAD

**Issue by Rivalo** [Kwoth/NadekoBot#189]
For instance: 
`!m q https://www.youtube.com/watch?v=CxnaPa8ohmM`
Will throw an exception: 
`Failed resolving the link.Exception of type 'VideoLibrary.Exceptions.BadQueryException' was thrown.`

I've tested this on my own instance and on the official Nadeko server. I can't be for certain that it throws the same exception on your server but the video won't queue either.

**Comment by Rivalo** [comment]
I've did a little more research and I think that the problem is the fact that VEVO, and probably other companies block embedded videos. 

For instance: 

`https://www.youtube.com/embed/q604eed4ad0` (Sorry for Copy/Paste, but for some reason being referred it does work)

won't work, while `https://www.youtube.com/embed/bCodVbucTbo` does.

This is quite a limitation, probably since the usage of embedded video's in the way Nadeko does block advertisements. It's not a complete limitation of YouTube, since Discord has the possibility to embed them in chat. Do you know if it is possible to play the videos in a different, probably with advertisements, way using the library you're currently using?

**Comment by Kwoth** [comment]
There is nothing i can do about this. It was much worse with old library (YoutubeExtractor), this lib is a fork of that one, and proved to be much better, but since yesterday people started having a lot of issues again. I do not think it has anything to do with embeds.

**Comment by gwigz** [comment]
https://github.com/jamesqo/libvideo/issues/33

**Comment by Rivalo** [comment]
Hmm, I don't get the problem anymore. Still using the same nadeko version as when this issue was created. Did something changed at Youtube?

**Comment by Kwoth** [comment]
Most likely, ill try to confirm with other guys.

**Comment by Kwoth** [comment]
@Rivalo did this stop happening?

**Comment by sethdm02** [comment]
Yeah
