### ISSUE TITLE
Broken links in docs.

### ISSUE THREAD

**Issue by tukimoop** [Kwoth/NadekoBot#1890]
[The Windows Guide](http://nadekobot.readthedocs.io/en/latest/guides/Windows%20Guide/) references a url at http://nadekobot.readthedocs.io/en/latest/guides/Upgrading%20Guide/, which was deleted from [this commit.](https://github.com/Kwoth/NadekoBot/commit/696a0eb2a7c0b7b7b4ad63b3fb52530e7da3df00) Probably either remove the note or reinstate the page (some people though still have old versions of nadeko laying around.)

The [invite guide link in this section](http://nadekobot.readthedocs.io/en/latest/JSON%20Explanations/#inviting-your-bot-to-your-server) is dead, since Kong had taken the website down. Delete or maybe re-host it on someone elses website? It's a handy page though.

(i'm not doing any pull requests since kwoth may have other ideas on what to do with these sections.)

**Comment by Macley-Kun** [comment]
@Kwoth can confirm that the above is true. What you wanna do with this?

**Comment by Kwoth** [comment]
Migrating up from <1.4 or 1.3 is no longer supported, removed the link. Thanks
