### ISSUE TITLE
Warn command not working in my  server. 

### ISSUE THREAD

**Issue by FrostedWolf** [Kwoth/NadekoBot#1891]
.warn, .warnclear & .warnlog don't work on my server anymore. The only warn command that works is .warnpunish. 

I tried it on another server I was admin on and the warn command still workers there but not on my server.

**Comment by Macley-Kun** [comment]
Your using the public NadekoBot? Also, you might wanna check your permissions. Maybe it's not configured right. Perhapes the guys @ Help in the server could help you out future if the above didn't worked out for you.

**Comment by FrostedWolf** [comment]
I'm using public NadekoBot and I have the Nadeko role+ I'm admin. The bot also has admin and I've reset all the perms for the bot 3 times...

**Comment by Macley-Kun** [comment]
Mhm strange.. Could you try to kick and re-add it?

**Comment by FrostedWolf** [comment]
Did that about 4 times. :/

**Comment by MaybeGoogle** [comment]
@FrostedWolf DM me server invite. Google#1696

**Comment by FrostedWolf** [comment]
@MaybeGoogle https://gyazo.com/cb79528fb141cd727186a074eb7c4ea7

**Comment by MaybeGoogle** [comment]
Just join nadekolog and shoot me a dm.
discord.gg/nadekolog

**Comment by MaybeGoogle** [comment]
another #1535 problem. tell them to hurry up and fix it 😈

**Comment by Kwoth** [comment]
We'll track it over there.
