### ISSUE TITLE
[BUG] After adding feeds on my server bot is shutting down automatically!

### ISSUE THREAD

**Issue by AmitGamingKing** [Kwoth/NadekoBot#1892]
Hello,

After adding 10 feeds on my server my bot is going down after every 30-45 minutes! (Need to restart every time with puTTY!) Did everything such as rebooting my instance, created a new instance with a fresh installation but nothing works... Then I remembered that this problem occurring after adding feeds then after removing all feeds my bot is running fine for 24 hours without any interruptions! So I think this maybe a bug of feeds feature... Hope you will fix it in the next update!

Thank you in advance...

**Comment by Macley-Kun** [comment]
You can't add any atom feeds as far as i know. #1628 
For now it's better to leave those atom feeds out and wait until someone can pick that issue up.

**Comment by AmitGamingKing** [comment]
I'm not adding any atom feed to my server... Just added simple rss feeds and those are accepted by bot but after adding those feeds the problem is my bot is shutting down automatically after sometime!

**Comment by Macley-Kun** [comment]
Mhm strange, though it could be something with those types of feeds... Can you try to add just one feed and see how it goes?

**Comment by AmitGamingKing** [comment]
Ummm... Not want to take risk because once it crashed my whole instance and then I needed to create one again with all stuffs.... But I'll try it! Let's see what happens :D

**Comment by AmitGamingKing** [comment]
Okay.. So after adding only 1 RSS feed to my server the same problem is happening (Bot going down after sometime read first post for more details!) So what problem it should be? I'm just requesting you to please try to add feeds on your own server and check it out if it is running or not...

**Comment by Macley-Kun** [comment]
For me it works. Bin trying it out for a long time with different stuffs that works. I think your vps might not be powerful enough. I don't have any logs of your issues so i assume it's just something you experience with your setup.

**Comment by AmitGamingKing** [comment]
Ok it's alright if you tried and if it successfully worked for you then I'm assuming that this issue is only happening with me... Closing this issue as there is no further topic remaining... Thanks for your assistance!
