### ISSUE TITLE
Mute is avoidable

### ISSUE THREAD

**Issue by invalidgamer** [Kwoth/NadekoBot#1893]
Muted members can easily leave and join the server when a mod uses the .mute command. Role should persist even if the member leave and joins the server to prevent mute avoids.

**Comment by tukimoop** [comment]
What version of nadeko are you on? My nadeko successfully reapplies the mute role to someone who's been muted before who leaves and rejoins. I'm pretty sure this was an old issue which was fixed already.

**Comment by invalidgamer** [comment]
Yes I didn't try locally hosting and seeing if the issue would be resolved with hosting on my own end. It was the public Nadeko bot that was having that issue.
