### ISSUE TITLE
Hosting mutibot

### ISSUE THREAD

**Issue by kaiserdj** [Kwoth/NadekoBot#1895]
hello,
I would like to know if there is any way to host, several times the same bot ?. Since the windows launcher only allows one bot.

I have enough resources to run several bot, I have a windows server 2012

**Comment by samdivaio** [comment]
You can try copying your actual Nadeko folder multiple times to different folders and replacing credentials and data.
Or you can try the batch file way that has download, run and update feature, you can get that batch script from [here](https://github.com/samdivaio/NadekoBotInstallerWin/raw/1.9/NadekoInstaller.bat) by simply right clicking and saving the link file. Just place them in folder you want to install Nadeko. Also note you do need the latest .NET Core SDK along with prerequisites from Nadeko updater to make it work.

Good Luck!
