### ISSUE TITLE
Automatic Shard Restarts are messing with repeat

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#1899]
Timer resets when bot restarts, so repeats with long intervals never get sent.

Idk how to fix, maybe use the real time or smth.
Or fix those memory problems :^)

**Comment by Macley-Kun** [comment]
Double issue, suggest we refer to the first issue pointing at this. #1894

**Comment by MaybeGoogle** [comment]
thanks @Macley-Kun
