### ISSUE TITLE
Minimizing NadekoBot to system tray

### ISSUE THREAD

**Issue by Bergster** [Kwoth/NadekoBot#1902]
Is it currently possible to minimize the command prompt window to the system tray? I'm hosting my own NadekoBot and it's kinda annoying having the program in my taskbar all day. If there isn't a way, can this be implemented somehow?

**Comment by Macley-Kun** [comment]
Windows or linux?

**Comment by Bergster** [comment]
I'm using Windows 10 atm

**Comment by Jonz00r** [comment]
I'm guessing Windows. You could probably get nadeko to run as a daemon
somehow.

**Comment by Macley-Kun** [comment]
Sorry but then i have no real clue how to minimize that...

https://feathub.com/Kwoth/NadekoBot/+172
^not that you have much with this link but, it shows 2 ways to 'minimize' it. Sadly it's only for linux...

**Comment by Kwoth** [comment]
Yea just continue the convo on the feathub.
