### ISSUE TITLE
Can't install NadekoUpdater

### ISSUE THREAD

**Issue by vandolph09** [Kwoth/NadekoBot#1909]
sorry if this is the wrong place to put it  but i'm trying to install it for my server but it can't seem to install. What seems to be the problem?

Here is my log.

The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 6.3.0 {version}
Running checks for package 'Microsoft .NET Framework 4.5.2 (x86 and x64)', phase BuildList
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read integer value 461310
Setting value '461310 {int}' for property 'DotNet45Full_Release'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNet45Full_OSIntegrated'
The following properties have been set for package 'Microsoft .NET Framework 4.5.2 (x86 and x64)':
Property: [DotNet45Full_OSIntegrated] = 1 {int}
Property: [DotNet45Full_Release] = 461310 {int}
Running checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet45Full_Release' and value '379893': true
Result of checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe' is 'Bypass'
Running checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet45Full_Release' and value '379893': true
Result of checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe' is 'Bypass'
'Microsoft .NET Framework 4.5.2 (x86 and x64)' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697208'
Error: An error occurred trying to download 'https://dl.nadekobot.me/NadekoUpdater.application'.

**Comment by Macley-Kun** [comment]
Jou use windows 8.1 or higher? You tried running with admin? Disabled the anti-virus?

**Comment by coconut24** [comment]
can you try again with an internet connection?
assuming dl url is down at that time :P

**Comment by vandolph09** [comment]
Tried all of them, still didn't work

**Comment by Macley-Kun** [comment]
Checked all of your keys and stuff in the credentials.json?

**Comment by vandolph09** [comment]
I don't have the credentials.json file since I'm installing Nadeko bot files for the first time.

**Comment by Macley-Kun** [comment]
Idk the only option I can think off now is trying to re-install windows... but that might be overkill to just install nadeko.

Idk if this issue also occurs if you use a different internet connection..?

Verstuurd vanaf mijn iPhone

**Comment by vandolph09** [comment]
thanks. i used a vpn to install nadekobot and now i have setup credentials.json and a bot account. only problem is that i cant run the bot because it says 'Token is missing from credentials.json or Environment Variables. Add it and restart the programs' i know what environment variables are but what exactly do i need to add to make it work?

**Comment by Macley-Kun** [comment]
Good to hear! Have fun with Nadeko :-)

Verstuurd vanaf mijn iPad
