### ISSUE TITLE
"following streams" can't reset after deleting the original channel

### ISSUE THREAD

**Issue by DrRandom7** [Kwoth/NadekoBot#191]
I've got a problem.. If you set up nadekoBot in the first channel and enable it to let nadekobot follow some streamers and notify you about them, it all works fine.
But it can't be changed, if u accidently delete the channel where u set everything up and u can't just create a second channel and change it. i even tried it with kicking the bot out and inviting it back again. it didn't worked. 
In my situation right now I can't even get a list by using the ~ls command, but i guess it means, that there are to many symbols already in the ~ls command to show.
Is there a possibility to program a reset command for the nadekobot in a certain server to avoid that kind of problem?

**Comment by Kwoth** [comment]
Tell me what server you're on and ill reset it manualy. Interesting.

**Comment by DrRandom7** [comment]
i'm on the server "4 R4ND0M C0RN3R"
here an invite aswell, if needed: https://discord.gg/0WgRVJW5B04wDpIu
ty for helping me with my problem :D

**Comment by Kwoth** [comment]
Solved in discord
