### ISSUE TITLE
.rategirl broke

### ISSUE THREAD

**Issue by Jengas** [Kwoth/NadekoBot#1910]
![image](https://user-images.githubusercontent.com/14033756/33779433-304f960e-dc4d-11e7-8317-818b35eb937b.png)

**Comment by Kuromaru420** [comment]
Getting the same minus the  `.delmsgoncmd` error

**Comment by shikhir-arora** [comment]
Restarted and it works fine. [Judging from here](https://github.com/dutchcoders/transfer.sh/issues/108) the site could have/had issues causing this error. Let me know if it works for you guys.

**Comment by Kuromaru420** [comment]
Works fine on my end, looks like that was the problem.
