### ISSUE TITLE
.feed isn't working (TwitRSS.me)

### ISSUE THREAD

**Issue by Wickedddd** [Kwoth/NadekoBot#1916]
Hello,
.feed function doesn't work with twitter
There is also that in the console :
`=NadekoStrings | searches_feed_added key is missing from fr-FR response strings. PLEASE REPORT THIS.`

**Comment by Macley-Kun** [comment]
@Kwoth you think it's an issue on our side?
@Wickedddd what feed did you tried to add?

**Comment by Wickedddd** [comment]
> https://twitrss.me/twitter_user_to_rss/?user=Gameforge

There is also that : 
`NadekoStrings | searches_feed_removed key is missing from us-US response strings. PLEASE REPORT THIS.
NadekoStrings | searches_feed_out_of_range key is missing from us-US response strings. PLEASE REPORT THIS.
NadekoStrings | searches_feed_no_feed key is missing from us-US response strings. PLEASE REPORT THIS.`

**Comment by Macley-Kun** [comment]
@Wickedddd so i kinda looked trough that feed of yours and notice this line:
rss xmlns:atom="http://www.w3.org/2005/Atom"

Sadly enough atom feeds (the on you wanted to use) isn't supported sadly. But an issue is already made for it! #1628 

@Kwoth if you don't see any issue's with his log feel free to close this one :-)

**Comment by Kwoth** [comment]
us-Us doesn't exist. It's en-US, change your language, and yeah, move to #1628

**Comment by Kwoth** [comment]
French will get updated someday btw.
