### ISSUE TITLE
Fresh installed bot 2.8.2 opens console but always runs into error, likely related to certificates

### ISSUE THREAD

**Issue by Zihuadie** [Kwoth/NadekoBot#1919]
![image](https://user-images.githubusercontent.com/34451335/33838400-0f07af18-de55-11e7-8124-37d3d826b71e.png)

Those are the first few lines and everything past that is pretty much a repeat of the last few lines but with different numbers

After it fails it still tries to restart over and over again
![image](https://user-images.githubusercontent.com/34451335/33838521-61962d86-de55-11e7-9491-7a5c013bfe0d.png)

Will update on situation once I test again and go through all firewalls

**Comment by shikhir-arora** [comment]
With regards to your second picture (ShardsCoordinator), update to 2.8.3...does that fix that issue? 
https://github.com/Kwoth/NadekoBot/commit/b9611aa57e12a823edc18abbe4add21ac458d55f

**Comment by Zihuadie** [comment]
According to Nadeko Installer 2.8.2 is the latest version
I moved from school wifi to home wifi (yes I do know I'm an idiot I figured vpn would resolve that tho) and that original problem is now gone, the current problem is this now
![image](https://user-images.githubusercontent.com/34451335/33864682-8ce1d04a-deb3-11e7-85e7-ed94ba4f0f82.png)

**Comment by Zihuadie** [comment]
Turns out restarting the bot 5 times magically resolves the issues

**Comment by coconut24** [comment]
first problem was problably caused by your internet connection
as for the second, it might have been windows firewall's doing
