### ISSUE TITLE
Pokemon attacks not going through 

### ISSUE THREAD

**Issue by Zaikurron** [Kwoth/NadekoBot#192]
every time i try to attack its says there no such person

**Comment by MCTheMiz59** [comment]
Does it happens with a 2-words attack ? (like dragon rage) 
If yes try putting the name of the attack in quotation mark like this :
`>attack "dragon rage" @Target `

**Comment by Kwoth** [comment]
Yep, pokemon attacks work. MCTheMiz is probably right
