### ISSUE TITLE
.slowmode doesn't stay on

### ISSUE THREAD

**Issue by limerencee** [Kwoth/NadekoBot#1921]
.slowmode doesn't stay on, it switches off (100% replication success) but i am not sure how long it stays on.

**Comment by shivaco** [comment]
Public Nadeko or self-hosted? :thinking:

**Comment by limerencee** [comment]
public one

**Comment by shikhir-arora** [comment]
Could be that the bot went offline and that reset `.slowmode` -- are you still having this issue consistently?

**Comment by Kwoth** [comment]
Yeah, slowmode doesn't persist restart, and as we restart each shard every couple of hours, it can't really stay up. It will get fixed at one point.
