### ISSUE TITLE
How to stop Nadeko from echoing in hidden/admin-only channels?

### ISSUE THREAD

**Issue by Paril** [Kwoth/NadekoBot#1923]
We have a channel that we use to mess with bots, and Nadeko will echo out music commands and the like to it. We'd like it to not do that and redirect them somewhere else. How do we accomplish this?

**Comment by Macley-Kun** [comment]
If i'm not mistaken. It's possible to disable certain modules (aka music) on specific channels.

.chnlmdl .cm | Sets a module's permission at the channel level. | .cm ModuleName enable SomeChannel

Hope this answers your question :-)

Also we got a help channel were you can ask questions about using/hosting Nadeko 👍

**Comment by Kwoth** [comment]
Not sure what you mean. `.logserver disable` ?

**Comment by Kwoth** [comment]
Or maybe `.usmch`
