### ISSUE TITLE
Music commands to slow

### ISSUE THREAD

**Issue by lucasnotad** [Kwoth/NadekoBot#1925]
When I put the code to play the music it takes 15 seconds to search the music to queue and play it, how to improve it?

**Comment by shikhir-arora** [comment]
Post a screenshot of your console when you do these commands if you can. But likely not much, if your internet connection and/or computer is slow.. but 15 seconds does seem a little excessive so post that picture if you can.

**Comment by Kwoth** [comment]
Yea, your pc/vps is too slow, or your internet connection.
