### ISSUE TITLE
Nadekobot keeps sending me dms

### ISSUE THREAD

**Issue by Sonic338** [Kwoth/NadekoBot#1926]
<img width="912" alt="sketch 16" src="https://user-images.githubusercontent.com/34505208/33930280-4706fa98-e03c-11e7-8b06-12ee00d19f50.png">

I've been getting this for a while. My account keeps automatically sending invites every second while the bot keeps telling me to "Type '.h' for help" and it's getting so annoying! Someone help please

**Comment by tukimoop** [comment]
Known discord bug, they're fixing it. 
https://trello.com/c/raJ1WFqF/1409-invite-message-spam-in-dms-after-turning-off-msgs-from-players-in-server-and-inviting-them-to-a-server-you-created-part-of-exper
