### ISSUE TITLE
Please add admin .waifureset command

### ISSUE THREAD

**Issue by Dyonivan** [Kwoth/NadekoBot#1927]
Please add the ability for an admin to manually reset the waifuinfo of an individual.  The only commands I can find right now is to either purge all data, or have the person reset it themselves.  

Story goes that my clanmates were talking about how no one would ever be able to afford a spaceship.  I bragged that I could, and bought a spaceship (by giving myself currency) for our old clan leader who has and will be gone for the military for some time.  Didn't even think at the time that it would mess with the leaderboards, and now my clanmates are pissed at me ><

**Comment by shivaco** [comment]
http://feathub.com/Kwoth/NadekoBot :thinking:

**Comment by Dyonivan** [comment]
I'll make a post on there.  Thanks, shivaco.

**Comment by Macley-Kun** [comment]
You can close the issue fam :P
