### ISSUE TITLE
.waifureset doesn't work

### ISSUE THREAD

**Issue by Dyonivan** [Kwoth/NadekoBot#1928]
Typing .waifureset doesn't work.  The bot doesn't even acknowledge it as a request.
![image](https://user-images.githubusercontent.com/34512852/33947081-1bf90b0a-dfe9-11e7-8e45-6c538445ef02.png)

*Update: Nevermind.  It was broken in version 2.6 of Nadeko.  I updated it to 2.8.2 after posting this and it's now working.  Sorry.

**Comment by Kwoth** [comment]
Update

**Comment by Kwoth** [comment]
It wasn't broken, It didn't exist in 2.6
