### ISSUE TITLE
.img not using the Google search

### ISSUE THREAD

**Issue by Alex-Cas** [Kwoth/NadekoBot#1930]
When using the .img command, the bot seems to be only using the imgur search. When the imgur search has 0 results (which is quite frequent), the command returns nothing (like an error or something). Is it intended ?

**Comment by shikhir-arora** [comment]
Are you self-hosting the bot? If so, in your console, do you see `"Falling back to Imgur search."`?
If there are no results it should return nothing.

**Comment by Alex-Cas** [comment]
I am not self-hosting it. Could it solve the issue ?

**Comment by shikhir-arora** [comment]
Google search API is limited to 100 searches per day normally, so this makes sense that it does not use Google on the public bot.

**Comment by Alex-Cas** [comment]
Oh ok, thanks !
