### ISSUE TITLE
How to create custom reactions with image AND text?

### ISSUE THREAD

**Issue by TheTermnL** [Kwoth/NadekoBot#1932]
I want to create custom reactions that has Nadeko respond with an image AND a text as well. I know how to make Nadeko respond with image alone via embed builder, but I can't figure out how to add text as well, as Nadeko will not detect it. Can anyone help?

**Comment by shikhir-arora** [comment]
Someone can correct me if I’m wrong, but I don’t think this is possible at this moment with the current design. If you use the embed layout it’ll parse it as an embed without an option for external text. The only thing I can think of right now is to take a photo and include the link with the text in the custom reaction, or if you want you can use markdown in the embed to emulate a text block.

**Comment by Kwoth** [comment]
?!

Add text to plain text or description fields?
I don't get it.

**Comment by shikhir-arora** [comment]
I think he means text that is not part of the embed fields at all. but again that isn't possible with the design.

![screen shot 2017-12-16 at 11 23 15 pm](https://user-images.githubusercontent.com/8797918/34076523-286cf8de-e2b8-11e7-99d1-e3a81787c213.png)

**Comment by TheTermnL** [comment]
Thanks, you guys helped a lot.
![arigatogozaimasu](https://user-images.githubusercontent.com/34614630/34085337-aa2f19fa-e354-11e7-9612-96786d650da2.PNG)

**Comment by Tubolar** [comment]
I still can not make the bot response seem like embeded messages.
Who can help me and explain?

**Comment by Macley-Kun** [comment]
Ask in #help in the Nadekolog server, this github is meant to post about issues and bugs.
Questions go to the #help in the server.
Suggestions go to Feathub.
