### ISSUE TITLE
.asar not working

### ISSUE THREAD

**Issue by xukrilos** [Kwoth/NadekoBot#1938]
Hello all. I gave up in frustration. I've googled up about it and found nothing. 
I've tried creating a self assignable role with the .asar command but the bot didn't replied then I've tried the .lsar to see if the is a role and the bot replied "0 self assignable roles"
![screenshot_55](https://user-images.githubusercontent.com/34638955/34089845-2fb9024e-e39a-11e7-9bc4-533b996e2fe9.png)

**Comment by Kwoth** [comment]
The role needs to exist in the first place. Either do .cr Gamer or create the role manually in discord.

**Comment by xukrilos** [comment]
Thank you!
