### ISSUE TITLE
Build failed - no other info given

### ISSUE THREAD

**Issue by TETYYS** [Kwoth/NadekoBot#1940]
nadeko_run.sh fails (run through second option of installer) with latest git code (since 2017-12-18) with message "The build failed. Please fix the build errors and run again.". I tried to invoke `dotnet run` directly with maximum verbosity, but that didn't do anything. `dotnet build` with maximum verbosity just spits out garbage and doesn't actually do anything.

How do I know which errors need to be fixed? Debian 9.3

**Comment by tukimoop** [comment]
a screenshot of the specific errors would be nice.

**Comment by TETYYS** [comment]
That's the problem - there are no specific errors

![25510919_670917319963063_458815698_o 1](https://user-images.githubusercontent.com/3091645/34184112-b801ae48-e526-11e7-989b-c564afdba062.png)

**Comment by shikhir-arora** [comment]
Install `youtube-dl` and try again:

```bash

sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```

**Comment by TETYYS** [comment]
The line relating to `youtube-dl` is just replaced by `youtube-dl is up-to-date (2017.12.14)` as a result.

It's worth mentioning that first installer option (it was done before second option, when trying to set up the bot) with is "Download NadekoBot" downloads it, but tries to build it too, despite only being told to download the bot. Build is done 'successfully', however binary files are nowhere to be seen.

![2017-12-20_01-46-02](https://user-images.githubusercontent.com/3091645/34184390-1d6e45ce-e528-11e7-8ea5-8762d50acafc.png)

**Comment by shikhir-arora** [comment]
Make sure you are in your root directory (`cd ~`) and try installling the prerequisites by hand.

```bash

                apt-get update
		apt-get upgrade -y
		apt-get install sudo -y
		sudo apt-get install software-properties-common apt-transport-https -y
		sudo apt-get install curl libunwind8 gettext -y
		curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
		sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
		sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/dotnetdev.list'
		sudo apt-get update
		sudo apt-get install dotnet-sdk-2.0.0 -y
		echo "Installing prerequisites..."
		echo "deb http://ftp.debian.org/debian jessie-backports main" | tee /etc/apt/sources.list.d/debian-backports.list
		sudo apt-get update && sudo apt install ffmpeg -y
		sudo apt-get install libopus0 opus-tools libopus-dev libsodium-dev redis-server -y
		sudo apt-get install git -y
		sudo apt-get install tmux python python3.5 -y
		sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
		sudo chmod a+rx /usr/local/bin/youtube-dl
```


Then -

`sudo wget -N https://raw.githubusercontent.com/Kwoth/NadekoBot-BashScript/1.9/nadeko_run.sh` and 

`sudo bash nadeko_run.sh` 

Also, if that doesn't work, let me know what happens when you run 

`sudo -H bash nadeko_run.sh` after downloading that.

**Comment by TETYYS** [comment]
Why would i dump all generated files into my home directory? That doesn't make sense.

I already installed prerequisites and verified that they exist. Even `redis-server`, which shouldn't be a library dependency, because it's not a library.

Can we get to the original problem please, how can I display the compilation errors?

**Comment by shikhir-arora** [comment]
What happens when you do `sudo -H nadeko_run.sh`?

**Comment by TETYYS** [comment]
I don't run the bot with superuser rights

**Comment by shikhir-arora** [comment]
Then you need to check your permissions.  If anything is owned by root and you aren't running with sudo, then it won't work properly. Run `ls -la` on the folder your Nadeko is in, see if it's owned by your user, and that the chmod is 0755 (`-rwxr-xr-x`) or (`drwxr-xr-x`). 

Can manually try running. First type `pwd` and input that where I write `pwd` below. So if `pwd` outputs `/home/something` put that in.


```bash

cd pwd/NadekoBot
dotnet restore
dotnet build --configuration Release
cd pwd/NadekoBot/src/NadekoBot
dotnet run --configuration Release
```

**Comment by TETYYS** [comment]
`dotnet build` doesn't output anything, `dotnet run` fails with same "The build failed. Please fix the build errors and run again." message, nothing else.

**Comment by MaybeGoogle** [comment]
Probably won't help, but maybe worth a shot?
Reinstall dotnet using https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x

**Comment by shikhir-arora** [comment]
If that doesn't work still, your best bet is to:

- Back up the `NadekoBot.db` database
- Back up `credentials.json`

Delete the NadekoBot folder completely, reinstall dotnet (optional), download NadekoBot again using the fresh script again, and then replacing the `NadekoBot.db` and `credentials.json` **before** starting the bot again.

Then start it up and see if it builds. That's what I would do / what the advice you'd get as a 'last resort.'

**Comment by Macley-Kun** [comment]
@TETYYS did the solutions help'd you out?

**Comment by Macley-Kun** [comment]
@TETYYS Can you close the ticket if the issue is solved? Any update on this maybe?

**Comment by TETYYS** [comment]
I previously had `dotnet` installed and uninstalled it again. Tried to install it with AIO script, but only told me that my machine can _probably_ run dotnet (there's a debian check missing at the start) - installed it by executing from line from nadekoautoinstaller.sh.

Installation seems to fail when something segfaults upon running `dotnet restore` in `NadekoInstall_Temp/NadekoBot` on `X509_verify_cert`, but then some process detached from my terminal prints that restore is completed. `dotnet build --configuration Release` segfaults on `X509_verify_cert` too.

**Comment by TETYYS** [comment]
I previously had `dotnet` installed and uninstalled it again. Tried to install it with AIO script, but only told me that my machine can _probably_ run dotnet (there's a debian check missing at the start of `nadekoautoinstaller.sh`) - installed it by executing from line 224 from `nadekoautoinstaller.sh`.

`dotnet` installation fails when something segfaults - `/var/lib/dpkg/info/dotnet-sdk-2.0.0.postinst: line 22: 10235 Segmentation fault`. It's combined with `|| true` in `/var/lib/dpkg/info/dotnet-sdk-2.0.0.postinst` script, quality microsoft programming. It segfaults in `X509_verify_cert () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0`.

**Comment by Macley-Kun** [comment]
Your not doing this on a 32-bit linux right?
Also have you tried using an older distro maybe? Debian 8 (jessie) worked for me perfect 🤔
