### ISSUE TITLE
.owerwatch command broken

### ISSUE THREAD

**Issue by Wickedddd** [Kwoth/NadekoBot#1943]
Hi,
some values remain at zero
![image](https://user-images.githubusercontent.com/34405097/34251424-55e302a0-e640-11e7-96c1-7f68ee856684.png)
![image](https://user-images.githubusercontent.com/34405097/34251601-f7bb3b42-e640-11e7-94b1-21a31db3bfd9.png)

**Comment by Kwoth** [comment]
Should be fixed now.
