### ISSUE TITLE
Updating from 1.3b

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#1945]
I saw [this](https://github.com/Kwoth/NadekoBot/issues/1890#issuecomment-349282432) thanks to @shikhir-arora .

Does that mean it is no longer possible to upgrade, even if you remove all of the files and do a new reinstall with the updater? It doesn't work even if the database is taken out.

`Token is missing from credentials.json or Environment varibles. Add it and restart the program.`
Windows updater. Windows 10 x64. Upgrading from 1.3b. Copied over `credentials.json` and `nadekobot.db` after installing redis and downloading the bot. Reformatted credentials to match the format on the json explanations.

`credentials.json` is located in `C:\Program Files\NadekoBot`

**Comment by Kwoth** [comment]
No, you just did something wrong. credentials.json needs to be in the system folder in NadekoBot on windows.

By migrate i meant the .migrate command, which merges your old database to the new one.
