### ISSUE TITLE
Hanging on build - Windows Server 10

### ISSUE THREAD

**Issue by zdgoodnews** [Kwoth/NadekoBot#1947]
Running Nadeko from source and hanging infinitely at the ShardsCoordinator. Windows server 10, 64-bit.

![shards](https://user-images.githubusercontent.com/34757559/34281385-353f0dc2-e673-11e7-9cdb-98b85dede5ee.JPG)

**Comment by coconut24** [comment]
follow the [guide](https://nadekobot.readthedocs.io/en/latest/guides/From%20Source/) 🙋

**Comment by coconut24** [comment]
follow the [From Source](https://nadekobot.readthedocs.io/en/latest/guides/From%20Source/) guide
