### ISSUE TITLE
Strange display of commands

### ISSUE THREAD

**Issue by Andrej68689** [Kwoth/NadekoBot#1948]
[Admin](https://imgur.com/a/4R5cr)
[Not admin, user](https://imgur.com/a/bZMqh)
I dont know, how to fix that, can smb help me?

**Comment by shivaco** [comment]
Enable Link Preview in Settings, as shown [here](https://i.imgur.com/uqUn0cV.gif)

**Comment by Andrej68689** [comment]
Thnx

**Comment by Macley-Kun** [comment]
@Andrej68689 psst you can hit close ;3
Happy holidays 0/
