### ISSUE TITLE
Ability to have several commands run on startup of the bot.

### ISSUE THREAD

**Issue by ChrisLeOtaku** [Kwoth/NadekoBot#195]
Something like a script that runs at the starting of the bot. 

Example:

".setgame (name)"
"!m q (100 different items)"
"!m sh"

**Comment by Kwoth** [comment]
Ok ill close #69  and keep this one since this one is much more articulated :D

**Comment by xnaas** [comment]
To add onto this, would be nice to have `.logserver` run in a specific channel. I hate having to run it again every time. :D

**Comment by Kwoth** [comment]
this is not possible before 1.0, so not coming soon. For logserver persisting restarts, we have an issue for that #104

**Comment by Kwoth** [comment]
Ok I have an idea of how to do this, I'll attempt to do it within a few days at most. Need to do some other priority stuff right now.
