### ISSUE TITLE
.starevent reaction 

### ISSUE THREAD

**Issue by Jengas** [Kwoth/NadekoBot#1952]
When i start .starevent reaction. It starts and it deletes on Windows Server 2016
![image](https://user-images.githubusercontent.com/14033756/34328271-995bfe36-e8db-11e7-9274-fbfe4e688b2e.png)
![image](https://user-images.githubusercontent.com/14033756/34328272-9b0981a4-e8db-11e7-95b8-7cd64275acf3.png)
I tested with Google and its not server permission problem. Something with bot. On Linux and Mac works fine, but on windows - no

**Comment by Kwoth** [comment]
Bot doesn't have your currency emoji, or can't add that emoji for some other reason.

**Comment by Jengas** [comment]
Oh yes. Problem was due to Animoji
