### ISSUE TITLE
.startevent reaction does not work

### ISSUE THREAD

**Issue by BStorm888** [Kwoth/NadekoBot#1953]
.startevent reaction does not work if the currency sign is animated. However, it should work because bots have access to animated emojis.

**Comment by Macley-Kun** [comment]
Little update on this. Can you have a look at #nadeko-beta-testing in the server?
You can search on ".startevent reaction 500"

Seems like kwoth is going to fix this soon :-)

**Comment by BStorm888** [comment]
Yeah, I see it. Thank you :)

**Comment by Kwoth** [comment]
It will work now in 2.11 (if you're on linux)
