### ISSUE TITLE
How to change the Experience in NadekoBot.db？

### ISSUE THREAD

**Issue by hank0531** [Kwoth/NadekoBot#1954]
I want to change my **Experience** from **NadekoBot.db**, but I do not know where to change it, I can not find it.

**Comment by Gremagol** [comment]
Get your User ID and change it there:
![xpdb](https://user-images.githubusercontent.com/24619854/34355727-f2ddc46e-ea37-11e7-9207-4e6dfc289be4.PNG)

**Comment by Macley-Kun** [comment]
@hank0531 saw you online. Is the issue solved for you on this one?
