### ISSUE TITLE
langset error when trying to set an existing language

### ISSUE THREAD

**Issue by s890081tonyhsu** [Kwoth/NadekoBot#1955]
[Public nadeko server]
I've invite tester to check my commands.

It doesn't error when executing commands except for ``.langset`` with only one parameter (only one space in front of parameter and no space behind parameter).

But these works when tester tries on his server, my another server also works.

I leave this image below to show my error messages, if I have to check another settings please tag me to do so.

![image](https://user-images.githubusercontent.com/3825000/34371117-51a48fe6-eb05-11e7-947c-c702c4629cc0.png)

**Comment by Macley-Kun** [comment]
So summarizing your issue. `.langset ja` doesn't work on the public but `.langset ja-JP` works?

**Comment by Kwoth** [comment]
?! `.langset ja-JP`

**Comment by s890081tonyhsu** [comment]
Sorry for late reply.

Here's another language set test for that day.

![2017-12-29 01 32 29](https://user-images.githubusercontent.com/3825000/34418317-64dc03bc-ec38-11e7-99b5-ca38881228e2.png)
