### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by hank0531** [Kwoth/NadekoBot#1957]
Some instructions entered, there will be an error, the command will not play a role.
![image](https://user-images.githubusercontent.com/24751265/34382397-80405e22-eb49-11e7-90df-7e15fdb417d5.png)
![image](https://user-images.githubusercontent.com/24751265/34382429-ca5daafa-eb49-11e7-8cb7-5964ce6f5315.png)

**Comment by Macley-Kun** [comment]
Can you specify a bit what you mean with: "Some instructions entered, there will be an error, the command will not play a role."?

Wich instructions? You mean entering commands? Do you mean an error in Discord or the one refering here? And what you mean with play a role? We play music not roles..?

**Comment by hank0531** [comment]
For example: after entering .xp
Did not jump chart, then the background error message appears

**Comment by Macley-Kun** [comment]
Your error is that you don't get the .xp image? Did you do any source edits?

**Comment by hank0531** [comment]
I have not done any source code editing

**Comment by Macley-Kun** [comment]
You tried backing up the db and json file and re-installing?

**Comment by hank0531** [comment]
I have reinstalled it

**Comment by Macley-Kun** [comment]
goodjob

**Comment by Kwoth** [comment]
reinstall redis, or open redis.cli.exe from commandline and do FLUSHALL.

But basically this error means you've edited your xp.png and messed something up.
