### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by hank0531** [Kwoth/NadekoBot#1958]
Some instructions entered, there will be an error, the command will not play a role.
![34382397-80405e22-eb49-11e7-90df-7e15fdb417d5](https://user-images.githubusercontent.com/24751265/34382516-71cf2962-eb4a-11e7-8227-05c06991f676.png)
![34382429-ca5daafa-eb49-11e7-8cb7-5964ce6f5315](https://user-images.githubusercontent.com/24751265/34382517-71f6c0c6-eb4a-11e7-8ab0-cf340806fbb8.png)

**Comment by shivaco** [comment]
#1957 :^)
