### ISSUE TITLE
Added typing articles not being saved after updates.

### ISSUE THREAD

**Issue by rayne510** [Kwoth/NadekoBot#1959]
File is there but bot reverts to original typing articles after removal with bot command.

**Comment by Macley-Kun** [comment]
Typing articles? What you mean with that ^_^ ??
If your doing source edits. Then that would be normal.

**Comment by Kwoth** [comment]
Tested this. Works fine both added and removed changes are there after restart.

If you're manually editing the file, file is now called typing_articles3.json
