### ISSUE TITLE
Currencies in .convertlist are listed twice

### ISSUE THREAD

**Issue by numbermaniac** [Kwoth/NadekoBot#1960]
![screen shot 2017-12-28 at 13 29 27](https://user-images.githubusercontent.com/5206120/34398463-2dd69f4a-ebd3-11e7-85df-264d6ff5d830.png)
This is on the public Nadeko bot. Most of the currencies seem to be listed twice.

**Comment by MaybeGoogle** [comment]
Verified with selfhost.

units.json doesn't list currencies twice....

Random thing that probably doesn't matter: SKK is the one that doesn't repeat, also happens to be the last on in units.json 🤔 .

**Comment by Macley-Kun** [comment]
@Kwoth label as bug ^_^ ?
