### ISSUE TITLE
Streamer option broken with newest build

### ISSUE THREAD

**Issue by evacfk** [Kwoth/NadekoBot#1962]
Since updating last night to the latest linux build, Nadeko picks up anyone who is "Playing" anything as streaming.

I have not made any chances outside of updating via Git.

http://evac.gg/i/iyxrh.png

Thanks.

**Comment by Kwoth** [comment]
Update again, tell me if it works.

**Comment by evacfk** [comment]
Working as intended again Kwoth.

Thanks for your quick fix.

**Comment by Kwoth** [comment]
<3
