### ISSUE TITLE
Every command that has to do with currency doesn't work

### ISSUE THREAD

**Issue by RainingMen** [Kwoth/NadekoBot#1966]
I tried using .gc and .timelyset 100 1. For .timelyset, it didn't set and for .gc nothing happened. Can't do any other command since I don't have currency.

**Comment by SparkyKitteh** [comment]
Are you self-hosting?

**Comment by Kwoth** [comment]
SERVER OWNERS ARE NOT BOT OWNERS. All owner-only commands require you host the bot. Hosting means you are running a nadekobot on your own computer. If you want to learn how to host the bot yourself, type `.guide`
