### ISSUE TITLE
deletecurrency not working properly

### ISSUE THREAD

**Issue by TheSacrificed** [Kwoth/NadekoBot#1967]
So issue is technically resolved due to the discord server but I'll post the problem here so it can be noticed. Currently the deletecurrency command is not working properly because currency data is currently being saved in a table in the data base called discorduser instead of the currency table. While the deletecurrency goes through and still deletes what ever was in the currency table due the bot pulling the data from discorduser instead of currency, nothing happened to the currency people had whenever the command was used. This seems to be an issue that has sprung up during the recent version change, v2.11, I think. Thanks again for the help on discord.

**Comment by Kwoth** [comment]
True.
