### ISSUE TITLE
Twitch feed notification

### ISSUE THREAD

**Issue by Glaived** [Kwoth/NadekoBot#197]
When a new post is sent by the streamer, Nadeko wrote part of the message (X characters) and provides the link to the post.
e.g. :

```
NadekoBot
« Surgery Went Good #SocialClub . Recoverying is going to take longer then expected so i don't know if i will be able to be...  » https://www.twitch.tv/Glhrmzz/p/519252821459625758
```

Demo: http://codepen.io/Glaived/embed/XdVxzZ?height=700

Doc:
- https://blog.twitch.tv/attention-broadcasters-channel-feed-beta-is-now-available-28f7c3dff995
- https://github.com/justintv/Twitch-API/blob/master/v3_resources/channel_feed.md#get-feedchannelposts

**Comment by Kwoth** [comment]
We would need to add a new command for this I guess, its not really possible to add it to current ~twitch

**Comment by Glaived** [comment]
It's an idea: `~twitchFeed` or `~twitchPost`
