### ISSUE TITLE
.autohentai does not respect .nsfwtbl

### ISSUE THREAD

**Issue by Zurhydryh** [Kwoth/NadekoBot#1970]
Images with tags blacklisted by .nsfwtbl are still posted when the .autohentai command runs.

**Comment by Macley-Kun** [comment]
Have you tried asking help in #help ?
Are you refering to the private or public nadeko?
Have you checked that the pics sended by the bot contain that tag from the source? So we can conclude that it's not a user error?

**Comment by Zurhydryh** [comment]
I haven't tried asking in #help, I didn't think of that, sorry.
This is with the private nadeko.
The pics do include the tag. I checked the source of one of the images posted, and blacklisted a tag from it. After restarting the .autohentai command, the same image was posted within 10 minutes.

**Comment by Macley-Kun** [comment]
Mhm strange. Can you post the commands you used to setup the autohentai and the blacklisted tag in here? Then i can test it out and mark this as a bug ^_^

**Comment by Zurhydryh** [comment]
First I used '.autohentai 60 yuri|tentacles' and eventually [this image](https://gelbooru.com/index.php?page=post&s=view&id=4012711) was posted. I used '.nsfwtbl boy' and '.nsfwtbl male', and just for good measure I restarted the ,autohentai command. Shortly after the same image was posted.

I've just now realized that those aren't the exact tags on the image, and so I've added the unwanted tags exactly as they appear to the blacklist. So far after a few dozen posts, things seem to be working. I'll close this for now unless something comes up. Sorry about that!

**Comment by Macley-Kun** [comment]
Great to hear you found the issue by yourself :-) i had the same issues before with tags. Have fun with nadeko!

**Comment by Seathre** [comment]
I would actually petition to reopen this.

I verified the tags on [this image](https://gelbooru.com/index.php?page=post&s=view&id=4245313) in question, and it does indeed match a tag on my blacklist.

Funny enough, the image appeared right after I checked my blacklist:
https://i.imgur.com/HOhHYG5.png

**Comment by Seathre** [comment]
A little update. So far, the only website that Nadeko seems to not be respecting the tag blacklist for is Gelbooru. I've not seen any images with blacklisted tags appear from any other website.
