### ISSUE TITLE
.acr command variables.

### ISSUE THREAD

**Issue by TheHairyUnicorn** [Kwoth/NadekoBot#1971]
Hello guys, just wondered if there were any way to adjust the .acr command to respond to people who say something including a certain phrase - example below:

If someone were to use .acr as 

> .acr "hello" hello 

it would produce the response from Nadeko if users were to type only 'hello' rather than 'hello world' as an example.  Is there a way to make it so that I wanted to raise a response from Nadeko if 'hello' was used within a phrase (such as 'hello world' AND 'hello %user%') or would I have to construct a .acr response for each possible phrase?  

If not, are there any plans on adding the ability to add a wildcard variable that would allow the above examples to take place?

Hope this makes sense!

**Comment by SparkyKitteh** [comment]
.crca makes the custom reaction called anywhere in a sentence. Use .lcr to get the I'd, then .crca id

**Comment by TheHairyUnicorn** [comment]
Many thanks, worked a charm 👍
