### ISSUE TITLE
Mysterious Nadeko mute

### ISSUE THREAD

**Issue by T-POPB** [Kwoth/NadekoBot#1972]
So, for the past two weeks my members, including staff, have been getting muted. I thought it was another staff member so I revoked the staff roles from everyone, however, it still happened. I have logs of nadeko just muting on its own and no one has been inputting the command. I have a way to see all messages as well as all deleted messages that only I can access. Nadeko is just muting my members randomly. Even muting members who never really talk at all. I don't know if anyone else has been having this issues. So far, no one else has that I have talked to. I, myself, even got muted. However, being server owner I cannot be muted but the "nadeko-mute" role was still added to my roles which includes my other members as well. Only random members have been muted. I do have antispam set up but no one has posted 3 of the messages in a row which would result in a mute. I also have slowmode disabled thinking that might help but I am not sure of the problem, neither are the support memebers on the nadeko server. Hopefully someone can shed some light onto this anomaly.

**Comment by shikhir-arora** [comment]
Can you post some screenshots from the audit log?

**Comment by SillyBirds** [comment]
Maybe `.antispam` is on with a low value?
