### ISSUE TITLE
%mention% placeholder does not work if the bot has a set nickname.

### ISSUE THREAD

**Issue by tukimoop** [Kwoth/NadekoBot#1974]
Title. It seems the placeholder %mention% only works if the bot has no nickname assigned.

![](http://puu.sh/yT2aN/9b96b48495.png)

~~right, the duplicate nicknames dont help.~~

**Comment by willysunny** [comment]
Make sure you changed the nickname of the bot via .setnick, instead of right click and change the nick name of the bot. Or else you'll break %mention%

**Comment by tukimoop** [comment]
still broken using .setnick. ![](http://puu.sh/yT2Yn/c4fbcfd6b8.png)

**Comment by TwinDragon** [comment]
If I'm correct, this is known to be broken for a long time. I did however find a way around this that works. Basically, the %mention% placeholder only works if the bot does not have a nickname, at all. If you set one, it'll no longer work as intended until its removed.

This is how I got around it: https://i.imgur.com/mzWmgyK.png - Basically, just mention the bot itself and it works even through nicknames.

**Comment by tukimoop** [comment]
I'm just here to report issues ¯\_(ツ)_/¯

**Comment by TwinDragon** [comment]
Yeah, I'm just noting a work-around in the meantime though.

**Comment by shikhir-arora** [comment]
You’re correct @TwinDragon, this has been this way for a while. 

```cs 

_reps.TryAdd("%mention%", () => $"<@{client.CurrentUser.Id}>");

```

So the placeholder is just parsing the ID of the bot, like `<@ID>` which looks to the username assigned.

**Comment by Kwoth** [comment]
Not possible due to how custom reactions work right now.
