### ISSUE TITLE
Creating Custom Trivia Questions

### ISSUE THREAD

**Issue by Durgon** [Kwoth/NadekoBot#1976]
I'm trying to create some custom trivia commands and and I'm having trouble getting nadeko to display the image from a direct image link. (example provided)
[questions.txt](https://github.com/Kwoth/NadekoBot/files/1604898/questions.txt)

Is there some way to do this?

**Comment by anigatari** [comment]
```
[
  {
    "Category": "Gundam",
    "Question": "Can you name that Mobile Suit?",
    "Answer": "Driesen",
    "ImageUrl": "https://i.imgur.com/TDzpYsG.jpg",
  },
]

```

**Comment by Durgon** [comment]
Works great. Thanks :)

**Comment by Macley-Kun** [comment]
@Durgon can you close the issue please ^^ ?
