### ISSUE TITLE
.prefix

### ISSUE THREAD

**Issue by LunarSera** [Kwoth/NadekoBot#1977]
Obviously requires Admin privileges but the help string only says its from the module administration.
Does not list that it requires any permissions.
Also the log correctly says I used too many parameters.
Sorry for being stupid with the bot xD

**Comment by Macley-Kun** [comment]
@Kwoth It does require a certain level of permission to use this command. Should we adjust docs and help to this?

**Comment by Kwoth** [comment]
Ah, can't fix actually, as it's an overload. I can try but probably not possible.

**Comment by Kwoth** [comment]
(because parameterless .prefix requires no permissions)
