### ISSUE TITLE
.mute doesn't do anything for voice channels

### ISSUE THREAD

**Issue by NyteLyte** [Kwoth/NadekoBot#1978]
So, when I mute someone, a permission setting is supposed to be created in all channels that disallows you from reading messages, I believe it should do same with voice, just instead of read messages, it disallows you to speak, but it doesn't do anything in voice channels.

Tried .voicemute, it doesn't do anything at all.

**Comment by Macley-Kun** [comment]
I think issue #1556 already covers this problem. Maybe you can close this issue and comment on the #1556 one.

**Comment by Kwoth** [comment]
Yes
