### ISSUE TITLE
[Request] Module Enabler/Disabler in NadekoInstaller

### ISSUE THREAD

**Issue by thebeastgamer25** [Kwoth/NadekoBot#1980]
This would be helpful if for example I wanted to disable Fun, or Music, in case I dont want it globally

**Comment by TwinDragon** [comment]
Why not just use the permission system to disable the modules? Little work, but that's what the permission system is for if you don't want particular modules.

**Comment by thebeastgamer25** [comment]
I want this on a global scale tho @TwinDragon

**Comment by Kuromaru420** [comment]
Isn't that exactly what `.gmod` does?

**Comment by thebeastgamer25** [comment]
Sorta, but it still has it in the help menu and such.
