### ISSUE TITLE
hi how i can fix this problem . 

### ISSUE THREAD

**Issue by mina9999** [Kwoth/NadekoBot#1983]
![54634754675467548548](https://user-images.githubusercontent.com/28566705/34669919-48d97380-f489-11e7-839d-08f892d927e8.png)

**Comment by Macley-Kun** [comment]
if you want, you can state your solution here :P not required btw

**Comment by mina9999** [comment]
i have that error bc i changed the BetflipMultiplier to 3.0 and it fix it now , i changed back to 2.0 .
