### ISSUE TITLE
.reactionroles

### ISSUE THREAD

**Issue by Arnemetia** [Kwoth/NadekoBot#1985]
Hello !

I deleted a channel in which I had several reactions roles, and when I want to create others, the bot tells me "You've reached the limit on ReactionRole messages. You have to delete some."

what should I do?

**Comment by tukimoop** [comment]
`.reactionroleslist`

`.reactionrolesremove`

**Comment by Arnemetia** [comment]
I have already tried, these commands give no results

**Comment by clairvoyant216** [comment]
@Arnemetia **.reactionrolesremove 1** (You can spam this command 5 times)
