### ISSUE TITLE
.award not working, not dropping currency. 

### ISSUE THREAD

**Issue by Sethybae** [Kwoth/NadekoBot#1987]
when using .award @/myself the cmd operator says the command had an 
Error: Failed to Pars Int32

**Comment by tukimoop** [comment]
number before user.

`.award 18238 @user`

**Comment by Sethybae** [comment]
is there a way to force drop a flower? meaning is there a command that drops a flower on command, rather than being automated by the bot?

**Comment by Sethybae** [comment]
is there also a way to take flowers from people?

**Comment by tukimoop** [comment]
`.take 2637 @user`

**Comment by Kwoth** [comment]
Use #help channel for questions like these
