### ISSUE TITLE
Embed Thumbnail field broken.

### ISSUE THREAD

**Issue by SyndicateDiscord** [Kwoth/NadekoBot#1988]
Replace "thumbnail":"" with
"thumbnail": { "url": ""}

**Comment by clairvoyant216** [comment]
@SyndicateDiscord It's in beta stage RN. Give it some time.

**Comment by Kwoth** [comment]
Fixed, make sure to refresh the page or clear browser cache if it still shows the thumbnail with url property

**Comment by SyndicateDiscord** [comment]
@Kwoth It's not fixed. I'm saying you need to replace your code 
**"thumbnail":""**

with:
**"thumbnail": { "url": ""}**

**Comment by Kwoth** [comment]
No, why would i do that. It's simpler like this.

**Comment by SyndicateDiscord** [comment]
@Kwoth Because, I use the useful embed builder for webhook posts, not just for Nadeko. I think many others do the same. The embed breaks with the current `"thumbnail":""`. That's why I was asking you to replace it.
