### ISSUE TITLE
.delmsgoncmd error

### ISSUE THREAD

**Issue by Mjk53** [Kwoth/NadekoBot#1989]
as the new update comes out for windows with the added `.bj` feature there is an error with the `.delmsgoncmd` when a server has the `.delmsgoncmd` an error pops up after `.bj 50` is executed and the following error comes up https://gyazo.com/f03b3970ce5812f094a1d15cb600c382 i think the problem is since the command is auto deleted then put in that the main `.delmsgoncmd` is trying to delete the same message but cant because its already deleted on its own but who's to say i'm probably wrong but was not sure if it was worth mentioning or not

**Comment by LunarSera** [comment]
I concur that this happens on linux as well. though I get a different error. 
2.13.4 Ubuntu 16.04
https://pastebin.com/p8xXUJLj

**Comment by Kwoth** [comment]
Yea, just ignore it. I'll remove that log line.
