### ISSUE TITLE
nadekobot crashing on launch

### ISSUE THREAD

**Issue by redqo** [Kwoth/NadekoBot#1990]
yet another crash on launch error, new to this so cant fix it myself.
running on windows on the latest version, tried reinstalling redis, running as admin, double checking token etc but nothings worked yet. any ideas what silly mistake ive made? 
![image](https://user-images.githubusercontent.com/35387137/34901315-bf29a5c6-f800-11e7-9ba4-3c396e7ced46.png)

**Comment by shikhir-arora** [comment]
Your token is probably incorrect, or something along those lines if you're getting a `401: Unauthorized` error.

**Comment by redqo** [comment]
all fixed, chrome extension was making the token lowercase and its case sensitive.

**Comment by shikhir-arora** [comment]
Glad to hear. If you can close the issue that'd be appreciated!
