### ISSUE TITLE
Nadeko Music....

### ISSUE THREAD

**Issue by NeeAfk** [Kwoth/NadekoBot#1991]
I don't know what do anymore. I've reinstalled ffmpeg multiple times, each time restarting my pc. No matter what I do the music won't work. It had just been working when after a song ended it stopped the entire playlist and said **"Destroying"** in the cmd. After that I restarted the bot and now all I get is **"No song found"**. 
![image](https://user-images.githubusercontent.com/26068101/34901546-5284199e-f7d1-11e7-87fc-0499eaa0ec59.png)
![image](https://user-images.githubusercontent.com/26068101/34901558-6f474326-f7d1-11e7-935e-d8f6962ee03d.png)

**Comment by shikhir-arora** [comment]
Does this happen with any song/URL? `.queue <some song>`  -- still the same error?

**Comment by NeeAfk** [comment]
Yes it happens with song urls for youtube and just general searching. I tried a soundcloud link and it worked fine though, I should also mention I made a new api for the bot as well thinking that might have been the problem. Still doesn't work though @shikhir-arora .

**Comment by shikhir-arora** [comment]
Can confirm it's not you and this is not working for YouTube in the current/latest version. I'll have to look further into it.

**Comment by NeeAfk** [comment]
Glad at least someone else is having this problem. It sucks though cause it was **JUST** working...

**Comment by shikhir-arora** [comment]
```bash

4|Nadeko   | 0 02:06:36 <GetResolveStrategy>d__2 | Getting link
4|Nadeko   | 0 02:06:37 <ResolveSong>d__2 | WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
4|Nadeko   | WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
4|Nadeko   | WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
4|Nadeko   | WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
4|Nadeko   | WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
4|Nadeko   | Traceback (most recent call last):
4|Nadeko   |   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
4|Nadeko   |     "__main__", fname, loader, pkg_name)
4|Nadeko   |   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
4|Nadeko   |     exec code in run_globals
4|Nadeko   |   File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
4|Nadeko   |   File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
4|Nadeko   |   File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
4|Nadeko   |   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1988, in download
4|Nadeko   |   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
4|Nadeko   |   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
4|Nadeko   |   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1599, in _real_extract
4|Nadeko   | TypeError: argument of type 'NoneType' is not iterable
4|Nadeko   | 0 02:06:37 <GetResolveStrategy>d__2 | No song found. Data less than 6
4|Nadeko   | 0 02:06:37 CommandHandler | Command Executed after 0/0/1.54s
4|Nadeko   | 	User: .vlexar#5320 [243902693666455553]
4|Nadeko   | 	Server: EC || Bot & Dev || General [249664293656592384]
4|Nadeko   | 	Channel: adminlogs-spectra [277284038254002177]
4|Nadeko   | 	Message: .queue https://www.youtube.com/watch?v=MiHqH_2XGwc
```

There's a problem with Nadeko's video downloading through `youtube-dl` it seems, and it is running the latest version of `youtube-dl` as well:

```bash
vlexar@node1:~/main/vlexar$ /usr/local/bin/youtube-dl --version
2018.01.07
```

Can also confirm that it is not directly related to `youtube-dl` or the specific videos because I use `youtube-dl` for many things including another bot, which works fine. Will try to look into it shortly as I don't use Nadeko for music.

**Comment by shikhir-arora** [comment]
Think I found a fix, let me confirm and will update.

**Comment by NeeAfk** [comment]
Rog

**Comment by shikhir-arora** [comment]
https://github.com/Kwoth/NadekoBot/pull/1992 should be pulled shortly, but you'd have to edit it manually for now. The file is in`NadekoBot/NadekoBot.Core/Services/Impl` and is `Ytdl.cs` 

You can change the contents to the following: https://raw.githubusercontent.com/shikhir-arora/NadekoBot/1.9/NadekoBot.Core/Services/Impl/Ytdl.cs

**Comment by NeeAfk** [comment]
Um...
![image](https://user-images.githubusercontent.com/26068101/34902038-1251925e-f7d9-11e7-9b4e-cfc1468fdda4.png)

**Comment by shikhir-arora** [comment]
Unfortunately for Windows you have to wait till the next release is compiled.

**Comment by NeeAfk** [comment]
Oh well darn.

**Comment by Macley-Kun** [comment]
@NeeAfk for music related issue we have an already made issue were you can comment on: #1053.
You can close this one and refer to this issue there.

**Comment by shikhir-arora** [comment]
@Macley-Kun This issue will be resolved in the PR I pushed. See above.

**Comment by Macley-Kun** [comment]
Woops gotta get my glasses when i'm reading issues on GitHub 🤓 sarry
