### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by LunarSera** [Kwoth/NadekoBot#1993]
So The bot responds to me deleting the ping of a user that isnt in my server
step 1. copy someone's id that you know isnt in your server
step 2. send <@!userid>in your server
step 3. delete the message.

bot response in terminal https://pastebin.com/BvnVTdcY

basically is this normal or should we be looked to create efficiency. apparently the bot thought something was needed with this action, otherwise it wouldn't have thrown that exception. I can keep and eye on stuff like this and report as much as needed, if that's what you want.

**Comment by shikhir-arora** [comment]
It's just Discord.Net telling you that a field was empty or null and shouldn't be. This can happen for many reasons. And it's part of the library (or any library, really) -- so this isn't something that is really an issue for efficiency.
