### ISSUE TITLE
Reminders no longer pinging after new format.

### ISSUE THREAD

**Issue by Westerlies** [Kwoth/NadekoBot#1994]
^

**Comment by Macley-Kun** [comment]
👀 maybe show us some nice screenpics and logs?

**Comment by Westerlies** [comment]
https://cdn.discordapp.com/attachments/342331773776035847/401665774521155586/Screenshot_20180113-111225.jpg

What, like this?

Not a whole lot to show. Just doesn't ping. The gibberish was supposed to ping a role. It doesn't ping the user who set it either anymore.

**Comment by Macley-Kun** [comment]
thx, neh we ussually provide screenshots so kwoth can just look and mark
the issue accordingly. @kwoth bug and/or investigate tag :eyes: ?

2018-01-13 10:18 GMT+01:00 Westerlies <notifications@github.com>:

**Comment by shikhir-arora** [comment]
This may be related / caused by https://github.com/RogueException/Discord.Net/issues/824

**Comment by Kwoth** [comment]
Completely unrelated. On the phone you can't see the mentions inside the embed. But it doesn't mention anyway. I might move reminder text as message content.
