### ISSUE TITLE
Bot Currency Total decreases every time `.rafflecur` is used

### ISSUE THREAD

**Issue by theLAZYmd** [Kwoth/NadekoBot#1996]
So if someone types .rafflecur 20 then the raffle ends and the user gets their 20 back, the Nadeko .$ total sum will also decrease by 20. It seems because Nadeko is holding those 20 flowers for the user temporarily then giving them away, it's counting them as a loss.
Same obviously applies for `.rafflecur mixed`. Leads to unrepresentative count in Nadeko's .$

**Comment by Kwoth** [comment]
#1995
