### ISSUE TITLE
"stopping reaction event because message was deleted" cannot do reaction events

### ISSUE THREAD

**Issue by UnbendableStraw** [Kwoth/NadekoBot#2000]
After updating to version 2.13.6, when I do event reactions the message immediately disappears and the nadkeo logs show "stopping reaction event becvause message was deleted"

Ubuntu server 16.04

I've also wiped and reinstalled nadeko, only copying in data and credentials. It's still broken. Tried starting with pm2 and not in pm2

**Comment by Macley-Kun** [comment]
🎉 Happy #2000th issue! 🎉

Try just re-installing, place the db and credentials back and see how it floats.

**Comment by UnbendableStraw** [comment]
That's exactly what I did when I mentioned "I've also wiped and reinstalled nadeko, only copying in data and credentials. It's still broken. Tried starting with pm2 and not in pm2" at the end of my issue

**Comment by Macley-Kun** [comment]
Woops sorry didn't red that it's still broken.

Does the bot have permission to write the message? No other bot deleting the message?

**Comment by UnbendableStraw** [comment]
Yeah, and it was all working fine right before I updated to the latest from 1.8.4. The update is the only thing that's changed

**Comment by UnbendableStraw** [comment]
My NadekoBot.db currency was configured as :eggplant: so in order to fix this you need to run ".bce CurrencySign :eggplant:" where eggplant is your desired currency.

Note, ".bce CurrencySign eggplant" will not work, you need to specify an emoji, at least in my case

**Comment by Macley-Kun** [comment]
Ah yes, you need to copy paste the litter emoji. You can also make a custom one and insert that. Should also work.

Rip issue 2000th party :c

**Comment by UnbendableStraw** [comment]
At least it was an easy fix, thanks!
