### ISSUE TITLE
Self-Hosted Bot Can't Connect to Redis, Bot Doesn't Work, and Updater Doesn't Open

### ISSUE THREAD

**Issue by savemedoctah** [Kwoth/NadekoBot#2003]
In case the title isn't explanatory enough, the bot tells me it's not possible to connect to the redis server. As an obvious result, the bot doesn't work. I tried to open the Updater, in case the bot just needed an update (I'm on like 2.13 or whatever the latest as of like a day ago is, but I figured I'd check). The Updater won't launch. Like, doesn't even show in task manager. I have not messed with the files, and I've been having that issue with the bot not being able to execute commands requiring others to be tagged (ie .award or .waifustats). The error is posted below.
Should I reinstall, should I wait it out, is it even an issue on the bot side (as opposed to redis)...?
![nadeko error](https://user-images.githubusercontent.com/35473840/34967854-94a2ca96-fa33-11e7-88f3-173a17e63a46.png)

**Comment by Kwoth** [comment]
I'd suggest you reinstall. It's either your antivirus or you just removed redis from your PC. But considering your updater won't even open anymore, just do a complete reinstall (make sure to save your credentials.json and NadekoBot.db)

**Comment by savemedoctah** [comment]
Ironically, restarting my computer seems to have done the trick, but now I have the side effect of the bot registering commands like .timely twice, despite the user only typing it once. Looks like I may end up reinstalling anyways.

**Comment by Macley-Kun** [comment]
@savemedoctah did reinstalling worked for you? Kinda strange with the double message thing. Normally i stop the whole bot, start it once and things are okish again.
