### ISSUE TITLE
.lsar doesn't output a response

### ISSUE THREAD

**Issue by AbcentMineDead** [Kwoth/NadekoBot#2004]
[aSWeDWfr.txt](https://github.com/Kwoth/NadekoBot/files/1635274/aSWeDWfr.txt)

I have 224 roles and a large amount are included in the default auto assignable group. I don't use any other group. I believe there are so many now it cannot paginate correctly as is. I very much need to have .lsar working correctly somehow.

**Comment by Macley-Kun** [comment]
I think your issue is the following:
The logs say: Description length must be less than or equal to 2048.

Assuming the amount of roles that should be displayed is larger then 2048 in lenght. Would make me believe you just have to many assignable roles.

Can you try removing some selfassignable roles and try to `.lsar` again?

**Comment by Macley-Kun** [comment]
Also maybe you wanna reduce the amount of roles, 224 is quite a number. Maybe try to work with with a set of roles that fufill permissions only, a set of roles that have a specific color.
![image](https://user-images.githubusercontent.com/26381427/34991964-cdabcf02-facb-11e7-8a63-fe449aba2005.png)

**Comment by shivaco** [comment]
@Macley-Kun They can't check `.lsar` to see which roles are self-assignable.

**Comment by Macley-Kun** [comment]
They have to remove some roles @shivaco so the .lsar can output the roles he has added.

**Comment by shivaco** [comment]
Then wouldn't they just have to take guesses on which roles are self-assignable and which ones are not? @Macley-Kun

**Comment by AbcentMineDead** [comment]
@Macley-Kun It should paginate? 2048 is a discord character limit I'm not requesting Nadeko break. I cannot remove the self assignable roles or rather will not without a justified reason to do so. It would be very burdensome.

Is my only choice to shorten the default group and be mind full when I redo it all while using groups?

**Comment by LunarSera** [comment]
I know on mobile Android, discord itself has a broken embed option where it shows 15 lines or so before cutting the beat off.

**Comment by AbcentMineDead** [comment]
lol beat off

**Comment by Macley-Kun** [comment]
@shivaco well i would just do `.rsar` on each role.
@AbcentMineDead Mhm true, nadeko wants to paste more then 2048 because it doesn't paginate it.
@Kwoth Possible to implement that: if lenght >2048 that the .lsar is paginated?

Also sorry i should've understood what paginate ment.

**Comment by Kwoth** [comment]
@Macley-Kun no need to ping me, i see the issue.

Can you try `.lsar 2` or any other page, and tell me if you can see the roles on that page?

**Comment by AbcentMineDead** [comment]
.lsar 2
outputs the correct response. It's empty.

.lsar 1
outputs nothing. It's "full"?

**Comment by AbcentMineDead** [comment]
@Kwoth I'm sorry to ping you but it's extremely important to my team for us to have to ability to correctly use .lsar. At this time I estimate we have 174 assignable roles. Recently our database was corrupted and we readded everything(which was a lot). At no point did we realize adding back these assignable roles would error the .lsar command.

If having too many in default group errors maybe have them use the next group when default us full and so on. At what exact point would the output of .last stop outputting? Removing 100 assignable roles is a daunting task to find out I need to remove more. Is there possibly an option to remove all the assignable roles via command? We self host.

Cheers and thank you for this amazing project!!

**Comment by Kwoth** [comment]
Are you sure you're on latest version? DM me your NadekoBot.db if you're sure you are. @AbcentMineDead

**Comment by AbcentMineDead** [comment]
@Kwoth Can we possibly take this to private?

**Comment by Kwoth** [comment]
I just told you to DM me on discord.
