### ISSUE TITLE
Owner??? Not listening

### ISSUE THREAD

**Issue by theman23290** [Kwoth/NadekoBot#2005]
I am the Owner to my server. That is for a fact. I have made a Nadeko roll and assigned it to me. But when I go and do Bot Owner only commands, it does not even listen. I type the command right, but it does not want to listen to the command I say. Please help.......

**Comment by shikhir-arora** [comment]
Server owner is not bot owner. Bot owner is only if you self host the bot and not use the public version.

**Comment by theman23290** [comment]
............ Ok............. Sorry for bothering you then...........

**Comment by theman23290** [comment]
Just one more thing then. If I download the Nadeko code and run it and do the command I want (`.timelyset`), then can I just stop Nadeko on my computer and the `.timely` work now without my computer running nadeko?

**Comment by shikhir-arora** [comment]
No, you’ll need to keep it running to keep the bot online.

**Comment by theman23290** [comment]
Ok, so if I don't run Nadeko all the time, then most of the gambling is down?

**Comment by shikhir-arora** [comment]
If you don’t keep the bot running it’ll be completely offline, not just the gambling. This is your own bot in this case, not the public version of Nadeko. That is its own thing and you can’t use it and be a bot owner.

**Comment by theman23290** [comment]
Oh, ok, thanks

**Comment by Macley-Kun** [comment]
@theman23290 close issue ples
