### ISSUE TITLE
Reactionroles Command emote not found

### ISSUE THREAD

**Issue by Theman839** [Kwoth/NadekoBot#2006]
Hi I attempting to test the reaction roles command with a simple setup.  On the discord side the command is deleted with no response. This is a self hosted instance

`.reactionroles NA :regional_indicator_n: EU :regional_indicator_e:`

If I check the logs I can see:
```
0|Nadeko   | 0 18:06:43 NadekoTopLevelModule | Emote 🇳 not found.
0|Nadeko   | 0 18:06:43 NadekoTopLevelModule | Emote 🇪 not found.
0|Nadeko   | 0 18:06:43 CommandHandler | Command Executed after 0/0/0.056s
0|Nadeko   |    User: TheMan839#3994 [338483034787676171]
0|Nadeko   |    Server: The Trust Circle [338148992812711937]
0|Nadeko   |    Channel: testautoroles [402878864960913408]
0|Nadeko   |    Message: .reactionroles NA 🇳 EU 🇪
```

I've tried other emotes like the :flag_us: and :flag_eu: I've checked Nadeko role has all permissions. Is there a certain set of emotes I should be using maybe?

Thank you

**Comment by shivaco** [comment]
`.rero` doesn't work with Discord's default emojis. Try to use some custom one instead.

**Comment by Theman839** [comment]
Thank you that makes sense. Doc says **server emojis**
