### ISSUE TITLE
Nadeko offline?

### ISSUE THREAD

**Issue by CosmicOutlaw** [Kwoth/NadekoBot#2007]
Nadeko worked perfectly fine over the last couple of weeks for me, suddenly the bot is offline and doesn't react to any commands. What can I do?

**Comment by Killer-Kitten-Heart** [comment]
@CosmicOutlaw Lol

**Comment by Kwoth** [comment]
Yup, I was asleep and other person who can restart the server wasn't around. Sorry. Will be back soon. No info atm as to what happened.
