### ISSUE TITLE
Shes just dead. 

### ISSUE THREAD

**Issue by Killer-Kitten-Heart** [Kwoth/NadekoBot#2008]
ALRIGHTY I have restarted a server made a new server still getting 6006 even resized it. 
**Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: An exception occurred while reading a database value. See the inner exception for more information. ---> System.FormatException: String was not recognized as a valid DateTime.** Get that error after new install also

**Comment by Kwoth** [comment]
screenshot the console

**Comment by Macley-Kun** [comment]
@Killer-Kitten-Heart Can you post a screenshot of the console? If the issue is still persisting?
