### ISSUE TITLE
Change the image size in module XP

### ISSUE THREAD

**Issue by FaL03** [Kwoth/NadekoBot#2009]
Hello, I want to make avatar bigger picture of the clan as well to increase. If you change in "XpService.cs", the image becomes more, but it is cropped in half.

Tell me where to make changes, maybe I just haven't found the right settings file.

**Comment by Macley-Kun** [comment]
We have a speciale channel in NadekoLog to ask these type of questions.
You can go to nadeko-modding. The people in there have more knowledge about modding Nadeko.
