### ISSUE TITLE
Public Nadeko Blackjack issue

### ISSUE THREAD

**Issue by Nhyv** [Kwoth/NadekoBot#2013]
**Public Nadeko** starts the blackjack game whenever you use .bj x (x for the amount) but nothing happens and it gets stuck there and if you try doing the command again nothing happens, the message gets instantly deleted.

**Comment by Kwoth** [comment]
Fixed in the latest update. If someone gets stuck, there will be an error in the console that says you should send the error to me, and when you do i'll figure out what's the problem.
