### ISSUE TITLE
Regional indicator not displaying proper icon for BlackJack in Android

### ISSUE THREAD

**Issue by drake0727** [Kwoth/NadekoBot#2015]
bot is displaying text instead of the regional indicator.  See attached.

![hector](https://user-images.githubusercontent.com/18490814/35081118-8f4baefa-fbd7-11e7-9809-6cdfc887b4ba.png)
![screenshot_20180117-223446](https://user-images.githubusercontent.com/18490814/35081120-9184a640-fbd7-11e7-9f5e-4640e5cc420d.png)

**Comment by Nhyv** [comment]
That's not Nadeko, I just reported to Discord this issue for mobile emojis, they are gonna fix this for next release hopefully. Reproduced it with 3 different phones.

**Comment by Kwoth** [comment]
Works fine on some phones. Doesn't on others. Discord issue.

**Comment by Nhyv** [comment]
Yes, it is an Android version issue mainly so I can understand it working for certain phones

**Comment by Macley-Kun** [comment]
Update:
![image](https://user-images.githubusercontent.com/26381427/35336474-cf08d270-0118-11e8-8275-55860dea6d86.png)
Personnally i don't own a android so i can't test this out. But expect the next android update to fix this.
