### ISSUE TITLE
My .autoboobs and .autobutts commands aren't working

### ISSUE THREAD

**Issue by sennnns** [Kwoth/NadekoBot#2017]
My .autoboobs and .autobutts commands aren't working even tough i gave all the necessary rights to the bot (Nadeko) and enabled nsfw on the server.
Need help please!

**Comment by Macley-Kun** [comment]
Suggest using another bot that sends automatic stuff.
Or find an RSS-feed that sends you NSFW.

If you want to host nadeko you could try SkySilk. It's free and you can run Nadeko on it too. But this free "beta" isn't forever.

Also you can close the ticket, if your sufficient with the above solutions.
