### ISSUE TITLE
Bot has completely broken?

### ISSUE THREAD

**Issue by b1tchduck** [Kwoth/NadekoBot#2018]
Every time I attempt to start the bot, it successfully logs in and then proceeds to completely break, crashing and starting over (to the point where Discord told me it has reset the bot's token.) Checking the console and even attempting a complete uninstall/reinstall yielded no changes. Attached is a screenshot of the fullscreened console with both exception errors.
![teamviewer_2018-01-18_16-24-10](https://user-images.githubusercontent.com/23391230/35128610-690eac48-fc6c-11e7-8a98-eefb6f7c5083.png)

**Comment by Kwoth** [comment]
You edited either commands_strings.json or any of the languages in the _strings folder, so the bot can't parse it anymore.

**Comment by Macley-Kun** [comment]
@b1tchduck try re-installing your bot. Notify us if the issue is still present for you :-)
