### ISSUE TITLE
gambling bug

### ISSUE THREAD

**Issue by mina9999** [Kwoth/NadekoBot#2019]
bot is fast for gambling when the channel is nsfw mode . but when the channel is not nfsw mode bot is slow .

**Comment by Kwoth** [comment]
That makes no sense. Something to do either with your server, discord client, or something else.

**Comment by mina9999** [comment]
i fix it
it was bc of the filter 
![4567456745785678](https://user-images.githubusercontent.com/28566705/35191202-2c23c6a4-fe8a-11e7-9818-576211930216.png)
