### ISSUE TITLE
Change Plant Message

### ISSUE THREAD

**Issue by northerncarrots** [Kwoth/NadekoBot#202]
image is something other than a flower
http://i.imgur.com/p1tdA17.png

**Comment by Kwoth** [comment]
Should i change it to currency name?

**Comment by northerncarrots** [comment]
that sounds good

**Comment by northerncarrots** [comment]
it's also the same for some other commands like >heal (displays flower icon instead of currency)

**Comment by Kwoth** [comment]
It will be fixed in the next release, unless you are building from source.
