### ISSUE TITLE
[Feature Request] .say automatically removes commands' message

### ISSUE THREAD

**Issue by liljayyyy** [Kwoth/NadekoBot#2020]
Can we please have **.say** removes the message that was sent after executing so you don't have to manually delete that message 🙏

**Comment by Macley-Kun** [comment]
Ah ic your asking for a feature!
For these types of questions we refer to: http://feathub.com/Kwoth/NadekoBot
Try to look if the suggestion is made already, if it get's enough upvotes kwoth might make this :-)

**Comment by liljayyyy** [comment]
Ohh my bad, posting in the wrong section. DX

The link doesn't seem to work for me though, is the website down right now ?

**Comment by Kwoth** [comment]
Yeah, it's a third party website and it's down atm. Just wait until it's back and post it, could be a day, or a week.
