### ISSUE TITLE
(bug ) new version of nadeko using too much ram

### ISSUE THREAD

**Issue by mina9999** [Kwoth/NadekoBot#2021]
![5785678967897890](https://user-images.githubusercontent.com/28566705/35142513-c7da023e-fd13-11e7-8cbf-a07ccbfb94b0.png)

**Comment by tukimoop** [comment]
🤔 i don't see the problem. it's how it usually is.

**Comment by Macley-Kun** [comment]
It's quite hard to tell whenever or not nadeko uses more memory these days.

I've bin thinking to look at something like this: http://www.jetbrains.com/profiler/index.html

And maybe use the older version of nadeko, and see how much more memory were using.

**Comment by Kwoth** [comment]
What?

**Comment by Macley-Kun** [comment]
It's a tool to look into the memory usage (or other stuff) of an c# application. I though it would help mina to identify if nadeko indeed uses more memory then before.

**Comment by SpielefreakJ** [comment]
it looks like they are using public bots...
and no problem on my own
![2018-01-20 01_11_52- intern_botspam - discord-2](https://user-images.githubusercontent.com/28605085/35177421-88b07dec-fd7f-11e7-8c3a-65a06cceafdc.png)
