### ISSUE TITLE
Reaction is not a CurrencyEvent

### ISSUE THREAD

**Issue by misskoa** [Kwoth/NadekoBot#2023]
Version: NadekoBot v1.8.4

I've been having this problem for a while now, at-least for the last 4-5 months, but I'm only now trying to fix it. Seems like I can't start a reaction event. When doing `.startevent reaction` or `.startevent reaction 100`, there is no event to start.

I've updated the bot thinking it'll work but it didn't. 

```
        Message: .startevent reaction
        Error: Value is not a CurrencyEvent
```

I'm on Ubuntu Server 16.04.3 

Thanks.

**Comment by misskoa** [comment]
Solved, it's .startevent flowerreaction

**Comment by Kwoth** [comment]
Please update for the love of god : )
