### ISSUE TITLE
List quotes by specific user

### ISSUE THREAD

**Issue by seangenabe** [Kwoth/NadekoBot#2025]
Is there any way to list all quotes created by a specific user and/or the current user?

**Comment by Macley-Kun** [comment]
I’m not sure but there was a pull that was merged on here. I can look it up later for you. But this means you have to source edit your bot.

**Comment by Macley-Kun** [comment]
https://github.com/Kwoth/NadekoBot/pull/1944

**Comment by Macley-Kun** [comment]
@seangenabe is the above pull somewhat an answer or? You might wanna submit a feature request on here: http://feathub.com/Kwoth/NadekoBot. (Yes it's up again!)

**Comment by shikhir-arora** [comment]
Yeah that PR does exactly that. I just run it off my branch ¯\_(ツ)_/¯
