### ISSUE TITLE
.award does not DM user.

### ISSUE THREAD

**Issue by Dragon342** [Kwoth/NadekoBot#2026]
Commands such as .take and .give DM the user the amount taken/given along with a reason. However, it seems that .award does not, which is really disappointing. 

I'm not sure if this is an issue with my bot, or it is intended. But, having .award DM users would be a great improvement.

**Comment by Macley-Kun** [comment]
If your suggestion to be implemented, it's adviced to use featurehub!
http://feathub.com/Kwoth/NadekoBot

It's not intended to pm a user when he/she is awarded with flowers. They actully get mentioned in embed in the channel the .award was used in.

**Comment by Dragon342** [comment]
@Macley-Kun The website has been down for over a week...

**Comment by Macley-Kun** [comment]
We can only wait for it to go up again, but we only accept feature requests trough that. Sorry :/

**Comment by Macley-Kun** [comment]
@Dragon342 as this is a feature request. You can go to http://feathub.com/Kwoth/NadekoBot and upvote/submit this idea. If you have any other questions feel free to ask in #help or make another issue on here if it's needed.

You can close this one as it seems to be solved.
