### ISSUE TITLE
Repeating command in a specific channel

### ISSUE THREAD

**Issue by xalexslx** [Kwoth/NadekoBot#2027]
Hi,

I Would like to have some commands being repeated each X minutes on specific channels. For example, repeating cryptocurrencies command on a #coins channel or something similar. I know NadekoBot does have a repeat command, but it didn't work with commands.

Cheers.

**Comment by Macley-Kun** [comment]
We have a channel in NadekoLog called #help, maybe try asking these questions there first.

**Comment by Macley-Kun** [comment]
Idea2: You can submit a feature request on: http://feathub.com/Kwoth/NadekoBot to set an x amount of time to post a command ouput automatically.

I hope this answerd your question.
