### ISSUE TITLE
Shard 0 is scheduled for a restart

### ISSUE THREAD

**Issue by Conqube** [Kwoth/NadekoBot#2030]
https://gyazo.com/f530880375857e3c7ce0b42e70346cd1
Do i need upgrade my pc or something ? Because its windows 7.
I did everything that it needed but still doesn't work.
After a while this happens 
https://user-images.githubusercontent.com/28166876/35317806-2aa0ba5e-00e1-11e8-8382-cc7c54ee1549.png

**Comment by Macley-Kun** [comment]
YES

Met vriendelijke groet,
