### ISSUE TITLE
Public nadeko can't set permissions

### ISSUE THREAD

**Issue by invalidgamer** [Kwoth/NadekoBot#2033]
I believe all the commands from .srvrcmd, all the way to .allsrvrmdls
is not working at all. I'm also given an error when typing in .listperms ;; Failed to parse Int32

**Comment by Gremagol** [comment]
Can't verify, I updated to the latest version and it stll works.
![](https://i.imgur.com/h1sQVfH.png)

**Comment by invalidgamer** [comment]
I mean the publicly hosted one, Public NadekoBot https://nadekobot.readthedocs.io/en/latest/

Not the locally or user hosted one

**Comment by Gremagol** [comment]
The public bot works fine aswell.
![](https://i.imgur.com/ySsIB2R.png)
Are you sure you don't miss anything?

**Comment by Gremagol** [comment]
Then i guess you can close this issue, if it's solved now. 😄
