### ISSUE TITLE
Shard 0 unresponsive.

### ISSUE THREAD

**Issue by SrGatou** [Kwoth/NadekoBot#2036]
So, when I try to start Nadeko on my PC (Win7 64 Bits) from source it stuck. (Sorry for my English)
https://i.imgur.com/yMDqI2l.png

**Comment by SpielefreakJ** [comment]
#2030 see here ;)

**Comment by Macley-Kun** [comment]
Nadeko doesn't work on windows 7. Close issue and upgrade to windows 8 (or higher).
