### ISSUE TITLE
.aar command not working

### ISSUE THREAD

**Issue by RileyRoo** [Kwoth/NadekoBot#2037]
I've triple checked the syntax on the command and the spelling on the role name, but the role still isn't being assigned to new users upon joining. 
Is there a setting in Discord that could clash with this? 
Everything else I've tried is working really well.
Nadeko is running on a virtual Ubuntu 16.04 server, install was smooth, using pm2.

**Comment by shivaco** [comment]
What about role hierarchy?

**Comment by RileyRoo** [comment]
I put the role to be assigned at the bottom (just above @everyone), is that correct?

**Comment by shivaco** [comment]
No. Put the Nadeko role above the role you want to be auto-assigned.

**Comment by RileyRoo** [comment]
<img width="189" alt="screen shot 2018-01-26 at 19 07 25" src="https://user-images.githubusercontent.com/35848283/35456060-2e58974c-02cc-11e8-849b-ec2ff891aca0.png">
Tried this still not working. 
NB: I tried with the Nadeko role I created during setup for permissions, and the default NadekoBot role.

**Comment by RileyRoo** [comment]
I think I know the issue, I think NadekoBot needs to be the top role. I'll test.

**Comment by RileyRoo** [comment]
OK found out the bot needs Manage Roles as well as Admin, didn't realise it was a secondary role. User error!
