### ISSUE TITLE
Self Hosted Nadeko offline

### ISSUE THREAD

**Issue by Marko5689** [Kwoth/NadekoBot#2039]
After I have finished installing it and following your guide on how to hosted it, its not online after I have finished all the setup, how do I get it up?
![image](https://user-images.githubusercontent.com/35858396/35468149-56b75570-0353-11e8-92d7-c7c6ae80c0dc.png)

**Comment by shikhir-arora** [comment]
This isn't enough information to diagnose anything.
Let's start with what OS are you running? Where in the guide did you stop/follow?
If you have console screenshots? Did you configure the JSON file with your token? 
Did you read the startup guide if you are on Linux or macOS? 

Please provide as much info so we can help.. 🙂

**Comment by Marko5689** [comment]
Alright, First the OS is Windows 10, and the guide I follow the Windows guide but apparently I cant run the NadekoUpdater that you put there so I download the latest one from GitHub, and I follow the guide to setup the credentials files, and put in my client id and the token for it.

**Comment by Kwoth** [comment]
You have to run it. When you do, show us the console output you're getting.

**Comment by Marko5689** [comment]
Run it with the program I open it with, eg visual studio or notepad++?

**Comment by Gremagol** [comment]
Are you sure you installed Redis?

**Comment by Marko5689** [comment]
Eh how do I do that?

**Comment by Gremagol** [comment]
https://github.com/MicrosoftArchive/redis/releases/download/win-3.2.100/Redis-x64-3.2.100.msi

**Comment by Gremagol** [comment]
you can use this one for now

**Comment by Macley-Kun** [comment]
@Marko5689 Did Gremagol fixed your issue or your still dealing with it?

**Comment by Marko5689** [comment]
Ah yes he did

**Comment by Macley-Kun** [comment]
How about you close this issue? @Marko5689 ?

**Comment by inkkey** [comment]
Nadeko is doing that on my server and on another server i need help
