### ISSUE TITLE
How to change some commands

### ISSUE THREAD

**Issue by forcenchan** [Kwoth/NadekoBot#2040]
I need to change some commands from nadekobot on my channel 
how can I do this in the source code?

**Comment by Macley-Kun** [comment]
Ask this question in the right place. In nadeko server we have nadekomodding. Close the issue here and ask there. The people in that channel are experts :-)

**Comment by forcenchan** [comment]
But I was intelligibly explained by the ban that there they do not help with cases concerning the source code

**Comment by forcenchan** [comment]
@Macley-Kun 
But I was intelligibly explained by the ban that there they do not help with cases concerning the source code

**Comment by shikhir-arora** [comment]
This is correct. We don’t support source changes. If you do make a source change you are free to use it or PR it if you feel it would be a good addition to the bot. You should have a general idea of how to edit source before going to the modding channel; that’s for discussion not really learning.

**Comment by forcenchan** [comment]
@shikhir-arora 

I just need to know which source code is responsible for the .pick command to change it to another one.

**Comment by Macley-Kun** [comment]
My sincerely apologies. I understood that the nadeko modding was more relevant to ask them here. 
If I do understand it correctly now, you can discuss the changes you wanna make in source.

Again my apologies, I don’t mod the code in the nadeko source sadly.

**Comment by forcenchan** [comment]
@shikhir-arora to simply change the command name

**Comment by shikhir-arora** [comment]
https://github.com/Kwoth/NadekoBot/blob/b4566b74862742708d0c850132d481cc2cddd286/src/NadekoBot/_strings/cmd/command_strings.json#L1073-L1079

Specifically edit the lines above - *1073 to 1079* - and **replace** with:

```json
"pick": {
    "Cmd": "whateveryouwanthere",
    "Desc": "Picks the currency planted in this channel. 60 seconds cooldown.",
    "Usage": [
      "{0}whateveryouwanthere"
    ]
  },
```

Save the file and restart the bot.

**Comment by Kaoticz** [comment]
You could've simply used `.alias` for that, but w/e 🤷
