### ISSUE TITLE
.gcmd issue with .cleverbot

### ISSUE THREAD

**Issue by Nhyv** [Kwoth/NadekoBot#2041]
If you use .gcmd to disable .cleverbot, it doesn't actually disable it.
https://puu.sh/zaNca.png

**Comment by Gremagol** [comment]
It only works with the server-side permissions `.sc .cleverbot disable`
If you want to enable it for yourself only try `.uc .cleverbot enable @yourname#1234`

**Comment by Nhyv** [comment]
Doesn't matter, it is a command which should be disabled globally, I was asked by Zergling to report it as a bug.

**Comment by Macley-Kun** [comment]
Kwoth can you label this as Bug?
