### ISSUE TITLE
.uinfo without @mention or ID

### ISSUE THREAD

**Issue by Nhyv** [Kwoth/NadekoBot#2042]
It is impossible to use .uinfo without a mention or an id, tried many times with different users with name#discrim

**Comment by shikhir-arora** [comment]
![screen shot 2018-01-27 at 11 26 35 am](https://user-images.githubusercontent.com/8797918/35473933-067efab6-0355-11e8-867f-8eeaf041a8b3.png)

I don't see the issue?

**Comment by Nhyv** [comment]
@shikhir-arora Maybe It was a bug in the first place but I was always able to use .uinfo on username#discrim which doesn't seem to work anymore.

**Comment by Kuromaru420** [comment]
@Nhyv 
![uinfo](https://user-images.githubusercontent.com/15279414/35476384-404bacd0-03af-11e8-9e48-74c8da85a478.png)
Seems to work on v2.13.8

**Comment by shikhir-arora** [comment]
Yeah I can confirm it works too.

**Comment by Nhyv** [comment]
I tested it on Public Nadeko in Nadekolog and a few people were with me and couldn't do it either, perhaps a Public Nadeko issue?

**Comment by Nhyv** [comment]
Apparently I found out it doesn't work for invisible people, after a few trials.

**Comment by Kwoth** [comment]
No mention commands work on invisible users. It's just how discord.net works.
