### ISSUE TITLE
.lsar command will not work

### ISSUE THREAD

**Issue by krpw1204** [Kwoth/NadekoBot#2044]
Typing .lsar on my Discord server will not work, however, .asar and .rsar do.

**Comment by shikhir-arora** [comment]
- Are you self-hosting or using Nadeko public bot?
- If you are self-hosting, can you post a photo of your console when you run these commands?
- Can the bot post embeds in the channel? (It should if `.asar/.rsar` work)

**Comment by krpw1204** [comment]
@shikhir-arora Public.
