### ISSUE TITLE
[Enhancement/Request] .prefix command enhanced

### ISSUE THREAD

**Issue by Alison-Sera** [Kwoth/NadekoBot#2045]
Would it be possible to expand the .prefix command to include more than just one word (or maybe even a word and a space, so the prefix and command aren't the same word)?

**Comment by Macley-Kun** [comment]
If you wanna suggest this feature into Nadeko. Drop this one in the featurehub of NadekoBot! If enough people vote on that idea Kwoth might work that into the bot!

Feature requests aren't really ment to be posted here, so you can close the issue if you've posted a request on here: http://feathub.com/Kwoth/NadekoBot

**Comment by Alison-Sera** [comment]
Thanks, sorry, I remember *way* back in the day everything for Nadekobot was done on here, did not know about feathub at all.
