### ISSUE TITLE
Replace images with images.json

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#2046]
It would contain links to the actual images hosted somewhere. This has 2 benefits:

1. Bot takes up less space
2. Any command which sends a raw image, like `.draw 1` or `.plant` will be much faster, as there is no image upload involved - it will only put a link in embed "imageurl" property

**Comment by zergling-man** [comment]
Drawbacks: Image customisation requires a webhost.
Granted, imgur is free. People won't learn how to use it though, but then, people don't learn how to edit images currently either.

**Comment by hemipatu** [comment]
Will this change also be revised to include the remaining files within the images folder at anypoint Kwoth?

> Cards/Rip/Slots

**Comment by Kwoth** [comment]
Yes
