### ISSUE TITLE
Database: Clubs.Discrim every club has the same discriminator?

### ISSUE THREAD

**Issue by ExodusTime** [Kwoth/NadekoBot#2047]
Database: Clubs.Discrim every club has the same discriminator?

Not totally sure if that's normal but i don't guess it is at all, when joining a club you need to specify you're applying for "Whatever Club#1" and everyone is the same "SomeOther#1" "Another#1"
Otherwise, applying with "Whatever Club" or "SomeOther" doesn't work, gives the error **That club doesn't exist.**

🤔 

![](https://i.gyazo.com/c870e61e3e68d58e92c7592f40aa1cb9.png)

**Comment by Kwoth** [comment]
Because someone else can create Whatever Club, and it will be Whatever Club#2
