### ISSUE TITLE
Blackjack error

### ISSUE THREAD

**Issue by 7H28J** [Kwoth/NadekoBot#2048]
Getting an error on blackjack and a huge delay when the command is used, tried fixing it myself but no luck.

here is the error log.
https://pastebin.com/tfK2kJen

edit: forgot to mention this is self-hosted.

**Comment by Macley-Kun** [comment]
Can you re-create the issue still? Maybe you can tell wich commands you use and with how many people?

Wanna re-create this myself so we can mark it as a bug :-)

**Comment by 7H28J** [comment]
Yep, everytime we use .bj and the amount we want to bet and then it just hangs for 10+ seconds before dealing the blackjack hand and when I checked the bot files and error log was generated.

I think it has something to do with (locker) in blackjack.cs

**Comment by Kwoth** [comment]
#2074
