### ISSUE TITLE
Self hosted, offline, program runs with no errors.

### ISSUE THREAD

**Issue by FishEye18** [Kwoth/NadekoBot#2049]
Windows 10, using Nadeko updater.
I have restarted my computer and the program several times, as well as an uninstall. I have tried running it from both the updater and the exec file itself. Screenshot:
![image](https://user-images.githubusercontent.com/36090581/35759800-38efabf6-0839-11e8-85f5-3f95462e6cdf.png)

**Comment by Kwoth** [comment]
Try running it as admin?

Disable your antivirus too?

**Comment by FishEye18** [comment]
I tried both of those to no avail.

**Comment by Macley-Kun** [comment]
Are all credentials correctly inserted? There must be something specific going wrong at your machine. (Otherwise we would've bin flooded with other people having the same issue)

**Comment by FishEye18** [comment]
I checked the credentials, even redid them, still stuck on the same result. Even kicked the bot and re-added it.
![image](https://user-images.githubusercontent.com/36090581/35791907-729f744c-0a07-11e8-8970-a90a707c09de.png)

**Comment by hemipatu** [comment]
Personally I'd check that you've provided the correct client ID and secret.

I would even go as far as to say, delete all your apps which you can find here; https://discordapp.com/developers/applications/me/ relating to Nadeko and generate a new one.

Then go ahead and invite this new bot to your Discord server.

**Comment by Macley-Kun** [comment]
@FishEye18 did Hemipatu's adviced helped you out?

**Comment by Macley-Kun** [comment]
Kwoth can you close the issue? Answer is provided 2 weeks ago and no sign of the Fisheye.

**Comment by Macley-Kun** [comment]
@Kwoth bin over a month. No update of the guy. Can you close this please?
