### ISSUE TITLE
Welcome embed error

### ISSUE THREAD

**Issue by 7H28J** [Kwoth/NadekoBot#2050]
Tried to use %user% and #(channel) in the embed builder and it didn't work, only thing that worked was %server%, not sure what the issue is here either.. 

![screenshot_2018-02-04-01-10-02](https://user-images.githubusercontent.com/17189030/35769145-9993c4b0-08d4-11e8-9186-5d3f8e3d0a19.png)

and the code..

![a7df01974a4590a7bf58403f7f126318](https://user-images.githubusercontent.com/17189030/35769156-d26cb120-08d4-11e8-8821-5fc2303a9976.png)

**Comment by Kwoth** [comment]
Discord issue. It happens only on (some?) mobile devices.

You can use %username% and #%chname% instead.
