### ISSUE TITLE
Race is broken

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#2051]
![1](https://midorina.ga/u/cbd694d9387a.png)
Happens everytime on everywhere. v2.14.1

**Comment by Midoriin** [comment]
It was happening on every server. However, after a restart, the issue does not occur anymore. It's pretty odd. I wish I checked the console, but I didn't at that time. This issue can be closed for now, I guess.

**Comment by Macley-Kun** [comment]
Still happening or? Maybe just a little hiccup?

**Comment by Midoriin** [comment]
Nah, not happening anymore. Not sure if I should close this issue or not.

**Comment by Macley-Kun** [comment]
You can close it, if it happens you can re-open it or just create another one.

**Comment by Midoriin** [comment]
You're right. o7

**Comment by Midoriin** [comment]
This still occurs randomly. I don't know how to reproduce it though. It randomly gets stuck in a server, and stays this way unless bot gets restarted.
![1](https://midorina.ga/u/47dca82c302a.png)
![2](https://midorina.ga/u/48a9df99509e.png)

**Comment by Macley-Kun** [comment]
Kwoth i think we can mark this a bug.

**Comment by Macley-Kun** [comment]
@Kwoth Can you mark the issue as a bug?

**Comment by Midoriin** [comment]
on v2.16.4, I am not able to join the race without specifying an amount.
![1](https://midorina.ga/u/709030f9c8cd.png)
![2](https://midorina.ga/u/ab767bb94f03.png)

**Comment by Midoriin** [comment]
They both don't seem to be happening anymore. Closing the issue.
