### ISSUE TITLE
Picarto notification (.pa - .picarto) doesn't work

### ISSUE THREAD

**Issue by Macley-Kun** [Kwoth/NadekoBot#2053]
I've bin using `.pa` for a while but i notice it's not working.
![image](https://user-images.githubusercontent.com/26381427/35778116-d9552e28-09b9-11e8-964e-7d8787e4c660.png)
The twitch command works perfect, don't have issues with that. But picarto seems to be not working. The picture above shows that i added this streamer and after two times him streaming, nothing is posted. The bot has full permission and does post the twitch streams in the same channel.

This also happens in other servers. I'm on the latest version using selfhosted on Linux.

Can someone else test this out for me?

**Comment by Macley-Kun** [comment]
Can we also mark this as bug...? 
The guy is even streaming now bot has all permissions possible. Just doesn't work.

**Comment by derpynirvash** [comment]
Just curious as we are having this issue to, was there a resolution for this?

**Comment by Kalimeme** [comment]
Yeah Having the Same issue here, Works fine with Twitch

**Comment by Kwoth** [comment]
Ok. Some of you guys have to DM me and be ready to turn your stream on/off. I checked quickly yesterday and there didn't seem to be any issue.

**Comment by Macley-Kun** [comment]
Think issue is fixed. Saw during testing that it worked. Gonna test it on the latest update, waiting for a streamer to go offline :^)

Expect to get the fix on Windows soon™!

Thank you Kwoth for fixing the issue so fast!
