### ISSUE TITLE
.fairplay

### ISSUE THREAD

**Issue by Devaliah** [Kwoth/NadekoBot#2054]
`.fairplay` sometimes glitches out, and resets the playlist from the beginning,  replaying all previous songs before any of the "fairplay" songs.

**Comment by Macley-Kun** [comment]
Hey the music issues actully go here:
https://github.com/Kwoth/NadekoBot/issues/1053
Could you re-ask it there and close his one?

**Comment by Kwoth** [comment]
duplicate of #1389
