### ISSUE TITLE
.send with embeds, does not have a confirmation.

### ISSUE THREAD

**Issue by Devaliah** [Kwoth/NadekoBot#2055]
`.send` does not give a confirmation that a message was sent if it contains an embed.

**Comment by Macley-Kun** [comment]
Assuming `.send` works. You also can do one of the following!

1. You can code this yourself. If you want you can send the changes as a pull to the project so everyone can use it aswell!
2. You go to the feathub of NadekoBot and upvote (or create if it doesn't excists) this idea.

You can close this issue, i'm pretty sure your asking for a feature and not submitting a bug/question.

**Comment by Macley-Kun** [comment]
👀 what's this?
A 3rd option. Someone got inspired by your idea and did the work for you/us :D 

👌

**Comment by shikhir-arora** [comment]
Hah, wasn't much of an idea, it's just a simple fix. Need to send the confirmation before the return statement for the embeds, that's all.
