### ISSUE TITLE
cannot remove currency from user that's left server

### ISSUE THREAD

**Issue by RapthorneLightweaver** [Kwoth/NadekoBot#2058]
A user who used to be a bot owner gave himself over 10 billion flowers, and has since left the server, however I am unable to (as a bot owner) use the !take command to remove the flowers, as his username is no longer recognised within the server.

This has caused issues with the leaderboard and having one person billions of flowers ahead of other legitimate server members

**Comment by shikhir-arora** [comment]
Do you have access to the computer or VPS/server where the bot is hosted?

**Comment by Kwoth** [comment]
Use his userid
