### ISSUE TITLE
%avatarurl% should be nammed %useravatar% and it doesn't work on thumbnail

### ISSUE THREAD

**Issue by Pierrounator** [Kwoth/NadekoBot#2059]
Hi (sorry for my english)

The new commit says the new placeholder is `%avatarurl%` but it should be nammed `%useravatar%` because the code is like that...

By the way, `%useravatar%` doesn't work in thumbnail. It generates the link well (if you use it in a field as text for example) , the link works it you put it directly in the thumbnail field but not the placeholder for some reasons...

**Comment by Macley-Kun** [comment]
An update was launched about placeholders.
https://nadekobot.readthedocs.io/en/latest/Placeholders/

Can you update and check if it works for ya?

**Comment by Pierrounator** [comment]
`%user.avatar%` seems not working on thumbnail. (Public Nadeko)
