### ISSUE TITLE
Hosting on Heroku

### ISSUE THREAD

**Issue by JGriffin34432** [Kwoth/NadekoBot#2064]
**Is it possible to self-host NadekoBot on Heroku?**

![heroku](https://user-images.githubusercontent.com/32964555/35927118-ed5c8c0a-0bf7-11e8-8d26-fb1f7f4b8247.JPG)

**Comment by shivaco** [comment]
Yes, [there is a 1.3b version of Nadeko](https://github.com/ScarletKuro/NadekoBot), which means:
1. Multiple prefixes.
2. Many new commands are not added.
3. If your server needs/has categories, the bot will not work.

**Comment by Macley-Kun** [comment]
@JGriffin34432 You can close this issue. It's solved.

**Comment by Kwoth** [comment]
It's not officially supported.
