### ISSUE TITLE
NadekoBot.db DiscordUser BUG?

### ISSUE THREAD

**Issue by hank0531** [Kwoth/NadekoBot#2068]
Excuse me
This is a BUG or normal
How to solve ??
![image](https://user-images.githubusercontent.com/24751265/35965640-80335b0e-0cf6-11e8-87a8-e051ce3c46c8.png)

**Comment by shivaco** [comment]
![image](https://user-images.githubusercontent.com/22858781/35965881-6725ce68-0ce6-11e8-91f7-e046c6bccb44.png)
:thinking:

**Comment by Macley-Kun** [comment]
User probably never used a command on the nadekobot. That's why it's labeld Unknown probably.

Nothing we/you can do about it.

**Comment by hank0531** [comment]
Thank

**Comment by Macley-Kun** [comment]
You can hit close :-)
