### ISSUE TITLE
.sand problem

### ISSUE THREAD

**Issue by hank0531** [Kwoth/NadekoBot#2070]
Excuse me,
I want to use **_.send_** send a message will have a speaker and speaker the front of things
Is there any way to simply display the text? (Do not show other things, only the text is good)
(The previous version did not have anything in front of the speaker and speaker)
![image](https://user-images.githubusercontent.com/24751265/36004941-316e2114-0d70-11e8-85d5-01f777856a86.png)

**Comment by Kwoth** [comment]
update your bot. if you're on windows - wait.
