### ISSUE TITLE
lsar doesn't show all roles

### ISSUE THREAD

**Issue by danielospinap** [Kwoth/NadekoBot#2071]
![image](https://user-images.githubusercontent.com/17339872/36009616-ec4b51ce-0d1a-11e8-9979-cf75687788cc.png)

**Comment by tukimoop** [comment]
`.lsar` is now properly paginated. Use `.lsar [#]` to view the rest.

**Comment by Kwoth** [comment]
already fixed, update. About to be released on windows too.
