### ISSUE TITLE
Nadeko site in block list

### ISSUE THREAD

**Issue by RedWolf8** [Kwoth/NadekoBot#2072]
I cant connect from my provider to nadeko srvices such as Nadeko Updater or https://www.nadekobot.me. Problem occured since December or smth like that.
Any solutions?

Error msgs:
		+ Downloading https://dl.nadekobot.me/NadekoUpdater.application not executed.
		+ Can't establish connection with server
		+ Attempt to setup connection was unsuccessful, because from another computer within the required time is not received the desired response, or was lost already established connection due to an incorrect response of already connected computer 104.27.148.240:443

**Comment by Macley-Kun** [comment]
You could try using a vpn or try downloading from another place. Optionnally I can try to download it for you and send trough mega. 

But I’m having a buzzy day so might not be able to help you out today. 

Met vriendelijke groet,

**Comment by RedWolf8** [comment]
@Macley-Kun i've guess mega is bettet ^^''

**Comment by Macley-Kun** [comment]
https://mega.nz/#!OBATDATQ!z52GbDkp46JqrZ5RT_T9xjiyjO_C_lO7tZjGA2lDSEo
here ya go

**Comment by RedWolf8** [comment]
@Macley-Kun wow! idk wut happened (maybe server changed today or my operator putted block down) but i defenetly downloaded application from yr application manifest (guess it's have no changes from original). Anyway, ty :3
