### ISSUE TITLE
Latest linux update broke Blackjack

### ISSUE THREAD

**Issue by evacfk** [Kwoth/NadekoBot#2074]
`Feb 09 03:44:22 evacbot bash[21662]: 0 03:44:22 Blackjack | Waiting for doan#0923's move
Feb 09 03:45:17 evacbot bash[21662]: -1 03:45:17 ShardsCoordinator | StackExchange.Redis.RedisTimeoutException: Timeout performing LRANGE Mjc3Nzc4OD_shardstats, inst: 1, queue: 1, qu: 0, qs: 1, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientNa
Feb 09 03:45:17 evacbot bash[21662]:    at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange
Feb 09 03:45:17 evacbot bash[21662]:    at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase
Feb 09 03:45:17 evacbot bash[21662]:    at StackExchange.Redis.RedisDatabase.ListRange(RedisKey key, Int64 start, Int64 stop, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:lin
Feb 09 03:45:17 evacbot bash[21662]:    at NadekoBot.Core.Services.ShardsCoordinator.<>c__DisplayClass15_0.<<RunAsync>b__1>d.MoveNext()
`

Here's what it looks like in Discord http://evac.gg/i/u9ub1.png

**Comment by Kwoth** [comment]
Restart your server and try again.

**Comment by drake0727** [comment]
having same issue, on my server, if i use the .hit command, exception is thrown.  

Process is terminating due to StackOverflowException.

Shard restarts after a few secionds.

**Comment by evacfk** [comment]
Same issue after restarting VPS. .stand crashes the blackjack session.

**Comment by Kwoth** [comment]
Update. Blackjack has some serious issues, it's disabled in the latest update.

**Comment by Midoriin** [comment]
@Kwoth This is fixed, I assume?

**Comment by Kwoth** [comment]
Blackjack is enabled again.
