### ISSUE TITLE
Global custom reactions are not enabled by the custom reactions module.

### ISSUE THREAD

**Issue by Shadowlight213** [Kwoth/NadekoBot#2078]
If you have all server modules disabled, then enable the customreactions module for a specific channel, global reactions will still be blocked.

Steps to reproduce:
Setup your permissions like this:
`3. cm customreactions enable #testchannel`
`2. asm disable`
`1. asm enable`

add a global reaction
try to use that reaction in #testchannel.

Result: if verbose is on, NadekoBot will say that `2. asm disable` is preventing the command.

Workaround: enable all modules on the channel then manually disable all the other modules.
aum and arm also allow the global reactions to be used.

**Comment by Gremagol** [comment]
Try using `.cm actualcustomreactions enable`
This one is like a hidden Module for reactions.

**Comment by Kwoth** [comment]
^
