### ISSUE TITLE
Enhancement Request: "What is my movie" command

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#2079]
Being able to find movies with any kind of descriptions and our own words is pretty cool. I'd like to be able to use this service through Nadeko.

[https://www.whatismymovie.com/](https://www.whatismymovie.com/)
[https://www.whatismymovie.com/apikey/](https://www.whatismymovie.com/apikey/)
[https://www.whatismymovie.com/apiguide/](https://www.whatismymovie.com/apiguide/)

**Comment by Macley-Kun** [comment]
Suggestions and Feature Requests
http://feathub.com/Kwoth/NadekoBot

**Comment by Midoriin** [comment]
Well, I saw a few enhancement requests here in this repository's issues, so I thought it'd be fine to post to here.

**Comment by Macley-Kun** [comment]
Well it's ok but, normally people have to suggest it there. I mean, idk it's kinda what kwoth uses for the features and suggestions...

But some c# developers can find the issue here and decide to make it for themselfs/public. So um, we'll see ig?
