### ISSUE TITLE
rock paper scissors problem

### ISSUE THREAD

**Issue by AnkokuShizora** [Kwoth/NadekoBot#2082]
![image](https://user-images.githubusercontent.com/32851707/36097667-9407ff3e-1004-11e8-9c22-20f2f2243bbc.png)
![image](https://user-images.githubusercontent.com/32851707/36097673-9996a39c-1004-11e8-8cfa-271ec740bd99.png)

Says i win but the embed color is red and says i won 0. When the bot wins the embed color is green and says how much it won. Either way there is no difference in my balance whatsoever.

**Comment by Kwoth** [comment]
It doesn't actually give/take money atm at all. It's a known issue, will be fixed soon.
