### ISSUE TITLE
Anime Photo

### ISSUE THREAD

**Issue by DemonRem** [Kwoth/NadekoBot#2084]
how can i added to my discord install 20 sec instant hentai photo i want anime photo for example

blade & soul
bleach .. such on

**Comment by Midoriin** [comment]
`.autohentai 20 blade_and_soul|bleach|naruto` you can add tags like this. Please ask in NadekoBot Support server next time -> discord.gg/NadekoBot

**Comment by Kwoth** [comment]
but that's nsfw :P You can't have normal pictures on autoloop.
