### ISSUE TITLE
BUG: .hgit command not working

### ISSUE THREAD

**Issue by JGriffin34432** [Kwoth/NadekoBot#2090]
![image](https://user-images.githubusercontent.com/32964555/36168180-2e31715a-10c6-11e8-98fe-992708195110.png)

**Comment by Macley-Kun** [comment]
Ah yes this is probably because Kwoth moved the nadeko command list to the website.

Therefore the file isn't present anymore in people's folder.

Just wait until kwoth marks this as a bug and fixes it.

**Comment by Kwoth** [comment]
you aren't supposed to be running hgit anyway unless you know what you want.
