### ISSUE TITLE
.send command

### ISSUE THREAD

**Issue by hellosiema** [Kwoth/NadekoBot#2092]
There is username and emoji in front of send command and it kinda ruined it for me and members of my server, is there any way to remove it or can you add it in future updates? Much love by the way, bot is great!

**Comment by shivaco** [comment]
What is your OS?

**Comment by hellosiema** [comment]
Win10

**Comment by Macley-Kun** [comment]
Can't remove that i think? Only on linux you can edit the source files to your liking.

**Comment by hellosiema** [comment]
Well that's understandable, however previously It was completely fine and I don't understand this change at all.

**Comment by Devaliah** [comment]
I believe it was supposed to be like an "Announcement" kinda thing. But I also disagree with it. It leaves less wiggle room to be creative with it. I mean before you could manually add the user tag and an emoji if you wanted to announce something. it's not useful for other uses tho.

**Comment by samphunter** [comment]
I agree. I was using .send as startup command to announce, that the bot was activated. Now it looks weird.

**Comment by Devaliah** [comment]
This is something i personally use. Posted by Sobaco in the Nadeko server.

Info on how to remove the username and the emoji from `.send` command message:
Directory - `NadekoBot/NadekoBot.Core/Modules/Administration`
File - `SelfCommands.cs`
Line - `473 (await ch.SendMessageAsync($"**{Context.User}** 📣 " + rep.Replace(msg)?.SanitizeMentions());`)
Text to remove `- $**{Context.User}** 📣 " +` (So it would look like `await ch.SendMessageAsync(rep.Replace(msg)?.SanitizeMentions());`)

That being said, any time nadeko updates you would need to re-add this fix. I wish it would just be removed entirely.
