### ISSUE TITLE
Not much of an issue, more of a question

### ISSUE THREAD

**Issue by 8BitAsian** [Kwoth/NadekoBot#2094]
Hello! I have been messing around with Nadekobot, and I am just wondering: what is this embedded field called? There are fields like CurrentQuestion and QuestionEmbed, not sure which it is. Thanks!

![capture](https://user-images.githubusercontent.com/26202077/36217164-98753d04-1165-11e8-9059-8f29582087e1.PNG)

**Comment by Macley-Kun** [comment]
If it's more of a question. Why not ask it in #help in the Nadekolog server?

**Comment by 8BitAsian** [comment]
@Macley-Kun Hi there! I have looked all over the net for a Nadeko Discord Invite, all of them seem to be expired. I would greatly appreciate it if you could send me one though.

**Comment by Macley-Kun** [comment]
https://discord.gg/nadekobot

**Comment by FurkanKambay** [comment]
@Macley-Kun apparently he's not allowed to

**Comment by Macley-Kun** [comment]
With allowed you mean. He didn't do: `.iam modder`?

**Comment by FurkanKambay** [comment]
@Macley-Kun So he mentioned he was making a bot, they replied and I quote: 

> we don't offer support for other bots or even making bots
