### ISSUE TITLE
.alias embedding bug

### ISSUE THREAD

**Issue by Devaliah** [Kwoth/NadekoBot#2097]
using the command `.alias` with embed command will sometimes miss pieces of the code. 

Ex: .send
`{
  "plainText": "outside text",
  "description": "Text Here",
  "author": {
    "name": "bot",
    "icon_url": "embedded-hyperlink"
  },
  "color": 10027247,
  "footer": {
    "text": "footer text"
  },
  "thumbnail": "image-link"
}
`
adding the embed to the .send will skip the "thumbnail" when posting. the rest posts fine. (including other pictures and the embeded text)

**Comment by FurkanKambay** [comment]
Reproduced
- `.alias .send .say`
- `.say { "plainText": "From .say", "description": "Text Here", "author": { "name": "bot", "icon_url": "embedded-hyperlink" }, "color": 10027247, "footer": { "text": "footer text" }, "thumbnail": "https://vignette.wikia.nocookie.net/day-r/images/2/2d/Discord-Logo-Color.png/revision/latest?cb=20170409224508" }`
![.say](https://i.imgur.com/NedIDnB.png)

- `.send { "plainText": "From .send", "description": "Text Here", "author": { "name": "bot", "icon_url": "embedded-hyperlink" }, "color": 10027247, "footer": { "text": "footer text" }, "thumbnail": "https://vignette.wikia.nocookie.net/day-r/images/2/2d/Discord-Logo-Color.png/revision/latest?cb=20170409224508" }`
![.send](https://i.imgur.com/dUA675s.png)

**Comment by Devaliah** [comment]
lol did you copy and paste my example? xD that was not a full code (I striped the URL links from it) using .alias with the full embed included posts as intended.

![image](https://user-images.githubusercontent.com/26513239/36288735-735a3cc6-1279-11e8-9272-d80da3cf3742.png)
 

However using just the server/channel IDs (I have preset alias's to quickly send messages to a channel/user) then manually pasting an embed after removes the thumbnail section when posting. and seems to add a screen shot of a command prompt where the footer image goes? O.o

![image](https://user-images.githubusercontent.com/26513239/36288813-e1e913a6-1279-11e8-9f2f-54e367f56aa4.png)


Both embeds use the exact same code, with direct links from imgur for all images. And yes, before its asked I made sure it is using direct links for all images.

![image](https://user-images.githubusercontent.com/26513239/36288927-6cc0ceba-127a-11e8-9029-32fa84261799.png)

**Comment by FurkanKambay** [comment]
> lol did you copy and paste my example?

Well, yeah, to reproduce it. And I assumed you were using `send` as an alias for the `say` command because you didn't say anything about what alias you were using.

Could you copy the link for that command-line-looking image?

**Comment by Devaliah** [comment]
the alias is `.send <name>` to fill out `.send SID|u:UID` to DM a specific user. sorry I should have been more clear. so the bug occurs when you use `.send <name>` then add the <embed>
It does not matter if it is a DM or channel being used. some parts of the embed break.

![image](https://user-images.githubusercontent.com/26513239/36340432-ed07cb44-1399-11e8-8d47-3619ce4e9450.png)

The embed code is 
`{
  "plainText": "alias .send test",
  "title": ".Send",
  "url": "https://discord.gg/xxxxx",
  "description": ".send test",
  "author": {
    "name": "Sutekina",
    "url": "https://discord.gg/xxxxx",
    "icon_url": "https://cdn.discordapp.com/attachments/333802677605761028/414043431791493121/82583d48822b75df0cadbfea956413f9.jpg"
  },
  "color": 53380,
  "footer": {
    "text": "footer test",
    "icon_url": "https://media.discordapp.net/attachments/413995694274248716/413995853003358208/wjREH0E.png"
  },
  "thumbnail": "https://cdn.discordapp.com/attachments/412934998149300225/413496848926507008/NB4jgJt.png",
  "image": "https://media.discordapp.net/attachments/413858120570503188/413918886195625994/tenor.gif"
}`

Also upon further looking, the "cmd prompt" image was an image not found notice. It seems like it is breaking the link when using an alias. as the link works completely fine in any other embedding command (`.say/.acr`) and only has an issue when used in `.alias` as described. (.say also does not seem to work with alias in that manor manor, as the "%target%" coding is missing, therefore is not recognizing as a command. I tried it out of curiosity and is unrelated but probably should be noted.)

![image](https://user-images.githubusercontent.com/26513239/36340500-4a8f7c02-139b-11e8-8b23-424dee7c5dc3.png)

**Comment by Devaliah** [comment]
The footer icon url is:
https://media.discordapp.net/attachments/413995694274248716/413995853003358208/wjREH0E.png

And replaced by:
https://images-ext-1.discordapp.net/external/eRGiDXmbLm2NgR96_Rai0KxIyAPPAqFgOV91KEPXcho/https/media.discordapp.net/attachments/413995694274248716/413995853003358208/wjreh0e.png

Adding to the url:
https://images-ext-1.discordapp.net/external/eRGiDXmbLm2NgR96_Rai0KxIyAPPAqFgOV91KEPXcho/

to any link you add at the bottom for the footer, breaking any links. 

The thumbnail image is simply gone >.> there is no data to get from it.

**Comment by Macley-Kun** [comment]
@Kwoth can you mark as bug? It's a minor one tho.

**Comment by Kwoth** [comment]
Ok it's because input transformer converts everything to lowercase :\\\\
