### ISSUE TITLE
Blackjack is broken, bot doesnt respond to .hit .stand or .double 

### ISSUE THREAD

**Issue by sirneversleep** [Kwoth/NadekoBot#2099]
![bjfail](https://user-images.githubusercontent.com/32783172/36243467-413eb380-11e7-11e8-99a9-e3eaa76a8a68.png)

**Comment by TwinDragon** [comment]
I can't reproduce it using latest github pull on a Debian 9 box. Blackjack is working fine for me.

**Comment by Kwoth** [comment]
Blackjack is fixed. Update your bot. If you're on latest version of windows, then it didn't make it in the last patch and will be fixed in the next one.
