### ISSUE TITLE
Leaderboard Bug - "Unknown#????"

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#2103]
When running `[p]lb`, it's hit or miss what names show up as "Unknown#????" This has been an strange occurrence for about a few days or so. Nothing in particular seems to trigger who becomes "Unknown#????" and when they go back to username#1234 or whatever.

Here's some examples:

![image](https://user-images.githubusercontent.com/8271327/36321768-969ac79a-1310-11e8-9629-cbb623c67671.png)

![image](https://user-images.githubusercontent.com/8271327/36321720-72929a94-1310-11e8-826d-4bb75eb31e5c.png)

If this was already reported in Discord, I haven't seen so for obvious reasons.

**Comment by Kwoth** [comment]
You possibly updated after a while and as the database changed, those users weren't in the database. They need to run `.xp` or `.$` command once in order to be registered in the database with their names/discrims.

**Comment by xnaas** [comment]
Unfortunately, that doesn't help. Every one (myself included) runs `.$`  all time yet fall into `Unknown#????` and then will randomly be `actualuser#1234` at complete random.

**Comment by Kwoth** [comment]
then run .xp

**Comment by xnaas** [comment]
Working for the moment, we'll see if people start falling into `Unknown?####` again. 😜

**Comment by xnaas** [comment]
Nope! Didn't fix it. Still completely randomly dropping people into `Unknown#????` and then bringing them back to normal. Even users who have ran `.xp` _and_ `.$`. 🤷‍♂️

**Comment by xnaas** [comment]
I can nuke the entirety of all of the currency-related tables, it's just a bit annoying.
