### ISSUE TITLE
Bug, Feature Request -- Manage saved playlists

### ISSUE THREAD

**Issue by Hursofid** [Kwoth/NadekoBot#2104]
Hello,

I would like to request a feature to be able to rename saved playlists (using command .save), would that be possible?

Also there's a one annoying thing: when you delete playlist, the numbers of saved playlists isn't organising properly, i.e. there's missing numbers...
While I've been adding playlists, I removed first one and then later 18th, and you can see on screenshot that these numbers are just missing, which lead our admin today to think that someone's removed 23th playlist, but it's simply was on next page

![screen shot 2018-02-16 at 19 21 27](https://user-images.githubusercontent.com/15228720/36322764-d0265edc-134e-11e8-955e-71f596abedc4.png)

Also I'm thinking that it would be helpful to display how many pages of playlists are there, now there's only current page number displayed.

Thank you.

**Comment by Macley-Kun** [comment]
NO

**Comment by Hursofid** [comment]
Anyway, me thinking that the issue with playlist numbers is a bug and I'd like to ask you to fix that, if possible.

**Comment by Hursofid** [comment]
Could you please reply?

**Comment by Macley-Kun** [comment]
Your asking for two things, a request and an issue.

If your refering to the issue, i recommand making a new issue only about the **issue**.

Make sure to provide screenshots of the problem your getting. And what the expected  result should've been.

Also say if you use selfhost and wich OS.
