### ISSUE TITLE
(question) does self-host nadeko change anything in computer registry?

### ISSUE THREAD

**Issue by Foxwells** [Kwoth/NadekoBot#2105]
pretty much what the title says. win10 x64 build. using latest nadeko update.

i ask this because my computer was constantly crashing due to some program having changed the registry which caused errors. im still trying to figure out what program it was.

**Comment by Kuromu** [comment]
NadekoBot does in fact modify the registry, namely so the machine knows that it is installed (and possibly *where* it's installed as well as what version?). But it doesn't modify much else. It's only useful to know this when uninstalling the bot normally fails. It's highly unlikely it's the cause for your crashes.
If you need to remove it just to be sure, it's located at `HKEY_LOCAL_MACHINE\SOFTWARE\NadekoBot`

**Comment by Foxwells** [comment]
hmm, all right. thank you!

**Comment by Kwoth** [comment]
To be more precise: The bot doesn't modify the registry, the installer does.

You can review the file yourself here: 

https://github.com/Kwoth/NadekoBot/blob/1.9/NadekoBot.iss
