### ISSUE TITLE
%user% on byemsg display the id instead of the name

### ISSUE THREAD

**Issue by etshy** [Kwoth/NadekoBot#2110]
As the title says

https://puu.sh/zq0jD/c854ca4c13.png

Can't you use the name without ping the user ?

**Comment by Kwoth** [comment]
That's how discord embeds work. User `%user.name%`  or `%user.full%` if you want to put them in embeds.

**Comment by etshy** [comment]
Oh, maybe update the doc so.
ppl who don't know the discord library can't know what to put.
