### ISSUE TITLE
.send not working for servers other than own

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#2111]
I had this issue long time ago, someone else had it today. `.send` sometimes works, sometimes doesn't. Not a per-try type thing, more like it works 100% on some days and not at all on others. 

Bot has perms to send messages and embed, sender is bot owner, command registered in console.

When sending to current server, it works.

**Comment by shikhir-arora** [comment]
Hmm, do you notice a pattern after restating or something along those lines? If that's true it could be some guild cache issue, but I doubt it would register successfully. Try giving admin for a minute when it happens to the bot as that will completely rule out any permission issues or channel permission issues.

**Comment by MaybeGoogle** [comment]
The ping command works, so it should have perms. I'll be sending randomly in case it happens again, though

**Comment by MaybeGoogle** [comment]
doesnt seem to be happening anymore... 🤔
