### ISSUE TITLE
Yet Another Die-Update-Restart Bug

### ISSUE THREAD

**Issue by ronelm2000** [Kwoth/NadekoBot#2113]
Tbh, idk how to fix this one. This is when you pushed a new update and I restarted the bot.

OS: Ubuntu LTS on a Private Server
Run Method: `.die` = Restart and Auto-Update
Using: pm2

```sh
0|Nadeko   |   Restore completed in 17.73 ms for /home/earth/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj.
0|Nadeko   |   Restore completed in 5.43 ms for /home/earth/NadekoBot/src/NadekoBot/NadekoBot.csproj.
0|Nadeko   |   Restore completed in 1.86 ms for /home/earth/NadekoBot/src/NadekoBot/NadekoBot.csproj.
0|Nadeko   |   Restore completed in 18.33 ms for /home/earth/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj.
0|Nadeko   |   Restore completed in 10.04 ms for /home/earth/NadekoBot/NadekoBot.Tests/NadekoBot.Tests.csproj.
0|Nadeko   | Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
0|Nadeko   | Copyright (C) Microsoft Corporation. All rights reserved.
0|Nadeko   | Services/Impl/BotConfigProvider.cs(197,91): error CS1738: Named argument specifications must appear after all fixed arguments have been specified [/home/earth/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]
0|Nadeko   | Build FAILED.
0|Nadeko   | Services/Impl/BotConfigProvider.cs(197,91): error CS1738: Named argument specifications must appear after all fixed arguments have been specified [/home/earth/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]
0|Nadeko   |     0 Warning(s)
0|Nadeko   |     1 Error(s)
0|Nadeko   | Time Elapsed 00:00:09.11
```

**Comment by shikhir-arora** [comment]
I need to look at this this option and I will hopefully later today. For now, just do the following:

`cd ~ && wget -N https://gist.githubusercontent.com/shikhir-arora/b7a34e2caf67a8e31ea5cd4f3e0f6421/raw/2a9f9c8e29612164d830de3ca5010e85fa54dea6/nadeko-update-pm2.sh && sudo bash nadeko-update-pm2.sh`
`

**Comment by ronelm2000** [comment]
```sh
Building NadekoBot
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Services/Impl/BotConfigProvider.cs(197,91): error CS1738: Named argument specifications must appear after all fixed arguments have been specified [/home/earth/NadekoInstall_Temp/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]

Build FAILED.

Services/Impl/BotConfigProvider.cs(197,91): error CS1738: Named argument specifications must appear after all fixed arguments have been specified [/home/earth/NadekoInstall_Temp/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]
    0 Warning(s)
    1 Error(s)
```

The error still persists. 🤔

**Comment by shikhir-arora** [comment]
Make sure you are in `/home/earth` when you run it.

**Comment by ronelm2000** [comment]
Well, `~` is set in `/home/earth` so running either of these will do the same thing, with the exact same results.

I'll wait and see if Kwoth has anything to say about this, since the build error is in the database. He might need to redo the migration script for `BotConfig`

**Comment by shikhir-arora** [comment]
Where is your NadekoBot actually installed though? Also, did you make any modifications to the bot at all?

**Comment by Kwoth** [comment]
what is this wall of text

@ronelm2000 just update again, i just fixed it

**Comment by ronelm2000** [comment]
Looking at the change in the commit, I say that this should be raised to rosyln somehow if that pre-change worked for Windows but not Linux.

**Comment by shikhir-arora** [comment]
I didn't notice this was just an hour ago. It makes sense why it didn't work with Linux now that I see it. No worries. I had assumed you had issues prior based on the title of this issue.

**Comment by ronelm2000** [comment]
The error was so bizzare I didn't know what to name it.
