### ISSUE TITLE
.br all isn't working?

### ISSUE THREAD

**Issue by ronelm2000** [Kwoth/NadekoBot#2114]
Self-Explanatory.

PS: `MinimumBetAmount` was set to 1.

![screenshot 2018-02-18 21 15 37](https://user-images.githubusercontent.com/12634987/36352302-c028699a-14f1-11e8-8f51-c23730a290fa.png)

**Comment by shikhir-arora** [comment]
It's allin :)

**Comment by ronelm2000** [comment]
Apparently, that doesn't work either. 🤷‍♂️

**Comment by shikhir-arora** [comment]
I just tried `.br allin` and it works fine. Running latest.

**Comment by ronelm2000** [comment]
It works on my end, just not on someone else. Plus, this weird thing happens.
(The guy had 10005 currency; I had 85 million)
![screenshot 2018-02-18 21 30 12](https://user-images.githubusercontent.com/12634987/36352384-1cac26e2-14f3-11e8-8751-40e861a7f998.png)

**Comment by shikhir-arora** [comment]
Nothing strange there. `allin` is a self statement - so you don't use it with formulas. `all` is there now to use in formulas.

**Comment by ronelm2000** [comment]
No that's still weird. 10005 divided by 1 000 000 should be 0.01 (which we all know shouldn't even be possible to be computed here). Even if I have somehow set 66 Multiplier to 2460%, that doesn't explain my winnings then.

**Comment by ronelm2000** [comment]
And then there's this.

Did Nadeko change how `.br` works (as in the payout is a certain percentage on fail?)
![screenshot 2018-02-18 21 38 38](https://user-images.githubusercontent.com/12634987/36352448-288ed3f0-14f4-11e8-984b-dd1ea9ca9bb3.png)

**Comment by shikhir-arora** [comment]
Yeah the numbers were changed - not sure if this was intentional. 

Also, `allin` is not working correctly with br. Losing it makes you lose half of your bet. 

```cs


                case "all":
                case "allin":
                    args.Result = Cur;
                    break;
                case "half":
                    args.Result = Cur / 2;
                    break;
                case "max":
                    args.Result = Max;
                    break;
                default:
                    break;
```

Will wait on Kwoth here.
