### ISSUE TITLE
[BUG or new terrible feature?] Betflip now taking rounded DOWN figures instead of simply rounded

### ISSUE THREAD

**Issue by theLAZYmd** [Kwoth/NadekoBot#2115]
Hi, before, my self-hosted bot used to round the sum bet times-ed by the multiplier. For instance, `.bf 2 h` used to return `4` if won.
Now it seems it rounds down.
[Exhibit A.](https://i.imgur.com/JRxYzBS.png)
[Exhibit B.](https://i.imgur.com/bP7JVjV.png)
[Exhibit C.](https://i.imgur.com/bP7JVjV.png)

This means that for any multiplier <2, `.bf 2 h` returns 3. I can't allow a betflip function on my server where betting 2 returns 3 when winning; the only alternative is to set the multiplier to 2, which is also stupid.
Therefore, betflip is broken in its current state. It's not clear if this is a bug or a new 'feature' but either way, it really must be fixed.

Nadeko for Windows, 2.16.3 problem still there on 2.16.5

**Comment by Kwoth** [comment]
I hope you understand that was the bug.

If the multiplier is 1.95, it doesn't make sense for the win to be 1.95-2.0, it either has to be 1.95 or lower. If you want your users to get 4 when betting 2, that means you want 2.0 multiplier.
