### ISSUE TITLE
Playing music from SoundCloud is broken

### ISSUE THREAD

**Issue by Hursofid** [Kwoth/NadekoBot#2117]
Hello,

today I've noticed 300+ zombie processes of youtube-dl and ffmpeg programs, and decided to restart bot.
After restart bot is not playing songs from soundcloud anymore:
• I've tried to load saved playlist before - checked URLs in browser - they are available to listen
• I've tried to load random song from my feed in soundcloud
none of these options haven't lead to success

Server runs Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-141-generic x86_64), Nadeko bot runs using pm2

https://pastebin.com/48DNRTvm

**Comment by Macley-Kun** [comment]
Can you strip down that log a bit?

You can past the code in hastebin.

Also, you see the message/log repeating itself. So it's maybe handier that you strip down that log to only the part that happens once/is relevant.

**Comment by Hursofid** [comment]
Lines from 135 to 153 is repeating because I've added saved playlist (see line 124) and after adding, songs are just skipping like they've finished playing

**Comment by florian-kaiser** [comment]
seems like the resolve website is down. Any news when it will be up again?

**Comment by Kwoth** [comment]
Should be all back now
