### ISSUE TITLE
SelfHost (Dedicated Server) StreamerOnline/Offline Errors

### ISSUE THREAD

**Issue by worldofmadness** [Kwoth/NadekoBot#2118]
Hey there,

Since the last update with eh new streamers online/offline announcements the offline part has stopped working and the console is filled with errors about it. the dedicated server internet is working fine so are the other bots and things on that server running 24/7 - [https://puu.sh/zr8w7/393b377972.png](url) all working

[https://hastebin.com/alihisupec.vbs](https://hastebin.com/alihisupec.vbs)

**Comment by Macley-Kun** [comment]
Before any other people come to help you, can you try to edit your message and use Hastebin?

You can past this gigantic log in there,.

Also if you take a look at it, you see it repeats itself. So try stripping down that log a bit.

**Comment by Kwoth** [comment]
I pushed a fix for this, talked to him in dms. it should work fine now.
