### ISSUE TITLE
reactionroles not working with roles that are  more than one word

### ISSUE THREAD

**Issue by RapthorneLightweaver** [Kwoth/NadekoBot#2121]
As title says, the .rero command seems to only work if you use a role name that is a single word only, is this intended?

**Comment by Kwoth** [comment]
Yeah. It's not possible sorry.

**Comment by FurkanKambay** [comment]
@Kwoth How about wrapping it with `"`s? Cmd does it. We can just say `argument.Trim('"')`

**Comment by Macley-Kun** [comment]
@FurkanKambay is it a possibility that you test out this solution you have in mind, and maybe pull it over to nadekobot?

**Comment by FurkanKambay** [comment]
@Macley-Kun just took a look at it. Discord allows characters like `"''` in the role name, so my suggestion won't work. But I think if we count every word before the :emoji: as a role name, that would work. I will try to do it when I find the time.

**Comment by Macley-Kun** [comment]
Thanks dude! 👍

**Comment by FurkanKambay** [comment]
@Macley-Kun #2142
