### ISSUE TITLE
`.osu topplay` command does not show the image properly

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#2125]
![1](https://midorina.ga/u/efb88ace8acf.png)

**Comment by FurkanKambay** [comment]
It because [this guy](https://lemmmy.pw/osusig/) doesn't work when you input that nickname.
And I even have a theory why that service doesn't work: the user doesn't have a profile picture.

Türk bayrağını görünce bir şaşırdım, türk müsün? 😄

**Comment by Kwoth** [comment]
Yea, no idea where you got that command from 😂
