### ISSUE TITLE
NadekoInstaller.bat not downloading

### ISSUE THREAD

**Issue by Schism989** [Kwoth/NadekoBot#2127]
Following the guide someone gave me here
https://discordbeats.readthedocs.io/en/latest/guides/Windows%20Guide/
When I get to the "save link as" part, NadekoInstaller.bat does not install. This is all I can say, as it is all that I know.
As an update, the FFMPEG link does not work for me either.

**Comment by FurkanKambay** [comment]
Apparently, the repo that has that file is gone. Kwoth is probably doing something.

**Comment by Schism989** [comment]
Thanks

**Comment by Kwoth** [comment]
that's a fork of nadeko. Not real nadeko.
