### ISSUE TITLE
Issue installing Redis on Windows.

### ISSUE THREAD

**Issue by Maxrocket** [Kwoth/NadekoBot#2128]
I'm trying to reinstall the Nadeko Bot with the new version and when I click to install Redis I receive an error:

---------------------------

---------------------------
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.

   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)

   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

   --- End of inner exception stack trace ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at NadekoUpdater.MainWindow.<InstallRedis>d__29.MoveNext()
---------------------------

---------------------------

After I receive a message: Redis download or install failed.

**Comment by Schism989** [comment]
Getting the same thing after I downloaded the real thing on GitHub

**Comment by Macley-Kun** [comment]
Try later, I assume it has to do with a certificate issue on their side. Give it a couple of days.

(I think the httpS certificate runned out its time, becoming invalid. Due to this a secure connection trough the https protocol can't be established. They have to renew their certificate so, just doing the waiting game for now. I'll check later on this :-))

Verstuurd vanaf mijn iPad

**Comment by Nitswah** [comment]
I'm getting it from both the updater and directly launching the bot.

**Comment by atmfog** [comment]
Want to bump this issue. Get this issue with both youtube-dl and Redis installation.

**Comment by Macley-Kun** [comment]
> Samdivaio

> Get latest redis 3.0.504 from `[here](https://github.com/MicrosoftArchive/redis/releases)`

You guys can use the above solution as a quick fix.

**Comment by samdivaio** [comment]
Get the [zip](https://cdn.discordapp.com/attachments/287982972664020994/416782797420888074/NadekoInstaller.zip) extract and run. Use Option 6 to download and install (don't change the redis default installation dir) and option 7 to start and keep it in background.

**Comment by atmfog** [comment]
The Quick fix worked perfect, thank you Macley-Kun/Sa,divaio. I am attaching a screen shot of the Youtube-dl error that comes up in hope it helps fix the second issue.
![updater and youtube-dl](https://user-images.githubusercontent.com/5356787/36634888-7bbc0f78-1960-11e8-8485-807560543c51.png)

**Comment by Kwoth** [comment]
Fixed. Restart your updater and press Install redis again.
