### ISSUE TITLE
bot will not boot up

### ISSUE THREAD

**Issue by tyler40550** [Kwoth/NadekoBot#2129]
so I'm sourcing and this never happened until I updated the bot because I had not updated in a while.
![screenshot 50](https://user-images.githubusercontent.com/26098123/36573624-d7595162-180f-11e8-8d81-2e85c48db3c9.png)

**Comment by FurkanKambay** [comment]
Some app is using NadekoBot.Core.dll. Restart the computer or find that app (another instance of the server?)

**Comment by tyler40550** [comment]
already did that. was told to post here from the discord

**Comment by Kwoth** [comment]
Yea. That's the issue. Maybe your antivirus then? Or you're running it as a service maybe. In either case, something is using your bot's files.

**Comment by tyler40550** [comment]
I just did a tasklist on the directory of what its saying is being used and showed nothing
![tasklist](https://user-images.githubusercontent.com/26098123/36574863-acc28936-1815-11e8-9230-f8c58c4a3daf.PNG)

**Comment by tyler40550** [comment]
reopen plz

**Comment by tyler40550** [comment]
even disabled antivirus and still didn't work

**Comment by FurkanKambay** [comment]
Try this: duplicate the root folder with a different name, then start the new one.

**Comment by tyler40550** [comment]
root folder as in the folder i put everything in or?

**Comment by tyler40550** [comment]
didnt work

**Comment by FurkanKambay** [comment]
You mean the same thing happened with the new one? It's being used by another process?

**Comment by tyler40550** [comment]
Yes i even installed a fresh ftom github and moved the database and credentials over and still happes

**Comment by tyler40550** [comment]
@kwoth

**Comment by Macley-Kun** [comment]
You can try re-installing windows tottaly. But instead of putting the db back. Just add the token only (get a new one) and just start the bot. Should just work.

You can always put the db back later, but for now i'm curious how it would work with your hardware and all.
