### ISSUE TITLE
Nadeko refuses to update and run

### ISSUE THREAD

**Issue by darsparx** [Kwoth/NadekoBot#2130]
I had nadeko working pretty fine minus a few hiccups with using the music feature until I went to install my ssd as a means to speed up the old desktop I'm running her on, and reinstall windows in the process. Now it worked to install once then wouldn't update, and music was completely messed up. Now she's installed, but won't update, and apparently has no version. 

![image](https://user-images.githubusercontent.com/16845458/36575769-b060af14-181a-11e8-9399-ab18e597cbee.png)

She's been uninstalled, and the regedits done but still nothing. Now I just get this, though it does recognize redis, fmpeg, and yt-download is installed but that's as far as it gets. Before it was at least displaying a version at the very least but now she's just being stubborn.

**Comment by Macley-Kun** [comment]
Could you try uninstalling her, and double check if all folders and files are deleted aswell? Seems something went wrong during updating.

**Comment by Kwoth** [comment]
So, updater won't work for another 12-24h because the current version's octokit package is outdated.

**Comment by darsparx** [comment]
That does explain it. Though why yt wasn't working in teh first place that made me try and do this to fix it is beyond me. I had uninstalled and deleted everything but yeah....

**Comment by DarkNecromancer9878** [comment]
How do I uninstall all the files?

**Comment by Macley-Kun** [comment]
@DarkNecromancer9878 go to `control panel`, then to `programs and features`, then `remove programs` and then delete both the nadekobot and the updater programs.

Or just google: `how do i uninstall programs on windows`

**Comment by Kwoth** [comment]
Fixed. Restart your updater.
