### ISSUE TITLE
"Redis downlod or install failed."

### ISSUE THREAD

**Issue by Purpleness2** [Kwoth/NadekoBot#2133]
I don't know why but every time I try and download Redis I get this error message
![aa](https://user-images.githubusercontent.com/36789714/36629723-74fdeacc-195a-11e8-9dc4-2465753a0351.PNG)
![eks](https://user-images.githubusercontent.com/36789714/36629756-02b255ec-195b-11e8-82c9-29dee923efde.PNG)

I have tried uninstalling and reinstalling NadekoBot completley, with the installer. But it doesnt seem to work still. Only install that works was FFMPEG. I also searched through most of the posted issues but I didn't find any that worked. Example "Crash upon start up" but the only answer is install redis but I can't install redis.
![eksudeeu](https://user-images.githubusercontent.com/36789714/36629746-e04b6052-195a-11e8-8c20-15fd0366a9ee.PNG)

any help is apriciated.

**Comment by samdivaio** [comment]
Get latest redis `3.0.504` from [here](https://github.com/MicrosoftArchive/redis/releases).

**Comment by Macley-Kun** [comment]
@Purpleness2 you can close the issue. Were going to solve it in this issue: #2128 .

**Comment by Lynxiris** [comment]
i have the same problem for youtube dl

**Comment by samdivaio** [comment]
Download the batch in this [zip](https://cdn.discordapp.com/attachments/287982972664020994/416782797420888074/NadekoInstaller.zip) and use option 8 and then 9 for youtube-dl.

**Comment by Kwoth** [comment]
I've pushed a fix. Restart your updater (Your updater will update) and then install redis. It will work now.
