### ISSUE TITLE
Bot failing to delete words on server filter word list even with manage messages permission and after having bot role placed at top of hierarchy

### ISSUE THREAD

**Issue by AnnoyedCartoonist** [Kwoth/NadekoBot#2134]
Nadeko used to delete words on the fw list almost immediately. I haven't changed anything, but suddenly, it doesn't work anymore. I made sure the nadeko role had the manage messages permission, and then I tried placing it above all other roles. No luck. I have to assume this is a bug that's recently been introduced, or otherwise, something must have changed in the coding of discord.

**Comment by shikhir-arora** [comment]
Works just fine. Make sure you do `.sfw` to enable the filtering on the server after adding the words with `.fw` (or `.cfw` if you just want it to be on a channel basis).

**Comment by AnnoyedCartoonist** [comment]
The bot still won't do it in my server. Is there some other known issue that could be at work? Because I made sure and have been trying the past couple days and it's still not working.
