### ISSUE TITLE
Self-hosting v2.16.7 Music player not playing at the correct speed.

### ISSUE THREAD

**Issue by Ven0mstrike42** [Kwoth/NadekoBot#2135]
After updating to version 2.16.7, the music player no longer plays youtube audio at full speed. I have tested it using different youtube links including:
https://youtube.com/watch?v=4zLfCnGVeL4
https://youtube.com/watch?v=u9Dg-g7t2l4

Note: my upload speed is not an issue (50mb/s)

**Comment by Macley-Kun** [comment]
Little confused why this isn't closed and asked in #1053 . But oh well.

Can you say wich OS your using? 
Have you tried maybe re-installing? Maybe the whole OS?
Checked how cpu/memory performance is doing when playing music?

Any logs that might indicate something strange when you play other songs that also happen to be slower played?
