### ISSUE TITLE
[Suggested Feature] Having the .log track kicked users.

### ISSUE THREAD

**Issue by DarkNecromancer9878** [Kwoth/NadekoBot#2136]
![capture](https://user-images.githubusercontent.com/5510523/36637276-e4e1f92e-1995-11e8-8181-7810b7c3ff6a.PNG)

So, at present, the .logserver command does not track when a user is kicked, either through .kick or by kicking the user through Discord itself. It tracks bans, and when a user leaves by themselves, but not being kicked?

I just request that these be added to what Nadeko can track.

**Comment by Kwoth** [comment]
http://feathub.com/Kwoth/NadekoBot
