### ISSUE TITLE
Upvoting Bot

### ISSUE THREAD

**Issue by syngtu** [Kwoth/NadekoBot#2137]
I don't get the flowers when I upvote. I am signed in on the right account.

**Comment by shikhir-arora** [comment]
Yeah there's something not working with it for a bit, can confirm. Kwoth will take a look shortly I'm sure.

**Comment by AmitGamingKing** [comment]
Same problem with me too worked perfectly for two days and then boom no flowers at all! Contacted Kwoth but he said I can't do anything 😕

**Comment by Kwoth** [comment]
Forgot to close this. it has been fixed the following day.
