### ISSUE TITLE
.sfw failing to enable word filtering

### ISSUE THREAD

**Issue by AnnoyedCartoonist** [Kwoth/NadekoBot#2138]
As seen here:
https://i.imgur.com/q0r2Jbp.png
The permissions are all in order and no roles are ignored, so I am not sure what's causing this issue, but it is very much happening.

**Comment by tukimoop** [comment]
Filtered words will not work on people with server owner or people with admin roles.

**Comment by AnnoyedCartoonist** [comment]
Ah, thank you. I was thoroughly confused for a while there.
