### ISSUE TITLE
my voice+text doesn't work anymore

### ISSUE THREAD

**Issue by IrbeinTepes** [Kwoth/NadekoBot#2144]
is it intended? as in the command list seems to doesn't have a voice+text command to restart the funcionality

**Comment by shivaco** [comment]
It has been removed from the bot recently.

**Comment by IrbeinTepes** [comment]
it's so sad, I was using nadeko to solve that problem, now I'm struggling to get it to work with a replacement that won't be as good as it used to be

**Comment by Macley-Kun** [comment]
Why not stick with the older bot?
Or if you know what your doing. You can add the code back in for yourself.

Also issue can be closed. :-)

**Comment by shivaco** [comment]
You could basically use `.vcrole` by creating a separate role, making only the role to be able to have access to the channel and joining the voice channel, using `.vcrole <YourRoleHere>`. :man_shrugging:
