### ISSUE TITLE
~Filterwords

### ISSUE THREAD

**Issue by LillySatou** [Kwoth/NadekoBot#2145]
Hello,

Just found out that filtering multiply words with spaces in them for a name as an example "Tash Sultana" the bot won't filter the words even if they are filtered as separated words. Might need to add 'space' as a character to the filtered words list

**Comment by Pierrounator** [comment]
Did you try `.fw "yours words"` with this **" "**?

**Comment by LillySatou** [comment]
Oh I didn't realize that using " " was a thing. Thanks that fixed my problem

**Comment by Macley-Kun** [comment]
@LillySatou please close the issue when the issue is solved. <3

**Comment by LillySatou** [comment]
Oh sorry forgot too
