### ISSUE TITLE
[FR] A way to control all modules/commands at once

### ISSUE THREAD

**Issue by Saturn-Enceladus** [Kwoth/NadekoBot#2146]
I kinda wish there was a way to disable/enable every module for a role/channel/user/server at once, just for efficiency. Something like `.um * enable @SomeUser#0001`

**Comment by Macley-Kun** [comment]
Hey dude that's a great feature you have posted here!
Sadly enough, it's not allowed to ask them here.

Instead. Ask it here as we ask people to do so!: https://feathub.com/Kwoth/NadekoBot/
You can better search in the suggestions there and upvote it. If it's not there you can make a new suggestion and make sure to get lots of people to upvote it! Then kwoth might implement it~!

You can close the issue emmedialty :-)

**Comment by Saturn-Enceladus** [comment]
ok, thanks

**Comment by Kwoth** [comment]
Isn't that what `.aum` does?
