### ISSUE TITLE
What does Bot Owner means?

### ISSUE THREAD

**Issue by rafapousin** [Kwoth/NadekoBot#2147]
That means that some comands are just able if u pay?

**Comment by Kyousei** [comment]
A bot owner is someone who is hosting Nadeko on their machine/VPS.
That being said, they have access to all the commands and all the files of Nadeko bot, and can customize it however they will.
Nadeko bot is completely **FREE** to download.
You can download Nadeko from **https://download.nadekobot.me** and follow the guide for the Operating System you have at **https://nadekobot.readthedocs.io/en/latest/guides**

If this answered your question, close the issue.

**Comment by shikhir-arora** [comment]
No, it means you self-host the bot yourself and get access to many features, including Music. Of course you need to host it somewhere that is online 24/7 or the bot will go offline. Here's a link to the Windows Guide: https://nadekobot.readthedocs.io/en/latest/guides/Windows%20Guide/ and any commands labeled `Bot Owner Only` here: https://nadekobot.me/commands are for those who self-host the bot.
