### ISSUE TITLE
stream announcements preview not updating

### ISSUE THREAD

**Issue by worldofmadness** [Kwoth/NadekoBot#2151]
i have noticed that the steam announcements preview shots are not updating they are from very old streams they have done any ideas on this (twitch)
![discordptb_2018-03-05_20-03-40](https://user-images.githubusercontent.com/17691564/36998205-082e9480-20b4-11e8-86e6-61d2be79bb4f.png)

**Comment by Macley-Kun** [comment]
I'm afraid this is out of reach for Kwoth.
He uses an API that gives him the information he can use. If you would want this to refresh faster. Your better off asking the Picarto developers about it.

Up to you if you wanna close this.

**Comment by worldofmadness** [comment]
Picardo? I am using twitch its never updated

**Comment by Macley-Kun** [comment]
Woopsie! I ment twitch haha XD!
See, twitch provides the data for kwoth to use. So kwoth can’t increase the update time. Only twitch can.



Met vriendelijke groet,
