### ISSUE TITLE
lots of console spam with announcements  is there rate limiting involved here

### ISSUE THREAD

**Issue by worldofmadness** [Kwoth/NadekoBot#2152]
```
0 21:42:02 StreamNotificationService | An error occurred while sending the request.
0 21:42:02 StreamNotificationService | An error occurred while sending the request.
0 21:42:02 StreamNotificationService | An error occurred while sending the request.
0 21:42:02 StreamNotificationService | An error occurred while sending the request.
0 21:42:02 StreamNotificationService | An error occurred while sending the request.
0 21:42:02 StreamNotificationService | An error occurred while sending the request.
0 21:42:02 StreamNotificationService | An error occurred while sending the request.
0 21:42:02 StreamNotificationService | An error occurred while sending the request.
0 21:42:02 StreamNotificationService | An error occurred while sending the request.
0 21:48:06 StreamNotificationService | Retreived and published stream statuses i
```

is the system being rate limited since its now checked every 20 seconds? cause these dedicated servers have no connection issues

**Comment by Kwoth** [comment]
How many streams are you following? I don't have these issues with around 5 streams at least.

**Comment by worldofmadness** [comment]
15 in the team so far.

**Comment by shikhir-arora** [comment]
Yes it does check every 20 seconds, that's normal. That was changed here f27ac07e593a24bae8bb4249d0a2f620ee0a8175 -- but if you have too many stream notifications (15 is a fair bit) this error occurs.

**Comment by worldofmadness** [comment]
never used to error and i used the bot a very long time with that amount and more. and to be honest its not that big for a stream team announce system

**Comment by xnaas** [comment]
Personally, I get this spam every now and then with only 1 channel watched on Twitch... 🙃

**Comment by xnaas** [comment]
Over the past few days, the spam has gotten even worse and worse. It will also spam shit like this in chat: ![img](https://xnaas.info/img/ZclKx.png)

We only have two streams monitored on our server. ¯\\\_(ツ)_/¯

**Comment by Kwoth** [comment]
@xnaas are you sure you're on 2.16.11?

**Comment by xnaas** [comment]
I'm on 2.16.10, the latest I see on https://github.com/Kwoth/NadekoBot/releases even. 🤔 

![stats](https://xnaas.info/img/marxj.png)

**Comment by Kwoth** [comment]
I assume it's just twitch ratelimiting in effect. Probably an hourly limit that we hit, it spams until the timeout passes and then keeps working properly.

**Comment by xnaas** [comment]
Does Nadeko take advantage of the proper Twitch API (like Red, as an example)?

**Comment by xnaas** [comment]
As an example, when using Red, you actually have create an account and get an API key to use the Twitch stream monitoring functionality. I never noticed it having any issues with rate-limiting, but who knows.

**Comment by worldofmadness** [comment]
have noticed that there is a client ID with in the source so that would mean we are sharing the same Client ID instead of using out own? 

```https://api.twitch.tv/kraken/streams/{Uri.EscapeUriString(stream.Username.ToLowerInvariant())}?client_id=67w6z9i09xv2uoojdm9l0wsyph4hxo6```

**Comment by xnaas** [comment]
If so, would explain hitting rate limits constantly. 😛

**Comment by Kwoth** [comment]
Added TwitchClientId to credentials.json. Check JSON Explanation to see how to get the client id.

**Comment by xnaas** [comment]
Windows release in 400 years™. 😉
