### ISSUE TITLE
.masskill SQL Database messup

### ISSUE THREAD

**Issue by StarlightGalerie** [Kwoth/NadekoBot#2153]
![image](https://user-images.githubusercontent.com/33184750/37007473-714927cc-20ab-11e8-849d-0ae24bc73c29.png)
Whenever .masskill is run, this error occurs and, in some cases, causes the bot to completely crash. The bot on Discord shows up with the proper message but doesn't actually perform the command. Nadeko versions tested were 2.16.7 and 2.16.10. Both had the same results.

OS version is Windows 10 Pro version 1709, OS Build 16299.192

**Comment by Kwoth** [comment]
Will look into it today. thanks
