### ISSUE TITLE
Danbooru image links are incorrect.

### ISSUE THREAD

**Issue by turey** [Kwoth/NadekoBot#2154]
NadekoBot posts Danbooru image links in the form:
https://danbooru.donmai.ushttps//hijiribe.donmai.us/data/...
but those links should be in the form:
https://hijiribe.donmai.us/data/...

This seems to apply to all commands that draw images from Danbooru.

**Comment by Kwoth** [comment]
Works fine for me. What's your bot version and give me an example of a keyword.

**Comment by casKd-dev** [comment]
Having the same problem when using the .hentaibomb command.
Using official bot, works with any keyword.

Modules loaded:
>NSFW (only on a channel)
