### ISSUE TITLE
Nadeko offline

### ISSUE THREAD

**Issue by BladeMasterLegend** [Kwoth/NadekoBot#2156]
Hi, the bot is offline, is it due to maintenance? 

I'm sorry if this isn't right place to post, could't find way to contact the creator, never seen it go offline before and been using it for quite a while. By the way, it's awesome bot and works great, thank you very much.

**Comment by Kwoth** [comment]
Yes, server issue. I have contacted the host and they will have to manually restart the server, it might take an hour or two from now. Sorry for the inconvenience

**Comment by BladeMasterLegend** [comment]
That's great, thank you for the quick reply, appreciate it.

Thanks again for the awesome bot :)

**Comment by Kwoth** [comment]
Should be up within 15 minutes on the remaining 12 shards.
