### ISSUE TITLE
Search module

### ISSUE THREAD

**Issue by SmugCardboardBox** [Kwoth/NadekoBot#2157]
So, when self-hosting Nadeko, it seems a few search commands are broken, for example; .ani .mq and .lolban

I've looked high and low for an answer to this, but nothing turns up, I'm curious as to why the commands don't work, is there something in my credentials.json I need to edit? 

Nothing weird seems to happen in my console, either.

**Comment by Kwoth** [comment]
Working fine for me.

**Comment by Macley-Kun** [comment]
Strangely enough, for me the .ani and .mq don't work. Using the exact same string as in help. But .lolban works perfect.

I'm gonna try to login into mal (may anime list). Sometimes you need to login inorder to let it work again. But i'm not sure on that...

**Comment by Kwoth** [comment]
There was some issue and it was resolved.
