### ISSUE TITLE
Typing Test Apostrophe Problem

### ISSUE THREAD

**Issue by redstoneruin** [Kwoth/NadekoBot#2159]
In typing test prompts, Nadeko displays this kind of apostrophe -’- when normal apostrophes look like -'-. It's a small difference, but these are counted as errors, which is pretty frustrating. Nadeko is nicknamed appropriately in our Discord.
![capture](https://user-images.githubusercontent.com/5103211/37246014-4795b612-2456-11e8-980f-08ffbf05d78e.PNG)

**Comment by Kwoth** [comment]
Fixed in 2.12 (soon:tm:)
