### ISSUE TITLE
.log <event> toggling response bug

### ISSUE THREAD

**Issue by SlimShadyIAm** [Kwoth/NadekoBot#2160]
When using `.log UserJoined` for example, the bot will respond `@SlimShadyIAm Logging UserJoined event in this channel.` both when toggling on or off.

**Comment by florian-kaiser** [comment]
Could you post a picture? For me its saying "
dsafadн#5991 Logging UserJoined event in this channel" when toggling on and  "dsafadн#5991 Stopped logging UserJoined event." when toggling off

**Comment by Kwoth** [comment]
THis was an issue many versions ago. Make sure you're updated to the latest version (2.11.x)
