### ISSUE TITLE
ubuntu 16.04 / shard 0 error

### ISSUE THREAD

**Issue by queercavegaming** [Kwoth/NadekoBot#2164]
So this error started happening recently
I would restart my bot and ill get prompted 

`ShardsCoordinator | Shard 0 is scheduled for a restart because it's unresponsive
ShardsCoordinator | Auto-restarting shard 0`

This message will continue to prompt itself constantly with out ending.
Ive tried a fresh install, checked creds/db & checked if it still in a server and still nothing.

https://gyazo.com/973cb208d23385cad7f926491eba171c

**Comment by Kwoth** [comment]
How long does the startup take? If you're running it on a low low end box, maybe loading of services etc takes so long that the shards coordinator thinks it's down. Also you need to check whether your redis is up and running, and your hard drive space to see if redis has space to function.

**Comment by Macley-Kun** [comment]
@queercavegaming 

> How long does the startup take? If you're running it on a low low end box, maybe loading of services etc takes so long that the shards coordinator thinks it's down. Also you need to check whether your redis is up and running, and your hard drive space to see if redis has space to function.

You've tried this? It's bin 2 weeks withoud any updates from your side.
