### ISSUE TITLE
addcustreact request permission

### ISSUE THREAD

**Issue by wong8888** [Kwoth/NadekoBot#2166]
why use **.addcustreact** need Administration permission , not just need only Bot owner ?

i see effect just show embed message.

**Comment by Kwoth** [comment]
.acr requires admin if you're using it in a server to create a server custom reaction.
it only requires bot ownership if you're running it from dms.

**Comment by wong8888** [comment]
but still not solve why need so powerful permission for server custom reaction. is it have any special reason?

i see that message is only need embed message permission and say message permission is already can say it out.

**Comment by Jonz00r** [comment]
so you can't make a buncha spam stuff in a server you're not an admin on.

**Comment by wong8888** [comment]
is it possible set a role for this one (set server custom reaction) ?

that mean if you have this "role" , you can add or del server custom reaction ?
