### ISSUE TITLE
Trivia win amount + win requirements do not follow through

### ISSUE THREAD

**Issue by InquisitiveWombat** [Kwoth/NadekoBot#2167]
When using these commands on a self hosted bot:

.bce MinimumTriviaWinReq 5

.bce TriviaCurrencyReward 500

The values do not actually change despite saying the values have been changed. Win amount it still 100 and win requirements is 10.

EDIT: Sorry didn't understand that the win requirements was the minimum for parameters, I thought it was for default win requirements is starting a game without -w parameter. 

Also currency does look like it has been updated, was given a false report.

**Comment by MaybeGoogle** [comment]
does it get changed in the database?
