### ISSUE TITLE
Failed resolving error

### ISSUE THREAD

**Issue by tradana** [Kwoth/NadekoBot#217]
Failed resolving the link.Exception of type "VideoLibrary.Exception.BadQueryException" was thrown 
?
how to fix?

**Comment by Kwoth** [comment]
Either try a few more times, try different keyword/link. If it doesn't work it will be probably resolved in one of the next releases. It's a bug in a library I'm using, nothing I can do about it.

**Comment by tradana** [comment]
:(  all list not working queue

https://www.youtube.com/playlist?list=PLqQS9eGUjjjBjqu_hM6iEgDV3bPktXNqs
https://www.youtube.com/watch?v=ZLu5b4Arl7U
https://www.youtube.com/watch?v=QUBvVTNRp4Q&list=RDQUBvVTNRp4Q
https://www.youtube.com/watch?v=i7wveOu5hkQ
https://www.youtube.com/watch?v=6ttobrfMnyQ

**Comment by Kwoth** [comment]
we will track this issue in #189

**Comment by RMcD94** [comment]
https://www.youtube.com/watch?v=RIhYrcFmBBM

Same issue.

http://i.imgur.com/qlDRmjv.png
