### ISSUE TITLE
.load queues wrong songs

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#2170]
Doing `.load [playlist index]` loads the correct number of songs into the queue, but all of the songs are the same incorrect song. 

https://i.imgur.com/CpCWJLa.jpg
https://i.imgur.com/5l5kZtJ.jpg

edit: idk what _d does on the link but apparently it makes the image shitty. fixed

**Comment by Nitswah** [comment]
I'm having this issue as well, would love to know what's up with it.

**Comment by Kwoth** [comment]
True, something is terribly wrong with .load, I'll take a look

**Comment by Kwoth** [comment]
Will still need to test the fact that rikka doesn't load some playlists correctly even though they worked fine before.

**Comment by Kwoth** [comment]
nvm, working fine now O.o
