### ISSUE TITLE
.slowmode doesn't work

### ISSUE THREAD

**Issue by Leefee** [Kwoth/NadekoBot#2173]
Global Nadeko. Has Manage Messages permission.

1. Set .slowmode 3 5
2. Have a regular user spam 5 messages in quick succession.
3. Nothing happens.

**Comment by shivaco** [comment]
Stops working after spamming hardly. However, works fine for me.

**Comment by Kwoth** [comment]
Slowmode is getting rewritten atm anyway, but will only come in 2.12 which is still few days away, just wait a few days : )
