### ISSUE TITLE
Custom Trivia Questions in hosted Nadeko on CentOS 7

### ISSUE THREAD

**Issue by Durgon** [Kwoth/NadekoBot#2174]
trying to add some custom questions into the trivia_questions.json. After adding the questions and starting Nadeko normally, error received is "additional text was detected" and the bot becomes unresponsive. Attached is example of format I'm using. 
[example.txt](https://github.com/Kwoth/NadekoBot/files/1816913/example.txt)

**Comment by Kwoth** [comment]
you probably have an extra comma at the end, or you don't have the wrapping [ ]
