### ISSUE TITLE
NadekoBot.Core.Common.ShmartNumber instead of a number value

### ISSUE THREAD

**Issue by liminalitythree** [Kwoth/NadekoBot#2175]
In pretty much all command responses nadeko says 'NadekoBot.Core.Common.ShmartNumber' instead of a number amount. I noticed that picking doesn't do this though.

I'm using the latest docker image on debian 9. I re-created the bot following the instructions but this issue still happens.

![capture](https://user-images.githubusercontent.com/30793687/37549752-d61f1ee0-2948-11e8-888a-0f2a84eeb37b.PNG)

**Comment by Kwoth** [comment]
Means your bot is not updated. @shikhir-arora I think he owns the docker image so he needs to update it if it's not.

**Comment by shikhir-arora** [comment]
@Kwoth I don't own the Docker image xD

**Comment by Kwoth** [comment]
Oh my bad, @willysunny does

**Comment by shikhir-arora** [comment]
Well anyway, it's not hard to change if this is all:


```
FROM microsoft/dotnet:sdk
MAINTAINER Poag <poag@gany.net>

WORKDIR /opt/

#Install required software
RUN echo "deb http://www.deb-multimedia.org jessie main non-free" | tee /etc/apt/sources.list.d/debian-backports.list \
	&& apt-get update \
	&& apt-get install -y --force-yes deb-multimedia-keyring \
	&& apt-get update \
	&& apt-get install -y git libopus0 opus-tools libopus-dev libsodium-dev ffmpeg

#Download and install stable version of Nadeko
RUN curl -L https://github.com/Kwoth/NadekoBot-BashScript/raw/1.9/nadeko_installer_latest.sh | sh \
	&& curl -L https://github.com/Kwoth/NadekoBot-BashScript/raw/1.9/NadekoARN.sh > nadeko.sh \
	&& chmod 755 nadeko.sh

VOLUME ["/opt"]

CMD ["/opt/nadeko.sh"]
```

**Comment by liminalitythree** [comment]
Why not update the official docker image?

**Comment by willysunny** [comment]
Because I wasn't aware of the update, as there hasn't been really much new announcements in the nadeko help channel, so I didn't check the update as often, anyways, the docker images has been updated to 2.16.11 as of this post, and the issue should be resolved.
