### ISSUE TITLE
Bot Owner?

### ISSUE THREAD

**Issue by CaptainVianite** [Kwoth/NadekoBot#2176]
I am the bot owner on the server and as I was messing around with the bot I wanted to reset it so I typed .resetglobalperms and nothing happened and then I realized I can't type any owner commands? Why is that?

**Comment by Macley-Kun** [comment]
Selfhost or Public?

**Comment by CaptainVianite** [comment]
I'm using a discord server so I would say public.

**Comment by CaptainVianite** [comment]
I figured it out on the Nadeko discord server
