### ISSUE TITLE
NSFW not working

### ISSUE THREAD

**Issue by R4B5** [Kwoth/NadekoBot#2177]
whenever i use the nsfw nothing happens I've made sure that the nsfw is enabled

**Comment by shikhir-arora** [comment]
If you have made sure to that it's enabled and aren't getting any errors, are you using the public bot? A few NSFW stuff doesn't work on the public bot for spam/traffic reasons.

**Comment by R4B5** [comment]
not using the public bot i get this though when i give a nsfw command 
0 09:07:25 CommandHandler | Command Errored after 0/0/0.001s
        User: Weabu dUd#1778 [257284762723418112]
        Server: MYstical [389158057298362368]
        Channel: bot-commands [424526807895900161]
        Message: .boobs
        Error: Command precondition group nsfw_or_dm failed.

**Comment by shivaco** [comment]
The channel is not marked as NSFW, I suppose.

**Comment by R4B5** [comment]
so then i should do what?

**Comment by R4B5** [comment]
i figured it out all good
