### ISSUE TITLE
Official Cleverbot broken?

### ISSUE THREAD

**Issue by Gremagol** [Kwoth/NadekoBot#2178]
Hey there, cleverbot stopped working randomly. When trying to talk with it, 
it types without sending a message, only `0 17:10:43 ChatterBotService | Error in cleverbot`. popping up in the logs.

When I look into the API I bought, it doesn't get any request. (But i'm 100% sure i've put it right into the crendentials)

So I bought a second 5k/free API to look if this one works, which also didnt get any request.

Well, my question is, if the wrapper died or if they have API Issues. 

Tested on two bots with two different Keys.

Thanks in advance.

**Comment by Macley-Kun** [comment]
@Kwoth can repoduce. 

api calls made:
Total API calls allowed: 5000
Used in total: 394
Last used: 16 March 2018 22:05

Seems like the bot can't call to the api anymore. Can you test it on beta bot to be sure?

**Comment by shikhir-arora** [comment]
Strange. Works fine for me. Maybe something is getting blocked?

**Comment by Gremagol** [comment]
Seems to work for me too now, must've been some outage. I'll close it now then.
