### ISSUE TITLE
'unknown op code' disconnections

### ISSUE THREAD

**Issue by InfectedYoU** [Kwoth/NadekoBot#218]
Have received this message a few times when trying to reboot the bot, havne't had many problems before this. Just the youtube library exceptions. but this too is making the bot very hard to use, any ideas?
v0.9.5943.31954
![image](https://cloud.githubusercontent.com/assets/18339083/14493606/31f3aa82-017e-11e6-9cd9-4b16e6d704b9.png)

**Comment by coggy9** [comment]
I'm also seeing the same issue in newer builds. The last good version was v0.9.5941.21822. It usually happens when playing music.

**Comment by DragonOverlord** [comment]
I think this happens when the bot tries to play music on multiple servers; which is not supported by the library anymore

**Comment by Kwoth** [comment]
Try several times and it will work. It is not due to bot version. Discord changed some stuff which library doesn't support atm.

**Comment by InfectedYoU** [comment]
Additional triggers regarding the OpCode 9 Error.
![image](https://cloud.githubusercontent.com/assets/18339083/14693956/eca2d00a-075b-11e6-8166-dbe87404c5f8.png)
Recurring without fail (to a high %) everytime !m sh is used when queueing local files via a path.

**Comment by Kwoth** [comment]
@InfectedYoU this issue is solved for bot accounts on a newest release. Upgrade your bot to official bot account and update to the latest release.

https://github.com/DoNotSpamPls/repository/wiki/How-to-convert-your-bot-account-in-the-API
