### ISSUE TITLE
Music silent on Amazon AWS Windows x64 server 

### ISSUE THREAD

**Issue by FrozenAtlas** [Kwoth/NadekoBot#2181]
After I execute the command, bot joins the channel and music doesn't play. Followed Windows guide and installed ffmpeg and youtube-dl (I had to install youtube-dl with https://www.microsoft.com/en-US/download/details.aspx?id=5555). Also followed Google API guide. Everything works but music.

Any help?

**Comment by Kwoth** [comment]
Ask in #help on nadeko bot support server. discord.gg/nadekobot
