### ISSUE TITLE
Disabling actualcustomreactions globally doesn't work

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#2182]
![1](https://midorina.ga/u/278ec1e88f2e.png)

**Comment by xnaas** [comment]
Isn't the module `CustomReactions` unless I'm missing something...?

**Comment by Midoriin** [comment]
@xnaas there is a hidden module called `actualcustomreactions` that manages the global reactions. Disabling it with `.sm actualcustomreactions disable` will disable global custom reactions in a server. But unfortunately, its not the case with `.gmod` command, and I think this is not an expected behaviour.
