### ISSUE TITLE
Groups Out of Order

### ISSUE THREAD

**Issue by LilyLincesa** [Kwoth/NadekoBot#2183]
So for some reason all of my groups are out of numerical order and im unsure as to why. I added all the roles in numeric order, but they still appear in this order

![image](https://user-images.githubusercontent.com/37550976/37694985-a4da22ea-2c99-11e8-9a6d-f0a2fd3d9bfb.png)

**Comment by Kwoth** [comment]
Can someone else confirm this?

**Comment by Macley-Kun** [comment]
![image](https://user-images.githubusercontent.com/26381427/38164293-4494476e-3502-11e8-85a2-a8f0e665298e.png)
Can confirm, v2.17.3.

No restart. Hosting on Ubuntu 16.04.

**Comment by Kwoth** [comment]
i don't think that's what he's saying. I think what he''s saying is he has group 2 and 5 on first page, 1 and 3 on second, etc

**Comment by Macley-Kun** [comment]
![image](https://user-images.githubusercontent.com/26381427/38165080-511beb70-350e-11e8-808b-a7c170bd7864.png)
Sorry i didn't understood it that way-

I think i'm able to recreate it too with only 3 groups.

**Comment by LilyLincesa** [comment]
​Here is what the lists look like unedited on my end. We've tried removing
the roles and readding them to the groups and it didnt help.

**Comment by LilyLincesa** [comment]
Sorry for being late to the email thread, Ive been sick as shit the last
few weeks.

On Sun, Apr 8, 2018 at 9:38 PM, Lily Lincesa <lilylincesa@gmail.com> wrote:

> ​Here is what the lists look like unedited on my end. We've tried removing
> the roles and readding them to the groups and it didnt help.
>
>
>
>
>
>
>
>


-- 
~Lily Limpic
Pronouns: She/her, hers.
Student at Missouri State University
Interactive Story Design Major

**Comment by Kwoth** [comment]
Should be fixed in 2.18.1, post again if it's still bugged.
