### ISSUE TITLE
Connect4 Game Generates A False Win

### ISSUE THREAD

**Issue by xSinclare** [Kwoth/NadekoBot#2184]
**BEFORE YOU READ:** I did a quick search of the issue (#1476) and it's the exact same issue I'm having. That issue was closed and fixed, but I'm having it now with different users in my Discord. This is the first time I also enabled new modules in Nadeko as I only used it for the purpose of linking text and voice channels, so this is the first time I'm experiencing it.

I don't have much of a theory here, as with the 3 screenshots I gathered, there's a varying factor to what potentially caused Nadeko to generate a false win. If there's any more information I need to provide other than the screenshots I have, let me know.

![](https://i.imgur.com/CUbZWcb.png)

![](https://i.imgur.com/LxuJyvP.png)

![](https://i.imgur.com/B98vSvy.png)

**Comment by Kwoth** [comment]
First one is fine lol. the other 2, are you sure you're not running out of time?

**Comment by xSinclare** [comment]
If a player does not make a move in a timeframe of, let's say, 15 seconds, does it automatically draw a win?

**Comment by Kwoth** [comment]
Yes, i might need a clearer way to let users know why the game ended, but technically game works fine.
