### ISSUE TITLE
Danbooru links are insert into chat incorrectly.

### ISSUE THREAD

**Issue by Renari** [Kwoth/NadekoBot#2185]
It seems Danbooru is using a subdomain now, Nadeko is pasting links like the following:
`https://danbooru.donmai.ushttps//hijiribe.donmai.us/data/image.png`

When it should be:
`https://hijiribe.donmai.us/data/image.png`
or
`https://danbooru.donmai.us/data/image.png`

**Comment by Kwoth** [comment]
Works fine for me, can't reproduce

**Comment by Renari** [comment]
This appears fixed, was probably something on danbooru's side.

**Comment by Renari** [comment]
@Kwoth I saw this being able to be reproduced quite frequently today with people using the `.hentaibomb goo_girl` command.

**Comment by Kwoth** [comment]
Ok I'll add some code to check if it's a full url then just in case.

**Comment by Renari** [comment]
`https://danbooru.donmai.ushttps//raikou2.donmai.us`

Was another one that showed up.
