### ISSUE TITLE
Add an interface to be able to talk through the bot ?

### ISSUE THREAD

**Issue by Narihari** [Kwoth/NadekoBot#2186]
Hi, i know that the command .send already exists but this is very hard to copy and paste the correct ids of users or channels servers all the time, i'm not really good at coding a bot but i know it's possible, if you have time to do it it'll be really great :)

**Comment by Macley-Kun** [comment]
Features need to go to feathub.
Also I doubt that’s suggestion. You do know it’s really easy to copy paste in discord.

Met vriendelijke groet,

**Comment by Narihari** [comment]
Yeah but it's really boring to always have to do that, I know it can be possible to do an interface.

**Comment by Kwoth** [comment]
http://feathub.com/Kwoth/NadekoBot
