### ISSUE TITLE
Nadekobot.exe has stopped working

### ISSUE THREAD

**Issue by Klixiso** [Kwoth/NadekoBot#2188]
screenshot removed thanks to post below
tl:dr bot was angry at me

**Comment by shivaco** [comment]
I strongly recommend you to reset the bot application as soon as possible, because you just leaked your Client ID and Bot Token.
And for your issue, you forgot to put a comma after the client ID.

**Comment by Klixiso** [comment]
Thanks m8

**Comment by Macley-Kun** [comment]
Close the issue when your question is answers :p
