### ISSUE TITLE
question about bot logs

### ISSUE THREAD

**Issue by mina9999** [Kwoth/NadekoBot#2189]
hi i have this log idk what should i do 
can someone tell me what is this and why bot log this . 
![2345234523452345](https://user-images.githubusercontent.com/28566705/37866532-6480184a-2fa9-11e8-9931-d351530dfdb4.png)

**Comment by mina9999** [comment]
![3245234523452345](https://user-images.githubusercontent.com/28566705/37867195-588087ec-2fb2-11e8-9748-767b0b43e5d1.png)

**Comment by MaybeGoogle** [comment]
Too much stuff is happening at the same time, and discord is preventing the bot from sending some of it. Limit your logs with `.logignore` and `.logevents`
