### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by kanauru** [Kwoth/NadekoBot#219]
When I'm trying to build NadekoBot I get these errors

> 'DiscordClient' does not contain a definition for 'GetService' and no extension method 'GetService' accepting a first argument of type 'DiscordClient' could be found (are you missing a using directive or an assembly reference?)	NadekoBot

> 'DiscordClient' does not contain a definition for 'Add' and no extension method 'Add' accepting a first argument of type 'DiscordClient' could be found (are you missing a using directive or an assembly reference?)

**Comment by Kwoth** [comment]
I believe you can solve this by changing it to Client.Services.Get amd Client.Services.Add.

If that doesn't work, simply build discord.net separately, remove project references and reference the dlls you've built
