### ISSUE TITLE
NSFW Blacklist Command Bug

### ISSUE THREAD

**Issue by NightYoshi** [Kwoth/NadekoBot#2193]
Blacklist doesn't work for the E6 command. I have set blacklist tags but they still come through when used through e6 command. 

The tagging for E6 is also different from what is specified in the command description. E6 used to take tags with spaces between each but now it returns a "no results found" unless you use the "+" with your tags instead of spaces.

I'm using a self hosted Nadeko v2.16.10.

**Comment by Kwoth** [comment]
Show me a concrete example of what you tried to do.

**Comment by NightYoshi** [comment]
Here's a screencap of it. https://i.imgur.com/mkB3QUz.png (cropped to not show image for obvious reason).
Tag is on the blacklist but still comes through on E6, I asked about it on the discord server and was told to just report it here.

**Comment by Kwoth** [comment]
Can't reproduce. Keep in mind e621 has some weird tagging, so you might want to blacklist related tags too. And yes, you should use +, fixed description in the last commit.
