### ISSUE TITLE
Server specific currencies

### ISSUE THREAD

**Issue by xXLupoXx** [Kwoth/NadekoBot#2194]
Hey,
would it be possible to implement server specific currencies that if enabled override the global one?
That would be useful if you have a server where you wipe the currency each month for contests or something so it would not nuke all of it. As well as if you have the bot on more than one themed server you could have a currency name for each of them.

**Comment by xnaas** [comment]
Feathub.

**Comment by Macley-Kun** [comment]
https://feathub.com/Kwoth/NadekoBot/
Put your suggestion on there.
Get lots of upvotes!

And close the issue here ;-)
