### ISSUE TITLE
.weather cannot differentiate between cities in different states (US) with the same name 

### ISSUE THREAD

**Issue by roothorick** [Kwoth/NadekoBot#2196]
* `.we Springfield` returns Springfield, Missouri
* `.we Springfield, IL` returns "city not found"
* `.we Springfield, Illinois` returns "city not found"
* `.we Springfield, IL, US` returns Springfield, **Missouri**
* `.we Springfield, Illinois, US` again returns Springfield, Missouri

As best I can tell, you cannot ask Nadeko what the weather is in Springfield, Illinois.

**Comment by Macley-Kun** [comment]
Not sure but, you tried this on other bots?
IIRC, fredboat also uses the same api. If that bot can't do it ether. It's possible that this is a api limitation. But that's just a geuss...

**Comment by roothorick** [comment]
After a little googling... it is indeed a limitation in OpenWeatherMap and their stance appears to be you should just know the geolocation coordinates of the city you want and pick it from the list (seriously?): https://openweathermap.desk.com/customer/portal/questions/16829365-state-is-missing-from-the-location-information-only-shows-city-this-is-critical-for-us-clients

However, it doesn't look like that's the end of the story. The OpenWeather extension for GNOME3 also uses OWM (or optionally Dark Sky), but it has a more intelligent search, as it picks up on and factors in specifying the state, and you get results that look like this: "Springfield, Sangamon County, Illinois, United States of America [39.7989763,-89.6443688]". On a quick skim of their source code I couldn't find their search function, sadly.

**Comment by Macley-Kun** [comment]
Well that leaves us with two options, what both results in suggesting a feature.
1. You make a feature that kwoth should code this search himself, so the weather also works with **all** cities.
2. You make a feature to use a weather api that is smarter/beter then the current one.

Still, it's up to kwoth if he wants to improve this. ~explicity say improve, b/c this is not a bug however~.

**Comment by Kwoth** [comment]
Yes, nothing I can do about this.
