### ISSUE TITLE
Danbooru image links are incorrect. 

### ISSUE THREAD

**Issue by takeserelly** [Kwoth/NadekoBot#2197]
When I use .hentaibomb 
NadekoBot posts Danbooru image links in the form:
https://danbooru.donmai.ushttps//hijiribe.donmai.us/data/...
but those links should be in the form:
https://hijiribe.donmai.us/data/...
depending on the danbooru image mirror server.

**Comment by takeserelly** [comment]
Exemples, redhead and megumin , and how do i check bot version?

**Comment by xnaas** [comment]
`.stats`?

**Comment by Kwoth** [comment]
#2185
