### ISSUE TITLE
.setnick doesn't take user as argument

### ISSUE THREAD

**Issue by shivaco** [Kwoth/NadekoBot#2199]
Bot version: 2.17.3
OS: Ubuntu 16.04
Short description: The bot doesn't accept the user as an argument.
Steps to reproduce: 
- Make sure your bot version is 2.17.3.
- Make sure the bot has `Change Nickname` permission.
- Use `.setnick @UserMention NewNickname`.
Expected result: The user's nickname should change.
Actual result: The bot changes it's own nickname to <@IDOfTheUserYouMentionedEarlier> NewNickname`.
![screenshot](http://retarded.men/31xohg)

**Comment by shikhir-arora** [comment]
Not able to replicate this on 2.17.3. Relevant logs:

![screen shot 2018-03-29 at 4 56 59 am](https://user-images.githubusercontent.com/8797918/38079810-ce9622b2-330d-11e8-8c4a-3f061abe5275.png)
![screen shot 2018-03-29 at 4 57 42 am](https://user-images.githubusercontent.com/8797918/38079808-ce7e19b0-330d-11e8-81c4-7947955d6a60.png)
![screen shot 2018-03-29 at 4 57 07 am](https://user-images.githubusercontent.com/8797918/38079809-ce8a81e6-330d-11e8-8674-59a1976560f1.png)

**Comment by shikhir-arora** [comment]
Also, make sure the bot has `Manage Nicknames` (not just the `Change Nickname`) perm.

**Comment by shivaco** [comment]
Bot has the `Administrator` permission, although the command still doesn't work properly.

**Comment by shikhir-arora** [comment]
Not sure, I'm unable to replicate. Does this happen for any user/bot you try to change the nick for? Are you using the desktop client?

**Comment by shikhir-arora** [comment]
Only other thing I can see is that you need to make sure you have `Manage Nick` permissions.

**Comment by shivaco** [comment]
I am an admin. Yes, I am using desktop Discord client. Not a role hierarchy issue since the bot is almost at the top and `Active` role is under the bot's role.

**Comment by shivaco** [comment]
Update:
Happens only on my personal server. Works fine on others.

**Comment by Kwoth** [comment]
Means bot can't find that user. Make sure the user is online and bot can see it. Checked the code, its' fine.

**Comment by Kwoth** [comment]
And make sure the bot has manage nick permissions.

**Comment by shivaco** [comment]
As I mentioned before, bot has `Administrator` permission. I doubt that the bot is unable to change **my** as well as any other members' nick.
