### ISSUE TITLE
Using a custom search for a database

### ISSUE THREAD

**Issue by TM22** [Kwoth/NadekoBot#220]
Apologies if this is a stupid question, but if the question sounds stupid to you then you're probably the best person to ask :)

Simply put: I want to have NadekoBot search a database for any given input and either throw back a link or, ideally, parse results into chat.
- User types "~database ITEM"
- NadekoBot returns "http://www.database.com/q=ITEM"

OR

- NadekoBot returns information about ITEM  
e.g. "{Icon} Name: Poisoned Dagger Type: Dagger Quality: {icon} Req. lvl: 100 Item Lvl: 150"

How I would go about doing this? I am a little out of my depth when it comes to these things but I'm a quick learner so even a point in the right direction would be tremendously helpful.  :)

**Comment by Kwoth** [comment]
There are a lot of examples in the source of how to add variables from command to a string. Look into SearchHelper.cs and SearchesModule.
