### ISSUE TITLE
The bot can't seem to see the roles when it comes to permissions

### ISSUE THREAD

**Issue by Rob1992** [Kwoth/NadekoBot#2200]
Whenever I try to change the .permrole on a self hosted version of the bot to for example ".pr Overlord" (because of course I called my role that) and I have said role set to myself, it can't seem to spot that I have that role. It just keeps repeating "you need the Overlord role to change permissions".
Every time i need to use ".scadd .pr reset" to fix it because i can't seem to find the correct place in the files to do it manually.

It knows that i have the role when i do ".inrole Overlord". But when i change the permrole to it, nothing

Is this a bug, an error in my config, permission order error or something else?

**Comment by Kwoth** [comment]
Check how many roles you have that are called overlord. `.resetperms` is the right command. Also that message won't be showing up if you have administrator permissions on your server.

**Comment by Rob1992** [comment]
That's the odd thing, there is only one Overlord role, the one i made when i started the server. I also "made" (ie, downloaded and hosted it) the bot. I do have admin privileges on the server, unless things get weird if multiple roles have admin perms. If i understand the role hierarchy thing correctly it could be that, but no matter how i order them i can't seem to change them.

[https://imgur.com/a/oWv2l](url) this is how they are ordered now. The self made Bot role (the orange one) is also assigned to myself. 

On a sidenote, what happens if i don't change the .permrole from what it is when you install the bot? can everyone edit its permisions?

**Comment by shikhir-arora** [comment]
> On a sidenote, what happens if i don't change the .permrole from what it is when you install the bot? can everyone edit its permisions?

From b3327df63853cd317a4a4a2072a7f6a042c2607f:

> .pr reworked. It now saves role id in the database. Default permission role no longer exists. By default, only users with administrator permissions will be able to change permissions. use .pr role name o set a role, .pr with no arguments to see currently set role, .pr reset to reset existing one. All currently set permission roles are reset, both on public and self hosted bots.

**Comment by Rob1992** [comment]
> .pr reworked. It now saves role id in the database. Default permission role no longer exists. By default, only users with administrator permissions will be able to change permissions. use .pr role name o set a role, .pr with no arguments to see currently set role, .pr reset to reset existing one. All currently set permission roles are reset, both on public and self hosted bots.<

Well that's good, that's at least one worry less

**Comment by Kwoth** [comment]
There has been a weird issue. It's been fixed few days ago.
