### ISSUE TITLE
Self host taking up 100% cpu

### ISSUE THREAD

**Issue by nnever** [Kwoth/NadekoBot#2202]
After restarting the bot on the newest version, the dotnet consumes a 100% of it's thread. The bot still works fine, it just has abnormally high cpu usage.
This has been seen on Ubuntu 16.04 and 17.10.

**Comment by SillyBirds** [comment]
You're right, didn't notice it.

![untitled](https://user-images.githubusercontent.com/22528910/38126775-ee58904a-33f2-11e8-9cbc-81ff1a15288b.jpg)

And restarting doesn't help.
`%Cpu(s): 99.7 us,  0.3 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st`
