### ISSUE TITLE
shard 0 unresponsive

### ISSUE THREAD

**Issue by Nisouc** [Kwoth/NadekoBot#2203]
Hi,
I recently created a server and wanted to add some bots to it, I knew Nadeko from another server so I wanted to add it there. I did everything this page told me : http://nadekobot.readthedocs.io/en/latest/guides/Windows%20Guide/ and all seemed fine.

But when I tried to run the bot, this happened : http://image.noelshack.com/fichiers/2018/13/5/1522430969-gyazo.jpg 
I tried to restart my Pc and try again but the same thing happened, I checked here to see if people were having the same issue but I didnt find anything interesting. 

Could you try to help please ?
(Ps : Im on Windows10)

**Comment by Kwoth** [comment]
Can you try downloading the bot again, there was some CPU throttling issue. Also Make sure your redis is running.

**Comment by Nisouc** [comment]
I tried erasing everything from my computer (NadekoBot, NadekoBotUpdater, Redis) to install everything again. I downloaded the Updater again and reinstalled Redis, but I can't press "Update" there because for some reason it didnt go back to "Version : None" so I cant have the files again. Therefor I can't launch the bot or do anything, it just tells me "Install the NadekoBot".
I may have done something stupid there since I don't know much about all this, sorry but can you please help me again ? ^^'

**Comment by Nisouc** [comment]
I reinstalled everything and its all working perfectly, thanks for your help

**Comment by Macley-Kun** [comment]
@Nisouc close the issue when your question is answerd.
