### ISSUE TITLE
Is Nadeko offline?

### ISSUE THREAD

**Issue by PurpleBread** [Kwoth/NadekoBot#2208]
I'm not sure what happened, but I wanted to add some new self-assigning roles and Nadeko isn't responding to any commands. I think the bot is still there because the Nadeko and nadeko-mute roles are still there, but we do have over 100 members so I can't see it if it's just offline. Is there an easy fix or will I have to remove Nadeko from the server, reinvite, and set everything up all over again? 

I do have the top role and all permissions, but I'm not the owner of the server. Not sure if this matters.

**Comment by Rob1992** [comment]
from a mod in discord:
"Keep calm and carry on. We know nadeko is down. Unless you have some selfhost-related question, leave this channel. Right fucking now.

No I don't know why
No I don't know how
No I don't know when
So stop asking."

Yes we all know it's down, No we don't know when it'll return. No you can't go into discord just to ask when it'll be back

**Comment by PurpleBread** [comment]
Huh. Alrighty then. I'm kinda new to bots in general so I didn't know if something I did broke it.
