### ISSUE TITLE
.save no longer seems to work on latest docker image

### ISSUE THREAD

**Issue by Biye123** [Kwoth/NadekoBot#2213]
![image](https://user-images.githubusercontent.com/32176449/38212398-9d8adaec-368b-11e8-8709-1b63bb27392d.png)

I can only imagine this to be due to the newest docker image that fixed the shmartnumber issue (#2175) because playlists saved from before I updated are fine.

Whenever I save a playlist now of any video, it would not grab the full YouTube URL (see image), and when I try to load that playlist, it would try and pull something random, though it is the same random video if I try to load a playlist of say 200 songs.  This random video also changes day to day which I'm assuming has something to do with YouTube itself redirecting the query somewhere.

**Comment by xnaas** [comment]
Would it make more sense to make an issue on @willysunny's repo for this? https://github.com/willysunny/Nadecker 😜

**Comment by Kwoth** [comment]
Yes, i fixed this few patches ago and the docker should be updated.
