### ISSUE TITLE
Banned for asking question

### ISSUE THREAD

**Issue by BobbyMan227** [Kwoth/NadekoBot#2215]
I asked a question regarding legal / Copyright with Nadeko, I asked multiple times nobody answered. Went to ask Kwoth himself got soft banned for it, when I returned I asked why we cant ask legal / Copyright questions, after that One of the admins got really pissed off at me saying to just ask the question (which I did but nobody responded) They then sent me the Link I needed, when I asked why they couldn't have sent the link in the first place they claimed I was being "bitchy" and perm banned me. Just for asking a question. I took a recording so if you need it let me know.

**Comment by shikhir-arora** [comment]
While I wasn't witness to any of this, please go through the appropriate ban appeal process if you haven't as it keeps things organized, and GitHub is generally for bot problems/bugs/errors and the likes.

https://docs.google.com/forms/d/1xAeyjWnQCe_OgHv3od0XIjKbq_iTm6qaRQqGFS6hPOs/viewform?edit_requested=true
