### ISSUE TITLE
.autoboobs and all .auto commands not working

### ISSUE THREAD

**Issue by SplitSins** [Kwoth/NadekoBot#2218]
I have it where Nadeko bot has managemessages channel perms yet it still doesn't work, help please

**Comment by Macley-Kun** [comment]
set channel on nsfw

**Comment by shivaco** [comment]
`.auto`-NSFW commands don't work on public Nadeko. You would need to self-host it.

**Comment by Kwoth** [comment]
SERVER OWNERS ARE NOT BOT OWNERS. All owner-only commands require you host the bot. Hosting means you are running a nadekobot on your own computer. If you want to learn how to host the bot yourself, type `-guide`
