### ISSUE TITLE
Bot doesn't see who's the owner

### ISSUE THREAD

**Issue by SKMots** [Kwoth/NadekoBot#2219]
I tried this multiple times on different servers -> I invite the bot but then trying to set it up it doesn't do anything, all of the "botowner" commands don't seem to work and I can't setup anything.

Not in a single discord

**Comment by Macley-Kun** [comment]
Is the owner id correct?
Did you try making a brand new server, invite the bot. And try out the commando there?

Also keep an eye on the logs. They might tell you more about what’s going on.

**Comment by Kwoth** [comment]
SERVER OWNERS ARE NOT BOT OWNERS. All owner-only commands require you host the bot. Hosting means you are running a nadekobot on your own computer. If you want to learn how to host the bot yourself, type `.guide`
