### ISSUE TITLE
!M q wont work!! help

### ISSUE THREAD

**Issue by sethdm02** [Kwoth/NadekoBot#222]
Every Time I Type in A song !m q (song) or link it says "Failed resolving the link.Exception of type 'VideoLibrary.Exception.BadQueryException' I Need Help
![failure](https://cloud.githubusercontent.com/assets/18504983/14583047/f750b0a4-03db-11e6-8279-c60712f500b1.PNG)

**Comment by Kwoth** [comment]
#189
