### ISSUE TITLE
Connect to an SQL database

### ISSUE THREAD

**Issue by hemipatu** [Kwoth/NadekoBot#2225]
Is it possible to connect Nadeko to a cloud based SQL database and if not, is it something that can be added as a future function?

Also, are the tables being used all InnoDB?

**Comment by Kwoth** [comment]
not atm, and it's all sqlite.

**Comment by Macley-Kun** [comment]
Make a feature! Maybe it'll get implemented :-)

Unrelated: i think if this would be implemented, i could have a shot to get Nadeko working in Heroku again...

**Comment by hemipatu** [comment]
I've done just that, if you like the idea I've added it on feathub as a request here: https://feathub.com/Kwoth/NadekoBot/+512
