### ISSUE TITLE
Changing Slot Machine Images Brings This Error.

### ISSUE THREAD

**Issue by ATAStaff** [Kwoth/NadekoBot#2227]
![1](https://user-images.githubusercontent.com/35782609/38475749-15407fc4-3b78-11e8-9a49-14239a972f5b.png)

That first image is the error. I made sure that all the dimensions were the same and the names were exactly the same. I thought there might be a reference to the images somewhere in a .dll that I'd have to go and edit, but I did a very minor change to the numbers that appear on the slot machine (Color change only) and I would still get the above error. 

![2](https://user-images.githubusercontent.com/35782609/38475804-688f17a8-3b78-11e8-8d7e-30b5be7c0f3f.png)

Restarted the bot, triple checked names and dimensions (Only place dimensions vary a little are for the emojis), etc etc. None of the Suport Girls in the Discord know how to fix it.

Please and thank you.

**Comment by shivaco** [comment]
Try deleting the other files other than 1.png, 2.png and 3.png and see if that works.

**Comment by ATAStaff** [comment]
I have. I changed all the files and only changed some. It always gives me that error unless I'm using the base images.

**Comment by ATAStaff** [comment]
![4](https://user-images.githubusercontent.com/35782609/38476698-3045e606-3b7d-11e8-9edd-4a74024a4ff9.png)

**Comment by Macley-Kun** [comment]
i though we stored images like these in the image.json?

Not sure on windows. But i would surely say it would. What version your on?

**Comment by ATAStaff** [comment]
I thought these were stored in a .json also  so I asked around the discord, but it seems that everything but the slot machine is in the image.json. 

I'm using the latest windows one.

**Comment by Macley-Kun** [comment]
Well i'm only using linux..

@MaybeGoogle your familiar with windows 🤔 ?

**Comment by ATAStaff** [comment]
Since I'm running it off a virtual server I can try switching to linux. Will I be able to transfer all the data from the old one easily?

I'd also still like to know how to fix this issue on windows.

**Comment by Macley-Kun** [comment]
Oh yes you can backup everything! Just get the credentials.json and the db! Only replace the db in Linux after it's all up and running.

About the issue, I would have to test it out for myself, but I'm quite busy with college so.. for now I suggest Linux.

Verstuurd vanaf mijn iPad

**Comment by ATAStaff** [comment]
Thank you.

**Comment by MaybeGoogle** [comment]
@Macley-Kun no, macos for personal. This person asked in help, I couldn't figure out why it was doing this. :male_shrug:

**Comment by Macley-Kun** [comment]
@MaybeGoogle oh well, let's see if more people show up with this 😛 
@ATAStaff update us if linux works better for ya!

**Comment by ATAStaff** [comment]
Hey @Macley-Kun . Finally got it working on Windows. When I was copying the files over, I changed everything except for "background2". background2 I has as the original, default image. After changing background2, everything worked great. Essentially, it seems that I can't just change one file, but instead have to change all of them.
![2](https://user-images.githubusercontent.com/35782609/38710883-7910d362-3e90-11e8-8af3-dd80d579a8e5.png)
![1](https://user-images.githubusercontent.com/35782609/38710886-7af2ba92-3e90-11e8-9892-e564be02bd1c.png)

Thanks again.

**Comment by xnaas** [comment]
@ATAStaff don't forget to close the ticket. 😜

Thanks for sharing your answer for future issue searchers!
