### ISSUE TITLE
Music not working with SoundCloud.

### ISSUE THREAD

**Issue by skid9000** [Kwoth/NadekoBot#2228]
Running Debian 9 (up to date)
Youtube-DL 2018.04.09
NadekoBot v2.17.4

``avril 09 22:04:45 twittolabel zsh[17517]: 0 22:04:45 MusicPlayer | Starting
avril 09 22:04:45 twittolabel zsh[17517]: 0 22:04:45 MusicPlayer | Got Audio client
avril 09 22:04:45 twittolabel zsh[17517]: https://soundcloud.com/leonekmi/nintendo-direct-earrape: Invalid data found when processing input
avril 09 22:04:45 twittolabel zsh[17517]: 0 22:04:45 CommandHandler | Command Executed after 0/0/0,748s
avril 09 22:04:45 twittolabel zsh[17517]:         User: leonekmi#5691 [193616433312301057]
avril 09 22:04:45 twittolabel zsh[17517]:         Server: Serveur de Luclu Askip [278929236960608256]
avril 09 22:04:45 twittolabel zsh[17517]:         Channel: general [278929236960608256]
avril 09 22:04:45 twittolabel zsh[17517]:         Message: +ra https://soundcloud.com/leonekmi/nintendo-direct-earrape
avril 09 22:04:46 twittolabel zsh[17517]: 0 22:04:46 MusicPlayer | Created pcm stream
avril 09 22:04:46 twittolabel zsh[17517]: 0 22:04:46 MusicPlayer | Song removed because it can't play
avril 09 22:04:46 twittolabel zsh[17517]: 0 22:04:46 MusicPlayer | Next song``

I tested to download it with youtube-dl only and it worked so ...

**Comment by Kwoth** [comment]
Works fine for me.
