### ISSUE TITLE
Shop/Buy bug. (Self hosted)

### ISSUE THREAD

**Issue by vashu96** [Kwoth/NadekoBot#2230]
When purchasing something from the .shop command using the .buy the amount that should be deducted from a players flowers is not taken out.  For example if a Role/List item cost 100k and the User has 105k flowers, when the finish the transaction with .buy X the player than only would have lost 10k for some reason IE they would be at 95k instead of having 5k remaining. The issue can be recreated pretty easily. Version tested on 2.17.4 and 2.18.2
![image](https://user-images.githubusercontent.com/17517472/38574024-5871ecba-3cbd-11e8-9f8d-a9db80e3f598.png)

**Comment by Kwoth** [comment]
🤦‍♂️ 

`.curtrs`
