### ISSUE TITLE
Embedded quotes borked

### ISSUE THREAD

**Issue by PotatoGaming2079** [Kwoth/NadekoBot#2231]
When doing ... with an embedded quote, the quote will not have an id#. Example shown here https://imgur.com/a/B1ffO. Also, when doing .qid with an embedded quote id#, it will not display the quote id# and who made but will display the quote. Example shown here https://imgur.com/FTteWbZ. Please fix embedded quotes to show id# when ... is done and to show id# and who made it when .qid is done.

**Comment by MaybeGoogle** [comment]
Find the qid with liqu. The point of the embed is for it to look clean.

**Comment by PotatoGaming2079** [comment]
But what if i want to know who made the embedded quote?

**Comment by PotatoGaming2079** [comment]
.qsearch will show ID but not who made it

**Comment by MaybeGoogle** [comment]
.liqu will.

**Comment by zergling-man** [comment]
Re-open. The main bug (not being able to quickly retrieve author of an embedded quote) remains unfixed.
