### ISSUE TITLE
Reaction event not working on self-hosted bot

### ISSUE THREAD

**Issue by splendiferachie** [Kwoth/NadekoBot#2232]
Hi there,

I've been trying for a while to have my self-hosted bot do a reaction event but nothing seems to be working. The reaction start message itself shows, but currency isn't given out for some reason.

I've upgraded to the latest version of Nadeko (v2.18.2) and the console doesn't show any error message so I don't know what's up. 

What can I do to fix this? Thank you!

**Comment by Kwoth** [comment]
It's `.eventstart reaction` If console throws an error, then change your currencysign to some proper emoji with `.bce CurrencySign <emoji_here>`
