### ISSUE TITLE
problems with nsfw.

### ISSUE THREAD

**Issue by eXcaliburNwi** [Kwoth/NadekoBot#2233]
Hello, first i should be thanking you for such amazing bot =].

I've added nadeko on my server and proceeded to follow the guide to set it up. I have a Nadeko role attached to myself (placed it above all other roles and gave its proper permissions), i have also allowed nsfw on the server using the command .sm nsfw enable. 

Now shes not recognizing the commands like .rule34 []. I tried using the .verbose true to see if i'd get anything back,, but nop no response.

Everything works fine, i need help D:

**Comment by MaybeGoogle** [comment]
Set the channel to nsfw in Discord channel settings.
