### ISSUE TITLE
nadeko not logging deleted messages

### ISSUE THREAD

**Issue by Takikimo** [Kwoth/NadekoBot#2235]
After the recent update (v2.18.2), my self-hosted Nadeko doesn't log deleted messages at all - I've tried everything I can think of to fix it, and nothing works. Every other logging event works fine, it's just the deleted messages.

**Comment by xnaas** [comment]
Anything related to messages, for me. Doesn't get edits nor deletions on 2.18.2.

**Comment by MaybeGoogle** [comment]
For extra confirmation, someone who i think has a new install or something reported this in help channel on discord server.

**Comment by xnaas** [comment]
My current install is only a few months old, but my database is probably a year or two old, at least, FWIW.
