### ISSUE TITLE
Failed to parse Int32 Error  when someone wants claim waifus

### ISSUE THREAD

**Issue by mina9999** [Kwoth/NadekoBot#2238]
when someone want claim someone else with 2422227712 flowers bot showing the Failed to parse Int32 error and he cant claim someone .

**Comment by xnaas** [comment]
2,147,483,647 is the max supported by 32-bit integers. 2,422,227,712 is too large. Use a smaller number.

**Comment by mina9999** [comment]
ik but maybe he can change it to 64-bit integers or 128 .

**Comment by xnaas** [comment]
https://feathub.com/Kwoth/NadekoBot

**Comment by MaybeGoogle** [comment]
64 bit int is the maximum storage value. that would break gifting, making waifu price negative.

**Comment by Kwoth** [comment]
No plan to fix this
