### ISSUE TITLE
No icon on the bot exe

### ISSUE THREAD

**Issue by TheOddball** [Kwoth/NadekoBot#2240]
As title says, there currently is no icon on the actual bot exe. Unfortunately there is a bug with DotNet that doesn't allow icons to be set. https://github.com/dotnet/cli/issues/3267
I seem to have found a solution though:
https://github.com/JustArchi/ArchiSteamFarm/tree/04a5d59d52b6c27badf16b1b507c84ee3eac587f/tools/rcedit
The RCEdit exe can be used to edit executable resources after compilation.  If you use RCEdit in the installer then run it after the fact, using this command: `rcedit.exe "nadekobot.exe" --set-icon "nadeko_icon.ico"` That command with RCEdit will set the icon correctly.

**Comment by Kwoth** [comment]
Yea this doesn't seem like something i want to do.

**Comment by Kwoth** [comment]
#yolo
