### ISSUE TITLE
embedbuilder incorrectly uses json field for thumbnails

### ISSUE THREAD

**Issue by theLAZYmd** [Kwoth/NadekoBot#2241]
This is a request to bring the json generated by Nadeko's embed visualiser in-line with a standardised json object for a discord embed; so that the embed visualiser might be a universal embed generator. As it stands, the embed visualiser incorrectly creates fields for thumbnails. A typical embed might look like this:
```json
{
  "title": "Rules of Music Flip & Roll",
  "description": "1. Start by typing`.give x @Musickn`\n2. Flip 30 using `.roll 30`.\n3. If your average is lower than **2.85 or higher** than an average of **4.05**, then you get to flip a coin. Call **heads** or **tails**. If you win the coin flip, then you get **3x** what you bet!\n4. If your average is lower than **3.45**, then you get to flip a coin!",
  "color": 53380,
  "footer": {
    "text": "Good luck!"
  },
  "thumbnail": "https://i.imgur.com/w1Ne9aK.jpg"
}
```
but in actual fact, in order to be a valid discord embed object, it *should* look like this:
```json
{
  "title": "Rules of Music Flip & Roll",
  "description": "1. Start by typing`.give x @Musickn`\n2. Flip 30 using `.roll 30`.\n3. If your average is lower than **2.85 or higher** than an average of **4.05**, then you get to flip a coin. Call **heads** or **tails**. If you win the coin flip, then you get **3x** what you bet!\n4. If your average is lower than **3.45**, then you get to flip a coin!",
  "color": 53380,
  "footer": {
    "text": "Good luck!"
  },
  "thumbnail": {
    "url": "https://i.imgur.com/w1Ne9aK.jpg"
  }
}
```
Now obviously Nadeko parses the former layout correctly, because it does register thumbnails and returns them correctly. But it would be nice to be able to use this embed visualiser with other bots, since it's such a minor change to make it compatible. The visualiser really is the best embed visualiser for discord available on the internet, and it's a really useful tool that it would be nice to use for more purposes.

**Comment by Kwoth** [comment]
No, it would break everything that we already have.
