### ISSUE TITLE
Sometimes, when bot gets kicked, custom responses get wiped.

### ISSUE THREAD

**Issue by JeDaYoshi** [Kwoth/NadekoBot#2243]
I found this on public Nadeko, got told to report it here.

We kicked Nadeko from a guild, yeah, in past it would keep custom responses etc. and have them when she was readded - but looks like now they got suddenly wiped. I'm not sure how this happened, we just kicked her then readded her and nothing there. Configurations like prefix etc. were still there, but the 14 pages of custom responses were gone.

(This screenshot was kicking her then readding her again):

![Nothing, nada.](https://a.very.lewd.cat/32jTs.png)

(Before me kicking her, yesterday, at the time of posting this issue):

![14 pages.](https://a.very.lewd.cat/hxoBH.png)

They all are gone.

**Comment by xnaas** [comment]
Is this the public Nadeko? Or self-hosted? (Looks like public.)

If it's the public bot, I think this is what the Discord help server is for. GitHub is for reporting bugs and such with the self-hosted version of the bot.

**Comment by JeDaYoshi** [comment]
@xnaas As mentioned in the post, it is the public Nadeko. I went to the Discord help server, and got told to open an issue here.

**Comment by xnaas** [comment]
Hmm, that doesn't seem right, haha

@Kwoth can you confirm if public Nadeko does some kind of purging when leaving a server?

**Comment by Kwoth** [comment]
@JeDaYoshi Yes i did indeed change the code which handles that. I will look into this issue, thanks

**Comment by Kwoth** [comment]
(btw don't worry they're not wiped, they just don't reload for some reason)
