### ISSUE TITLE
MessageUpdated/MessageDeleted not logging

### ISSUE THREAD

**Issue by Paril** [Kwoth/NadekoBot#2246]
Our server has a channel where we log UserJoined, UserLeft and UserUnbanned - these all work fine.
We have a second channel that is set to log UserUpdated, MessageUpdated, and MessageDeleted. UserUpdated works fine, but MessageUpdated and MessageDeleted do not propagate to these channels.

Is there something else we have to enable for these to go through? https://i.imgur.com/jandEKA.png

**Comment by shikhir-arora** [comment]
There's already an issue for this: https://github.com/Kwoth/NadekoBot/issues/2235

Probably related to the change made earlier that disabled the message cache.

**Comment by Paril** [comment]
Ah, thanks for the note! I didn't catch it in my search. Close as dupe as necessary.

Is there a way to downgrade?

**Comment by shikhir-arora** [comment]
It's like one line of code, but I don't know if this is the actual problem. Only a guess. I'll check it out later.

**Comment by Paril** [comment]
I don't know, I just went back to before that commit.

On Apr 17, 2018 5:22 PM, "Shikhir Arora" <notifications@github.com> wrote:

Does it work with 2.18? I'll check shortly. If it does, then it's the
message cache disable that did it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Kwoth/NadekoBot/issues/2246#issuecomment-382151220>,
or mute
the thread

**Comment by xnaas** [comment]
Is there a fix for this in the pipeline, @Kwoth?
