### ISSUE TITLE
Error: Command precondition group nsfw_or_dm failed.

### ISSUE THREAD

**Issue by gigastackcat** [Kwoth/NadekoBot#2247]
Error shows on log when I try a NSFW command in a server with the module enabled. NSFW commands work through DM, though. Nadeko is self-hosted. 

![nadekobot_2018-04-17_21-19-43](https://user-images.githubusercontent.com/38486049/38913069-4dd2750e-4285-11e8-9745-d855f1f1763a.png)

**Comment by shivaco** [comment]
Mark the channel as NSFW.

**Comment by gigastackcat** [comment]
That did it, thanks. I was using an old version of Nadeko and updated it, don't think the old version required it.

**Comment by shivaco** [comment]
According to discord ToS, all NSFW stuff should be sent in marked-as-NSFW channels.
