### ISSUE TITLE
planting 1000000000 flowers kills the bot and vps and redis

### ISSUE THREAD

**Issue by mina9999** [Kwoth/NadekoBot#2248]
![56345634563456463456](https://user-images.githubusercontent.com/28566705/38935263-2cfbea32-4333-11e8-8549-83c9edfeb80e.png)

**Comment by TheOddball** [comment]
This is due to the fact that flowers are a 32 bit integer. This really isn't a bug.

**Comment by xnaas** [comment]
This is basically the same thing that was brought up in #2238.

Just use smaller numbers. There's no need to have such large, inflated values anyway. 🙃

**Comment by Kwoth** [comment]
fix your economy : )
