### ISSUE TITLE
Playing status changing randomly

### ISSUE THREAD

**Issue by KruziikDova** [Kwoth/NadekoBot#2252]
Is it possible to make these "playing/watching/etc." statuses changing randomly? Not by the IDs in database?

F.e. ids (1->4->5->2->8->...) instead of (1->2->3->4->5->...)

**Comment by xnaas** [comment]
Sounds like something for FeatHub. https://feathub.com/Kwoth/NadekoBot

If you add it, link it here, I'll upvote it, for sure.

**Comment by KruziikDova** [comment]
Sure, why not
Thank you 😃 

https://feathub.com/Kwoth/NadekoBot/+528

**Comment by xnaas** [comment]
Don't forget to close the GitHub issue, @KruziikDova. 😉
