### ISSUE TITLE
Ratelimit issues with aws.random.cat?

### ISSUE THREAD

**Issue by zergling-man** [Kwoth/NadekoBot#2256]
http://aws.random.cat/meow does work, and returns a cat picture...
Once. Then it starts returning 403s, so I'm guessing it's a lazy attempt at a ratelimit with an absurdly high cooldown for something based on AWS. (Going on 10 minutes already.)

**Comment by xnaas** [comment]
It's working for me:
![image](https://user-images.githubusercontent.com/8271327/39317810-2529f64a-4942-11e8-9d07-c809020de779.png)

Possibly you just ran into a temporary API issue? I can spam it as much as I want right now on my self-hosted bot.

**Comment by Kwoth** [comment]
Hmm, I'm thinking of collecting dog, cat and food images to my own cdn and hosting them from there...

**Comment by Kwoth** [comment]
Oh this was fixed since bot uses a different source for cat, dog, food and bird images.
