### ISSUE TITLE
Option to ping a role when stream goes live? (and/or make a customisable message.content)

### ISSUE THREAD

**Issue by theLAZYmd** [Kwoth/NadekoBot#2257]
At the moment I'm having to use a bot to read Nadeko's live message and react to it appropriately like this:

![image](https://user-images.githubusercontent.com/31519537/39369719-f5efd522-4a34-11e8-9421-0b2a35b970fc.png)

It would be cool if the feature was native.

**Comment by Kwoth** [comment]
You can do it with .streammsg in the latest patch. Just put a role mention in. You have to set it for ever stream individually though.
