### ISSUE TITLE
Design option to edit live messages when offline removing thumbnail and change wording instead of posting new message?

### ISSUE THREAD

**Issue by theLAZYmd** [Kwoth/NadekoBot#2258]
Floating an alternative design consideration which might be nice: HarmonBot edits the old live message and replaces the wording with 'was live' to signify when a stream is over. Might look nicer.

![image](https://user-images.githubusercontent.com/31519537/39369844-3bb74fb8-4a35-11e8-89a3-18b4b1de9f93.png)

**Comment by Kwoth** [comment]
nope
