### ISSUE TITLE
.autocmdadd issue

### ISSUE THREAD

**Issue by AnkokuShizora** [Kwoth/NadekoBot#2262]
I used .autocmdadd to have my bot repeat a command every 60 seconds. The issue is that even though i removed the command from the autolist later, the bot kept repeating it nonetheless. I had to restart my bot for it to stop doing so.

**Comment by Kwoth** [comment]
Oh, I'll investigate 👀

**Comment by Kwoth** [comment]
Nope, can't reproduce, works fine.
