### ISSUE TITLE
.repeat broken for self-hosters

### ISSUE THREAD

**Issue by anthonyrgib** [Kwoth/NadekoBot#2263]
Hello,

I updated to version 2.20 and since then .repeat does nothing. When i type for example ".repeat 5 hello" the message disappears, the bot console shows it's a correct command but as soon as I type ".repeatlist" the message appears saying "no active repeaters". 

I've enabled the ".ve" thing and tried, that doesn't report any issues with what i'm typing. It's just broken.

**Comment by YokoSpaghetti** [comment]
This also appears to be affecting commands related to streaming, such as .streamadd and its similar commands. They no longer show when users begin streaming.

**Comment by Kwoth** [comment]
`.remind -m "Hello" -i 5` Read the new command description.

**Comment by anthonyrgib** [comment]
So there is no longer a .repeat command? I thought .remind and .repeat were separate commands?

**Comment by xnaas** [comment]
I think he just typo'd, @anthonyrgib. It seems to still be `.repeat`:

![img](https://xnaas.info/img/NJTQF.png)

When in doubt, just `.h .command`. 😉
