### ISSUE TITLE
Bot refusing to play any Icecast hosted radio server

### ISSUE THREAD

**Issue by NeddyPlays** [Kwoth/NadekoBot#2266]
Hi i've got a problem using the NadekoBot on my Discord Servers.
Its refusing to play any Icecast hosted radio servers.

Shoutcast servers are fine. But i cannot expect the big radio stations to change over.

**Comment by Kwoth** [comment]
Make a feathub issue and ask for support of icecast
http://feathub.com/Kwoth/NadekoBot.

**Comment by NeddyPlays** [comment]
This isn't a feature request. It seems like a bug.
