### ISSUE TITLE
.autocmdadd works but stopping the auto-commands fails.

### ISSUE THREAD

**Issue by Gremagol** [Kwoth/NadekoBot#2267]
This is how to recreate it:
Just do `.autocmdadd 10 .flip`
After that, remove it by doing `.autolist`, in my case ID 0.
So, we are going to remove it with `.scrm 0`
The Bot will still continue using the command.
Restarting the Bot finally fixed the issue. To understand it better, look at my Screenshot.
![d84](https://user-images.githubusercontent.com/24619854/39425585-74a41600-4c7c-11e8-9a7b-05f04aafab85.jpg)

**Comment by Gremagol** [comment]
Yes, can confirm that restarting without deleting it, makes the bot forget about it but its still in the list.
(The autocommand is in the list but doesnt work anymore after restart.)

**Comment by Kwoth** [comment]
It has something to do with the fact that it doesn't execute successfully it seems
