### ISSUE TITLE
Nadeko Parcing Won't Work

### ISSUE THREAD

**Issue by SallGoodmanServers** [Kwoth/NadekoBot#2269]
Parcing is when you do .setgame watching/playing/streaming %users%, for example. It will not work, and I host my own version of the bot. I was told to put in about this issue here. 

Other parcing is %servers% for example.

**Comment by shikhir-arora** [comment]
AFAIK, those only work with `.addplaying`:

```
Adds a specified string to the list of playing strings to rotate. You have to pick either 'Playing', 'Watching' or 'Listening' as the first parameter. Supported placeholders: %servers%, %users%, %playing%, %queued%, %time%, %shardid%, %shardcount%, %shardguilds%.
```

You can just use `.adpl` and then `.ropl` to enable it. If you just add one game, it'll act the same as `.setgame`.

I could be wrong as I haven't checked so let me know if that is the case, but I'm pretty sure it's like that now. Either way, it's relatively easy of a change if @Kwoth wishes it to work that way.

**Comment by SallGoodmanServers** [comment]
I am not sure how to use the .adpl command. I just tried it and nothing
happened. I will show you some pictures of how I'm executing the command.

**Comment by shikhir-arora** [comment]
Just type `.h .adpl` and it'll tell you, but it's fairly straightforward. 

`.adpl Watching %users%` for example - then `.ropl` should activate it.

**Comment by SallGoodmanServers** [comment]
That worked, thank you!

**Comment by shikhir-arora** [comment]
No worries. If you want to leave this open (not sure if Kwoth wants to add placeholders to setgame) that's fine. Also, if you can use the same `.adpl` to add another game if you wish, and `.listplaying` to view the list of rotating games. Right now you should only have one if you type `.listplaying` 🙂
