### ISSUE TITLE
~i/~ir Image search throws an Error: 403 (Forbidden)

### ISSUE THREAD

**Issue by darkCUUKIE** [Kwoth/NadekoBot#227]
First of all I want to say, awesome work with the bot.
I only have one small problem right now.

Every time I try the ~ir or ~i command, discord only tells me:

`Response status code does not indicate success: 403 (Forbidden). `

No error in the cmd.

**Comment by Kwoth** [comment]
Most likely daily limit reached. One day we will move to imgur and we won't have this problem.
