### ISSUE TITLE
.listservers bug 

### ISSUE THREAD

**Issue by mina9999** [Kwoth/NadekoBot#2270]
hi kwoth :3 
my bot is in 57 servers but the list just shows 12 servers i think its a bug . 
![3456456345344564563456](https://user-images.githubusercontent.com/28566705/39499908-28895cbc-4dc6-11e8-95d6-f58b1f4e0dbd.png)

**Comment by Kwoth** [comment]
Did you try to use `.listservers 2` etc, to see the pages?

**Comment by mina9999** [comment]
thanks kwoth it work now .
