### ISSUE TITLE
.autocmdadd bug - Only executes the last command from the list

### ISSUE THREAD

**Issue by JohnGow383** [Kwoth/NadekoBot#2275]
When setting up more than one .autcmdadd commands, only the last command in the list is executed. This occurs when using .prune / .clear commands in the list. It would appear when using the same time between intervals that all commands are executed simultaneously but only the last command is actually triggered. A get around I've found is to stagger the commands, say 5 seconds more for each consecutive command, but over time this will cause issues after many repeats. The BOT also has to be restarted to reset the timers. It does not perform in the same manner as .scadd command where each command is successfully triggered before moving onto the next.

**Comment by Kwoth** [comment]
Can't reproduce in the latest patch. I think you're getting ratelimited.

**Comment by JohnGow383** [comment]
What do you mean ratelimited? Should I retry with not putting a stagger between commands?

**Comment by zergling-man** [comment]
Doesn't the console log ratelimits? I'll try to reproduce later.
