### ISSUE TITLE
Uhh... Negative exp?

### ISSUE THREAD

**Issue by ItsRainey** [Kwoth/NadekoBot#2276]
https://cdn.discordapp.com/attachments/441049353159835669/441765000491827200/186229847520051201_xp.png
So I messing with the .xpadd command(in my own server, duh), and I noticed I didn't get any levels. 
Give me a simple fix, and you can close this.

**Comment by xnaas** [comment]
Automatically expanded image:

![discord](https://cdn.discordapp.com/attachments/441049353159835669/441765000491827200/186229847520051201_xp.png)

**Comment by Kwoth** [comment]
`.execsql UPDATE UserXpStats SET Xp=0 WHERE GuildId=yourguildid and UserId=youruserid`
