### ISSUE TITLE
Nadeko bot won't launch and shows as offline

### ISSUE THREAD

**Issue by Scarlet-Lunarys** [Kwoth/NadekoBot#2277]
![image](https://user-images.githubusercontent.com/39012953/39666660-0bfd2b9e-505c-11e8-8414-f78a49debe56.png)
help!

**Comment by Wizkiller96** [comment]
Seems the error is try to tell you that your config file json format messed up. Try looking at https://github.com/Kwoth/NadekoBot/blob/1.9/src/NadekoBot/credentials_example.json and seeing if anything is missing. But seem to be pointing at the OwnerIds so I will compare that spot first
