### ISSUE TITLE
Custom reactions with .crca enabled interfere with the use of .acr

### ISSUE THREAD

**Issue by Qwertygiy** [Kwoth/NadekoBot#2280]
Some months ago, I was able to use Nadeko to add a wide list of reactions to messages containing specific words or phrases.

.acr "abomination" Somebody say, abomination? (link to an abomination)
(Nadeko confirms reaction)
.crca (number of reaction)
.acr "abomination" Somebody say, abomination? (link to a different abomination)
(Nadeko confirms reaction)

But it has stopped working properly. Now, instead of allowing a list to be built, it triggers the response instead of adding a new response:

.acr "abomination" Somebody say, abomination? (link to an abomination)
(Nadeko answers with a previously added response and does not add the reaction)

And further testing shows that it is not some fault with the hefty list being too full:
https://i.imgur.com/IkOYwfk.png
https://i.imgur.com/f1yxCKq.png

**Comment by Kwoth** [comment]
#2172
