### ISSUE TITLE
nadekobot just won't start.

### ISSUE THREAD

**Issue by domokoo** [Kwoth/NadekoBot#2283]
Have done everything accordingly to the youtube video i found. 
but i cant seems to start the bot.

![image](https://user-images.githubusercontent.com/38987774/39672932-e37291b8-5165-11e8-9fbc-c7e3eacacaa1.png)

**Comment by shivaco** [comment]
Try restarting your Internet.

**Comment by domokoo** [comment]
i did restart it, but still it didnt work.

![image](https://user-images.githubusercontent.com/38987774/39675635-7e214d42-5190-11e8-8d04-b7ff1db28a53.png)

**Comment by Macley-Kun** [comment]
Disable antivirus and firewall

Met vriendelijke groet,

**Comment by domokoo** [comment]
tried, still cannot.

**Comment by Macley-Kun** [comment]
@domokoo you've tried the above?

**Comment by domokoo** [comment]
Hi,

I have tried the above.
None of them works till i reinstall everything again.

Thanks for the help!

**Comment by Macley-Kun** [comment]
Don't forget to close the issue ;)
