### ISSUE TITLE
.lsar messes up the formatting when changing pages

### ISSUE THREAD

**Issue by Gremagol** [Kwoth/NadekoBot#2285]
I got told to open an issue.
So, this is how to recreate it:
Use `.asar` on enough roles to have multiple pages. 
Use `.lsar` and switch between the pages for a bit. You'll see it.
I've made a GIF to show it:
https://gfycat.com/HiddenMemorableIcefish

**Comment by Macley-Kun** [comment]
@Kwoth bug?

**Comment by Macley-Kun** [comment]
![image](https://user-images.githubusercontent.com/26381427/40933100-c2b90916-6830-11e8-8e91-239a88da0796.png)

**Comment by Gremagol** [comment]
Try with changing pages.

**Comment by rjt-rockx** [comment]
Could likely be a Discord bug, I've come across similar cases where the embed text gets messed up similarly to this when editing embeds. 
Not sure if that's the case though, I haven't been able to reproduce it.

**Comment by Gremagol** [comment]
Was indeed a Discord issue. Can't reproduce it anymore.
