### ISSUE TITLE
I'd like to see a better Shop system

### ISSUE THREAD

**Issue by haydennyyy** [Kwoth/NadekoBot#2287]
As far as I know, you can only have 1 item per listing using the shop, otherwise it tells you there's already an item. This is quite annoying as it then cannot be used for the purpose some people will want to use it for! Have it so you can just add stock to it with the same description at least, or make it so the `list` type can be unique or just a stocked item.

**Comment by haydennyyy** [comment]
I posted this here because I feel being able to at least add more than one item is an issue.

**Comment by Macley-Kun** [comment]
Normally suggestions go here: https://feathub.com/kwoth/nadekobot

But it seems to be “missing”. Not sure what to tell you to do now.
