### ISSUE TITLE
.mute display glitch (Timer)

### ISSUE THREAD

**Issue by Mercy1** [Kwoth/NadekoBot#2288]
It seems whenever i do a .mute 10m etc it will mute the person and give the normal message but instead of showing the time it shows this (screenshot is below)-
"NadekoBot.Core.Common.TypeReaders.Models.StoopidTime minutes."
Is this just a glitch with the new update? (Self hosted bot)
![image](https://user-images.githubusercontent.com/928221/39784721-4f1b74fa-5311-11e8-9362-c5e2935d73d4.png)

**Comment by Wizkiller96** [comment]
Yeah, I also encounter that and did a temp fix until an actual fix came out. But I think the cause was that it was just `time` and not `time.Time` so it couldn't find it in the TypeReader.

**Comment by SeemsFishy** [comment]
Yeah, I can confirm the glitch. But it is only a visual bug, the command works fine.
