### ISSUE TITLE
Documentation points to command that doesn't exist

### ISSUE THREAD

**Issue by numbermaniac** [Kwoth/NadekoBot#2291]
![screen shot 2018-05-12 at 11 34 55 am](https://user-images.githubusercontent.com/5206120/39952384-a60a98d0-55d8-11e8-9767-ae8cd677781b.png)

The "usage" section for `.reactionrolesremove` uses the example `.reactionrolesrm`, but that command doesn't exist.

**Comment by Seraraphu** [comment]
rero doesn't work with public nadeko afaik
