### ISSUE TITLE
.calc printing

### ISSUE THREAD

**Issue by Seraraphu** [Kwoth/NadekoBot#2293]
if you do .calc 'test' it'll print the text inside

another thing i found, not sure if its an issue
also using | is a bit weird, .calc 5|6 will give 7, .calc 2|6 will give 6 and so on, not sure if this is meant to be that way

**Comment by Macley-Kun** [comment]
I'm not so sure what you mean by

> if you do .calc 'test' it'll print the text inside

I would say that's correct. 'text' means you want to print the text (a string).

About the second part of your question, i'm not familiar with | in math. Anyone feel free to educate me on basic math 😛

**Comment by MaybeGoogle** [comment]
`|` is a bitwise operator for "or". Google it up.

And yes, kwoth didn't exactly code his own calculator... so 'test' outputs as 'test' :WeSmart:

**Comment by Kwoth** [comment]
Yea, | works fine, this string is just how it works, it can't be changed.
