### ISSUE TITLE
Stream notification keeps showing up

### ISSUE THREAD

**Issue by Bostolm** [Kwoth/NadekoBot#2294]
No matter how many times i disable the stream notifications, remove my stream and so on, she keeps on sending it, and at this point it doesnt make sense anymore

![image](https://user-images.githubusercontent.com/37375449/39960844-4e4dc002-562a-11e8-88b0-4325c08697a3.png)

**Comment by Kwoth** [comment]
How did you remove the stream? Using `twitch lobotomit` or using the link?

**Comment by Bostolm** [comment]
Tried every option i could find. As shown in the screen, shes saying im not following anything, but then she sends it anyway. Tested right now, send a notification again

**Comment by Bostolm** [comment]
I mightve just found out what happened. Apparently the invited bot kept posting that, but i never used the command with her. Of course i removed it all and she was still sending it, because i removed it from the hosted one. They have different prefixes, so i have no clue how it happened

**Comment by Kwoth** [comment]
Can't reproduce this anyway
