### ISSUE TITLE
Connect 4 doesn't have clear instructions on how to actually play

### ISSUE THREAD

**Issue by TheSpiderDungeon** [Kwoth/NadekoBot#2296]
The bot is is usually pretty helpful when using the help command, but connect 4 doesn't tell you how to play. No one in my server can figure it out.

**Comment by xnaas** [comment]
It seems pretty self-explanatory to me? It says whose turn it is and you simply type the number of the column you want to drop a piece in?

**Comment by TheSpiderDungeon** [comment]
If it was that easy we'd have figured it out, haha

Though I feel kinda dumb. I was using .4 instead of just 4
