### ISSUE TITLE
.repeatinvoke throwing NullReferenceExeption

### ISSUE THREAD

**Issue by StewieFellows** [Kwoth/NadekoBot#2299]
I have a self-hosted Nadeko (v2.21.2) where I have a single repeat message in my repeat list. I am attempting to use ".repeatinvoke 1" in the corresponding channel in order to get the message to appear and reset the timer. When I run this, I get a NullReferenceException with the following stack:

https://pastebin.com/pW3KPVNk

Note: The message wasn't correct in previous attempts of adding it, so I did add/remove it a few times before this point. 

Edit: moved stack into pastebin. Line breaks were messed up when pasting it in directly.

**Comment by Kwoth** [comment]
I either fixed it in 2.22 or can't reproduce.
