### ISSUE TITLE
Possible to delete bot response automatically?

### ISSUE THREAD

**Issue by griffinevans** [Kwoth/NadekoBot#2304]
I'm trying to set up my server so that new users can select one of a set of roles for themself. This is working fine, except that I want the bot to delete the confirmation messages sent after .iam is used, to prevent the channel from becoming cluttered. I'm using .delmsgoncmd to automatically delete user messages, but the bot replies remain, which is frustrating. Is there a way to automatically delete the bot's replies, ideally after a few seconds?

**Comment by Macley-Kun** [comment]
Suggest features
https://feathub.com/Kwoth/NadekoBot

Or ask our staff members in the NadekoLog server in the #help section!

**Comment by Kwoth** [comment]
@griffinevans Already exists. `.adsarm`
