### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by RJpapke** [Kwoth/NadekoBot#2307]
Alright I switched from a very old version I hosted on my PC to Debian server hosting.
Setting everything up while keeping the old data was pretty easy except for one thing which are user quotes. The only reason why I switched from the old version to the newest one, was because I wasn't able to manually add quotes in the DB using sqlite. I tried the same thing again on the current version and as it turns out it still doesn't work. The bot shows the single entry by ID (.quoteid 1) but can't select it by keyword "test". So afterwards I just wiped that one entry the table had (with DELETE FROM Quotes) and restarted the Bot.

And now the bot doesn't recognize ".." and "..." anymore. It simply shows nothing on console, .listquotes and all the other functions are still working. 
Is there a quick workaround to this problem? I somehow doubt that one INSERT/DELETE Statement can break this whole quote function. The bot is starting up with 0 issues/warnings after all and the db file is fine too.

**Comment by LunarSera** [comment]
if you kept the nadekobot.db file you can paste your old nadekobot.db into the new nadeko and everything will work again.

**Comment by Kwoth** [comment]
well you obviously messed something up and there is no way for us to know what.
