### ISSUE TITLE
Deleted message log bug

### ISSUE THREAD

**Issue by weslyv8** [Kwoth/NadekoBot#2311]
it won't log any deleted message anymore since a month or 2.
they then told me it would be fixed in a future update but still nothing...

someone who has a actual solution?

**Comment by shivaco** [comment]
Re-update or re-install your bot. All logs are working for me on v2.20.0.

**Comment by xnaas** [comment]
Ditto. Logs have been working since a few updates ago. All I did was disable and re-enable logging back when it was fixed and they've worked great since.
