### ISSUE TITLE
Bot Startup Issue [Windows 10 64bit]

### ISSUE THREAD

**Issue by KarsanHAM** [Kwoth/NadekoBot#2312]
Error occurs when executing NadekoBot.exe

Steps taken to get to error:
1 installed bot
2 filled in credentials according to windows startup guide
3 got the following error: 
![unknown error 1](https://user-images.githubusercontent.com/39461288/40279955-7dcd1d32-5c4c-11e8-9be8-a6058bba9b4f.png)
4 Fixed error by changing "0" in Credentials to proper owner ID.
5 Then the following error came up on start up attempt:
![unkown error](https://user-images.githubusercontent.com/39461288/40279982-c7bea802-5c4c-11e8-8d10-45f3de15829c.png)

Attempts made to fix error:
1. Restart Pc
2. Reinstall NadekoBot
3. Start up with Firewall Disabled
4. No Anti-virus installed
5. Caused by Discord?

Open to all suggestions
feel free to ask more information if needed.

Your help is greatly appreciated!!!

**Comment by senprime** [comment]
Updater will not launch on the Windows 10 Insider developer it seems like redis needs to be recoded for me.
