### ISSUE TITLE
currency awarding per role not capturing all users

### ISSUE THREAD

**Issue by RapthorneLightweaver** [Kwoth/NadekoBot#2313]
In my server (which is particularly large, 2500+ members) when using role based currency awards and trying to award @everyone, only about 1,060~ people will be awarded, despite using the @everyone role and having over double that number of people in the server.

This also happens with server-custom roles which have a large number of people in. I can tag a role, and not everyone who has that role will be found for awarding

**Comment by Kwoth** [comment]
Nothing i can do about this. People who are offline for a long time are invisible to the bot, she can't see them at all.
