### ISSUE TITLE
.remind bug

### ISSUE THREAD

**Issue by LunarSera** [Kwoth/NadekoBot#2314]
![discord_2018-05-20_18-51-52](https://user-images.githubusercontent.com/29496284/40284574-23d9e4d2-5c5f-11e8-8eab-c5dcfcdc14c7.png)

So when I send `.remind #channelname 1m test` , it give me the above error.
but when a mod sends it, they can use it just fine.
`.remind me` and `.remind here` work though

**Comment by Kwoth** [comment]
The message is misleading sadly, but i understand why it happens. In order to remind a channel you need to have manage messages permissions. However, since you don't, bot falls back to the normal use case, and sees that you didn't input the me or 'here' and it prints that error message.
