### ISSUE TITLE
Nadeko Bot fails to start

### ISSUE THREAD

**Issue by Firelion348** [Kwoth/NadekoBot#2315]
Anytime I try to run the bot, be it from the updater, or the application in Program Files, the bot fails to start. 
![image](https://user-images.githubusercontent.com/26208187/40287716-65cd82b8-5c7d-11e8-9a83-60997b9a6aa4.png)
![image](https://user-images.githubusercontent.com/26208187/40287729-7e77b70c-5c7d-11e8-87de-3d2f159d6ae6.png)
![image](https://user-images.githubusercontent.com/26208187/40287750-8fa027bc-5c7d-11e8-95d2-7439c0c0f599.png)
If it has any relevance, this is after updating to 2.22.0, then restarting my computer. Restarting the computer does not change this result.

**Comment by Kwoth** [comment]
if you're on windows, stop the bot, navigate to your redis installation location, there is a file called redis-cli

open it, type FLUSHALL and start the bot back up

**Comment by Firelion348** [comment]
After doing this process repeatedly, reinstalling and uninstalling pretty much all related software, it still failed to start. I now have another problem related to reinstalling Nadeko.
![image](https://user-images.githubusercontent.com/26208187/40870451-814440f2-65fd-11e8-84d6-3e8c1f625dbc.png)

**Comment by xnaas** [comment]
You should be at this location: https://nadekobot.readthedocs.io/en/latest/guides/Windows Guide/ unless something's changed...
