### ISSUE TITLE
401: Unauthorized

### ISSUE THREAD

**Issue by mstarbuck13** [Kwoth/NadekoBot#2316]
Bot worked before. Had to make some minor changes Discord side. Fixed the Token as needed. Now I am getting a 401 error. Discord API guys say this: 
![image](https://user-images.githubusercontent.com/19699010/40326663-1a1def56-5d0e-11e8-93bd-df6bf645ead6.png)

This is the error the command prompt is displaying: 
![image](https://user-images.githubusercontent.com/19699010/40326830-ac64b46c-5d0e-11e8-90b1-79fcf8fe0120.png)

Tokens are all corrected wihin the credentials file. I was experiencing connection issues to the Discord API webtool before, and was being forced to redo the captcha repeatedly, so I was questioning if that could be the issue but they disagree.

I am lost.

**Comment by MaybeGoogle** [comment]
Possible silly mistake, just checking: you are sure you used the token and not the secret, right?

**Comment by Kwoth** [comment]
401 unauthorized means you either didn't put your correct bot TOKEN (not secret) or your token got reset, so you need to generate a new one.
