### ISSUE TITLE
.rero

### ISSUE THREAD

**Issue by LunarSera** [Kwoth/NadekoBot#2317]
Attempting to `.rero Gamer :one:` doesnt seem to work, yet using other emojis do work. 
I havent extensively tested the default emojis but that one doesnt work for some reason.

**Comment by Gremagol** [comment]
You can only use your server's emotes.
![rero](https://user-images.githubusercontent.com/24619854/40384638-71a91d44-5e04-11e8-9b53-47d6be6b32fd.png)
