### ISSUE TITLE
%user% Mention Always User ID

### ISSUE THREAD

**Issue by TwinDragon** [Kwoth/NadekoBot#2319]
This has been going on the past day or so now, using the latest commit currently on the bot.

https://cdn.discordapp.com/attachments/317197568926810112/448276320183517198/unknown.png

At the moment, I can't pin it down to a specific cause. I tried it using the web client briefly to join a couple servers I'm in with the bot and a welcome message set, but doesn't appear I can reproduce it at the moment. I tried watching it while in the channel, and also tried looking in another channel, then flip to where the welcome message is and still didn't trigger it.

I know sometimes this could happen if someone were to join and immediately leave the server, but that doesn't seem to be the case here. Nothing is showing up on the console either, so I'm not sure what's really going on currently.

**Comment by shivaco** [comment]
Blame the new `Lazy Load` feature implemented by **Discord developers**. The user is not loaded in cache properly, which causes the mentions to be shown as IDs.

**Comment by TwinDragon** [comment]
Oh, is that what it is? Wow..

**Comment by Kwoth** [comment]
Yes, nothing we can do about it, someone else reported it and Stan (discord dev) said that was never supported. %user.mention% should work properly in plain_text field though.
