### ISSUE TITLE
.reactionroles limit of 5 question

### ISSUE THREAD

**Issue by casmbu** [Kwoth/NadekoBot#2321]
Is there a (technical or otherwise) reason the reactionroles are limited to 5?

**Comment by LunarSera** [comment]
bot lag. on public nadeko, its in like 80,000 servers. if each server used it, it would lag the hell outta the bot

**Comment by casmbu** [comment]
could it be a setting then?

**Comment by LunarSera** [comment]
yeah, anything can be edited with the bot. but I dont know how to edit the source code. sorry

**Comment by MaybeGoogle** [comment]
Rero is disabled on public nadeko, but on any big selfhost, rero would likely kill the bot.

It's a source edit to change the limit atm. Go to https://feathub.com/Kwoth/NadekoBot to request changes.

**Comment by Kwoth** [comment]
Bot has to add those reactions to the message, that's the main reason. Adding 5 seemed like a nice number that doesn't take too long. Imagine if you had 20, it would take far too long to add them all to the message, and idk how devs would feel about the bot spamming reactions on messages.
