### ISSUE TITLE
No spacers in some command outputs.

### ISSUE THREAD

**Issue by lessvoice** [Kwoth/NadekoBot#2322]
I am not sure if this is a potential bug, but some outputs from the bot do not contain a space between the text and the emoji.

Here are some examples:
![example 1](https://user-images.githubusercontent.com/38194726/40448551-22f1b0da-5ed6-11e8-9a18-cb1c15f455fc.PNG)
![example 2](https://user-images.githubusercontent.com/38194726/40448556-260bbbe4-5ed6-11e8-8f75-df930db91f77.PNG)

**Comment by Kwoth** [comment]
It's not
