### ISSUE TITLE
Cleverbot possibly down

### ISSUE THREAD

**Issue by DukeFerret** [Kwoth/NadekoBot#2323]
Been getting the same error message any time i attempt to run the cleverbot functions from my self hosted version of Nadeko. Have attempted a restart, but still getting it. Has been taking place for the last 12 hrs at least.
![screenshot_12](https://user-images.githubusercontent.com/39598529/40501606-99916e28-5f45-11e8-8cd7-2b95ff3d6028.png)

**Comment by shivaco** [comment]
Not an issue with Nadeko specifically. Blame Program-O for the error.

**Comment by DukeFerret** [comment]
Ill have to wander over to them and poke around then.

**Comment by Macley-Kun** [comment]
@DukeFerret you can refer to this issue, might direct users to the right place.

**Comment by senprime** [comment]
How about blaming yourselves for being pseudo Developers creating cancerous code
