### ISSUE TITLE
Is there a way i can reset my settings in Nadeko?

### ISSUE THREAD

**Issue by GoodBignoah1234** [Kwoth/NadekoBot#2324]
I want to reset all my settings back to default, but I can't seem to find out how anywhere. Is there a way to do this?

**Comment by senprime** [comment]
Don't quote me on this but I'd imagine you regenerate a token for it or just use the commands and default value.

**Comment by Kwoth** [comment]
Pleas post this on feathub, it's a feature request. But yes, you can just delete NadekoBot.db file.
