### ISSUE TITLE
Quote commands break if default prefix is set to a single quote

### ISSUE THREAD

**Issue by seanieb64** [Kwoth/NadekoBot#2325]
If the defprefix is set to a "'" Nadeko cannot perform any quote tasks other than adding a quote,

the "..." or "'.." command doesn't work at all
the ".." or "'." command produces a too few parameters error in console.

``0 00:02:41 CommandHandler | Command Errored after 0/0/0s
        User: seanieb#6464 [141321435103756288]
        Server: Stasia and Joshy's Funland~! [179065904468852736]
        Channel: bot [181999562561552384]
        Message: '. Stasia
        Error: The input text has too few parameters.
``

**Comment by Kwoth** [comment]
I think you got it confused.

`..` and `.` are the real names of the commands.

if you have a prefix `.` then it becomes 
`...` and `..` for show and add

So if you have a prefix of `'` the commands are
`'..` and `'.`
