### ISSUE TITLE
Tagging a role in .aar occasionally causes it to not operate

### ISSUE THREAD

**Issue by zergling-man** [Kwoth/NadekoBot#2326]
A server in which a role called "new" exists and is taggable. (Role ID for reference: 449839136623558659 )
Public Nadeko, 2.22.0.
Running `.aar @new` causes the bot to report that auto-assign is enabled, but doesn't actually apply the role upon a new user joining.
Running `.aar new` behaves normally.

In a test server, with a role called "blep", both tagging it and just specifying the name works.
Also, a self-hosted clone, also on 2.22.0, behaves correctly in the test server.
In the test server, with a role named "new", tagging it works with public Nadeko but does not work with the clone.
(Note that all tests were conducted with bot accounts.)

There seems to be some really obscure interaction at play here, between the role's name, the structure of the mention, and... Something else?

**Comment by senprime** [comment]
Your're Squirrel Shell hosted Discord Update just got exposed. GG.

**Comment by senprime** [comment]
System.IO SMH. Been reported to numerious US security developers in team with Discord.

**Comment by senprime** [comment]
I can't wait to see how much money you guys owe me

**Comment by Kwoth** [comment]
It's just some weirdness either caused by the local bot, or some server settings, it's the same codebase regardless of whether you mention the role or not.
