### ISSUE TITLE
DailyCurrencyDecay rounding error

### ISSUE THREAD

**Issue by MC4lio** [Kwoth/NadekoBot#2332]
Daily currency decay has a rounding error for people with 0 currency. They will have 1 after the DB update.
```csharp
public void CurrencyDecay(float decay, ulong botId)
{
    _context.Database.ExecuteSqlCommand($@"
    UPDATE DiscordUser
    SET CurrencyAmount=CurrencyAmount-ROUND(CurrencyAmount*{decay}-0.5)
    WHERE UserId!={botId};");
}
```
Probably fixed with: ```WHERE CurrencyAmount!=0 AND UserId!={botId}; ```. No need to decay 0 currency.

**Comment by zergling-man** [comment]
https://msdn.microsoft.com/en-us/library/3s2d3xkk(v=vs.110).aspx
```
If the fractional component of d is halfway between two integers, one of which is even and the other odd, the even number is returned.
```
`a-round(a*d-0.5)` for any `a=0` -> `0-round(0*d-0.5)` -> `0-round(-0.5)` -> `0-0`. Is Nadeko using a modified round function?
