### ISSUE TITLE
No .autocmdrm command

### ISSUE THREAD

**Issue by rjt-rockx** [Kwoth/NadekoBot#2334]
There's a command to add autocmds, one to list autocmds but none to remove autocmds.
If you mess up any autocmd, it keeps repeating and looping it endlessly with no way to fix it but to stop the bot and edit it out manually. 
[Here's an example of the issue.](https://i.imgur.com/JHELym5.png)

**Comment by Gremagol** [comment]
I thought you remove them with `.scrm` 🤔

**Comment by MaybeGoogle** [comment]
Put a possible solution in https://feathub.com/Kwoth/NadekoBot/+585

Text:
Proposed solution for issue [#2334](https://github.com/Kwoth/NadekoBot/issues/2334)  
Idk if this is a good solution, but heres an idea:  
  
- Combine `scadd` with `autocmdadd` into `selfadd`, with an argument specifying which type to add.  
- Combine `sclist` with `autolist` to `selflist`, either with some emote (🔁and 1️⃣for example) showing which type it is or splitting it into two sections.  
- Rename `scrm` to `selfrm`.  
- Rename `scclr` to `selfclear`, with argument specifying type or all.  

The main idea is to combine autocmds and startupcmds into selfcmds
