### ISSUE TITLE
Image Missing on .stats

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#2335]
On both public Nadeko and self-hosted versions of Nadeko, the image is missing/broken for `.stats`:

![image](https://user-images.githubusercontent.com/8271327/40789979-56430a2c-64b9-11e8-8b7a-f5393485d7e4.png)

![image](https://user-images.githubusercontent.com/8271327/40789995-5e985b3c-64b9-11e8-98f3-1f4120058231.png)

If you right-click the missing image and "Open Link" it will take you to `https://images-ext-1.discordapp.net/external/Nt7-TlGfBwIXZfH_FsQBlbEk64tnOxN9GqvuEjUVtL0/https/cdn.discordapp.com/avatars/116275390695079945/b21045e778ef21c96d175400e779f0fb.jpg` which is super dead.

**Comment by SillyBirds** [comment]
Kinda related, but the same thing happens to the `.xkcd` response:


![image](https://user-images.githubusercontent.com/22528910/40873802-772de374-6667-11e8-80a3-774bc1870323.png)

**Comment by xnaas** [comment]
This bug appears to still be present in 2.24.2.

![img](https://xnaas.info/img/LowOriginalVervet.png)
