### ISSUE TITLE
.meow command is not working

### ISSUE THREAD

**Issue by Kaoticz** [Kwoth/NadekoBot#2336]
Bot hosted on Amazon AWS, OS is Ubuntu 16.04.4 LTS
Nadeko version is 2.22.0

This is what I get in the console.
![meow](https://user-images.githubusercontent.com/1812311/40796344-31a8c8e2-64db-11e8-8fc6-2c9e827da98f.png)
.woof command works just fine.

**Comment by shivaco** [comment]
Same error on my self-hosted Nadeko instance.

**Comment by xnaas** [comment]
![image](https://user-images.githubusercontent.com/8271327/40796802-dc6e32c2-64cb-11e8-9ce1-9c0123c93496.png)

Working for me, FWIW.

**Comment by Kaoticz** [comment]
Might be a specific issue on the Linux version then? The console complains about something in the "Searches.cs" file, line 266.

**Comment by TwinDragon** [comment]
Works fine for me on a self-hosted Debian 9 tower in my room.
![discord_2018-05-31_21-48-23](https://user-images.githubusercontent.com/4114117/40818468-b8efbe0a-651c-11e8-93a4-6e9c83759605.png)

**Comment by FurkanKambay** [comment]
https://github.com/Kwoth/NadekoBot/blob/5ff70d462cfb7c0db2ecd27982e2307101fa4b53/NadekoBot.Core/Modules/Searches/Searches.cs#L266

According to the screenshot, the HTTP request resulted in a 403 response:
https://i.imgur.com/VJ1eyZM.png

**Comment by Kaoticz** [comment]
Hey, just updated my bot to test another issue and I noticed your commit has resolved the issue. Thanks man, now I can spam cats with no issues and it doesn't return any errors in the console :)
![discord](https://user-images.githubusercontent.com/1812311/40896131-bc72b9fa-6789-11e8-8ad7-53fc37489bab.png)

**Comment by Kaoticz** [comment]
What the hell? So you're telling me the service Nadeko uses to get cat images is randomly malfunctioning, even though it was returning a valid link in my web browser, but a 403 error in Nadeko's console at the same time? That makes even less sense.

No, there was no error on Discord. Nadeko simply didn't react to the command in Discord. In the console, it returned that massive error you saw in the original post.

The command is working properly now. Now I have no idea why, as you stated your commit wasn't supposed to fix it. This is what I get now.
![discord](https://user-images.githubusercontent.com/1812311/40898944-91442e92-679a-11e8-94b6-c3f817ab7986.png)

**Comment by Kaoticz** [comment]
What a sad coincidence. That means the command is probably going to malfunction again eventually.

**Comment by FurkanKambay** [comment]
@Kaoticz Yep. It might have been just a one-time thing, though. Either way, there is nothing more for us to do.

**Comment by Kaoticz** [comment]
@FurkanKambay I see. Thank you for taking your time to look into this.
