### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Denizzje** [Kwoth/NadekoBot#2345]
After updating the bot, I get this error on startup and the programme closes: https://imgur.com/a/8ukcSNj

It has actually been a while that it has broken, and it happened after an update a while ago. Meanwhile I updated it again it still doesnt work. Reddis is running according to the updater screen.

What can I do to revive my bot from the dead?

**Comment by Macley-Kun** [comment]
Tried backing up db and config files, removing bot completley, re-install it. And then put the backed-up files back and restart again?

**Comment by Denizzje** [comment]
Hmm, I think I have already attempted to reinstall the bot before, but why not give it a try again. It is my local computer where I am also on Discord on just fine. 

I havent taken a look at the tokens, I kept them the way it is since installing. So that is also something to look into then. ;)

**Comment by Kwoth** [comment]
Yea it's simply something wrong with your connection, antivirus, firewall, or anything of the sort.
