### ISSUE TITLE
No offline stream notification

### ISSUE THREAD

**Issue by SillyBirds** [Kwoth/NadekoBot#2346]
As of late, the bot has stopped showing when a stream goes offline. The stream start notification works fine though.<br>
<br>
Console doesn't show any error (05h45 being the stream start and 06h35 when it stopped):<br>
```
0|Nadeko`   | 0 05:42:19 StreamNotificationService | Retreived and published stream statuses in 1.21s
0|Nadeko   | 0 06:35:58 StreamNotificationService | Retreived and published stream statuses in 0.23s
```

**Comment by shikhir-arora** [comment]
This is intended as of a while ago, AFAIK. Have you tried `.streamoffline`?

**Comment by SillyBirds** [comment]
Oh, I wasn't aware of that change. There's chance it's that . I'll give it a try, thanks.
