### ISSUE TITLE
shard 0 scheduled for a restart

### ISSUE THREAD

**Issue by LunarSera** [Kwoth/NadekoBot#2348]
```0|Sanae    | -1 19:13:05 ShardsCoordinator | Shard 0 is scheduled for a restart                                                                                                                                                              because it's unresponsive.
0|Sanae    | -1 19:13:06 ShardsCoordinator | Auto-restarting shard 0```

So My bot has been doing this about once a day for the last month or so. I'm wondering what is causing this? it only happens on one of my bots, the other 4 Nadeko's that I host have no issues. as a matter of fact, the one has been online for 19 days so far.

**Comment by shikhir-arora** [comment]
You running the latest version? That shouldn't happen on any recent version, unless there's some issue with resources or something. How many bots are you hosting? Not sure how it works with them both polling redis.

**Comment by LunarSera** [comment]
I'm running 2.23.0 on 3 different bots, 2.17.1 on another bot and 2.22.0 on another. It's Ubuntu through digital ocean.

**Comment by shikhir-arora** [comment]
1. Is the bot you're running that's having issues an old version?

2. What's the output of `free -h` on your server?

**Comment by LunarSera** [comment]
sam@sera:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.9G        1.9G        320M        126M        1.7G        1.6G
Swap:            0B          0B          0B

It looks like you are on to something, I may need even more ram. bummer

**Comment by shikhir-arora** [comment]
Yeah, common issue with redis, as it's in memory store. It's 99% that, unfortunately all you can do is get more memory. It's common with many apps that use redis to get OOM (out of memory) errors if you aren't watching 🙃

**Comment by LunarSera** [comment]
it says I have 1.9gb of ram available though. isnt that good?

**Comment by shikhir-arora** [comment]
Run the bot that has issues, make sure it's latest version, and not using any custom settings in the credentials file. If it keeps doing it check memory and report back.

**Comment by LunarSera** [comment]
My bot just randomly restarted again for no apparent reason. Same as before. Shard 0 is unresponsive. It's been about 4 days since it's done it. The ram usage is about 2.1gb out of 4gb

**Comment by LunarSera** [comment]
it kinda looks like when people spam customreactions, it causes my bot to lag out and restart itself. could that be the issue?

**Comment by xnaas** [comment]
This has started to happen to me recently as well. It's usually while everyone is asleep and the bot isn't even in use.

My guess is it's just a temporary loss of connection to Discord for whatever reason.

**Comment by LunarSera** [comment]
It's been 14 days and the bot finally restarted again. I'm assuming that it doesnt have anything to do with my memory usage at this point.

**Comment by Macley-Kun** [comment]
@LunarSera Keep an eye on it for 3 more days. If everything is still fine i.g. the issue would be resolved from itself?

**Comment by LunarSera** [comment]
It restarted yesterday, I didnt write a comment here about it though

**Comment by Macley-Kun** [comment]
Was it scheduled or? Like related to the issue or? Was there a error?

**Comment by Macley-Kun** [comment]
Looking a bit back into this issue, but have you tried re-making a new vps on digital ocean?

Sometimes re-installing it completley should resolve all issues related to the specific machine. But that's all i can give you. As most common solutions don't seem to have effect 🤔

**Comment by LunarSera** [comment]
I don't have that luxery because there are tons of programs set up on it including a game server

**Comment by Macley-Kun** [comment]
Mhm.. and a partial re-install would-be help ether..

What happens when you build another nadekobot, and see if it behaves better. If so you can then discard the one that’s now partial working.

**Comment by LunarSera** [comment]
Only one of my nadeko's does it. I have 4 running.

**Comment by Macley-Kun** [comment]
Ik, but what happens when you add another bot. If 3/4 work, maybe adding another one will work better then the faulthy one.

If that's the case, you simpley remove the that's faulthy, and you have 4 working nadeko's.

**Comment by LunarSera** [comment]
The one that is faulty is in 75 servers. I'm not going to just delete it. I'll wait for kwoth or someone else with more common sense to reply here.

**Comment by Macley-Kun** [comment]
I try to explain to you that you can add another’s bot, test and see if it works better.

And if it is better. That you can then move from the faulthy one to The new one. Moving is then just editing the token from that point. And no point you ever have to delete or risk the faulthy one.

**Comment by Kwoth** [comment]
It's fine as long as it comes back normally. No idea why it may happen.
