### ISSUE TITLE
"~e621" command broken in Mono

### ISSUE THREAD

**Issue by coggy9** [Kwoth/NadekoBot#235]
![kppsqux](https://cloud.githubusercontent.com/assets/352207/14793135/3d806fac-0ae3-11e6-8ef6-734025b68e51.png)
Windows gets a 403 error, so that likely isn't Nadeko's fault, but Mono/Linux adds the folder the app is in when trying to find the XML file. Not sure how to go about fixing that.

**Comment by Bang0123** [comment]
Gives me the same error on windows

**Comment by Kwoth** [comment]
e621 seems completely broken now.

@Gaboer is looking into it i blieve

**Comment by Gaboer** [comment]
Apparently someone messed up E621's api

Friend of mine has posted on official forums trying to see what's going on.
Adding a chrome/mozilla/applewebkit user-agent alleviates the issue, still continuing to look into it

**Comment by Kwoth** [comment]
Should be fixed in the **upcoming** release. If it isn't, reopen the issue.
