### ISSUE TITLE
Nadekobot doesn't open

### ISSUE THREAD

**Issue by missyaoibl** [Kwoth/NadekoBot#2350]
I'm trying to open Nadekobot.exe but it crashes before it even opens.
The Nadekobot.db never have created itself...

What I can do?
Thank you.

**Comment by xnaas** [comment]
You followed [the guide](http://nadekobot.readthedocs.io/en/latest/guides/Windows%20Guide/) step-by-step and didn't miss ***anything***?

**Comment by missyaoibl** [comment]
Yeah. I did step-by-step. So, yesterday it wasn't even opening. But today, for some reason, I uninstalled and reinstalled and it worked fine. Very strange. Anyway, thanks though.
