### ISSUE TITLE
Repeat commands not working in one server

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#2351]
Not disabled in `.lp`, shows up in `.cmds util`  
Public Bot.

Was working up until ~ 30 hours ago
Created May 2 (not sure if this is old repeat or new repeat)

sid: 385956732888678402

**Comment by Kwoth** [comment]
Lets move this to discord :P

**Comment by MaybeGoogle** [comment]
Err it wasn't my server but I tried p much everything with them. Based on GitHub, though, probably just them having the problem.
