### ISSUE TITLE
A way to self host nadekobot 24/7

### ISSUE THREAD

**Issue by missyaoibl** [Kwoth/NadekoBot#2352]
I don't know if there is a way to self host nadeko in my computer and let her run 24/7. I mean, everytime I turn off my computer it goes offline, right?

So there is a way to make it run, even after I turn off my computer?
Thank you.

**Comment by Macley-Kun** [comment]
You can better ask these types of **questions** in then #help in the Nadekolog server.

If you want to have it 24/7 you could use a vps (a server/computer/virtualmachine in the cloud/external). Think kwoth has a link where you get 5$ Extra if you use his link. He also gets a tip from it what is nice.
