### ISSUE TITLE
.xp unable to generate an image

### ISSUE THREAD

**Issue by aPyon** [Kwoth/NadekoBot#2356]
Hey I just freshly installed Nadeko bot on OS X and I came across a problem with the .xp function:

https://pastebin.com/uz95hLS5

My .NET is on version 2.1.300 and everything is pretty much up to date, however Nadeko seems to be having problems generating an image for .xp

Is there any way to resolve this issue?

**Comment by Kaoticz** [comment]
Mine is working fine. Ubuntu 16.04.4 LTS
![discord](https://user-images.githubusercontent.com/1812311/41210347-7ecaa03a-6d07-11e8-834b-3d6e6f19b536.png)

Do you get the same error by running other commands that creates images as well, like `.slot` ?

**Comment by xnaas** [comment]
Thanks for posting the solution before closing! 😄
