### ISSUE TITLE
Reaction Roles

### ISSUE THREAD

**Issue by StevenKvodo** [Kwoth/NadekoBot#2357]
I've had a reaction roles message with 6 rero on it, I needed to add another one with 8 reactions
After doing so the bot sent me this message:
![screenshot_2](https://user-images.githubusercontent.com/40173191/41235853-5d6c1b6c-6d98-11e8-9ee9-3aa5e22c6ef7.png)
I wondered if there's a way to raise the limit?
I'm self-hosting the bot.

**Comment by Kwoth** [comment]
If you are running from source, you would have to edit line 163 in RoleCommandsService (from 5 to any number you want)
