### ISSUE TITLE
.gvc behavior

### ISSUE THREAD

**Issue by Kaoticz** [Kwoth/NadekoBot#2365]
Currently, the `.gvc` command automatically redirects users that join the game voice channel to the voice channel with the name of their current game, if it exists. However, that only works for users that join the gvc while their game is running. If someone joins the game voice chat THEN runs the game, the bot won't redirect them to the appropriate voice channel. I'm not sure if it's a bug or intentional, but it's not intuitive and also kinda renders the command useless. I believe it should make any user running a game in the gvc get automatically redirected to the appropriate voice channel, regardless if the game was launched before or after the user joined the gvc.

Additional tweak (or perhaps a new command): allow the bot owner to set users running a specific game to be redirected to a specific voice channel. That way, voice channels will not be required to have the exact same name as the game being run by the users.

**Comment by shikhir-arora** [comment]
Just to your first point, it's kind of impractical. If a user has a game set that has a voice channel, and joins the game voice channel, Nadeko can read the user's game and direct them accordingly. But in your case it would involve polling the users game on a schedule and keep track of their presence in the game voice channel. That's a lot of overhead, and I think the point was to have a quick way for users playing a game to be able to jump to a channel full of other users with that game, not queue in the channel and move when their game is set. It's doable - but a pretty heavy overhead to keep track of users statuses and games in that channel - especially if it's a big guild that uses that feature.

**Comment by Kaoticz** [comment]
That's a good point, but wouldn't that mean commands like `.streamadd` and `.twitch` would face the same problem/limitation? Yet they work fine and don't seem to cause heavy workload issues.

**Comment by shikhir-arora** [comment]
Sort of, except you have to poll a user and also keep track of when they leave. It's not something on a defined interval as the user can change their game anytime and also leave the channel. So it requires a lot more checks, but it's possible, sure. Just seems like it can cause issues for several reasons

**Comment by Kaoticz** [comment]
Would having larger intervals for the check help? Because I don't think there is any need for the users to get immediately redirected. The checks for the user's status and departure are unavoidable though. Would these checks themselves be enough to create a breeding ground of issues and bugs?
