### ISSUE TITLE
Club Hierarchy

### ISSUE THREAD

**Issue by Kiyoshi1412** [Kwoth/NadekoBot#2366]
So apparently, club admins doesn't have any hierarchy. Beste, Hatsu, Shivaco and I were there when we tested it. Beste and I are admins (Loli Society.. reeee) and we are still able to kick and ban each other :retardeyes:. Not only that, admins are also able to ban and kick themselves (leaving club in style much?). Kwothy, please fix :retardeyes:

**Comment by Macley-Kun** [comment]
@kwoth mark as bug?
