### ISSUE TITLE
.leave not working

### ISSUE THREAD

**Issue by hemiipatu** [Kwoth/NadekoBot#2367]
It seems as though the `.leave` command doesn't work when the message comes from a server and will only work when privately messaged to the bot. 

Is this deliberate or a bug?

**Comment by LunarSera** [comment]
Are you the bot owner?

**Comment by Kwoth** [comment]
Hm, ok this needs improving. leave will only work if the server you want to leave is on the same shard. I will fix that in the next patch

**Comment by hemiipatu** [comment]
Sorry for the late replies here: Yes I am the bot owner @LunarSera and nice one @Kwoth thanks again! 👍
