### ISSUE TITLE
.slowmode command does not say anything when its already disabled, giving an error on console

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#2368]
![1](https://i.imgur.com/k5gYGJ2.png)
No response. This error in console. Happens in every server, Selfhost, v2.23.0

**Comment by Kaoticz** [comment]
Aren't you supposed to use that command with the `-s` and `-m` options?
For example, doing `.slowmode -s 10 -m 5` means that users won't be able to send more than 5 messages every 10 seconds. I don't think `.slowmode` is going to work without these options. But I might be wrong, so take my word with a grain of salt.

**Comment by Midoriin** [comment]
You are able to use it with no parameters, which is supposed to disable slowmode if enabled, or inform its already disabled. But when its already disabled, it doesnt give any response, is just giving an error on console.

**Comment by Midoriin** [comment]
Excuse me for not clarifying the situation enough at first.
