### ISSUE TITLE
Not messaging owner if  bot is offline

### ISSUE THREAD

**Issue by Area45** [Kwoth/NadekoBot#2369]
I run Nadeko off my Computer and can't leave my computer running all the time. I like to have people message nadeko to so the Moderaters of my discord get messaged too.

The issue is if someone messages the bot when it is offline, it doesn't check for new messages when coming back online so the Owners don't get messaged.

Would be nice if the bot would send all New Messages to Owners when it starts back up.

**Comment by xnaas** [comment]
https://feathub.com/Kwoth/NadekoBot

Also, not even sure that's possible, but idk the bot API limitations.

**Comment by Kaoticz** [comment]
I'd be easier to host the bot somewhere so it never goes offline.

**Comment by xnaas** [comment]
What @Kaoticz said. If you can't leave your own PC on forever, you should look into the plethora of VPS options out there, @Area45.
