### ISSUE TITLE
Bot suddenly stopped working

### ISSUE THREAD

**Issue by neoDemi** [Kwoth/NadekoBot#237]
Tried to open the bot earlier and got this response, followed by the program crashing anytime I opened it.

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Discord.Net, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at NadekoBot.NadekoBot.Main()

wat do

**Comment by Kwoth** [comment]
try reinstalling

**Comment by Kwoth** [comment]
Any new info on this?

**Comment by neoDemi** [comment]
I reinstalled it using the video tutorial you guys had up, but same thing happened after restarting my computer

**Comment by tg44** [comment]
operating system? is the path has special characters? (öüóúőű etc.) Are you using some type of security/virus detection software? In the bot directory is there a Discord.Net.dll or sth like that?

**Comment by vSwifty** [comment]
Just had this error and solved it by running nadekobot.exe as administrator.

I think the problem for me was lack of perms to my c: drive so the bot couldn't access ffmpeg.

**Comment by Kwoth** [comment]
@neoDemi did you manage to resolve the issue?

**Comment by neoDemi** [comment]
No, I've tried all these and nothing is working

**Comment by Kwoth** [comment]
something is deleting your discord.net.dll folder. It could be antivirus.
