### ISSUE TITLE
React event isn't working.

### ISSUE THREAD

**Issue by StevenKvodo** [Kwoth/NadekoBot#2371]
So a few days ago I was using the .eventstart reaction, and it worked, now when I do it the message appears with the reaction, but adding a reaction will not give you the money. Is there any way I could fix that?
![screenshot_7](https://user-images.githubusercontent.com/40173191/41783727-473ee354-7646-11e8-9d8d-bb7a41be6ae3.png)

**Comment by xnaas** [comment]
Is the money awarded after the timer runs out?

**Comment by Kwoth** [comment]
Maybe you hae too much money, I don't know :P Can't reproduce, works fine.
