### ISSUE TITLE
Nadeko flowers on an Unknown#????

### ISSUE THREAD

**Issue by Sonfa** [Kwoth/NadekoBot#2375]
We were messing with the gambling section of the commands and then now we have this

http://prntscr.com/jywh6z

We gave everyone flowers and then we took them away 1 by one. Except for Unknown#????

Is there a way I can reset them or can I manually change this Unknowns flowers?

**Comment by xnaas** [comment]
There's a command for resetting currency. You could also delete the offending person from the database.

**Comment by Sonfa** [comment]
Thanks for the reply, I would like to use a reset command but I do not see one on the Nadeko commands website. Could you perhaps tell me the command to do so?

**Comment by xnaas** [comment]
It's the very last command in the XP section on https://nadekobot.me/commands `.xpreset`

**Comment by Sonfa** [comment]
Thanks for the reply, I would like to use a reset command but I do not see one on the Nadeko commands website. Could you perhaps tell me the command to do so?
