### ISSUE TITLE
NSFW not working, even though I enabled it.

### ISSUE THREAD

**Issue by coolchipsbros** [Kwoth/NadekoBot#2376]
Pretty much as the title says.

**Comment by PotatoGaming2079** [comment]
Instead of posting here, please go to the Nadeko support server and ask for help there.  (https://discord.gg/sFvgeFG) <--- Server Invite. I'd be happy to assist you in the Nadeko support server. See you there.

**Comment by Kwoth** [comment]
You can only use nsfw in nsfw channels.
