### ISSUE TITLE
remind missing info/error

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#2380]
`.remind` seems to have a limit of 2 months. I'd love for the limit to be increased, but regardless:

* `.h .remind` should mention the limit.
* https://nadekobot.me/commands should mention the limit.
* When trying to set a reminder past the allowed time limit, a warning or response should be posted in chat. Something like "The max remind limit is X months, please try again."

**Comment by Kwoth** [comment]
I fixed this in the last patch.

**Comment by xnaas** [comment]
Sweet, thanks @Kwoth. 👍
