### ISSUE TITLE
Nadeko has been offline for a few hours. 

### ISSUE THREAD

**Issue by 1Loredana** [Kwoth/NadekoBot#2381]
I'm using the public nadeko. It's been offline for a few hours and I'm trying to set up server commands.

**Comment by xnaas** [comment]
This is not what GitHub is for. This is for reporting issues with self-hosted bots and bot code.

I'm sure everyone on the help server is already aware but anyone who can fix it is either busy or asleep.

**Comment by 1Loredana** [comment]
Ah okay. Sorry! I'll delete this if possible then.

**Comment by xnaas** [comment]
There should be a "Close" button somewhere. 😄

**Comment by xnaas** [comment]
And no worries. I understand the frustration with the bot being down. That's why many of us self-host. 😉

**Comment by 1Loredana** [comment]
I can't really self host because I don't use discord on my computer, so I'm kind of forced to use the public nadeko. Heh. 🌸
