### ISSUE TITLE
[Feature Request] Pokemon info screen

### ISSUE THREAD

**Issue by Glazelf** [Kwoth/NadekoBot#2383]
Like waifuinfo, but showcasing someones type, remaining hp out of max hp, movelist, and maybe if their open for attacks from the person who issued the command.

**Comment by xnaas** [comment]
https://feathub.com/Kwoth/NadekoBot

**Comment by Kaoticz** [comment]
If you want stats for Pokemon in general, that's what the `.poke` command is for.
If you want stats for a user's Pokemon, suggest that on the FeatHub link above.

**Comment by Kwoth** [comment]
Pokemon is going to get a rework, hopefully soon.
