### ISSUE TITLE
Self Hosted - Responding twice

### ISSUE THREAD

**Issue by tigerdesignsolutions** [Kwoth/NadekoBot#2385]
Since the bot updated today it's been replying twice to everything.

![screenshot_1111](https://user-images.githubusercontent.com/18332675/42106595-6ee6192a-7b89-11e8-8eb0-bf75b85bd082.png)

**Comment by xnaas** [comment]
What's the response to `.stats`?

**Comment by tigerdesignsolutions** [comment]
Solved it on my own. I had two processes of the bot running.
