### ISSUE TITLE
Remove previous role on level up

### ISSUE THREAD

**Issue by E-v-o** [Kwoth/NadekoBot#2386]
Hi there,

Would it be possible to have an option to remove the previous role given for leveling up? I've got level tags at the minute, aka level 1, level 2 and the bot gives them out perfectly fine, but the user ends up having a bunch of tags, if it could check for example if (level >=2) then remove previous levels tag that would be super handy!

**Comment by Macley-Kun** [comment]
https://feathub.com/Kwoth/NadekoBot
^close issue. Ask here. Ask friends to upvote so your suggestion will be implemented!
