### ISSUE TITLE
.nsfwtagbl not blacklisting tag

### ISSUE THREAD

**Issue by Koutomi** [Kwoth/NadekoBot#2387]
Version: | v2.23.0
------------ | -------------
Type: | self-hosted
OS: | Windows

When I asked about my issue on the server I was asked to report it here. I am the bot owner.

I blacklist the tag and it says it blacklists and the console looks normal.

I do the command on its own to see what tags are blacklisted, and the one I have blacklisted does show up, console looks normal.

Any member of the server can type `.hentaibomb Blacklistedtag` and get a full thing of results like normal.

**Comment by Kaoticz** [comment]
I have the same issue.
**Nadeko v2.23.0**
**Ubuntu 16.04.4 LTS**
![nsfw](https://user-images.githubusercontent.com/1812311/42183668-1ea369bc-7e19-11e8-9940-9554e7e438c8.png)

**Comment by Kiyoshi1412** [comment]
I tested it earlier, it seems to be working just fine on v. 2.23.0 Ubuntu 16.04.

**Comment by Koutomi** [comment]
After some time it does seem to be blocking the tag.

It would not do it right away. I have not restarted two of the bots I am also testing it on and they are blocking it now too. I suppose the solution is to wait for a while?

**Comment by Koutomi** [comment]
@Kaoticz Have you tried it again recently? Also maybe give it a restart then try?

**Comment by Kaoticz** [comment]
The issue persists for me. I haven't restarted the bot yet, though.

**Comment by Kwoth** [comment]
@Koutomi your comment 'maybe the solution is to wait a while' made me realize the problem. The problem is that bot only filters the images while loading them to the cache. which means that if you use a certain tag, bot will load 100+ images to the cache with that tag, and then when you blacklist the tag, bot will still use the cahced images until it spends them, and when it does, next time it gets more images of the same tag from the server, it will filter them out, throwing away the ones that don't have the proper tag.

**Comment by Koutomi** [comment]
So the solution is to spam the blocked tag in a hidden channel until nothing comes up?

**Comment by Kaoticz** [comment]
If that's the case, `.nsfwcc` should do the trick. Let me test it out.

**Comment by Kaoticz** [comment]
Yes, that seems to be exactly the case, @Kwoth @Koutomi 
Reproduction in the prints below
![nsfw](https://user-images.githubusercontent.com/1812311/42290395-6199bc52-7f9b-11e8-9d6e-aeb84f5b5f6a.png)
![nsfw2](https://user-images.githubusercontent.com/1812311/42290401-65b1d5cc-7f9b-11e8-8d00-46779779a3c7.png)
![nsfw3](https://user-images.githubusercontent.com/1812311/42290405-69565c70-7f9b-11e8-9c3f-e6145516d3a9.png)

**Comment by Kwoth** [comment]
@Koutomi no that's not a solution, it's a hack. I've implemented the fix, it will fixed be in the next patch.

**Comment by Koutomi** [comment]
Thank you!
