### ISSUE TITLE
.derpibooru blocks NSFW results

### ISSUE THREAD

**Issue by JClarion** [Kwoth/NadekoBot#2388]
By default, Derpibooru filters out NSFW search results; this also extends to their API. To allow NSFW results, Derpibooru's API requires you to 1) set up an account with a more permissive filter, and 2) pass that account's API key. Presently, at least from what I can see, Nadeko does not support booru API keys out of the box.

**Comment by Kwoth** [comment]
Yes, I have no plans to add this but you can suggest it on feathub.
