### ISSUE TITLE
Issue with abusing currency with selfbot accounts

### ISSUE THREAD

**Issue by sadJokew** [Kwoth/NadekoBot#2389]
Could you be so mindfull to change random currency dropping message with phrase on image, but not on embeded? Because anyone who can create selfbot can abuse currency with pick in chat.
Actually its not the best solution, but to ocr image you should have time.

**Comment by xnaas** [comment]
https://feathub.com/Kwoth/NadekoBot

**Comment by shivaco** [comment]
Selfbots will still be able to detect the message, so that would be just waste of time.

**Comment by xnaas** [comment]
Also, if people are using selfbots still, just report them to Discord. 😉

**Comment by Kwoth** [comment]
No matter what i do, self bots will be able to detect it and react appropriately. They're illegal anyway afaik so just report them as xnaas said.
