### ISSUE TITLE
Running multiple bots on the same PC

### ISSUE THREAD

**Issue by StevenKvodo** [Kwoth/NadekoBot#2390]
Is there any way to do run 2 bots on the same PC? I've looked around and didn't see an answer to that.
I'm using a Windows 10 OS.

**Comment by shivaco** [comment]
It would be better if you asked in [official Nadeko support server](https://discord.gg/nadekobot). GitHub is for issues/bugs with Nadeko.

**Comment by Kwoth** [comment]
Yes, you can do it but you have to copy your folder manually, and updating may be a problem. It's one of the suggested things on feathub - to run multiple bots from the updater. On linux it's much easier, just make 2 folders and set them up separately to host nadeko.
