### ISSUE TITLE
Leaderboard shows users as Unknown#????

### ISSUE THREAD

**Issue by MrCoolKhaled** [Kwoth/NadekoBot#2392]
So I was awarding people with flowers and when I checked the leaderboard I find other people except me showing as Unknown#???? 
![image](https://user-images.githubusercontent.com/18599715/42294952-df2dbf0c-7fe5-11e8-9dc0-d5d94a64903d.png)

**Comment by MrCoolKhaled** [comment]
The above is an example.

**Comment by Kwoth** [comment]
Means the user didn't run any commands which create his entry in the database. for example `.xp` First time he does some of the commands which do, it will show up as a normal user.
