### ISSUE TITLE
.overwatch command failing to find users

### ISSUE THREAD

**Issue by Windows11** [Kwoth/NadekoBot#2397]
The .overwatch command as far as I know requires no special API, and I don't get any error messages explaining that I don't have the necessary API like I do with other commands. Instead, it just simply tells me that it can't find my account in Overwatch. This happens all the time, with everyone who tries using the command.
![screenshot_1](https://user-images.githubusercontent.com/33648723/42348265-a8b8ecbc-805d-11e8-8ff7-781bd9b89280.png)

It's not that we're just inputting something incorrectly, we've made sure that all information is correct.
![screenshot_2](https://user-images.githubusercontent.com/33648723/42348326-e79259c8-805d-11e8-8feb-65c30934ee19.png)
![screenshot_3](https://user-images.githubusercontent.com/33648723/42348388-214c71da-805e-11e8-9d37-508f21709dcb.png)

**Comment by Kwoth** [comment]
Yes, ow api will be back tomorrow hopefully.
