### ISSUE TITLE
.slowmode not working on updated bots, including public

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#2398]
Works on selfhost, error on public. 

My selfhost is on 2.22.0, and still uses `.slowmode 1 5` without the `-i` and `-m` flags.

![screen shot 2018-07-05 at 4 22 10 pm](https://user-images.githubusercontent.com/30007491/42348691-03f44ce0-8070-11e8-805b-663e2ebc2379.png)

**Comment by Kwoth** [comment]
Oh it's already fixed, next time i update public nadeko it will be fine.
