### ISSUE TITLE
Nadeko Avatar for Embeds is Dead

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#2399]
Comment on closed issue: https://github.com/Kwoth/NadekoBot/issues/2335#issuecomment-402884407

Unfortunately, it seems like DigitalOcean's "spaces" has struck us! 😛 

Edit: Copied comment below.

> This bug appears to be present in 2.24.2:
> 
> ![img](https://xnaas.info/img/LowOriginalVervet.png)
> 
> Edit: https://nadeko-pictures.nyc3.digitaloceanspaces.com/_other/avatar.png appears to be unavailable. Perhaps a solution other than DigitalOcean's "spaces"? 🤔

**Comment by hemiipatu** [comment]
Might be worth looking into Google Cloud Bucket for storing images for the bot?

**Comment by xnaas** [comment]
Just have to be careful with GCP and AWS both. They're notorious for suddenly costing a shitload if someone requests the image a bajillion times and uses a ton of bandwidth.

**Comment by Kwoth** [comment]
You guys love speculating :)) I just changed the name of the folde rfrom _other to other and forgot to update :)

**Comment by xnaas** [comment]
v2.24.3 Never™ 😉 

At least it's something simple. 👏

**Comment by Kwoth** [comment]
Fixed in 2.24.3
