### ISSUE TITLE
Latest update breaks Nadeko

### ISSUE THREAD

**Issue by evacfk** [Kwoth/NadekoBot#2400]
`CSC : warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer cannot be created from /root/.nuget/packages/microsoft.entityframeworkcore.analyzers/2.1.1/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/home/evacbots/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]
Modules/Music/Common/PoopyBufferReborn.cs(74,16): error CS0619: 'ReadOnlySpan<byte>' is obsolete: 'Types with embedded references are not supported in this version of your compiler.' [/home/evacbots/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]

Build FAILED.

CSC : warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer cannot be created from /root/.nuget/packages/microsoft.entityframeworkcore.analyzers/2.1.1/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/home/evacbots/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]
Modules/Music/Common/PoopyBufferReborn.cs(74,16): error CS0619: 'ReadOnlySpan<byte>' is obsolete: 'Types with embedded references are not supported in this version of your compiler.' [/home/evacbots/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]
    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:09.46
Running NadekoBot. Please wait.
CSC : warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer cannot be created from /root/.nuget/packages/microsoft.entityframeworkcore.analyzers/2.1.1/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/home/evacbots/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]
Modules/Music/Common/PoopyBufferReborn.cs(74,16): error CS0619: 'ReadOnlySpan<byte>' is obsolete: 'Types with embedded references are not supported in this version of your compiler.' [/home/evacbots/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]

The build failed. Please fix the build errors and run again.
Done
`

I pushed the latest commit as an update and Nadeko broke, my database files also seem to be corrupt when trying them on a new instance of Nadeko.

2.24.1 is fine, 2.24.2 is bugged.

**Comment by LunarSera** [comment]
I concur on this. I got the same error

**Comment by xnaas** [comment]
The two commits for that may or may not tell you anything useful: https://github.com/Kwoth/NadekoBot/commit/1d89b3d454b251038f96d9c2350a13fdbbf0ca74 and https://github.com/Kwoth/NadekoBot/commit/2126593b187858122d8874bc48704143e9d15257

I don't build from source or know much about .net/c# so I can't say for sure.

**Comment by evacfk** [comment]
Updating pre-reqs allows the bot to load.

However trying to launch from NadekoARN.sh presents this error:

`Running NadekoBot with auto restart normally! (without updating)
/usr/share/dotnet/sdk/2.1.301/NuGet.targets(114,5): error : Access to the path '/home/evacbots/NadekoBot/NadekoBot.Core/obj/c1eb3229-8031-4163-844e-7cfc333588fd.tmp' is denied. [/home/evacbots/NadekoBot/src/NadekoBot/NadekoBot.csproj]
/usr/share/dotnet/sdk/2.1.301/NuGet.targets(114,5): error :   Permission denied [/home/evacbots/NadekoBot/src/NadekoBot/NadekoBot.csproj]

The build failed. Please fix the build errors and run again.`

Also my database file is intact, however the bot is showing default values. (currency sign, currency etc)

**Comment by Kwoth** [comment]
Fixed. Rerun the `cd ~ && wget -N https://github.com/Kwoth/NadekoBot-BashScript/raw/1.9/linuxAIO.sh && bash linuxAIO.sh` script, redownload prerequisites, 1 (download nadeko bot again) and then run it.
