### ISSUE TITLE
"help_requires" key is missing

### ISSUE THREAD

**Issue by Kaoticz** [Kwoth/NadekoBot#2402]
So... it has been a while I've been using Nadeko in pt-BR and I've noticed every time I use the help command for a command, a warning pops up in console (print below).
![pleasereportthis](https://user-images.githubusercontent.com/1812311/42417822-9e885896-8269-11e8-9949-d222586938a5.png)

This seems pretty obvious to me. Nadeko can't find the pt-BR strings so it uses the default (en-US) ones instead. The warning yells "PLEASE REPORT THIS", so here I am, reporting this. :D

If there isn't anyone working on the translation or if it's taking way too long, I'm willing to volunteer myself to the task. I currently have a lot of spare time, so I expect to be done with all strings within this month. This is my Discord ID, hit me up if you're interested.

*Kotz#7922 <@341420590009417729>*

~~Btw, greetings from Huezil :D~~

**Comment by Kwoth** [comment]
It's because pt-br translation is not complete. Yo ucan dm me on discord to add you to pt-br translation on poeditor so you can contribute :P
