### ISSUE TITLE
XP card is unaligned on 2.24.2

### ISSUE THREAD

**Issue by Vox-ic** [Kwoth/NadekoBot#2403]
Upgrading the bot to 2.24.2 introduced this problem for me:

![4ae6509e-03ba-40ef-882b-b9335af4c696](https://user-images.githubusercontent.com/24983951/42423771-e7b91c1c-82cd-11e8-9227-aceb57f75933.png)

The level number, username, ranking, and xp amounts are all shifted upwards. Downgrading to 2.24.1 fixes it:

![130451434100490241_xp](https://user-images.githubusercontent.com/24983951/42423782-13dd2bf8-82ce-11e8-915b-6ca212bb7b88.png)

The image itself was not changed in between versions. This also occurs with the default xp card image.

Edit, after posting this I noticed the dimensions of the images sent by the bot are different. Was that an intentional change?

**Comment by Kwoth** [comment]
None of it was intentional, I apologize for being half-blind obviously. I made big changes to the image generation codebase and quickly looked if it's the same, and it looked the same to me. :P 

I will fix it asap.
