### ISSUE TITLE
Cannot use NSFW module outside private chat

### ISSUE THREAD

**Issue by RevanProdigalKnight** [Kwoth/NadekoBot#2405]
I just updated to NadekoBot v2.24.4, and decided to try out some commands for the first time in a while.

My server's permissions are as follows:

```
4. .sm games disable
3. .sm searches disable
2. .sm music disable
1. .asm enable [uneditable]
```

but every time I type a command from the NSFW module, the log spits out

```
CommandHelper | Command Errored after 0/0/0s
...
Error: Command precondition group nsfw_or_dm failed.
```

**Comment by Kwoth** [comment]
NSFW module cannot be used outside of nsfw channels.
