### ISSUE TITLE
Unable to launch NadekoBot due to OwnerID issue.

### ISSUE THREAD

**Issue by N7Yumie** [Kwoth/NadekoBot#2406]
Hiya, I've recently just set up a custom NadekoBot using the Nadeko Installer provided and I've been unable to launch it due to the OwnerID not being specified despite the fact that I have included the ID there and have laid it out in the correct manner in which the JSON Explanations on the website have set it out. I'm not sure if it's because my credentials.json file is corrupted or something like that but, the same file has worked in the past. 

(I'll include some screenshots below)

![imageedit_3_2948213316](https://user-images.githubusercontent.com/41021693/42467657-6886d618-83aa-11e8-955a-41eace1caa95.gif)
https://media.discordapp.net/attachments/459396978686558209/465937059937386497/unknown.png?width=887&height=499

**Comment by shivaco** [comment]
Is the bot on a server you are on?

**Comment by N7Yumie** [comment]
Ah, it isn't in any servers yet. Could that be the issue?

**Comment by shivaco** [comment]
Yes.

**Comment by N7Yumie** [comment]
Alright, just invited it to a server. Whoops.

**Comment by N7Yumie** [comment]
Thank you, it's working now.

**Comment by shivaco** [comment]
Do you mind closing this issue?

**Comment by N7Yumie** [comment]
Will do.
