### ISSUE TITLE
repo for https://github.com/Kwoth/Discord.Net/ not found﻿

### ISSUE THREAD

**Issue by edvardavd** [Kwoth/NadekoBot#2408]
Hi, Kwoth!

```
$ git clone -b master --recursive --depth 1 --progress https://github.com/ScarletKuro/NadekoBot.git
Cloning into 'NadekoBot'...
remote: Counting objects: 506, done.
remote: Compressing objects: 100% (420/420), done.
remote: Total 506 (delta 127), reused 268 (delta 76), pack-reused 0
Receiving objects: 100% (506/506), 3.84 MiB | 729.00 KiB/s, done.
Resolving deltas: 100% (127/127), done.
Checking connectivity... done.
Submodule 'Discord.Net' (https://github.com/Kwoth/Discord.Net) registered for path 'Discord.Net'
Cloning into 'Discord.Net'...
remote: Repository not found.
fatal: repository 'https://github.com/Kwoth/Discord.Net/' not found
fatal: clone of 'https://github.com/Kwoth/Discord.Net' into submodule path 'Discord.Net' failed

```

Do you know the way? Do you know the way to solve this problem? :sweat_smile:

**Comment by edvardavd** [comment]
@shivaco Написано, что говорите по-русски. В общем, я хотел запустить запустить сервер, чтоб он постоянно работал без моего участия. Для этого выбрал Heroku, увы, он официально не поддерживается... Может есть какие-то конкретные предложения, как сделать его онлайн постоянно? Нет ли официальной поддержки для другого облака или чего-то похожего? (

Translation: It is written that you speak Russian. In general, I wanted to start the server, so that it would work continuously without my participation. To do this, I chose Heroku, alas, it is not officially supported... Can there be any specific suggestions how to make it online without online owner? Is there no official support for another cloud or something similar? (

**Comment by Macley-Kun** [comment]
You can try skysilk. You can get a free server (PICK THE ONE WITH MORE THEN 512MB OF MEMORY) during beta.

You need a cc for this however. And the beta won't last long. It's not possible to run nadeko with 512 mb. (Recommand you using debian 8, uses the least amount of memory).
