### ISSUE TITLE
.flip X doesn't use currency images

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#2409]
![img](https://user-images.githubusercontent.com/8271327/42533866-acffbd86-8450-11e8-81a8-158bf3e9830a.png)

`.flip 2` or more does not use the images in `images.json` on Windows. Only regular `.flip` or `.flip 1` will use custom images from `images.json`.

Version: 2.24.5

**Comment by Kwoth** [comment]
What the hell

**Comment by xnaas** [comment]
¯\\\_(ツ)_/¯

**Comment by xnaas** [comment]
Look at the screenshot. I literally ran it. 😛

**Comment by xnaas** [comment]
Well, fuck it. Ran it about 10 more times and it finally decided to work, I guess. ¯\\\_(ツ)_/¯

**Comment by xnaas** [comment]
Re-opened since this is confirmed to still be an issue. ¯\\\_(ツ)_/¯

**Comment by Kwoth** [comment]
Fixed in latest patch. Windows release in a few hours.
