### ISSUE TITLE
Role based permissions broken

### ISSUE THREAD

**Issue by RustyGrizwold** [Kwoth/NadekoBot#241]
;rc "command" disable "role" is not working/being enforced. nadeko lists the command as banned for the role but does not stop the users of the role from executing it.

**Comment by Kwoth** [comment]
You have to ban it for "everyone" role too first.

If a user has a role whcih allows him to do something, he will be able to do it. So you need to prevent everyone role and all roles that user has, in order to prevent him from doing that command.
