### ISSUE TITLE
Can't run nadeko

### ISSUE THREAD

**Issue by Drmalkav** [Kwoth/NadekoBot#2410]
i keep getting errors when trying to run nadeko, it all went wrong after an update, so i tried to reinstall nadeko completely from scratch, but i keep getting the same error when trying to start up nadeko. i tried 2 times on ubuntu 16.04.4 and one time on 17.10 and one time from windows 10 64bit. plz send help
![image](https://user-images.githubusercontent.com/41089048/42540568-36b5ad1c-849f-11e8-950a-a30ba94aa057.png)

**Comment by xnaas** [comment]
Seems related to #2407?

**Comment by Drmalkav** [comment]
yeah but that was after updating, #2407  and not the same error codes. prob same problem though, so wasn't really sure about making a new issue post or not. but mine is about fresh installs on clean systems. though the reason i had to try those clean installs, was that my bot broke after i updated

**Comment by lori9** [comment]
I looked in the images.json file, which was using the new default files, and I noticed there were many being hosted from a new domain instead of imgur. I replaced them with imgur equivalents and now the bot functions perfectly.

Looks like this digital oceans host is maybe getting DDoSed by the traffic?

**Comment by Kwoth** [comment]
![image](https://user-images.githubusercontent.com/2537696/42562280-83d15f98-8525-11e8-88c3-2f3464401f2b.png)

**Comment by Drmalkav** [comment]
yeah i saw that but i run it from san fransico, and i go the same error when trying from my own windows 10 pc

**Comment by Kwoth** [comment]
.... what you just said doesn't make sense : )

**Comment by Drmalkav** [comment]
i ment i run my droplets from the san fransico 2 option you get when creating a droplet. and when i tried to host the bot from my own windows 10 64bit machine here at home, i got the errors too

**Comment by Drmalkav** [comment]
welp it now runs again perfectly for some strange reason xD
