### ISSUE TITLE
.hentaibomb not working on selfhost bot

### ISSUE THREAD

**Issue by Ming-A** [Kwoth/NadekoBot#2411]

**Comment by Kaoticz** [comment]
Mine is working fine. **Nadeko v.2.24.5**, **Ubuntu 16.04.4 LTS**
Can you provide a screenshot of your console when you use that command?

**Comment by Wizkiller96** [comment]
Also, make sure the channel you are in has NSFW enabled in the channel settings.

**Comment by Ming-A** [comment]
https://media.discordapp.net/attachments/465980400972595221/466352615714717696/unknown.png?width=190&height=444

**Comment by Ming-A** [comment]
![image](https://user-images.githubusercontent.com/41011175/42619325-5197b57a-85ea-11e8-99c0-3fb92a6aeed2.png)

**Comment by Kaoticz** [comment]
Are you using DigitalOcean's VPS to host your bot?

**Comment by Ming-A** [comment]
I'm not, just on my windows 10 pc

**Comment by Kaoticz** [comment]
Error 404 (Not Found) is an indication that there might be a problem with your internet connection. Make sure you can access the following sites in your browser: **gelbooru, danbooru, konachan, yandere and atfbooru**
