### ISSUE TITLE
ffmpeg download or install failed.

### ISSUE THREAD

**Issue by KumiDesu** [Kwoth/NadekoBot#2412]
I can't install ffmpeg with the updater, and of course i can't play music with the bot.
![screenshot_1](https://user-images.githubusercontent.com/41129206/42601772-2f10d1b0-853d-11e8-92d1-e7c4944ae851.png)

**Comment by EduenSarceno** [comment]
it's a cloudflare issue 
if you have git bash, open and write
`curl https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-20180711-09628cb-win64-shared.zip -I`

If the output looks like:  
```
HTTP/1.1 403 Forbidden
Connection: close
Set-Cookie: __cfduid=d9415f5f808c97b9f885218017df5ad6c1531346883; expires=Thu, 11-Jul-19 Server: cloudflare
CF-RAY: 438e962688b33864-ATL
```
it's cloudflare issue. 

Just do:
1. Download [ffmpeg](https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-20180711-09628cb-win64-shared.zip)
2. Extract the `/bin` folder of ffmpeg in the `system` folder of nadeko (all .dll in the same folder of NadekoBot.dll)
3. Restart the bot

**Comment by Kwoth** [comment]
DO spaces had some problems. It's solved now. It should work.
