### ISSUE TITLE
.hentaibomb not working on selfhost bot on NSFW lobby

### ISSUE THREAD

**Issue by Ming-A** [Kwoth/NadekoBot#2414]
![image](https://user-images.githubusercontent.com/41011175/42619339-5e00e3d6-85ea-11e8-8b3f-ba51eb7f5e21.png)

**Comment by Macley-Kun** [comment]
public or selfhosted?

Any info where you host this?

just throwing a picture isn't really enough to determin what were dealing with

**Comment by xnaas** [comment]
Does `.stats` say you're on `v2.24.5`?

**Comment by shikhir-arora** [comment]
Are you sure you don't mean 2.24.4? That's the latest version 🤔

**Comment by Ming-A** [comment]
![image](https://user-images.githubusercontent.com/41011175/42653000-a6e18df6-8646-11e8-801f-1b4fb9997377.png)
Also its 2.24.5 thats the latest according to Nadekobot updater

**Comment by shikhir-arora** [comment]
Maybe for Windows. For Linux compiled from Git, it's [2.24.4](https://github.com/Kwoth/NadekoBot/blob/1.9/NadekoBot.Core/Services/Impl/StatsService.cs#L26)

**Comment by Kwoth** [comment]
Tested on 2.25.0, works fine. Maybe you're using some weird tags : )
