### ISSUE TITLE
.aar issue

### ISSUE THREAD

**Issue by Biwerman** [Kwoth/NadekoBot#2418]
when i try to use the .aar command nadeko only says either that it is enabled or disabled.

i have been using it like so (.aar The Moon Guardians), (.aar TestRole) and (.aar) where as with the 2 first nadeko only says
BiwerTheWorst#0288 Auto assign role on user join is now enabled.

and with the 3 one it works as it should ofc 
BiwerTheWorst#0288 Auto assign role on user join is now disabled.

i have also tryed 
.aar "The Moon Guardians"
.aar (The Moon Guardians)
.aar <The Moon Guardians>
but with no response

and 2 new ppl joined the server after i did .aar The Moon Guardians and they did not get the role assigned

is there something special you have to do to make it work that i have missed?
pls help and thanks in advance

-- BiwerTheWorst--

**Comment by Kaoticz** [comment]
- Are you using public or a self-hosted Nadeko? If self-hosted, which version and for what OS?
- Does Nadeko have the **ManageRoles Server Permission**?

**Comment by Macley-Kun** [comment]
@Biwerman you need to provide some more information.
If you already solved your issue or don't see any use in asking it here. Do not forget to close the issue.

**Comment by Macley-Kun** [comment]
@Kwoth think he got it solved. No reaction after 9 days.

**Comment by Kwoth** [comment]
.aar works. You need to make it enabled, which means specifying a role like you did in your first try.

.aar The Moon Guardians

after that you must make sure that the role you want to assign is under nadeko's highest role.

Also the users who join can't be invisible possibly (appear offline)

**Comment by Biwerman** [comment]
Hey Kwoth. 

What do you mean exacly when you say that i need to make sure that the role im using has to be under nadeko's highest role?

**Comment by Kaoticz** [comment]
He means this:
![image](https://user-images.githubusercontent.com/1812311/43360244-98ef8844-9288-11e8-9c6e-14c194ca2bf9.png)

Roles are draggable. Make sure Nadeko's is higher than whatever role she is interacting with.

**Comment by Biwerman** [comment]
allraight it works

thanks for all the help

biwer signing out
