### ISSUE TITLE
Network Paths Half Supported for Redis Image Caching

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#2420]
As discussed, I'd test out if network paths were supported on Windows.

Here's a screenshot:

![img](https://xnaas.info/img/UnwelcomeWaryGalapagospenguin.png)

And of course, trying `.flip` after that results in only the default images showing up.

I figured it'd be worth a shot, so I changed the `\` to `/` and it seems to work. Should probably be mentioned in docs somewhere since Windows defaults to `\` when copying paths and the like and it's not obvious that fixing `\` to `/` is the answer to most people.

**Comment by Kwoth** [comment]
either use `\\` or `/`

You're free to make a pr to the docs 😂
