### ISSUE TITLE
I have no idea what this is.

### ISSUE THREAD

**Issue by LunarSera** [Kwoth/NadekoBot#2421]
The below is logged in the terminal every time I start the bot. and it reposts every now and then.

0|Sanae    | -1 21:37:01 ShardsCoordinator | StackExchange.Redis.RedisTimeoutException: Timeout performing LRANGE MTcwMDY3OD_shardstats, inst: 1, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: , serverEndpoint: 127.0.0.1:6379, keyHashSlot: 9941
0|Sanae    | (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
0|Sanae    |    at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcesso
0|Sanae    | r`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2101
0|Sanae    |    at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint
0|Sanae    | server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
0|Sanae    |    at StackExchange.Redis.RedisDatabase.ListRange(RedisKey key, Int64 start, Int64 stop, CommandFlags flags) in C:\code\StackExchange.Redis\StackExchange.Re
0|Sanae    | dis\StackExchange\Redis\RedisDatabase.cs:line 874
0|Sanae    |    at NadekoBot.Core.Services.ShardsCoordinator.<>c__DisplayClass15_0.<<RunAsync>b__1>d.MoveNext()

**Comment by xnaas** [comment]
Try re-installing Redis?

**Comment by Kwoth** [comment]
run redis-cli and try FLUSHALL then start the bot again

**Comment by LunarSera** [comment]
I performed redis-cli then sent flushall. As requested. I got an ok confirmation.

Less than 3 hours after restarting the bot, I got the error again. If it doesn't effect nadeko  negatively I won't worry about it.

**Comment by Kwoth** [comment]
Nobody else reporting this, and i'm not getting it on public nor beta bot, so i'll just close this and assume it's your local issue

**Comment by rjt-rockx** [comment]
Getting this issue here.
Will try flushall and send the results.
