### ISSUE TITLE
Updater Keeps Wiping images.json Back to Default

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#2422]
Every time I use the updater, it extracts a new `images.json` and wipes out everything...can we not. 😉 

Edit: It also wipes the `images_backup.json` so that's annoying too. 🙁

**Comment by xnaas** [comment]
Also of note, even going up from `2.25.1` to `2.25.2`, it still did all of this again:

    -1 11:33:54 ShardsCoordinator | Starting NadekoBot v2.25.2
    -1 11:33:54 RedisImagesCache | Migrating images v0 to images v1.
    -1 11:33:54 RedisImagesCache | Migrating images v1 to images v2.
    -1 11:33:54 RedisImagesCache | Cards loaded in 0.02s
    -1 11:35:18 RedisImagesCache | Images reloaded in 84.10s

Mostly that migration junk from 0 -> 1 -> 2.

**Comment by Kwoth** [comment]
Ok that's an issue. 

images_backup is not a backup for you. It's a backup of original values in case you mess up, so they should be wiped.

**Comment by Kwoth** [comment]
Are you sure it's the updater?

**Comment by Kwoth** [comment]
Does it happen every time you restart the bot?

**Comment by Kwoth** [comment]
Wait... Where is your images.json? images.json is moved from data/images/images.json to data/images.json, are you perhaps editing the wrong one?

**Comment by xnaas** [comment]
> Are you sure it's the updater?

Yes. Both times I've updated using the updater since the change to `images.json` it has wiped it back to default.

> Does it happen every time you restart the bot?

No. Works fine on a restart.

![img](https://user-images.githubusercontent.com/8271327/42818555-d1eb2626-8996-11e8-8abb-fc2224bdf3ef.png)

> Where is your images.json? images.json is moved from data/images/images.json to data/images.json, are you perhaps editing the wrong one?

I have edited `C:\Program Files\NadekoBot\system\data\images.json` every single time.

> The first message will only ever trigger if there is data/images/images.json file. It will delete it after.

I guess it thinks that file is there, because that hasn't been there in awhile...all I know is watching the updater both times, it said it was extracting `images.json` and wiped mine. :D

**Comment by xnaas** [comment]
As a partial aside, should I just delete `C:\Program Files\NadekoBot\system\data\images` if it's not actually in use anymore?

**Comment by Kwoth** [comment]
Cards are in there :D

**Comment by Kwoth** [comment]
Yes please do

**Comment by xnaas** [comment]
Alright. I may be able to on Saturday night or Sunday. Unfortunately, real life stuff in the way at the moment. 👍

**Comment by xnaas** [comment]
Just did it again after the update to 2.25.4, btw.

<img width="598" alt="image" src="https://user-images.githubusercontent.com/8271327/42950945-b5aacb06-8b3a-11e8-8ec0-7794514815e3.png">

**Comment by Jengas** [comment]
Same, after updating bot, images.json getting wiped to default.

**Comment by Kwoth** [comment]
@xnaas as i said, after you update and before you start the bot, you have to check if data/images/images.json exists

**Comment by xnaas** [comment]
The file `C:\Program Files\NadekoBot\system\data\images\images.json` does not exist, but I will check if the file is created next time after updating and before launching the bot. Or as part of my larger test this weekend.

**Comment by Kwoth** [comment]
Ok I think the file was there because it seems file weren't being cleared up when a new release is built, so old files which should've been removed long time ago were still present. Please try updating to 2.26.0, tell me the result and close if it's solved.

**Comment by Jengas** [comment]
For me - works
![screenshot_3](https://user-images.githubusercontent.com/14033756/43047433-75ed90c6-8dd7-11e8-8a7c-7f0c011d5a48.png)
![screenshot_4](https://user-images.githubusercontent.com/14033756/43047434-76090de2-8dd7-11e8-8350-e98dbe120e0e.png)

**Comment by xnaas** [comment]
You don't have any customization in your JSON unless I'm blind. The issue is that the images.json is being reset back to default. You have default anyway, so you wouldn't be affected.

**Comment by xnaas** [comment]
Finally seems to have stuck after this last update.

![img](https://xnaas.info/img/ExcitableSmugCock.png)

**Comment by xnaas** [comment]
Wait, cancel that. ALMOST, perfect. 😛 Still added your own nadeko image there.

**Comment by Kwoth** [comment]
That's unrelated, it's a new pic 😂
