### ISSUE TITLE
No autocmd delete?

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#2423]
There's `.autocmdadd` to create automatic commands and `.autocmds` to view all of them...but there's no way to delete them without editing the database? Is this an oversight or am I missing something entirely?

**Comment by xnaas** [comment]
Never mind. I see `.scrm` is supposed to be used for startup commands and auto-commands since they're all related, I guess.

**Comment by Kwoth** [comment]
I think .autocmdrm is an alias

**Comment by xnaas** [comment]
Seems to be.

![img](https://xnaas.info/img/IlliterateUpsetWoodpecker.png)

Good to know. Thanks. 👍
