### ISSUE TITLE
Project File Missing / Segmentation fault

### ISSUE THREAD

**Issue by Quadrocompile** [Kwoth/NadekoBot#2428]
I already had NadekoBot up and running on my server (v2.23.0), and tried to update it today which broke everything. I updated dotnet, removed all NadekoBot files and tried a clean install. When I enter the option "Download NadekoBot" the installation script prints some warnings:

/opt/dotnet/sdk/2.0.0/NuGet.targets(216,5): warning MSB3202: The project file "/home/happiebot/NadekoInstall_Temp/NadekoBot/src/NadekoBot/Nadeko
tall_Temp/NadekoBot/NadekoBot.sln]
/home/happiebot/NadekoInstall_Temp/NadekoBot/src/NadekoBot/NadekoBot.csproj : warning NU1503: Skipping restore for project '/home/happiebot/NadekoInstall_Temp/NadekoBot/src/NadekoBot/NadekoBot.csproj'. The project file may be invalid or missing targets required for restore. [/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.sln]
/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj : warning NU1503: Skipping restore for project '/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj'. The project file may be invalid or missing targets required for restore. [/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.sln]
/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.Tests/NadekoBot.Tests.csproj : warning NU1503: Skipping restore for project '/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.Tests/NadekoBot.Tests.csproj'. The project file may be invalid or missing targets required for restore. [/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.sln]
/opt/dotnet/sdk/2.0.0/NuGet.targets(102,5): warning : Unable to find a project to restore! [/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.sln]

However, the following script "Welcome to NadekoBot" is then executed.

When I then try to run Nadeko (normally or with auto restart) I get a segmentation fault error. 

Option 2)
/home/happiebot/nadeko_run.sh: line 16: 22095 Segmentation fault      dotnet restore
/home/happiebot/nadeko_run.sh: line 17: 22125 Segmentation fault      dotnet build -c Release
Running NadekoBot. Please wait.
/home/happiebot/nadeko_run.sh: line 20: 22159 Segmentation fault      dotnet run -c Release

Option 3)
/home/happiebot/NadekoARU_Latest.sh: line 8: 22320 Segmentation fault      dotnet restore
  Restore completed in 31.48 ms for /home/happiebot/NadekoBot/NadekoBot.Tests/NadekoBot.Tests.csproj.
  Restore completed in 22.66 ms for /home/happiebot/NadekoBot/src/NadekoBot/NadekoBot.csproj.
  Restore completed in 22.62 ms for /home/happiebot/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj.

Any idea on how to resolve this issue?

**Comment by shikhir-arora** [comment]
This happens when dotnet has an issue. 

Have you done this (posted in Nadeko server from @Kwoth:
```
**If you're updating on LINUX** 
You'll have to run the latest linuxAIO script
`cd ~ && wget -N https://github.com/Kwoth/NadekoBot-BashScript/raw/1.9/linuxAIO.sh && bash linuxAIO.sh` 

Select option 4 first (install prerequisites) as you have to reinstall them, and then update (option 1)```

**Comment by Quadrocompile** [comment]
Yes, I have followed this guide http://nadekobot.readthedocs.io/en/latest/guides/Linux%20Guide/
I used the most recent linuxAIO.sh, I used option 4 (auto-install), followed by 1 (download NadekoBot). This is when the first warning appears:

/opt/dotnet/sdk/2.0.0/NuGet.targets(216,5): warning MSB3202: The project file "/home/happiebot/NadekoInstall_Temp/NadekoBot/src/NadekoBot/NadekoBot.csproj" was not found. [/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.sln]

Although this is just a warning and not an error, I don't believe this is supposed to happen, is it? Because the .csproj file exists in this GitHub repository.

**Comment by Kaoticz** [comment]
My bet is, for some reason, your Nadeko has been installed with root permissions and now the system won't let the script download anything in that folder because you're running it as a user.

Try this to remove the root permissions:
`cd /home && sudo chown -R username:username happiebot`
(Replace "username" with whatever your username is called, ofc)

Then try running the script again (with the command from the guide), options 4 and 1 and watch if the same warnings pop up.

**Comment by Quadrocompile** [comment]
Unfortunately this does not solve the issue. Here is what I did: I deleted the whole folder, created a new one and ran the chown command. I then used the command from the documentation to download and start the install script in this new created folder. ls gives me the following output so I think it's not a permission problem:
```console
-rw-r--r--  1 happiebot happiebot  272 Jul 20 16:42 linuxAIO.sh
```
I then started the installation process according to the linux installation guide (-> 4. Auto-Install Prerequisites (For Ubuntu, Debian and CentOS); -> 1. Download NadekoBot) which yields the same output as the last time.

```console
NadekoBot Installer started.

Git Installed.

Dotnet installed.

Downloading NadekoBot, please wait.
Cloning into 'NadekoBot'...
remote: Counting objects: 813, done.
remote: Compressing objects: 100% (686/686), done.
remote: Total 813 (delta 236), reused 348 (delta 112), pack-reused 0
Receiving objects: 100% (813/813), 4.72 MiB | 7.43 MiB/s, done.
Resolving deltas: 100% (236/236), done.

NadekoBot downloaded.

Downloading Nadeko dependencies
/home/happiebot/nadeko_installer_latest.sh: line 42:  3351 Segmentation fault      dotnet restore

Download done

Building NadekoBot
/home/happiebot/nadeko_installer_latest.sh: line 48:  3381 Segmentation fault      dotnet build --configuration Release

Building done. Moving Nadeko

credentials.json copied to the new version

Database copied to the new version
/opt/dotnet/sdk/2.0.0/NuGet.targets(216,5): warning MSB3202: The project file "/home/happiebot/NadekoInstall_Temp/NadekoBot/src/NadekoBot/NadekoBot.csproj" was not found. [/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.sln]
/opt/dotnet/sdk/2.0.0/NuGet.targets(216,5): warning MSB3202: The project file "/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj" was not found. [/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.sln]
/opt/dotnet/sdk/2.0.0/NuGet.targets(216,5): warning MSB3202: The project file "/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.Tests/NadekoBot.Tests.csproj" was not found. [/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.sln]
/home/happiebot/NadekoInstall_Temp/NadekoBot/src/NadekoBot/NadekoBot.csproj : warning NU1503: Skipping restore for project '/home/happiebot/NadekoInstall_Temp/NadekoBot/src/NadekoBot/NadekoBot.csproj'. The project file may be invalid or missing targets required for restore. [/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.sln]
/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj : warning NU1503: Skipping restore for project '/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj'. The project file may be invalid or missing targets required for restore. [/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.sln]
/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.Tests/NadekoBot.Tests.csproj : warning NU1503: Skipping restore for project '/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.Tests/NadekoBot.Tests.csproj'. The project file may be invalid or missing targets required for restore. [/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.sln]

Other data copied to the new version
/opt/dotnet/sdk/2.0.0/NuGet.targets(102,5): warning : Unable to find a project to restore! [/home/happiebot/NadekoInstall_Temp/NadekoBot/NadekoBot.sln]

Installation Complete.
```
Starting NadekoBot results in the same segmentation fault error
```console
Running NadekoBot with auto restart and updating to latest build!
/home/happiebot/NadekoARU_Latest.sh: line 5: youtube-dl: command not found
/home/happiebot/NadekoARU_Latest.sh: line 8:  4484 Segmentation fault      dotnet restore
  Restore completed in 32.09 ms for /home/happiebot/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj.
  Restore completed in 32.83 ms for /home/happiebot/NadekoBot/src/NadekoBot/NadekoBot.csproj.
  Restore completed in 19.38 ms for /home/happiebot/NadekoBot/NadekoBot.Tests/NadekoBot.Tests.csproj.
```

**Comment by Kaoticz** [comment]
You might have dotnet c-release running in the background. Try this:

`sudo pkill -f nadeko && sudo pkill -f dotnet`

Then run Nadeko's script again.

**Comment by Kwoth** [comment]
Have you solved this? This is not a bot issue either way. You should google for the 4484 segmentation fault, and if you find solution please post it here as other people (completely unrelated to the bot) might stumble upon this issue while searching for the same error.
