### ISSUE TITLE
e621 command not working whatsoever

### ISSUE THREAD

**Issue by Advanst** [Kwoth/NadekoBot#243]
So I've had the bot around for about 2 weeks, and I offered to host it in someone's server, no big deal... But for some reason it seems like the e621/hentai commands broke today. From what I can tell, everything else works, and it sees the e621 and hentai commands, but it seems to essentially refuse to respond to them.

I've done a complete reinstall of the new version, and I've made sure several times over that the nsfw module is enabled.

**Comment by appelemac** [comment]
What does the console say?

**Comment by Advanst** [comment]
Alright so after some more command testing, hentai was just a fluke and I was doing commands too fast. Hentai, gelbooru, danbooru, butt, and boobs all work. This is something with e621, and I saw that e621's API got screwed, so I'll assume it was that.

**Comment by Advanst** [comment]
The console notes that the command was processed, but it doesn't reply with anything. I'd really just link this to e6's API issues.

**Comment by Gaboer** [comment]
Console says the site returns a 403 error, and it's directly attributed to E621's change that bans any requests without a valid user agent. Working on the fix, just gotta finish up a final today. Rewritten pull request will probably come up later tonight

**Comment by Advanst** [comment]
Awesome. Thank you c:

**Comment by Kwoth** [comment]
Will be fixed in the next release. I'm planing to make a minor one tonight.
