### ISSUE TITLE
Nadeko 'rip' after Discord Issue :(

### ISSUE THREAD

**Issue by stargazer001** [Kwoth/NadekoBot#2430]
Hi, My nadeko didn't come back online after being 'knocked offline' by the Discord Issue yesterday.. It affected my other bot on the vm; but that one came back online with rebooting the vm.

Kotz#7922 seems to think it has to do with dotnet. > _"This error happens when dotnet c-release is running in the background"_ (from the Nadeko Support Discord)

Someone helping me had run the following so, wouldn't that have stopped all dotnet processes? and found that my **Dotnet version was ...2.1.302**

TIA 

nb: my vm is on Google Cloud, with ubuntu.

> sudo pm2 stop Nadeko
> sudo killall dotnet
> sudo pm2 start Nadeko

> 0|Nadeko   | /usr/share/dotnet/sdk/2.1.302/Microsoft.Common.CurrentVersion.targets(4172,5): error MSB3021: Unable to copy file "obj/Release/netcoreapp2.0/NadekoBot.dll" to "bin/Release/netcoreapp2.0/NadekoBot.dll". The process cannot access the file '/home/sasha_sim_sonic/NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/NadekoBot.dll' because it is being used by another process. [/home/sasha_sim_sonic/NadekoBot/src/NadekoBot/NadekoBot.csproj]
> 0|Nadeko   | The build failed. Please fix the build errors and run again.

**Comment by Gremagol** [comment]
Well,  `sudo pm2 restart Nadeko` would've been enough.
Maybe there are still dotnet processes running, try finding them with `ps -A | grep dotnet` and try killing them by ID. `kill PID`
Otherwise just try restarting the VPS with `sudo reboot`.

**Comment by stargazer001** [comment]
it's saying 
![dot net stuff](https://user-images.githubusercontent.com/35642974/42868099-cba0b0e6-8ab4-11e8-8e9c-e9021374e213.JPG)
a repeated (in red) dotnet defunct

**Comment by Gremagol** [comment]
I would say, a VPS restart would be the best solution. 😂 
Well, if it's possible ofc.

**Comment by stargazer001** [comment]
these two were in red.. but not 'defunct'..?

> 16840 ?        00:00:03 dotnet
> 16890 ?        00:00:24 dotnet

are those two what I should run kill pID and where to put the number?

**Comment by stargazer001** [comment]
a restart of my vm? (vps) well, guess I can, but is that a sure fire fix for the dotnet issue?

**Comment by Gremagol** [comment]
I don't know. I'm running multiple Nadeko Clones on Ubuntu 18.04 with pm2 for longer than 3 months without a restart and they still work fine as if nothing happened.

**Comment by Kaoticz** [comment]
*Kotz#7922* from #help here
No, rebooting does not solve the problem. dotNet keeps running in the background, preventing Nadeko from using it.

**Comment by stargazer001** [comment]
this is the 'kill process' msg..  thanks for dropping by @Kaoticz 
![dot net issue](https://user-images.githubusercontent.com/35642974/42868661-386dc096-8ab6-11e8-90db-e05d1242bef3.JPG)

**Comment by Macley-Kun** [comment]
try sudo on that one

**Comment by stargazer001** [comment]
sudo kill PID 16840? 

_or do I include bash or something?_

**Comment by Macley-Kun** [comment]
Just sudo kill PID 16840. Hope it let's you go trough. Noticed that you aren't root :P

**Comment by stargazer001** [comment]
![dot net issue 2](https://user-images.githubusercontent.com/35642974/42868810-a1607558-8ab6-11e8-8466-f56e3842ff34.JPG)

**Comment by stargazer001** [comment]
should I be 'in' a Nadeko file/folder to run these? or it doesn't matter?

**Comment by Macley-Kun** [comment]
https://www.tecmint.com/how-to-kill-a-process-in-linux/ <-read

**Comment by stargazer001** [comment]
or should it also have 'dot net' in the command

**Comment by Macley-Kun** [comment]
Can we please continue this in the Help channel? Because your spamming the shit out of everyone here.

**Comment by stargazer001** [comment]
oh.. well ok: just had asked twice yesterday to no avail.

**Comment by Macley-Kun** [comment]
Github is when you have actully bugs found or want to send a fix/pull.
#help is when you need help with the bot in all kinds. Everyone that helps there is doing it in their spare time. So you just have to re-visit it a few times until someone can help you out there.

**Comment by stargazer001** [comment]
Fix still needed **please only reply if you have an understanding / have dealt with similar issue of dotnet.**

**Comment by shikhir-arora** [comment]
`sudo pkill -f nadeko && audo pkill -f dotnet` 

Then try again.

**Comment by stargazer001** [comment]
![dotnet prob](https://user-images.githubusercontent.com/35642974/42877578-89203872-8acd-11e8-9d18-a4f8f6044dd0.JPG)
? I'm thinking a typo then for the && was also meant to be sudo, not 'audo' then?

**Comment by shikhir-arora** [comment]
Right, I edited that a second after. Typo :P

**Comment by stargazer001** [comment]
ok, just a new line after that.. so then, sudo pm2 restart Nadeko now?

**Comment by stargazer001** [comment]
oh..... without doing either of those... thanks so much @shikhir-arora it's online!!! _/|\_ namaste friend 👍

**Comment by shikhir-arora** [comment]
No problem. Glad things worked out 👍

**Comment by stargazer001** [comment]
same.. 🥇

**Comment by Kaoticz** [comment]
@stargazer001 Glad you got it fixed :D 
And now I learned how to fix it :3
