### ISSUE TITLE
Build failing on CentOS 7

### ISSUE THREAD

**Issue by bryonadams** [Kwoth/NadekoBot#2434]
Build fails on run or download after updating system, new dotnet upgraded, dotnet-host-2.1.0_rc1-1.x86_64

Output from running the download option when running the script to run/update Nadeko
Build FAILED.

CSC : warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer cannot be created from /home/nadeko/.nuget/packages/microsoft.entityframeworkcore.analyzers/2.1.1/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/home/nadeko/NadekoInstall_Temp/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]
Modules/Music/Common/PoopyBufferReborn.cs(74,16): error CS0619: 'ReadOnlySpan<byte>' is obsolete: 'Types with embedded references are not supported in this version of your compiler.' [/home/nadeko/NadekoInstall_Temp/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]
    1 Warning(s)
    1 Error(s)

**Comment by bryonadams** [comment]
I restored a snapshot from before I updated CentOS where NadekoBot is working. Updating only NadekoBot resulted in the same build failure.

**Comment by Kaoticz** [comment]
Run the script from the Linux guide and do options 4 and 1. Then try running the bot again.

**Comment by Kwoth** [comment]
Yes, you didn't update your prerequisites, as kaoticz said.
