### ISSUE TITLE
MessageUpdated not working

### ISSUE THREAD

**Issue by DevoidCoding** [Kwoth/NadekoBot#2436]
MessageDeleted works perfectly but not MessageUpdated
i.e. : https://i.imgur.com/cftM3mc.png

No errors or warning in the console. Redis installed fine and all other logs working.
Every log events are registered : https://i.imgur.com/lMvzO6n.png

**Comment by Kwoth** [comment]
MesssageUpdated event ignores messages which are updated in the channel the bot is logging in.

I tested, it works.
