### ISSUE TITLE
Question: Why does Nadeko use root perms so much?

### ISSUE THREAD

**Issue by BlackHoleFox** [Kwoth/NadekoBot#2438]
As the title says, im confused as to why the Linux installer for Nadeko bot requires root perms everywhere. For installing the .NET requirements is fine but why does it have to create directories owned by root, and ran as root? I don't see why a bot needs to run as root on a user account.

**Comment by Kwoth** [comment]
Linux scripts are contributed by several people, I myself am i complete linux noob, so if you know a better way to do it, feel free to pr it to https://github.com/Kwoth/NadekoBot-BashScript/tree/1.9
