### ISSUE TITLE
the picking from pc working but picking from plants error

### ISSUE THREAD

**Issue by Nanonium** [Kwoth/NadekoBot#2439]
basically, when I plant currency, people are able to pick it. However, the currency generated from chat activity popping up occasionally does not get picked up upon typing .pick. I have attempted to restart the bot, ensure it is up to date, taken the bot offline back to online to see if restarting would work and nothing worked.

**Comment by Overlordmittenz** [comment]
Also having this issue.

**Comment by Badllamah** [comment]
Same here.

**Comment by BStorm888** [comment]
Having the same issue.

**Comment by Kwoth** [comment]
Oki, will look into it asap
