### ISSUE TITLE
Auto Currency Generation Issues

### ISSUE THREAD

**Issue by bstompor** [Kwoth/NadekoBot#2441]
I'm having an issue with currency generation, when users use the `.plant ` command others can pick - just like it should be, however when the bot plants currency through auto generation (`.gc`) people cant pick it.  I've set the `CurrencyGenerationPassword` to `False` thinking it might be an issue with that, however the problem persists.   The console shows the `.pick` command and shows no errors.  Hopefully you can help.

**Comment by xnaas** [comment]
Duplicate. #2439
