### ISSUE TITLE
How to make a custom bg

### ISSUE THREAD

**Issue by zMatix** [Kwoth/NadekoBot#2444]
How to make a custom xp bg following the template?

**Comment by zMatix** [comment]
both images have a similarity, so I assumed that there was a type of template; i have my self hosted bot :)

![](https://user-images.githubusercontent.com/6222472/32847744-882de88e-ca33-11e7-9c90-24605205b331.png)

![](https://nadeko-pictures.nyc3.digitaloceanspaces.com/other/xp/bg.png)

**Comment by Macley-Kun** [comment]
@zMatix you can ping Macley in the #help chat in the nadekolog server, i'll help you out ok.

**Comment by Kwoth** [comment]
@zMatix yes there is
