### ISSUE TITLE
No icon on the bot exe

### ISSUE THREAD

**Issue by TheOddball** [Kwoth/NadekoBot#2445]
#2240 is broken again

**Comment by xnaas** [comment]
This .exe the one you're talking about?

<img width="567" alt="image" src="https://user-images.githubusercontent.com/8271327/43079464-d0f42554-8e52-11e8-8a37-79f67d6b4897.png">

**Comment by Kwoth** [comment]
Should be fixed in 2.26.1

**Comment by TheOddball** [comment]
Still broken @Kwoth

**Comment by Kwoth** [comment]
nope, works on 2.26.1 for sure, i just tested it, try uninstalling and installing again

**Comment by TheOddball** [comment]
that worked, c:
