### ISSUE TITLE
Unable to get PM2 to function; Bot remains offline

### ISSUE THREAD

**Issue by CrawfordK** [Kwoth/NadekoBot#2447]
Hello! I've posted this twice now in the discord @SupportGirls and I've actively watched them answer and assist others but have ignored my message even if it came before the one they decided to answer! I know this is all volunteer work and I am not a donator personally but it becomes discouraging to self host a bot..

Anyways onto the issue. I use Digital Ocean, I opted to SSH into via Putty vs their build-in browser console. I had to go through the initial steps again to fix another issue, this involved re-downloading pre-reqs and the main download again. Then I booted the bot up like normal (no auto restart/update during current session) then killed the bot, pressed 6 to download PM2 dependencies and then pressed 7 to run PM2 for the first time, this time I press 2 which allowed for auto-restart/updating during the PM2 session. It goes through it's thing then it starts at the beginning with the options to download, etc. Bots still offline.. Try to boot just in the session, nothing. Closed the session, created a new session (using the commands offered within the Linux documentation), closed putty, etc and my bot is still offline. I even went through and downloaded everything again like I did at the beginning - still offline.

[Screenshot 1](https://i.imgur.com/XtRYkND.png)
[Screenshot 2](https://i.imgur.com/SDAPsGS.png)

**Comment by Kaoticz** [comment]
Use `sudo pm2 status` to see what pm2 processes are currently running
I bet you're running several instances at once, so use `sudo pm2 delete x` to delete the extra ones (x is the ID number, your first installed instance should have ID number 0)
Once you have only one instance of Nadeko running, use `sudo pm2 restart Nadeko` (if it's offline) or use `sudo pm2 logs Nadeko` (if it's already online).

Ping me on Discord, in the #help channel if you want me to aid you in real time (**Kotz#7922**)

**Comment by CrawfordK** [comment]
I used the delete and it deleted it, but when I ran restart it couldn't start anything :/

https://i.imgur.com/GeOLT1M.png
https://i.imgur.com/H2cXKgC.png

**Comment by Macley-Kun** [comment]
![image](https://user-images.githubusercontent.com/26381427/43132424-091159a4-8f3c-11e8-8689-95c9c3f43db4.png)
🤔 you tried that?
