### ISSUE TITLE
cleverbot crashes bot every few hours, bot also spits out patreon errors

### ISSUE THREAD

**Issue by TamaKaiNya** [Kwoth/NadekoBot#2448]
-1 10:00:15 ShardsCoordinator | Starting NadekoBot v2.26.0
-1 10:00:16 ShardsCoordinator | Images are already present in redis. Use .imagesreload to force update if needed.
0 10:00:21 NadekoBot | Shard 0 logging in ...
0 10:00:24 NadekoBot | Shard 0 logged in.
0 10:00:24 NadekoBot | Shard 0 loading services...
0 10:00:26 NadekoStrings | Loaded 26 languages in 0.09s
0 10:00:26 NadekoBot | All services loaded in 1.81s
0 10:00:26 NadekoBot | Shard 0 connected in 4.99s
0 10:00:29 NadekoBot | Shard 0 ready.
0 10:00:35 SelfService | Created 2 out of 2 owner message channels.
0 10:26:25 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ai-chat [470038697530884097]
UserId: Victor#4630 [297802354261229569]
Message: <@469486583884808192> hi
0 10:26:25 CommandHandler | User [Victor#4630] executed [<@469486583884808192> hi] in [ChatterBotService]
0 10:26:57 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ai-chat [470038697530884097]
UserId: Victor#4630 [297802354261229569]
Message: <@469486583884808192> im fine
0 10:26:57 CommandHandler | User [Victor#4630] executed [<@469486583884808192> im fine] in [ChatterBotService]
0 10:27:31 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ai-chat [470038697530884097]
UserId: Victor#4630 [297802354261229569]
Message: <@469486583884808192> pats head
0 10:27:31 CommandHandler | User [Victor#4630] executed [<@469486583884808192> pats head] in [ChatterBotService]
0 10:29:48 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ai-chat [470038697530884097]
UserId: Victor#4630 [297802354261229569]
Message: <@469486583884808192> what
0 10:29:48 CommandHandler | User [Victor#4630] executed [<@469486583884808192> what] in [ChatterBotService]
0 10:30:34 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ai-chat [470038697530884097]
UserId: Victor#4630 [297802354261229569]
Message: <@469486583884808192> hugs
0 10:30:34 CommandHandler | User [Victor#4630] executed [<@469486583884808192> hugs] in [ChatterBotService]
0 11:05:26 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ndm [466572640187056129]
UserId: Emily#0632 [435977029985370153]
Message: <@469486583884808192>  hugs
0 11:05:27 CommandHandler | User [Emily#0632] executed [<@469486583884808192>  hugs] in [ChatterBotService]
0 11:06:11 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ndm [466572640187056129]
UserId: Emily#0632 [435977029985370153]
Message: <@469486583884808192> holds
0 11:06:11 CommandHandler | User [Emily#0632] executed [<@469486583884808192> holds] in [ChatterBotService]
0 11:07:51 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ndm [466572640187056129]
UserId: Emily#0632 [435977029985370153]
Message: <@469486583884808192> rubs head
0 11:07:51 CommandHandler | User [Emily#0632] executed [<@469486583884808192> rubs head] in [ChatterBotService]
0 11:08:22 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ndm [466572640187056129]
UserId: Emily#0632 [435977029985370153]
Message: <@469486583884808192> love you too sweety
0 11:08:22 CommandHandler | User [Emily#0632] executed [<@469486583884808192> love you too sweety] in [ChatterBotService]
0 11:08:42 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ndm [466572640187056129]
UserId: Emily#0632 [435977029985370153]
Message: <@469486583884808192> e yes
0 11:08:42 CommandHandler | User [Emily#0632] executed [<@469486583884808192> e yes] in [ChatterBotService]
0 11:09:26 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ndm [466572640187056129]
UserId: Emily#0632 [435977029985370153]
Message: <@469486583884808192> emily
0 11:09:26 CommandHandler | User [Emily#0632] executed [<@469486583884808192> emily] in [ChatterBotService]
0 11:09:52 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ndm [466572640187056129]
UserId: Emily#0632 [435977029985370153]
Message: <@469486583884808192> head pats
0 11:09:52 CommandHandler | User [Emily#0632] executed [<@469486583884808192> head pats] in [ChatterBotService]
0 11:10:40 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ndm [466572640187056129]
UserId: Emily#0632 [435977029985370153]
Message: <@469486583884808192> Your name is Anrew?
0 11:10:40 CommandHandler | User [Emily#0632] executed [<@469486583884808192> Your name is Anrew?] in [ChatterBotService]
0 11:11:08 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ndm [466572640187056129]
UserId: Emily#0632 [435977029985370153]
Message: <@469486583884808192> No your name is Grace
0 11:11:08 CommandHandler | User [Emily#0632] executed [<@469486583884808192> No your name is Grace] in [ChatterBotService]
0 11:12:30 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ndm [466572640187056129]
UserId: Emily#0632 [435977029985370153]
Message: <@469486583884808192> Who is your dad?
0 11:12:30 CommandHandler | User [Emily#0632] executed [<@469486583884808192> Who is your dad?] in [ChatterBotService]
0 11:13:07 ChatterBotService | CleverBot Executed
Server: Aiuchi/MazeMoi Official Discord [466572639016583169]
Channel: ndm [466572640187056129]
UserId: Emily#0632 [435977029985370153]
Message: <@469486583884808192> Who is your mom?
0 11:13:07 CommandHandler | User [Emily#0632] executed [<@469486583884808192> Who is your mom?] in [ChatterBotService]
0 11:15:27 ChatterBotService | Error in cleverbot
0 11:15:27 ChatterBotService | Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NadekoBot.Modules.Games.Common.ChatterBot.OfficialCleverbotSession.<Think>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Games.Services.ChatterBotService.<TryAsk>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Games.Services.ChatterBotService.<RunBehavior>d__18.MoveNext()
0 11:17:31 ChatterBotService | Error in cleverbot
0 11:17:31 ChatterBotService | Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NadekoBot.Modules.Games.Common.ChatterBot.OfficialCleverbotSession.<Think>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Games.Services.ChatterBotService.<TryAsk>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Games.Services.ChatterBotService.<RunBehavior>d__18.MoveNext()

**Comment by Kwoth** [comment]
It can't crash the bot. It's probably your internet connection dying for some time. I've reduced the error message in the next patch though.

**Comment by TamaKaiNya** [comment]
windows 10 x64
4GB DDR3 RAM
500GB HDD
i3
only purpose is to run the bot 24/7
it's a laptop that just sits on my desk
