### ISSUE TITLE
Nadeko won't say anything

### ISSUE THREAD

**Issue by jjrocker123** [Kwoth/NadekoBot#2449]
For some reason, no nadeko commands are working except for .help and .prefix :( the bot has all permissions and i can't see the issue

**Comment by Kaoticz** [comment]
![image](https://user-images.githubusercontent.com/1812311/43178737-3c45b4f0-8fa5-11e8-9f0e-f037894b6192.png)
This issue is more fit for Nadeko's Discord server. GitHub is for bug reports.
Invite: https://discord.gg/nadekobot
