### ISSUE TITLE
reaction event ignoring specified duration

### ISSUE THREAD

**Issue by EcoNadder77** [Kwoth/NadekoBot#2456]
The self-hosted Nadeko bot (v2.26.1) ignores any specified duration of time when executing reaction events.

**Comment by Kwoth** [comment]
??? Is this a feature request?

**Comment by UnbendableStraw** [comment]
I believe this is part of the eventstart command and it is just a feature that exists already but doesn't work

![screen shot 2018-07-26 at 8 39 02 am](https://user-images.githubusercontent.com/22043907/43272664-690589b0-90af-11e8-8e99-8b74100d0e97.png)

**Comment by EcoNadder77** [comment]
Yea, this isn't a feature request. It's a bug report.

And no, I did not restart or disconnect the bot at any time during the reaction event.

**Comment by Ranger3217** [comment]
@Kwoth I just tested this, it's not stopping the event after the specified time. Looks like a bug.

**Comment by Kwoth** [comment]
Ok thanks
