### ISSUE TITLE
Crypto command not pulling correctly

### ISSUE THREAD

**Issue by DLCoates1** [Kwoth/NadekoBot#2458]
I'm into an ERC-20 utility token called Refereum (RFR) and I'm a big help in their community. As of late, I've noticed that there is a Crypto command in Nadeko. When attempting to use it to track stats of cryptos, I notice I can pull all kinds and that it uses coinmarketcap to get the info. However when attempting to check Refereum, it states "Cryptocurrency with that name was not found." I find this odd if it's pulling from coinmarketcap since Refereum is listed there. https://coinmarketcap.com/currencies/refereum/#markets
Is there a way to add cryptos to this command? Or can it possibly be updated in a future patch/version to include this crypto? It's been around for nearly a year now and I still can't get the command to work for it.

**Comment by Kwoth** [comment]
Crypto command needs work. I'll consider this a bug since there is only a limited number of cryptos supported.

**Comment by DLCoates1** [comment]
Since you asked, I guess some realistic ideas for the crypto command would be not much different then it is now. Maybe add a direct link to the page on coinmarketcap. As well as a way for users to add a crypto to the tracker or customize their tracker with various cryptos such as .crypto add <Link>, .crypto remove <crypto name> etc. similar to the twitch channel tracker.

**Comment by ia03** [comment]
This seems to be caused by CryptoData obtaining data from https://api.coinmarketcap.com/v1/ticker/, which only shows the first page of 100 results.

Also, the API being used will be taken offline on November 30th.

**Comment by DLCoates1** [comment]
@ia03 I believe they're just coming out with a new version, hence why it's being taken off. However currently you can use the api from each individual coin rather than that first 100 page with the method I suggested above for adding your own coins to track. Little customization thing.

**Comment by Kwoth** [comment]
![image](https://user-images.githubusercontent.com/2537696/43358992-e5ebe91c-92c4-11e8-8dd0-bdbcc0c8e045.png)
