### ISSUE TITLE
NSFW image autopost

### ISSUE THREAD

**Issue by ClaszyClover** [Kwoth/NadekoBot#2461]
I have it set to post every hour. It will post at the same minute of the hour but at a random hour instead of on each hour. 

Its set to 3600 seconds. Lasts posts it did were at 2:59, 3:59, 7:59, 10:59, 12:59

**Comment by MaybeGoogle** [comment]
Check to see if your bot is down at those times. You can use `.stats` to check uptime and determine when it most recently came back up.

**Comment by ibigfire** [comment]
If it had gone down it would have stopped completely.  That's actually something I've been meaning to report but haven't gotten around to it yet, that the bot stops its NSFW autopost schedule when it dies or needs to be rebooted or whatnot.  Which wouldn't be so bad if you could re-set up the schedule easily but if you want it to post at specific times it becomes pretty tricky to re-set up again.

**Comment by Kwoth** [comment]
That's not true. the timer doesn't stop if it errors.

**Comment by ibigfire** [comment]
My apologies, I meant that in response to MaybeGoogle's suggestion about the bot fully going down.
