### ISSUE TITLE
.acr should have higher priority than customreactions

### ISSUE THREAD

**Issue by RoseBox** [Kwoth/NadekoBot#2466]
.acr allows custom reactions to trigger. Tried getting around this by disabling the actualcustomreactions module in a channel, and adding a permission to enable .acr higher than that in the same channel.
https://cdn.discordapp.com/attachments/117523346618318850/473055935426985984/20180729_021303.jpg
https://cdn.discordapp.com/attachments/465013853281845258/473059570554634250/20180729_022853.jpg

**Comment by Kwoth** [comment]
Can't reproduce. You probably have a custom reactions called '.acr' that's why it doesn't work.

**Comment by RoseBox** [comment]
Sorry, I should’ve mentioned that I have previous custom reactions set to trigger with .crca.

E.g.
🔹Reaction 1 to is set to trigger whenever "straight Jojo" is found within the message body.
🔹I attempt to add a second reaction to "straight Jojo", .acr "straight Jojo" Test.
🔹Instead of adding a new custom reaction, Nadeko returns Reaction 1.

**Comment by RoseBox** [comment]
For reference, here are all the custom reactions on my server that begin with punctuation.
https://cdn.discordapp.com/attachments/465013853281845258/473216126025859072/20180729_125041.jpg

**Comment by RoseBox** [comment]
I think this is the same issue that was closed three months ago:
https://github.com/Kwoth/NadekoBot/issues/2280

**Comment by Kwoth** [comment]
#2172
