### ISSUE TITLE
%mention% placeholder does not work correctly when bot has a server specific nickname.

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#2472]
![1](https://i.imgur.com/NY3E75b.png)

**Comment by Kaoticz** [comment]
I don't see `%mention%` in the [placeholders list](https://nadekobot.readthedocs.io/en/latest/Placeholders/).
What is it supposed to do?

**Comment by Midoriin** [comment]
It's one of the old placeholders, works the same way as `%bot.mention%`

**Comment by Kwoth** [comment]
It's one of the old 'issues' but nothing i can do about it. If you want the bot to reply properly with a server nickname, you will have to manually use <@!botid> instead of bot.mention
