### ISSUE TITLE
Error when  trying to run Nadeko on RPi3 Ubuntu 16.4

### ISSUE THREAD

**Issue by sleepymanakete** [Kwoth/NadekoBot#2473]
Hi, I was following the steps in #1203 and when I run `dotnet run -c Release` I get this message and I'm not sure on how to fix it.
![image](https://user-images.githubusercontent.com/30272172/43553634-33360d2a-95ad-11e8-90e3-09aacf75180b.png)

**Comment by Kwoth** [comment]
It has noting to do with the bot. 

https://github.com/dotnet/cli/issues/9376

just a 2 seconds google search found this issue.
