### ISSUE TITLE
Owner channels

### ISSUE THREAD

**Issue by Prometheus112358** [Kwoth/NadekoBot#2477]
I'm having issues with the credentials file, I'm trying to use the docker method of setting this up, using 2 owner IDs and I've set it up multiple times so far but every time I do so it tells me that there are no owner channels set up in the credentials.json file. I've deleted the image and re-pulled it, I've even deleted the VM and remade that but none of it seems to change the fact that it is not reading owner channels for me and my friend and saying I might need to check the IDs.
![image](https://user-images.githubusercontent.com/42060524/43633456-4a4ef6c2-96d7-11e8-82f8-0ed78e29cfef.png)

**Comment by Gremagol** [comment]
Have you invited your bot to one of your servers?

**Comment by shivaco** [comment]
Invite the bot to your server.

**Comment by Kaoticz** [comment]
Bot won't work if it isn't already in a server.

**Comment by mstarbuck13** [comment]
You need to invite the bot before initializing. ;)
