### ISSUE TITLE
Prune causes error

### ISSUE THREAD

**Issue by mstarbuck13** [Kwoth/NadekoBot#2478]
Basically, two consecutive prunes to remove some embarrassing self host gambling resulted in this error:

https://cdn.discordapp.com/attachments/117523346618318850/474869027072901121/unknown.png

**Comment by xnaas** [comment]
I can spam the shit out of `.prune` without any errors...what version is your bot?

**Comment by mstarbuck13** [comment]
Newest. Updated just before that.

**Comment by xnaas** [comment]
<img width="548" alt="image" src="https://user-images.githubusercontent.com/8271327/43647105-445bf862-96fc-11e8-903f-fd7426a0033a.png">

Maybe something is wrong with your redis install? You can try a reinstall of it, but there's also some "flushall" command I've seen @Kwoth recommend a few times...can't recall off-hand. Should be in plenty of old tickets/issues though.

**Comment by Kwoth** [comment]
This doesn' t look like bot's error at all, more like somethign wrong with your PCs interwebz or disk space, since redis is complaining too.

**Comment by Gremagol** [comment]
Kwoth, prune is broken as fuck. My bot's shard always restarts after pruning. And no, I didn't change anything in that CS file. I'm having that issue for almost a month. Here is a proof:
![image](https://user-images.githubusercontent.com/24619854/44519035-22ab7000-a6cc-11e8-9c8e-05888b3951ac.png)
