### ISSUE TITLE
.economy shows decimal currency

### ISSUE THREAD

**Issue by mstarbuck13** [Kwoth/NadekoBot#2479]
Pretty self explanatory, but . economy is showing decimal currency.

**Comment by Kwoth** [comment]
Screenshot

**Comment by mstarbuck13** [comment]
https://cdn.discordapp.com/attachments/437343601769447425/474934830694531107/image.png

Right now it is resolved because somehow the bot had distributed decimal currency. 
Once the decimal currency is removed, it cleared 

https://cdn.discordapp.com/attachments/437343601769447425/474935152426876928/image.png
