### ISSUE TITLE
Bot automatically restarting upon raid 

### ISSUE THREAD

**Issue by Nitrosine** [Kwoth/NadekoBot#2483]
Ever since updating from v2.13.8 to v2.25.2 and then v2.26.0 we've been having an issue that causes the bot to restart when many members join (raid). It'll autorestart fine but this causes the ban, mute, antispam and antiraid commands to no longer function so it's a major issue for our server. 

Screenshot attached of the bot running the startup commands repeatedly:
![image](https://user-images.githubusercontent.com/29689821/43674451-61dcedbe-97d4-11e8-80b5-c0736e7f9834.png)

**Comment by Kwoth** [comment]
What kind of server are you running your bot on? My first assumption is that if you're running it on a 5$ digitalocean server and you have a lot of things happening, your vps specs are just too weak to handle it.

If it's not that, then i'll look into it.

**Comment by Nitrosine** [comment]
This is the only bot running on the server currently, previously we ran version v2.13.8 on a server with 1GB of ram and it did not do this. As this started happening on the old 1GB server, we decided to upgrade to a server which has the following specs: 4 x86-64 cores, 4GB memory, 200Mbit/s. Thank you for your time. We highly appreciate it.

**Comment by evacfk** [comment]
Had a similar issue today. 

http://pastebin.com/hirGdrAm

We had about 500 users raid our server today. Antiraid got about 100 of them. But then it stopped working.

All the other bots on my box continued to function except nadeko.

Nadeko completely froze up and restarting the process through systemd made nadeko start working again. 

Any insight would be appreciated.

**Comment by rjt-rockx** [comment]
Can confirm, happened on 2.27.3 as well. 
Although this was on a 2GB RAM, 2 core VPS with 200 MBit/s bandwidth so I'm guessing it might not have to do with the specs.

**Comment by zzaagg** [comment]
Me too, I make sure when i'm away from my house i have no other programs running but nadeko to try and stop this problem, but even so much as a leave and join bot spam breaks it.

**Comment by zzaagg** [comment]
I have figured it out,
@Nitrosine Are you logging all events in the log channel? My bot always logged everyone who joined until I cut it off, and ever since the raid protect has been working much better!

**Comment by Kwoth** [comment]
This will be solved by default in 3.0, I won't rework antiraid until then as it would be a huge waste of time. Hang in there.
