### ISSUE TITLE
.sargn does not change group name.

### ISSUE THREAD

**Issue by shivaco** [Kwoth/NadekoBot#2487]
`.sargn 0 Testing` gives no response __on public Nadeko__.
![you_broke_it](https://i.imgur.com/Tyvd7An.png)
The command, however, works perfectly on 2.27.3 self-host.
![you_probably_did_not_break_it](https://youtube.finally-fucking.works/o4rhxxm9.png)

**Comment by Kwoth** [comment]
This was fixed in 2.7.5

**Comment by zergling-man** [comment]
https://puu.sh/Bc12V.png
Not fixed in 2.27.5.
