### ISSUE TITLE
Anonymous warn/ban commands

### ISSUE THREAD

**Issue by hflw** [Kwoth/NadekoBot#2489]
Currently Nadeko will include the user that sent the warn/ban in the DM to the receiving user, it'd be great if there was a way to disable this as an option. I've found that mods tend to not want to warn people due to personal backlash that they might get, and this would make things easier for them.

**Comment by Kwoth** [comment]
No, as it's open another possibility, mods going rogue and warning people for no reason without knowledge. Also this is a place for bugs. featurehub is for features.
