### ISSUE TITLE
Bot does not update, gives 1 warning and 1 error

### ISSUE THREAD

**Issue by DarkFamiliarity** [Kwoth/NadekoBot#2490]
`CSC : warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer cannot be created from /root/.nuget/packages/microsoft.entityframeworkcore.analyzers/2.1.1/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/home/darkfamiliarity/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]
Modules/Music/Music.cs(316,27): error CS0121: The call is ambiguous between the following methods or properties: 'IMessageChannelExtensions.SendPaginatedConfirmAsync(ICommandContext, int, Func<int, EmbedBuilder>, int, int, bool)' and 'IMessageChannelExtensions.SendPaginatedConfirmAsync(ICommandContext, int, Func<int, Task<EmbedBuilder>>, int, int, bool)' [/home/darkfamiliarity/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]
    1 Warning(s)
    1 Error(s)`

Bot is running CentOS 7. Nadeko bot discord redirected me here to post the issue.

**Comment by Kwoth** [comment]
Can you try updating your prerequisites?

**Comment by Kaoticz** [comment]
Do options 4 and 1 and watch out for any warnings/errors during installation.

**Comment by DarkFamiliarity** [comment]
I just ran the prerequisites installer and it reported no errors. The installer reports that the installation was successfully completed. Option 1 also gives no errors and says build successful. Seems like the bot runs fine now, that is weird. The issue can be closed as the bot seems to be working fine now, thanks.

**Comment by Kaoticz** [comment]
You can close it yourself. It's next to the "comment" button.
