### ISSUE TITLE
youtube-dl errors

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#2492]
I'm not sure if those are some important errors or not. It happened while queueing a playlist with `.pl`
![1](https://gtaodiscord.com/u/ed900d4bdf8c.png)

**Comment by Kwoth** [comment]
I wonder what kind of crap was inputed, but you can ignore it, basically means invalid url.

**Comment by Kaoticz** [comment]
It might have been a deleted video, that's why it has returned invalid URL.
(Yes, YouTube keeps deleted videos on playlists for some fucking reason :retardEyes:)

**Comment by Midoriin** [comment]
It was a `.pl` command with a keyword. So bot pulled these videos from Youtube. It wasn't a manual input. So that basically that means youtube API is also able to provide deleted videos with keywords? Interesting. Thanks for your answer @Kwoth ♥
