### ISSUE TITLE
Bot can't Start anymore

### ISSUE THREAD

**Issue by SpielefreakJ** [Kwoth/NadekoBot#2494]
After Updating Nadeko to the newest version (08.08.2018 19:00 UTC+2)

Warning (not so important/able to start):
CSC : warning CS8032: Eine Instanz des Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer-Analyzers kann nicht aus /home/justin/.nuget/packages/microsoft.entityframeworkcore.analyzers/2.1.1/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll erstellt werden: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/home/justin/NadekoInstall_Temp/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]

Error:
Modules/Music/Music.cs(316,27): error CS0121: Der Aufruf unterscheidet nicht eindeutig zwischen den folgenden Methoden oder Eigenschaften: "IMessageChannelExtensions.SendPaginatedConfirmAsync(ICommandContext, int, Func<int, EmbedBuilder>, int, int, bool)" and "IMessageChannelExtensions.SendPaginatedConfirmAsync(ICommandContext, int, Func<int, Task<EmbedBuilder>>, int, int, bool)" [/home/justin/NadekoInstall_Temp/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj]

(i hope the german text won't hurt ya)

**Comment by Kaoticz** [comment]
Have you done options 4 and 1, in that order?

**Comment by SpielefreakJ** [comment]
ofc, otherwise i wouldn't reference it to 2490

**Comment by Kwoth** [comment]
This is an issue when your dotnet sdk is not updated, which means you either didn't run 4 (install prerequisites) or you're running the old script. Use the script as it's in the guide (by referencing it from github, not by using your local one you downloaded months ago)

**Comment by SpielefreakJ** [comment]
Fix:
Update .Net SDK
# `sudo apt-get install apt-transport-https`
# `sudo apt-get update`
# `sudo apt-get install dotnet-sdk-2.1` (or higher)
