### ISSUE TITLE
.gc command can't disable channel to generate currency in v2.27.5

### ISSUE THREAD

**Issue by forleong** [Kwoth/NadekoBot#2497]
Hi, I had host on my linux server.
Just update to version 2.27.5 and .gc command keep saying "Currency generation has been disabled on this channel.".
And I use .gclist for checking, that channel is still in there.
Looks like once I had enable it, I can't disable it.

ps. I had try to fix that out by remove the sql data in db, and it works!

**Comment by Kwoth** [comment]
This was fixed in 2.27.7
