### ISSUE TITLE
Stream notifications

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#25]
Twitch/youtube/hitbox notifcations

suggested by ૨σ૮ҡყ รεɳʝµ and  phil_Pi

**Comment by Melaghan** [comment]
I third this suggestion. More so on the Hitbox going live notification cause I use that instead of Twitch ;)

**Comment by Kwoth** [comment]
Added hitbox. Checkign out how hard it will be for youtubegaming/twitch

**Comment by Kwoth** [comment]
youtube gaming left
