### ISSUE TITLE
Is it possible to self-host NadekoBot on Heroku?

### ISSUE THREAD

**Issue by a15945675321** [Kwoth/NadekoBot#2500]
Is it possible to self-host NadekoBot on Heroku?

**Comment by shivaco** [comment]
Questions like this should go to channel #help in [NadekoBot support server](https://discord.gg/nadekobot).
There is a [really old version, which is 1.3b](https://github.com/ScarletKuro/NadekoBot) working on Heroku. However, that will not work if your server has categories.
