### ISSUE TITLE
okcolor/errorcolor values always revert back to default after restarting the bot

### ISSUE THREAD

**Issue by RapthorneLightweaver** [Kwoth/NadekoBot#2501]
I run a self hosted nadekobot on Ubunto 16.04, updated to the most current version of everything as of this ticket being posted. Every time I restart my bot, the okcolor and errorcolor values will reset back to the standard green/red, even if I have manually changed them directly in the nadekobot.db file. These two values are the only thing that reverts from all available settings to change via .bce

to replicate:
use bce command to change errorcolor or okcolor to anything other than the default, trigger an ok or error message to confirm the change, restart the bot, and use a command that would bring up an ok or error prompt, observe that the colours have reverted back to their default values

**Comment by Kwoth** [comment]
How did nobody notice this bug for months?? thanks.

**Comment by Kaoticz** [comment]
People notice. They just don't bother reporting it.
I've had taken like 3 to 4 reports like this in #help.  :GWchadThink:
