### ISSUE TITLE
Stuck on shard 0 logging in

### ISSUE THREAD

**Issue by ccluong** [Kwoth/NadekoBot#2505]
When I start NadekoBot, it gets stuck on "Shard 0 logging in" like this:

-1 22:40:17 ShardsCoordinator | Starting shard 0, 0 more in queue.
0 22:40:30 NadekoBot | Shard 0 logging in ...
-1 22:41:42 ShardsCoordinator | Shard 0 is scheduled for a restart because it's unresponsive.
-1 22:41:45 ShardsCoordinator | Auto-restarting shard 0, 1 more in queue.
0 22:41:48 NadekoBot | Shard 0 logging in ...
-1 22:43:12 ShardsCoordinator | Shard 0 is scheduled for a restart because it's unresponsive.
-1 22:43:13 ShardsCoordinator | Auto-restarting shard 0, 1 more in queue.
0 22:43:16 NadekoBot | Shard 0 logging in ...

I've tried disabling anti-virus, reinstalling NadekoBot, and reinstalling Redis.

I am on the latest version of Windows 10.

**Comment by PotatoGaming2079** [comment]
@ccluong  Are you using windows 7?

**Comment by samdivaio** [comment]
Try a vpn, seems like isp connection issue if not firewall.

**Comment by ccluong** [comment]
I've tried a VPN and allowing it through firewall and it still has the same problem.

**Comment by ccluong** [comment]
Ended up resetting PC to fix some other things and it also fixed this issue.
