### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by TuiFire** [Kwoth/NadekoBot#2506]

**Comment by Kwoth** [comment]
This error looks impossible. I'll wait to see if someone else gets it

**Comment by MaybeGoogle** [comment]
Could you send what `NadekoBot/NadekoBot.Core/Modules/Gambling/WaifuClaimCommands.cs` has on lines 204-206? opening the file in textedit is fine if you don't have a code editor. Like Kwoth said, This error seems impossible. (with the latest code anyway)
