### ISSUE TITLE
[Suggestion] Add an AM:PM time placeholder

### ISSUE THREAD

**Issue by StevenKvodo** [Kwoth/NadekoBot#2508]
I use an embed message as my .greetmsg and in the bottom I have the time they joined, but the best I can do with placeholders in with the %server.time%, but it just says my current timezone rather then AM:PM.
Would be amazing if you could add that in future builds

**Comment by Kaoticz** [comment]
Suggestions go to FeatHub
https://feathub.com/Kwoth/NadekoBot

Please close this ticket.

**Comment by Kwoth** [comment]
O.o isn't it 24-hour?
