### ISSUE TITLE
Server level command disabled still trigger command error.

### ISSUE THREAD

**Issue by Taknok** [Kwoth/NadekoBot#2509]
**Full version :** On my server people of write `...` to express frustration etc, at this moment the bot trigger the command and display `Command Error The input text has too few parameters.`. We don't use the `...` command so I decided to disable it with `.sc "..." disable`. But even with it disabled `Command Error The input text has too few parameters` show up. I have to deactivate error messages (`.ve`) which I don't really want, because it's really helpful for others commands. I just want to disable 1 command and has no message when it is used correctly or not. Changing the order of permission checking and command validity should solve this.

**Sort version :** 
- I want to disable `...` =>  `.sc "..." disable`
- Write `...` trigger `Command Error The input text has too few parameters.`
- I expected nothing showing up due to command disabled on server level. I think this is more user-friendly to disable errors messages of a disabled command.

**Comment by Kwoth** [comment]
Try .gcmd

But that's just how it works.
