### ISSUE TITLE
Possibly broke betflip in latest version

### ISSUE THREAD

**Issue by StevenKvodo** [Kwoth/NadekoBot#2510]
Normally I wouldn't report for it, but it happened with multiple people one by one.
I'm self-hosting my bot on the current latest version of Nadeko. I've updated it today.
After the update literally 9/10 of the times that you bet on H in bet flip you will win, 5 different people from my server have gotten from 10k to 100m+ just by bet flipping, other gambling methods didn't seem to change. I was testing for hours and came to the conclusion that it's not the whole bet flip that is broken, it's just H. One of the users in my server has started with 10k and all in bet flipped on h 10 times in a row and won all of them, since then other users have done the same and got to 100m+. 9/10 of the times that they bet on H they win when they bet on T it's basically 2/10 of the times.

![screenshot_1](https://user-images.githubusercontent.com/40173191/44125722-ccfd899e-a03c-11e8-8a2b-93611bd94698.png)
![screenshot_2](https://user-images.githubusercontent.com/40173191/44125786-2ac05f34-a03d-11e8-93b2-d16272bd055d.png)

**Comment by Kwoth** [comment]
Can't reproduce, but i've made betflip generate a number from 0 to 999 in the next version just in case.
