### ISSUE TITLE
Currency generation issue

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#2511]
When you use `.gc` in a channel for the first time, it successfully enables the currency generation. But after disabling it once, you're not able to enable it again.
![1](https://gtaodiscord.com/u/222b2ec97e43.png)
v2.27.5

**Comment by Kwoth** [comment]
can't reproduce. Maybe it was fixed in one of the patches I didn't push yet. Just wait for the next one and update.
