### ISSUE TITLE
Repeats are locked

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#2512]
Might have just been that you didn't clear all the nulls, or maybe the entire issue still exists. same issue as before.

329839820308480000 is the sid having the problem.

Recap for if you forgot or for those who might also have the problem:
- No repeat messages are sending 
- No repeat-related commands work.

**Comment by Kwoth** [comment]
Yea, i didn't fully fix the bug in that patch, but nadeko was already updated. I cleared all bugged repeaters again manually. Next time nadeko is restarted this problem should completely go away.
