### ISSUE TITLE
Custom hosted nadeko not displaying text for some commands

### ISSUE THREAD

**Issue by Kirjava444** [Kwoth/NadekoBot#2514]
Hello,

A server that I moderate in has a custom version of nadekobot hosted by somebody in another server that we've been using with their permission. We're having an issue with it not displaying responses for all commands - the server greeting message works, .avatar works, .checkperms works; however, .uinfo and .sinfo don't display anything, .listperms doesn't work (server owner/admin tried it and nothing happened). 

Commands like .iam and .iamnot do add/remove roles properly, but the bot doesn't display a message confirming the addition or removal. Any ideas on how we can fix this on our end?

Thank you

**Comment by Kirjava444** [comment]
Thanks! We weren't able to find a solution; the bot is working as normal on the owner's server. In the end we just decided to use the public Nadeko instead, since the only thing the custom one had that was much different was the avatar and name

**Comment by Kwoth** [comment]
Yea it's either a bot, or server permission issue.
