### ISSUE TITLE
".take all" removes currency equal to command authors currency

### ISSUE THREAD

**Issue by mstarbuck13** [Kwoth/NadekoBot#2515]
When using a ".take all Kotz" You would expect to make Kotz go broke. 
However, the bot only takes the amount of currency the bot owner using the command has. 

EX: 

Kwoth has 69 Flowers. 
Kotz has 100. 

Kwoth: .take all Kotz
Bot takes 69 flowers. 

If Kwoth has 100 and Kotz has 69, bot errs and says Kotz is too broke to take that amount. 

Screenshots from my examples are attached: 

![image 2](https://user-images.githubusercontent.com/19699010/44314995-847a8a00-a3ed-11e8-9c41-2d3d6a65784a.png)
![image1](https://user-images.githubusercontent.com/19699010/44314996-91977900-a3ed-11e8-82e1-d4cad56d0096.jpg)
![image0](https://user-images.githubusercontent.com/19699010/44314997-952b0000-a3ed-11e8-9a06-ccab1334c5ac.png)

**Comment by Kwoth** [comment]
that's just how it works. wont fix.
