### ISSUE TITLE
Catch ALL errors occuring in the program and resolve them in order to improve performance.

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#252]
Letting exception happen and then catching them is bad. Preventing them is much better.

**Comment by appelemac** [comment]
:scream: He finally realised!

**Comment by Kwoth** [comment]
bfa4622c4f57706a13a2604f8c9d5d5c44704e30 this helps a lot
Also built into discord.net lib to not send messages to channels you don't have sendmessage permission for.

**Comment by Kwoth** [comment]
Fixed quite a few more stuff. Console should be mostly clear now. v+t is still causing some issues with a lot of errors when triggered on some servers.

**Comment by Kwoth** [comment]
Pretty much all errors occurring are either in library, http exception (403, 404, 422) or intentional.
