### ISSUE TITLE
Problem with waifu commands.

### ISSUE THREAD

**Issue by CuchuuN** [Kwoth/NadekoBot#2520]
https://i.gyazo.com/594f12fe66f0cda6b8d1836015f24c67.png

This is what I get when I do .waifuinfo. Not sure what causes it, since I can't read it.
Hopefully could get help ASAP.

**Comment by Kwoth** [comment]
Is that the whole error?

**Comment by CuchuuN** [comment]
Yes, It is the whole error. Sometimes, if I try to claim a waifu, it gives some kind of int32 error. Didn't get it in time and accidentally closed my bat file for Nadeko.

**Comment by Kwoth** [comment]
I'm dumb it wasn't fixed, it's gonna get fixed now.
