### ISSUE TITLE
.gmod gives error when enabling it

### ISSUE THREAD

**Issue by Jengas** [Kwoth/NadekoBot#2524]
Latest version 2.28
![image](https://user-images.githubusercontent.com/14033756/44465322-83c83a80-a61d-11e8-8b77-923b3da85933.png)

**Comment by mstarbuck13** [comment]
Can confirm. 

On my end. Bot responds in chat disabling gambling. But when enabling no response. Both enable and disable throw the same error.

**Comment by Jengas** [comment]
@mstarbuck13 yep 
![image](https://user-images.githubusercontent.com/14033756/44466765-69905b80-a621-11e8-8698-cb0613b67895.png)

**Comment by Kwoth** [comment]
Fixed in 2.28.1

**Comment by Jengas** [comment]
![image](https://user-images.githubusercontent.com/14033756/44521146-6d2feb00-a6d2-11e8-8783-a73957cdb83d.png)
Still gives error in 2.28.1

**Comment by Kwoth** [comment]
I'm officially retarded.

**Comment by mstarbuck13** [comment]
Can confirm both the above comments. #KwothTheIncompetent
