### ISSUE TITLE
Selfhost with version 2.28.0 is getting Missing Access errors.

### ISSUE THREAD

**Issue by Gremagol** [Kwoth/NadekoBot#2525]
As I've been told here:
![image](https://user-images.githubusercontent.com/24619854/44479879-25618300-a642-11e8-80f7-5a15119b6e21.png)
I am getting many Missing Access errors from the log module. Zerg told me to open an Issue to talk about a fix or a way to get the server which causes those.
Here is an example of how it looks:
![image](https://user-images.githubusercontent.com/24619854/44480039-87ba8380-a642-11e8-9437-69f9db743ef1.png)
Its actually hard to see which server causes it, when the bot is bigger than the usual... (330 servers and still growing fast)

Hope for some answers. Have a great day!

**Comment by Kwoth** [comment]
That means that the the bot can't send the embeds to where you're logging message deleted events. Logging needs rework anyway.
