### ISSUE TITLE
.waifuinfo is not working for some users

### ISSUE THREAD

**Issue by Kaoticz** [Kwoth/NadekoBot#2526]
This issue is present both on self-hosted bots (**v.2.28.0**) and public Nadeko.
I've joined this guy's server and tried to use `.waifuinfo`. It gave no response on Discord. Nadeko's log registers the command as it had run normally. It also does not work if someone else tries to pull the affected user's waifuinfo. It gets fixed upon giving the affected user any waifu gift.
![github1](https://user-images.githubusercontent.com/1812311/44490989-3e643700-a636-11e8-94a8-db5bb74261ff.png)
![github2](https://user-images.githubusercontent.com/1812311/44490995-42905480-a636-11e8-8be8-1626ac0fec70.png)

For the public Nadeko, 2 people already reported the same in #help. Gifting them waifu items also fixes the issue.

This is just a hunch, but it seems to only affect people who have never interacted with Nadeko before **v2.27.7**.

**Comment by Kwoth** [comment]
Tell him to update again, i fixed a bug but didn't push a new version yesterday. I didn't test it though.

**Comment by Kaoticz** [comment]
The issue has been successfully fixed.
