### ISSUE TITLE
Self hosted bot halves every gift (BUG)

### ISSUE THREAD

**Issue by depths** [Kwoth/NadekoBot#2527]
NadekoBot v2.27.7 is the version. Everyone on our server is getting their gifts halved despite the affinities being set to each other. Was told to report it here-- Can anyone help? 
![6fc11688cd53e4ae3cc525a678eb57b7](https://user-images.githubusercontent.com/2237435/44493651-c0546000-a636-11e8-96d7-64d3d1bbc021.png)

**Comment by Kwoth** [comment]
please read the description of waifugift before making an issue.

**Comment by depths** [comment]
Yes, the description says:
-waifugift / -gift
Gift an item to someone. This will increase their waifu value by 50% of the gifted item's value if you are not their waifu, or 95% if you are. Provide no parameters to see a list of items that you can gift.

On our server, it's still doing 50% if they are your waifu for the gifting value and not 95%. The affinities were also mutual before claims, and it still continues to do 50%.
![screen](https://user-images.githubusercontent.com/2237435/44496240-a3715a00-a641-11e8-9232-7ca3b665369a.jpg)

**Comment by depths** [comment]
![screenbunnie1](https://user-images.githubusercontent.com/2237435/44497141-b128de80-a645-11e8-8d4d-f686671721c8.png)
![screenbunnie2](https://user-images.githubusercontent.com/2237435/44497143-b38b3880-a645-11e8-8aa8-c583ea728b04.png)

Happening to another user, where the Cookie value is 10, and the waifu's value only goes up by 5 even though they claimed each other and have affinities set to each other.

https://gyazo.com/7fb6b5d442a997cc49f0d131b12610fa
