### ISSUE TITLE
Commands?

### ISSUE THREAD

**Issue by Criata** [Kwoth/NadekoBot#253]
Is there a way to give commands to Nadeko without said commands showing up in the general text chat? There are some commands I don't want the people on my server using but if I type the command it general chat they can see the command I entered.

Just wondering if there's any way around this. Thanks.

**Comment by Kwoth** [comment]
You can use permission system to disallow certain commands being used by other roles.

`;rc "!m q" disable all`
`;rc "!m s" disable all`
`;rc "!m q" enable DJ`
`;rc "!m s" enable DJ`

Now only DJ can use `!m q` and `!m s`

Check the command list and comprehensive guide.
