### ISSUE TITLE
XpMinutesTimeout not working

### ISSUE THREAD

**Issue by Waterin** [Kwoth/NadekoBot#2530]
I noticed that the ".bce XpMinutesTimeout" isn't working, I've set it to 1,2,3,4,etc but still the bot is not adding any cool down to it and I had to disable XP temporarily to avoid massive farming

**Comment by mstarbuck13** [comment]
Appears the BCE numberal is doing the cooldown in seconds. Confirmed on my selfhost returning to 28.0.

**Comment by Waterin** [comment]
It wasn't in the "releases" tab so I thought it was a bug, but thanks for checking it for me..

**Comment by mstarbuck13** [comment]
No, that is a bug. :) It should be minutes. Try multiplying it by 60 and seeing what happens as a temporary fix.

**Comment by Waterin** [comment]
yap I'm doing that, but thanks again

**Comment by MavisTail** [comment]
Yes, had to disable it too

**Comment by Kwoth** [comment]
Fixed in 2.28.3 

I wonder for how long this bug existed. : \
