### ISSUE TITLE
.xp redundant output

### ISSUE THREAD

**Issue by HerbalBeverage** [Kwoth/NadekoBot#2531]
I self-host a NadekoBot shard for my own server that isn't used anywhere else. Because of this, I find it a bit redundant for the .xp command to show both global and server XP, since 90% of the time they're going to be the same value. Is it possible to remove the 'Global' output (so that .xpadd still works) and show only your server level? Or even just post an embed similar to .xplb that only shows yourself? If this isn't possible currently, is it relatively simple to add?

**Comment by MavisTail** [comment]
It's possible, go to the Data folder and look for xp_template.json open it and look for `XP --> Global --> Show` and change it from true, to false,
