### ISSUE TITLE
.serverinfo and .listservers showing different member count

### ISSUE THREAD

**Issue by FrozenAtlas** [Kwoth/NadekoBot#2532]
1: Bot Version.
v2.28.3
2: Public Nadeko or Selfhost. 
Selfhost windows server on AWS
3: Supporting Screenshots
![Image of screenshot](https://puu.sh/BjJKj/23b91a51af.png)
4: Any specifics you might think will help Kwoth resolve.
I think that `.serverinfo` is showing total members while `.listservers` is showing online members but that's just my 2c.
PS: referred here by MatthewStarbuck#0001 in the Nadeko help server

**Comment by mstarbuck13** [comment]
Bump so I can follow conversation

**Comment by mstarbuck13** [comment]
For what I've been able to find, the bot pulls LISTSERVERS count from "g.Users.Count" whereas SERVERINFO pulls from "guild.MemberCount.ToString". 

So it would make sense they are pulling from two sources, one being online and the other being total. I'll wait for Kwoth to bump this tommorow.

**Comment by xnaas** [comment]
>Bump so I can follow conversation

FYI there's a "Subscribe" button on the right side of the page. (Or the bottom on mobile?)

**Comment by Kwoth** [comment]
If that's the case ,then listservers is just wrong. Users.Count would just show the number of users who are 'visible' to the bot, so usually offline people won't be in there.
