### ISSUE TITLE
FEATURE: configure the location of redis server

### ISSUE THREAD

**Issue by LordVeovis** [Kwoth/NadekoBot#2533]
Hi,

I'm trying to write a Dockerfile to have a more up-to-date version of Nadeko that what is available from willysunny. At least one by tag.
This new container will be lighter, simpler and only contain the nadeko process, leaving redis for another container, which respect one of the container principles: "1 container = 1 service".

Let's go to the fact. During my test, I've noticed that the redis server is hardcoded in the source code : https://github.com/Kwoth/NadekoBot/blob/1.9/NadekoBot.Core/Services/ShardsCoordinator.cs L81

I think this setting (hostname and optionally also the port) MUST be configurable.
Maybe on the credentials.json file or as an environnent variable (easier to implement ^^) ?

What do you think?

**Comment by Macley-Kun** [comment]
What about this docker? https://github.com/shikhir-arora/Nadecker

Auto updates, easy install (even easier then Linux (aside of installing docker itself)).

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________

**Comment by LordVeovis** [comment]
Thanks for the suggestion but that's still wrong for the other points:
* a container should NOT auto-update itself. The purpose of a tagged container is to exactly know what version is running. An update MUST imply changing the container. In other words: a healthy container is immutable
* redis is still in the same container than nadeko, preventing a good monitoring of the nadeko process (hidden behing the auto-restart.sh). Anyway the auto-restart feature should be controlled by dockerd itself
* well... debian/ubuntu base is klunky at best for a container: either fat or slim with no basic command tool to debug. Currently my image is only 228MB and with a complete linux tools, a quarter of willysunny's.

**Comment by LordVeovis** [comment]
I've been able to starts the container with only Nadeko inside: the bot was able to respond to my .h on Discord.
I had to patch 127.0.0.1 2 times with another hardcoded value (just for testing).
I also had to patch the default ShardRunArguments as the program did not take the one defined in the credentials.json, I don't know why.

```
sed -i 's/127.0.0.1/redis/' NadekoBot/NadekoBot.Core/Services/ShardsCoordinator.cs; \
sed -i 's/127.0.0.1/redis/' NadekoBot/NadekoBot.Core/Services/Impl/RedisCache.cs; \
# for linux, I want dotnet my.dll {0} {1}
sed -i 's!run -c Release --no-build -- !/app/NadekoBot.dll!' NadekoBot/NadekoBot.Core/Services/Impl/BotCredentials.cs
```

Unrelated to this peculiar issue, this makes me think the default ShardRunArguments should be dotnet my.dll instead of dotnet run for the Unix platform. In that way, the sdk is not mandatory anymore, only the runtime.

Currently, this run with this base image: microsoft/dotnet:2.1-sdk-alpine

**Comment by LordVeovis** [comment]
I think this issue is resolved now.
Next merge request will be the Dockerfile :)

**Comment by shikhir-arora** [comment]
@LordVeovis: Didn't see this before but I feel like I need to address some points.

> "a container should NOT auto-update itself. The purpose of a tagged container is to exactly know what version is running. An update MUST imply changing the container. In other words: a healthy container is immutable" 

That's incorrect. You can specify specific tags, but, in general, a huge part of Docker comes from the ability to use tools like watchtower that look for newer images. Also, my setup is optionally auto-updated: it is pushed to the hub but the automatic update in live action comes from watchtower - which you don't have to use. 

https://github.com/shikhir-arora/Nadecker/blob/master/README.md explains the automation process. 

Yes, the container is immutable, but the data is mounted in volumes, so it's a safe upgrade. Furthermore, if anything fails on building, watchtower doesn't pull (only successful tags). Running redis inside Docker is fine, but doing it outside is not an issue either. Redis can be monitored normally - not sure what you mean there by hidden. As far as the auto-restart, I don't see why you'd want to restart the entire container vs. using existing functionality to just restart the bot internally. This also sticks with functionality and current commands. 

As far as size: yeah, it's pretty big due to verbosely installing a ton of dependencies for audio, etc. The baseimage is fairly large but not bad (based on 18.04), and you're right that it could be shrunk using an alpine or like build with dotnet as a container.

**Comment by LordVeovis** [comment]
@shikhir-arora I don't remember why I said the container should NOT auto-update, that does not seems to apply to yours (and YES I know about the :lastest-like tags).

About the monitoring, the PID 1 of a container should be the service itself if possible, that's it redis or nadeko.exe for instance.
If not the case, transmitting a signal (docker kill) to the service can be challenging.

Specifically, how do you monitor a container when there is more than 1 service? If the container is not healthy, (from a docker perspective) it is because of redis or nadeko (or something else)?
If a service is failing, I want to restart only it, (and without hacking with docker exec), that's not possible with a multi-service containers.
Lastly : and if I want to use my own redis? The container should not force me to use it's own redis instance.
There are cases were multi-services containers is the only architecture possible (or the split required too much work), like for librenms. Here the split is easy and that's something I want to address.

I intend to ship a solution based on alpine and dotnet, and directly integrated to Nadekobot's git to automatically trigger builds (tag-builds and latest) with dockerhub.com
I'm not looking to sell my stuffbut this image will be awesome :)
Stay tuned, it's almost ready.

**Comment by LordVeovis** [comment]
@shikhir-arora see the docker proposition at #2556

**Comment by shikhir-arora** [comment]
@LordVeovis Looks nice 👍. For our purposes I build against a slightly customized fork that's managed using Backstroke to automatically be up to date with the upstream - https://github.com/shikhir-arora/Nadecker/blob/master/README.md explains that - so for me it's just approving a PR or making a change, and after Appveyor checks on our fork are passed, GitHub sends a webhook that triggers the build from the above Nadecker repo. Docker's plugin Watchtower runs every two minutes and updates the bot once the latest tag is pushed to Dockerhub, and a webhook is posted on Discord. 

As far as monotoring goes, we use Traefik and have Portainer configured (https://github.com/shikhir-arora/traefikfiles/blob/master/docker/docker-compose.yml)
