### ISSUE TITLE
Name being used twice when checking currency.

### ISSUE THREAD

**Issue by TwinDragon** [Kwoth/NadekoBot#2534]
![discord_2018-08-24_16-40-44](https://user-images.githubusercontent.com/4114117/44609285-a3e23000-a7bc-11e8-91b0-0f849e5dca1c.png)

As seen in the image, when you use `.$` to check how much currency you have, the bot will say your name twice instead of just once.

Using the latest github pull with `.stats` showing v2.28.0.

**Comment by Kaoticz** [comment]
You have 2 instances of your bot running. Please take this kind of issue to the #help channel in our Discord server, GitHub is for bug reports only.
**Invite: https://discord.gg/nadekobot**

**Comment by TwinDragon** [comment]
Fixed in 300f4512af3ba0cca9f63b4ec978acaef1d5c93d so I'll just close this myself.
