### ISSUE TITLE
.xp error

### ISSUE THREAD

**Issue by Jengas** [Kwoth/NadekoBot#2535]
![image](https://user-images.githubusercontent.com/14033756/44617491-7ac8aa80-a863-11e8-9e7c-6c0098bac54f.png)
Everyday this happens. Sometimes in few hours after restart, sometime in few days after restart. `.imagesreload` doesnt help

**Comment by SenorKarlos** [comment]
Per message in discord, I get the same error on various commands, which require a bot restart to correct.

http://prntscr.com/kmupf3

Windows Server 2016, Virtual Environment, using the prebuilt installer/updater, usually at least 25-15% RAM available at all times on it

**Comment by Kwoth** [comment]
Never saw this happen on local or public bot. This only happens when the image you've specified is not an actual image, or website where image is hosted unavailable i guess. Also could happen if you flush your redis cache. while bot is running. (Maybe you're running out of ram?)

**Comment by Jengas** [comment]
Nope. With ram all ok. imgur works good. (https://i.imgur.com/idn8QTq.png). I have never flushed redis cache while bot running
![image](https://user-images.githubusercontent.com/14033756/44948099-41221180-ae18-11e8-95b1-39f72e5ce31a.png)
