### ISSUE TITLE
Running on Mac OS X 10.11

### ISSUE THREAD

**Issue by MistieKitteh** [Kwoth/NadekoBot#254]
When running in xQuartz on Mac OS X 10.11 I get the error:
Failed resolving the link.Cannot perform member binding on `null' value
When running a !m q command. Then it spams me with:
Severity: ErrorMessage: Error handling VOICE_STATE_UPDATE eventExceptionMessage: Object reference not set to an instance of an object

I am pretty sure I set it up properly. I have Mono installed or it wouldn't be running and ffmpeg installed from homebrew. Could this be the issue?

**Comment by Kwoth** [comment]
No idea what xQuarz is, is your bot an official bot account?

**Comment by MistieKitteh** [comment]
My bot is a bot account.

**Comment by MistieKitteh** [comment]
Alright so everything works while running it normally in terminal rather than xQuartz but it doesn't seem to want to join a voice channel... 
`Uptime: 0 days, 0 hours, and 0 minutes.`
`Servers: 0 | TextChannels: 0 | VoiceChannels: 0`
`Commands Ran this session: 0`
`Message queue size: 0`
`Greeted 0 times.` `| Playing 0 songs, 0 queued.`
`Heap: 5.92`

-----------------
Reading from the permission files.
Permission initialization complete.
>>Command !m lo

It ques it and then just sits. I have it as an official bot and it's on two servers

**Comment by Kwoth** [comment]
Make sure your bot has all permissions. (In this case it needs to be able to join to that channel)

**Comment by MistieKitteh** [comment]
Of course. I have everything set up properly. The bot works properly on WIndows. I copied over the config file and am running it now on OS X,

**Comment by Kwoth** [comment]
all issues will go away when we move to .net core after 1.0, so we will stop tracking this
