### ISSUE TITLE
Continuous crashes

### ISSUE THREAD

**Issue by missingbinaries** [Kwoth/NadekoBot#2541]
C# isn't my native language so I'm not able to properly understand and debug just by looking at the error. However, my NadekoBot instance keeps crashing, I believe this is due to a logging failure (`.log` command) as per one of the support agents' view (https://awau.moe/8b95a6.png) 

Here's the error on Hastebin: https://hastebin.com/meqoyaxaci.md

**Comment by Wizkiller96** [comment]
I also, seen the same error pop up in my console randomly couldn't really pinpoint the causes since everything in posts by the bot log command seem to show fine.

**Comment by Kwoth** [comment]
This is when you have presence updates enabled. Seems to be issue with your internet connection.

**Comment by missingbinaries** [comment]
Oh?
