### ISSUE TITLE
Song not found issue.

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#2545]
![1](https://gtaodiscord.com/u/24c56dda6805.png)
It happens every boot. It starts giving this error after a few hours of its boot. The only solution is restarting the bot. v2.28.3

**Comment by Midoriin** [comment]
One more note: Restarting bot with `.die` does not solve the issue. I'm having to kill its session from the server, then reboot the bot manually.

**Comment by Kwoth** [comment]
Means your bot can't find youtube-dl. Seems like you have some server problems 😂

**Comment by Midoriin** [comment]
It happens **after a few hours of its boot**. It doesn't happen at first. I'm pretty sure my youtube-dl is installed properly, because it works fine at first.
