### ISSUE TITLE
The .wheel command has broken odds.

### ISSUE THREAD

**Issue by Bronzdragon** [Kwoth/NadekoBot#2549]
You have an average change of 2.4 * 1.7 * 1.5 * 1.2 * 0.5 * 0.3 * 0.2 * 0.1  = 0.022032 of coming out ahead. As you notice this is very low. To balance out the 0.1 odds, we'd have to have 10x in there. To balance out 0.2, we'd need 5x, etc, etc.

**Comment by Kwoth** [comment]
🤦‍♂️
