### ISSUE TITLE
.crca shouldn't be usable on custom reactions that aren't in the current context

### ISSUE THREAD

**Issue by zergling-man** [Kwoth/NadekoBot#2557]
Though I'd argue that the `.crca` setting for a GCR should be server-specific, and thus be allowed to use those. Not sure about that. For now at least, this is a bug that needs fixing.

Also, should check `.crad` and `.crdm` as well, they're probably the same.

**Comment by Macley-Kun** [comment]
@Kwoth maybe mark this one as bug aswell?
