### ISSUE TITLE
Need help disabling a command or change it's prefix

### ISSUE THREAD

**Issue by bolzi** [Kwoth/NadekoBot#256]
I want to disable or change the prefix of the 'e' command on my server. Any idea how? Thanks in advance.

**Comment by appelemac** [comment]
In the next update you will be able to change/remove the command if you host.

You can disable it with `;sc e disable`

**Comment by bolzi** [comment]
Thanks for the help! It's better than nothing, but now a message shows up saying that the command has been banned.

In english conversation this isn't much of a problem, though. But in other languages a lot of sentences start with "e" and it gets spammy really really quick.

**Comment by appelemac** [comment]
use `;v 0` to disable verbosity
