### ISSUE TITLE
Rename roll command (.renr) doesn't work on roles with a space.

### ISSUE THREAD

**Issue by StephenHall93** [Kwoth/NadekoBot#2560]
Tried a number of times with different roles with the most current version of the bot which I host myself. The bot would process the command but the name wouldn't change, but it'd work with roles that were just one word and no spaces.

**Comment by StephenHall93** [comment]
Thanks for the speedy response! Neither of us could figure it out the other day, good to know it does actually work with quotation marks on both tho! disregard this issue! 👍 

(Should probably update the notes on https://nadekobot.me/commands to reference the need for quotation marks on both role names, not just the first one.)

**Comment by Kaoticz** [comment]
The quotation marks are only necessary if the role has any space in it. Otherwise, it's going to complain there are too many parameters, as it will think each separated word is a different role.

`.renr "Nadeko Test" OhNo` would have worked too
The same goes for `.renr OhNo "Nadeko Test"`

**Comment by StephenHall93** [comment]
Nevermind, this isn't an issue with Nadeko, I've figured out that actually, it's a permission clash. My bad, thanks for the help tho Kaoticz!
