### ISSUE TITLE
Can't plant currency and random currency drops do not appear

### ISSUE THREAD

**Issue by TerminusMan** [Kwoth/NadekoBot#2562]
<img width="324" alt="plant" src="https://user-images.githubusercontent.com/43189566/45392614-83bdc800-b628-11e8-9d3e-3793365c7a09.png">

I am self-hosting Nadeko and the Bot Version is 2.28.4. For some reason I can't plant currency or get currency drops. Everything else Works. I can award myself currency and I can check the leaderboard how much currency I have. I can also aquire dailies. I changed the currency name to be something else, but it also didn't work when I tried the original nadeko Flowers. I've tried moving the database and reinstalling the bot, also planting With a password, nothing Works. Really hope I can get a fix for this as it's really annoying.

**Comment by nerkverse** [comment]
I can also confirm that this has been happening. As of right now has only happened to me twice, Im also self hosting the bot. Not even drops was working the only way i could get this sorted was by resetting the nadeko bot. Hope someone can give some insight in to this problem?

**Comment by cocoatrash** [comment]
I tried deleting the bot and making it again 3 times but I still had the same issue.

<img width="442" alt="screen shot 2018-09-15 at 3 42 31 am" src="https://user-images.githubusercontent.com/38589702/45581214-80ca0e00-b89a-11e8-8f9d-d7dd15e23058.png">

**Comment by mstarbuck13** [comment]
Hi. I have been looking into this. Can you all attempt to replicate this again? This time, show me both what the bot does in Discord chat, and then the screenshot from the terminal? (Terminal as in the actual bot command prompt window? I want to see if there are any errors thrown there. Thanks!

**Comment by Kaoticz** [comment]
From what they've reported in #help, the bot does not react on Discord.
Although it does log the commands normally in the console, with no error message.

**Comment by cocoatrash** [comment]
Kaoticz is right,, but here it is anyways

<img width="477" alt="screen shot 2018-09-16 at 7 55 42 pm" src="https://user-images.githubusercontent.com/38589702/45599359-8c2c4f00-b9ea-11e8-9aca-1046052cfc55.png">
<img width="473" alt="screen shot 2018-09-16 at 7 55 48 pm" src="https://user-images.githubusercontent.com/38589702/45599361-8cc4e580-b9ea-11e8-9f0f-a2865a82919a.png">

**Comment by nerkverse** [comment]
Yeah i've also havent seen any errors.

**Comment by cocoatrash** [comment]
Still doesn't work

**Comment by nerkverse** [comment]
Yeah this is still going on. Only way i seem to fix this problem is by resetting my VM, but i shouldnt have to be doing this everytime.

**Comment by cocoatrash** [comment]
I forgot to mention that along with this, I also can't use currency generation.

**Comment by charliepja** [comment]
I was using the most up to date version of Nadeko, but redownloaded it yesterday and it caused this problem. Rebooting the dedicated server fixed the issue.

I have two servers, both running different bots (not a shard) and I did the same thing to both of them yesterday. But only one of them ran into this problem

**Comment by nerkverse** [comment]
Still doesnt work.

**Comment by Kwoth** [comment]
Kotz figured it out. One or more currency pictures in your images.json are invalid. I'll make a better error soon.
