### ISSUE TITLE
Is the Raspberry pi zero compatible with self host bot? 

### ISSUE THREAD

**Issue by Ming-A** [Kwoth/NadekoBot#2568]
Hey i wanna ask if  the Raspberry pi zero is compatible with nadeko and if there's anyone that could help me with that :) if it is, i might buy one

**Comment by bakabakasama** [comment]
In theory it's possible, but _very very_ unsupported and slow. You're better off getting something else for sure. Consider looking around locally for computers, you'll get better performance.
TL;DR, don't.

**Comment by Kaoticz** [comment]
Not with current Nadeko, because the architecture is not supported.
There is a fork of Nadeko somewhere that supports it, but it's for a very old version (v2.10.0 or older). Not worth the effort, imo.
Related: https://github.com/Kwoth/NadekoBot/issues/1203

**Comment by Kwoth** [comment]
Its not officially supported but it's possible yes, a lot of people did it as you can see in #1203
