### ISSUE TITLE
[TYPO] - NSFWblacklitedtags in DB file - Tedious 

### ISSUE THREAD

**Issue by mstarbuck13** [Kwoth/NadekoBot#2569]
Apparently, the bot's db file is now collected lit NSFW tags, instead of blacklisting them. :owo: 
![image](https://user-images.githubusercontent.com/19699010/45591451-27f18880-b921-11e8-92fc-d34723aa8b04.png)

**Comment by Kwoth** [comment]
Not an important mistake, it would require table drop. Sqlite doesn't support alter table.
