### ISSUE TITLE
Slot Bug

### ISSUE THREAD

**Issue by Kiyoshi1412** [Kwoth/NadekoBot#2570]
Slot is showing weird result.

Betting 2 and get one flower in the result and end up having a `Bet:2 Won:0` result. Not only that, the result is also shown differently in the picture with `Bet: 4` and `Winnning: 2`

<img width="558" alt="screen shot 2018-09-17 at 11 24 58 am" src="https://user-images.githubusercontent.com/38747093/45642324-b45c9200-ba6c-11e8-8c30-7f0c59160850.png">

**Comment by bakabakasama** [comment]
Can confirm, but appears to just be graphical. Afterwards, it stopped printing messages as a whole and only modifies your balance when using slot.

**Comment by Kaoticz** [comment]
Might be related. The same is happening to the `.roll <number>` command
![image](https://user-images.githubusercontent.com/1812311/45731915-3e614380-bbb0-11e8-8d59-2de678e3ad6e.png)

**Comment by Kwoth** [comment]
wtf 😂

**Comment by Kiyoshi1412** [comment]
Nadeko can no longer do math.

**Comment by Kwoth** [comment]
five plus five is six over two that's three quick mafs
