### ISSUE TITLE
Reputation System?

### ISSUE THREAD

**Issue by Spooky-Noodle** [Kwoth/NadekoBot#2571]
`.rep @User`

`%sender% has awarded %user% a reputation point!`

So, some sort of reputation system, tracked globally, that can be awarded from one user to another once per day. A user can only award rep once every 24 hours, but they can receive Rep an unlimited number of times (as long as there are users available to award it). 

This could be displayed using `.xp`, just a little section on the card that displays how many reputation points the person has. 

I have no idea how difficult this would be to program, but it seemed like a fun feature that would be really nice to have. Thanks for reading.

**Comment by PotatoGaming2079** [comment]
Suggestions go to https://feathub.com/Kwoth/NadekoBot

**Comment by Spooky-Noodle** [comment]
Okay, thank, sorry about that.
