### ISSUE TITLE
Reactions

### ISSUE THREAD

**Issue by Spooky-Noodle** [Kwoth/NadekoBot#2572]
`.hug @User`

`.slap @User`

`%user& has been slapped by %sender%!
[random (from a pool) anime gif of someone being slapped]`

Again, this is another feature where I have no idea how difficult it would be to program, but it would be really nice to have, where you could hug/slap/kiss/poke/punch/etc someone and Nadeko would provide the gif and text. There's other bots that have similar features, and I can find a full list of features that would be cool feature (but only if it's not too difficult, don't want Kwoth tearing out their hair over anime hugs).

**Comment by Spooky-Noodle** [comment]
I use acr pretty regularly, but I suppose I misspoke. It's called "reactions" in other bots, but Nadeko already has that function. I'm looking for custom text, for both the person who triggers the command and the person it's targeted at, uploading the gif from a random pool, but not using a link. 

But yeah, I'll migrate that over to feathub, my apologies.

**Comment by Kaoticz** [comment]
You've just answered your own question: use the `%target%` placeholder.

**Comment by Spooky-Noodle** [comment]
Still doesn't solve the 'image upload' situation, and it seems like a lot of unnecessary work on the part of every single user who wants this feature, buuuut... It's a workable, temporary solution. Thanks for your help, guys.
