### ISSUE TITLE
Stream notifications announces every stream when one goes live

### ISSUE THREAD

**Issue by elijabesu** [Kwoth/NadekoBot#2574]
Self-hosted, latest version.

Finally started hosting Nadeko on GCP, setup stream notifications for my server (currently having 4), but when one goes live, it announces all four of them.
![unknown](https://user-images.githubusercontent.com/41390133/45784332-98254480-bc68-11e8-8497-957d98ea8ea4.png)
![unknown 1](https://user-images.githubusercontent.com/41390133/45784338-9b203500-bc68-11e8-9505-74399d7ff233.png)

**Comment by Kaoticz** [comment]
Related: #2502

**Comment by Kwoth** [comment]
Tracking this in #2212
