### ISSUE TITLE
.rip is pulling old images & code

### ISSUE THREAD

**Issue by charliepja** [Kwoth/NadekoBot#2575]
The server I manage the bot for changed the .rip image, so I needed to adjust some of the code for it to work - SearchesService.cs

So if someone did .rip and then I changed the source file, and reloaded Nadeko, that person would view the old .rip But if a new person did .rip, they would receive the new image. Changing your nickname would also mean you would pull the new image. 

I've attached some photos to show what I mean. 

[Image One](https://media.discordapp.net/attachments/398794541710180363/492109658387906561/rip.png)

[Image Two](https://media.discordapp.net/attachments/398794541710180363/492109658387906561/rip.png)

These 2 images were done at the same time, then we realised that resetting your nickname or changing your nickname would mean pulling the new image. But if you went back to a previous nickname then you would pull the old image. 

[Image Three](https://cdn.discordapp.com/attachments/398794541710180363/492181395582615552/rip.png)

[Image Four](https://cdn.discordapp.com/attachments/398794541710180363/492181470471782410/rip.png)

Those two images were done one after the other with no bot reload, all I did was change my name back to a previous one used. 

I tried a fresh install of a new bot in a testing server to see if it was the same, and it was. From testing, it seems that after 24 - 48 hours the bot will naturally recognise the changes without having to reset nicknames etc.

**Comment by Kaoticz** [comment]
That's probably cached on Redis.
Try doing a `redis-cli flushall`

**Comment by Potato1680** [comment]
@charliepja After doing what Kotz's said to do, was your issue resolved? If so, please close this.

**Comment by charliepja** [comment]
The solution works, you just need to reload/restart the bot after doing it as well otherwise a lot of the commands don't work
