### ISSUE TITLE
Can't use .mute

### ISSUE THREAD

**Issue by lugui1998** [Kwoth/NadekoBot#2577]
Hello. I trying to use the .mute clients at my discord server and the command simply do nothing.

I created a role called "Muted" and I .setmuterole Muted.
After that, I tyed to .chatmute a player but he can still send messages.

This happens because the server has only a few public rooms, The majority can only be seen by the ones who have a specified role. In order to properly mute those players, the bot need to assign the muted role and also remove the member role.

That could be automatic. Upon "setmuterole" or even a "addmuterole" (for multiple mute roles that are assigned acording to the player current roles) Nadeko could just duplicate the role without the send messages permission on every channel (IDK if it is possible)

My sugestion is to add a configuration on the chatmute command that allow to specify wich roles will be removed from the client when he gets muted and re assigned when he is unmuted.

Also, There could be a second mute type where every message from a player is auto deleted and the NadekoBot will always ignore commands from that player. This is not evective on server that have many bots, mut mine for exempla has only 2, Nadeko and another one that only responds to staff members

Thankyou.

**Comment by Kaoticz** [comment]
![image](https://user-images.githubusercontent.com/1812311/45850338-1555c580-bd0c-11e8-9685-8ea083e76e03.png)

Also, this is the wrong place for feature suggestions. Go to [Feathub](https://feathub.com/Kwoth/NadekoBot/) for that, GitHub is for bug reports only.

**Comment by lugui1998** [comment]
That is exactly what I've described. We can't allow @everyone on our server to send messages on every channel, therefore, we need to assign a role with send messages.

**Comment by lugui1998** [comment]
Oh, sory, I got it, I just needed to let the permission role below the muted role and set the permission role to neutral and @everyone to neutral
