### ISSUE TITLE
.edit only works if the targeted message is in the same channel where the command is used

### ISSUE THREAD

**Issue by Kaoticz** [Kwoth/NadekoBot#2578]
Title is self-explanatory. `.edit` does not work for messages that are not in the same text channel where the command is used.

How to replicate the issue:
- Go to #chat1 text channel
- Use `.say Test1` there

The bot should respond with `Test1`, like it's supposed to.

- Use `.edit <message-ID> Test2`
The message should be edited like it's supposed to.

- Go to #chat2 text channel
- Use `.edit <message-ID> Test3`

Nothing is going to happen. The bot registers the command on the console but does not edit the targeted message.

**Comment by Kwoth** [comment]
thats how its supposed to work
