### ISSUE TITLE
Need help to reinstall the bot

### ISSUE THREAD

**Issue by Nisouc** [Kwoth/NadekoBot#2579]
Hello there, I feel like my issue may be easy to fix for you guys but I'm kind of a noob so be easy on me.
So for the story, I was hosting Nadeko without problems, and that for months, but this morning I decided to check if there were any updates for the bot since I never updated it, and there were !
So I decided to update it of course, but I didnt do ".die" to kill it before hand (idk if that changes anything). And after the update was done, I tried to restart the bot, but the console was saying something like "error 400 : Bad request". I tried restarting it again but it didnt change anything, so I decided to try to uninstall redis and reinstall but now it just said "Images already exist in redis" or something like that.
I kept trying to uninstall stuff and everything and eventually decided to completely delete the NadekoBot folder, the NadekoUpdater and redis to start again from scratch, but here is my problem now, I downloaded the NadekoUpdater again and it still considers that it is on version 2.28.4 even though I unistalled everything. I can install redis no problem, but cannot click the big update button to reinstall the NadekoBot application, and it is nowhere to be found in my Pc either.

So here is my question, is there any way for me to "reset" the NadekoUpdater so I can start again from scratc as if I never hosted the bot in the first place, or have a way to download the NadekoBot files from elsewhere ? 
Thanks for your time

**Comment by Potato1680** [comment]
How to reinstall Nadeko on Windows?
1. Close Nadeko completely.
2. Go to Control Panel > Programs > Programs and Features > Uninstall or change a program
3. Uninstall NadekoBot version <number>
4. Open Nadeko Updater and click Update

If Nadeko Updater still detects the program as installed after removing it:

1. Close Nadeko Updater.
2. Open regedit and delete this: HKEY_LOCAL_MACHINE\SOFTWARE\NadekoBot
3. Open Nadeko Updater and try again.

**Comment by Nisouc** [comment]
Okay now it doesnt detect the version anymore, I cant believe you saved me so fast haha
Only problem now is that it tells me that I check for updates too often and the "Update" area is grayed, I still can't install, does that go away if I wait for a bit ?

**Comment by Potato1680** [comment]
So, it's still detecting the program as installed?

**Comment by Nisouc** [comment]
No its not, theres just this pop-up telling me to "chill a bit"

**Comment by Potato1680** [comment]
Then I we must chill a bit. Try restarting your pc.

**Comment by Nisouc** [comment]
I will, thanks for the help !

**Comment by Potato1680** [comment]
If you would, close this when ever you get it to stop telling you to chill out

**Comment by Potato1680** [comment]
@Nisouc  If you got it to work, please close this. Thank you.

**Comment by Nisouc** [comment]
Oh yeah Im sorry I was busy creating all the bot reactions again and I forgot, thanks for the help again and have a good day !

**Comment by Potato1680** [comment]
You have a good day too.
