### ISSUE TITLE
`.help liqu` says not found, even though it's the abbreviation for `listquotes`

### ISSUE THREAD

**Issue by numbermaniac** [Kwoth/NadekoBot#2581]
![screen shot 2018-09-22 at 11 03 14 am](https://user-images.githubusercontent.com/5206120/45911472-23fcc380-be57-11e8-8751-7c36816794bd.png)

`listquotes` uses `liqu` as a shortened form but the `help` command isn't accepting it.

**Comment by Kaoticz** [comment]
Command aliases require prefix to work.
`.h liqu` will not work
`.h .liqu` will work

**Comment by Potato1680** [comment]
This can be closed
