### ISSUE TITLE
Cleverbot API

### ISSUE THREAD

**Issue by Jengas** [Kwoth/NadekoBot#2582]
Cleverbot API provides Username and Token, while in NadekoBOT credentails only token presents; Which of it, Nadeko shows error in logs
![image](https://user-images.githubusercontent.com/14033756/45918789-5c6ac480-be8c-11e8-9c4f-956082766ac6.png)
![image](https://user-images.githubusercontent.com/14033756/45918799-6d1b3a80-be8c-11e8-96c4-1995b2898e8f.png)

**Comment by bakabakasama** [comment]
Make sure you put the API _key_ in the Credentials file correctly.
> 401: unauthorised due to missing or invalid API key

**Comment by Jengas** [comment]
> Make sure you put the API _key_ in the Credentials file correctly.
> 
> > 401: unauthorised due to missing or invalid API key

![image](https://user-images.githubusercontent.com/14033756/45940513-d066b300-bfd9-11e8-800f-ede5a7af2607.png)
I have

**Comment by samdivaio** [comment]
You are using cleverbot.io api, you need the actual cleverbot api. 
Read the guide again: https://nadekobot.readthedocs.io/en/latest/JSON%20Explanations/

**Comment by Jengas** [comment]
Got it. Thanks @samdivaio
