### ISSUE TITLE
New members added to the leaderboard as Unknown#????

### ISSUE THREAD

**Issue by codingJWilliams** [Kwoth/NadekoBot#2583]
**What I expect to happen**

When booting the bot with a clean database, awarding 10 to a random member and checking the leaderboard, they should be added by their name

**What happens**

When performing the above, the member appears on the leaderboard as Unknown#????

**Steps to repro**

Clone 995b60e locally. Fill in `src/NadekoBot/credentials.json`, making sure you're the bot owner. cd to `src/NadekoBot`, and run `dotnet run -c Release`. In a guild with the Nadeko instance, run `.award 10 <your own id>`; it completes successfully. Check `.lb` and you'll see yourself listed as `Unknown#????`

**System Info**

Dotnet SDK 2.1, Solus Linux.

---

Also, one support member noted this may be due to changes in the GetOrCreate method.

**Comment by Potato1680** [comment]
#2392 Is related

**Comment by codingJWilliams** [comment]
Ah yeah. @Kwoth's response seems... strange. Why doesn't it add their name correctly

**Comment by Potato1680** [comment]
This can be closed.

**Comment by Kwoth** [comment]
Yea, tha'ts just how it works right now. *Maybe* I'll think of smarter system for nadeko 3.0
