### ISSUE TITLE
NSFW tag blacklisting is not working

### ISSUE THREAD

**Issue by 9gfg06w2** [Kwoth/NadekoBot#2586]
I am a NSFW Mod on a discord server. What we did is type ".nsfwtagbl gore"(without the quotes). When we typed in ".hentai gore" (without the quotes), a picture of hentai with the tag of gore came up. Thanks for reading.

**Comment by Kaoticz** [comment]
If you're self-hosting, have you tried to clear Nadeko's cache with `.nsfwcc`?

**Comment by 9gfg06w2** [comment]
Nobody in the server hosts the bot.

**Comment by Potato1680** [comment]
Can confirm, `.hentai` does not take the blacklisted tags into mind.

**Comment by SpielefreakJ** [comment]
Blacklist is only for nfsw command, not for hentai :man_shrugging: 
(says the description of nfswtagbl)

**Comment by Potato1680** [comment]
Hentai is an NSFW command.
