### ISSUE TITLE
If you set Nadeko to run on startup, it doesn't. (Windows)

### ISSUE THREAD

**Issue by TheOddball** [Kwoth/NadekoBot#2587]
Title. If you add the NadekoBot.exe shortcut to the startup folder, it never starts on boot, causing me to have to manually do it. (Yes, I have UAC disabled.)

**Comment by Kwoth** [comment]
You can set it as a startup servie afaik. This is not something i'm gonna delive into.

**Comment by TheOddball** [comment]
Weird. I can't do it by using a shortcut, you have to do it with Task Scheduler, and even if you do, it won't start correctly, because it won't find creds. You have to set it to run in the system folder. (Posting for others to use in future reference)
