### ISSUE TITLE
[Suggestion] Improved .prune/.clr Commands

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#259]
Currently `.prune` is kinda weak-sauce. :stuck_out_tongue: Below is what I would like to see:

`.prune 1` should delete the `.prune 1` message you just typed and the message immediately before it. It doesn't make any sense to only delete the prune message...On the same vein, the prune message should always be included no matter what. So `.prune 50` would kill the prune message *_and_* the 50 previous messages before it, not 49.

~~I'd like to see `.prune @user X` to clear a number of messages only from a specific user (and the prune message itself).~~ <-- `.clr` already handles this. Command doc was out of date. Thanks @Kwoth.

Also, I'd like to see functionality akin to this: ![text cleanup](http://i.imgur.com/lBkopGY.png)
This is to cleanup/prune messages with only a certain word or phrase. (Note: `[p]` = prefix like `!`, `~`, or `.`) Example: `.prune text "faggot" 17` This would clean up the last 17 messages (and the prune message) with the word "faggot" in it.

**Comment by xnaas** [comment]
Why have `.clr` *and* `.prune`? Maybe combine these commands functionality and make one an alias for the other?

**Comment by xnaas** [comment]
`.clear @user X` where X is a number of messages would be nice.

**Comment by fjrichman** [comment]
If you are expanding .prune in functionality .prune clear would make for a good alternative to .clr 
Where a command like .prune clear @UserName would remove all of that users messages. But .prune 10 @UserName would only remove the last 10.

**Comment by xnaas** [comment]
I like that idea @fjrichman. A clear division of prune vs clear (clr) would also be a good option.

**Comment by Kwoth** [comment]
I'm thinking of this:
- remove clr
- `.prune` - Clears all nadeko's messages from the last 100 messages
- `.prune X` - Removes last X+1 messages in the channel
- `.prune @Person` Removes all messages from that user's in the last 100 messages
- `.prune @Person X` Removes last X messages from that user.

**Comment by xnaas** [comment]
The problem with using `;cfw` is this doesn't go back and cleanup messages with the word. It also doesn't help prevent spam, it only filters words you deem bad.
