### ISSUE TITLE
Antispamignore only toggling on

### ISSUE THREAD

**Issue by Stalltt** [Kwoth/NadekoBot#2591]
The version should be up to date I assume, it is a Public Nadeko.
As the title says, it is possible to toggle a channel to be ignored by nadeko's antispam, but when attempting to toggle it back off it doesn't respond.
[https://cdn.discordapp.com/attachments/360634979505405953/495099841433829376/ignore.png](url)

**Comment by SpielefreakJ** [comment]
Same on self Hosted
