### ISSUE TITLE
.reactionroles not responding to my input

### ISSUE THREAD

**Issue by rogueyoshi** [Kwoth/NadekoBot#2593]
simply typing something like:

`.reactionroles PA :PA: NJ :NJ: DE :DE: NY :NY: MD :MD:
`

does nothing for me. not sure what to do. the bot has all the required permissions (add reactions, manage roles).

EDIT: .reactionroleslist is also not working at all.

**Comment by Kaoticz** [comment]
![image](https://user-images.githubusercontent.com/1812311/46251046-ab7da000-c41e-11e8-8343-f4123d622a09.png)
You can close this ticket
