### ISSUE TITLE
Nakedo help issues

### ISSUE THREAD

**Issue by Tobrito** [Kwoth/NadekoBot#2594]
Hi I was checking the help for the cmds and tried to do .cmds permissions and it said that help module didn't exist I can't submit imgs but I think you understood I am using your bot
I love the bot Ty for making it, Tobrito

**Comment by Kaoticz** [comment]
![image](https://user-images.githubusercontent.com/1812311/46262689-0674cd00-c4db-11e8-9c02-a9a0b7db9feb.png)
Works just fine. Tested on public Nadeko.
