### ISSUE TITLE
Console Report : Language Change - Error Report Sept, 30 , 2018

### ISSUE THREAD

**Issue by ItsRealSnow** [Kwoth/NadekoBot#2595]
When i changed my language to English i got some errors telling me to report this 

![screen shot 2018-09-30 at 3 37 17 pm](https://user-images.githubusercontent.com/43733089/46263851-901b9f00-c4c9-11e8-9a7c-f78d233b633c.png)

**Comment by Kaoticz** [comment]
"english" is not a language
"en-US' is

Use `.langli` to check which languages are available

**Comment by ItsRealSnow** [comment]
well i set back to default it lang i should be good
