### ISSUE TITLE
.asar doesn't work properly

### ISSUE THREAD

**Issue by Alcoth** [Kwoth/NadekoBot#2600]
I've been running into an issue while I was trying to set up the self-assigned roles.
After setting the first one in group 1 using "**.asar 1 Aquean**" I haven't been able to set anything else within the same group. After having sent the message "**.asar 1 Cealian**"to create the next role, nothing popped up from the bot.
I would like some help on this issue.

**Comment by LordVeovis** [comment]
@Alcoth this is more likely a configuration problem. You can get some help on the official discord channel: https://discord.gg/nadekobot

**Comment by Alcoth** [comment]
Sure, I'll take a look, thanks
