### ISSUE TITLE
Punishment for warnings applies to cleared warnings

### ISSUE THREAD

**Issue by ConductedForce** [Kwoth/NadekoBot#2604]
A user with 2 warnings had a warn punishment applied to him despite not actually reaching the requirement. He has 3 warnings (applies kick) but the 1st had been cleared some time ago. a .warnlog for the user shows that the first warning was cleared, but the warn punishment for a 3rd warning was still applied.

**Comment by Kaoticz** [comment]
Do you mind posting his `.warnlog` **and** his kick registered in Nadeko's log? If you're not self-hosting, send a screenshot of the audit log instead.

**Comment by ConductedForce** [comment]
Well, this is embarrassing. Turns out we did a third warn by accident. No actual problem (on Nadeko's end).
