### ISSUE TITLE
How to use custom image for Flowers image?

### ISSUE THREAD

**Issue by MysticDream534** [Kwoth/NadekoBot#2605]
How do you replace the current flower images when you are picking up the flowers to custom ones you want? I've got my images uploaded on imgur, and I tried to replace the image urls in the images.json and images_backup.json files. I closed the nadekobot.exe and restarted and nothing changed, it's still showing flower images... Any help will be appreciated, I'm new to editing bots.

**Comment by Kaoticz** [comment]
You forgot to use `.imagesreload`
Ask these kind of questions in out Discord server, GitHub is for bug reports only.
https://discord.gg/nadekobot

**Comment by Drmalkav** [comment]
even with imagesreload i can't get it to work either

**Comment by MysticDream534** [comment]
Oh... Um I figured it out, i typed .imagereload instead of .imagesreload. Forgot the "s". Thanks for answering, also I joined the Nadeko Discord Server in case I have more questions.
