### ISSUE TITLE
.ow command is not working properly

### ISSUE THREAD

**Issue by MrAdapt** [Kwoth/NadekoBot#2606]
When you use the .ow command it won't find the users information, throws out error 403 which is the HTTP service. I tried the same on the official NadekoBot server and it gives the same problem.

**Comment by Kaoticz** [comment]
Blame Blizzard's shitty API. ![image](https://user-images.githubusercontent.com/1812311/46489176-16422900-c7db-11e8-81e1-ab12e6386ad2.png)

**Comment by MrAdapt** [comment]
Figured that much, just had to confirm it 💯

**Comment by Kwoth** [comment]
2 Reasons
- The api changes every few months when blizzard adds new things which makes it annoying for me to go back and review what changed and apply it to models etc
- Sometimes there are weird issues with the api instance i'm hosting

I've decided I don't have the time to deal with these issues, as this feature wasn't even added by me to begin with (and as you can guess, the guy who added it doesn't maintain it), so it will be removed.
