### ISSUE TITLE
.repeat command not working?

### ISSUE THREAD

**Issue by gabbyshibaki** [Kwoth/NadekoBot#2607]
1: Bot Version. -- 2.28.4
2: Public Nadeko or Selfhost. -- Nadeko, its in my private discord server
3: Supporting Screenshots attached -- attached is it showing nothing happening after the command
4: Any specifics you might think will help Kwoth resolve. -- i reviewed the command list and reviewed what others here have talked about the .repeat command? I made sure Nadeko has manage messages turned on and nothing happens. 
![1](https://user-images.githubusercontent.com/43863203/46500060-dcc7e880-c7ef-11e8-8745-0bf1aea02f23.png)
![2](https://user-images.githubusercontent.com/43863203/46500354-a8a0f780-c7f0-11e8-890b-2b2bf7a09b7f.PNG)

**Comment by Gremagol** [comment]
Try using `.ve` and try again.

**Comment by Kwoth** [comment]
Is this fixed?

**Comment by Kwoth** [comment]
I'll close this as there was no reply in 3 days.
