### ISSUE TITLE
[Suggestion] Global Variables

### ISSUE THREAD

**Issue by fjrichman** [Kwoth/NadekoBot#261]
~~It would be nice if we could setup some form of MOTD for a server.~~

~~The basic idea would be something like taking the default text channel which everyone has read permissions on and taking away all permissions to write to it. Then let the bot run and it could display information about the server based on some sort of user customized template.~~

~~The bot would delete/repost or edit the message to keep it up to date and it could show things like uptime, online users, and other useful information that could be grabbed from any of the various APIs NadekoBot has access to.~~

~~An example could be something like:~~
~~Hello welcome to [servername], it is currently [date/time].~~
~~Currently we are listening to [currentsonginfo] in [botvoicechannel].~~
~~We currently have [usersonline] of [totalusers] and are looking for more!~~
~~Please enjoy your stay,~~
~~[serverowner].~~

We need global variables so that we can use the .repeat command to create dynamic MOTDs or announcements.

**Comment by Kwoth** [comment]
we have `.repeat` command. Although with no placeholders like .ropl has

**Comment by fjrichman** [comment]
.repeat would work since it does the whole delete/repost. Perhaps instead of creating a specific motd function global variables would be what I'm suggesting then instead.

**Comment by Kwoth** [comment]
Global variables?

**Comment by fjrichman** [comment]
Effectively you'd create placeholders (typically called variables since the content can change) that would be replaced no matter where they are said by the bot. So having the bot say [serverowner] would make it show up as @Username where ever it happens to be used. Whether it is in .repeat or .greetmsg .greetpm, or any of the other commands where you can send custom text.

**Comment by Kwoth** [comment]
It's a cool idea but that would mean using the part of the library api that gets removed in discord.net 1.0 or changing the library.

**Comment by appelemac** [comment]
Couldn't you add those in The Extensions method?

**Comment by Kwoth** [comment]
No, because we need to catch outgoing sendmessage api requests and edit them, and afaik this is getting removed in discord.net 1.0. I'll close it for now and see about it when we swtich
