### ISSUE TITLE
feed quantity

### ISSUE THREAD

**Issue by a15945675321** [Kwoth/NadekoBot#2612]
I am self-hosting! 
How to increase the quantity?
(Rss)(Currently ten)

**Comment by Potato1680** [comment]
I have the GitHub location to change the quantity. I have no clue where it will relate to the files on the OS you are using but it *should be* similar. 

https://github.com/Kwoth/NadekoBot/blob/1.9/NadekoBot.Core/Modules/Searches/Services/FeedsService.cs

Line 166. Change the 10.
