### ISSUE TITLE
.time not responding anywhere

### ISSUE THREAD

**Issue by numbermaniac** [Kwoth/NadekoBot#2613]
I've tested in multiple different servers using public Nadeko, and it's not responding to the `.time` command in any of them.

It's responding or reacting to other commands, such as `.weather` and `.prune`, but it's not responding with anything when I use `.time` - for example `.time London, UK` gives no response, but `.weather London, UK` works fine.

**Comment by Kaoticz** [comment]
The `.time` command is broken on public Nadeko.

**Comment by Kwoth** [comment]
Time will be removed.
