### ISSUE TITLE
poei search

### ISSUE THREAD

**Issue by Dandacion** [Kwoth/NadekoBot#2614]
The .poei search is still non-functional after almost 5 months
per the comments on this pull request
https://github.com/Kwoth/NadekoBot/pull/1908

Noticed there wasn't an issue raised so throwing one up so it's not forgotten.

**Comment by Kwoth** [comment]
Thank you. I'll see if there is a reply in a few days, and then i'll decide whether to remove the unmaintained PRed commands or starting fixing them and maintaining myself.
