### ISSUE TITLE
Numerical custom reactions

### ISSUE THREAD

**Issue by ShadowShard** [Kwoth/NadekoBot#2616]
If you make a custom reaction with a number (in this case, it was somebody using "3", which I'll admit was a bad idea in the first place), and then turn .crca on for that reaction, if the trigger shows up in the ID, it can't be deleted, nor can .crca be turned off (because Nadeko will react to the number as opposed to completing the command).  The only way to get rid of it that I could find was just removing all of them using .crclear.

**Comment by Kwoth** [comment]
yes, tracked in #2172
