### ISSUE TITLE
System.MissingMethodException on bot startup

### ISSUE THREAD

**Issue by gsoftwares** [Kwoth/NadekoBot#2618]
When I start the debug I get this:
`System.MissingMethodException: 'Method not found: 'System.Threading.Tasks.Task'1<Discord.IUserMessage> Discord.IMessageChannel.SendFileAsync(System.String, System.String, Boolean, Discord.Embed, Discord.RequestOptions)'.'`

**Comment by Kaoticz** [comment]
Have you installed the prerequisites?

**Comment by gsoftwares** [comment]
> Have you installed the prerequisites?

If you mean the dependencies, yes, I've installed them.

**Comment by gsoftwares** [comment]
> > Have you installed the prerequisites?
> 
> If you mean the dependencies, yes, I've installed them.

Actually I'm getting an error in the Discord.Net dependency that says that it found another version.

**Comment by Kaoticz** [comment]
It shouldn't honestly, as this has been fixed a while ago https://github.com/Kwoth/NadekoBot/commit/445e082d6c63f6f4b4ff598cb3dc073f5f32cbc7

Redownload the bot and try again.

**Comment by Kwoth** [comment]
Yeah, this was fixed a long time ago.
