### ISSUE TITLE
[Request] Separation of Administration and "General"

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#262]
I think there should be a separation of a lot of the commands from the "Administration" module to a new "General" module. `.checkmyperms` isn't really administration since any user can run that command. Same goes for commands like `.iam`, `.iamn`, etc.

I think stuff like `>rps` and `>8ball` would fit in a "General" module too, but that's really at your discretion, @Kwoth.

As you mentioned in #258, Administration module stuff shouldn't be managed by the permissions system. If that's the case, then please move stuff form the Administration module that isn't administration. 😄

**Comment by Kwoth** [comment]
.iam and iamn and checkmyperms are administration in a sense. and they aren't going out. They don't need to, and shouldn't be moderated with permission system. They fit perfectly into administration.

No, rps and 8ball are a part of games and it makes sense for them to be there.

**Comment by Kwoth** [comment]
Administration needs to be reduced in size

**Comment by Kwoth** [comment]
i did this a while back Oo. We have Utility and Administration now, i will further separate them along the way.
