### ISSUE TITLE
Changing the CurrencySign

### ISSUE THREAD

**Issue by AkaFarukon** [Kwoth/NadekoBot#2620]
Alright so I am messing around with the currency system, and I don't know if I am blind or just not sure what to do to change the currency sign. Atm, it's the cherry_blossom but I want to change it to a custom emote. Anyone care to provide steps to do so correctlly?

**Comment by xnaas** [comment]
This is more of a NadekoLog help server question...

But it's `.bce CurrencySign <:EmojiOrWhateverHere:>`
