### ISSUE TITLE
Bot automatically deletes messages

### ISSUE THREAD

**Issue by TunetexBG** [Kwoth/NadekoBot#2623]
My NadekoBot deletes welcome messages and quit messages per seconds

**Comment by samdivaio** [comment]
Cool.
So what's the issue?

**Comment by Kaoticz** [comment]
Not a bug, this is a feature. ![akkoshrug](https://user-images.githubusercontent.com/1812311/47210315-06911b80-d369-11e8-8b40-709e9df78b59.png)
And I'm not even being ironic this time.

**Comment by zzaagg** [comment]
Use ".greetdel 0" and ".byedel 0" to allow them to stay in the channel permanently.

**Comment by Kwoth** [comment]
thanks @zzaagg
