### ISSUE TITLE
Cleverbot not working

### ISSUE THREAD

**Issue by ScarletDevil25** [Kwoth/NadekoBot#2624]
![image](https://user-images.githubusercontent.com/17516560/47220207-b1462000-d3e3-11e8-93c8-b9f49249905a.png)
I'm currently self hosting Nadeko and am getting these errors from the clever bot, I'm using the native APi and have not provided a key for the cleverbot API I asked support and they told me to submit a ticket

![image](https://user-images.githubusercontent.com/17516560/47220512-958f4980-d3e4-11e8-8a41-da7100588d21.png)

**Comment by ScarletDevil25** [comment]
> The official API works for me. Dunno about the free one.
> ![image](https://user-images.githubusercontent.com/24619854/47220631-a030eb00-d3b2-11e8-9e59-6e5ff6c8eaf8.png)
> ![image](https://user-images.githubusercontent.com/24619854/47220634-a45d0880-d3b2-11e8-8a27-053148228926.png)

Sadly I do not have the money to pay for the official api so I can't us it

**Comment by Gremagol** [comment]
> > The official API works for me. Dunno about the free one.
> > ![image](https://user-images.githubusercontent.com/24619854/47220631-a030eb00-d3b2-11e8-9e59-6e5ff6c8eaf8.png)
> > ![image](https://user-images.githubusercontent.com/24619854/47220634-a45d0880-d3b2-11e8-8a27-053148228926.png)
> 
> Sadly I do not have the money to pay for the official api so I can't us it

I actually still have two 5k/free apis. Got them when they were for free back then.

**Comment by ScarletDevil25** [comment]
wow

**Comment by Gremagol** [comment]
I can give you one if you wish.

**Comment by ScarletDevil25** [comment]
> I can give you one if you wish.

if it wont be any trouble

**Comment by Gremagol** [comment]
Sent you DM's, but I don't think that this fixes the main issue of this problem here.

**Comment by ScarletDevil25** [comment]
sadly the one fro Kworth is currently down

**Comment by Kaoticz** [comment]
Program-O API is facing some issues right now.
https://program-o.com/v2/api.php
![image](https://user-images.githubusercontent.com/1812311/47234121-26493380-d3ab-11e8-950d-8424415b4dfe.png)
No word on when it's going to get fixed. There isn't anything we can do here.

**Comment by Kwoth** [comment]
Program-o will be removed.

**Comment by Kwoth** [comment]
Wait, program-o is removed. This is cleverbot.io

**Comment by Macley-Kun** [comment]
Mhm, cleverbot doesn't give out a free api key. So an alternative has to be used.

Happen to find this one on another project. Maybe that's something you could use?
https://github.com/avaire/avaire/blob/master/src/main/resources/config.yml#L456
^place where i found it.

https://dialogflow.com/docs/reference/agent
^Official docs.

**Comment by Gremagol** [comment]
I would still suggest to keep support for both apis, depending which is better as I already am paying for the official api.

**Comment by Kwoth** [comment]
The requests to the api endpoint are timing out. I'll wait a bit more and then see what to do.
