### ISSUE TITLE
Need Help - "Error: signature extraction faild" and "song not found" ERROR's.

### ISSUE THREAD

**Issue by Sonfa** [Kwoth/NadekoBot#2626]
So, Sound cloud works just fine how ever when using Nadeko bot it seems that on this latest update the bot will not play YT url's or search for them. The error itself has been occurring all day and my youtube-dl is working exceptionally fine it seems. 

![nadekohelp](https://user-images.githubusercontent.com/40552381/47263100-3b63b680-d4c0-11e8-872d-c0aa6bd8b419.png)

![image](https://user-images.githubusercontent.com/40552381/47263104-46b6e200-d4c0-11e8-80d3-563cbed00bfd.png)

At this point I am pretty stumped I've uninstalled Nadeko and re-installed, Made sure the bot was up to date VIA Github and NadekoUpdater.exe 

~ P.S. I personally find soundcloud boring. So I would like youtube to work again ^~^ 
Would love who ever decided to help a fella out :D

**Comment by Kaoticz** [comment]
Update youtube-dl
![image](https://user-images.githubusercontent.com/1812311/47263150-18da9900-d4d2-11e8-8cd9-a8c2637fdeb5.png)
