### ISSUE TITLE
Nadeko not working with pm2

### ISSUE THREAD

**Issue by Skiddl** [Kwoth/NadekoBot#2627]
Nadeko works fine when started normally, but does not start propperly when using pm2. Using Centos7.
Error log:
0|Nadeko  | /usr/share/dotnet/sdk/2.1.403/NuGet.targets(114,5): error : 'N/A' is                                             not a valid version string. [/root/NadekoBot/NadekoBot.sln]
0|Nadeko  | /usr/share/dotnet/sdk/2.1.403/NuGet.targets(114,5): error : Paramete                                            r name: value [/root/NadekoBot/NadekoBot.sln]

pm2 info Nadeko:

│ status            │ online                           │
│ name              │ Nadeko                           │
│ version           │ N/A                              │
│ restarts          │ 1                                │
│ uptime            │ 12h                              │
│ script path       │ /root/NadekoARU_Latest.sh        │
│ script args       │ N/A                              │
│ error log path    │ /root/.pm2/logs/Nadeko-error.log │
│ out log path      │ /root/.pm2/logs/Nadeko-out.log   │
│ pid path          │ /root/.pm2/pids/Nadeko-0.pid     │
│ interpreter       │ bash                             │
│ interpreter args  │ N/A                              │
│ script id         │ 0                                │
│ exec cwd          │ /root                            │
│ exec mode         │ fork_mode                        │
│ node.js version   │ N/A                              │
│ node env          │ N/A                              │
│ watch & reload    │ ✘                                │
│ unstable restarts │ 0                                │
│ created at        │ 2018-10-20T21:22:45.702Z         │
└───────────────────┴───────────────────────────

Edit: Only seems to be affecting option 2 ( auto restart & auto update). works without auto update.

**Comment by Kaoticz** [comment]
I've been dealing with this bug for the past few days and still trying to figure out what is cause of it. Here is what I've found out so far:
![image](https://user-images.githubusercontent.com/1812311/47270324-ace34980-d540-11e8-8fd7-d2b8f8e80fca.png)

1. It affects all Linux distros, no exception.
1. It affects both `no autoupdate` and `with autoupdate` options
1. It's not related to the pm2's version (reproduced the issue both on versions 3.1.3 and 3.2.2).
1. It only affects new installations. By new, I mean any clean installations of Nadeko made after this commit: https://github.com/Kwoth/NadekoBot/commit/445e082d6c63f6f4b4ff598cb3dc073f5f32cbc7 (the commit itself might not be related)
1. Systems that had Nadeko installed and running prior to this commit do not suffer from this bug after updating Nadeko or pm2.
1. dotNET seems to be unrelated, as I had version `2.1.403` running on all my tests.


**.::How to reproduce the issue::.**

- Install Nadeko and pm2 normally by following the steps on the [Linux Guide](https://nadekobot.readthedocs.io/en/latest/guides/Linux%20Guide/). It **must** be a clean install (as in the system must have never had ran Nadeko before).
- It will work normally the first time you run the bot through pm2
- Stop the bot with `sudo pm2 stop Nadeko` then restart it with `sudo pm2 restart Nadeko`
- You'll get the build error above.

**.::Workaround::.**

- Kill the pm2 instance with `sudo pm2 delete Nadeko`
- Run the installer with `bash linuxAIO.sh` and redo Option 7.
- It will work until you stop the bot again with `sudo pm2 stop Nadeko`
