### ISSUE TITLE
Automatic temporary ban (.warnpunish)

### ISSUE THREAD

**Issue by P-eter** [Kwoth/NadekoBot#2628]
### Introduction
There is a feature on Nadeko that lets users get automatically kicked/temporarily banned/permanently banned on a certain amount of warnings. This is followed by the command of 
"**.warnpunish [Number] <Kick/Ban> [Optional timer]**".

### Bug
I've noticed a bug that destroys the point of this feature. When a user gets an temporary ban, Nadeko will NOT unban the user when time is up.

### Visual Explanation (An Example)
![image](https://user-images.githubusercontent.com/44347386/47272004-6c3dfd00-d54d-11e8-887a-837aeb4dbfd7.png)
The screenshot above is the settings that are set in a server that a worker and I manage. _10080 minutes is equal to 7 days, which equals to 1 week_
![image](https://user-images.githubusercontent.com/44347386/47271906-c0e07880-d54b-11e8-9614-516f34df6055.png)
The screenshot above is showing a user that has been automatically banned temporarily. As you see, this user has been banned on October 11, 2018; meaning, the user should be unbanned on October 18, 2018, 1 week later.
![image](https://user-images.githubusercontent.com/44347386/47271919-f4bb9e00-d54b-11e8-9fda-33cf5d73b02b.png)
The screenshot above is showing that Nadeko does not unban the user, Dorse, on the promised time that I have set. Instead, a user manually unbanned Dorse.
![image](https://user-images.githubusercontent.com/44347386/47271997-4fa1c500-d54d-11e8-8146-6ccf95d98348.png)
The screenshot above are the warnings that Dorse has.

**Comment by Kaoticz** [comment]
It turns out that ban timers cease from triggering if you restart the bot.
For now, avoid restarting Nadeko if you have a timed ban in place. A fix is being worked on right now, but no ETA on when it's going to be released.
