### ISSUE TITLE
Races not working in v2.28.4

### ISSUE THREAD

**Issue by zdgoodnews** [Kwoth/NadekoBot#2631]
Self-hosting the bot.

I started a race, user joined, response was "race is full! starting immediately". Races are currently in limbo, can't join or start them and the previous race never started.

![capture](https://user-images.githubusercontent.com/34757559/47589558-58641380-d91e-11e8-8a67-41aef3e89b20.PNG)

**Comment by zergling-man** [comment]
Can't reproduce. Check your console's output, it's probably giving you errors.
Also I suspect you've gone and tweaked something about the max number of participants that broke it.

**Comment by zdgoodnews** [comment]
Not running from source, haven't touched the max participants. I'll check console.

**Comment by Kwoth** [comment]
Try restarting the bot.
