### ISSUE TITLE
Images are no longer shown in embeds

### ISSUE THREAD

**Issue by Midoriin** [Kwoth/NadekoBot#2633]
![1](https://cdn.discordapp.com/attachments/244403505920606210/505772197806211102/Screenshot_2018-10-27-10-57-28.jpg)
![2](https://cdn.discordapp.com/attachments/244403505920606210/505772216684904448/Screenshot_2018-10-27-10-57-58.jpg)
Another example
![3](https://gtaodiscord.com/u/d44d804532cd.png)
![4](https://gtaodiscord.com/u/a8225740e0e3.png)

**Comment by Gremagol** [comment]
are these imgur links?
If yes, then...
https://cdn.discordapp.com/attachments/464099470766899201/506062025055666192/IMG_20181028_120920.jpg

**Comment by Potato1680x2** [comment]
Imgur is having issues with displaying links on Discord. Imgur is aware of the issue and is looking into it.

**Comment by Potato1680x2** [comment]
![screenshot 87](https://user-images.githubusercontent.com/44508314/47618272-2332ff00-da9f-11e8-98d0-5f358e17da75.png)
https://trello.com/c/7grpgSvA

**Comment by Kwoth** [comment]
Thanks, I'll leave this open so other people can see it.

**Comment by Potato1680x2** [comment]
This can be closed, the issue has been resolved. Imgur links are now previewing and displaying in embeds properly.
