### ISSUE TITLE
Cannot disable DM help response

### ISSUE THREAD

**Issue by jklouse-rei** [Kwoth/NadekoBot#2635]
We would like to use Nadeko without the initial DM response for "help", but have not been able to find a way to configure the bot to prevent sending that response.

**Comment by Kaoticz** [comment]
Set up a custom reaction with `.help` and `.h` as the trigger.
Next time, take that question to our [Discord server](https://discord.gg/nadekobot), GitHub is for bug reports only.

**Comment by zzaagg** [comment]
Try ".bce HelpString {Custom Message}." Read this as well: [https://nadekobot.readthedocs.io/en/latest/Bce%20Guide/](url) for more information on it.

**Comment by Kwoth** [comment]
This is a question for discord server, and it's unclear which message you're referring to.
