### ISSUE TITLE
Unsupported 16-Bit Application

### ISSUE THREAD

**Issue by ACupOfSaltTV** [Kwoth/NadekoBot#2636]
i get this error when i try to update the bot for the first time to install it. redis is installed and i tried rebooting. from the googling i did im missing NTVDM from Legacy Components on windows features.

im on windows 10 pro not licenced. newest update.

screenshot of error
https://i.imgur.com/Wl27xm4.png

**Comment by ACupOfSaltTV** [comment]
i should probably add that im moving the bot off the vm on my main pc on to my old pc with a fresh install of windows. both are windows 10 pro 64 bit so idk why it wont work on my dedicated machine

**Comment by Kaoticz** [comment]
![image](https://user-images.githubusercontent.com/1812311/47694619-1288a300-dbdd-11e8-81c4-491796939228.png)
Reproduced on Windows 10 Pro - 64 Bits
I made sure all prerequisites were installed before clicking the "Click here to Update" button.

**Comment by Kaoticz** [comment]
As an alternative, you can [download the bot directly from the releases page](https://github.com/Kwoth/NadekoBot/releases). It should launch both from the updater and from the shortcut it automatically installs.

**Comment by Kwoth** [comment]
Seems like innosetup has some incompatibility? I'll check whether i can update it or if there is an alternative >.>

**Comment by Kwoth** [comment]
Seems like innosetup has some incompatibility? I'll check whether i can update it or if there is an alternative >.>

**Comment by Kwoth** [comment]
https://stackoverflow.com/questions/16130669/inno-setup-compiled-exe-is-not-installing-app-on-windows-8-64-bit-unsupported-1 according to this post, the download is corrupt. Maybe windows is "protecting you"?

**Comment by Kaoticz** [comment]
Negative. I've attempted a clean install on Windows with all security features disabled and still got the same error.
![image](https://user-images.githubusercontent.com/1812311/47946144-61d51900-dee6-11e8-9d76-28ed0392299d.png)

**Comment by Kwoth** [comment]
@Kaoticz did you try directly downloading the exe from github and seeing if that works?

**Comment by Kaoticz** [comment]
@Kwoth Yes I did and yes it worked.

**Comment by Kaoticz** [comment]
That's exactly the workaround we are giving to people on Discord.

**Comment by Kwoth** [comment]
Then the download code is corrupt. Super weird.

**Comment by Kwoth** [comment]
Ok lets just move this to #2460 Updater is broken beyond repair.
