### ISSUE TITLE
Permissions command usage response string

### ISSUE THREAD

**Issue by Skarmunds** [Kwoth/NadekoBot#2637]
Your used command could be shown actually the same in response. In this example it's add qoute command.
![discord_2018-10-29_21-51-14](https://user-images.githubusercontent.com/38059263/47681539-6b9f0980-dbd2-11e8-8585-c5556df8a304.png)

**Comment by Kaoticz** [comment]
Where is the issue here?
The first dot is the prefix, the second is the command.

**Comment by Skarmunds** [comment]
Ok, closing it. Never thought of this. :sweat_smile: I always thought it's 2 dots forgetting prefix. Only case with this command. :ok_hand:
