### ISSUE TITLE
.waifuinfo not functioning properly

### ISSUE THREAD

**Issue by Vyndinctus** [Kwoth/NadekoBot#2638]
So earlier today i was testing out the waifu functions. Once i had finished, i executed the command .deletewaifus. It reset all the data, but now when someone inputs the command .claim 50 (name), it claims them, but does not show up on .waifuinfo. If you type .waifus, it shows you the top waifus, but it does not show up on .waifuinfo.

**Comment by Kaoticz** [comment]
Workaround: have someone gift you any waifu item.
I thought that bug had already been resolved a few versions ago.

**Comment by Kwoth** [comment]
Oh, that's the  bug we've had when we were testing it, but it magically went away and we never figured out what was causing it.

**Comment by Kwoth** [comment]
👌 found the issue

**Comment by Vyndinctus** [comment]
is there a fix?

**Comment by Kwoth** [comment]
Fixed already in the latest patch. Not sure when public nadeko will be updated.
