### ISSUE TITLE
[Feature Request] Set Role Based on Patreon Level

### ISSUE THREAD

**Issue by digiwombat** [Kwoth/NadekoBot#2639]
I know Patreon has a bot for this but it doesn't work something like 90% of the time for my Patrons and I'd love something a little less opaque.

Since there is already Patreon integration for currency, I'm hoping we could get a bit more flexibility over what we can do, especially on the Role side.

**Comment by Kaoticz** [comment]
Feature requests [go here](https://feathub.com/Kwoth/NadekoBot).
GitHub is for bug reports only.
