### ISSUE TITLE
[Feature Request] Public Polls

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#264]
Currently all opened polls require you to PM the bot. Most people, I find, don't care enough to actually PM the bot. Would like an option for public polls where users can just type their responses in the channel the poll was started in.

**Comment by notyouraveragegithubuser** [comment]
I disagree. People who care enough to vote shouldn't be turned off just because they have to PM the bot.

**Comment by fjrichman** [comment]
A revamp of the poll system would allow multiple polls to run at once (and be persistent ideally after bot restart). In a revamped system the bot would save polls with a number and then

**Comment by Kwoth** [comment]
@fjrichman nah. Just use strawpoll then.

**Comment by fjrichman** [comment]
@Kwoth In that case, might I suggest https://github.com/strawpoll/strawpoll/wiki/API

**Comment by xnaas** [comment]
Oh wow. Strawpoll has an API. TIL.

**Comment by Kwoth** [comment]
We could maybe make nadeko create a new channel #poll and let people type in there. If poll is public, peaple have read and write permissions, if poll is private, people can only write to that channel.

**Comment by Kwoth** [comment]
Added simple public polls in 1.0, better late than never.
