### ISSUE TITLE
The .autoboobs, .autohentai and autobutts arent working

### ISSUE THREAD

**Issue by NocToy** [Kwoth/NadekoBot#2641]
The repeating system doesnt repeat anything. I type .autohentai 30 and nothing happens for hours.

pls help an yes it is an nsfw channel.

**Comment by Kaoticz** [comment]
![image](https://user-images.githubusercontent.com/1812311/48017848-81eb1f00-e116-11e8-8d94-065a9e6e0640.png)
Next time, ask on our [support server](https://discord.gg/nadekobot).
