### ISSUE TITLE
.safebooru not working since the nov 4 update

### ISSUE THREAD

**Issue by SillyBirds** [Kwoth/NadekoBot#2642]
Hello,

Since the nov 4 updates, `.safebooru` was broken for my self-hosted nadeko, with searches with tags giving no results and using `.safebooru` alone always gave the same nsfw image:
![image](https://user-images.githubusercontent.com/22528910/48052041-23ba4c80-e1a7-11e8-8f76-1aac53eff593.png)

I had to revert to before the nov 4 changes to get back safebooru working. Don't know if it matters, but the nsfw module is disabled.

Thanks.

**Comment by Kwoth** [comment]
Yes indeed a bug. We're tracking this over at gitlab now.
