### ISSUE TITLE
[Bug] Random 502 Errors?

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#266]
I get this at random: `Severity: ErrorMessage: Failed to send message to Action Sack/logsExceptionMessage: The server responded with error 502 (BadGateway)`

It's not very often and there doesn't appear to be any rhyme or reason to it.

Thoughts?

**Comment by Kwoth** [comment]
That is DIscord server error, nothing we can do about it. ONly thing is wait for discord.net 1.0 and maybe volt will decide to resend failed messages.
