### ISSUE TITLE
[Request] More uses for our hard-earned cash!

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#268]
Currently you can't do a whole lot with your cash outside of healing your Pokémon and giving it to others.

Gambling would be fun. Blackjack? Lottery? Idk, just trying to throw out some random ideas.

**Comment by fjrichman** [comment]
An interesting idea would be "cash only" rooms where you can spend your earnings to gain access to a room subscriber service style so much cash per hour/day/month. That or a "private rooms" subscription, where they can pay the virtual currency to have their own private room named whatever they want on the server in which they're the mod for that room, with all the rights to modify the channel however they see fit.

**Comment by Kwoth** [comment]
we have betroll and betflip now, more to come. No need for this issue
