### ISSUE TITLE
[Request] -version command

### ISSUE THREAD

**Issue by MingweiSamuel** [Kwoth/NadekoBot#270]
If there isn't a way to get the current bot version, there should be. Something like `-v` or `-version`.

**Comment by appelemac** [comment]
it's in the stats,,,,,

**Comment by Kwoth** [comment]
I removed it because it needs to be manually maintained and I forget to change it often.

You have a completely useless build number in `.stats` ;)

**Comment by xnaas** [comment]
Can we just remove the version from `.stats` if it's just unmaintained bloat? 😛

On that note, there's `heap` in `.stats` and a `.heap` which are both different. Maybe some kind of indicator about that? Different terminology? I don't know.

**Comment by Kwoth** [comment]
for now we'l handle with .stats version until i find a better solution. I don't see any atm.
