### ISSUE TITLE
$award command functions

### ISSUE THREAD

**Issue by WildestDrake** [Kwoth/NadekoBot#271]
So I recently got Nadekobot on my Discord.
And I've been trying to use the $award command in order to plant them in our channels for fun.

So far I've tried several different methods of using the command, the bot recognizes the command, but it doesn't do anything.

$award @name 5
$award 5 @name
$award "5" @name
$award @name "5"

Is there anything I'm missing with the method of writing the $award command? Or do you have any ideas on the issue?

**Comment by appelemac** [comment]
a. It's bot owner only, ie. your id must be in the credentials.json/ownerIds array.
b. Syntax should be `$award 5 @person`
