### ISSUE TITLE
!m pl no longer working

### ISSUE THREAD

**Issue by aldun** [Kwoth/NadekoBot#272]
just updated to the latest version and !m pl is no longer working the bot replies with "No search results for that query."

**Comment by Kwoth** [comment]
It works.

Try some other query, or are you using the link?

**Comment by aldun** [comment]
using a link.

**Comment by Kwoth** [comment]
which one

**Comment by aldun** [comment]
I have tried youtube playlist and soundcloud both get the same response and they both worked before the update.

**Comment by Kwoth** [comment]
No, soundcloud playlists never worked. Youtube is broken i tested, thanks.
