### ISSUE TITLE
[Request] Ability to Disable Deletion of Greet/Bye Messages

### ISSUE THREAD

**Issue by TheBeverage** [Kwoth/NadekoBot#273]
Potential Command: .greetdel / .byedel
Function: Toggles whether or not to delete greet and bye messages after five minutes (currently on at all times)
Reason: I like being able to keep track of whenever someone has left or been invited to the group, and with it deleting so quickly it often can happen without anyone ever noticing. This would be very helpful.

**Comment by ohnozombie** [comment]
https://github.com/Kwoth/NadekoBot/blob/master/commandlist.md

Its at the top of the commands

**Comment by TheBeverage** [comment]
Oh, is that new? I didn't see that before, but thanks for adding it!

**Comment by Kwoth** [comment]
Yep, it's added in the release from 2/3 days ago
