### ISSUE TITLE
Nadeko doesn't respond with @ mentions, if it has a nickname

### ISSUE THREAD

**Issue by JustApollo** [Kwoth/NadekoBot#274]
I run nadeko for a private server, and I named it JuliaHolterBot, forgetting that it already has a bot tag. So I nicknamed it JuliaHolter, but @ing with the nickname it doesn't register the command, and @JuliaHolter ? doesn't give a response. Not a huge deal, but a problem nonetheless

**Comment by Kwoth** [comment]
I'm still unsure how to solve this without doing something ugly. For now just don't use nicknames.

**Comment by Kwoth** [comment]
You can change the name of your bot thought with `.newname` command

**Comment by JustApollo** [comment]
So when I use %mention% with the new custom commands, it will respond with the nick? Cool, thanks for continuing development on the bot!

**Comment by Kwoth** [comment]
No. %mention% is for use within command name. You have %user% which is mention of the user. Patch notes contain this information.

**Comment by hlaaftana** [comment]
In case this is still an issue and your prefixes can be regex or you can have multiple prefixes (which you seem to do), nickname mentions have a ! after the <@ and before the id.

**Comment by Kwoth** [comment]
@hlaaftana i'm using volt's commandbuilder, and it has no mention prefix in a sense i need it.
