### ISSUE TITLE
NadekoBot for Raspberry Pi?

### ISSUE THREAD

**Issue by Flezza** [Kwoth/NadekoBot#275]
Is it possible to host the bot on a raspberry pi successfully? I have tried but ran into a few errors. If it's not possible it would be a great new feature.

**Comment by tg44** [comment]
This is one of the things I will try after I finished school. Theoretically it's working on any linux but I will write a tutorial if I have time.

**Comment by Kwoth** [comment]
Yes it theoretically should work on any linux. If you post some errors we can try to resolve them here.

**Comment by xXLadonXx** [comment]
Trying the same thing at the moment actually.
I get that error most of the time though (sometimes TLS errors cause it seems to miss certificates but I probably just to have to install those) : 

> 
mono NadekoBot.exe
ÿþNo google api key found. You will not be able to use music and links won't be shortened.
No trello appkey found. You will not be able to use trello commands.
Forwarding private messages to owner.
No soundcloud Client ID found. Soundcloud streaming is disabled.
Severity: ErrorMessage: DisconnectedExceptionMessage: You must send data by websocket after websocket is opened!
Probably wrong EMAIL or PASSWORD.
System.Exception: You must send data by websocket after websocket is opened!
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at Discord.TaskManager.ThrowException () [0x00000] in <filename unknown>:0
  at Discord.Net.WebSockets.WebSocket.WaitForConnection (CancellationToken cancelToken) [0x00000] in <filename unknown>:0
  at Discord.Net.WebSockets.GatewaySocket.WaitForConnection (CancellationToken cancelToken) [0x00000] in <filename unknown>:0
  at Discord.DiscordClient+<BeginConnect>d__78.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at Discord.DiscordClient+<BeginConnect>d__78.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <filename unknown>:0
  at Discord.DiscordClient+<Connect>d__76.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[System.String].GetResult () [0x00000] in <filename unknown>:0
  at NadekoBot.NadekoBot+<>c+<<Main>b__32_3>d.MoveNext () [0x00000] in <filename unknown>:0


Same configuration works on Windows just fine.
Things to note, when starting the bot the Pi will instantly cap at 100% CPU

**Comment by Kwoth** [comment]
@xXLadonXx you didn't import root certs probably

`mozroots --import --ask-remove --machine`
`certmgr --ssl https://gateway.discord.gg`

And yes, atm we have a problem on linux which makes it take 90%+ of cpu. I have no idea what is mono doing.

**Comment by xXLadonXx** [comment]
Ahh thanks a lot for the discord cert I was missing that one.
Now I only get the exception mentioned above (like 15 times in a row), I assume that is due to the abnormal CPU load?

**Comment by Soundofdarkness** [comment]
Actually i am working with mono currently but i have like 5 % cpu usage while using Nadeko. Maybe its just the case on RPI

**Comment by Kwoth** [comment]
There are several people hosting nadeko on RPI atm, so there should be no problem (except cpu usage which is happening on linux machines only)

**Comment by Ezir** [comment]
So I was one of those people hosting Nadeko on a RPi before, and I think it may still be possible? I could be totally wrong since I'm not very experienced with Linux or .net, but the raspberry pi 3 model b uses a 64bit ARM processor, and I'm currently running a 64 bit OS (Fedora) on it. Though I think that may not be necessary? 
Recently (Jan 31) [This](https://stevedesmond.ca/blog/net-core-on-arm) blog was posted announcing a build of .net core for ARM processors. If I'm not mistaken, this should make it possible to run Nadeko on even a 32 bit pi? 
Sorry if I'm reviving a dead thread but I'd rather not have to run a full desktop PC 24/7 for Nadeko when it might be possible to use a power efficient and quiet pi. If I'm wrong in any of my assessments please let me know, as I'm still learning. Thanks!

**Comment by hendrikbl** [comment]
This looks interesting. I wanted to update Nadeko bot on my Pi 2 the last day and ended up thinking about buying the new Pi 3 model...
If there is a way of getting it to work on my Pi 2 model I would be more than happy!

**Comment by Ezir** [comment]
It would have been cool to get it working on Pi 2 but the requirement for 64bit Architecture rules that out. And on the model 3 I got really close, only to be stopped by what I believe to be a library mis-match that I couldn't figure out. Really quite unfortunate.

**Comment by Bypus** [comment]
When i try to install Nadeko on my Raspberry (Raspbian) it tells me "Your system architecture is armv7l which is unsupported to run Microsoft .NET Core SDK.". I suppose there is no way to counter it ?

**Comment by Buglardons** [comment]
I have the same problem. Now the problem gone fix ( i don't know how) but now i have an other problem i have some error : 
![2017-06-29 16_09_14-greenshot](https://user-images.githubusercontent.com/7920156/27692153-440e426c-5ce6-11e7-8915-8f1a95d4956b.png)
