### ISSUE TITLE
[Suggestion] Game Only Rooms

### ISSUE THREAD

**Issue by fjrichman** [Kwoth/NadekoBot#282]
Much like .v+t has the ability to give you access to a text chat if you enter certain voice chats my suggestion is something similar that allows access to Text/Voice chats only when you're playing certain games. 

The idea originally comes from here: https://www.reddit.com/r/discordapp/comments/4idc8j/is_there_a_way_to_make_a_channel_you_can_only/

**Comment by Kwoth** [comment]
lol thats a nice idea, ill add it when i have time

**Comment by Kwoth** [comment]
I dropped this idea a month or so ago, great idea, but it's too much.
