### ISSUE TITLE
-help and etc. don't work.

### ISSUE THREAD

**Issue by NonUhnonymous** [Kwoth/NadekoBot#285]
It says on the right side, its online in the server along with my other bots. When I try to do -help nothing happens. However when I put -module it responded with 
"List of modules: 
• Administration
• Help
• Permissions
• Conversations
• Gambling
• Games
• Searches
• NSFW
• ClashOfClans
• Pokegame
• Translator
• Customreactions"

So it does seem to be in the server. The bot doesn't show up on the left side of the voice channels.

**Comment by Kwoth** [comment]
She is trying to DM you. You probably disallowed PMs from that server. No other reason this could be happening I can think of
