### ISSUE TITLE
~gelbooru is broken on some hosts, which makes ~hentai unusable too

### ISSUE THREAD

**Issue by Nythius** [Kwoth/NadekoBot#289]
~hentai isn't a valid command anymore? Couldn't find any change regarding that on the Releases.

**Comment by Kwoth** [comment]
Are you hosting your own bot?

**Comment by Nythius** [comment]
No, I am using the hosted one.

**Comment by Kwoth** [comment]
Can you try ~gelbooru and ~danbooru, and tell me if they work

**Comment by Nythius** [comment]
~gelbooru is not working as well. ~danbooru is working

**Comment by Kwoth** [comment]
[NadekoBot v0.971.zip](https://github.com/Kwoth/NadekoBot/files/257780/NadekoBot.v0.971.zip)

Can you tell me if this one fixes your issue? Probably just replacing the NadekoBot.exe will be enough.

Weird thing is that this is affecting NadekoBot on the server but not on my local PC. Maybe gelbooru got blocked in U.S? Just guessing.

**Comment by Nythius** [comment]
The client-side one is working as intended. The server-side commands still aren't working. The U.S. block might be a possibility, as I don't live there.

**Comment by Kwoth** [comment]
What do you mean by client side and server side?

**Comment by Kwoth** [comment]
Ohh you said you don't host your own bot. Sorry. Yeah ok then ill try restarting nadeko with the new patch

**Comment by Kwoth** [comment]
Ok its fixed.
