### ISSUE TITLE
disable custom command for all roles, but enable for user. Still does not work even for user.

### ISSUE THREAD

**Issue by ohnozombie** [Kwoth/NadekoBot#290]
i did `;rc "command" disable all` then `;uc "command" enable @name` but it still doesn't let that user use that command. is it because i disabled it for all roles? but i did enable it for that user shouldn't it let that user call the command since it's been enabled for the user?

it seems like ;uc doesn't work if ;rc disable all is used. 

Is there another way i don't know off that i can disable the command for everyone but 1 user? excluding roles.

**Comment by Kwoth** [comment]
No that won't work.

Give yourself a role, lets say "admin" and do

`;rc "command" disable all`
`;rc "command" enable admin`
