### ISSUE TITLE
[Request] Infinitely long playlists, but only for bot owners

### ISSUE THREAD

**Issue by HylianShroom** [Kwoth/NadekoBot#291]
I see you extended the playlist length since my last request. That actually helps a lot, but we're looking to go even further if it's possible.

https://www.youtube.com/playlist?list=UU9ecwl3FTG66jIKA9JRDtmg

That's every video on SiIvaGunner's channel, and it stays constantly updated. We want to queue this up and shuffle it so we can always have high-quality rips playing. Obviously being able to queue really long playlists can be abused and maybe even crash the bot, which is why I suggest to restrict it to bot owners only.

**Comment by Kwoth** [comment]
Sorry its not possible. Even 500 is going to be weird due to not being able to stop queuing of playlist which can take up to a minute with 500 tracks.

Since proper playlist queuing is now implement, you can build from source and simple change the number in `!m pl` command and it will work.
