### ISSUE TITLE
Music sometimes creates a second playlist, while still playing the first one

### ISSUE THREAD

**Issue by HylianShroom** [Kwoth/NadekoBot#292]
This video should explain everything: https://www.youtube.com/watch?v=OUEVXdtIMFs

Also a note at the end, when this happens the titles in the playlist get out of sync. The only way to fix any of this is to wait for the playlist to run out without queueing anything or restart the bot, since we have no access to the original playlist.

**Comment by Kwoth** [comment]
Its a known issue, although i thought it only happened to me.

If you can recreate it that would be great, because we were unable to.

**Comment by HylianShroom** [comment]
We can't recreate it at will because it seemingly happens at random. Occasionally someone will queue a song and it'll just be in it's own playlist and the bot will start playing alongside what's already playing, in slow-motion satan mode. What's in that video is all I have on it.

**Comment by Kwoth** [comment]
We'l just wait until next iteration of music and this will get fixed along the way. I may make a music problems mega-issue to track numerous music problems.
