### ISSUE TITLE
many suggestions hope it become a new features on Nadeko

### ISSUE THREAD

**Issue by calmnoise** [Kwoth/NadekoBot#295]
(1)
 to seperate language and make a file called language.json .. so there anyone can translate the bot to his language
----
(2) 
Suggestion to make a file for command settings "commands.json" there I can easily edit commands shortcut , enable/disable a certian command, create custom command with bot reaction
----------
(3) 
to make connection between Bot and Youtube channle in a way that notice you with new videos uploaded
 [this feed will notice with any new uploaded video in certian channel]
       with video title embaded video link
https://developers.google.com/youtube/2.0/developers_guide_protocol_video_feeds

---------
(4)
when the command is disabled" it will send the error msg to direct msg instead of the same channel
Suggestion to enable ability to change Bot msg when someone speak with him on direct msg 
((commands can be send to him & Reaction to each of them ))
suggestion with enable commands in a certian role or channel to add something like ((enable_only on )) rather than disable in each channel ... that will safe time  so for example I'll enable (music module only on music channel) or ony for certian role

these are suggestions that I hope you like it

thank you

**Comment by Kwoth** [comment]
Its good enough to post them in suggestions channel
