### ISSUE TITLE
Music refuses to play

### ISSUE THREAD

**Issue by Turipuru-chan** [Kwoth/NadekoBot#296]
I've done everything as said in guide, but that damn music refuses to play no matter if I play it from my local drive, YouTube or Soundcloud.
That's how it looks in bot's console: http://puu.sh/oRIMP/d89519bee8.png
,,Nie można odnaleźć określonego pliku" means ,,Can't find specified file"

**Comment by kongslien** [comment]
Missing ffmpeg. Check if path is correct. If it is, then reboot computer, it should resolve your problem.

**Comment by Kwoth** [comment]
Yes this is a common error if you didn't setup your ffmpeg correctly. If it doesn't work for you recheck the guide.
