### ISSUE TITLE
Radio streams not working.

### ISSUE THREAD

**Issue by DarkRsing** [Kwoth/NadekoBot#298]
So I've been hosting the bot on my own machine on v0.98 . 
I've gotten the youtube/soundcloud API's with no problems and both have been working great, with minor hippcups here and there , however when I try to stream a radio ( using !m radio *link* ) it doesn't work, it says the stream has started and it finishes it almost instantly without playing anything

Console log : 
>>Command !m radio
Prebuffering done? in 3000
Song finished. [0]
Awiting buffer task
Buffer task done.

**Comment by Kwoth** [comment]
That means you haven't supplied a valid radio link.
http://yp.shoutcast.com/sbin/tunein-station.m3u?id=22146 

try that one for example. Supported formats are .m3u, .pls, .xspf, .asx and direct mp3 streams

**Comment by DarkRsing** [comment]
yeah well, I did and it still doesn't work , the stream in question is http://hive365.co.uk/players/playlist.asx

**Comment by Kwoth** [comment]
Weird, it really doesn't work.

**Comment by DarkRsing** [comment]
They have other formats besides a direct stream link, all are the same though. weird thing is that it doesn't give any error

**Comment by Kokoro-Neko** [comment]
Suddenly this is happening with YouTube and Soundcloud as well on multiple versions, maybe it's just me. It was working fine then suddenly stopped today, no idea why.
Screenshot from the console-. http://prntscr.com/bfpqs5

**Comment by Kwoth** [comment]
Im going to stop tracking this, like other music issues. Music is getting rewritten. It's just a matter of time.
