### ISSUE TITLE
>8ball formatting breaks in certain scenarios

### ISSUE THREAD

**Issue by ix** [Kwoth/NadekoBot#303]
(don't ask why i tried to do this)

![scrot32](https://cloud.githubusercontent.com/assets/16062051/15448199/de8ac8bc-1f28-11e6-84ef-1febbe1e2165.png)

**Comment by Kwoth** [comment]
?

**Comment by ix** [comment]
basically, embedding actual markdown in an `>8ball` question causes nadeko's formatting for `>8ball` to break, hence there should be some form of input sanitization

this could also happen for other commands but i haven't tested them

**Comment by appelemac** [comment]
That's for anything; actually going and sanitizing the input is a lot of hassle which wouldn't have much of an advantage.

**Comment by ix** [comment]
hm, okay
