### ISSUE TITLE
Any way to edit commands added with ... ?

### ISSUE THREAD

**Issue by fisherino49** [Kwoth/NadekoBot#306]
Talking about this one: http://i.imgur.com/RteG8ae.png
I can see no edit or delete commands for those, is there any way to edit or remove the ones I don't like?

**Comment by Kwoth** [comment]
Nope unless you edit data/nadekobot.sqlite with sqlitebrowser.

I've pushed a commit which lets you delete quotes you made, or any if you are server owner. It will be in the next release

**Comment by fisherino49** [comment]
Thanks for the quick reply, and glad to hear it!
