### ISSUE TITLE
Avatar reverse image search

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#31]
In addition to currently existing `@bot av` add `@bot rav` which will reverse image search that person's avatar and get the link.

**Comment by tg44** [comment]
not really doable, but you can create the google search link easily:
`https://images.google.com/searchbyimage?image_url={@bot av @user}&encoded_image=&image_content=&filename=`

(I didn't find any easy to use free rev img search api.)

**Comment by Kwoth** [comment]
thats good enough, thanks a lot, ill add it later today
