### ISSUE TITLE
Unable to remove quotes from my own nadeko bot?

### ISSUE THREAD

**Issue by samuel1260** [Kwoth/NadekoBot#310]
iv been looking into the files and the commands to remove quotes but i cant seem to figure it out both ..qdel, ..quotedelete dont seem to be working on my server so i stopped looking and turned to you guys please help!
Thanks!

**Comment by Kwoth** [comment]
Your ownerID in credentials.json is probably wrong.

**Comment by samuel1260** [comment]
that cant possibly be the problem since i can use all the other server owner only commands just fine

**Comment by appelemac** [comment]
Did you update to the latest version? i.e. `-h ..qdel` should respond with the description

**Comment by samuel1260** [comment]
also Kwoth im hosting from my own computer and all my other owner only commands work fine and i did my ownerID right im pretty sure that the quote deleting is the only thing that isnt working

**Comment by Kwoth** [comment]
Do what applemac told you. You are probably just not on the latest version.
