### ISSUE TITLE
Can't queue YouTube Playlists

### ISSUE THREAD

**Issue by mathiaslsn** [Kwoth/NadekoBot#312]
Youtube playlists not working. I'm also having issues with queuing regular songs but just by keyword instead of link.

http://prntscr.com/b8a9nf // issue of queuing regular songs by keyword

http://prntscr.com/b8aaao // issue of queuing playlists

**Comment by samdivaio** [comment]
You are having the youtube API issue like everyone else, it's alright to see if you can't queue half of the songs right now, we are waiting for google to fix that too! Thanks for notifying though, keep up the good work 👍🏻

**Comment by Kwoth** [comment]
Either youtube data api is not enabled, or you have standard issue which are not related to the bot. I'd bet on the first

**Comment by bape234** [comment]
17:54:47 CommandHandler | Command Errored after 0/0/0/0.032s
        User: smokja234#2230 [201774747565031433]
        Server: Chilling [306877932251643914]
        Channel: lounge [306877932251643914]
        Message: !!pl https://www.youtube.com/playlist?list=PLMC9KNkIncKvYin_USF1qoJQnIyMAfRxl
        Error: Google.Apis.Requests.RequestError
Bad Request [400]
Errors [
        Message[Bad Request] Location[ - ] Reason[keyInvalid] Domain[usageLimits]
]

This is what I get when I try to queue a playlist with: !!pl https://www.youtube.com/playlist?list=PLMC9KNkIncKvYin_USF1qoJQnIyMAfRxl

Any help would be awesome
