### ISSUE TITLE
Can't queue songs

### ISSUE THREAD

**Issue by mathiaslsn** [Kwoth/NadekoBot#314]
I recently wiped my computer, making sure to backup my bot files.

On my newly installed windows, I try to queue a song like a would normally, and it queues and then finishes fairly quickly without making any sound. I get this issue in the command prompt:

http://prntscr.com/b8visb

**Comment by Kwoth** [comment]
you did not add ffmpeg to path. Make sure you read the guide carefuly. Try typing `ffmpeg` in the console.Restart your PC if you're sure you got it right.
