### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by KuroMera** [Kwoth/NadekoBot#323]
I don't know if i missed it in the commands or not but i couldn't get the bot to join or play music
also for me all the admin commands doesn't work and i am the owner other wise its a great but i just need help with this

**Comment by Kwoth** [comment]
Music is temporarily disabled. Administration commands which specify "OWNER ONLY" mean the BOT OWNER - not SERVER owner.

If you want music and Owner only commands you would have to host yourself. You have a guide in the readme file.
