### ISSUE TITLE
[Feature Request] Multi-Line Playlist Additions

### ISSUE THREAD

**Issue by AndrewYoungs** [Kwoth/NadekoBot#326]
Multi-line reading for songs to search for and add to playlist.

Would function something like:

https://gyazo.com/da87dca79c490e8957e48274f5208f76

Parses message splitting it up by new line character "\n" and then executing each queue command individually in a loop.

A great tool for formatting queued songs for nadeko is: http://textmechanic.com/text-tools/basic-text-tools/add-prefixsuffix-into-line/

**Comment by Kwoth** [comment]
That's both impossible with the command system we're using, (looping command execution) and unneeded. You can just make a youtube playlist with the songs you want and queue that.

**Comment by AndrewYoungs** [comment]
Oh didn't know it supported YouTube playlists, that's pretty useful. But, impossible isn't the word I'd use. Possible with effort :P But I got you, thanks for the reply.

**Comment by appelemac** [comment]
Maybe, when Kwoth realizes his dreams of overhauling the current command system😝
