### ISSUE TITLE
Can not unblacklist server

### ISSUE THREAD

**Issue by ItsFriday** [Kwoth/NadekoBot#328]
So, I added the following server id to my blacklist "157298866524258304", I try to remove it, but I cant.
I tried to remove it from config, but after I restart the bot it puts that id back in the
`  "ServerBlacklist": [
    157298866524258304
  ],
`
Is there anyway to fix this?

**Comment by Kwoth** [comment]
Stop the bot. 
Make your serverblacklist look like this 
`"ServerBlacklist": [ 157298866524258304 ], `
Run the bot.
