### ISSUE TITLE
Some music searches or links do not work.

### ISSUE THREAD

**Issue by ItsFriday** [Kwoth/NadekoBot#330]
What I mean by this is for example: https://www.youtube.com/watch?v=UzQXEQqX70I
will not be played in the bot, it gives me the Dictionary error. Is it possible to fix this to where any you tube video could be played?
I can't even get around this error sometimes.

**Comment by Kwoth** [comment]
It sometimes happens, try another link.

This is a part of issues we are not tracking (music) because music will be rewritten at some point in 1.0
