### ISSUE TITLE
.repeat double posting, and ending up unable to be disabled.

### ISSUE THREAD

**Issue by AeonWilder** [Kwoth/NadekoBot#337]
On our server, I was setting a notification to be played in our general chat every 2.5 hours, containing a link to a Google Fomrs poll we were taking responses to over the week. I messed something up in the posting message, and resubmitted the command. Lo and behold, Nadeko was now posting the repeated message twice, with the difference in time equal to the amount of time it took for me to repost the edited message.

Not quite sure how it happened, as we were unable to replicate the circumstances, but I'll outline the gist of what happened before the issue.

- The repeat command that posted first was accidentally posted in another channel, while a repeat was running in our general chat. Nadeko logged that the message would be posted to the general chat, despite being in a different room.
- A .repeat was issued in that self-same room to cancel what we thought was a simple mistake fix.
- The repeat command, with a message beginning with an @here, was issued in our general chat to begin the loop. 
- Upon realizing that @here mentions fail to work in repeat messages, (It is unsure whether we issued a stop .repeat command or not) a .repeat command with the @here removed was issued, again, for 150 minutes.

Once we noticed the issue, .repeat commands were issued naked in every channel to try to resolve the issue, but a .repeatinvoke returns with the claim that there are no repeats programmed to occur. Since we're using a clone from https://www.carbonitex.net/Discord/bots , we don't have access to .unstuck, and .restart doesn't terminate .repeat messages.

I'm currently in the painstaking process of setting up a personal clone for the server that we'll instate once the poll closes (since really, it isn't an issue until we don't want the repeats there), and since there's no option to set command/module permissions for a range of roles, I'll have to enter another 170-some-odd commands. I love the bot, and appreciate the help that you might be able to give that will save me the process.

**Comment by AeonWilder** [comment]
I fixed the issue by deleting and remaking the channel, but it'd be nice to figure out why it happens so it can be fixed/so we don't accidentally do it again.

**Comment by Kwoth** [comment]
I think this is fixed in one of the recent commits by dragon (a guy who's helping). Global Nadeko is not on that release yet.
