### ISSUE TITLE
command permission issue

### ISSUE THREAD

**Issue by mikotowp** [Kwoth/NadekoBot#339]
i don't know why i can't disable the command "copyme" in converstions module
i tried:
;sc copyme disable
;sc cm disable
;sc @Nadeko copyme disable
;sc @Nadeko cm disable
but none of them works
am i doing wrong?

**Comment by Kwoth** [comment]
`;sc "@Nadeko copyme" disable`

use double quotes for multi-word commands. Same applies to pokemon attacks.
