### ISSUE TITLE
Music plays for about 20 seconds and stops working completely

### ISSUE THREAD

**Issue by otaviomad** [Kwoth/NadekoBot#341]
I'm using a vps, and the music plays for about 20 seconds until suddenly stopping and not working until I restart the bot, and it doesn't show anything on the terminal.
Also, it can still queue songs, it just won't play them. 

Update: it isn't about 20 seconds, it's exactly 20 seconds. After the freeze, I can still use the ls command. https://my.mixtape.moe/nyjpkz.png

**Comment by Kwoth** [comment]
We aren't tracking music issues, because music is getting a rewrite, but since it's exactly 20 seconds im guessing your VPS's RAM is getting full? 

No idea really. Just wait for the rewrite i guess
