### ISSUE TITLE
Custom Reactions Not Working

### ISSUE THREAD

**Issue by CancerSenpai** [Kwoth/NadekoBot#359]
Not sure if I did something wrong, but I AM the owner and it lists the reaction as added, however Nadeko won't respond. 
http://puu.sh/pAU1z.png
http://puu.sh/pAUqn.jpg

**Comment by Kwoth** [comment]
your Bot ID is probably wrong.

**Comment by CancerSenpai** [comment]
Weirdly enough, that worked, though the ID I replaced and the new ID were both identical! Thank you, and while this is still open, is there/will there be a way to have roles in which the color cycles? That'd be pretty cool, however difficult.
Thanks again!!

**Comment by Kwoth** [comment]
Not possible atm.
