### ISSUE TITLE
Externalize all strings

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#36]
Everything from errors to responses etc should be in an external file to allow people to translate the bot and add new replies to arrays.

**Comment by MasterDomino** [comment]
good idea would be to use resx files, as they provide quickest way of managing multilanguage, also debug strings like errors should stay english as its easier to debug such stuff

**Comment by Kwoth** [comment]
Working hard on this, around 40% done, no idea.
The ones left:
- [ ] Music
- [ ] Searches
- [ ] Permissions
- [ ] Utiltiy
- [ ] Games

**Comment by Kwoth** [comment]
Music and searches left.

**Comment by Kwoth** [comment]
Done. Need to get people to find missing keys where I messed up, then I'll set up a Poedit project and let people translate it.
