### ISSUE TITLE
Trying to play something

### ISSUE THREAD

**Issue by RiesvGeffen** [Kwoth/NadekoBot#362]
When I type something like "!m q https://soundcloud.com/illeniumofficial/the-chainsmokers-dont-let-me-down-illenium-remix" It says "Queued",  "Started" and finished within 3 seconds. If I check the console it shows me this "Buffering errored: The system can not find the file specified".

Hope you know the problem!

**Comment by Kwoth** [comment]
you didn't setup ffmpeg properly. Follow the guide carefully.

**Comment by RiesvGeffen** [comment]
I am 100% that I did set it up properly.

**Comment by Kwoth** [comment]
You didn't. Open cmd/terminal and type ffmpeg. It will say command not found or something similar. Try restarting your PC.

**Comment by RiesvGeffen** [comment]
I even tried that what you said and then it just showed me all the commands. But I fixed it now by downloading the same version of ffmpeg as I used with Redbot and now it works.
