### ISSUE TITLE
SoundCloud

### ISSUE THREAD

**Issue by Kitty1338** [Kwoth/NadekoBot#364]
So i enabled soundcloud and i cant figure out how to get it to work. I've tried taking a song form soundcloud and going !m q soundcloud link. Then a playlist under !m pl playlist link. Ive tried !m sc then a link. Whats the specific command for it? Or do i need a specific link?

**Comment by xnaas** [comment]
Does the console give any information/errors when you run the command?

**Comment by Kwoth** [comment]
!m q soundcloudlink works. If it doesn't you didn't add soundcloud api key in credentials.
No soundcloud playlist support atm

**Comment by Kwoth** [comment]
Just to confirm soundcloud works, and that `!m scpl` will be a command in the next rleaese to queue a soundcloud playlist
