### ISSUE TITLE
Display Custom Commands Better

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#367]
Alright @Kwoth. You wanted my 50 github issues? Here's the first one. 😛 

The current method for displaying commands is `.lcr [page]`. This is fine if you have like 5 commands. Once you start to get a few dozen, each with many responses, this becomes an ugly nightmare. Here's some example screenshots:

![ss1](http://i.imgur.com/grIeHWZ.png)
![ss2](http://i.imgur.com/5YHcBLc.png)

There are a few problems with this:

1. Tons of wasted space.
2. Impossible to actually find commands as they're not in any order other than "created time."
3. This creates a lot of blank pages. For us, we're missing page 6, 7, and numerous others.

A suggestion for fixing this problem is to do it like Red does.

![Get PM'd!](http://i.imgur.com/fVvikMd.png)

She PMs you a list of all of the commands and only the commands. She can also break the list into parts to send as multiple messages for when you have an ass-load of commands (like my server :D). This does not show the reaction to each command, but it at least shows you what is even available.

Now that you have a list of what's available, you could make another command `.lcr mike` to list every reaction to the command `mike`. `.lcr "eat shit"`, `.lcr !foad`, etc., etc.

**Comment by Kwoth** [comment]
Done
