### ISSUE TITLE
Edit Commands

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#368]
So this is actually going to build off of #367 a little bit.

-----

So currently you can add and delete reactions as you please. That's nice and all, but needing two steps to add and then delete seems tedious. If you could simply edit an existing, no longer needed/desired one, that would be super amazing.

Example: `.ecr mike 4 <link>` -- This would edit the 4th link from `mike` to be something else.

This system wouldn't be super useful until the changes from #367 are implemented, but it's still an important QOL change.

**Comment by Kwoth** [comment]
done
