### ISSUE TITLE
Nothing happens after queueing songs

### ISSUE THREAD

**Issue by TechNick6425** [Kwoth/NadekoBot#369]
I just set up the latest version of NadekoBot on OS X 10.11.5, installing both ffmpeg and opus-tools using homebrew. Upon using "!m q" to queue a video, Nadeko queues the song, but won't connect to a voice channel.

- Nadeko has the necessary permissions
- ffmpeg and opus are installed and updated

After waiting less than a minute, this message was logged in the console continuously.
```
Severity:` ErrorMessage: Error handling VOICE_STATE_UPDATE eventExceptionMessage: Object reference not set to an instance of an object
```

**Comment by Kwoth** [comment]
I think this is the exact same issue other people hosting on mac had. Nobody I know of managed to get music working on a mac

Maybe try building mono from source?

**Comment by TechNick6425** [comment]
Recompiling the latest version of Mono from GitHub worked.

**Comment by Kwoth** [comment]
Awesome, great news! I will add it to FAQ, since we don't have a mac guide yet. If you feel like making one, that would be great ;p

**Comment by TechNick6425** [comment]
I'll write I guide when I get home this afternoon.
