### ISSUE TITLE
Deleting "e" command

### ISSUE THREAD

**Issue by Loolzy** [Kwoth/NadekoBot#370]
After completely deleting the "e" command from data/config.json it continues to work.
deleted both manually and through `.dcr e`
The only way to delete it completely is remove it from source-code AND config.json
[screenshot](http://i.imgur.com/klHuIHl.png)
I assume it's not supposed to be like this

-PoPi | Secret Service

**Comment by Kwoth** [comment]
You have to restart the bot.

**Comment by Loolzy** [comment]
[it did not help](http://i.imgur.com/wl7BKCk.png)

**Comment by Kwoth** [comment]
Look, custom reactions are directly loaded from the file. If there is no custom reaction named "e" in the config.json, it should not load and work. You might be editing the wrong file. Keep in mind restarting the bot will only then reload the custom reactions.

So, stop the bot, delete it from reactions and start the bot back up, it won't work anymore.

**Comment by Loolzy** [comment]
i'm honestly confused at this point.
[gif](http://i.imgur.com/SwYalcN.gifv)
Note that it adds `e` command after it's ran
exactly the same happens when `.dcr e` is used.

**Comment by Rosenvine** [comment]
It's hard coded in. Remove it from configuration.cs and it should clear up.

**Comment by Kwoth** [comment]
It is hardcoded, but it should be overwritten with the actual configuration. I didn't look into this yet since i don't see it as a priority issue, but i will see about what is going on tomorrow or day after tomorrow.

**Comment by Kwoth** [comment]
Fixed in the next release.
