### ISSUE TITLE
Nadeko music local problem

### ISSUE THREAD

**Issue by Nythius** [Kwoth/NadekoBot#372]
Whenever I try to play a single song/soundfile through !m local +directory it get cut or just doesn't play at all.

I have no idea how to fix it. It is working for playlists apparently. ffmpeg is installed properly.

**Comment by Kwoth** [comment]
You don't use `!m local directory`, you use `!m lopl directory`

**Comment by Nythius** [comment]
I want to play a single file though, in some cases.

**Comment by Kwoth** [comment]
![img](https://i.imgur.com/2gKA8Eb.png)
for single files use `!m lo path/to/file`. It works just tested it. Keep in mind bot has to be hosted on your own PC in order for it to work, or you have to transfer the music files to your server.
