### ISSUE TITLE
Formatting of "showcustreact"

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#380]
First, thank you so much for this @Kwoth. :heart:

-----

So, showing custom reactions is great...but maybe some catches for commands that already have formatting in them?

![img](http://i.imgur.com/eF5kJA8.png)

As you can see above...the formatting gets a little bit wonky when commands with formatting already present are listed. Also all that blank space... :smile:

**Comment by Kwoth** [comment]
fixed, the whitespace is a discord bug because the images load for a second then disappear.
