### ISSUE TITLE
[Feature Request] Aliases

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#381]
I think it would be really awesome if we could add our own aliases.

Option 1: `!alias add !meme !memegen` This would add `!meme` as an alias to `!memegen`.

Option 2: `!alias add meme memegen` This would accomplish the same as option 1, but looks a little different.

Formatting is up to your discretion. Aliases are definitely not a priority by any means, but would be a great QOL feature.

**Comment by Kwoth** [comment]
This is impossible due to how discord.net is working.

**Comment by xnaas** [comment]
That's a shame, but thanks for the info, @Kwoth. :smile:
