### ISSUE TITLE
.logserver and .userpresence commands are merged

### ISSUE THREAD

**Issue by Ryonez** [Kwoth/NadekoBot#382]
I run a self hosted Nadako bot on windows.
She is a part of a large server and does some logging. However, the latest updates seem to have broken the .logserver and .userpresence commands as shown below.

http://i.imgur.com/DZgalTr.png

**Comment by Kwoth** [comment]
are you on latest-latest version? We had a hotfix to fix this.

**Comment by Ryonez** [comment]
Updated less the 5 mins ago.

Bot Version: NadekoBot v0.9.6029.18008

**Comment by Ryonez** [comment]
Option 2 of the updater.

**Comment by Kwoth** [comment]
It works for me, i just tested it ...

**Comment by Ryonez** [comment]
What's your bot version? Because it's not working for me.

**Comment by Kwoth** [comment]
@Ryonez you are right, i either didn't fix it completely or uploaded the wrong release, I downloaded the release version and it had that problem. I uploaded another version, use updater again with number 2 and tell me does it work for you now.

**Comment by Ryonez** [comment]
Sweet, I updated to: Bot Version: NadekoBot v0.9.6031.2385

.logserver seems to function correctly now.

Thank you for fixing it.
