### ISSUE TITLE
Can't play music at all

### ISSUE THREAD

**Issue by ihatevim** [Kwoth/NadekoBot#383]
https://upload.teknik.io/1dC5g.png

Just instantly finishes before even starting playing. 

I manually compiled ffmpeg from the github source so it's the latest release 100%

**Comment by Kwoth** [comment]
delete ffmpeg and get it like this. http://www.faqforge.com/linux/how-to-install-ffmpeg-on-ubuntu-14-04/

Since it is correctly resolving the song, but won't buffer it, i'm just guessing you have a 64bit ffmpeg on 32bit system, or something like that? Or maybe very limited RAM?

**Comment by ihatevim** [comment]
I can't get it like that because I'm on debian Jessie. It's already included in my non-free packages but I went a step further and compiled it myself from the latest github version.

**Comment by Sevenn83** [comment]
Same problem :c

**Comment by Seven--** [comment]
I had this problem, the updater doesn't seem to download FFMPEG.
Easiest fix is just to dump the three .exe files you get from [FFMPEG](https://ffmpeg.zeranoe.com/builds/) into the folder with the NadekoBot.exe.

Pictured here.
![](http://image.prntscr.com/image/ba8fbabab9d14504b8955e69d18712eb.png)

**Hope it helps!**

**Comment by ihatevim** [comment]
No, and maybe if you'd read the actual issue or any of the replies to the issue you'd be able to tell why you didn't help at all.

https://upload.teknik.io/lFJha.png
https://upload.teknik.io/0tpjA.png

**Comment by Kwoth** [comment]
@ihatevim no need to be rude :D

https://github.com/Kwoth/NadekoBot/blob/dev/LinuxSetup.md#ffmpeg someone updated the guide with Jessie instruction, can you delete your ffmpeg and try installing it like this? (there is "if you are running jessie" part)

**Comment by miraai** [comment]
@Kwoth `someone updated`, mhm

**Comment by ihatevim** [comment]
Installed it that way, still have the same issue:
https://upload.teknik.io/bRs5R.png

**Comment by miraai** [comment]
Did you do clean install with provided guide?

**Comment by ihatevim** [comment]
Yeah I just ended up installing it on docker and giving up, now I can't stop the music !m stop/!m destroy both fail.
