### ISSUE TITLE
[Feature Request] Show ALL Commands

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#384]
So...you _almost_ got #367 all the way. :stuck_out_tongue:

I would like to be able to do something like `.lcr all` and get a PM (multiple messages so it can get around the 2000 character limit) with _all_ of the custom commands.

Thanks @Kwoth, love you bb.

**Comment by Kwoth** [comment]
33176f894398ebe6d1b9e9c08327fd460e7d7d13

**Comment by xnaas** [comment]
Praise ~~the Sun~~ @Kwoth!
