### ISSUE TITLE
Not Able to Play YouTube Links

### ISSUE THREAD

**Issue by Psykonic** [Kwoth/NadekoBot#385]
![error](https://cloud.githubusercontent.com/assets/20362279/16700898/8686b61c-452a-11e6-9eb3-a305331b177d.JPG)
It's not playing any youtube links
I was thinking that it might be my Google API, but nothing is different from the first time I made it, which was working just fine then

**Comment by xnaas** [comment]
For what it's worth, I had issues with the Google API awhile back. I had to completely kill my project on Google's side, make a new project, and new keys. ¯\_(ツ)_/¯

**Comment by Psykonic** [comment]
ok, so it allows me to play some links, but not others
well, the youtube link in the pic was some meme thing my friend wanted to play, so I guess its not important
if someone wants to close this issue, go ahead

**Comment by Kwoth** [comment]
Could be one of many things. Either badly copied api key, not enabled youtube data api in the developer console or simply blocked song (usually happens with official vevo videos).

**Comment by Psykonic** [comment]
idk if its just me, but Google API is acting up and won't allow me to access my projects
prob the reason for my troubles

**Comment by Kwoth** [comment]
Was this resolved?

**Comment by Psykonic** [comment]
its resolved as it can get, since its not a problem with your program

**Comment by Kwoth** [comment]
Ah ok, sorry ;[
