### ISSUE TITLE
Toggle of .grde1 not working

### ISSUE THREAD

**Issue by Sankanyo123** [Kwoth/NadekoBot#386]
Im typing in the command to toggle turning on and off greet/bye msgs but its not working. I toggled it on so it deletes the msgs but i wanna toggle it off and its not working. im typing in the command .grde1 but its not turning the message delete off. Sorry complete noob when it comes to this. I wanna see the msgs so i know who is leaving and entering the server. thanks for help!

**Comment by kongslien** [comment]
Easy. It's not .grde1, it's .grdel. Small "L", not 1 at the end.

**Comment by Sankanyo123** [comment]
Ohhh LOL im so dumb thanks xDD
