### ISSUE TITLE
[Bug] Forward PM's to Bot Owner

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#388]
PM's to the bot seem to _only_ get sent to whoever is listed as the owner first in the config file.

I'm not sure if this is the intended functionality, but I have three user's set as bot owner and all three of us should be getting the PM's, not just me.

**Comment by Kwoth** [comment]
It was intended, i could add an option for it i guess?

**Comment by xnaas** [comment]
I would appreciate that. :smile:

**Comment by Kwoth** [comment]
done 57bc26dd46d9561d7822308b9f7bd07e6153653a
