### ISSUE TITLE
Can't do music in CentOS7

### ISSUE THREAD

**Issue by Penetros** [Kwoth/NadekoBot#393]
There's no guide for CentOS 7 so I gave it a crack, was able to get everything working, got no errors compiling ffmpeg or anything else.

I've tried downloading mono from tpokorra (Keeps a compiled version of the github community version) and the official site (Regular, beta, and alpha repos).

After a while I get this error:
Severity:` ErrorMessage: Error handling VOICE_STATE_UPDATE eventExceptionMessage: Object reference not set to an instance of an object
the same as 
#369 

I'm not particularly great at handling this linux stuff so I may have done something wrong here.

Mono JIT compiler version 4.4.0

**Comment by Penetros** [comment]
Not an actual solution, but while mono seems to have an issue on centOS with running music guessing from that previous issue, running another musicbot using python did not, and it worked fine.

**Comment by Kwoth** [comment]
@Penetros what you can try is using this https://hub.docker.com/r/uirel/nadeko/ and just copy your credentials.json to /nadeko folder and restart her afterwards. Everything should work

**Comment by miraai** [comment]
@Penetros 
Try to do it this way: https://github.com/Kwoth/NadekoBot/blob/dev/LinuxSetup.md
There's CentOS7 fix for mono, it was often causing issues. But you will have to do the clean installation.

In case you didn't fix it :]
