### ISSUE TITLE
I can't seem to play a single Youtube Song

### ISSUE THREAD

**Issue by nightfrost** [Kwoth/NadekoBot#397]
Hello there,

The bot is working PERFECTLY so far, everything works and you had a really detailed stup guide.

My only issue, if it is even an issue, is that the bot cannot play just a single direct youtube link. The issue I get is the following:
No search results for that query.
I use the command !m pl *youtube link*. I realise that pl would be for a playlist, but I can't seem to find another command for a single song?

Am I missing something? It can play playlists perfectly.

**Comment by miraai** [comment]
We solved it. :]

**Comment by Kwoth** [comment]
Thanks @miraai :)
