### ISSUE TITLE
Music Timeout

### ISSUE THREAD

**Issue by micmorris** [Kwoth/NadekoBot#4]
I've had some issues with playing music. If I queue up a song, the bot will join the channel, start playing the song, the song will be choppy and then the bot stops and leaves chat. The app window says that there was a timeout. When I queue up the same song again everything works fine, and as long as the queue is populated the issue doesn't appear. However when starting a fresh queue, this occurs every time.

I haven't debugged this yet, so I can't tell which layer or call is timing out. I will add a capture of the console when I get a chance.

**Comment by Kwoth** [comment]
I didn't experience these issues, and I cannot reproduce it. Which release are you on?

Keep in mind audio is still unstable, I'm working on fixing it.

**Comment by Kwoth** [comment]
Also, if you want you can join the NadekoBot discord server so we can talk about issues there, the invite is at the top of the readme file.

**Comment by micmorris** [comment]
I took the v0.7.b1.zip as-is and the audio worked in the way that I said above very consistently. I forked the repo last night and was going to look into debugging it today. I'm currently at work, but I can chat later tonight.

**Comment by micmorris** [comment]
Output from the console running the v0.7.b1.zip exe:
net: done. (1476880 read)
Audio stream timed out. Disconnecting.
Killing transcoder...
OutputFunc stopped

I feel like it doesn't have enough buffer time before playing, but that's just a guess.

However, when running the forked project (loading the DLLs), I get a completely different issue: an NPE when trying to connect to the voice channel. I'm going to load up the Discord project and ref to that to see if I can debug into the Join call.

**Comment by Kwoth** [comment]
Problem was - Outdated DLLs, and was solved in the discord chat. Repo is updated with the latest DLLs.
