### ISSUE TITLE
Imgur Searches

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#400]
> Note: `[p]` = prefix.

I would like the option to pull images from imgur and/or Reddit. Here is an example of pulling from imgur: [Red DiscordBot "image.py" cog](https://github.com/Twentysix26/Red-DiscordBot/blob/develop/cogs/image.py).

Examples:
- `[p]imgur search tits` would search imgur for "tits" and return the first search result.
- `[p]imgur gonewild new` would pull the three (or more or less, you decide) newest images from http://imgur.com/r/gonewild/.
- `[p]imgur gonewild top`  would pull the all-time top images from http://imgur.com/r/gonewild/top.

I used porn in all the examples above, but obviously this would work just as well for SFW content.

**Comment by Kwoth** [comment]
Waiting for @LawlyPopz to see if he wants to add it as an api on his server, because we can't really make people setup twitter api keys which are a disaster to work with

**Comment by xnaas** [comment]
FWIW, here it is in Python: https://github.com/Twentysix26/Red-DiscordBot/blob/develop/cogs/image.py

I assume `imgurclient = ImgurClient("1fd3ef04daf8cab", "f963e574e8e3c17993c933af4f0522e1dc01e230")` is the important part, but idk. ¯\\\_(ツ)_/¯

**Comment by LawlyPopz** [comment]
@xnaas Thanks this has helped me alot ill have the api up in the next 3 hours

**Comment by fkndean** [comment]
#767 
Added initial commit for imgur api. Will improve later.

**Comment by Kwoth** [comment]
Nah
