### ISSUE TITLE
[Feature Request] "Search" Google

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#402]
Pretty much title. Would be nice to have `[p]g` or `[p]google` to search Google and return the first result as a link.

**Comment by Kwoth** [comment]
nah, at least not for now

**Comment by xnaas** [comment]
Ok, as a less good option, how about just this, @Kwoth?

`User: ~g some words here`
`Bot: https://www.google.com/search?q=some+words+here`

**Comment by Kwoth** [comment]
Ok i'll do it

**Comment by Kwoth** [comment]
Since i actually liked `~g` i will add another command with your original request - to post the actual first result link

**Comment by Kwoth** [comment]
![image](https://cloud.githubusercontent.com/assets/2537696/21469585/f7169f14-ca59-11e6-938e-7f508c9effbc.png)
