### ISSUE TITLE
NadekoBot occasionally crashes

### ISSUE THREAD

**Issue by Evinagro** [Kwoth/NadekoBot#407]
Running NadekoBot on my Win7-64bit system, it occasionally crashes with a Windows error "NadekoBot.exe has stopped working". Is there any way to get a crash report and put it here next time it occurs?

**Comment by miraai** [comment]
You can always go to Nadeko's Discord server, and ask for help from support. But you should also check your Nadeko setup, because this is the first time I see this error. :]

**Comment by Kwoth** [comment]
Yep, this should never happen, please come to our discord server and we'll resolve it. https://discord.gg/0ehQwTK2RBjAxzEY
