### ISSUE TITLE
[Feature Request] automatically .setgame when playing music.

### ISSUE THREAD

**Issue by Boneshock** [Kwoth/NadekoBot#408]
When playing music, automatically set the currently playing game to the song's title. (Normally done with the .setgame command)

**Comment by kongslien** [comment]
That's already a feature. "!m setgame"

**Comment by Boneshock** [comment]
@kongslien "!m setgame" does nothing, is it in a newer build?  
.ropl and .adpl %playing%  did the trick though.

**Comment by kongslien** [comment]
"!m setgame" is the old option i guess. Don't know why i even still think it works, my bad.
