### ISSUE TITLE
[Feature Request] Temporary Roles

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#409]
From #suggestions on the server:
> Vole: Temporary Roles (like the v+t plugin)
Group up all people which are "playing Overwatch" at the very moment into the role Overwatch and display it on the right so they are grouped up together.
Group up all people which are "streaming" into the role "Streaming" as long as they are doing so.
When they are not streaming or not playing a game at the moment they back in the normal user list.

**Comment by Kwoth** [comment]
This by itself won't be done, but look at #282 , that will be implemented and has same side effect (creating roles for users with a game) most likely.
