### ISSUE TITLE
[Enhancement] Per-channel filter lists

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#410]
From #suggestions on the server:

> Kanjo: Ability to ignore certain filtered words on a per channel basis.

> Currently you can only have 1 list of filtered words and enable or disable the entire list on a channel by channel basis. This means if you add 2 words to the filtered word list and enable it on two channels those channels loses access to both words. This makes it impossible to have the 1st word filtered from the 1st channel and the 2nd word filtered from the 2nd channel without filtering the other word in the channel at the same time

Basically, If I have `#room1` and `#room2`, they would each have their own list of filtered words.

**Comment by Kwoth** [comment]
This would remove backwards compatibility ;s I will think about it

**Comment by Kwoth** [comment]
I've been working on filtering words for 1.0 today, it will be tough to control. I want to keep it simple. When we get a dashboard ill reconsider this

**Comment by SillyBirds** [comment]
would it be possible to add a silent delete option for filtered words? (delete without notifying the offending user)

**Comment by fearnlj01** [comment]
Do `;verbose 0` to turn off the feedback when a filtered word is deleted
