### ISSUE TITLE
Trello is unable to bind

### ISSUE THREAD

**Issue by Ryonez** [Kwoth/NadekoBot#416]
Nadeko is unable to link a Trello board to a channel with the following error:

[trellobind error msg.txt](https://github.com/Kwoth/NadekoBot/files/368144/trellobind.error.msg.txt)

**Comment by Kwoth** [comment]
Oh gawd.

I don't really support trello, it was originaly written for a separate trello bot in a very short time and i copied it over to nadeko. There are only a few people using it afaik. 

But, make sure board is public and your api key is correct, it works that's certain.

Good luck
