### ISSUE TITLE
self assign

### ISSUE THREAD

**Issue by theantihero** [Kwoth/NadekoBot#417]
.iam issue with role hierarchy. Seems to have an issue. Says it set the role, but throws an error message "I am unable to add that role to you. I can't add roles to owners or other roles higher than my role in the role hierarchy."

Doesn't do anything.

**Comment by appelemac** [comment]
well, does it work for other people below it in the hierarchy?

**Comment by Kwoth** [comment]
You can't use `.iam` if you are above the bot role in the role hierarchy, because the bot can't change your roles then.

**Comment by Sohel12** [comment]
yes
