### ISSUE TITLE
pokemon fight script  issue

### ISSUE THREAD

**Issue by s1lverw0lf** [Kwoth/NadekoBot#418]
There's a bug in  attacks script: 

ig u select e.g a steel type with
~settype steel 
 and check movelist and then attack 
~attack metal burst [@user] 
bot will recognize second word 
🔩bullet punch
🔩metal burst
🔩gear grind
🔩magnet bomb 

as a nickname and give an error 
this bug is in every attack that contains 2 words in attackname  

^_^

**Comment by s1lverw0lf** [comment]
using ~attack bulletpunch instead of bullet punch doesnt' work either

**Comment by Midnight-Myth** [comment]
Try it like this. 
~attack "bullet punch" [@user]

It should work like this.

**Comment by Kwoth** [comment]
^
