### ISSUE TITLE
Auto assignable role command (.aar) doesn't work. :(

### ISSUE THREAD

**Issue by TriAce** [Kwoth/NadekoBot#420]
Hello!

The auto assign role (.aar) command doesn't add the role to the new user that joins the server for some reason. It does show that it is enabled and disables fine though.

Thanks if you can fix it!

Regards, 
Tri

**Comment by miraai** [comment]
Use `.aar` to disable; `.aar Role` to enable. 
Did you create a role before you used `.aar`?
1. Create a role.
2. Use `.aar RoleName`

And just test it out. I just tried and it works fine.

**Comment by Kwoth** [comment]
^ works fine.
