### ISSUE TITLE
Avatar image sizing 

### ISSUE THREAD

**Issue by Starxie** [Kwoth/NadekoBot#421]
On my server I recently changed my bot's avatar picture but the image is squished. I was wondering what the recommended size for the avatar is.

**Comment by miraai** [comment]
About 150x150 works best. Avatar size and its look is on Discords side, so just pick something not waaay to big and not waay too small :]

**Comment by xnaas** [comment]
@Starxie also, general rule of thumb, choose something square (same length and width dimensions) and with content mostly towards the center since the edges get cut off.
