### ISSUE TITLE
`$draw 5` consider that an Ace is the weakest card

### ISSUE THREAD

**Issue by SkateurZeD** [Kwoth/NadekoBot#423]
https://github.com/Kwoth/NadekoBot/blob/master/NadekoBot/Modules/Gambling/Helpers/Cards.cs line 229 `return "High card " + cards.Max().GetName();`
But "Ace" is the number one, so everything is better than an Ace

**Comment by xnaas** [comment]
But what rules are we playing? Aces high? Aces low? :stuck_out_tongue:

**Comment by SkateurZeD** [comment]
Didn't know that Ace can be considered as the lowest card :o 
But Ace high isn't more common ?

**Comment by xnaas** [comment]
Aces high is probably more common. Cribbage would probably be one of the few "popular" exceptions. :stuck_out_tongue:

**Comment by SkateurZeD** [comment]
So in this case, it's a bug or it's wanted ? ;-;

**Comment by xnaas** [comment]
Pending @Kwoth on that one. :stuck_out_tongue:
