### ISSUE TITLE
.prune not working

### ISSUE THREAD

**Issue by Sheefou** [Kwoth/NadekoBot#428]
so after a while i've gotten to the point where i cant even, I've done a fresh install of Nakedo and my OS, and yet i can not prune messages. any reason behind this? it appears to be an issue on my end but i have no clue thus far

**Comment by appelemac** [comment]
Need more context; OS? does it show the command in console? any errors show? etc.

**Comment by Sheefou** [comment]
OS: Windows server 2012 r2
![2016-07-20 1](https://cloud.githubusercontent.com/assets/7604544/16996839/f49c9482-4e80-11e6-8df7-60f9014f39c1.png)
![2016-07-20 2](https://cloud.githubusercontent.com/assets/7604544/16996838/f49c1188-4e80-11e6-86e2-1361208c9ee3.png)

and no errors show up .-.

**Comment by Sheefou** [comment]
top is before fresh install and bottom is after fresh install

**Comment by xnaas** [comment]
Pretty sure `.prune` requires a specification of an amount to prune?

**Comment by Kwoth** [comment]
Tested it, it works. Make sure your bot has maange messages permission in discord. @Sheefou 

no there are 4 different uses of .prune @xnaas, read the command list :)

**Comment by Sheefou** [comment]
@Kwoth bot has literally all permissions possible

**Comment by miraai** [comment]
Working on it. Sometimes works, sometimes doesn't. Will be fixed soon.

**Comment by Kwoth** [comment]
Prune was failing when there are messages from users who left the server in the last 100 messages in the channel prune is ran in. It is fixed now.
