### ISSUE TITLE
Wiki Edits

### ISSUE THREAD

**Issue by ItsFriday** [Kwoth/NadekoBot#430]
Since music module prefixes were changed were changed. 
https://github.com/Kwoth/NadekoBot/wiki/Permissions

> 
;rc "!m nowplaying" enable all, enable the command for everyone
;rc "!m getlink" enable all, as above.
;rc "!m listqueue" enable all, as above.

to

> 
;rc "!!nowplaying" enable all, enable the command for everyone
;rc "!!getlink" enable all, as above.
;rc "!!listqueue" enable all, as above.

also, maybe add an example of config.json for people wanting to change the config,json around without messing everything up, ill be glad to give a rough draft of a guide.
:)

**Comment by miraai** [comment]
We know that already, and it will be done :]

**Comment by Kwoth** [comment]
fixed, thanks
