### ISSUE TITLE
No response from music commands.

### ISSUE THREAD

**Issue by Infectious99** [Kwoth/NadekoBot#433]
Hi, I wanted to play music with Nadeko so I set it up to host myself.
I've got the bot on my server and everything seems to work except for !m commands, which don't seem to be doing anything at all for me. No response from Nadeko in chat or anything in cmd.
I have ffmpeg set up correctly as far as I know (ffmpeg in cmd gives a response).
I've tried restarting Nadeko/my pc but still having the same problem, my first time using anything like this so no idea what I could be doing wrong :(

**Comment by miraai** [comment]
Did you set up all API keys?
Are you using `!mq` command?

**Comment by Infectious99** [comment]
I'm dumb :( I was copying the commands exactly from the wiki, I didn't think to try without a space, was using "!m q" "!m dv" this whole time, just tried "!mq" and "!mdv" and it worked. Thanks

**Comment by miraai** [comment]
No problem. :] Enjoy!

**Comment by Kwoth** [comment]
@Infectious99 keep in mind recommended way is to go to data/config.json and change your music prefix from !m to !!
