### ISSUE TITLE
Music good on desktop, shaky on mobile

### ISSUE THREAD

**Issue by Pikachu24Fan** [Kwoth/NadekoBot#434]
While in a call the bot is heard perfectly from all the desktop users, but most mobile users have to keep leaving and joining the call before they obtain the sound. Was wondering if their was something to help them be able to hear it without having to leave and rejoin several times? Thank you for your time :)

**Comment by Kwoth** [comment]
Nope, this seems to be the discord issue on mobile devices, we're experiencing it too.
