### ISSUE TITLE
Credential input

### ISSUE THREAD

**Issue by DecemberDragon** [Kwoth/NadekoBot#435]
Hello. It seems I type in my credentials every time, but as soon as i start nadeko it says it cant find the credential info and I click on the credentials .jnson file and they are completely wipe clean and i input all over again and the process restarts? Anyone know anything about this?

**Comment by Kwoth** [comment]
You are doing something terribly wrong.

Make sure you've enabled file extensions for known file types. Next to your NadekoBot.exe you must have **credentials.json** file (make sure you spelled it correctly).

**Comment by DecemberDragon** [comment]
So you dont edit credentials_example.json?

**Comment by Kwoth** [comment]
you rename credentials_example.json to credentials.json and edit that.

**Comment by DecemberDragon** [comment]
Woah i feel dumb. Haha thanks i got it :D
