### ISSUE TITLE
LoL support

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#44]
Champion search? - done

Current match preview?

Server status?

**Comment by isackender** [comment]
[Gravebot](https://github.com/Gravebot/Gravebot/blob/master/src/commands/games/leagueoflegends/championgg.js) has some really useful commands. It uses [Champion.gg's API](http://api.champion.gg/).

Accepted positions are **Top**, **Mid**, **ADC**, **Jungle**, and **Support**.
Accepted regions are **br**, **eune**, **euw**, **kr**, **lan**, **las**, **na**, **oce**, **pbe**, **ru**, and **tr**.

**`!lol bans`** - Get the top 10 most common bans.
Example output:
```
1st. Shyvana
2nd. Urgot
3rd. Mordekaiser
4th. Galio
5th. Rumble
6th. Yorick
7th. Aatrox
8th. Nunu
9th. Cassiopeia
10th. Heimerdinger
```
**`!lol best position`** - Get the top 10 best champs for a position.
```
!lol best top

1st. Gangplank with a 50.2% winrate.
2nd. Nasus with a 52.35% winrate.
3rd. Garen with a 51.51% winrate.
4th. Irelia with a 50.22% winrate.
5th. Tryndamere with a 52.51% winrate.
6th. Yasuo with a 52.33% winrate.
7th. Pantheon with a 55.94% winrate.
8th. Wukong with a 51.31% winrate.
9th. Singed with a 50.39% winrate.
10th. Quinn with a 54.11% winrate.
```
**`!lol counters champ-name position`** - Get the top 10 counters for a Champion and Position.
`!lol counters ahri mid`
Output: [Image](https://images-1.discordapp.net/.eJwFwdENhSAMAMBdGICCtYBuQwDRBIXQ-mXe7u_uU-9salenyOAdIF-c-syapc9Yi66911biuFinfkMUiem8yyMMdnXOOAoBt9UjkgtgyRi0C6H3lqzfCCGXI75N9Hiq-v0BBjEitg.9bEBTWqhptncREtQKoZ34zfGW3U.png?width=400&height=179)

**`!lol items champ-name position`** - Get the highest win item sets for a Champion and Position.
`!lol items ahri mid`
Output: [Image](https://images-2.discordapp.net/.eJwFwdsNwyAMAMBdGACbmFezjQWURCIBgfMVdffeveqZTe3qEBlrB8jnSn1mvaRPrkXX3msrPM6lU7-ARTgdV7llgbHeo3cx0scGIucjGIdIJtgYNtwILRrI5ctPEz3uqn5_BTgipQ.qF_kuMIimQlkW0s9R0zouXdm_CY.png?width=400&height=209)

**`!lol skills champ-name position`** - Get the highest win skills for a Champion and Position.
`!lol skills ahri mid`
```
Skill Priority: Q>W>E
Full Order: E,Q,W,Q,Q,R,Q,W,Q,W,R,W,W,E,E,R,E,E
```

**Comment by Kwoth** [comment]
thanks! i will look into it

**Comment by Asat0rr** [comment]
Maybe consider adding the (relatively) new rito defined role names to the list of recognised roles. Fighter, marksman, mage etc? :) 
Although they are more fuzzy for positions...

**Comment by isackender** [comment]
I'm afraid that with the new champ select, those roles have become completely irrelevant.

Moreover, that wouldn't make any sense. For example, `!lol best mage`? Why would you want to know that? You just want to go Mid, and what champions are the best for that position.

**Comment by Asat0rr** [comment]
Why not? What if i feel like playing a mage in the support role? Or a fighter in the jungle? From a player's perspective it seems just as valid an ask for `!lol best assassin` as `!lol best jungle`.

**Comment by isackender** [comment]
I get what you say. I guess it could be useful if you want to get a `tank support` champion, for example. 

Anyway, those roles are not completely clear. Look Blitzcrank, he's tagged as `Fighter` instead of `Support` (yes, you may consider him a fighter, but his main role is support). So if you chose to filter `Support` you will never get Blitzcrank as a result of the query. Those roles are always changing. And Riot can't control that (Tahm Kench top).

It could be useful, but it's a real pain in the ass.

**Comment by Kwoth** [comment]
~lolchamp [champ_name] [(optional)role_name]

and

~lolbans

have been added. I will probably add 1-2 more commands in the coming days, then I'll close this issue and leave the rest to people who want to contribute.

**Comment by Asat0rr** [comment]
@isackender Yeah you have a point. I guess it could be left for a future addition seeing as how roles can be better aggregated with stats from the new champion select by seeing picks + positions played rather than predefined roles.

**Comment by Kwoth** [comment]
we will track this in #208
