### ISSUE TITLE
Bringing Nadeko back online

### ISSUE THREAD

**Issue by ClientSideOnly** [Kwoth/NadekoBot#440]
Hey, Nadeko was "Restarting" for the past few minutes and she hasn't come back online since. I was just curious as to if there was a command I was missing on this page (https://github.com/Kwoth/NadekoBot/blob/master/commandlist.md) to start her back up.
Thanks in advance

**Comment by Kwoth** [comment]
Hello,

Don't worry. Bot is restarting due to bugfixes and setting up for another round of Music feature testing.

Sorry for the inconvenience.

**Comment by ClientSideOnly** [comment]
Oh, I thought it was something I did. Thanks!
