### ISSUE TITLE
Music Track Skip (especially?) on Playlist

### ISSUE THREAD

**Issue by jkesselring** [Kwoth/NadekoBot#441]
I've got a YouTube playlist of about 20 songs (though the size doesn't appear to matter). For the most part the first several songs will play normally and to completion. After this happens the song will stop before it is complete and then start playing the next queued song. Nothing out of the ordinary appears to be going on in the command log.

**Comment by xnaas** [comment]
@Kwoth is currently working on a re-write of the music code to try and get rid of issues like that. It's a known bug and currently being worked on.

**Comment by Kwoth** [comment]
Yes, we aren't tracking music issues as they will become irrelevant soon. 

With your specific issue, sometimes changing discord server location fixes it.
