### ISSUE TITLE
Nadeko's custom reactions on commands.

### ISSUE THREAD

**Issue by JustAnotherPony** [Kwoth/NadekoBot#447]
Please, make Nadeko run commands.
Like: 
**"@Nadeko next track" 
"Okay *switches the music*"**

"@Nadeko next track"  = !!next

It's really easier.

**Comment by miraai** [comment]
No it is not. How is it easier to write `@Nadeko next track` than `!!n` ?

**Comment by Kwoth** [comment]
xD

**Comment by JustAnotherPony** [comment]
This makes it more like a human.
