### ISSUE TITLE
inrole requires MentionEveryone permission

### ISSUE THREAD

**Issue by flurri** [Kwoth/NadekoBot#450]
Is this intentional? The code is there, but there doesn't seem to be any reason for it. Unlike mentionrole, it just lists usernames, and it's useful for users who might not have permission to mention everyone to look up other tags; e.g., finding a group of people who use a certain self-assignable tag.

**Comment by Kwoth** [comment]
It's probably a leftover because i copy pasted it from menrole i guess. Will fix it asap.

**Comment by Kwoth** [comment]
5db12144409b7251c0b271ea990f89b0d90993ad
