### ISSUE TITLE
NadekoBot Music not working

### ISSUE THREAD

**Issue by Darkstars123** [Kwoth/NadekoBot#453]
So, my problem is whenever I do a music command, Nadeko doesn't respond.
I followed all the instructions in the video tutorial and the text tutorial, and Nadeko is setup on my pc with the Google api key and they soundcloud key(and ffmpeg, typing ffmpeg in cmd does not show "unknown command" error, rather a bunch of information), as well as the api's and the google server.
But whenever I type a music command in chat, Nadeko simply doesn't react at all.
The commands i've tried using are: !!qq, !m, !!sqq 
Any suggestions?

**Comment by Darkstars123** [comment]
Yea: http://prnt.sc/bxlqks
By the way, does it matter that im using Youtube Data API v3? That's what installed when I clicked Youtube data api under youtube api's: http://prntscr.com/bxlstv

I just checked the Google api and soundcloud api and their setup correctly.
Plus the cmd window that opens when you open NadekoBot.exe says that soundcloud streaming is enabled and google api key provided, so I can't see the problem.

**Comment by Kwoth** [comment]
you are probably just using wrong commands, I'm assuming you've hosted before the last patch @Darkstars123 , which means your config persisted and your music prefix is still !m, only without a space.

Type `-commands Music` to see a list of music commands. If it indeed was a prefix problem, go into data/config.json and change  Music Prefix  from !m to !!

**Comment by Darkstars123** [comment]
@Kwoth Yep, that worked. Thanks!
By the way is there any way to make it so only owners can use certain commands? Like music commands.

**Comment by Kwoth** [comment]
yes, check out the wiki - permission system.
