### ISSUE TITLE
Release with no NSFW

### ISSUE THREAD

**Issue by 1239145** [Kwoth/NadekoBot#460]
Could someone make a release or some sort of way to remove the NSFW module?

**Comment by Kwoth** [comment]
`;sm disable nsfw`

**Comment by 1239145** [comment]
Umm.. Still not working. :/
![screenshot_1](https://cloud.githubusercontent.com/assets/20377334/17157723/460d841a-535f-11e6-8133-c98348b1698d.png)

**Comment by 1239145** [comment]
I also tried lowercase, if that helps.
