### ISSUE TITLE
Turning off NSFW doesn't work (module not found)

### ISSUE THREAD

**Issue by 1239145** [Kwoth/NadekoBot#461]
I tried using lower and uppercase, giving Nadeko all permissions, and it doesn't work. 
![screenshot_1](https://cloud.githubusercontent.com/assets/20377334/17158168/530782bc-5362-11e6-8b0a-6e4d052507a8.png)

**Comment by Kwoth** [comment]
`;sm nsfw disable` my bad.

**Comment by Kwoth** [comment]
use -h ;sm (-h command name) to get a help for that command

**Comment by 1239145** [comment]
Ooohhh :P Thanks! that worked!
