### ISSUE TITLE
Whitelist only??

### ISSUE THREAD

**Issue by Navyguy330** [Kwoth/NadekoBot#463]
Can I make a white list so that all posts that contain more then specific words allowed is removed or edited to remove anything else?

so If I have a list of 200 words, all posts that dont contain one of them is removed? or if it has one, but has extra crap that crap is removed? or the post is deleted?

like a reverse chat filter? lol would be great

**Comment by Kwoth** [comment]
No, sorry, seems very specific and I don't see it's general use case.
