### ISSUE TITLE
self-assignable roles, not assigning roles.

### ISSUE THREAD

**Issue by Laurond** [Kwoth/NadekoBot#466]
When a user use ".iam _rolename_", Nadeko replies that she can't assign the role, AND that "OK You now have _rolename_ role".
She then removes the message saying that the role has been assigned to the user. 

I've been told there is also a bug where "Nadeko replies that she can not assign the roles, but does anyway.", this is not the case as the role is never assigned.

![nadekobug](https://cloud.githubusercontent.com/assets/20698790/17205679/3e317e74-54ac-11e6-864e-84cdfedc6bf7.png)

Note: I'm using the publicly hosted version that can be invited from Nadeko's github page.

**Comment by miraai** [comment]
First: You didnt read commands.
Second: https://github.com/Kwoth/NadekoBot/blob/master/commandlist.md <------ there
Description for `.iam` : `Adds a role to you that you choose. Role must be on a list of self-assignable roles.`
Therefore, your role must be added to the `.lsar` <--- list [`.lsar` : `Lists all self-assignable roles.`]
To add the role to the list, use `.asar` [ `.asar` : `Adds a role, or list of roles separated by whitespace(use quotations for multiword roles) to the list of self-assignable roles.`]
For example: `.asar MyRole`.

**Comment by Laurond** [comment]
I did read commands. Familiarized myself with them before adding the bot to the server.
The picture above just contains 1 instance of someone trying to add a role that doesn't exist..
I added roles to `.lsar` before the first attempt at `.iam myRole`. 
![nadekobug2](https://cloud.githubusercontent.com/assets/20698790/17210073/d189d662-54c0-11e6-8de9-b210598a49de.png)
No, I am not trying to use `.iam` with the account that owns the server.

**Comment by Kwoth** [comment]
extremely weird, @Laurond if you could drop me your server invite link, i would check it out myself

**Comment by miraai** [comment]
@Laurond And you could have said so ^^ o/

**Comment by Laurond** [comment]
@Kwoth it has 1 use only: https://discord.gg/zWdYk

**Comment by Kwoth** [comment]
2 factor authentication was missing on my account, that is why it couldn't add roles. I have added 2fa and now bot can properly use admin functions on servers requiring it.

**Comment by MasonDro** [comment]
Ive invited Nadeko to my nsfw server and ive already set up roles, I have a few self assignable roles however only Male and female are working. When my members try .iam rolename it comes up with "I am unable to add that role to you. I can't add roles to owners or other roles higher than my role in the role hierarchy." however the bots role is above all the self assignable roles.

**Comment by Macley-Kun** [comment]
Have you tried putting it up all the way? Possible give it all he rights and try again.

Met vriendelijke groet,

**Comment by titomb345** [comment]
"I can't add roles to owners or other roles higher than my role in the role hierarchy." but both of the bots roles are at the top of the role list.

any solutions?

**Comment by titomb345** [comment]
Solution was to kick and re-invite the bot.

¯\_(ツ)_/¯

**Comment by Macley-Kun** [comment]
Good to hear! Can ya close the issue too ^^

Met vriendelijke groet,

**Comment by mitsuwii** [comment]
YAMMERO! i tried .asar (role name) but didnt work how can i suppost to add assignable if the bot doesnt work ....im mad at this.!!!!!!!!111111111
