### ISSUE TITLE
SQLite speed needs to be drastically increased

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#471]
Every DbHandler call will create a a new connection to the database, which increases the duration of each insert by 100%. (around 200q/s vs 100q/s)

Since every insert statement starts a transaction and commit it right after, this will drastically reduce the number of queries per second. If I could manage to make a queue with queries needed for execution every-so-often, the queries can go from 200/s up to 65k/s

https://www.sqlite.org/faq.html#q19

I will probably drop Sqlite-net for something else

**Comment by Kwoth** [comment]
I made slight modifications which are on the branch for this issue, but i'm afraid to merge it into dev since i don't know how well it will work :\

**Comment by Nitix** [comment]
Originnaly I Have made sme modification to SQLite-net before it was changed. I added a extra text like for Insert "ON COLLICT IGNORE", to be sure that if one query fail, others still execute. With this one, Insert are safe, but I think that if one update fails, transaction will be stopped.

**Comment by Kwoth** [comment]
I really feel like i should just leave it as it is, and rewrite it to use SQL server in 1.0, since we're moving to .net core
