### ISSUE TITLE
Radio or long music can fill your disk entirely

### ISSUE THREAD

**Issue by Nitix** [Kwoth/NadekoBot#478]
In dev branch, the way on how is handled buffer can fill up the disk. When buffer is end to client it's not removed from file, so radio that are unlimited will create a really big file, as data are saved in raw byte in the file.

**Comment by Kwoth** [comment]
Didn't think anyone would run into this problem. But yes, if you do listen radio for hours with no stops, temp music file can get extremely large.

Not really sure how should i tackle this

**Comment by Kwoth** [comment]
merged a PR to address this, thanks a lot @Nitix
