### ISSUE TITLE
Music Commands Don't work on Windows Server

### ISSUE THREAD

**Issue by SlenderCraft** [Kwoth/NadekoBot#480]
I set up the bot on my Windows Server and set the path to ffmpeg, etc, however music commands don't work on the server.
Here is a screenshot of the console. You can see that I do have ffmpeg set up correctly however using any music commands, the bot just joins the voice channel, sits there and doesn't play anything.
![server-screenshot](https://cloud.githubusercontent.com/assets/9424012/17272312/49e5645e-5661-11e6-8c01-965f41fd7ed5.png)

It works fine when I host it locally on my computer using the same way I set everything up on the server.

**Comment by Kwoth** [comment]
Try youtube/soundcloud links. Nadeko herself is hosted on windows server, and we have at least 10 more people hosting her on windows server too. Your config looks fine, but make sure you're on latest release and you are queuing links which are not blocked in the country server is hosted in.

**Comment by SlenderCraft** [comment]
Oops, it looks like it was simply that my server was blocking the link, just switched my server recently so didn't even think about that being the issue at first, everything is sorted out now.
Nice bot though, it's definitely my favorite. :)
