### ISSUE TITLE
Adding roles with Nadeko WORKS but the permissions error still shows when two roles are given to NadekoBot

### ISSUE THREAD

**Issue by Drakonas** [Kwoth/NadekoBot#481]
I think this may be a bug with the code, because I just updated to the latest code and I'm still having this issue. Nadeko has the highest hierarchy of role for the server besides owners, and all things are checked in the role. When I attempt to add a role below that of Nadeko's role, it DOES add it, but still shows an error saying "Could not add role. insufficient permissions."

**Comment by Drakonas** [comment]
Alright I think I narrowed down what causes the bug. I kept "Nadeko" as NadekoBot's role, but to clean up the user list I had made a "Bot" role, and added Nadeko to it so it gets displayed in a separate list. Both roles were of highest hierarchy, but that seems to cause Nadeko to flip out. Might want to take a look at it.

**Comment by Kwoth** [comment]
Make sure you're on latest prerelease. I personally made sure that doesn't happen anymore on the servers people complained that is happening on.

**Comment by Drakonas** [comment]
You mean v0.99.9c isn't the latest, so I should build from source?

**Comment by Kwoth** [comment]
Hm maybe the fix isn't in any release yet, you could try building from source, or waiting for next minor release.

**Comment by xnaas** [comment]
In case you didn't know, @Drakonas, [0.99.9x](https://github.com/Kwoth/NadekoBot/releases/tag/v0.99.9x) is out now.

**Comment by Kwoth** [comment]
I'll assume this is fixed. If not, it will be fixed in 1.0 anyway.
