### ISSUE TITLE
bot wont work.

### ISSUE THREAD

**Issue by tykodey** [Kwoth/NadekoBot#487]
after setting the rate nadekoflowers generate at. 1 min cooldown. i played around for a bit, and got a PM from the bot saying the owner took 1 flower. i was like K idk why that is but fine, and now the bots commands all dont work

**Comment by Kwoth** [comment]
Bot is updating atm.

**Comment by tykodey** [comment]
oh ok, thanks

**Comment by tykodey** [comment]
apparently all bots are updating, marshmallow and nadeko are offline too

**Comment by tykodey** [comment]
when does the update finish?

**Comment by miraai** [comment]
Currently Discord is having issues with connection, so bots are not able to connect to Discord. Be patient and wait for the issue to be fixed.
