### ISSUE TITLE
Prebuffering timed out or canceled, cannot get any data from stream.

### ISSUE THREAD

**Issue by vSwifty** [Kwoth/NadekoBot#494]
Trying to load up https://stream.r-a-d.io/main.mp3 for my group's radio bot but this is the only station that won't work with the bot every other radio link is fine.

Is it on the hosts end or did I not set something up right?

**Comment by Nitix** [comment]
Are you using the dev version?

**Comment by Nitix** [comment]
I just tested your link using the dev version, music loaded correctly.

**Comment by vSwifty** [comment]
Huh interesting I'm using the version the NadekoUpdater gave me which is this one 
https://github.com/Kwoth/NadekoBot/releases/tag/v0.99.9c

**Comment by Nitix** [comment]
Music module got reworked a lot in dev version.
[Diff between v0.99.9c and dev](https://github.com/Kwoth/NadekoBot/compare/8fad100...dev)

**Comment by vSwifty** [comment]
Oh yeah that's quite a bit of changes, I'll make the switch over and close out this ticket. 

Thanks for the quick and speedy responses!

**Comment by Nitix** [comment]
Np, but if you still get issue when next release is out, open a new issue.
