### ISSUE TITLE
Nadeko dev doesn't run anymore with mono

### ISSUE THREAD

**Issue by Nitix** [Kwoth/NadekoBot#497]
With the change SQLite dependencies, It's now rely on two dll that need the kernel32.dll

**Comment by Kwoth** [comment]
I actually completely forgot about this, even though i saw it myself when testing something. Thanks a lot.

**Comment by Kwoth** [comment]
pushed the fix 596472519076757939a3eec92e6e635295025b19 , reopen if issue persists
