### ISSUE TITLE
Music early end

### ISSUE THREAD

**Issue by Accelerando** [Kwoth/NadekoBot#50]
It seems as if having multiple songs queued makes songs end too early and it goes to the next queued song.

Leaving this here just in case, NadekoBot was added to the discord server via invite on this site https://www.carbonitex.net/Discord/bots

**Comment by Kwoth** [comment]
yes this issue is known, i will investigate it further, thanks for the report

**Comment by Kwoth** [comment]
fixed it with new music code, will be available in 0.9 release
