### ISSUE TITLE
Says wrong token, but sure it isn't

### ISSUE THREAD

**Issue by justinkruit** [Kwoth/NadekoBot#503]
Hi,

I'm trying to set the bot up, and whenever I start it, I read in the logs that the token isn't correct. But I'm pretty sure it is the correct token, with the correct bot and client ID's. Are there some problems, or am I still doing something wrong? I'm using the latest Pre-Release.

**Comment by Kwoth** [comment]
It just prints that when it can't connect.

Linux/Windows?

Show full console error. Probably certs issue on linux.

**Comment by justinkruit** [comment]
Linux, and I've run the certs commands multiple times to be sure.

> Script started on Tue 02 Aug 2016 10:11:45 AM EDT
root@ubuntu-1gb-ams2-01:~# cd NadekoBot[K[K[Kbot
bash: cd: Nadekobot: No such file or directory
root@ubuntu-1gb-ams2-01:~# cd Nadekobot[K[K[KBpt[K[Kot
root@ubuntu-1gb-ams2-01:~/NadekoBot# mono Nadekpb[K[Kobot[K[K[KBo.[Kt.exe
ÿþG o o g l e   A P I   k e y   p r o v i d e d . 
 T r e l l o   a p p   k e y   p r o v i d e d . 
 F o r w a r d i n g   p r i v a t e   m e s s a g e s   t o   o w n e r . 
 S o u n d C l o u d   s t r e a m i n g   e n a b l e d . 
 o s u !   A P I   k e y   p r o v i d e d . 
 T o k e n   i s   w r o n g .   D o n ' t   s e t   a   t o k e n   i f   y o u   d o n ' t   h a v e   a n   o f f i c i a l   B O T   a c c o u n t . 
 S y s t e m . N e t . W e b E x c e p t i o n :   E r r o r   g e t t i n g   r e s p o n s e   s t r e a m   ( W r i t e :   T h e   a u t h e n t i c a t i o n   o r   d e c r y p t i o n   h a s   f a i l e d . ) :   S e n d F a i l u r e   - - - >   S y s t e m . I O . I O E x c e p t i o n :   T h e   a u t h e n t i c a t i o n   o r   d e c r y p t i o n   h a s   f a i l e d .   - - - >   M o n o . S e c u r i t y . P r o t o c o l . T l s . T l s E x c e p t i o n :   I n v a l i d   c e r t i f i c a t e   r e c e i v e d   f r o m   s e r v e r .   E r r o r   c o d e :   0 x f f f f f f f f 8 0 0 b 0 1 0 a 
     a t   M o n o . S e c u r i t y . P r o t o c o l . T l s . H a n d s h a k e . C l i e n t . T l s S e r v e r C e r t i f i c a t e . R e m o t e V a l i d a t i o n   ( M o n o . S e c u r i t y . P r o t o c o l . T l s . C l i e n t C o n t e x t   c o n t e x t ,   A l e r t D e s c r i p t i o n   d e s c r i p t i o n )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   M o n o . S e c u r i t y . P r o t o c o l . T l s . H a n d s h a k e . C l i e n t . T l s S e r v e r C e r t i f i c a t e . v a l i d a t e C e r t i f i c a t e s   ( M o n o . S e c u r i t y . X 5 0 9 . X 5 0 9 C e r t i f i c a t e C o l l e c t i o n   c e r t i f i c a t e s )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   M o n o . S e c u r i t y . P r o t o c o l . T l s . H a n d s h a k e . C l i e n t . T l s S e r v e r C e r t i f i c a t e . P r o c e s s A s T l s 1   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   M o n o . S e c u r i t y . P r o t o c o l . T l s . H a n d s h a k e . H a n d s h a k e M e s s a g e . P r o c e s s   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   ( w r a p p e r   r e m o t i n g - i n v o k e - w i t h - c h e c k )   M o n o . S e c u r i t y . P r o t o c o l . T l s . H a n d s h a k e . H a n d s h a k e M e s s a g e : P r o c e s s   ( ) 
     a t   M o n o . S e c u r i t y . P r o t o c o l . T l s . C l i e n t R e c o r d P r o t o c o l . P r o c e s s H a n d s h a k e M e s s a g e   ( M o n o . S e c u r i t y . P r o t o c o l . T l s . T l s S t r e a m   h a n d M s g )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   M o n o . S e c u r i t y . P r o t o c o l . T l s . R e c o r d P r o t o c o l . I n t e r n a l R e c e i v e R e c o r d C a l l b a c k   ( I A s y n c R e s u l t   a s y n c R e s u l t )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     - - -   E n d   o f   i n n e r   e x c e p t i o n   s t a c k   t r a c e   - - - 
     a t   M o n o . S e c u r i t y . P r o t o c o l . T l s . S s l S t r e a m B a s e . A s y n c H a n d s h a k e C a l l b a c k   ( I A s y n c R e s u l t   a s y n c R e s u l t )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     - - -   E n d   o f   i n n e r   e x c e p t i o n   s t a c k   t r a c e   - - - 
     a t   S y s t e m . N e t . H t t p W e b R e q u e s t . E n d G e t R e s p o n s e   ( I A s y n c R e s u l t   a s y n c R e s u l t )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   R e s t S h a r p . H t t p . G e t R a w R e s p o n s e A s y n c   ( I A s y n c R e s u l t   r e s u l t ,   S y s t e m . A c t i o n ` 1   c a l l b a c k )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
 - - -   E n d   o f   s t a c k   t r a c e   f r o m   p r e v i o u s   l o c a t i o n   w h e r e   e x c e p t i o n   w a s   t h r o w n   - - - 
     a t   S y s t e m . R u n t i m e . E x c e p t i o n S e r v i c e s . E x c e p t i o n D i s p a t c h I n f o . T h r o w   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   S y s t e m . R u n t i m e . C o m p i l e r S e r v i c e s . C o n f i g u r e d T a s k A w a i t a b l e ` 1 + C o n f i g u r e d T a s k A w a i t e r [ S y s t e m . S t r i n g ] . G e t R e s u l t   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   D i s c o r d . N e t . R e s t . R e s t C l i e n t + < S e n d > d _ _ 2 5 . M o v e N e x t   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
 - - -   E n d   o f   s t a c k   t r a c e   f r o m   p r e v i o u s   l o c a t i o n   w h e r e   e x c e p t i o n   w a s   t h r o w n   - - - 
     a t   S y s t e m . R u n t i m e . E x c e p t i o n S e r v i c e s . E x c e p t i o n D i s p a t c h I n f o . T h r o w   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   S y s t e m . R u n t i m e . C o m p i l e r S e r v i c e s . C o n f i g u r e d T a s k A w a i t a b l e ` 1 + C o n f i g u r e d T a s k A w a i t e r [ D i s c o r d . N e t . R e s t . R e s t C l i e n t + R e s t R e s u l t s ] . G e t R e s u l t   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   D i s c o r d . N e t . R e s t . R e s t C l i e n t + < S e n d > d _ _ 2 1 ` 1 [ D i s c o r d . A P I . C l i e n t . R e s t . G e t V o i c e R e g i o n s R e s p o n s e [ ] ] . M o v e N e x t   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
 - - -   E n d   o f   s t a c k   t r a c e   f r o m   p r e v i o u s   l o c a t i o n   w h e r e   e x c e p t i o n   w a s   t h r o w n   - - - 
     a t   S y s t e m . R u n t i m e . E x c e p t i o n S e r v i c e s . E x c e p t i o n D i s p a t c h I n f o . T h r o w   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   S y s t e m . R u n t i m e . C o m p i l e r S e r v i c e s . C o n f i g u r e d T a s k A w a i t a b l e ` 1 + C o n f i g u r e d T a s k A w a i t e r [ D i s c o r d . A P I . C l i e n t . R e s t . G e t V o i c e R e g i o n s R e s p o n s e [ ] ] . G e t R e s u l t   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   D i s c o r d . D i s c o r d C l i e n t + < L o g i n > d _ _ 7 9 . M o v e N e x t   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
 - - -   E n d   o f   s t a c k   t r a c e   f r o m   p r e v i o u s   l o c a t i o n   w h e r e   e x c e p t i o n   w a s   t h r o w n   - - - 
     a t   S y s t e m . R u n t i m e . E x c e p t i o n S e r v i c e s . E x c e p t i o n D i s p a t c h I n f o . T h r o w   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   S y s t e m . R u n t i m e . C o m p i l e r S e r v i c e s . C o n f i g u r e d T a s k A w a i t a b l e + C o n f i g u r e d T a s k A w a i t e r . G e t R e s u l t   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   D i s c o r d . D i s c o r d C l i e n t + < B e g i n C o n n e c t > d _ _ 7 8 . M o v e N e x t   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
 - - -   E n d   o f   s t a c k   t r a c e   f r o m   p r e v i o u s   l o c a t i o n   w h e r e   e x c e p t i o n   w a s   t h r o w n   - - - 
     a t   S y s t e m . R u n t i m e . E x c e p t i o n S e r v i c e s . E x c e p t i o n D i s p a t c h I n f o . T h r o w   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   D i s c o r d . D i s c o r d C l i e n t + < B e g i n C o n n e c t > d _ _ 7 8 . M o v e N e x t   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
 - - -   E n d   o f   s t a c k   t r a c e   f r o m   p r e v i o u s   l o c a t i o n   w h e r e   e x c e p t i o n   w a s   t h r o w n   - - - 
     a t   S y s t e m . R u n t i m e . E x c e p t i o n S e r v i c e s . E x c e p t i o n D i s p a t c h I n f o . T h r o w   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   S y s t e m . R u n t i m e . C o m p i l e r S e r v i c e s . C o n f i g u r e d T a s k A w a i t a b l e + C o n f i g u r e d T a s k A w a i t e r . G e t R e s u l t   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   D i s c o r d . D i s c o r d C l i e n t + < C o n n e c t > d _ _ 7 7 . M o v e N e x t   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
 - - -   E n d   o f   s t a c k   t r a c e   f r o m   p r e v i o u s   l o c a t i o n   w h e r e   e x c e p t i o n   w a s   t h r o w n   - - - 
     a t   S y s t e m . R u n t i m e . E x c e p t i o n S e r v i c e s . E x c e p t i o n D i s p a t c h I n f o . T h r o w   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   S y s t e m . R u n t i m e . C o m p i l e r S e r v i c e s . C o n f i g u r e d T a s k A w a i t a b l e + C o n f i g u r e d T a s k A w a i t e r . G e t R e s u l t   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
     a t   N a d e k o B o t . N a d e k o B o t + < > c + < < M a i n > b _ _ 3 2 _ 3 > d . M o v e N e x t   ( )   [ 0 x 0 0 0 0 0 ]   i n   < f i l e n a m e   u n k n o w n > : 0   
 [6n

And yes, I know the way it looks is terrible, but otherwise it wasn't even readable. (For if it wasn't obvious yet, I'm new with this kind of stuff :P)

**Comment by justinkruit** [comment]
Just remembered. While installing the certs, it said some where invalid, but I still installed them. But that happened while I used the exact same commands from the guide.

**Comment by xnaas** [comment]
Personally, I'd scrap and try a fresh install. But we'll see if @Kwoth has anything more helpful. :P

**Comment by justinkruit** [comment]
@xnaas You mean a fresh install of the server, or Nadeko? Want I've already tried a fresh intall of Nadeko.

**Comment by Nitix** [comment]
Your error is an invalid certificate from discord server, then make sure that you have  **really** accepted certificates. I was running dev version on my server using Ubuntu 16.04 without problems. 

And please do something for your console, it `p u t s   s p a c e   b e t w e e n   e a c h   l e t t e r`, It was really difficult to read.

**Comment by xnaas** [comment]
@justinkruit yeah, I meant Nadeko. Sorry for not clarifying.

**Comment by justinkruit** [comment]
@Nitix Originally, the log was even more of a mess. It gets all outputted in a separate file, otherwise I'm not able to read it all. I'm sure I was pressing `y` to accept them every time. But I will try again.

**Comment by Kwoth** [comment]
@justinkruit in the linux guide, step 5, do those steps for "if you get random strings and you can't login"
also second one should be without double --, its a typo.

13) 1certmgr -ssl https://discordapp.com1

14) 1certmgr -ssl https://gateway.discord.gg1 (not --ssl)

**Comment by Kwoth** [comment]
@justinkruit was this solved?

**Comment by Ahtram** [comment]
Hi, 
I have the same issue. And I'm sure the certmgr steps was right.

> No google api key found. You will not be able to use music and links won't be shortened.
Trello app key provided.
Forwarding private messages to owner.
No soundcloud Client ID found. Soundcloud streaming is disabled.
No osu! api key found. Song & top score lookups will not work. User lookups still available.
Token is wrong. Don't set a token if you don't have an official BOT account.
System.Net.WebException: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.RemoteValidation (Mono.Security.Protocol.Tls.ClientContext context, AlertDescription description) [0x00000] in <filename unknown>:0
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.validateCertificates (Mono.Security.X509.X509CertificateCollection certificates) [0x00000] in <filename unknown>:0
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.ProcessAsTls1 () [0x00000] in <filename unknown>:0
  at Mono.Security.Protocol.Tls.Handshake.HandshakeMessage.Process () [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) Mono.Security.Protocol.Tls.Handshake.HandshakeMessage:Process ()
  at Mono.Security.Protocol.Tls.ClientRecordProtocol.ProcessHandshakeMessage (Mono.Security.Protocol.Tls.TlsStream handMsg) [0x00000] in <filename unknown>:0
  at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
  at RestSharp.Http.GetRawResponseAsync (IAsyncResult result, System.Action`1 callback) [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[System.String].GetResult () [0x00000] in <filename unknown>:0
  at Discord.Net.Rest.RestClient+<Send>d__25.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[Discord.Net.Rest.RestClient+RestResults].GetResult () [0x00000] in <filename unknown>:0
  at Discord.Net.Rest.RestClient+<Send>d__21`1[Discord.API.Client.Rest.GetVoiceRegionsResponse[]].MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[Discord.API.Client.Rest.GetVoiceRegionsResponse[]].GetResult () [0x00000] in <filename unknown>:0
  at Discord.DiscordClient+<Login>d__79.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <filename unknown>:0
  at Discord.DiscordClient+<BeginConnect>d__78.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at Discord.DiscordClient+<BeginConnect>d__78.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <filename unknown>:0
  at Discord.DiscordClient+<Connect>d__77.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <filename unknown>:0
  at NadekoBot.NadekoBot+<>c+<<Main>b__32_3>d.MoveNext () [0x00000] in <filename unknown>:0

**Comment by Nitix** [comment]
Your token is rejected by discord API, you are using a wrong token.

**Comment by appelemac** [comment]
Make sure you use certngr on the account of the user that opens the bot, not just root

**Comment by Ahtram** [comment]
Still no luck :(
This is how my certmgr steps look like
![2016-08-04 11_08_32-cmder](https://cloud.githubusercontent.com/assets/1751201/17389137/01370a2e-5a34-11e6-9cee-7a435f7419f0.png)

**Comment by miraai** [comment]
@Ahtram Which Linux?

Anyway, first update mono and check for any missing dependencies.
Then run `mozroots --import --sync`
Make sure you have `ca-certificates-mono` installed, if not, do so.

And then basically you sould do this:
```
sudo certmgr -ssl -m https://discordapp.com
sudo certmgr -ssl -m https://gateway.discord.gg
mozroots --import --sync
```

**Comment by Nitix** [comment]
@Athram Your issue is not the certificate, in fact you can can communicate
without problem with Discord server. But Your token is invalid, please
check your token [here](https://discordapp.com/developers/applications/me).

2016-08-04 11:42 GMT+02:00 miraai <notifications@github.com>:

**Comment by Ahtram** [comment]
@miraai I'm using Ubuntu 16.04 LTS
yes I've run the two certmgr so many time. (see the screenshot) However there's some problem with the mozroots sync command.
![2016-08-04 18_56_12-cmder](https://cloud.githubusercontent.com/assets/1751201/17399574/6c3e5e58-5a75-11e6-8f04-7fe5512a6fbe.png)
@Nitix I've check my bot token many times to make sure they are correct. Still no clue where's the problem.
![2016-08-04 18_59_57-c__users_neo_desktop_credentials json - notepad](https://cloud.githubusercontent.com/assets/1751201/17399629/bfd844de-5a75-11e6-8e8b-9a0b2fe89391.png)
![2016-08-04 19_00_08-discord - developer documentation](https://cloud.githubusercontent.com/assets/1751201/17399630/c17874ee-5a75-11e6-95b2-bec2f1cfcfb4.png)

**Comment by Ahtram** [comment]
Also I've notice the bot token changed when everytime I do a page refresh and reveal it.
Is this a common behavior?

**Comment by Nitix** [comment]
Well, I don't know but now You have to invalidate your token, since you
posted it. I know that sometimes it gives me a wrong token when I create a
bot, but if I refreshh the page and copy the token then the token is
correct.

**Comment by miraai** [comment]
@Ahtram It is, every time you refresh a page, it will show you a different token. 
Try a different token, save credentials and try to run again.
Also put your OwnerID.

**Comment by Ahtram** [comment]
@miraai Sorry for stupid question. But where can I get my ownerID? The doc didn't mention it and said it was alright without an ownerID.

**Comment by miraai** [comment]
@Ahtram it kinda is in the guide: http://prntscr.com/c1ijdi
If your bot is not in your server, you can get it from public Nadeko server.

**Comment by Kwoth** [comment]
@Ahtram can you use `sudo` with certmgr commands and then try again?

**Comment by Ahtram** [comment]
Yes, I tried but the result is the same.

**Comment by Kwoth** [comment]
Maybe just try docker? :D

It uses those commands automatically and they work.

http://nadekobot.readthedocs.io/en/latest/guides/Docker%20Guide/

If you don't want to host on digitalocean, just ignore first steps and install docker yourself on your machine. I don't know what else to suggest

**Comment by Ahtram** [comment]
The problem solved after I do 

> apt-get install ca-certificates-mono

again.
I'm still not sure why. Thank you all anyway.

**Comment by paulstelian97** [comment]
I'm having similar problems myself. I'm just copy-pasting the token directly from the page, right into `Discord.js` `client.login(TOKEN)` function call and now it only gives unhandled promise rejections: "Incorrect login details were provided."

What should I do now? I'm not planning on building the bot again from scratch lol (I've already added it to the servers and the server isn't my own)
