### ISSUE TITLE
Channel / Personal Reminders

### ISSUE THREAD

**Issue by WasabiCannon** [Kwoth/NadekoBot#51]
Something similar to Reddit's RemindMeBot.
https://www.reddit.com/r/RemindMeBot/comments/24duzp/remindmebot_info/

Like ~Remind Channel/Me [Date] [Time] [Timezone] [Discription]
If channel is used then it would blast the remind message to the channel and if me is used it would PM you.

Where the time tracking would be based on the host's machine's time?

**Comment by Kwoth** [comment]
Really like the idea, i will implement it at some point.
