### ISSUE TITLE
Trello module not exist

### ISSUE THREAD

**Issue by Ahtram** [Kwoth/NadekoBot#510]
Is the trello module currently working? I really like that feature.

![2016-08-03 14_03_51-nadeko](https://cloud.githubusercontent.com/assets/1751201/17355435/223db184-5983-11e6-8fa6-e13839fc34da.png)

**Comment by miraai** [comment]
Its working. Make sure your board is public. :]

**Comment by Kwoth** [comment]
@Ahtram trello module is not available on the shared bot, you have to host Nadeko yourself in order to have access to it.

**Comment by Ahtram** [comment]
Cool thanks.
