### ISSUE TITLE
[Suggestion] User limitations

### ISSUE THREAD

**Issue by justinkruit** [Kwoth/NadekoBot#511]
Is there a way to limit users from using commands and/or modules? For example, I'm listening to some music with some friends, and they just love to put the volume to 100% while it was at 25%. So can you disable them using the music module in any way?

**Comment by blitz4694** [comment]
use permissions, there are examples in the command list https://github.com/Kwoth/NadekoBot/blob/master/commandlist.md

**Comment by justinkruit** [comment]
@blitz4694 Of course. Didn't read it all properly. So many commands :P 
After some good reading (lot of commands that look the same, but aren't) I got it working.
