### ISSUE TITLE
How do I fix this? It says there's a Debug issue.

### ISSUE THREAD

**Issue by juicysun23** [Kwoth/NadekoBot#53]
I was working on the source code. I did a rebuild and no error came up, but when I went to open the application. I got this http://puu.sh/nii4j/6d5221d376.png Is there anyway to fix this?

**Comment by blitz4694** [comment]
your missing dlls

**Comment by juicysun23** [comment]
It should be noted that the biggest change that I did to the Source Code was add in another command. I copied and pasted the insult command and replaced every word of insult with kill.

**Comment by juicysun23** [comment]
How do I get the missing dlls back?

**Comment by Kwoth** [comment]
Make sure nito dlls are in the bin/debug, if they are not, redownload them from the repo. If that is not the issue, then add those dlls as a reference (like you added discord dlls)

Also, it would be best if you came to our server to ask questions.

**Comment by Kwoth** [comment]
Solved in discord chat. Was missing DLLs from the repo.
