### ISSUE TITLE
no permission on some commands 

### ISSUE THREAD

**Issue by vanucci** [Kwoth/NadekoBot#548]
I'm trying to do some owner commands, mainyl ;cm nsfw enable #spam

But when i do this, it says im not the owner and sends a pm to another user id i dont know. 

In the credentials, only my id is in the owner id section and its accurate. I weas alble to change the bots avatar no problem. Just this command isnt working

**Comment by miraai** [comment]
Just type the name of the channel, like `;cm nsfw enable spam`.

**Comment by vanucci** [comment]
You don't have the necessary role (Nadeko) to change permissions.

in terminal says sending message to an id i dont know

**Comment by vanucci** [comment]
[ "ClientId": "183909395673907200",
  "BotId":183911371686150144,
  "OwnerIds": [124639104359989248],
]

but says sending message to 188637782493757440

**Comment by miraai** [comment]
No, you have two `]]`. Should be `[386363748],`. 
For Nadeko role, create a role and name it Nadeko. Give the role all permissions, then give the role to yourself and the bot.

**Comment by Nitix** [comment]
the `]]` is right, I'm supposing that have you additional entry after OwnerIds, or this json file is incorrect  `,` followed by `]`. `]]`close the first `[` before `"ClientId"`

**Comment by miraai** [comment]
[Image](http://prntscr.com/c2smxb)
It is not.
File begins with `{ }`
