### ISSUE TITLE
[Feature Request] Google Calendar Integration

### ISSUE THREAD

**Issue by Sairys** [Kwoth/NadekoBot#553]
Hey, just wondering if it might be possible for Nadeko to link into a google calendar. The main features I'd be hoping for are just checking for events in the next x days and seeing if anything has been cancelled. 

Handy for things like organising raids, games, or physical events with Nadeko letting people know what's up.

**Comment by Kwoth** [comment]
Please post command examples and how would it work, I never heard of google calendar.

I would also prefer if you posted suggestions in  #suggestions channel on #NadekoLog server and close this.

**Comment by Kwoth** [comment]
Not worth the effort i believe
