### ISSUE TITLE
Nakedo Says Music Module dosent exist 

### ISSUE THREAD

**Issue by Zileen** [Kwoth/NadekoBot#558]
everytime anyone on my server attempts to use the command "!!" nothing happens at all. I tried a few commands and anytime i said "Music" as the module she said it didnt exist. I also used .modules and it only listed out 
List of modules: 
• Help
• Administration
• Utility
• Permissions
• Conversations
• Gambling
• Games
• Searches
• NSFW
• ClashOfClans
• Pokegame
• Translator
• Customreactions
Type "-commands module_name" to get a list of commands in that module.

**Comment by miraai** [comment]
Public Nadeko does not play music.
For music module you have to host the bot yourself.
http://nadekobot.readthedocs.io/en/latest/Readme/
