### ISSUE TITLE
Music module ain't working

### ISSUE THREAD

**Issue by koshypopo** [Kwoth/NadekoBot#575]
So yeah, I've installed the bot yesterday for maily music, I've followed the guide trough the whole thing and finshed it. Now that my bod is in my server, when I ask him to play something, he only tell me type -h for help. Then I did it, and now I've tried a couple of thing and figured out that the music module isn't even in the module list, I went on the discord and they told me that it should be there. So idk what the issue is, but if anyone have the same problem and found out the solution, just tell me plze.

**Comment by Kwoth** [comment]
You've setup something badly. Just come to discord and ask for help and be patient, someone will help you.
