### ISSUE TITLE
Disabling exclusively Anime/Manga commands

### ISSUE THREAD

**Issue by Xiocious** [Kwoth/NadekoBot#583]
In our Discord server, I'd like to disable users from using anime/manga commands as that allows for the searching of NSFW content. Is there a way to disable those and only those?

**Comment by miraai** [comment]
Use `;sc "command_name" disable` to disable those commands in the server, or `;cc "command_name" disable channelName` to disable them in a specific channel.

**Comment by Xiocious** [comment]
Oh thank you very much
