### ISSUE TITLE
Repeat command broke

### ISSUE THREAD

**Issue by Sonic1901** [Kwoth/NadekoBot#585]
So I had put in the command .repeat 30 "Your a loser, just remember that" then since it was spamming it for every 30 min one of the admins kicked the bot.
Now I added it a second time but it keeps on repeating the message even though when i do .repeatinvoke it says it has nothing to repeat.
![repeat](https://cloud.githubusercontent.com/assets/21149337/17834701/4719e30c-671a-11e6-8c12-7013c1caca97.PNG)

**Comment by Kwoth** [comment]
Super weird, Try adding a new repeat message, then disable it?

**Comment by Sonic1901** [comment]
what are the commands to do that

**Comment by Kwoth** [comment]
`.repeat`
`.repeat new messsage`
`.repeat`

**Comment by Sonic1901** [comment]
ok i disabled it and that should help us out alot cause no one wants to be spammed. If it continues to repeat even though it is disabled i will contact you.
