### ISSUE TITLE
[Feature Request] Together Tube 

### ISSUE THREAD

**Issue by TheMagicMcRib** [Kwoth/NadekoBot#586]
I think it would be cool to have a command that created an open togethertube server for you and others on the discord to join.

**Comment by Kwoth** [comment]
We just need to send a get request here https://togethertube.com/room/create and use regex to get the id from data-ng-init= i believe.

Should be super simple. maybe @DragonOverlord wants to do it and PR it into 1.0

**Comment by Malax** [comment]
Hey, I am the guy who built and runs TogetherTube. :) It should be even easier, just make a GET request to said URL and just read the Location header that comes back, it contains the URL to the room. :)

**Comment by Kwoth** [comment]
Thanks a lot!

**Comment by Kwoth** [comment]
Woops, at one point i removed togethertube by accident. I just noticed, will get readded soon

**Comment by Kwoth** [comment]
![image](https://cloud.githubusercontent.com/assets/2537696/21465741/b764bc02-c9af-11e6-8c56-e0428d498e60.png)
