### ISSUE TITLE
Music is borked

### ISSUE THREAD

**Issue by Wzill** [Kwoth/NadekoBot#589]
Updated to the newest version, music commands worked for a day and then were broken the next time I started the bot up.

**Comment by miraai** [comment]
Be more specific please.

**Comment by Kwoth** [comment]
type `-commands Music` , musix prefix changed, and it is advised that you go to data/config.json and change the music prefix from !m to !! in order to match the official commandlist

**Comment by Wzill** [comment]
Fixed it. Thanks a bunch 

    On Monday, August 22, 2016 4:40 AM, Master Kwoth <notifications@github.com> wrote:
 

 type -commands Music , musix prefix changed, and it is advised that you go to data/config.json and change the music prefix from !m to !! in order to match the official commandlist—
