### ISSUE TITLE
💢 The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by evozims** [Kwoth/NadekoBot#59]
Whenever anyone in my server types the command: ~ir (insert anything)
We get this message: 💢 The remote server returned an error: (403) Forbidden.
We're not sure why this started happening. The same goes for DjBot. It used to work perfectly just moments ago. What's wrong? It's our favorite feature of nadeko bot!

**Comment by Kwoth** [comment]
As some of the users reported, it seems google custom search has a daily quota, which, if true, terribly sux. I will investigate this when I have more time. Thanks for the report

Working on a new release and server hosting issues atm.

**Comment by LawlyPopz** [comment]
the limit is 100 per day but if you could have multiple google api keys you could work around this by having multi api keys... also if you have more then 300,000 music requests per day on a key you will get this too

**Comment by Kwoth** [comment]
Yeah there is nothing we can do atm. I don't want to use imgur api. When we find something better, ill replace google images with it.
