### ISSUE TITLE
Custom commands question!

### ISSUE THREAD

**Issue by WaifuBand** [Kwoth/NadekoBot#595]
Hello, I want to know if I can make my bot say something just when a certain member makes a quote (or a role). Like, maybe someone (no role at all, random guy) says "Hello!" then the bot would say "Hello!". But if I do, or an admin does, the bot will say "Hello, Admin!". I saw it in a Discord server, but I really don't know how to make it happen! Thanks!

**Comment by xnaas** [comment]
Coming in 1.0. Soon™. 👍
