### ISSUE TITLE
[Feature Request] Cage Virus

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [Kwoth/NadekoBot#596]
Nadekobot has been slowly replacing every bot we use on our server, except one.
Miki.
For Nicholas Cage Reasons
You see, Miki has a >cage command to pull an image from PlaceCage, aka this site http://www.placecage.com/
So.... Can we have a Cage command?

**Comment by Kwoth** [comment]
Can you explain how exactly it would work?

**Comment by Nitix** [comment]
Can you give the exact command you type, placecage is not a place to get random image of Cage. It's normally a placeholder for image while waiting to get the final one.

**Comment by UnstableCodeScarlet** [comment]
I imagine the way Miki's >Cage command works is by randomizing the url to below a certain value, say 500, then linking it.
That's the way I'd handle it anyways.

**Comment by Kwoth** [comment]
Added place command in 1.0, you can use these tags with it

Cage, //http://www.placecage.com
Steven, //http://www.stevensegallery.com
Beard, //http://placebeard.it
Fill, //http://www.fillmurray.com
Bear, //https://www.placebear.com
Kitten, //http://placekitten.com
Bacon, //http://baconmockup.com
Xoart, //http://xoart.link

for example `~place Cage` or `~place steven 500 400` (for size)
use `~placelist` to get a list of available tags
