### ISSUE TITLE
[Feature Request] Wikia Search

### ISSUE THREAD

**Issue by temperae** [Kwoth/NadekoBot#598]
Hello! I'd like to request something similar to #263 but for searching a specific Wikia instead.

Sample usage:
`~wikia wikia-target some-query`

The above would search for "some-query" on `http://wikia-target.wikia.com`, and return the first result.

I think one possible way of doing this would be using regex or substitution and having the bot spit out:
`http://wikia-target.wikia.com/wiki/Special:Search?search=some-query`

Thank you!

**Comment by fkndean** [comment]
#745 
Added a wikia command like
`~wikia target query`
Hopefully Kwoth approves :3

**Comment by Kwoth** [comment]
Yea this has been implemented by @fkndean - thx
