### ISSUE TITLE
Image/Text "Bot" with Modifiers

### ISSUE THREAD

**Issue by Chiharuuu** [Kwoth/NadekoBot#60]
Similar to /r/kpop's Tzuyu Bot, as found here https://github.com/berkuhlee/Tzuyu-bot

Adding would consist of something similar to "!add %commandname% %url%" (url consisting of text, image URL, etc), and actual use of saved command similar to "!_commandname_".

As discussed on Nadeko Discord server.

**Comment by Kwoth** [comment]
I like this and i have an idea of how it will work, most likely getting implemented today.

**Comment by Kwoth** [comment]
its kinda weird, but at least for now you have to add spaces, i want to make use of permission system and command builder, they are too good.

I *might* move it in the future to the message received event so that we don't have to put the space in.
