### ISSUE TITLE
Music Player doesnt work

### ISSUE THREAD

**Issue by SeiEinFisch** [Kwoth/NadekoBot#608]
I tried to use music commands but none of it worked. I dont even get a message. Nothing happens but I can still use other commands.
Hope you can help me ^^

**Comment by miraai** [comment]
📣 If you got the bot from Carbonitex, help or our github, music is disabled on public Nadeko and its not working due to large maintenance expenses, except when Kwoth is testing music. If you want music you will have to host Nadeko yourself. To do that, check Nadeko documentation.

**Comment by SeiEinFisch** [comment]
Ok thank you
