### ISSUE TITLE
Self-assignable roles reset

### ISSUE THREAD

**Issue by Accelerando** [Kwoth/NadekoBot#609]
Will the self-assignable roles ever stay saved? Whenever Nadeko goes down for whatever reason, I have to redo the .asar and it's quite annoying when new users join the server and the info section says that you can assign these roles but they end up not working cause Nadeko went down when I never noticed.

**Comment by miraai** [comment]
It will be fixed. It should not happen at all, but Nadeko had server issues for a while, it will not happen at all in 1.0. Hopefully will not happen again.

**Comment by Kwoth** [comment]
^
