### ISSUE TITLE
Restrict NSFW Content

### ISSUE THREAD

**Issue by omguser** [Kwoth/NadekoBot#610]
Hi,

I would like to enable NSFW content on my discord server. BUT I want it limited to one specific channel only.

Example:
# general
# admin
# nsfw
# games

If people use the ~hentai command or ~rule34, I only want the command to work in # nsfw channel, and no other channel.

However, I want the bot to be able to see and read and message the other channels, as it logs the chat and has other functions too.

**Comment by miraai** [comment]
Please, first check Nadeko documentation and Permissions system section. Then check the commands list. What you are looking for is `;cm`.

Have fun!

**Comment by Kwoth** [comment]
http://nadekobot.readthedocs.io/en/latest/Permissions%20System/
