### ISSUE TITLE
Question : Bot

### ISSUE THREAD

**Issue by di48l069** [Kwoth/NadekoBot#611]
Hi,

I did not know how else to contact you,

I'm creating a bot would it be alright with you if I use your app structure and some features if I can what credits for you must I provide?

**Comment by appelemac** [comment]
@di48l069 you can take a look at @Kwoth's licensing system (https://github.com/Kwoth/NadekoBot/blob/master/license.md).

**Comment by di48l069** [comment]
@appelemac thanks
