### ISSUE TITLE
Nadeko bot has stopped working.

### ISSUE THREAD

**Issue by SoRhyme** [Kwoth/NadekoBot#618]
Hey there. 
I was running Nadeko bot, and suddently (few hours ago) the bot stopped working. I tried to relaunch the bot (I have hosted the bot). 
The cmd give me this :

> No google api key found. You will not be able to use music and links won't be shortened.
No trello appkey found. You will not be able to use trello commands.
Forwarding private messages to owner.
No soundcloud Client ID found. Soundcloud streaming is disabled.
No osu! api key found. Song & top score lookups will not work. User lookups still available.
Token is wrong. Don't set a token if you don't have an official BOT account.
Discord.Net.HttpException: The server responded with error 401 (Unauthorized)
   à Discord.Net.Rest.RestSharpEngine.<Send>d__10.MoveNext() dans C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\Net\Rest\SharpRestEngine.cs:ligne 112
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Discord.Net.Rest.RestClient.<Send>d__25.MoveNext() dans C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\Net\Rest\RestClient.cs:ligne 119
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Discord.Net.Rest.RestClient.<Send>d__21`1.MoveNext() dans C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\Net\Rest\RestClient.cs:ligne 75
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à Discord.DiscordClient.<Login>d__79.MoveNext() dans C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\DiscordClient.cs:ligne 257
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à Discord.DiscordClient.<BeginConnect>d__78.MoveNext() dans C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\DiscordClient.cs:ligne 202
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à Discord.DiscordClient.<BeginConnect>d__78.MoveNext() dans C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\DiscordClient.cs:ligne 222
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Discord.DiscordClient.<Connect>d__77.MoveNext() dans C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\DiscordClient.cs:ligne 176
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à NadekoBot.NadekoBot.<>c.<<Main>b__32_3>d.MoveNext() dans C:\Users\Kwoth\Source\Repos\NadekoBot\NadekoBot\NadekoBot.cs:ligne 190

Sorry, some parts are in french.

I have totally deleted the bot and tried to reinstall one by following this guide [https://github.com/Kwoth/NadekoBot/blob/master/ComprehensiveGuide.md](url) and it gives me the same error.

I'm on W10, the bot worked well until few hours ago, but stopped and don't work anymore.

**Comment by fearnlj01** [comment]
Grab the latest update and it should work!

**Comment by SoRhyme** [comment]
> Grab the latest update and it should work!

> I have totally deleted the bot and tried to reinstall one by following this guide https://github.com/Kwoth/NadekoBot/blob/master/ComprehensiveGuide.md and it gives me the same error.

I've reinstall the bot with an updated one, and it still give me the same error

**Comment by SoRhyme** [comment]
Solved, sorry
