### ISSUE TITLE
Error code when trying to run bot

### ISSUE THREAD

**Issue by AlfonzoFrejoles** [Kwoth/NadekoBot#619]
Whenever I try and open my bot, I get this error message:

![image](https://cloud.githubusercontent.com/assets/20632405/18371215/92a6efdc-7600-11e6-8a3b-efc40f253e0b.png)

The same thing happens with my friends bots. Only a few hours ago, they were working just fine.

**Comment by miraai** [comment]
Update.

**Comment by xnaas** [comment]
Please download the latest release and copy everything but the data folder into your current bot folder.

**Comment by AlfonzoFrejoles** [comment]
Huh, I wonder why it would be telling me to update now instead of earlier. Thanks for the help though!

**Comment by xnaas** [comment]
@Kwoth please close this.

**Comment by Foxwells** [comment]
I hate to thread hijack, but @xnaas can you explain what you mean by "copy everything but the data folder into your current bot folder"? Because I updated, but I'm still getting the error, and I don't think I understand what I'm supposed to be copying (or where it's located).
