### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Twinky619** [Kwoth/NadekoBot#621]
For some reason after the new update my bot has stopped working.
<img width="946" alt="error" src="https://cloud.githubusercontent.com/assets/18133508/18406561/67399440-76b3-11e6-9987-ac048aefdf94.PNG">
I have tried generating a new token and replacing it in credentials.json but no luck.
It was working fine before.

**Comment by Kwoth** [comment]
You should update the bot to the latest version (0.99.9z) manually https://github.com/Kwoth/NadekoBot/releases if you are getting 400 or 401 error
To update, extract everything from the latest .zip except the /data/ folder into your current NadekoBot folder.
