### ISSUE TITLE
cannot queue songs at all

### ISSUE THREAD

**Issue by AlfonzoFrejoles** [Kwoth/NadekoBot#624]
Whenever I use !!q on my bot, it doesn't queue the song. I have my google api key and after updating to the newest version, it doesn't want to work.

**Comment by Kwoth** [comment]
Is there any error in the console?

**Comment by AlfonzoFrejoles** [comment]
nothing at all

**Comment by fearnlj01** [comment]
Try "-commands Music" Your prexfix may have changed

**Comment by AlfonzoFrejoles** [comment]
I just checked, and they did. Thanks for the help!
