### ISSUE TITLE
NSFW Commands don't work with multiple tags

### ISSUE THREAD

**Issue by Alodapos** [Kwoth/NadekoBot#626]
This started happening after updating 2 days ago (the update that change music from !m<space> to !!)
Like the title suggest , using ~<Nsfw command here> tag1+tag2 will no return any results - tested with a previous version and it works fine.
Forgive me if I missed something

**Comment by Kwoth** [comment]
`~hentai tag+tag` won't actually work because we already havethe explicit tag internally. You can only use one tag with it.

`~danbooru` and `~gelbooru` work with 2 tags however. I tested it right now.
