### ISSUE TITLE
~i and ~ir use some level of safesearch, or something

### ISSUE THREAD

**Issue by ibigfire** [Kwoth/NadekoBot#631]
When using ~i with adult terms it rarely returns what is actually the first image of that search, choosing a safer image instead.  I suspect it has some sort of "medium" setting enabled on safesearch, even though as far as I can tell by looking through SearchesModule.cs and Google's Custom Search API it should not.

**Comment by Kwoth** [comment]
It is ok for it to be safe if it is. I don't want getting nsfw results randomly anyway.

If this is correct i like it.

**Comment by appelemac** [comment]
If you want this, you can specify the safe search level in the request @kwoth
