### ISSUE TITLE
Some sort of way to voteskip.

### ISSUE THREAD

**Issue by MyranZ** [Kwoth/NadekoBot#632]
Me and my friends use your bot on a daily basis and came up with this idea. We have the _skip_ command disabled since we don't want people skipping each other songs. Sometimes everyone is queing songs at the same time and we'll have the problem that a song starts playing that not everyone likes. We thought it would be really useful if we had a way to "voteskip" songs which will be based on the majority preference and not just one person taste. We would really appreciate if you could somehow implement this feature. 

Greetz, 

MAL Recclub

**Comment by Kwoth** [comment]
already planned, no ETA.
