### ISSUE TITLE
.delmsgoncmd doesn't apply to .iam

### ISSUE THREAD

**Issue by Zalodu** [Kwoth/NadekoBot#633]
Unless I'm missing something, the messages for invoking ``.iam`` and ``.iamnot`` as well as the response the bot gives always gets deleted, regardless of ``.delmsgoncmd`` being toggled on or off. This does not apply to related commands such as ``.asar`` and ``.lsar`` which correctly respects the ``.delmsgoncmd`` setting.

Reproduce by toggling ``.delmsgoncmd`` to **not** delete invocations, and then calling ``.iam %role%``.

**Comment by xnaas** [comment]
>Toggles the automatic deletion of user's successful command message to prevent chat flood. **Server Manager Only**.

Hopefully I'm not misunderstanding you, but this means if I type `>plant`, `$give`, `>t 1`, etc., that message I typed will be deleted automatically by the bot. The bot's reply to the command will stay.

Some commands (particularly music commands) already have a lot of automatic cleanup of bot and user messages. In the case of `.iam`, I'm not sure the exact behavior (I don't use it on my own server), but I can say with 90% certainty that it is behaving however it was programmed by the dev if you have `. delmsgoncmd` off.

**Comment by Kwoth** [comment]
In 1.0 you will have an option to change auto delete of self assigned role messages.
