### ISSUE TITLE
Had a question...

### ISSUE THREAD

**Issue by Vanituhs** [Kwoth/NadekoBot#635]
So, I guess I'm kind of confused so a little bit of help on this would be awesome! I didn't think the NadekoBot had to be self-hosted, but it appears it does? If I'm wrong, can someone correct me?

It's weird that the bot is online in the server, but needs to be self-hosted for the commands to execute. Is it possible to do this in any fashion other than self-hosting the bot? I'm going to be starting a rather large community discord channel soon, and I hope to see that I don't have to leave my computer online 24/7 for the bot's functionality to work.

Let me know, and thanks for taking the time to read this!

**Comment by Kwoth** [comment]
No it does not have to be self hosted. You can invite the public bot with this link 

https://discordapp.com/oauth2/authorize?client_id=170254782546575360&scope=bot&permissions=66186303

She had a pretty long downtime until few hours ago.
