### ISSUE TITLE
Nadeko only greet when first login

### ISSUE THREAD

**Issue by loico78** [Kwoth/NadekoBot#636]
Hi,

I activated .greet and .bye message on my bot. However, It's only greeting people on their first log into the server, and sending the bye message when I kick them. 
Is there a way to make her greet people at each login, and each leaving?

Thanks.

**Comment by kongslien** [comment]
If you mean telling when people log in and such, you can use 
.userpresence
The bot will then tell their statuses.

**Comment by Kwoth** [comment]
^

**Comment by loico78** [comment]
I was more thinking about sending a custom message when people log in.

**Comment by Kwoth** [comment]
You cant
