### ISSUE TITLE
Permission System

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#639]
We are thinking about chained permission system inspired by iptables. This is just an idea.

Basically permissions will go through each of the rules in the chain and stop at the first matching rule. Better explained with the follow example:

- Each of the servers will start with a basic chain.   

#### Basic chain
1. server nsfw disable
2. enable all

When a command is ran, it will hit first rule. If it is a nsfw command it will be unable to run it due to that rule, and it will exit the chain. If the command is not nsfw, it will advance to the next rule and since it allows any command to be ran, it will trigger that rule and exit the chain.

#### Dj role
1. DJ role music enable
2. server music disable
3. enable all

If it is a a music command, and the person running the command is in a DJ role, first rule in the chain will trigger. If he is not in the DJ role, second rule will trigger, disallowing him the use of music commands. If it is any other command, it will allow it with 3rd default rule.

**Comment by miraai** [comment]
First

**Comment by Kwoth** [comment]
This is basicaly done.
