### ISSUE TITLE
Custom currency sign doesn't display correctly in private message

### ISSUE THREAD

**Issue by VF2blaze** [Kwoth/NadekoBot#645]
I have changed the currency sign to the :eggplant: emoji. However, when greeted by the $take command it will display the currency sign as letters instead of the icon because of the quote box feature.

One solution can be that the quotation box ends before the currency sign and the box starts again after it.

![capture2](https://cloud.githubusercontent.com/assets/22278111/18617420/0104ecde-7e23-11e6-801a-31f5e76c301f.JPG)

**Comment by Kwoth** [comment]
Show me your currency name in the config.json

**Comment by VF2blaze** [comment]
![capture2](https://cloud.githubusercontent.com/assets/22278111/18617514/51d16f28-7e25-11e6-9a3e-9bff88721764.JPG)

**Comment by Kwoth** [comment]
That is the problem. Copy paste this 
`🍆`
instead of 
`:eggplant:`

**Comment by VF2blaze** [comment]
Thank you

**Comment by Kwoth** [comment]
♥️
