### ISSUE TITLE
NadekoBot Music Issues - Computer Hosted

### ISSUE THREAD

**Issue by RavoTheGreedy** [Kwoth/NadekoBot#648]
So after I learned that music wasn't enabled on the NadekoBot I decided to host the bot on my laptop. I've been having multiple issues.

- Music cuts out on bot
I'll just be listening and then a song will be choppy for a few moments and catch up.
- Bot stops taking commands after awhile
it will take commands for awhile but ill let it sit and then try and skip a song out of a 40 song playlist and it doesn't work. The only way to fix this is to restart the bot but then i have to skip through 20 songs to get back to the spot I was.

Specs:
i7-6700HQ CPU @ 2.60GHz
Windows 10 64 Bit
8GB RAM

Internet Speed:
[http://www.speedtest.net/result/5647922105.png](url)

I'm just curious if there is a way I can fix any of these issues or if this is normal behavior. Maybe its a RAM issue and I can somehow allocate more to the bot? Thank you for any and all help provided.

**Comment by miraai** [comment]
Try moving Discord Server location closer to you, and if already is, try moving it around :)
