### ISSUE TITLE
Twitch stream notifications not working (as well as a few other problems)

### ISSUE THREAD

**Issue by 1Girl3Balls** [Kwoth/NadekoBot#650]
Basically whenever I use ~tw TwitchUserHere and they start streaming, Nadeko Bot doesn't notify the channel. No idea why it's like that; ever since I updated the bot it's been acting pretty weird
Sometimes ignores some commands, sometimes runs them. It seems random whether it'll run or not
Anyone got a fix for it? 
If I have to reinstall the bot from scratch, how do i keep my previous settings/preferences?

**Comment by fearnlj01** [comment]
Twitch notifications have been fixed for 1.0 release, they broke due to a change in the twitch API.
Keep the `/data/` folder and the `credentials.json` to keep all your settings

**Comment by miraai** [comment]
Twitch changed their API, it will be fixed in the next release.
Dammit, @fearnlj01 xd
