### ISSUE TITLE
!!S doesn't work when queuing a playlist.

### ISSUE THREAD

**Issue by Zylon** [Kwoth/NadekoBot#651]
`!!s` skips the song like `!!n` does, and doesn't clear the queue like it should. but only when using `!!pl` to load a playlist instead of queuing multiple songs with `!!q`

**Comment by Kwoth** [comment]
You need to wait for the whole playlist to queue up. Because you do stop the player and clear the queue, but it keeps queueing them in the background, since there is no playlist queing cancellation system.
