### ISSUE TITLE
Problem when Installing bot

### ISSUE THREAD

**Issue by EonIsAnOtaku** [Kwoth/NadekoBot#653]
I followed the instructions on the windows guide and ran NadekoUpdater.bat and I pressed 2 and y as instructed and after the downloading screen, it gave me this error. 
![screenshot 572](https://cloud.githubusercontent.com/assets/22389639/18789551/04eb851a-81de-11e6-8942-d56fd44393fb.png)
How do I solve this issue?

**Comment by kongslien** [comment]
Updater is broken, manually download it from here

https://github.com/Kwoth/NadekoBot/releases
