### ISSUE TITLE
anyone can use excluded "Administration Commands"

### ISSUE THREAD

**Issue by rtil5** [Kwoth/NadekoBot#661]
even though i only have my ID in the OwnerIds array in credentials.json, anyone can use .prune and .kick. i even tried disabling these commands for the @everyone role and it made no difference. am i missing something?

**Comment by Kwoth** [comment]
Yes, you are not using permission system correctly for roles. Also, everyone who has kick permissions in discord can use `.kick`

**Comment by rtil5** [comment]
" By default, every command is enabled for everybody, however a few exclusions are the Administration Commands like, .kick and .prune and Bot Owner-Only commands as these require your id to be in credentials.json."

is this information out of date, then? because anyone on my server can use .prune. the only solution i have discovered so far is to disable the command for the server since it has hierarchy if i'm not mistaken.

**Comment by Kwoth** [comment]
Yes that is incorrect info, where did you find that? :D

Kick is usable by people who have kick permissions in discord. `.prune` can be used by anyone and it clears only bot messages. Other variations of prune (with arguments) can only be used by people with manage messages permissions. 

If you wish to disable a command for a specific role, refer to the `creating a DJ role` section of the permission guide found here http://nadekobot.readthedocs.io/en/latest/Permissions%20System/ and modify it to suit your needs
