### ISSUE TITLE
Config edits aren't working

### ISSUE THREAD

**Issue by greenteakitkats** [Kwoth/NadekoBot#663]
I've been trying to edit the race animals as well as the currency sign/name. While the currency changes last, no matter what I do I can't get the race animals to update. I've copied the emojis from emojipedia and edited config, config(restored) and config_example. Is there something I'm missing to have it change?

**Comment by Kwoth** [comment]
restart the bot.

**Comment by greenteakitkats** [comment]
I've restarted it many times. That's why I mentioned that the currency gets overridden but the emojis never change.

**Comment by Kwoth** [comment]
Just wait for 1.0
