### ISSUE TITLE
Error while attempting to play music

### ISSUE THREAD

**Issue by v3Monsta** [Kwoth/NadekoBot#664]
So i'm out of options here. I've tried looking on StackOverflow about what I can do to regain access to the API, so I turned the bot off for a full 24 hours and still nothing. I'm sure that this isn't a Nadeko issue but i'd really like some help from you guys.

![untitled](https://cloud.githubusercontent.com/assets/16313385/18933485/02184d00-85a3-11e6-9a12-ca817d5c159a.png)

**Comment by Kwoth** [comment]
create a new google api key?

**Comment by v3Monsta** [comment]
I've tried that as well as creating an entirely new project.
