### ISSUE TITLE
Soundcloud has new app registration

### ISSUE THREAD

**Issue by analogouscpond** [Kwoth/NadekoBot#666]
So I was setting up my bot manually but now they have a new registration page. Please upload a guide to help with this. I tried twice but did not work after waiting 2 days.
https://gyazo.com/445dc62fd21ab3ccb8eed71d77bf8a2d

**Comment by Kwoth** [comment]
@miraai :D

**Comment by analogouscpond** [comment]
Sooooo is that a yes bb ;)

**Comment by miraai** [comment]
It shall be done!

**Comment by miraai** [comment]
Wait, soundcloud is fixed. You have to apply for an API key, we already did that.

**Comment by angelc3** [comment]
Where is the key?

**Comment by fearnlj01** [comment]
You will recieve your API key **if** SoundCloud approve your application. It's in the guide here [(screenshot)](http://i.imgur.com/TJkGgGW.png)

**Comment by miraai** [comment]
^
