### ISSUE TITLE
[Feature Request] Pull credentials from environment variables if present

### ISSUE THREAD

**Issue by TheTou** [Kwoth/NadekoBot#668]
It would come in handy for a fast docker setup to be able to pass the credentials via environment variables, instead of putting them in via the credentials.json file as it is currently.

**Comment by Kwoth** [comment]
good idea.

**Comment by Kwoth** [comment]
this was done 10-15 days ago. you can set Environment variables like `NadekoBot_Token` (same as in credentials, only prefixed with `NadekoBot_`). For owner ids, you need to add indexed enviornemnt variables in following format `NadekoBot_OwnerIds__1`, `NadekoBot_OwnerIds__2` `NadekoBot_OwnerIds__3`... etc (for each owner)
