### ISSUE TITLE
Playlist command not working and feature request

### ISSUE THREAD

**Issue by Credskiz** [Kwoth/NadekoBot#669]
**Issue**: Pulling playlists from youtube doesn't seem to work with the !!playlist, !!pl commands. No response from command. 

**Feature Requests:** Allow user to add, remove as well as display songs from/in already existing saved playlists. (youtube-link-playlist, saved by !!save)

**Comment by miraai** [comment]
If its not working, you did set up your API key right. Check if you have all three modules enabled.

Users can add, remove and display all songs in already saved playlists. All you have to do is do save again.

**Comment by Credskiz** [comment]
Which three modules, specifically, do you mean? I set up the google API key (Youtube Data API or something), adding songs individually works as intended.

With adding to already existing playlists, will another !!save on the playlist append the songs to it and not override the entire playlist with the current queue? Also, how do I remove individual songs from an existing playlist?

**Comment by miraai** [comment]
You need YouTube Data API key, Custom Search and URL Shortener API, as stated in the guide.
http://nadekobot.readthedocs.io/en/latest/guides/Windows%20Guide/#setting-up-nadekobot-for-music

**Comment by miraai** [comment]
To add a song to a playlist, load the playlist, queue the new song and save it. The whole palylist with the new song will be saved, same thing goes with removing the song.
