### ISSUE TITLE
Trivia occasionally fails to inform of a correct answer

### ISSUE THREAD

**Issue by Nyefan** [Kwoth/NadekoBot#675]
I think it's because of a rate limiting issue affecting line 129 in TriviaGame.cs.

Here's the sequence of events that I believe causes the behavior:

* Bot receives a correct answer
* PotentialGuess is called with the answer message
* PotentialGuess executes up through line 128, cancelling the task
* TaskCancelledException is caught on line 81
* line 129 is rate limited, throwing an exception, preventing execution of lines 130-134, and reverting the state of the task (so it was never cancelled)
* GameActive is set to false on line 82, preventing further messages from being acknowledged
* The task was never cancelled, so line 84 is executed, acting like a time-out

**Comment by Kwoth** [comment]
Let me check.

**Comment by Kwoth** [comment]
Last statement is incorrect. Task was canceled on line 128. So that line wouldn't execute.

**Comment by Kwoth** [comment]
Atm fixing these and similar situations in 1.0. Added shouldstopgame=true in the catch in 0.9, but idk if there will be another release of 0.9
