### ISSUE TITLE
self-assignable role list clearing itself

### ISSUE THREAD

**Issue by Schiffy94** [Kwoth/NadekoBot#682]
So this seems to happen every... I don't know actually. It might be whenever Nadeko ends up going offline and coming back on later. But however often, the self-assignable roles I set for Nadeko on my server end up clearing themselves, and `.lsar` spits back a number of 0. Not sure what's causing this.

**Comment by Nitix** [comment]
You are right, it's when Nadeko goes down, however this is gonna be fixed with 1.0 release.

**Comment by Kwoth** [comment]
yes, this will stop happening in a matter of days
