### ISSUE TITLE
A bug about $take?

### ISSUE THREAD

**Issue by Davinais** [Kwoth/NadekoBot#683]
I'm using version 0.99.10.
I was trying to figure out how would Nadeko react when I take a number of currency more than a user's own.
What I excepted is that Nadeko would reply that there wasn't enough flower to take, or just set the user's flowers to 0.
But what I get is:
![bug](https://cloud.githubusercontent.com/assets/5267712/19214480/f20092ca-8db7-11e6-9078-e66f0fb8ad7c.png)

The Bot send a successful message, but actually nothing happened.

Although it just a small question, I still want to resolve it.
Thanks.

**Comment by Kwoth** [comment]
Yea, it just doesn't send a message saying its not successful. It will be fixed in 1.0. You have to take exact amount he has if you want him to be at 0
