### ISSUE TITLE
Typing 'e' in the chat outputs "did it :unamused: :gun:"

### ISSUE THREAD

**Issue by Kamerdra** [Kwoth/NadekoBot#688]

**Comment by fearnlj01** [comment]
This is from the custom reaction "e". Either do `.dcr e` if you are hosting the bot yourself to delete this reaction, or do `;sc e disabled` to disable the command from being used on the server. 

If you use the second command, you may want to follow it up with `;verbose 0` to prevent it from telling you that the command is blocked from use in the server each time you type "e"
