### ISSUE TITLE
NadekoUpdate.exe Has stopped working

### ISSUE THREAD

**Issue by jonakun** [Kwoth/NadekoBot#690]
Hi All,

I'm trying to install the bot but every time I try to run the nadekoupdater.bat file it results in a nadekoupdater.exe has stopped working. Running it as administrator doesn't seem to help.

**Comment by fearnlj01** [comment]
The updater is mostly broken, Grab the latest release from [here](https://github.com/Kwoth/NadekoBot/releases/tag/v0.99.10), extract that to the `Nadeko` folder mentioned in the guide and carry on through the guide ignoring the updater

**Comment by jonakun** [comment]
Awesome! This work perfectly. Thank you!
