### ISSUE TITLE
NSFW functions dont work at my server.

### ISSUE THREAD

**Issue by exiledwolf** [Kwoth/NadekoBot#692]
I try to change permissions but nothing with the prefix " ; " are working. Can you help me?  
![image](https://cloud.githubusercontent.com/assets/22826544/19370188/98323448-9180-11e6-8130-f300fcf118a7.png)

**Comment by Kwoth** [comment]
Create a **NEW** role called Nadeko, give it to yourself and type `;sm nsfw enable`

You might want to look into permission system in the future http://nadekobot.readthedocs.io/en/1.0/Permissions%20System/

**Comment by exiledwolf** [comment]
I already tried this commands and others with prefix " ; " and nothing occurred. :/
