### ISSUE TITLE
NSFW functions dont work at my server again.

### ISSUE THREAD

**Issue by exiledwolf** [Kwoth/NadekoBot#693]
I already tried all commands of list for create perms and etc. But anyone work because he have prefix " ; " only this command is impossible to edit. Any tips? Here a img with a function command and a not function. Ty

![image](https://cloud.githubusercontent.com/assets/22826544/19409027/abe03f86-92a1-11e6-9bfc-08207105071d.png)

**Comment by fearnlj01** [comment]
Create a **NEW** role called **Nadeko**, give it to yourself and type `;sm nsfw enable`
