### ISSUE TITLE
Issue configuring FFMPEG / getting data from stream

### ISSUE THREAD

**Issue by SevenNights7** [Kwoth/NadekoBot#694]
Hi, I just followed your guide on setting up NadekoBot on Windows, and then setting it up for playing music. Everything went perfectly well and fine - except for Nadeko actually playing music. I got my Google API key on credentials.json, enabled the 3 requested API modules, installed FFMPEG manually and setup the pathing. After I restarted, I tested the instalation by running "FFMPEG -version" on the command line, and all seemed well.

But when I try queueing a radio, a local file or a youtube video it doesn't play, and I get a message in the (Nadeko) command line saying FFMPEG is not correctly installed or configured and "Prebuffering timed out or canceled. Cannot get any data from the stream."

Could this be a port forwarding problem? I've already added exceptions for the .exes on windows firewall to no avail... Please HELP!

EDIT: Managed to solve it myself, aparently the ffmpeg.exe inside the bot folder was 0 bytes in size for some reason, guess something went wrong extracting that single file (since everything else was fine). Works like a charm now!

**Comment by Kwoth** [comment]
glad you solved it, had no idea what could cause it :D
