### ISSUE TITLE
Restore failing on 1.0

### ISSUE THREAD

**Issue by v3Monsta** [Kwoth/NadekoBot#717]
This is the result of running a restore.
![nadekoissue](https://cloud.githubusercontent.com/assets/16313385/19628744/999c3360-9932-11e6-8e0c-39f4615f0cf2.png)

**Comment by Kwoth** [comment]
use the installer

https://github.com/Kwoth/NadekoBotInstallerWin windows
or 
https://github.com/Kwoth/NadekoBot-BashScript linux

**Comment by v3Monsta** [comment]
Still getting the same error with the bash script

**Comment by Kwoth** [comment]
Distro?

**Comment by v3Monsta** [comment]
Ubuntu server 16.04

**Comment by Kwoth** [comment]
ok, instead of dotnet restore, try doing 

`dotnet restore -s https://api.nuget.org/v3/index.json,https://www.myget.org/F/imageprocessor/api/v3/index.json,https://dotnet.myget.org/F/dotnet-core/api/v3/index.json`

**Comment by v3Monsta** [comment]
Didn't work either, also getting errors resolving the ImageProcessorCore now

**Comment by Kwoth** [comment]
k fk it, 

cd discord.net
dotnet restore
cd ../src/NadekoBot
dotnet restore

**Comment by v3Monsta** [comment]
Same error in resolving System.Net.WebSockets.Client

**Comment by Kwoth** [comment]
ok then go into discord.net/src/Discord.Net and restore there
then in dicsord.net/src/Discord.Net.Commands

**Comment by v3Monsta** [comment]
Worked, no errors when I tried to restore NadekoBot/ after

**Comment by Kwoth** [comment]
We will update installers soon
