### ISSUE TITLE
Permissions do not stay consistent.

### ISSUE THREAD

**Issue by fkndean** [Kwoth/NadekoBot#727]
Every time the bot restarts, the perms get reset.

***EDIT***
Custom reactions are all gone too.

**Comment by Kwoth** [comment]
O.o Make sure you're not in any of the folders, or have some files or db open in the nadekobot folder. I'm using installer on global Nadeko and it does not overwrite anything.

**Comment by fkndean** [comment]
Ok thanks, I will test around and check to make sure.

**Comment by fkndean** [comment]
We put the command in a `while :` loop and she is told to start back up 5 seconds after it stops.

Also
`.restart` is broken. It errored because I would have to give it a filename.

**Comment by Kwoth** [comment]
yea restart is removed.

Fearnlj01 is looking into data loss when db is opened.
