### ISSUE TITLE
The .logserver command will not work!

### ISSUE THREAD

**Issue by ZLDProductions** [Kwoth/NadekoBot#734]
I have tried multiple times, with several different prefixes, to use this command. What is the prefix for it, specifically?

**Comment by Kwoth** [comment]
.

SERVER OWNERS ARE NOT BOT OWNERS. All owner-only commands require you host the bot. Hosting means you are running a nadekobot.exe on your own computer.

**Comment by Kwoth** [comment]
If you are hosting and you still can't run it, then your OwnerId in the credentials.json is wrong.

**Comment by ZLDProductions** [comment]
Where do I get nadekobot.exe?

**Comment by spencersager** [comment]
Find the guides here:
http://nadekobot.readthedocs.io/en/latest/
