### ISSUE TITLE
Any move with a space in Pokegame causes "No such person." error.

### ISSUE THREAD

**Issue by tomijuu** [Kwoth/NadekoBot#738]
![image](https://cloud.githubusercontent.com/assets/23231988/19958750/ec9dee30-a15e-11e6-8f9c-bee222ad9542.png)

![image](https://cloud.githubusercontent.com/assets/23231988/19958772/0ca2c3f4-a15f-11e6-97d6-09dcc18a70e9.png)

**Comment by blitz4694** [comment]
put the attack in "", like "dazzling gleam"

**Comment by tomijuu** [comment]
rip my bad, ty for the fast response
