### ISSUE TITLE
Warnings about OpCodes

### ISSUE THREAD

**Issue by ZirconiumHacker** [Kwoth/NadekoBot#739]
When I start the newest version of NadekoBot, I sometimes get some or all of the following warnings:
`Severity: WarningExceptionMessage: -Message: Unknown Opcode: Heartbeat`
`Severity: WarningExceptionMessage: -Message: Unknown Opcode: 8`
`Severity: WarningExceptionMessage: -Message: Unknown Opcode: 9`
`Severity: ErrorExceptionMessage: EndWrite failureMessage: Disconnected`

Sometimes I don't get any warnings.
Am I doing something wrong?  Was there an API change or something that broke the bot?

**Edit (ninja-reedited):** Sometimes the bot fails (when the last error happens).  AFAIR no commands are recognized.  Other times the warnings just happen while the bot is running and it still works.
**Edit 2:** I am using the latest binary release, v0.99.10.
**Edit 3:** There are also warnings whenever custom reactions are updated, which spams the log on busy servers.

**Comment by appelemac** [comment]
Does the bot still work after this?

**Comment by Kwoth** [comment]
is it 0.9 or 1.0?

**Comment by ZirconiumHacker** [comment]
I've edited the OP's details based on the questions.  I am open to trying the 1.0 branch, but it's sometimes tricky to get MonoDevelop working.  Last time I compiled Nadeko from source the IDE complained about outdated packages and broken or nonexistent references, I think.  Hard to explain; I'm a C++ programmer.

**Comment by ZirconiumHacker** [comment]
Whoops, didn't know what that button did.  Sorry!

**Comment by Kwoth** [comment]
0.9 is no longer being developed. If you run into issues, upgrade to 1.0 http://nadekobot.readthedocs.io/en/1.0/
