### ISSUE TITLE
Twitter Integration

### ISSUE THREAD

**Issue by Jinx133** [Kwoth/NadekoBot#74]
Suggestion: A Twitter Integration that posts/links a twitter account's tweet in a channel automatically.

If a Twitter API Key is provided to the bot, it could automatically link Tweets in a channel chosen by the bot owner to announce them.

Example of the integration over slack: http://i.imgur.com/iisySs0.png

Thanks for your time!

**Comment by SillyBirds** [comment]
Is this planned for 1.0?

**Comment by Kwoth** [comment]
Since discord has webhooks now which can do this, i think i should close this issue?

**Comment by SillyBirds** [comment]
Yeah, I've been a webhook with zapier and it works fine...

**Comment by Kwoth** [comment]
thx for the update
