### ISSUE TITLE
[Nadeko 1.0] Owner bug ?

### ISSUE THREAD

**Issue by Taknok** [Kwoth/NadekoBot#742]
Hello,

Testing the permissions module, Nadeko told me to get nadeko role to do the commands even if i was the bot owner. Is that wanted ?
If not change : CommandHandler.cs:279 by `if ( !((IGuildUser)user).Roles.Any(r => r.Name.Trim().ToLowerInvariant() == pc.PermRole.Trim().ToLowerInvariant()) && (this.ownerChannels.Any(o => o.Recipient.Id != user.Id)) )`
_There probably is a better way to do it, but it works_

Nice work and have a good day :)

**Comment by Kwoth** [comment]
yes, i might change it so guild owners don't have to do it, but letting bot owners manage permissions on any channel they want is not right
