### ISSUE TITLE
[Feature Request] Create Groups of Exclusive Self-Assignable Roles

### ISSUE THREAD

**Issue by vsod99** [Kwoth/NadekoBot#747]
I believe it would be useful to have different groups of self-assignable roles. Let me use my server as an example. 

I run the /r/Skyrim Discord server, and I want users to be able to self assign their races, and Imperial/Stormcloaks status. At the moment, I can't add the races to self-assignable roles because I need them to be exclusive, but Imperials/Stormcloaks to be exclusive as well. If they're all in the same exclusive self-assignable group (which of course, since there isn't an option, they are by default) a user could not choose a race if they were already an Imperial or Stormcloak due to exclusivity. 

This is only my server's use case of course, I'm sure this feature would be useful for servers with multiple user roles as well.

**Comment by Kwoth** [comment]
I tend not to add too specific usecases. Self-assignble roles weren't meant for this.

**Comment by vsod99** [comment]
Makes sense. Thanks for the response.

**Comment by Shadnire** [comment]
Has this feature been added yet?

**Comment by Macley-Kun** [comment]
Isn’t made unless on featurehub it’s voted high.

**Comment by Kwoth** [comment]
yes this has been added

**Comment by Kwoth** [comment]
.h .asar
