### ISSUE TITLE
Moderator commands for (gaming) communities to handle inactive users

### ISSUE THREAD

**Issue by pedall** [Kwoth/NadekoBot#748]
1. A moderator command for gaming communities, that tells how long someone is on the discord server, how many messages have been written and when the last message of an user was written.

This should help to identify non-active members of a community.

2. And a auto role after some time of inactivity as well as the removal of that role if an user gets active again 

This feature would be used to list inactive members with already existing ".inrole" command

3. A feature to kick members that have a certain role or a certain amount of inactivity 

Kick members even though they have a role, cause built in Discord prune only works for members without roles

**Comment by Kwoth** [comment]
I'll actually drop this, 1. i don't like, 2. is too much hassle, and 3 part 1 i could add if there really is a need for it. You could put it in suggestions channel on the server if you want (Kick members in a role)
