### ISSUE TITLE
[Help] Weather Issue

### ISSUE THREAD

**Issue by ryuukibeat** [Kwoth/NadekoBot#751]
Help. I tried to use Nadeko hosted myself.

When I try to use weather commands, it refused to show the result. Am I overlooking something in the installation or what? When I tried with already hosted Nadeko, it works. 

Thanks

**Comment by miraai** [comment]
Are you hosting 1.0 or 0.99.9 version?

**Comment by ryuukibeat** [comment]
in NadekoBot.exe it say 0.9
![image](https://cloud.githubusercontent.com/assets/20012970/20097452/175c8dc6-a5e1-11e6-8f62-370bd069bf30.png)

**Comment by miraai** [comment]
Weather is not working on that version. 
Consider upgrading to 1.0 since 0.9 is not being supported anymore.

**Comment by Saiasanc** [comment]
@miraai - So how do you upgrade? The latest release is from September and the NadekoUpdater says you already have the latest version no matter which option you select.  If 0.9 is no longer supported, why isn't the latest version available under Releases yet?

**Comment by ryuukibeat** [comment]
yes, how to Upgrade? From Nadeko updater, this is latest version.
![image](https://cloud.githubusercontent.com/assets/20012970/20102605/4246df4c-a5f9-11e6-8ee9-3e3a3dfd2693.png)

**Comment by Kwoth** [comment]
http://nadekobot.readthedocs.io/en/1.0/ 

If you want to preserve data, there is a migration guide on the left, if not just follow the winodws/linux guide

**Comment by ryuukibeat** [comment]
Thanks.
