### ISSUE TITLE
[1.0][Feature Request] .mute @someone <time> <reason>

### ISSUE THREAD

**Issue by fkndean** [Kwoth/NadekoBot#756]
Adding at least the new arg `time` will prove to be useful in muting members for a certain amount of time without having to manually run a unmute command or remove the `nadeko-mute` role? Going to be in my to-do list if this is something that's worth pursuing.

**Comment by Kwoth** [comment]
I can't think of the proper way to do it. It has been suggested and on the radar. There are too many issues with it. Bot can lose permissions meanwhile, or hit 502 multiple times and admin will forget to unmute him. Bot can crash/be updated and cancel all unmute timers.  And I don't want to store this info in the database...
