### ISSUE TITLE
[1.0] "Failed resolving the link.Not a valid youtube query."

### ISSUE THREAD

**Issue by ZirconiumHacker** [Kwoth/NadekoBot#757]
As of the latest commit on the 1.0 branch, I cannot play specific YouTube videos through direct links.  For example, if I try `!!q We Are The Champions (Remastered 2011)` it works fine.  But through its link, with `!!q https://www.youtube.com/watch?v=tXyw4oMpeB4`, no music is played and the log shows this:

`Failed resolving the link.Not a valid youtube query.`
`21:25:26 CommandHandler | Command Errored after 0.2086614s`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`User:` *[redacted]*
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`Server:` *[redacted]*
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`Channel:` *[redacted]*
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`Message: !!q https://www.youtube.com/watch?v=tXyw4oMpeB4`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`Error: Value cannot be null.`
`Parameter name: s`

This does work however with other links, such as https://www.youtube.com/watch?v=EwTZ2xpQwpA.
Is this just a mistake on my part, a YouTube issue, or an actual bot issue?

**Edit:** Also happens with some searches, but a different error.
`Failed resolving the link.Response status code does not indicate success: 403 (Forbidden).`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*[...]*
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`Message: !!q peace of mind topic`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`Error: Value cannot be null.`
`Parameter name: s`

What the heck is going on here?  There used to be at least one version of the bot I could rely on, now 0.99 crashes (#739) and 1.0 silently glitches.

**Comment by Kwoth** [comment]
first issue is that song is probably blocked where your server is, or not being able to be streamed for whatever reason.

Second error is that you're missing, or have incorrectly setup google api key

**Comment by ZirconiumHacker** [comment]
My Google API key is absolutely fine, and the song isn't blocked (it worked before).  Is this really a Google bug?

**Comment by SillyBirds** [comment]
Gonna profit this music topic is here, because I have a somehow related problem.

Till 5 days ago, I had a 0.9 docker nadeko and I didn't have any issues with music. And since I updated to a 1.0 nadeko (linux one), music has not worked even once, with the exception of !!radio, which is fine.

Just in case, I made a new google api key, but that didn't help.

![console](http://i.imgur.com/S2JzjNk.jpg)

![api](http://i.imgur.com/eqKiM4o.jpg)

Any help would be appreciated.

Thanks,

**Comment by ZirconiumHacker** [comment]
@Kwoth Can this issue be reopened?  We have not confirmed with certainty that it is not a bot issue, and it affects multiple users.

**Comment by SillyBirds** [comment]
I was able to troubleshoot my problem! I don't know if the problem comes from _google_ or from _nadeko_, but the culprit was **ipv6**.

Turning that off fixed the issue for me.

**Comment by Kwoth** [comment]
I think i fixed this ~3 days ago, it was messed up.
