### ISSUE TITLE
[1.0] Logging Bug?

### ISSUE THREAD

**Issue by fkndean** [Kwoth/NadekoBot#763]
seems to have a bug in logging channels. If you type and enter a message it will not log it. However, if you delete or edit the message, it will log it. Unless this was intentional in the 1.0 remake?

**Comment by Nitix** [comment]
It's intentional, even 0.9 has this feature deleted.

**Comment by fkndean** [comment]
Ah I see, thanks for clearing that up.

---- On Fri, 11 Nov 2016 15:09:16 -0800 notifications@github.com wrote ----

It's intentional, even 0.9 has this feature deleted.
