### ISSUE TITLE
[Feature Request] yande.re image searching

### ISSUE THREAD

**Issue by Kyto** [Kwoth/NadekoBot#764]
There is already support for danbooru and gelbooru, can there be support for [yande.re](https://yande.re) too? Other bots used to have this function but they aren't around anymore and I think it'd be cool to have it on Nadeko.

Thanks!

**Comment by fkndean** [comment]
Done :) opened a PR for Kwoth to review.

#766

**Comment by Kyto** [comment]
Excellent, thanks for doing this 😄
