### ISSUE TITLE
.setavatar doesn't seem to do anything.

### ISSUE THREAD

**Issue by JakeSiegers** [Kwoth/NadekoBot#765]
I'm trying to set the avatar of the bot, but not even your example seems to work. 

.setavatar https://i.ytimg.com/vi/WDudkR1eTMM

I'm the owner of my channel and I invited the bot with my account.

Am I doing something wrong? Thanks!

**Comment by Kwoth** [comment]
SERVER OWNERS ARE NOT BOT OWNERS. All owner-only commands require you host the bot. Hosting means you are running a nadekobot on your own computer. If you want to learn how to host the bot yourself, type `-guide`
