### ISSUE TITLE
Music Volume Not Persistent Through Restarts

### ISSUE THREAD

**Issue by RMcD94** [Kwoth/NadekoBot#769]
https://github.com/Kwoth/NadekoBot/issues/324

There are a lot of reasons you would want the default volume to change all the time without manually adjusting the user volume to lower.

For example say you wanted the Nadekobot volume to be 10%, but you wanted to vary it up to 20% and to 5%, if you set the volume you can slam it to 200% or 50%. It's very easy to change.

If you leave the volume at 100% you have to fiddle trying to get 5% not 6% or 7%. As you can imagine if you want to set Nadekobot to 5% it is a magnitude harder, nay impossible to adjust per song.

**Comment by Kwoth** [comment]
command already exists `!!dv` , sets the default volume when bot starts

**Comment by RMcD94** [comment]
Awesome, glad to hear you changed your mind since the previous issue.
