### ISSUE TITLE
!m pl Error

### ISSUE THREAD

**Issue by Tadyr** [Kwoth/NadekoBot#77]
No matter what youtube playlist I link ie !m pl https://www.youtube.com/playlist?list=PLrRtwIUSeaCFFecNtIQ19ZfeksVEpdTwx
The console returns "Error in GetPlaylistId: The remote server returned and error: (400) Bad Request
I am running v0.8 b14.2
It plays all other individual videos just fine. There only seems to be issues with playlists.

**Comment by Kwoth** [comment]
That means you didn't setup your google api key properly. Watch the video tutorial and read the comprehensive guide.
