### ISSUE TITLE
Cant isntall NadekoBot

### ISSUE THREAD

**Issue by witchsorbet** [Kwoth/NadekoBot#794]
I install .NET Core SDK, Git, FFMPEG , but when i try to install NadekoBot I get this error:"dotnet not found, make sure it's been installed as per the guids instructions! Press any key to exit". Uninstall, than again install not working. How can i fix this?

p.s. I use windows 10 and Microsoft .NET Framework 4.6 installed

**Comment by samdivaio** [comment]
If [.NET Core is latest](https://go.microsoft.com/fwlink/?LinkID=835014) then try rebooting your PC, Few people have fixed that issue with a quick restart,
Let us know if that worked or not.

**Comment by witchsorbet** [comment]
It's working. Thank you
