### ISSUE TITLE
Google API randomly stopped working

### ISSUE THREAD

**Issue by BoWhackem** [Kwoth/NadekoBot#796]
Running a private Nadeko bot and everything was working without any issues. Then out of nowhere I get this error when issuing the !!q command. Sound cloud works fine, so this seems isolated to the google api's. 

Ive tried disabling/enabling the api's. Recreating a new project and assigning the bot the new project. Even created a new project under a different account and that key got same errors. 
No security/firewall settings was changed recently to cause this. 

Failed resolving the link.An error occurred while sending the request. Severity: warningExceptionMessage: -Message: Unknown Opcode: 8

**Comment by Kwoth** [comment]
probably an error related to 0.9, shouldn't happen in 1.0
