### ISSUE TITLE
[Feature Request] Show Custom Reactions including the formating

### ISSUE THREAD

**Issue by pedall** [Kwoth/NadekoBot#799]
Ability to show custom reactions with its format like **bold** to be able to copy the text with (partly complex) formatting for editing. 

Example:

One has the custom reaction "list" that shows

**1) BOLD**
~~2) STRIKED~~
*3) ITALIAN*

and I want to edit the the text "BOLD" to "NEW TEXT" it would be nice to make Nadeko output the Custom Reaction as follows, so one can copy & paste for editing.

```
**1) BOLD**
~~2) STRIKED~~
*3) ITALIAN*
```

**Comment by fkndean** [comment]
#807

**Comment by pedall** [comment]
Thank you!! 😀
