### ISSUE TITLE
Database Initialisation

### ISSUE THREAD

**Issue by Taknok** [Kwoth/NadekoBot#805]
Hello,

I have addapted the previous PokeGame to 1.0 I have few troubles bedore pull request (if you want it ^^). The module works, but I didn't understand very well the database initialisation : when i run the bot after au full clean, my Table isn't created in NadekoBot.db. If i add it wtih sql-request no problems :/. I have added my DbSet<PokeType> , complete de onmodelcreating and ensure_data in the NadekoContext. What am I missing ?

**Comment by Kwoth** [comment]
You need to add a migration. Go into Nadekobot/src/Nadekobot (next to project json) with cmd and type `dotnet ef migrations add pokegame`, then start the bot. Assuming you setup all models correctly, migration will apply automatically when you start the bot and it will work

**Comment by Taknok** [comment]
Sorry for bothering you, but i have an error when i run `dotnet ef migration add pokegame` so i cloned your dev, and I ran `dotnet ef migration list` it's return me the same error :/

**Comment by Kwoth** [comment]
oh, you need to readd old OnConfiguring method and then run the command, then readd it again. I think it's commented out in NadekoContext.cs

**Comment by Taknok** [comment]
Thank you ! It works !
Are you interrested to get the Pokegame module in the "official" Nadeko ?

**Comment by Kwoth** [comment]
depending on how it's done

**Comment by Taknok** [comment]
That's true
