### ISSUE TITLE
nadeko doesn't leave voice when done playing 

### ISSUE THREAD

**Issue by KimplEClonE** [Kwoth/NadekoBot#81]
In version 0.8 b14.2, i noticed this "nadeko doesn't leave voice when done playing, instead leaves only on !m s" thing.

Is it possible to change back to it's old behaviour via json or from somewhere else?

**Comment by Kwoth** [comment]
No, why are you bothered by her staying? She is not spying you or anything 








*for now*

**Comment by KimplEClonE** [comment]
Hmm... thats sad )';
People in my server like when nadeko is more "mobile" let's say
for example in old behavior it's just easy to type !m q [link], and Nadeko would come to you, 
but now people will need to check if Nadeko in anyother channel and try to move Nadeko from channel to another with different commands. (easy people like, that you need only 1 command to operate the bot)

I can see the convinience of static bot that stays on channel, but there is people that like old kind of Nadeko but still want new music code. 
can it be an option to change this behavior? could it be done, or is it just a fantasy, that i share with my server?
