### ISSUE TITLE
About .uinfo

### ISSUE THREAD

**Issue by koperkuba** [Kwoth/NadekoBot#810]
:bust_in_silhouette: Name: Arczi43#0247
:label: ID: 109975657026441216
:video_game: Current Game: Overwatch
**:date: Joined Server: 01.01.0001 00:00** 
:calendar_spiral: Joined Discord: 31.10.2015 11:23
:crossed_swords: Roles: (3) - @everyοne, nowy, ow
:camera: Avatar URL: https://goo.gl/iaDXbc

Why Joined Server: not store proper **date**?

**Comment by fkndean** [comment]
Seems to work fine for me.

**Comment by Kwoth** [comment]
Library bug, doesn't work for some.
