### ISSUE TITLE
!m q "nothing was buffered"

### ISSUE THREAD

**Issue by Wolcrez** [Kwoth/NadekoBot#83]
When i call "!m q" it doesnt work. The Console says: 
  "_Nothing was buffered, try another song and check your GoogleApikey._" 

I did what he says, and tells me the same. Help ;-; (sorry for my english).

**Comment by Wolcrez** [comment]
Solved.

**Comment by biguest** [comment]
How did you solve it ?
Because I have the same problem, and no solution seems to come up whatever I do about it.

**Comment by haloharry** [comment]
COME ON ;( am having the same problem

**Comment by Wolcrez** [comment]
Oh sorry. xD 

Install ffmpeg folder inside the folder bot. Like this: http://prntscr.com/akqbys 

sorry for my english ;-;

**Comment by Kwoth** [comment]
You need to download and extract ffmpeg to a location, and then add that location to PATH environment variable. (this tutorial is old but watch the ffmpeg part)

https://www.youtube.com/watch?v=x7v02MXNLeI around 6:40
