### ISSUE TITLE
[Feature Request] Nadeko says with TTS who entered the voice channel

### ISSUE THREAD

**Issue by rafaelbqm** [Kwoth/NadekoBot#831]
One thing that would be awesome to do is to Add an option to Nadeko always say when someone enters, leaves or changes voice channels with the TTS on discord.
I know that nadeko already have an option called ".voicepresence" , but we can't edit the string she says with /tts to announce who entered and who leaves the channel but My suggestion is just to type on the text chat with /TTS %user% entered "Name of voice channel" . When someone enters any voice channel.

This would be very nice because Discord actually doesn't have any option and this is very common with Teamspeak users , and also , looking for other bots that have this option and I couldn't find any.

Thank you and I hope my suggestion is good. Nadeko is awesome , great work!

**Comment by Taknok** [comment]
The diference with TS and Discord is that voice and text channels are linked in TS. Disord allows you too speak with some people and write to many others (or less). The problem with /tts is that you need to be in the same text-channel to heard the message. So if Nadeko post the /tts announce in a general channel (compared to v+t channels), maybe members will be bored from knowing someone is joinning this voice-channel (and it will be the apocalypse in big servers). The bot could post /tts it in v+t channels but personnaly when I have a mic i'm in a general text-channel cause I'm already speaking with the others :/ . Maybe I'm missing a way to do notify all users in voice-channel regardless their text-channel, tell me if you find one :). 
(or v+t /tss is okay ?)

**Comment by rafaelbqm** [comment]
In my server , (wich is a small server with around 20 people max) , we have just one general chat and the rest are just voice channels , and this would be ok for everyone since the movement of people is low but Maybe you can change where do you want to nadeko use tts. In big servers this would be a nightmare for sure but maybe adding the option to turn on and off , or to toggle in some specific channel (like .voicepresence already works) could be a solution? 

I'm sorry but I really don't understand how nadeko works (I'm a beginer in computer science right now) 
she works great in my server with greeting messages and other commands. This option that I suggested is something that most people on my server wants (since they came from an old TS server).

This option on Teamspeak is actually tied within the client (I think) , because when someone joins the channel , the client says "User joined your channel" , and this "mod" changes it to text-to-speech.

Maybe someday Discord adds this option , instead of the sound fx of someone entering or leaving the channel you could use tts. Right now , the only way is to have a bot doing this work. 

Researching I found that other bot has this function , but he's currently offline (Sirbrobot).

**Comment by Taknok** [comment]
Yep maybe an option to the command to choose just in actual text-channel or in v+t channels, that waiting the perfect way to /tts only the people wanted (DM people don't work :/)

**Comment by Kwoth** [comment]
👌
