### ISSUE TITLE
.asar not adding roles to .lsar

### ISSUE THREAD

**Issue by jopfan** [Kwoth/NadekoBot#835]
I type in .asar Rolename and check to see if it is added by typing in .lsar but I keep getting the message that there are 0 self assignable roles. All of my bots have Managing Roles enabled and are in a higher rank than the role I'm trying to add. What's happening?

**Comment by Kwoth** [comment]
![image](https://cloud.githubusercontent.com/assets/2537696/20810598/91ac8992-b80a-11e6-93d0-0706c7174bd5.png)
works for me
