### ISSUE TITLE
.calc can't do powers anymore

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#836]
`.calc` seems to be incapable of doing powers correctly now. 😛 

![calc](http://i.imgur.com/QvolV2h.png)

30^1.1 is actually 42.15 (rounded) and 100^1.1 is 158.49 (rounded). Not sure where the problem lies...but it used to calculates these just fine. 😄

**Comment by Kwoth** [comment]
use `pow(x,y)`, i looked at the .calc code and now my eyes are bleeding.
![image](https://cloud.githubusercontent.com/assets/2537696/20810828/9bce4b08-b80b-11e6-8a13-0a9a4fa7651d.png)

**Comment by xnaas** [comment]
Yikes. Maybe don't close this and plan to fix it later...? 😄

**Comment by Kwoth** [comment]
@DragonOverlord

**Comment by Kwoth** [comment]
@appelemac

**Comment by xnaas** [comment]
@Kwoth re-open this. 😛
