### ISSUE TITLE
NadekoBot not compatible with .Net Core 1.1?

### ISSUE THREAD

**Issue by HanSeoulOh** [Kwoth/NadekoBot#837]
The guide for Mac OSX links to .Net Core 1.1.0 rather than 1.0.0 and it doesn't work when running NadekoBot. Alternatively, is there a link to the .Net Core 1.0.0 .pkg install anywhere? Thanks.

I have found a link to the download for .Net Core 1.0.2 which works, for anyone who needs it in the future: https://go.microsoft.com/fwlink/?LinkID=831679

**Comment by Kwoth** [comment]
Follow the guide again. Both stable and latest releases require you to have .net core 1.1

If you are running it with 1.0, that means you're on 1.0 branch (several days old)

**Comment by Kwoth** [comment]
Oh my bad, mac guide wasn't updated yet

**Comment by samdivaio** [comment]
I have and it links to dotnet core 1.1 https://go.microsoft.com/fwlink/?LinkID=835011 not sure why you had to use dotnet 1.0 for the latest build 🤔

**Comment by Kwoth** [comment]
make sure you're following the correct guide from here http://nadekobot.readthedocs.io/

**Comment by HanSeoulOh** [comment]
I think I used this to install NadekoBot which may have given me an outdated version (found under Alternative Method to install Nadeko)

`cd ~ && curl -L https://github.com/Kwoth/NadekoBot-BashScript/raw/master/nadeko_installer.sh | sh`
