### ISSUE TITLE
~lolban

### ISSUE THREAD

**Issue by Senor-Oso** [Kwoth/NadekoBot#84]
This command is not working and pulls up the following error https://gyazo.com/d54046bd740d1ec0a481c5d30a6bdbee

**Comment by Kwoth** [comment]
This is extremely weird. It works on my PC just fine, but doesn't work on the server. However ~lolchamp works on the server too (and uses same API key). 

Have no idea what could be the cause except if champion.gg banned my IP from using that API endpoint, which seems unlikely.

**Comment by Kwoth** [comment]
ok, seems champion.gg disabled it until next patch, nothing i can do, thanks for the report anyway.

It will just start working again at one point
