### ISSUE TITLE
Problem with 

### ISSUE THREAD

**Issue by biguest** [Kwoth/NadekoBot#85]
The thing is as follows: when I try getting a music from anywhere (youtube or soundcloud doesn't matter), it'll say: _"Nothing was buffered, try another song and check your GoogleApikey."_
But I really did check everything. I executed every part of the installation and setup according to the ComprehensiveGuide. 
Thanking you in advance.

**Comment by Kwoth** [comment]
Open new cmd window, type in `ffmpeg`, if it says command not found, then you didn't setup your ffmpeg correctly. If it shows the ffmpeg, then you didn't setup your google api correctly.

Third, least likely thing, is that maybe the song you are trying is blocked or has age verification. Try several different songs.

make sure to follow the video tutorial 
https://www.youtube.com/watch?v=x7v02MXNLeI

**Comment by biguest** [comment]
Thank you again for the reply and for this awesome bot :)
