### ISSUE TITLE
safebooru links no longer working

### ISSUE THREAD

**Issue by nekonyuu** [Kwoth/NadekoBot#852]
Hello !

It seems safebooru just got updated lately, replacing all the images' links by "protocol-less" links to be http/https compatible.

As a result, Nadeko's outputting the link as-is, without any protocol, which breaks, for example : 

```
//safebooru.org//images/long-hash.jpg
```

**Comment by Kwoth** [comment]
0.9 will remain broken, this has already been fixed in 1.0
http://nadekobot.readthedocs.io/en/latest/

**Comment by nekonyuu** [comment]
oh, thanks for the info
