### ISSUE TITLE
Multi-Language

### ISSUE THREAD

**Issue by DaYWhiTe** [Kwoth/NadekoBot#856]
Add Multi-Language system,please.

**Comment by fkndean** [comment]
It's being worked on
![image](https://cloud.githubusercontent.com/assets/20934051/20890729/eefe865e-bad5-11e6-8e13-4e9f3da088d1.png)

**Comment by DaYWhiTe** [comment]
How ?

**Comment by DaYWhiTe** [comment]
Okay, I am waiting

**Comment by Kwoth** [comment]
#36
