### ISSUE TITLE
[Error] Docker Nadeko Disconnect

### ISSUE THREAD

**Issue by liljayyyy** [Kwoth/NadekoBot#869]
I'm not sure if this is due to the server of cause by the bot itself.

After this error appear, Nadeko rejoined the voice channel and any music queued or playing are stop and cleared and the music commands will not function properly.

Severity: ErrorExceptionMessage: Connection lostMessage: Disconnected

Also when Nadeko is not in a voice channel, if the command !!lq is used, it'll also cause the music module commands to start not working properly.

Looking for some help :)

http://puu.sh/sJ95h/65270141e2.png

**Comment by Kwoth** [comment]
Please update to 1.0, check the updating guide if you want to preserve your data. There is no docker for 1.0 atm.

http://nadekobot.readthedocs.io/en/latest/

**Comment by liljayyyy** [comment]
@Kwoth any idea when it'll update on docker?

**Comment by Kwoth** [comment]
same docker - never, 0.9 and 1.0 are not compatible.

New docker image for 1.0 is planned but there are technical difficulties

**Comment by liljayyyy** [comment]
@Kwoth where can i find the permission settings file in the new version ? ;o

And the new version is so neat !! Keep up the great work :>
