### ISSUE TITLE
embedded links not being detected by Nadeko?

### ISSUE THREAD

**Issue by RenimC** [Kwoth/NadekoBot#871]
for some reason I cannot add quotes if it embeds an image or a youtube video, for images at the very least i can take a new one and it works, but trying to add a image that has already been embedded in the server just doesn't work, no error on nadeko's side aswell. it just can't read the message.

it can't read youtube links at all either. so that means the music side of the bot doesn't work half the time.

**Comment by Kwoth** [comment]
i shall look into it

**Comment by Kwoth** [comment]
can't reproduce anymore, can you give a concrete example?
