### ISSUE TITLE
[Error] Consistent bot disconnect and instant reconnect.

### ISSUE THREAD

**Issue by nineBreaker** [Kwoth/NadekoBot#872]
Noticed nadeko has been disconnecting and instantly reconnecting - leaving and joining server. Usually being run with autoplay; this causes the current song to either restart or skip. 

Bot exe displays there lines:

Severity: ErrorExceptionMessage: Connection lostMessage: Disconnected
Severity: WarningExceptionMessage: -Message: Unknown Opcode: 8

Is this just a server issue or is there something I can do to fix it?

**Comment by Kwoth** [comment]
Update to 1.0 please

http://nadekobot.readthedocs.io/en/latest/

There is upgrading guide on the side. If you have no important settings, just follow the guide for your platform (you can't update 0.9 to 1.0 directly)

**Comment by nineBreaker** [comment]
Hey, thanks for the reply. I saw a similar thread in the closed section.

> Update to 1.0 please

I don't have windows 8, is there any way I can still run the bot?

**Comment by Kwoth** [comment]
Get a virtual machine with windows 8 or linux
