### ISSUE TITLE
Running on Raspberry Pi?

### ISSUE THREAD

**Issue by Thingon** [Kwoth/NadekoBot#875]
Is it possible to run NadekoBot on a raspberry pi? Sadly, dotnet isn't supported.

**Comment by Kwoth** [comment]
i don't think it is until this issue is resolved

https://github.com/dotnet/coreclr/issues/3977

**Comment by neyromant** [comment]
I am also interested in launching on the .net core Raspberry Pi dotnet/core#140

**Comment by Ezir** [comment]
There have been some [recent developments](https://stevedesmond.ca/blog/net-core-on-arm) in running dotnet on ARM processors, not sure if that makes it possible to run Nadeko on a RPi or not, but it's progress.
