### ISSUE TITLE
Problem installing Nadeko 1.0

### ISSUE THREAD

**Issue by Selviorn** [Kwoth/NadekoBot#877]
Upon trying to update to NadekoBot 1.0 I come across a bizarre issue. Installing the latest stable build provided by the NadekoInstaller.Bat file goes as normal, until I am prompted to continue and I am informed "The Batch File Cannot Be Found"
After this, when trying to run NadekoBot through the installer, I am given an upwards of 40 errors about an unsupported version of .Net framework.

I am running Windows 8.1 fully updated, and was able to run 0.9 without a problem, and previously was able to run Nadeko 1.0 before needing to perform a system restore to fix some issues with a few hardware drivers. I am unsure how to proceed or exactly what the problem is, as the error message appears nonsensical to me, claiming a .Net version of 1.3 or something to that effect. Any advice would be greatly appreciated. I am not sure if this is user error from something I've overlooked, or if something went wrong with my .net when I went through my System Restore. I've installed all prerequisite files listed on the Windows Guide to install and run NadekoBot.
![1](https://cloud.githubusercontent.com/assets/24496893/21075370/28dbed74-bede-11e6-9501-cff3bdfb1a40.png)
![2](https://cloud.githubusercontent.com/assets/24496893/21075371/28dc70b4-bede-11e6-981b-7f931d2ca4e3.png)
![3](https://cloud.githubusercontent.com/assets/24496893/21075372/28df60ee-bede-11e6-960c-d469d73254f9.png)

**Comment by Kwoth** [comment]
No idea, try reinstalling .net core (http://dot.net)

**Comment by Selviorn** [comment]
After undoing the system restore, the issue seemed to be fixed, though installing still yields the "The Batch File could not be found." Program runs fine despite this. 
Unsure of what exactly caused the system to restore to damage the .net framework. Problem has been solved. Sorry for the bother on an issue beyond your control.
