### ISSUE TITLE
Music bot not working.

### ISSUE THREAD

**Issue by BabyGeezus** [Kwoth/NadekoBot#88]
I request a song, It finds the song, buffers the song, says it plays the song when it really isn't and then finishes instantly I look at the CMD and it says that it tried it 4 times, It didn't work - check your API key or a new song.. I have tried a new song and I checked the API key everything looks fine.. Any tips on how to fix this?

**Comment by Kwoth** [comment]
You didn't set her up correctly. Check out the #85

**Comment by BabyGeezus** [comment]
Oh duh.. I moved the folder without changing the path. Thanks!
