### ISSUE TITLE
Changes of some files can't be seen in the bot

### ISSUE THREAD

**Issue by justinkruit** [Kwoth/NadekoBot#880]
Yes. Me.

Now I got yet another problem. It is now successfully grabbing it from my GitHub repo. Yet now, when I start the bot, some changes just don't get picked up. For example, I've changed some values of .stats, no problem, and you can see that in the bot. But I've also made changes in BotConfig.cs for some more lines in -help, but for some reason, they aren't showing in the bot. The files on the vps are correct tho, and have the changes. Any suggestions this time?

**Comment by Kwoth** [comment]
We don't support you changing source or where the bot installs from. You're on your own.
