### ISSUE TITLE
Nadeko wont lissen to my commands but will to my friends?

### ISSUE THREAD

**Issue by patrick508** [Kwoth/NadekoBot#881]
So i'm an admin on the server and nadeko worked fine for the last few days, but suddenly none of my commands seem to work. Things like >pick, >cleverbot -help. Nothing works. My friends can still do whatever they want. We did spam some commands, but we all did and only for me it seemed to stop working

**Comment by Kwoth** [comment]
you got blacklisted, whats your id?

**Comment by patrick508** [comment]
Noo, dont do it!#0961

Thats my full name.

**Comment by patrick508** [comment]
Thanks for getting me of the Blacklist.
