### ISSUE TITLE
Can't invite Bot to server.

### ISSUE THREAD

**Issue by Scuzzyexe** [Kwoth/NadekoBot#883]
I am doing the download set up and when it comes to copying the link to invite the bot to the server I want it in that link doesn't work at all. It gives me this on my screen: http://prntscr.com/di8jt4

Please help :(
I tried this awhile ago when I made the bot but it's been awhile since so I can't remember how I made it work but I can't this time and my old bot is long gone so I'm starting from a clean slate. Everything works perfectly (as far as I can see in code) I just can't make it to the discord server because the link is busted for me. Any help or suggestions is greatly appreciated. Thanks (:

**Comment by samdivaio** [comment]
I am guessung you have "Require OAuth2 Code Grant" checked, thats right below "Public Bot" option, so uncheck that if you don't have checked then you are just using incorrect link.

**Comment by phantom10152** [comment]
Bot+requires+code+grant.
help

**Comment by phantom10152** [comment]
and it checked off
