### ISSUE TITLE
Nobody in the server can use !m commands?

### ISSUE THREAD

**Issue by xLuckyCharm** [Kwoth/NadekoBot#89]
It's just as the title says, there is no response whatsoever, could you please help me with this?

**Comment by Kwoth** [comment]
Music is disabled on nadekobot, she is on too many servers. invite HaNadeko to your server and you will be able to use them.

**Comment by xLuckyCharm** [comment]
Where can I find HaNadeko?

**Comment by Kwoth** [comment]
On our server. Invite link is in the readme
