### ISSUE TITLE
Nadeko connection issues I think

### ISSUE THREAD

**Issue by ScaryPandas** [Kwoth/NadekoBot#893]
Recently while using NadekoBot I have started to have some issues with it. It randomly pops up messages such as these " https://gyazo.com/f9db9a492077595eb92730d41d23d8e8 " and then when I am playing music, the bot randomly puts another really long message, leave the channel and join back but will not be able to play music or any commands for that matter until I restart it.

P.S: I would get a picture of the really long message but it happens very randomly and I seem to not be able to get it again today while making this post.

**Comment by samdivaio** [comment]
Upgrade to Nadeko 1.0
