### ISSUE TITLE
Problem when downloading NadekoBot and putting it into Visual Studio.

### ISSUE THREAD

**Issue by NGTmeaty** [Kwoth/NadekoBot#90]
[Failure] Could not find file 'C:\Users\S\Desktop\Nadeko\NadekoBot-master\NadekoBot\Commands\FilterWordsCommand.cs'.
[Failure] Could not find file 'C:\Users\S\Desktop\Nadeko\NadekoBot-master\NadekoBot\Commands\StreamNotifications.cs'.

**Comment by Kwoth** [comment]
Remove them from the project, they are uncommited files. Stream notifications are about to be commited though. Remove Filter words command. and resync the project in 2 minutes

**Comment by NGTmeaty** [comment]
Thanks!
