### ISSUE TITLE
Starting Problem

### ISSUE THREAD

**Issue by Psykonic** [Kwoth/NadekoBot#901]
I updated to v1.0 today, but whenever I try to start the bot, this happens:

Project Discord.Net (.NETStandard,Version=v1.3) was previously compiled. Skippin
g compilation.
Project Discord.Net.Commands (.NETStandard,Version=v1.3) was previously compiled
. Skipping compilation.
Project NadekoBot (.NETCoreApp,Version=v1.0) was previously compiled. Skipping c
ompilation.
19:40:47 NadekoBot | Starting NadekoBot v1.0-rc2
19:40:47 ShardedDiscordClient | Shard #0 initialized.
19:40:47 ShardedDiscordClient | Shard #0 logged in.
19:40:48 ShardedDiscordClient | Shard #0 FAILED CONNECTING.
19:40:48 ShardedDiscordClient | Shard #0 FAILED CONNECTING TWICE.
19:40:48 ShardedDiscordClient | System.PlatformNotSupportedException: The WebSoc
ket protocol is not supported on this platform.
   at System.Net.WebSockets.WebSocketValidate.ThrowPlatformNotSupportedException
()
   at System.Net.WebSockets.WebSocketHandle.CheckPlatformSupport()
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at Discord.Net.WebSockets.DefaultWebSocketClient.<ConnectInternalAsync>d__24.
MoveNext() in C:\Users\-----------\Desktop\Games\Nadeko\NadekoBot\discord.net\src\
Discord.Net\Net\WebSockets\DefaultWebsocketClient.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.Net.WebSockets.DefaultWebSocketClient.<ConnectAsync>d__23.MoveNext
() in C:\Users\-----------\Desktop\Games\Nadeko\NadekoBot\discord.net\src\Discord.
Net\Net\WebSockets\DefaultWebsocketClient.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.API.DiscordSocketApiClient.<ConnectInternalAsync>d__22.MoveNext()
in C:\Users\-----------\Desktop\Games\Nadeko\NadekoBot\discord.net\src\Discord.Net
\API\DiscordSocketApiClient.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.API.DiscordSocketApiClient.<ConnectInternalAsync>d__22.MoveNext()
in C:\Users\-----------\Desktop\Games\Nadeko\NadekoBot\discord.net\src\Discord.Net
\API\DiscordSocketApiClient.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.API.DiscordSocketApiClient.<ConnectAsync>d__21.MoveNext() in C:\Us
ers\-----------\Desktop\Games\Nadeko\NadekoBot\discord.net\src\Discord.Net\API\Dis
cordSocketApiClient.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<ConnectInternalAsync>d__70.MoveNext
() in C:\Users\-----------\Desktop\Games\Nadeko\NadekoBot\discord.net\src\Discord.
Net\WebSocket\DiscordSocketClient.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.WebSocket.DiscordSocketClient.<ConnectInternalAsync>d__70.MoveNext
() in C:\Users\-----------\Desktop\Games\Nadeko\NadekoBot\discord.net\src\Discord.
Net\WebSocket\DiscordSocketClient.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<ConnectAsync>d__69.MoveNext() in C:
\Users\-----------\Desktop\Games\Nadeko\NadekoBot\discord.net\src\Discord.Net\WebS
ocket\DiscordSocketClient.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.ShardedDiscordClient.<ConnectAsync>d__57.MoveNext() in C:\Users\
-----------\Desktop\Games\Nadeko\NadekoBot\src\NadekoBot\ShardedDiscordClient.cs:l
ine 96
19:40:48 ShardedDiscordClient | Shard #0 downloaded 0 users.
19:40:48 NadekoBot | Connected
19:40:48 CommandHandler | No owner channels created! Make sure you've specified
correct OwnerId in the credentials.json file.

Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at NadekoBot.Services.Impl.StatsService.<Print>d__29.MoveNext() in C:\Users\H
IEN TRAN\Desktop\Games\Nadeko\NadekoBot\src\NadekoBot\Services\Impl\StatsService
.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.NadekoBot.<RunAsync>d__43.MoveNext() in C:\Users\-----------\Deskt
op\Games\Nadeko\NadekoBot\src\NadekoBot\NadekoBot.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__44.MoveNext() in C:\Users\HIEN TR
AN\Desktop\Games\Nadeko\NadekoBot\src\NadekoBot\NadekoBot.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.Program.Main(String[] args) in C:\Users\-----------\Desktop\Games\
Nadeko\NadekoBot\src\NadekoBot\Program.cs:line 6
NadekoBot has been succesfully stopped, press any key to close this window.

**Comment by Kwoth** [comment]
You're on windows7/ windows server 2008, you can't run 1.0. Your best bet is installing newer OS in a VM and running the bot from there.
