### ISSUE TITLE
Having a bit of a weather problem

### ISSUE THREAD

**Issue by LeafSenpai** [Kwoth/NadekoBot#902]
searching for weather does nothing...

Project Discord.Net (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Discord.Net.Commands (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project NadekoBot (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
15:07:00 NadekoBot | Starting NadekoBot v1.0-rc2
15:07:00 ShardedDiscordClient | Shard #0 initialized.
15:07:03 ShardedDiscordClient | Shard #0 logged in.
15:07:07 ShardedDiscordClient | Shard #0 connected.
15:07:07 ShardedDiscordClient | Shard #0 downloaded 51 users.
15:07:07 NadekoBot | Connected
15:07:08 CommandHandler | Created 2 out of 2 owner message channels.

Author: [Kwoth#2560] | Library: [Discord.Net]
Bot Version: [1.0-rc2]
Bot ID: 258819510163865601
Owner ID(s): 61332231909548032, 147201250545369088
Uptime: 0 days, 0 hours, 0 minutes
Servers: 1 | TextChannels: 11 | VoiceChannels: 6
Commands Ran this session: 0
Messages: 0 [0.00/sec] Heap: [11.52 MB]
15:07:28 CommandHandler | Command Errored after 2.2329098s
        User: Leaf Senpai#1523 [61332231909548032]
        Server: Kupo? [239141146016612352]
        Channel: bottesting [253566666636656641]
        Message: ~we newcastle nsw
        Error: Error parsing Infinity value. Path '', line 1, position 2.

**Comment by Kwoth** [comment]
fixed in latest.
