### ISSUE TITLE
Nadekobot disconnect and reconect

### ISSUE THREAD

**Issue by Grabthesky** [Kwoth/NadekoBot#904]
l
Buffering successfull
Prebuffering successfully completed in 00:00:02.1872195
Buffering done.
Severity: ErrorExceptionMessage: Connection lostMessage: Disconnected
l
Severity: WarningExceptionMessage: -Message: Unknown Opcode: 8
Severity: ErrorExceptionMessage: Connection lostMessage: Disconnected
Severity: ErrorExceptionMessage: Connection lostMessage: Disconnected
Severity: WarningExceptionMessage: -Message: Unknown Opcode: 9
Severity: ErrorExceptionMessage: Connection lostMessage: Disconnected

**Comment by Kwoth** [comment]
please update to 1.0
http://nadekobot.readthedocs.io/en/latest/

There is upgrading guide on the left. 0.9 is no longer supported 

Sorry for the inconvenience
