### ISSUE TITLE
Custom Currency Name, Issues

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#908]
So there's an issue with using your own currency name...

![img](http://i.imgur.com/SQncHnx.png)

Whenever the plural of the currency is used, it uses Nadeko Flowers instead of the currency name. Singular works fine.

**Comment by Garnet-D** [comment]
Did remember change "CurrencyPluralName" too in the BotConfig table of NadekoBot.db?

**Comment by xnaas** [comment]
Migrations OP. ¯\\\_(ツ)_/¯
