### ISSUE TITLE
Fising a ton of error when i pull from git then build

### ISSUE THREAD

**Issue by LawlyPopz** [Kwoth/NadekoBot#91]
[Link](http://pushzz.xyz/i/8cf74.png) to a screen shot of bugs!

**Comment by senahf** [comment]
Probably need to attach Discord.Net libs as well as restore nuget packages.

**Comment by LawlyPopz** [comment]
Kwoth fixed it for me

**Comment by Kwoth** [comment]
@senahf it wasn't that easy, there was something awfully wrong. I followed same steps as he did, we were on live call, and it worked for me not for him. 

We fixed it by building discord.net solution and referencing the dlls, and removing project references.

>.<
