### ISSUE TITLE
i try an nsfw command this happens

### ISSUE THREAD

**Issue by HarambetheGreat** [Kwoth/NadekoBot#912]
:warning:️ Permission number #1 ;sm nsfw disable  is preventing this action.

**Comment by samdivaio** [comment]
Create a **NEW** role called **Nadeko**, give it to yourself and type `;sm nsfw enable`

**Comment by HarambetheGreat** [comment]
thanks

**Comment by Garnet-D** [comment]
Do ;lp to check perms then ;rp <Id> to for example remove the permission disabling NSFW. You can also add ;cm nsfw enable #channel to enable NSFW on specific channels

**Comment by HarambetheGreat** [comment]
You need the nadeko role in order to use permission commands.
Thats what it says everytime i try to do what you recommended

**Comment by Garnet-D** [comment]
"Create a NEW role called Nadeko, give it to yourself" do this as Samdivaio says. Then do what i recommended

**Comment by HarambetheGreat** [comment]
thanks it worked now
