### ISSUE TITLE
Can't download the NadekoInstaller.bat file

### ISSUE THREAD

**Issue by soKuudere** [Kwoth/NadekoBot#913]
Whenever I try to download the NadekoInstaller.bat , it comes up was a NadekoInstaller.bat.txt file and when I just delete the .txt part, the program doesnt work. whenever I open it, it just closes right away before I can even see or do anything.

**Comment by Kwoth** [comment]
you're on windows 7 probably?

**Comment by soKuudere** [comment]
I'm on windows 10

**Comment by Kwoth** [comment]
Try opening powershell, navigating to the folder where it is and executing it from commnd line, just by typing it's name

**Comment by soKuudere** [comment]
![image](https://cloud.githubusercontent.com/assets/24687111/21372713/372a8b1a-c6d6-11e6-8a00-5f69806dab68.png)

**Comment by Kwoth** [comment]
for some reason choice is not working on your OS

@samdivaio can you look into this?

**Comment by soKuudere** [comment]
Okay I fixed it, the PATH was wrong and I to change the environment

**Comment by soKuudere** [comment]
Now i'm having problems with dotnet. I downloaded the SDK 1.1 version of it but it still undetected.

**Comment by samdivaio** [comment]
Screenshot

**Comment by samdivaio** [comment]
check if you have this folder `C:\Program Files\dotnet\sdk\1.0.0-preview2-1-003177`

**Comment by soKuudere** [comment]
![image](https://cloud.githubusercontent.com/assets/24687111/21374833/c67e08c2-c6e6-11e6-93e4-e1086c6d532a.png)
as you can see in the photo i have it downloaded but I don't see it in my program files for some reason

**Comment by soKuudere** [comment]
![image](https://cloud.githubusercontent.com/assets/24687111/21374860/ee733488-c6e6-11e6-8b2f-8c3e9b3cef95.png)

**Comment by soKuudere** [comment]
![image](https://cloud.githubusercontent.com/assets/24687111/21374866/f5e0e698-c6e6-11e6-8a14-e4043bffcfd0.png)

**Comment by soKuudere** [comment]
I even have the Visual studio so i don't know why it's not registering

**Comment by Kwoth** [comment]
you need .net core 1.1 not 1.0 (latest, not lts on the download page)
