### ISSUE TITLE
Konachan Not working for NSFW

### ISSUE THREAD

**Issue by KawaiiBusinessCat** [Kwoth/NadekoBot#914]
When I use ~hentaibomb, Konachan links don't work.
It doesn't have an http:// before it.

Example:
~hentaibomb
http://simg4.gelbooru.com/images/*removed*

http://danbooru.donmai.us/data/*removed*

//konachan.com/image/*removed*

https://files.yande.re/image/*removed*

**Comment by Garnet-D** [comment]
Issue is known and will be fixed in an upcoming release as far as I know
