### ISSUE TITLE
[Feature Request] Local playlists through m3u

### ISSUE THREAD

**Issue by cookx** [Kwoth/NadekoBot#917]
Right now, the only way to get Nadeko to play local files in succession is to play a whole folder.

Would it be possible to add support for the m3u format so people can make playlists instead of moving files around for different playlists? 

Thanks so much for your fantastic work!

**Comment by Kwoth** [comment]
make a m3u, then upload it somewhere and get a direct link to it, then use `!!ra link-to-m3u` to queue it.
