### ISSUE TITLE
Stream Status Change Link Not Clickable

### ISSUE THREAD

**Issue by FierceFrankie** [Kwoth/NadekoBot#92]
When a streamer's status changes online, the closing bracket causes the link to be incorrect.
![nadekobug](https://cloud.githubusercontent.com/assets/848317/13764477/2bb019e2-ea15-11e5-803b-26ef457c5ff7.png)

**Comment by Kwoth** [comment]
yep, mistake on my part, it has already been reported and fixed (will be fixed in the next release)
