### ISSUE TITLE
Can't build or run Nadeko after the function for `~define` was added.

### ISSUE THREAD

**Issue by gh0s7w4r10rd** [Kwoth/NadekoBot#921]
Error **CS0246** in `NadekoBot/src/NadekoBot/Modules/Searches/Searches.cs` in `(488,58)`: The type or namespace name 'DefineModel' could not be found (are you missing a using directive or an assembly reference?).
See https://msdn.microsoft.com/en-us/library/w7xf6dxs.aspx for details on the error.

**Comment by Kwoth** [comment]
For some reason, git decided not to push the model, i fixed it right now
