### ISSUE TITLE
[Feature Request] ".lcr all" include IDs

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#922]
Please make it so `.lcr all` includes IDs with each response.
Example:
```
{
    "Trigger": "!!bread",
    "Responses": [{
      "text":"https://i.imgur.com/gD804x2.jpg",
     "ID": 120}
    ]
  },
```
Warning: That image is NSFW. Open at your own risk. ¯\\\_(ツ)_/¯

As for formatting...I don't know how you'd need to set it, just offering a random (probably shitty) example.

**Comment by Kwoth** [comment]
done babe
