### ISSUE TITLE
move safebooru/hentai to https://ibsear.ch

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#924]
https://ibsear.ch

**Comment by Garnet-D** [comment]
The site hasn't indexed in quite a while, not a single one in all of 2016. Use search "upload>2016-01-01" to see all images after then.

**Comment by Kwoth** [comment]
O.o that's true, i did not know that. Thanks.

**Comment by Kwoth** [comment]
Guess We're out of luck then. Last uploaded image was at the end of november last year >.<

**Comment by Garnet-D** [comment]
Hope I saved you some time, though I'm also kind of saddened by this fact.
