### ISSUE TITLE
[DISCUSSION] Mono 4.6 not supported?

### ISSUE THREAD

**Issue by CheapSeth** [Kwoth/NadekoBot#925]
I am not sure how I should label this, my apologies if this is not the proper way.

So today I updated my server - it's running ArchLinux - and the update included the latest version of mono (4.6). Apparently this breaks Nadekobot, as the program returns with the following exception:

> System.Net.Sockets.SocketException:
> An address incompatible with the requested protocol was used at System.Net.Sockets.Socket..ctor 
> (System.Net.Sockets.AddressFamily addressFamily, System.Net.Sockets.SocketType socketType, 
> System.Net.Sockets.ProtocolType protocolType)

Is this normal and How can I warn other Arch users that the latest mono update breaks NadekoBot?

Many thanks.

**Comment by Kwoth** [comment]
yes, mono 4.6 breaks 0.9. But you shouldn't use 0.9 anyway. use 1.0

http://nadekobot.readthedocs.io/en/latest/
