### ISSUE TITLE
Unable to start bot on Ubuntu 14.04

### ISSUE THREAD

**Issue by arronlim13** [Kwoth/NadekoBot#926]
I tried to reinstall NadekoBot and operating system but none of them solve the problem. I also tried to install it on different operating system like Debian 8.0 and Ubuntu 16.04

http://puu.sh/t1nyx/be15681b0f.png

**Comment by Kwoth** [comment]
are you sure you're on 64bit system?

**Comment by arronlim13** [comment]
Yes, Ubuntu 14.04 x64 Minimal

**Comment by Kwoth** [comment]
No idea why would you have that issue. You must be doing something wrong. 

Follow the guide carefully from the start, don't skip any steps.

If it doesn't work, just use docker guide. That will work for sure.
