### ISSUE TITLE
Logging Fucked

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#931]
Everything I've configured related to logging is reset any time the bot is updated, rebooted, etc. *Only* stuff related to logging is affected. Nothing else.

Probably not relevant: #789 

This is reproduceable 100% of the time for me. The issue is somewhere in my `NadekoBot.db`, because if I complete wipe mine and use a default generated one, there are zero problems. My db is the result of a 0.99 migration, FWIW.

For _some_ reason, any table related to logging is wiped on reboot with my current database. `LogSettings`, `IgnoredVoicePresenceCHannels`, etc. Everything other than the `IgnoredLogChannels` table, anyway, which doesn't seem to actually do anything for me, but idk.

**Comment by xnaas** [comment]
Simpler, shorter title. ¯\\\_(ツ)_/¯

**Comment by Kwoth** [comment]
this is an issue exclusive to you, just send me your .db on discord
