### ISSUE TITLE
Fix -h

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#932]
This is currently what -h sends:

> You can use 195533879447126017modules command to see a list of all modules.
> You can use 195533879447126017commands ModuleName
> (for example 195533879447126017commands Administration) to see a list of all of the commands in that module.
> For a specific command help, use 195533879447126017h "Command name" (for example -h "!m q")
> 
> LIST OF COMMANDS CAN BE FOUND ON THIS LINK
> https://github.com/Kwoth/NadekoBot/blob/master/commandlist.md
> 
> Nadeko Support Server: https://discord.gg/0ehQwTK2RBjAxzEY

Not entirely sure what the whole `195533879447126017` thing is... 😛 

Also, that hasn't been the command list for a pretty long time. Update to http://nadekobot.readthedocs.io/en/latest/Commands%20List/ ?

**Comment by samdivaio** [comment]
Looks like your migration updated your help string,
You can fix it by simply, editing help string on your `NadekoBot.db`. The `195533879447126017` you are seeing is because of the usage of `{0}` Client ID instead of `{1}` Command Prefix and I am guessing it happens very rarely if your `config.json` has `"DontJoinServers": false,`.
The help string below is how your help string should look like.

```You can use `{1}modules` command to see a list of all modules.
You can use `{1}commands ModuleName`
(for example `{1}commands Administration`) to see a list of all of the commands in that module.
For a specific command help, use `{1}h CommandName` (for example {1}h !!q)```

**Comment by xnaas** [comment]
🤔 will give it a whirl and close this, probably, in a sec.

I have a sneaking suspicion that the migration has also caused issues like #931 for me. @Kwoth still hasn't gotten back to me after sending the database. 😛

**Comment by xnaas** [comment]
Found in the `BotConfig` table and fixed it. Thanks, fam.

**Comment by SillyBirds** [comment]
I just noticed I also have this issue... is there a particular program to use for editing the NadekoBot.db file?

**Comment by xnaas** [comment]
@SillyBirds, use http://sqlitebrowser.org

**Comment by SillyBirds** [comment]
This..... is a bit complex. Any tips for someone who is not used to these things? Where do I look?

**Comment by Kwoth** [comment]
![image](https://cloud.githubusercontent.com/assets/2537696/21576884/e1d789ae-cf42-11e6-9d46-cbe75d1aff2a.png)

**Comment by SillyBirds** [comment]
It was the db browser program that had my eyes spinning, but I managed to find what had to be edited 👍 

Thanks for the help.
