### ISSUE TITLE
"Failed resolving the link.Not a valid youtube query."

### ISSUE THREAD

**Issue by Starxyy** [Kwoth/NadekoBot#933]
After updating to 1.0 I had no issues until recently. Whenever I queue a youtube link the bot displays an error saying "Failed resolving the link.Not a valid youtube query." I tried remaking the google api but the error still appears. 
![screenshot 78](https://cloud.githubusercontent.com/assets/21966466/21579558/6c1db632-cf85-11e6-86aa-6013ba4a7eeb.png)

**Comment by xnaas** [comment]
Try getting rid of the `&` and everything after it. Should just be `https://www.youtube.com/watch?v=iq7npmYlOK8`.

**Comment by Starxyy** [comment]
I just tried it and it works now, thank you for helping. :)

**Comment by Kwoth** [comment]
Now that's odd, I'll reopen this to fix the regex

**Comment by Kwoth** [comment]
![image](https://cloud.githubusercontent.com/assets/2537696/21678673/47966a8e-d340-11e6-82f7-211290c514d4.png)
I can't recrete the issue
