### ISSUE TITLE
Currency Updates Failing

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#934]
Every few hours I'm getting this message:

> UnitConversion | Failed updating currency.

It's been happening for at least 2 days now, maybe longer.

**Comment by samdivaio** [comment]
its been there from the beginning 🤔

**Comment by xnaas** [comment]
Fascinating. Never noticed it until the past couple of days. 😮

**Comment by Kwoth** [comment]
yea that's not an issue. It actually needs just 1 update per day to function most correctly.
