### ISSUE TITLE
"Rainbow" rank.

### ISSUE THREAD

**Issue by Doyouwanttomakeacake** [Kwoth/NadekoBot#936]
`;sm Rainbow enable`
`;urainbow enable @User`
`;rrainbow enable @Rank` 
*Require* **manage roles** *permission*.
- Switch the color of the user/rank between all the color of the rainbow - 
`;rainbow x`
- Parameters : *x* in seconds (delay between switchs), default : 0.5 - 
```
;sm Rainbow enable
;urainbow enable @Ok#2752
;rainbow 1
```

I also found, [this](https://github.com/Geofed/Rainbow-Rank-for-Discord) in js.
```js
var Discord = require("discord.js");
var fs = require('fs');
var data = require("./data.json");
var options = require("./options.json");
var auth = require("./auth.json");

var afgdRole;
var i = 0;

var colours = [];
var coloursIndex = 0;

var interpolation = 1 / options.nameColourInterpolation;

var bot = new Discord.Client();

setInterval(function() {
    if (afgdRole) {
        bot.updateRole(afgdRole, {
            color: colours[coloursIndex]
        });
        coloursIndex++;
        if (coloursIndex >= colours.length) coloursIndex = 0;
    }
}, options.nameColourSpeed)

bot.on("message", function(msg) {

    if (!afgdRole) {
        console.log("for");
        while (i < 1) {
            i = i + interpolation;
            console.log("for'd " + i + " " + interpolation);
            colours.push(Number("0x" + RGBToHex(HSVtoRGB(i, 1, 1).r, HSVtoRGB(i, 1, 1).g, HSVtoRGB(i, 1, 1).b)));
        } 
        var roles = msg.channel.server.rolesOfUser(bot.user).filter(function(role) {
            return role.name === "AFGD";
        });
        afgdRole = roles[0];
    }
});

function HSVtoRGB(h, s, v) {
    var r, g, b, i, f, p, q, t;
    if (arguments.length === 1) {
        s = h.s, v = h.v, h = h.h;
    }
    i = Math.floor(h * 6);
    f = h * 6 - i;
    p = v * (1 - s);
    q = v * (1 - f * s);
    t = v * (1 - (1 - f) * s);
    switch (i % 6) {
        case 0: r = v, g = t, b = p; break;
        case 1: r = q, g = v, b = p; break;
        case 2: r = p, g = v, b = t; break;
        case 3: r = p, g = q, b = v; break;
        case 4: r = t, g = p, b = v; break;
        case 5: r = v, g = p, b = q; break;
    }
    return {
        r: Math.round(r * 255),
        g: Math.round(g * 255),
        b: Math.round(b * 255)
    };
}

RGBToHex = function(r,g,b){
    var bin = r << 16 | g << 8 | b;
    return (function(h){
        return new Array(7-h.length).join("0")+h
    })(bin.toString(16).toUpperCase())
}

bot.loginWithToken(auth.token);```

**Comment by shikhir-arora** [comment]
Indeed, there are some implementations of this. The best way is generally to have something like (using ! as prefix here) `!rainbow {interval} {role_id} {hex_code | hex_code2 | hex_code3 | etc}` Output `{rainbow_tag}` which you can use something like `!rainbow stop {rainbow_tag}` or even `!rainbow {rainbow_tag} {add more hex codes later | etc}` -- this is basically a timed, limited scripting command (with one option; changing colors).

However, the interval for the public bot would have to be 5-10 minutes at least. I've seen this done with one-minute intervals and with a bot the size of Nadeko, it will be *extremely* intense, as it changes the color of a roleID every {interval}. There was quite a heavy spike on the load of the server and it wasn't nearly as large as Nadeko.

Might be better to have that as a hosted Nadeko-command only, but I guess that ruins a lot of the novelty for many users.

**Comment by Doyouwanttomakeacake** [comment]
I like the way your command would work, it's for sure way better than mine. And I've to agree with your 5-10 minutes idea; I saw this on action with smth like 1/2s but it was a one server bot and only for one guy or so.

**Comment by shikhir-arora** [comment]
It is obviously not like music, but it's quite intense, especially when you have thousands of servers doing it. Even with 10 minutes, if even 5,000 users (fraction of Nadeko's public users) utilize the function, that's 5,000 roleID color change updates in 10 minutes -- or ~500 commands a minute, constantly just from that. And each of those has potentially 15+ color hex codes they chose, and the bot is managing all of this in a database for each `{rainbow_tag}`. So while it works, Nadeko is pretty big and that should likely end up being a self hosted feature in my opinion. 

I have something like this in my server but it's a much smaller bot, and it uses a 5 minute timeout. Indeed It's pretty cool, but for a *whole* purpose bot like Nadeko and its size I don't think it's viable. 😞

**Comment by Kwoth** [comment]
![image](https://cloud.githubusercontent.com/assets/2537696/21681100/eda9bc34-d34d-11e6-8ab6-61cf6c246a3d.png)


In the future I'll add gradient command to not make people type this much if they want a rainbow.

For now you'll have to type colors manually. here is the text from the image
```.rrc 1 "Support Staff" 00FF00 00FF1A 00FF35 00FF50 00FF6B 00FF86 00FFA1 00FFBB 00FFD6 00FFF1 00F1FF 00D6FF 00BBFF 00A1FF 0086FF 006BFF 0050FF 0035FF 001AFF 0000FF 0000FF 1A00FF 3500FF 5000FF 6B00FF 8600FF A100FF BB00FF D600FF F100FF FF00F1 FF00D6 FF00BB FF00A1 FF0086 FF006B FF0050 FF0035 FF001A FF0000 FF0000 FF1A00 FF3500 FF5000 FF6B00 FF8600 FFA100 FFBB00 FFD600 FFF100 F1FF00 D6FF00 BBFF00 A1FF00 86FF00 6BFF00 50FF00 35FF00 1AFF00 00FF00```

When I have time next time, i'll add another command, like `.rgrc 1 role ff0000>00ff00>0000ff>ff0000`
so that it automatically creates an HSV gradient

**Comment by monkyt** [comment]
How do I add these commands ???

**Comment by GRIMMboi** [comment]
how do i do this with the bot in my server?

**Comment by Kwoth** [comment]
You have to self-host.

**Comment by riobear1** [comment]
I'm sure the bot would be banned due to API abuse...
