### ISSUE TITLE
"Severity: ErrorExceptionMessage: Connection lostMessage: Disconnected"

### ISSUE THREAD

**Issue by aspectsg** [Kwoth/NadekoBot#937]
I keep getting this error message:
Severity: ErrorExceptionMessage: Connection lostMessage: Disconnected
or 
Severity: WarningExceptionMessage: -Message: Unknown Opcode: 8
This keeps happening when trying to play a song, and will randomly make the bot leave and rejoin the channel.

**Comment by Kwoth** [comment]
please update to 1.0 (separate install)
guides here
http://nadekobot.readthedocs.io/en/latest/
