### ISSUE TITLE
~autohentai keeps showing "no result found"

### ISSUE THREAD

**Issue by GameOverRage** [Kwoth/NadekoBot#939]
Even if nsfw is enabled and commands like ~hentaibomb are working, ~autohentai keeps showing "no result found", even after trying various tags and the default commandlist ~autohentai 30 yuri|tail|long_hair command. It accepts the command, waits for the given time of seconds and says "no result found" over and over again.

![no-result](https://cloud.githubusercontent.com/assets/24892530/21606398/84d848e6-d1af-11e6-9356-4dcc91b0c365.PNG)

**Comment by Kwoth** [comment]
This was fixed, But keep in mind you should check does that tag exist before using it.

**Comment by GameOverRage** [comment]
It does work fine now, but even with the recommended "~autohentai 30 yuri|tail|long_hair"-command, I'm seeing "no results found"-messages pretty often. Any way to disable that, so Nadeko just posts the pictures? I't not a command now, but maybe in the future ...?

**Comment by Kwoth** [comment]
are you sure you're updated? Autohentai should never post no results found.

**Comment by GameOverRage** [comment]
I used the discord invite link again today, don't host her myself, but there's still a "no results found" here and there.
![unbenannt](https://cloud.githubusercontent.com/assets/24892530/21748938/85ea6aca-d592-11e6-9b47-b56c0e99f715.PNG)
