### ISSUE TITLE
Your bot does not at all abide to any commands no matter what I do.

### ISSUE THREAD

**Issue by no1dead** [Kwoth/NadekoBot#94]

**Comment by CactusNugget** [comment]
Have you given the bot adequate permissions under roles?

**Comment by no1dead** [comment]
I would only assume my bot role is enough.

**Comment by CactusNugget** [comment]
I assume you have granted channel permissions for the "bot role"

**Comment by no1dead** [comment]
Yeah I have.

**Comment by CactusNugget** [comment]
Seems awfully stange.  Would like me to bring a privately hosted bot in for testing? if so,  can you private message an invite link? Cactus 🌵

**Comment by Kwoth** [comment]
Bot was either ratelimited at the time, bot has no permissions to talk, or i blacklisted a server.
