### ISSUE TITLE
Nadeko music queue doesn't work

### ISSUE THREAD

**Issue by Grabthesky** [Kwoth/NadekoBot#945]
When i use !!q to add a song to the queue most of the times doesn't add the song to the queue.

**Comment by Kwoth** [comment]
if you're on 0.9, update to 1.0, if you're on 1.0, just wait a few days and it will resolve itself, this is a recurring issue with some youtube library which mostly occurs with vevo songs. Try using less popular video LINKS of the same song (unofficial) and it will work
