### ISSUE TITLE
Broken Custom Reactions, Music Issues, Misc [v1.1.0-beta]

### ISSUE THREAD

**Issue by Foxwells** [Kwoth/NadekoBot#946]
All right, so maybe I'm just too used to v0.9.6111.2080 and have no idea how a database works, but since upgrading to 1.1.0, my bot has more or less fallen apart to a glitched mess. I'm just gonna run down the list of stuff I immediately think of. God knows there's more.

Custom reactions are broken. Just... flat out broken. I put them back in (not via migration, but through .acr), but only a handful work. ie: If you started your message with "(:", the bot would respond with "I don't know what happened, but it probably wasn't good." It now responds maybe 1 out of 4 times. There was also a command that was "@bot kill me" (don't judge), and it'd respond with a gun emoji. There was a variant which was "@bot kill %target%", and it'd respond with "%target% :gun:". This no longer works. It simply doesn't respond at all. And then, when I added "%mention%", to which it responds with some hideous emoji face, it began responding with that instead of the "kill %target%" response. In addition, the %mention% command didn't work until I had to awkwardly inject %target% into the command-- And it only works if there is a target. It doesn't work with just a mention anymore. Overall, extremely less flexible and more confusing than pre-1.0 versions.

When playing music in voice channels, the bot frequently skips (like a CD; it's not suddenly moving to a new song) through the song. The quality is reminiscent of a compressed midi and the volume jumps about. It doesn't announce when a song ends anymore, leaving me quite confused as to when a song ends. We generally don't have a queue and instead just load up a song when the old one ends. But between all the random silence and mess that is music now on top of the missing song-end announcement, it's impossible to determine when a song ends. Furthermore, it does not say when a song is skipped onto the next (which usually just empties the queue for no apparent reason), music is stopped and the queue is emptied, songs take a much longer time to buffer, and 9/10 times it doesn't even play music when I tell it to queue something. It just jams it into the queue as #1 in the playlist and does nothing.

Other issues I've noticed include that it's unable to use server emotes, the currency image displays below the explanation of ">pick" (which makes it hard for people with smaller screens to understand what's going on), it's very slow at responding to commands, the database was obnoxiously hard to locate, you can't pin the autorun/runnormal to your taskbar anymore, and... others I'm floundering on.

Let it be known that my internet speed is very fast and rarely with issue. All of these problems only came about after I upgraded to v1.1.0. If it's relevant, my laptop is a Dell Inspiron 15 and runs Win10 v1607 with all the latest updates installed. My Discord version is 0.0.296 if I located it right (I'm not sure; there's no direct way to check in-app and I don't know if the folder name updates as the app updates), and is the Desktop client.

I do like NadekoBot a lot, and I think v1.1.0 is going places. The database, while I find it sort of ridiculous that I had to install a 3rd party application and it was a very confusing application, is a lot more convenient and immediate than awkwardly poking through the scramble of files that makes up earlier versions. There's a bunch of little things within that as well that I quite liked, such as being able to change the race animals (and have it work), set a custom plural name for currency (ours is knives, which in older versions was 'knifes'), and that all the data is in one place. The format of messages was kind of startling at first, but it's overall neater than the old way. However, these issues greatly outweigh the benefits, and I'm going to be reverting back to my pre-1.x version until these things are patched. If you'd like, think of this post more as a report of issues or a review of current standings rather than an urgent "fix this" request.

Well be with you all.

**Comment by Kwoth** [comment]
It's really too long, Can you please remove any opinions/thoughts and leave with what your issues are.

**Comment by Kwoth** [comment]
1. reactions no longer accept target in trigger. `.acr hi %target% hello there` willdo what you want. (if someone types `hi kwoth` it will say `kwoth hello there`. It wouldn't be confusing if you've read the custom reaction guide http://nadekobot.readthedocs.io/en/latest/Custom%20Reactions/

2. Music skips while you queue another song/playlist. That is a known issue. Commands run in under 0.2-0.4 seconds on my PC. They take longer time on public bot (on many servers)

3. Thanks for the feedback
