### ISSUE TITLE
Music Command Issue

### ISSUE THREAD

**Issue by Jacob17256** [Kwoth/NadekoBot#947]
Hey, my friends were trying to use the music commands for Nadeko when they came across an error, the bot displays to me this message.

`Failed resolving the link.Length cannot be less than zero.`

Don't know if this is on my end or the bots, thanks for the great bot though!

**Comment by Jacob17256** [comment]
It doesn't appear to be all videos after research, most music is blocked but some meme videos and stuff are working just fine.

**Comment by samdivaio** [comment]
Known issue with Google API using EU IP addresses, you can wait for it to fix itself or use US vpn.

**Comment by Jacob17256** [comment]
Ah right okay, I think I'll try and wait for it to fix itself, thanks!

**Comment by DaYWhiTe** [comment]
![adsiz](https://cloud.githubusercontent.com/assets/21060067/21743552/1369ca3e-d50d-11e6-8e0b-e1e61ab75cf7.png)

**Comment by Vanillaah** [comment]
yeah same issue

**Comment by Vanillaah** [comment]
anyone got a good reliable way to use an US VPN?

**Comment by savinna** [comment]
this is not google api problem , i try US VPN , the same issue~
USA VPN: 206.108.55.26
user: test  pass: test 
you can try .....
issue still ~

**Comment by Vanillaah** [comment]
oh alright, idk if kwoth knows how and what

**Comment by Vanillaah** [comment]
seems he/she did not respond to this issue yet

**Comment by zhuoyang** [comment]
same issue here

**Comment by xKuro** [comment]
Same issue here ! :/

**Comment by shikhir-arora** [comment]
The length error seems to be a regex problem with handling certain outputs when passed to YouTube's v3 Data API.

Cleaning things up with that: 

`@"(?:youtube\.com\/\S*(?:(?:\/e(?:mbed))?\/|watch\?(?:\S*?&?v\=))|youtu\.be\/)([a-zA-Z0-9_-]{6,11})"`

Some tests (see _"table"_ ) for link ID separation -
[http://regexstorm.net/tester?p=%28%3f%3ayoutube%5c.com%5c%2f%5cS*%28%3f%3a%28%3f%3a%5c%2fe%28%3f%3ambed%29%29%3f%5c%2f%7cwatch%5c%3f%28%3f%3a%5cS*%3f%26%3fv%5c%3d%29%29%7cyoutu%5c.be%5c%2f%29%28%5ba-zA-Z0-9_-%5d%7b6%2c11%7d%29&i=http%3a%2f%2fwww.youtube.com%2fwatch%3fv%3dpapuvlVeZg8%0d%0ahttps%3a%2f%2fyoutu.be%2fpapuvlVeZg8%3ft%3d2%0d%0ahttps%3a%2f%2fwww.youtube.com%2fwatch%3fv%3d34Na4j8AVgA%0d%0ahttps%3a%2f%2fyoutu.be%2f34Na4j8AVgA%0d%0ahttps%3a%2f%2fwww.youtube.com%2fwatch%3fv%3dXFkzRNyygfk%26%0d%0ahttp%3a%2f%2fyoutube.com%2fwatch%3fv%3ddzf2o_bHjtI%0d%0ahttps%3a%2f%2fyoutu.be%2fdzf2o_bHjtI%3ft%3d17%0d%0ahttps%3a%2f%2fwww.youtube.com%2fembed%2fdzf2o_bHjtI%0d%0ahttp%3a%2f%2fyoutu.be%2fdzf2o_bHjtI](fully clean regex output for any YouTube ID)

**Changes:** https://github.com/Kwoth/NadekoBot/compare/dev...shikhir-arora:patch-3?diff=split&expand=1&name=patch-3

_Tested_ EU IP (two outgoing/host server IP's hosted in Germany & Netherlands, API key from EU account, requests made with Discord voice channel in Central EU)

Variety of inputs: complex keywords with special characters, VEVO YouTube URL's, http/https, shortcode, many plaintext keyword lookups for both "obscure" and mainstream/licensed videos, etc. Have not had a single issue.

**Comment by Kwoth** [comment]
Can you guys update to latest version and tell me if it's fixed? @shikhir-arora made a PR which allegedly fixes this issue.

**Comment by DaYWhiTe** [comment]
Yeah fixed, it's working

![nadekobot](https://cloud.githubusercontent.com/assets/21060067/21848899/ba8b659c-d80b-11e6-85db-7edd60cc56cc.png)

**Comment by J1NN1K** [comment]
did i updated it wrong, because i still have this error? i started NadekoInstaller and pressed 1 to update to latest version but it still dont fixed it. tell me if i did something wrong.

**Comment by Kwoth** [comment]
show me the link you're using

**Comment by J1NN1K** [comment]
you mean like this https://www.youtube.com/watch?v=8uvG7WVulDI&t=45s or as a picture?

**Comment by Kwoth** [comment]
try removing trailing &t=45s, so `!!q https://www.youtube.com/watch?v=8uvG7WVulDI`

**Comment by J1NN1K** [comment]
hahaha im so stupid, thx now its working^^

**Comment by Kwoth** [comment]
no you're not stupid, our regex was broken. Update to latest version, and it should work in the future properly. Sorry about that
