### ISSUE TITLE
Autohentai

### ISSUE THREAD

**Issue by grannyd15** [Kwoth/NadekoBot#948]
I activated autohentai and i cant find a way to stop it. I dont understand what "argument" means in this context

**Comment by 3941** [comment]
just use ~autohentai alone, to disable.

**Comment by grannyd15** [comment]
Is comma needed?

**Comment by shikhir-arora** [comment]
No just type `~autohentai` to disable. Nothing else.

**Comment by grannyd15** [comment]
Thank you shikhir-arora that worked
