### ISSUE TITLE
Mutes better being logged

### ISSUE THREAD

**Issue by justinkruit** [Kwoth/NadekoBot#949]
Hey,

None of the bans, kicks, mutes or deleted messages being done by people or by commands are being logged in the channel we set it to log everything to. Messages being edited are being saved properly, and I've set the logevents to set that they should be stored.

Edit: For some reason, they now all work again. But I would like that a kick would be better kept in the log, as it is basically not doing it now.

**Comment by Kwoth** [comment]
Kick can't be logged atm.
