### ISSUE TITLE
Starting a hangman game with a non-existent term type

### ISSUE THREAD

**Issue by dnaf** [Kwoth/NadekoBot#956]
Using the `>hangman` command with a term type that doesn't exist causes the following error message:
```
Starting errored: Object reference not set to an instance of an object.
```
Afterwards, the `>hangman` command causes a `Hangman game already running on this channel.` message. The bot doesn't send the actual game message and doesn't seem to respond to any letters.

Seems like a fairly straightforward issue, just not checking to see if the term type exists before actually starting the game?

**Comment by Kwoth** [comment]
If it's true, then i failed, thanks. Will investigate a bit later.
