### ISSUE TITLE
Autoprune old messages

### ISSUE THREAD

**Issue by ibigfire** [Kwoth/NadekoBot#964]
Would be cool if Nadeko could remove messages from a text channel that were older than a specified amount of time.  So if I wanted Nadeko to remove any messages in a channel that were more than a day old, she could do so.  The current prune command seems more geared toward removing just recent messages.

Auto saving the chat as an archive before then would be handy too, but not as necessary.

**Comment by Kwoth** [comment]
nope, sorry
