### ISSUE TITLE
Music Thread Crashed.

### ISSUE THREAD

**Issue by bigtigerx** [Kwoth/NadekoBot#966]
I am new to setting up a bot for discord, but I am pretty sure I am did everything right. I did run through the guide twice. :) Please help me figure this out!

If it matters it is running on a Windows Server 2012 64-bit

> Ready!
> >>COMMAND STARTED
> Cmd: !!queue
> Msg: !!q https://youtu.be/WmOdyunj-X0
> Usr: xxxx
> Srvr: xxxx
> -----
> Music thread crashed.
> System.BadImageFormatException: An attempt was made to load a program with an in
> correct format. (Exception from HRESULT: 0x8007000B)
>    at Discord.Audio.Opus.OpusConverter.UnsafeNativeMethods.CreateEncoder(Int32 F
> s, Int32 channels, Int32 application, OpusError& error)
>    at Discord.Audio.Opus.OpusEncoder..ctor(Int32 samplingRate, Int32 channels, I
> nt32 frameLength, Nullable`1 bitrate, OpusApplication application) in C:\Users\K
> woth\Source\Repos\NadekoBot\discord.net\src\Discord.Net.Audio\Opus\OpusEncoder.c
> s:line 28
>    at Discord.Net.WebSockets.VoiceSocket..ctor(DiscordConfig config, AudioServic
> eConfig audioConfig, JsonSerializer serializer, Logger logger) in C:\Users\Kwoth
> \Source\Repos\NadekoBot\discord.net\src\Discord.Net.Audio\Net\VoiceSocket.cs:lin
> e 70
>    at Discord.Audio.AudioClient..ctor(DiscordClient client, Server server, Int32
>  id) in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net.Audio\
> AudioClient.cs:line 89
>    at Discord.Audio.AudioService.<Join>d__29.MoveNext() in C:\Users\Kwoth\Source
> \Repos\NadekoBot\discord.net\src\Discord.Net.Audio\AudioService.cs:line 92
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
> ification(Task task)
>    at NadekoBot.Modules.Music.Classes.MusicPlayer.<<-ctor>b__61_1>d.MoveNext() i
> n C:\Users\Kwoth\Source\Repos\NadekoBot\NadekoBot\Modules\Music\Classes\MusicCon
> trols.cs:line 106
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at NadekoBot.Modules.Music.Classes.MusicPlayer.<<-ctor>b__61_1>d.MoveNext() i
> n C:\Users\Kwoth\Source\Repos\NadekoBot\NadekoBot\Modules\Music\Classes\MusicCon
> trols.cs:line 138
> Severity: ErrorExceptionMessage: Object reference not set to an instance of an o
> bject.Message: Error handling VOICE_STATE_UPDATE event
>

**Comment by shikhir-arora** [comment]
This is an error with Opus. I am not a Windows user, but it seems to be a problem with the dependency installation, not Nadeko itself. Also the error code seems to bring up 32/64 bit library confusion. 

I do not think that Nadeko supports Windows Server at this time; rather Windows 8+ 64-bit and Linux distributions directly, Docker installs, and macOS.

**Comment by Kwoth** [comment]
this almost always means you're on a 32bit system. 32bit is unsupported.

**Comment by shikhir-arora** [comment]
> this almost always means you're on a 32bit system. 32bit is unsupported.
> If it matters it is running on a Windows Server 2012 64-bit


He does say he's on 64-bit Windows Server 2012, which I am not sure Nadeko supports. It is likely the x86/32-bit or incompatible ffmpeg/OPUS or .NET SDK for that Windows Server 64-bit 2012 (if that is even supported).

**Comment by bigtigerx** [comment]
I just doubled checked, I am running 64-bit. Also It was my understanding that 2012 is the same as Win 8 just more features. The .NET SDK installer is the same for 7, 8, 8.1, 2012, 2012 R2. ffmpeg automatic isntall looked to install correctly, but I will do the manual install.

I have a HP microserver that is always on, it basically runs my Plex server, and hopefully this. I am saying all this as a Network Engineer, that tries to stay away from Windows as much as possible. -_-

**Comment by Kwoth** [comment]
I'm sorry i can't help, if you don't find a solution, you can run it on a linux in a VirtualBox
