### ISSUE TITLE
!!ap seems to be broken

### ISSUE THREAD

**Issue by Kwoth** [Kwoth/NadekoBot#967]
!!ap doesn't appear to be working, tested on 2 updated 1.1 bots - Chloe

**Comment by Kwoth** [comment]
Update to latest, and make sure you have a WORKING google api key with enabled youtube data API.

**Comment by hakufu** [comment]
Still not working. Reported on discord:

!!autoplay not working.
Build # 1.1.4
After song concludes, this is all that shows in the log with !!ap enabled:
https://nekomata.moe/i/B0A9f4.png

Tested with Rikka too, doesn't work with her either.

**Comment by xnaas** [comment]
So people don't have to click the image, format it like this:

`![img](https://nekomata.moe/i/B0A9f4.png)`

Will look like this:
![img](https://nekomata.moe/i/B0A9f4.png)
👍

**Comment by hakufu** [comment]
Sorry bro, just copy pasted my report lol. Thanks.

**Comment by xnaas** [comment]
Same thing for me. Song finishes and then:
    
    17:58:33 Song | read 1744
    17:58:33 Song | read 0

¯\\\_(ツ)_/¯
