### ISSUE TITLE
Language Translator

### ISSUE THREAD

**Issue by GinzaJ** [Kwoth/NadekoBot#97]
Suggestion as the title Says

**Comment by haloes123** [comment]
Translate to spanish plox <3

**Comment by appelemac** [comment]
You mean this to be a command to google translate a certain word into a certain language, or do you want another language for the bot itself?

**Comment by GinzaJ** [comment]
yes

**Comment by appelemac** [comment]
...Yes to what?

**Comment by GinzaJ** [comment]
command to google translate a certain word into a certain language

**Comment by MM4005** [comment]
google translate probably wouldn't be the best option. Google charges for API use of google translate.

**Comment by GinzaJ** [comment]
oh, i see, any other api that's reliable translating? and free =)

**Comment by tg44** [comment]
http://www.programmableweb.com/news/63-translation-apis-bing-google-translate-and-google-ajax-language/2013/01/15

This is a pritty list :)
Worst case we can use this:
http://www.codeproject.com/Articles/12711/Google-Translator

**Comment by GinzaJ** [comment]
bing translator api seems to be my second thought

**Comment by tg44** [comment]
what would the actual commands look like?

sth like:
~trans so much pain English>French
Or
~transl English Franch
~trans so much pain
Or both of the above?

Any syntax idea?

**Comment by GinzaJ** [comment]
~trans English>French seems good

**Comment by Kwoth** [comment]
^ yes i like that

**Comment by tg44** [comment]
#155 

Google theorically can ban you if your bot using 1 ip and they get more then 500k char/day to translate!

**Comment by Kwoth** [comment]
thanks to @tg44 who did this

`~trans en>fr Hello, how are you` is the way to use it
