### ISSUE TITLE
Bring back Google Image Search + Imgur and Google Image Search in one command?

### ISSUE THREAD

**Issue by AlphaXVIV** [Kwoth/NadekoBot#970]
Just to make it more organized (or more messy, but less confusing) I'm just gonna make another topic rather than replying to #400, feel free to merge this I suppose*

In the recent update I noticed that ~i and ~ir is replaced by ~img and ~rimg, but a bummer is that it completely replaces the image search to exclusively Imgur. I have few issues with this:

1. Imgur is blocked in my country (for some reason, don't ask)
2. The image search is much less broad, and not all keywords will produce any result
3. The image results can be quite lame (Subjective), and sometimes even irrelevant to what we were searching

So, I want the Google Image Search command to be back in one form or another. I do know that Google Image Search is only limited to max 100 queries (not including other queries) as the Custom Search API said, but people in my server doesn't seem to mind that and just waited out until the reset happens. 

However, I also do have an idea of combining both Google Image Search and Imgur into one command, if possible. My idea was to use Google Image Search until you run out of quota, and until that quota resets it only searches for Imgur images. Again, if possible.

Thanks in advance!

*I'm new to Github, sorry for the formatting mess

**Comment by 3941** [comment]
I agree. At least give us the old commands back please.
That's zero effort, and the google search is just so much better.

**Comment by xnaas** [comment]
The imgur search seems to suck a lot. I realize that's on imgur and not the bot, but still worth pointing out.

**Comment by Kwoth** [comment]
Yeah i'm going to do this, i didn't like imgur either, but that's what people wanted. Imgur image search sucks and is full of memes, not relevant images. Gonna use google image search until 403, when it hits 403, it will use imgur.

**Comment by xnaas** [comment]
When it starts using imgur instead of Google, can you have it say something at the top of those embeds about it? Not a requirement, but would certainly help alleviate confusion and let people know why the searches randomly drop from relevant to utter shit. 😛 

Additionally, I don't know if this is something you can fix:
![img](http://i.imgur.com/aesuJ5y.png)

**Comment by xnaas** [comment]
Additional note: Please change it back to `~i` and `~ir`. 😄

**Comment by xnaas** [comment]
`!img` seems to "fallback" to imgur immediately, for every search. `!rimg` is working fine.

Also please bring back `~i` and `~ir` as aliases. 😛

**Comment by xnaas** [comment]
Alternatively, having separate commands for Imgur and Google image searches would be nice, too. Whatever works. 😛

**Comment by xnaas** [comment]
Upon further testing, it seems highly inconsistent in what it chooses to use. ¯\\\_(ツ)_/¯

**Comment by xnaas** [comment]
After another 5 hours of use, I would like to opt out of using Imgur at all. This is the worst API with the worst/most useless selection of images, ever. 😛 I know some people wanted it, but this is worse than having *nothing*. ¯\\\_(ツ)_/¯
