### ISSUE TITLE
The auto assign role command is not running.

### ISSUE THREAD

**Issue by DaYWhiTe** [Kwoth/NadekoBot#976]
He does not have automatic role assignment even though he has all the authority

![image](https://cloud.githubusercontent.com/assets/21060067/21935912/ede7a9fc-d9b7-11e6-9c4f-a52a95d0acd0.png)

**Comment by DaYWhiTe** [comment]
version 1.1.0-beta

**Comment by Kwoth** [comment]
Give your bot administrator permissions. Make sure you're editing the right role. Move bot's role to the top. I tested it, and it works. You're missing some permission.
