### ISSUE TITLE
Starting at boot, go straight to auto-restart

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#977]
So, I used to use a shortcut to `NadekoAutoRun.bat` in `shell:startup` to have Nadeko start at boot in auto restart mode. However, some changes were made to the batch file and it requires you to run `NadekoInstaller.bat` to re-create that file any time you exit `NadekoAutoRun.bat` with the option `4`.

> Long path for `shell:startup`: **C:\Users\<username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup**

Basically, I want to launch `NadekoAutoRun.bat` at boot with option 4 to go to autorun and then option 3 in the `NadekoAutoRun.bat`.

What's the best way to go about this? 😛

**Comment by xnaas** [comment]
Sorry if the above is worded poorly. It's 1:30 in the morning after a long work week and too much Diablo 3 tonight. 😄

**Comment by Kwoth** [comment]
your best option is to contact Phildo on discord. He is running nadeko as a service to have it run when the server starts up

**Comment by xnaas** [comment]
Hmm...I guess I could switch back to having it run as a service. Just makes troubleshooting annoying when you can't see the console. 😛
