### ISSUE TITLE
Music player issue

### ISSUE THREAD

**Issue by Vanillaah** [Kwoth/NadekoBot#978]
The first song plays with sound, the second (and any other after) play without sound.
I have restarted bot multiple times but this happens every single time.

09:39:25 CommandHandler | Command Executed after 1,6617374s
        User: Aphiliae#7764
        Server: Sword Art Online
        Channel: music
        Message: !!q feint sky dance
09:39:27 Song | Buffering successfull
09:39:27 Song | Prebuffering successfully completed in 00:00:02.1626372
Buffering done.
09:44:43 Song | read 3208
09:44:43 Song | read 0
09:46:25 CommandHandler | Command Executed after 0,8847998s
        User: Aphiliae#7764
        Server: Sword Art Online
        Channel: music
        Message: !!q https://www.youtube.com/watch?v=x9WpVoAC3tk
09:46:27 Song | Buffering successfull
09:46:27 Song | Prebuffering successfully completed in 00:00:02.4663898
Buffering done.
09:49:42 Song | read 1500
09:49:42 Song | read 0

**Comment by Vanillaah** [comment]
- i do run on latest build -

**Comment by shikhir-arora** [comment]
I'm having trouble replicating your issue. Can you try with `!!pl <some YouTube playlist link or keywords>` and see if the second and further songs work? Also try queue with keywords. Is it happening with anything you do, or only specifics? If you have SoundCloud enabled with the API, also try that.

**Comment by Kwoth** [comment]
Can't reproduce, it's something on your side.
