### ISSUE TITLE
the offline pm broke.

### ISSUE THREAD

**Issue by deathlegacy** [Kwoth/NadekoBot#98]
the user is online, but still it says its offline and send pm. 

![capture](https://cloud.githubusercontent.com/assets/8214944/13837235/1341cabe-ec44-11e5-895a-2107bc944abd.JPG)

**Comment by Kwoth** [comment]
happens sometimes, not my fault. Underlying lib is showing them as offline ;[

**Comment by Kwoth** [comment]
yeah this will be fixed when bot gets upgraded to 1.0 (when its out), until then, either don't use it or expect it to screw up sometime ;p
