### ISSUE TITLE
$betflip, $betroll award 0 flowers

### ISSUE THREAD

**Issue by xMetaloid** [Kwoth/NadekoBot#980]
The command is awarding 0 flowers for winning and taking flowers bet as well.

**Comment by Kwoth** [comment]
You need to download and install sqlite browser from here http://sqlitebrowser.org/ Open the database with it, click on Browse Data, Change to BotConfig table, and all the way to the right you will see the modifiers you can change. After you make the changes you want, click on "write changes" at the top. Restart the bot.

Database can be found here:
NadekoBot\src\NadekoBot\bin\Release\netcoreapp1.0\data\NadekoBot.db

**Comment by Kwoth** [comment]
![image](https://cloud.githubusercontent.com/assets/2537696/21960025/5f073b02-dada-11e6-801d-a8df053c880a.png)
