### ISSUE TITLE
Running NadekoInstaller.bat causes explorer to hang

### ISSUE THREAD

**Issue by theoddball** [Kwoth/NadekoBot#983]
![gif](http://i.oddball.tf/3OPEe.gif)

**Comment by samdivaio** [comment]
Restart Explorer, Reboot PC its tested working.
Not sure whats the issue try running `cmd.exe` and launching `NadekoInstaller.bat` through it.

**Comment by Kwoth** [comment]
This has to be something on your side. Nobody ever reported this before and after you. I thought it had something to do with the new piece of code sam added (ffmpeg installer) but nope.
