### ISSUE TITLE
Feature Request - Auto DJ

### ISSUE THREAD

**Issue by Kronos25** [Kwoth/NadekoBot#984]
A command that when executed, takes a number of saved playlists like 5~10, queue them and then automatically shuffle them. So this way someone can use just one command to generate a random playlist without loading specific ones.

This would be particularly useful when a channel doesn't has song requests and people just want to chill with songs on the background.

Example:

!!auto 5 (queues5 random playlists, shuffle and play them)

**Comment by Kwoth** [comment]
We have a similar suggestion on discord suggestions channel.

Users will be able to set a playlist which will be looped through when there are no queued songs.

There won't be a command to load X number of saved playlists.
