### ISSUE TITLE
Bot drops connection

### ISSUE THREAD

**Issue by boredgamerz** [Kwoth/NadekoBot#986]
So lately I've having this issue that the bot just disconnects, even if it's playing music. It can just randomly drop out (this has happened with another friend of mine as well on a different network and location) I've tried to reinstall the server, deleting every file that I know of then trying to install nadeko on another drive to be sure.  the error messages I get are the following:

`Severity: ErrorExceptionMessage: Connection lostMessage: Disconnected
l
Severity: WarningExceptionMessage: -Message: Unknown Opcode: 8
Severity: ErrorExceptionMessage: Connection lostMessage: Disconnected
Severity: WarningExceptionMessage: -Message: Unknown Opcode: 8`
not sure if this is a known issue for you?

**Comment by Kwoth** [comment]
Update to 1.1. http://nadekobot.readthedocs.io/en/latest/guides/Upgrading%20Guide/

**Comment by boredgamerz** [comment]
Tried running the .migratedata without any reaction(neither in the console), haven't disconnected so I guess it fixed itm but still getting the severity warning

**Comment by Kwoth** [comment]
you didn't read the migration guide. .migratedata doesn't upgrade your bot. You have to follow the guide from the start, it's a new program.

**Comment by boredgamerz** [comment]
My bad. I did read it, but I'm just rly slow
