### ISSUE TITLE
Autohentai sometimes just doesn't do anything

### ISSUE THREAD

**Issue by TheSarali** [Kwoth/NadekoBot#990]
I used the tag "nipples" as a test, which is a tag all on 4 sites autohentai seems to pull from, and it would still sometimes just not work.  To test I set it to 300 seconds in between posts, giving it plenty of time since it is on a slow server and sometimes things take up to 20 seconds to register or so, and it just skips out sometimes.

When it doesn't work, it should at least give a reason why, so as to not just leave us lost as to why it just decided to not do anything.  But I don't understand why it ever wouldn't work when I give it such a simple tag anyway.

**Comment by Kwoth** [comment]
I tested it with a couple of tags and it just works. It simply uses the ~hentai command every x seconds. Hentai shouldn't work for you either with the tag you pick. I'm assuming it's your server failing to query the api.
