### ISSUE TITLE
Can't .sinfo -- 400, bad request

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#991]
15:51:30 CommandHandler | Command Errored after 0.078s
        User: xnaas#7485 [83983966608068608]
        Server: Action Sack [141249302260350977]
        Channel: spam [226086096675667969]
        Message: .sinfo
        Error: The server responded with error 400 (BadRequest)

Has been happening for a few bot versions now. `.cinfo` and `.uinfo` both work fine.

**Comment by Kwoth** [comment]
just tested, sinfo works fine. However, does your server have an icon, i see that as  being the only problem that might arise?

**Comment by xnaas** [comment]
It does indeed have an icon.

**Comment by Kwoth** [comment]
confirmed. Sinfo not working for some people.

**Comment by xnaas** [comment]
Let me know if there's any other info I can get you to try and figure it out.

**Comment by Kwoth** [comment]
I think it's due to huge number of emojis you have on your server.

**Comment by Kwoth** [comment]
Pushed a fix, i'm not sure what's the fine number of emojis to show. I tried 30. Tell me if it works.

**Comment by hakufu** [comment]
Still getting the error here mate. Just updated and tested it.

"Error: The server responded with error 400 (BadRequest)"

Josh#5558 on discord.

**Comment by xnaas** [comment]
Confirmed fixed. 👍
