### ISSUE TITLE
Help my bot won't abide to some command

### ISSUE THREAD

**Issue by JoelCastillo17** [Kwoth/NadekoBot#992]
So,I just begins hosting a bot using nadeko's source the music and some other commands are fine.But command like ~hentaibomb or cleverbot won't work for some reason

**Comment by Kwoth** [comment]
both require manage messages permission I believe. It's on your side. They work correctly.

**Comment by JoelCastillo17** [comment]
Well do i just give the bot a role or i have to do something else?

**Comment by Kwoth** [comment]
the person who is running the command. Also make sure you've enabled nsfw module on your server.

**Comment by JoelCastillo17** [comment]
Well i tried the -h nsfw and the hentaibomb isn't on the list and same goes for the clever bot on the games list for some reason

**Comment by JoelCastillo17** [comment]
And when i type >cleverbot nothing happens
