### ISSUE TITLE
[Feature request] Adding a new moderation command

### ISSUE THREAD

**Issue by deivedux** [Kwoth/NadekoBot#993]
I have this idea to add a `.moderate` command to prevent people from texting in that text channel. After issuing that command, Nadeko replies with something like `This channel is being moderated!` and no one is allowed to text in that channel, but people with admin permissions are also moderated by bot deleting their messages rigt as they are sent. Altho, I'm aware that using that in public bot woud be very risky as a lot of people would use that and the bot will break every 5 minutes, so at first I recommend adding it as a **Bot Owner only** command. Trust me, that feature could be very useful for serious servers, especially for people who host their own bots ;)

**Comment by Nitix** [comment]
I don't see any exemple why it should be done by the bot, you can use discord permissions directly.

**Comment by deivedux** [comment]
It is always recommended to do that publicly with bot commands. For example, if I'll just do directly via channel permissions, other people will get very lost on why they suddently can't send messages, while the bot warns everyone straight away.
That's just my idea tho, I thought that it will end up being something very useful at the end.

**Comment by Nitix** [comment]
You can say that this channel is now for read only yourself ¯\\_(ツ)\_/¯.

Maybe in some scenarios this can be useful, but If we didn't know this scenario, we can't make a viable solution.

**Comment by deivedux** [comment]
Well then why is there even a `.mute` command then? I can just manually give the command to a person since it's easier 😆 

Anyway, my idea was, that if the channel becomes really spammy, on purpose, I can make sure that the bot is taking care of it meanwhile I write in the same channel with a request to stop the spam and use `.unmoderate` after a while to see if the spam stopped.

Also, if you'll keep thinking about it your way, then ofc there is no way that you will like that idea, just try to think of how useful it might end up.

**Comment by Kwoth** [comment]
Thanks for the suggestion but no. Too specific.
