### ISSUE TITLE
!!mv not found

### ISSUE THREAD

**Issue by Taknok** [Kwoth/NadekoBot#994]
Hello,

People on my server noticed me that `!!mv` didn't work and after check it was the case. I tried to find the origin of the bug, and when I run on my computer localy i have the same issue. The `move_cmd` is well definited in CommandString.resx so I don't know ...
I hope it's just a bug on my side, but if anyone could check too :)

![capture](https://cloud.githubusercontent.com/assets/12498020/22179778/bb01f202-e05d-11e6-8963-885bbee5178b.PNG)

**Comment by Kwoth** [comment]
!!mv is removed a while back due to weird behaviour. You can drag the bot around and it should work fine from what i tested.

**Comment by Taknok** [comment]
Ok, it's quite inconvenient for people who haven't the autorisation, but anyway.
Could you please considerate removing it from the doc ?
