### ISSUE TITLE
Cleverbot not working

### ISSUE THREAD

**Issue by JillVa11a** [Kwoth/NadekoBot#995]
I can't toggle on Cleverbot 
P/s:Im using my hosting my own bot btw

**Comment by Kwoth** [comment]
1. make sure you're using the correct prefix (type -cmds Games)
2. You must have the manage messages permission in that server
3. If you edited the source i can't help you
4. We test cleverbot every day and it is working. And toggling properly.

**Comment by JillVa11a** [comment]
<8ball         []      <choose        []      <gencurrency   [<gc]   
<leet          []      <linux         []      <pick          []      
<plant         []      <poll          []      <pollend       []      
<rps           []      <t             []      <tl            []      
<tq            []      <typeadd       []      <typestart     []      
<typestop      []      
I did change the prefix but that's all

**Comment by Kwoth** [comment]
Update to 1.1.3 atleast. You might be using old installer. revisit the guide.

**Comment by JillVa11a** [comment]
I actually install this manually and Im currently using the latest release NadekoBot v0.99.10

**Comment by Kwoth** [comment]
You must be on 1.1.3. Revisit the guide http://nadekobot.readthedocs.io/en/latest/

**Comment by JillVa11a** [comment]
Im on window 7 so i don't know it'll work or not :|

**Comment by JillVa11a** [comment]
after i updated the bot and Run the bot normally the dotnet crashed

**Comment by Kwoth** [comment]
windows 8+, if not, you either user virtualbox with linux or newer windows or you're stuck on 0.9.x for now
