### ISSUE TITLE
Cant install or start

### ISSUE THREAD

**Issue by asanonisshoku** [Kwoth/NadekoBot#998]
First it was this with installing
Cloning into 'NadekoBot'...
remote: Counting objects: 421, done.
remote: Compressing objects: 100% (397/397), done.
remote: Total 421 (delta 71), reused 163 (delta 15), pack-reused 0
Receiving objects: 100% (421/421), 3.18 MiB | 0 bytes/s, done.
Resolving deltas: 100% (71/71), done.
Checking connectivity... done.
Submodule 'Discord.Net' (https://github.com/Kwoth/Discord.Net) registered for path 'Discord.Net'
Cloning into 'C:/Users/William/Desktop/Nadeko/NadekoInstall_Temp/NadekoBot/Discord.Net'...
error: no such remote ref 58766448d79ac9adec228f341f258aa262a3f278
Fetched in submodule path 'Discord.Net', but it did not contain 58766448d79ac9adec228f341f258aa262a3f278. Direct fetching of that commit failed.

now its this when trying to run
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(20,25): error NU1001: The dependency AngleSharp >= 0.9.9 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(21,27): error NU1001: The dependency VideoLibrary >= 1.3.4 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(22,28): error NU1001: The dependency CoreCLR-NCalc >= 2.1.2 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(23,47): error NU1001: The dependency Google.Apis.Urlshortener.v1 >= 1.19.0.138 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(24,42): error NU1001: The dependency Google.Apis.YouTube.v3 >= 1.20.0.701 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(25,47): error NU1001: The dependency Google.Apis.Customsearch.v1 >= 1.20.0.466 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(26,38): error NU1001: The dependency ImageSharp >= 1.0.0-alpha-000079 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(27,44): error NU1001: The dependency Microsoft.EntityFrameworkCore >= 1.1.0 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(28,51): error NU1001: The dependency Microsoft.EntityFrameworkCore.Design >= 1.1.0 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(29,51): error NU1001: The dependency Microsoft.EntityFrameworkCore.Sqlite >= 1.1.0 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(30,49): error NU1001: The dependency Microsoft.Extensions.Configuration >= 1.1.0 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(31,70): error NU1001: The dependency Microsoft.Extensions.Configuration.EnvironmentVariables >= 1.1.0 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(32,54): error NU1001: The dependency Microsoft.Extensions.Configuration.Json >= 1.1.0 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(33,55): error NU1001: The dependency Microsoft.Extensions.DependencyInjection >= 1.1.0 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(35,56): error NU1001: The dependency Microsoft.Extensions.PlatformAbstractions >= 1.1.0 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(40,36): error NU1001: The dependency Newtonsoft.Json >= 9.0.2-beta1 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(41,26): error NU1001: The dependency NLog >= 5.0.0-beta03 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(42,43): error NU1001: The dependency System.Diagnostics.Contracts >= 4.3.0 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(43,31): error NU1001: The dependency System.Xml.XPath >= 4.3.0 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(36,30): error NU1001: The dependency System.Xml.XPath >= 4.3.0 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(43,31): error NU1001: The dependency System.Xml.XPath >= 4.0.1 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(36,30): error NU1001: The dependency System.Xml.XPath >= 4.0.1 could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(44,29): error NU1001: The dependency Discord.Net.Commands >= 1.0.0-* could not be resolved.
C:\Users\William\Desktop\Nadeko\NadekoBot\src\NadekoBot\project.json(48,30): error NU1001: The dependency Discord.Net.WebSocket >= 1.0.0-* could not be resolved.

Any help apprecated followed the guide to the t.

**Comment by Nitix** [comment]
Did you run NadekoInstaller ?

**Comment by asanonisshoku** [comment]
Yes this where its all coming from.

**Comment by xnaas** [comment]
Wow that's a mess to try and read. 😛 You've followed [the guide](http://nadekobot.readthedocs.io/en/latest/guides/Windows%20Guide/) perfectly?

**Comment by Nitix** [comment]
Try relaunching NadekoInstaller.bat

Error comes from :

> error: no such remote ref 58766448d79ac9adec228f341f258aa262a3f278
Fetched in submodule path 'Discord.Net', but it did not contain 58766448d79ac9adec228f341f258aa262a3f278. Direct fetching of that commit failed.

**Comment by asanonisshoku** [comment]
To the T

**Comment by asanonisshoku** [comment]
Relaunched and reinstalled 3 time same result.

**Comment by Nitix** [comment]
I don't see any `T` in the [guide](https://nadekobot.readthedocs.io/en/latest/guides/Windows%20Guide/). 

But this isn't the error, do you have a proxy or something like that ? This is strange the [commit 58766448d79ac9adec228f341f258aa262a3f278](https://github.com/Kwoth/Discord.Net/tree/58766448d79ac9adec228f341f258aa262a3f278) does exist.

**Comment by asanonisshoku** [comment]
Nothing of the sort just xfinity.

**Comment by samdivaio** [comment]
You are installing Stable I believe, try Latest build and dont forget to run Installer as Admin.

**Comment by asanonisshoku** [comment]
Same thing with both.

**Comment by samdivaio** [comment]
Install it on a new folder/directory.

**Comment by asanonisshoku** [comment]
Nope, about ready to pull my hair out.

**Comment by xnaas** [comment]
I assume you've rebooted recently. Amazing how much shit that fixes. 😛 Also, this *is* on Windows, right?

**Comment by asanonisshoku** [comment]
Yes Window's 10 Ill try rebooting now to see if that helps.

**Comment by xnaas** [comment]
After a reboot, I'd wipe out the entire folder you've made for NadekoBot and start from scratch, just to be safe.

**Comment by asanonisshoku** [comment]
Nope did not help restarted the guide from top

**Comment by samdivaio** [comment]
It sounds like your ip/dns is getting bugged. Try it with an VPN on your PC, or get a linux VPS.

**Comment by asanonisshoku** [comment]
I'll just use the public version at this point.

**Comment by samdivaio** [comment]
If you try again, can you remove git and reinstall it just to make sure git has nothing to do with it.
If it fails, I'd suggest getting the bot manually, like zips from branches.

**Comment by Kwoth** [comment]
Getting zip would yield same result for him. (since submodules are not included in the zip) 

He did something wrong. Reinstalling git would maybe help. It can't find the submodule commit which obviously exists, so it might be some sort of cache problem.
